Link to cluster limits page to clarify max-pods-per-nodes from core concepts
openshift/openshift-docs pull request #10418
Opened 2018-06-26 01:49 UTC by bysnupy

The recommended pods-per-node maximum number is not consistent with our cluster limits page and nowhere is the details why 110 pods-per-node maximum is recommended.

So fix this by creating a link to the official limits table in the scaling guide.

2018-06-26 14:45 UTC, kalexand-rh requested changes
@bysnupy, please update the text and squash your commits.
Also, thanks for indicating that this change applies to 3.7 and 3.9, too. Next time, please don't open the PRs against other branches. Instead, add version tags to the PR that you open against master. :)

2018-06-26 14:45 UTC, kalexand-rh commented on architecture/core_concepts/pods_and_services.adoc
> +See the
I'd say:
```
For the maximum number of pods per {project-title} node host, see the
xref:../../scaling_performance/cluster_limits.adoc#scaling-performance-current-cluster-limits[Cluster
Limits].
```

2018-06-27 00:12 UTC, bysnupy commented
@kalexand-rh Thank you for your reviewing and advice for the labeling. I'll do it next time.
Additionally, I've also opened https://bugzilla.redhat.com/show_bug.cgi?id=1595059 BZ about this PR.

2018-06-29 12:47 UTC, kalexand-rh commented
@openshift/team-documentation PTAL

2018-06-29 13:32 UTC, ahardin-rh commented
LGTM! I assume that this will also apply to OCP 3.10.

2018-06-29 13:33 UTC, kalexand-rh commented
Thanks @ahardin-rh! That's a good point. 

@bysnupy, can I apply this change to 3.10 as well?

Also, will you please squash your commits down to 1?

2018-06-29 13:34 UTC, kalexand-rh approved these changes

2018-06-29 15:00 UTC, bysnupy commented
@kalexand-rh Sure! No problem.

2018-06-30 02:19 UTC, bysnupy commented
@kalexand-rh 
I'm completed squashing my commits, and I tried whether I can add additional or new label to the PR, but I couldn't. I think I don't have the permission about it.
Thank you :)

2018-07-02 12:31 UTC, kalexand-rh commented
Thank you, @bysnupy! I've added the label and am merging. :)

2018-07-02 12:31 UTC, merged

2018-07-02 12:31 UTC, kalexand-rh commented
/cherrypick enterprise-3.10

2018-07-02 12:31 UTC, kalexand-rh commented
/cherrypick enterprise-3.9

2018-07-02 12:31 UTC, kalexand-rh commented
/cherrypick enterprise-3.7

2018-07-02 14:15 UTC, kalexand-rh commented
The linked topic doesn't exist in the online or dedicated collections, so I'm getting more information about the requirements for those OpenShift versions. I've opened a follow-up PR to finish the change.