Added Network Policy content to Dedicated
openshift/openshift-docs pull request #10604
Opened 2018-07-03 15:25 UTC by ahardin-rh

https://trello.com/c/KtXebjFv/1132-3-dedicated-enable-dedicated-clusters-to-be-configured-with-networkpolicy-plugin

https://bugzilla.redhat.com/show_bug.cgi?id=1580507

2018-07-12 16:54 UTC, ahardin-rh commented
@wgordon17 @abhgupta PTAL. Thanks!

2018-07-17 16:25 UTC, wgordon17 requested changes
Link at line #21 not available for dedicated
Lines #94 - #269 should be removed from dedicated docs
Note on line #242 can then be removed
The endif on line 1168 should be moved to 1241

2018-07-26 19:18 UTC, wgordon17 commented
Exclude:

- Disabling Host Name Collision Prevention For Routes and Ingress Objects
- Setting up the HAProxy router to accept ingress objects
- Controlling Egress Traffic (exclude header text, but be sure to still include `Using an Egress Firewall to Limit Access to External Resources`)
  - Using an Egress Router to Allow External Resources to Recognize Pod Traffic
    - DEPLOYING AN EGRESS ROUTER POD IN REDIRECT MODE
    - REDIRECTING TO MULTIPLE DESTINATIONS
    - USING A CONFIGMAP TO SPECIFY EGRESS_DESTINATION
    - DEPLOYING AN EGRESS ROUTER HTTP PROXY POD
    - DEPLOYING AN EGRESS ROUTER DNS PROXY POD
    - ENABLING FAILOVER FOR EGRESS ROUTER PODS
  - Using iptables Rules to Limit Access to External Resources
- Enabling Static IPs for External Project Traffic

2018-07-26 23:03 UTC, wgordon17 commented
LGTM

2018-07-27 07:49 UTC, yasun1 commented
In the preview document, I found:

1. The link for` configured to use the ovs-networkpolicy plugin` is 404.
2. The content of the link for` Modifying the Template for New Projects` is missed.
3. Miss link url for `the ovs-multitenant SDN plugin` .

2018-07-30 21:02 UTC, ahardin-rh commented
@yasun1 Thanks. I fixed the issues.

2018-07-30 21:03 UTC, merged

2018-07-30 21:10 UTC, ahardin-rh commented
/cherrypick enterprise-3.9

2018-08-09 02:50 UTC, vikram-redhat commented
@ahardin-rh - I think this needs to be CP'ed to 3.11 as well.

2018-08-09 20:41 UTC, ahardin-rh commented
@vikram-redhat Thanks. I did so here, but looks like the content was already applied:
https://github.com/openshift/openshift-docs/pull/11485
I am currently checking the content, however, as there may be some issues with conditionals.