Applied edits to Kuryr content for 3.10
openshift/openshift-docs pull request #10741
Opened 2018-07-10 18:35 UTC by ahardin-rh

Follow-up edits to https://github.com/openshift/openshift-docs/pull/10739 and https://github.com/openshift/openshift-docs/pull/5845 per [review feedback.](https://docs.google.com/document/d/1WcuZLml2tJsMKY0FGy4pzSly84Mdsztqu8omdN6O05E/edit?usp=sharing)

2018-07-11 10:22 UTC, dulek commented
Actually the behavior described in https://github.com/openshift/openshift-docs/pull/8906 had changed, as we've discovered a bug with the previous approach. My bad that I haven't updated the PR. Below is the proposed update of paragraphs in line 46-55:

> {product-title} CNI will call Kuryr CNI script every time a new pod is spawned
> on or deleted from an {product-title} host. The script fetches the container ID of
> the local kuryr-cni from Docker API and executes Kuryr CNI plug-in binary through
> `docker exec` passing all the CNI call arguments. The plug-in then calls
> kuryr-daemon over local HTTP socket, again passing all the parameters.

2018-07-12 14:30 UTC, eurijon commented on architecture/topics/kuryr.adoc
> +  link:https://docs.openstack.org/octavia/latest/[Octavia].
Hey, there are two more OpenStack requirements to be added to the list:
 - Trunk Ports extension must be enabled
 - Neutron must use the Open vSwitch firewall driver
(taken from https://github.com/openshift/openshift-ansible/blob/master/playbooks/openstack/configuration.md#openstack-requirements)

2018-07-12 14:38 UTC, eurijon commented
In line 26 of install_config/configuring_kuryrsdn.adoc:
> are installed as pods on {product-title} in the `kube-system` namespace:

it should say `openshift-infra` instead of `kube-system`.

2018-07-12 20:04 UTC, ahardin-rh commented
@dulek @eurijon Updates complete. Thanks again!

2018-07-13 07:26 UTC, dulek requested changes

2018-07-13 16:58 UTC, ahardin-rh commented
I updated the output per Jon and addressed the latest feedback from @dulek

2018-07-23 14:19 UTC, ahardin-rh commented
@dulek @eurijon Any more updates for this, or is this okay to merge? Thanks!

cc @vikram-redhat

2018-07-23 14:21 UTC, eurijon commented
Ok from my side

2018-07-23 15:20 UTC, ahardin-rh commented
@eurijon I'm going to go ahead and merge this then. If further edits are needed, we can address those in a follow-up PR. Thanks!

2018-07-23 15:20 UTC, merged

2018-07-23 15:31 UTC, ahardin-rh commented
/cherrypick enterprise-3.10