add docs comparing oc and kubectl
openshift/openshift-docs pull request #10842
Opened 2018-07-16 22:14 UTC by juanvallejo

Adds documentation explaining the main differences between `oc` and `kubectl`.
Trello card: https://trello.com/c/BumbnGUY

cc @mfojtik @liggitt @derekwaynecarr

2018-07-17 14:59 UTC, mfojtik commented on cli_reference/differences_oc_kubectl.adoc
> +The `kubectl` binary is included alongside your download of the command line client-tools.
it is not :-) all the recent tars we publish on github does no have symlink nor the copy of oc inside. I would state that copying it manually from oc binary is the primary form of delivery :-)

2018-07-17 15:03 UTC, juanvallejo commented
cc @openshift/team-documentation

2018-07-17 16:12 UTC, mfojtik commented
/lgtm

2018-07-18 01:38 UTC, vikram-redhat commented
@juanvallejo thanks for this PR. Are we adding kubectl from 3.11 onwards or would this work in 3.10 docs as well.

2018-07-18 14:38 UTC, juanvallejo commented
@vikram-redhat As it currently stands, copying `oc` and renaming it `kubectl` would also work for the 3.10 docs - but based on @derekwaynecarr 's [comment](https://github.com/openshift/openshift-docs/pull/10842#discussion_r203149546), it looks like consensus still has to be reached as to how `kubectl` will ultimately be obtained by users

2018-07-19 00:48 UTC, vikram-redhat commented
@juanvallejo ok I will add a WIP on this PR then.

2018-07-25 11:49 UTC, soltysh requested changes

2018-07-25 11:49 UTC, soltysh commented on cli_reference/differences_oc_kubectl.adoc
> +Although there are several similarities between these two clients, this guide will
s/guide will aim/guide's aim is to

2018-07-25 11:49 UTC, soltysh commented on cli_reference/differences_oc_kubectl.adoc
> +The `oc` binary offers full support for all of the features offered by an {product-title} cluster.
Stronger message will be if we write something like: 

oc binary provides the exact same capabilities as kubectl binary, on top of that it's extended to natively support {product-title} features such as:

2018-07-25 11:49 UTC, soltysh commented on cli_reference/differences_oc_kubectl.adoc
> +These are resources specific to {product-title}, and not native to Kubernetes.
s/not native/not available

2018-07-25 11:49 UTC, soltysh commented on cli_reference/differences_oc_kubectl.adoc
> +into a cluster based on specified configuration. See
command which allows authentication ~~into a cluster based on specified configuration.~~ against a cluster.

2018-07-25 11:49 UTC, soltysh commented on cli_reference/differences_oc_kubectl.adoc
> +- Additional commands, such as `new-app`, which make it easier to get new applications started using existing source code.
existing source code or pre-built images.

2018-07-25 11:49 UTC, soltysh commented on cli_reference/differences_oc_kubectl.adoc
> +to `oc` in order to gain the added functionality mentioned in the previous section.
The move from `kubectl` to `oc` should be additionally simple that `oc` is built on top of `kubectl` which means that all that is required is to change the binary name from `kubectl` to `oc`.

2018-08-14 19:11 UTC, juanvallejo commented on cli_reference/differences_oc_kubectl.adoc
> +A copy of `kubectl` is included with the {product-title} command line interface (CLI).
Thanks, updated to `A copy of kubectl is included in {product-title} command line interface`

2018-08-14 19:18 UTC, juanvallejo commented
@soltysh thanks, comments addressed. Additionally, I have removed the section that mentions "obtaining a kubectl binary by renaming the existing `oc` binary"

2018-08-15 09:28 UTC, soltysh approved these changes
One final nit and this lgtm.

2018-08-15 09:28 UTC, soltysh commented on cli_reference/differences_oc_kubectl.adoc
> += Why Use oc over kubectl?
Why use <- lowercase use

2018-08-15 18:58 UTC, juanvallejo commented
@soltysh thanks, review comment addressed

2018-08-16 15:16 UTC, soltysh commented
@adellape ptal

2018-08-17 05:25 UTC, vikram-redhat commented
@ahardin-rh PTAL.

@xingxingxia or @xiaocwan - can you please provide QE review?

2018-08-17 05:50 UTC, xingxingxia commented
> Using OC
> Using Kubectl

LGTM, only except the letters case for them similar to https://github.com/openshift/openshift-docs/pull/10842#discussion_r205062071

2018-08-17 13:31 UTC, juanvallejo commented
@xingxingxia thanks, fixed

2018-08-21 19:19 UTC, closed without merging