add some warnings around changing Pod Templates from both Jenkins con…
openshift/openshift-docs pull request #10879
Opened 2018-07-18 15:52 UTC by gabemontero

…sole and OpenShift resources monitored by sync plugin

Fixes https://github.com/openshift/jenkins-sync-plugin/issues/246

@bparees @bmcelvee ptal

2018-07-18 17:50 UTC, bparees requested changes

2018-07-18 17:50 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +Keep in mind that after the Pod Template is created, if you log into the Jenkins
s/Keep in mind that/  (redundant since it's already going to be marked as a note)

2018-07-18 17:50 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +on the OpenShift Sync plug-in detects that the image associated with the
s/on//

2018-07-18 17:50 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +====
same edits here

2018-07-18 18:16 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +[NOTE]
yes it does

2018-07-18 18:56 UTC, bparees approved these changes

2018-07-18 19:17 UTC, gabemontero commented
@bmcelvee - while the function around scanning config maps and image streams dates back to 3.6, the behavior as pecisely worded only applies to 3.11

Warnings are applicable to the earlier versions, but the check to replace what is in Jenkins is less stringent ... basically, changes of any sort to the IS or CM on the OpenShift side will cause a replacement of what exists on the Jenkins side.

If you want to backport a modified version to the earlier releases, that is fine, but given the activity with this, I'm not overly concerned if it does not get backported.  I'll defer to you here.

2018-07-24 14:17 UTC, bmcelvee commented
Let's do 3.11. 
Since this is a minor change, I don't think it needs QE.

2018-07-25 18:46 UTC, merged