Bug 1566438, added suggestion to validate storage before upgrading
openshift/openshift-docs pull request #11484
Opened 2018-08-09 20:11 UTC by ahardin-rh

https://bugzilla.redhat.com/show_bug.cgi?id=1566438

@sdodson PTAL. Thanks!

2018-08-10 15:34 UTC, sdodson requested changes
needs --confirm flag in < 3.10

Also, this pre-upgrade check is a good idea to do in all upgrades, not just limited to 3.7, lets add it to 3.9 and 3.10 too.

2018-08-10 15:34 UTC, sdodson commented on upgrading/automated_upgrades.adoc
> +$ oc adm migrate storage --include=* --loglevel=2
In OCP < 3.10 they need to add `--confirm` in all cases.

2018-08-10 20:39 UTC, ahardin-rh commented
@sdodson I updated this PR and applied the changes to the other branches. 
3.10+: qqqhttps://github.com/openshift/openshift-docs/pull/11505
3.9: https://github.com/openshift/openshift-docs/pull/11509

2018-08-13 18:19 UTC, sdodson commented
/lgtm 
thanks!

2018-08-13 20:29 UTC, sdodson commented
/lgtm

2018-08-14 16:27 UTC, ahardin-rh commented
QE verified also

2018-08-14 16:27 UTC, merged