fixes openshift/openshift-docs#11983
openshift/openshift-docs pull request #11984
Opened 2018-09-11 16:12 UTC by davivcgarcia

This pull-request implements the suggestion of #11983.

2018-09-11 16:46 UTC, kalexand-rh commented
@davivcgarcia, does this apply to versions before 3.10?

2018-09-11 16:49 UTC, kalexand-rh requested changes
@davivcgarcia, I think you should add a step instead of adding more complexity to this one.

2018-09-11 16:49 UTC, kalexand-rh commented on upgrading/os_upgrades.adoc
> +. Make sure all the sensitive packages are protected by exclude rules, update
Please add a separate step to enable the excluder rules. I'd restore line 34 to its original state and keep the update and reboot commands in this step.

In the new step, please give a bit more context about why you'd want to do enable these rules.

2018-09-11 16:49 UTC, kalexand-rh commented
/ok-to-test

2018-09-11 17:46 UTC, kalexand-rh approved these changes
Thanks!

2018-09-11 17:47 UTC, kalexand-rh commented
@davivcgarcia, will you please squash your commits?

@jianlinliu, will you PTAL?

2018-09-11 17:58 UTC, davivcgarcia commented
@kalexand-rh sorry this mess, I'm still kinda newbie around here. Please let me know if the PR looks good now!

2018-09-11 18:00 UTC, davivcgarcia commented
@kalexand-rh answering your previous question, this update should be applicable for all versions.

2018-09-11 18:11 UTC, kalexand-rh commented
No worries, @davivcgarcia. It looks much better now. :) 

@jianlinliu, do you agree that we should apply this change going back to 3.6?

2018-09-12 02:17 UTC, jianlinliu commented
Yeah, agree to apply this change going back to 3.6

2018-09-12 12:16 UTC, merged