disable ansible 2.4
openshift/openshift-docs pull request #12436
Opened 2018-10-11 12:48 UTC by kalexand-rh

@jiajliu, @sdodson, I see at least one report on the mailing list that you need to disable ansible-2.4 during upgrade. Does this change sound right to you?

2018-10-11 12:53 UTC, sdodson approved these changes
Not disabling ansible 2.4 repos shouldn't create any harm, but it's fine to do so.
/lgtm

2018-10-11 12:53 UTC, sdodson requested changes

2018-10-11 12:53 UTC, sdodson commented on upgrading/automated_upgrades.adoc
> +    --disable="rhel-7-server-ansible-2.4-rpms"
oops, needs trailing \

2018-10-11 12:56 UTC, kalexand-rh commented on upgrading/automated_upgrades.adoc
> +    --disable="rhel-7-server-ansible-2.4-rpms"
You're right! Fixed. :)

2018-10-31 16:58 UTC, kalexand-rh commented
@jiajliu, are you ok with this change?

2019-01-02 18:13 UTC, merged

2019-01-02 18:13 UTC, kalexand-rh commented
/cherrypick enterprise-3.11