remove references to jenkins autoprovisioning
openshift/openshift-docs pull request #12713
Opened 2018-10-30 20:26 UTC by bparees

2018-10-30 20:28 UTC, bparees commented
@gabemontero ptal
@bmcelvee this probably needs some editing touches and possibly xref touchup but i hope it's a sufficient draft for you to carry it over the line.

The short version is we're dropping the jenkins auto provision feature, so:
1) references to that behavior and configuring that behavior need to be removed
2) we need to at least have minimal documentation on what users need to do so they know they need to provision their own jenkins and how to do it (the pipeline tutorial covers this).

2018-10-30 20:29 UTC, bparees commented
also it looks like the 3.3 and 3.4 release notes linked to the file i'm removing.  Not sure the best way to resolve that.

2018-10-30 20:33 UTC, gabemontero requested changes
just a couple of minor items

2018-10-30 20:33 UTC, gabemontero commented on dev_guide/openshift_pipeline.adoc
> +The OpenShift jenkins Sync Plugin provides the following:
jenkins -> Jenkins

2018-10-30 20:33 UTC, gabemontero commented on dev_guide/openshift_pipeline.adoc
> + OpenShift builds to the Jenkins git plugin.
add secret to credential mapping

2018-10-30 20:35 UTC, bparees commented on dev_guide/openshift_pipeline.adoc
> +The OpenShift jenkins Sync Plugin provides the following:
fixed

2018-10-30 20:35 UTC, bparees commented on dev_guide/openshift_pipeline.adoc
> + OpenShift builds to the Jenkins git plugin.
added

2018-10-30 20:43 UTC, gabemontero approved these changes
lgtm

2018-11-05 15:59 UTC, bparees commented
@bmcelvee bump

2018-11-30 21:43 UTC, bmcelvee commented on architecture/core_concepts/builds_and_image_streams.adoc
> -The first time a project defines a build configuration using a Pipeline
I created the Pipeline build strategy module for 4.0 and removed the Jenkins autoprovisioning content in https://github.com/openshift/openshift-docs/pull/13000.

As I convert content, I'll continue updating this PR until it is complete in the 4.0 branch.

2019-01-31 20:21 UTC, bmcelvee commented
@bparees @gabemontero We should be set to close this PR (*finally*). I modularized the content on the 4.0 branch, removed the autoprovisioning references, and added the Jenkins Sync Plugin.

2019-03-27 18:12 UTC, bmcelvee commented
Closing per previous comment.

2019-03-27 18:12 UTC, closed without merging