BZ 1666367: correcting API usage
openshift/openshift-docs pull request #13398
Opened 2019-01-23 19:14 UTC by ousleyp

https://bugzilla.redhat.com/show_bug.cgi?id=1666367

2019-01-23 21:09 UTC, stu-gott commented
Looks good to me. Nice job!

2019-01-23 22:47 UTC, davidvossel requested changes
Looks good. I think I may have caught a few instances where volumeName still needs to be addressed though

When I run a grep filter, I still see some references to volumeName when I checkout your branch.
```
$ grep -r -n "volumeName" modules/*
modules/cnv_creating_vm.adoc:30:|disks: volumeName 
modules/cnv_pxebooting.adoc:96:    volumeName: registryvolume 
modules/cnv_template_vm_config.adoc:29:            volumeName: root
```

2019-01-23 23:31 UTC, ousleyp commented
> Looks good. I think I may have caught a few instances where volumeName still needs to be addressed though
> 
> When I run a grep filter, I still see some references to volumeName when I checkout your branch.
> 
> ```
> $ grep -r -n "volumeName" modules/*
> modules/cnv_creating_vm.adoc:30:|disks: volumeName 
> modules/cnv_pxebooting.adoc:96:    volumeName: registryvolume 
> modules/cnv_template_vm_config.adoc:29:            volumeName: root
> ```

Oh, weird! I'm surprised I didn't see those when I grepped earlier. Thanks so much for checking.

Commit: https://github.com/openshift/openshift-docs/pull/13398/commits/14fae5625f62031869a6d129e5a9b6fde7a979ca

2019-01-24 16:54 UTC, davidvossel approved these changes
excellent :+1:

2019-02-05 14:50 UTC, kalexand-rh reviewed
Couple of minimalism picks, but if it passes SME review and renders well, it overall LGTM

2019-02-05 14:50 UTC, kalexand-rh commented on modules/cnv_creating_vm_web_console.adoc
> +*PXE*:: The virtual machine is booted over the network. The network
s/is booted/boots

2019-02-05 14:50 UTC, kalexand-rh commented on modules/cnv_creating_vm_web_console.adoc
> +*PXE*:: The virtual machine is booted over the network. The network
You configure the network interface and logical network later...

2019-02-05 14:50 UTC, kalexand-rh commented on modules/cnv_creating_vm_web_console.adoc
> +format can be compressed with *gzip* or *xz*.
You can compress either format...

2019-02-05 14:50 UTC, kalexand-rh commented on modules/cnv_creating_vm_web_console.adoc
> +. After you have created the VM, you can find it listed under
s/have created/create
s/you can find it/it is

2019-02-05 14:50 UTC, kalexand-rh commented on modules/cnv_vm_storage_volume_types.adoc
> +Container disks are not limited to a single virtual machine, and are
no comma

2019-02-05 20:58 UTC, merged

2019-02-27 00:24 UTC, vikram-redhat commented
/cherrypick enterprise-3.11

2019-02-27 00:25 UTC, vikram-redhat commented
@ousleyp FYI for future.. commits should have been squashed.