OSDOCS-241: Initial CLI reference docs for dev commands
openshift/openshift-docs pull request #13674
Opened 2019-02-19 22:07 UTC by bergerhoffer

@openshift/team-documentation Can someone please peer review? And also look closely to make sure that I didn't miss anything with adding a new heading (CLI Reference) and assembly? Thanks!

2019-02-19 22:36 UTC, bergerhoffer commented
@soltysh Can you please tech review this? Thanks!

This is the first of several sections that will be added to the CLI Reference section of the 4.0 docs. This is just the Developer CLI Commands (oc <command>). Another reference section for the Administrator CLI commands (oc adm <command>) will be added eventually, along with other sections.

Preview: http://file.rdu.redhat.com/~ahoffer/2019.02.19/OSDOCS-241-cli-dev/cli_reference/developer-cli-commands.html

2019-02-21 11:23 UTC, soltysh requested changes

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-advanced.adoc
> +$ oc patch node node1 -p '{"spec":{"unschedulable":true}}'
It would be nice to use a consistent naming scheme which is `<type>/<name>` so here `node/node1`.

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc annotate route test-route haproxy.router.openshift.io/ip_whitelist="192.168.1.10"
`route/test-route`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc annotate route test-route haproxy.router.openshift.io/ip_whitelist-
`route/test-route`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc autoscale dc/parksmap-katacoda --min=2 --max=5
Always use full names in docs, so `deploymentconfig` instead of `dc`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc delete pods parksmap-katacoda-1-qfqz4
`pod/parksmap-katacoda-1-qfqz4`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc describe deployments example
`deployment/example`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc edit dc/parksmap-katacoda
`deploymentconfig`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ OC_EDITOR="nano" oc edit dc/parksmap-katacoda
`deploymentconfig`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc edit dc/parksmap-katacoda -o json
`deploymentconfig`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc expose service parksmap-katacoda
`service/parksmap-katacoda`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc get dc python -o json
`deploymentconfig/python`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc label pods python-1-mz2rf status=unhealthy
`pod/python-1-mz2rf`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc scale dc ruby-app --replicas=3
`deploymentconfig/ruby-app`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-application-management.adoc
> +$ oc set build-secret --source bc/mybc mysecret
`buildconfig`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-build-deploy.adoc
> +$ oc cancel-build bc/python --state=pending
`buildconfig` instead of `bc`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-build-deploy.adoc
> +$ oc rollout undo dc/php
`deploymentconfig`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-build-deploy.adoc
> +$ oc rollout latest dc/php
`deploymentconfig`

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-other.adoc
> +== ex
I would skip `oc ex` commands, this are experimental and may change so I'd not document them.

2019-02-21 11:23 UTC, soltysh commented on modules/cli-developer-troubleshooting.adoc
> +$ oc debug dc/python
`deploymentconfig`

2019-02-21 14:28 UTC, bergerhoffer commented
Thanks a lot @soltysh! I've incorporated your suggestions and updated the preview: http://file.rdu.redhat.com/~ahoffer/2019.02.19/OSDOCS-241-cli-dev/cli_reference/developer-cli-commands.html

2019-02-21 14:52 UTC, soltysh approved these changes
lgtm, thanks!

2019-02-21 16:53 UTC, adellape requested changes
:+1: 	Just little stuff.

2019-02-21 16:53 UTC, adellape commented on _topic_map.yml
> +Name: CLI Reference
s/Reference/reference/

2019-02-21 16:53 UTC, adellape commented on cli_reference/developer-cli-commands.adoc
> += Developer CLI Commands
s/Commands/commands/

2019-02-21 16:53 UTC, adellape commented on _topic_map.yml
> +- Name: Developer CLI Commands
s/Commands/commands/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-basic.adoc
> +.Example: Log in specifying a username and password
s/username/user name/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-basic.adoc
> +$ oc new-app https://github.com/youruser/yourprivaterepo --source-secret=yoursecret
Use `<replaceables>`.

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-basic.adoc
> +.Example: Create a new application from a local git repository
Throughout (other than the URLs) : s/git/Git/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-application-management.adoc
> +.Example: Sets the name of a secret on a build configuration
Throughout: s/build configuration/BuildConfig/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-application-management.adoc
> +.Example: Add an annotation to a route
Throughout (outside of code blocks): s/route/Route/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-advanced.adoc
> +Idle scalable resources. An idled service will automatically become unidled when
s/service/Service/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-advanced.adoc
> +.Example: Idle the `ruby-app` service
s/service/Service/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-advanced.adoc
> +.Example: Observe changes to services
s/services/Services/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-application-management.adoc
> +Expose a service externally as a route.
s/service/Service/
s/route/Route/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-application-management.adoc
> +.Example: Expose a service
s/service/Service/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-application-management.adoc
> +.Example: Expose a service and specify the host name
s/service/Service/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-application-management.adoc
> +Set the desired number of replicas for a replication controller or a deployment
s/replication controller/ReplicationController/
s/deployment configuration/DeploymentConfig/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-application-management.adoc
> +.Example: Scale the `ruby-app` deployment configuration to 3 Pods
Since it's not referring directly to a value right here?: s/3/three/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-troubleshooting.adoc
> +Retrieve the log output for a specific build, build configuration, deployment
Throughout: s/build configuration/BuildConfig/
Throughout: s/deployment configuration/DeploymentConfig/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-troubleshooting.adoc
> +.Example: Start an instance of the `perl` image with 3 replicas
Same re: s/3/three/ ?

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-other.adoc
> +List the available plugins on the user's `PATH`.
s/plugins/plug-ins/

2019-02-21 16:53 UTC, adellape commented on modules/cli-developer-other.adoc
> +.Example: List available plugins
s/plugins/plug-ins/

2019-02-21 18:35 UTC, adellape approved these changes

2019-02-21 18:35 UTC, bergerhoffer commented
Thanks for the review @adellape, updated PR and preview.

2019-02-21 18:35 UTC, merged