Follow-up edits to Samples Operator documentation
openshift/openshift-docs pull request #13821
Opened 2019-02-26 20:03 UTC by bmcelvee

Follow-up to https://github.com/openshift/openshift-docs/pull/13625

This will include formatting changes to match the outlined template.

2019-03-01 02:51 UTC, xiuwang commented on _topic_map.yml
> +  File: configuring-samples-operator
"Create images" and  "Managing image sterams" topics need move up too

2019-03-04 16:12 UTC, bmcelvee commented
@gabemontero here's the follow-up edits PR. I'm also incorporating some changed request in the phase 1 docs review.

2019-03-05 02:25 UTC, xiuwang commented on modules/samples-operator-configuration.adoc
>  * *Skipped Image streams:* Image streams that are in the operator’s
“Skipped Image streams‘ should update to 'Skipped Imagestreams'

2019-03-05 02:30 UTC, xiuwang commented on modules/samples-operator-configuration.adoc
> +and any image streams or templates in the OpenShift namespace.
All 'image streams' phrases in this doc https://docs.openshift.com/container-platform/4.0/openshift_images/configuring-samples-operator.html#samples-operator-configuration-configuring-samples-operator should be updated to 'imagestreams'

2019-03-05 02:32 UTC, xiuwang commented on modules/samples-operator-configuration.adoc
> +** *Unmanaged.* The operator ignores updates to its configuration resource object
Better to keep ’configuration resource‘ with  'samples resource' in line

2019-03-05 19:43 UTC, gabemontero requested changes
Some minor changes @bmcelvee

2019-03-05 19:43 UTC, gabemontero commented on modules/samples-operator-configuration.adoc
> +Creation or update of RHEL content is not be gated if the `Samples Registry` is
s/ is not be gated / is not gated by the existence of the pull secret

2019-03-05 19:43 UTC, gabemontero commented on modules/samples-operator-overview.adoc
> +managed by the operator will be reverted automatically. The Jenkins images are
managed by the operator -> managed by the operator, where that version annotation is modified or deleted,

2019-03-05 19:43 UTC, gabemontero commented on modules/samples-operator-overview.adoc
> +* The `samples-registry-credentials` secret.
we are planning to no longer delete the secret with https://github.com/openshift/cluster-samples-operator/pull/125 ... please track that PR, and assuming that goes through, remove this line please

2019-03-06 07:50 UTC, xiuwang commented on _topic_map.yml
>  - Name: Understanding containers, images, and image streams
s/image stremas/imagestreams

2019-03-08 01:56 UTC, xiuwang commented on modules/samples-operator-configuration.adoc
> +* *Skipped imagestreams:* Imagestreams that are in the Samples Operator’s
s/Skipped imagestreams/Skipped Imagestreams

2019-03-13 02:04 UTC, xiuwang commented
LGTM, thanks

2019-03-13 17:06 UTC, merged