Add missing registry examples to Ansible Broker Configuration
openshift/openshift-docs pull request #13926
Opened 2019-03-01 16:36 UTC by nccurry

Fixes #13920

2019-03-02 21:07 UTC, vikram-redhat commented
/ok-to-test

2019-03-02 21:08 UTC, vikram-redhat commented
@bergerhoffer - when you have a chance, PTAL.

2019-03-05 20:38 UTC, bergerhoffer requested changes
@nccurry Thanks a lot for submitting these updates. Just a few things if you wouldn't mind updating.

2019-03-05 20:38 UTC, bergerhoffer commented on install_config/oab_broker_configuration.adoc
> +*Note:* A heavy percentage of helm charts from the stable repository are not well suited for OpenShift.
1. Can you replace `*Note:* A heavy...` with `NOTE: A heavy...` so that it renders as a note?
2. Can you replace `OpenShift` with `{product-title}`?

2019-03-05 20:38 UTC, bergerhoffer commented on install_config/oab_broker_configuration.adoc
> +For more information see link:https://github.com/ansibleplaybookbundle/helm2bundle/wiki/Known-Issues[here].
Can you instead say:

```
See the link:https://github.com/ansibleplaybookbundle/helm2bundle/wiki/Known-Issues[Known Issues] for more information.
````

2019-03-05 20:38 UTC, bergerhoffer commented on install_config/oab_broker_configuration.adoc
> +Using the `apiv2` type allows you to consume images from docker registries that implement the Docker Registry
This sentence runs on. Can you reword "can be configured with the apiv2 registry adapter" into a second sentence?

2019-03-05 20:38 UTC, bergerhoffer commented on install_config/oab_broker_configuration.adoc
> +[source,yaml]
This should not have source,yaml here since it's a terminal command. You can just remove this line.

2019-03-05 20:38 UTC, bergerhoffer commented on install_config/oab_broker_configuration.adoc
> +[source,yaml]
This should not have source,yaml here since it's a terminal command. You can just remove this line.

2019-03-05 20:38 UTC, bergerhoffer commented on install_config/oab_broker_configuration.adoc
> +docker --config=/var/lib/origin/.docker login -u <registry-user> -p <registry-password> <registry_url>
Can you put "$" in front of this command? (Or "#" if it needs to be run by root)

2019-03-05 20:38 UTC, bergerhoffer commented on install_config/oab_broker_configuration.adoc
> +docker --config=/var/lib/origin/.docker login -u <registry-user> -p <registry-password> quay.io
Can you put "$" in front of this command? (Or "#" if it needs to be run by root)

2019-03-05 20:38 UTC, bergerhoffer commented on install_config/oab_broker_configuration.adoc
> +If an authentication token is provided, private repositories (which the token is configured to access) will
Can you reword this a bit to something like:

```
If an authentication token is provided, private repositories that the token is configured to access and public repositories in the specified organization will load.
```

2019-03-05 20:41 UTC, bergerhoffer commented
@chengzhang1016 Would you mind reviewing these updates as well? Or let me know if there's someone else who should provide QE review. Thanks!

2019-03-05 21:46 UTC, nccurry commented
Thanks for taking the time to look at this!
Requested modifications added.

2019-03-06 00:59 UTC, bergerhoffer commented
Thanks for the updates @nccurry! Once we get QE approval, I'll merge and cherry-pick this to enterprise-3.11.

2019-03-06 01:00 UTC, bergerhoffer approved these changes

2019-04-10 13:58 UTC, kalexand-rh commented
@chengzhang1016, will you PTAL?

2019-04-10 14:38 UTC, chengzhang1016 commented
@bergerhoffer @kalexand-rh Looks you are adding these changes in document of enterprise-3.11. We need one day to review and test, and will provide feedback by the end of tomorrow.

I and @zihantang-rh will review it.

2019-04-11 08:13 UTC, zihantang-rh commented
LGTM, thanks

2019-04-11 09:09 UTC, chengzhang1016 commented
The changes LGTM. Thx.

2019-04-11 13:02 UTC, bergerhoffer commented
Thanks @chengzhang1016 and @zihantang-rh!

Merging and cherry-picking to enterprise-3.11.

2019-04-11 15:27 UTC, merged

2019-04-11 15:27 UTC, bergerhoffer commented
/cherrypick enterprise-3.11