Document CNV binding method webui option
openshift/openshift-docs pull request #14633
Opened 2019-04-30 17:47 UTC by booxter

2019-04-30 17:50 UTC, booxter commented
@SchSeba this is similar to https://github.com/kubevirt/user-guide/pull/236/ except that I dropped mentioning `sriov` because it's not included into CNV 2.0

2019-04-30 18:31 UTC, SchSeba approved these changes

2019-04-30 19:31 UTC, dankenigsberg requested changes

2019-04-30 19:31 UTC, dankenigsberg commented on modules/cnv_networking_wizard_fields_web.adoc
> +|List of available binding methods. For pod networking, the possible values are `masquerade` and `bridge`. The `masquerade` method is not supported for non-default networks.
It is very important **not** to allow `bridge` on the default network. It is spells only trouble.

For the default pod network, the only possible value is `masquerade`. For secondary networks the only possible method is `bridge`.

2019-05-01 23:02 UTC, booxter commented
/hold

This will need to be reproposed for enterprise-4.1 branch when the new layout for CNV docs is backported there.

2019-05-15 14:49 UTC, ousleyp commented
Hey @booxter do you mind closing this PR? The binding method info has already been merged:

https://github.com/openshift/openshift-docs/pull/14351/files#diff-f5fef2dd1faeebdba55e9b5ab92c1961

Thanks! And I'm sorry for all the confusion - when we're done modularizing the docs, we'll send out an email with new (and improved) instructions for dev contributions. Thanks for your patience.

2019-05-23 19:53 UTC, closed without merging