BZ1704843 Correct example API
openshift/openshift-docs pull request #14645
Opened 2019-05-01 19:42 UTC by bmcelvee

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1704843

2019-05-07 07:58 UTC, wewang58 commented
@bmcelvee  Should be kind: "BuildConfig" no need to update it, @adambkaplan could you help to confirm it again, thanks.

2019-05-07 18:13 UTC, adambkaplan requested changes

2019-05-07 18:13 UTC, adambkaplan commented on modules/builds-buildconfig.adoc
>  apiVersion: "v1"
```
kind: BuildConfig
apiVersion: build.openshift.io/v1
...
```

2019-05-10 15:01 UTC, bmcelvee commented
Minor change, no peer review needed

2019-05-10 15:02 UTC, merged