updating information related to customer-admin-cluster role in ARO
openshift/openshift-docs pull request #15727
Opened 2019-07-05 11:53 UTC by Makdaam

On hold until the feature is released.
/hold

waiting for PR https://github.com/openshift/openshift-azure/pull/1776
and the release process (new images, new version release, deployment in Azure)

I will cancel the hold after the feature is public.

2019-07-11 00:37 UTC, vikram-redhat commented
@xltian can someone from QE ack this?

2019-07-11 13:32 UTC, mffiedler commented
/cc @mgahagan73

2019-07-11 19:56 UTC, mgahagan73 commented
ACK, I was having issues getting the changed doc to render properly but I think it's an issue on my end. 

/lgtm

2019-08-09 11:31 UTC, Makdaam commented
/hold cancel
the new version with documented features is rolling out to production.

2019-08-09 14:37 UTC, mgahagan73 approved these changes
I reviewed this doc change back in July, it still looks good to me.

2019-08-09 16:03 UTC, huffmanca requested changes
I have one nitpick comment in the content itself; however, with this restructure the `Cluster-level Permissions` table in the openshift-aro admin guide is missing references. Specifically, it needs the `manage_rbac` and `manage_scc` files included.

To include these files, you'll need to update the `_topic_map.yml` in the root directory, and add `openshift-aro` to the comma-separated `Distros` list underneath each file.

Let me know if you have any questions on this process.

I can confirm that the links on the index page work after adding in these files and building locally. If these files shouldn't be included in the openshift-aro distro, then you'll need to reintroduce the specific `Cluster-level Permissions` section in the openshift-aro distribution.

2019-08-09 16:12 UTC, Makdaam commented on admin_guide/manage_rbac.adoc
> +{cluster-admin-name} can view but not manage cluster roles. They can manage cluster role bindings
FIxed.

2019-08-09 16:17 UTC, Makdaam commented
@huffmanca,
thank you for the quick response.
Fixed the singular and added manage_scc and manage_rbac to the openshift-aro distro.

2019-08-12 15:18 UTC, huffmanca commented
All of these changes look good to me! Merging and cherry picking.

2019-08-12 15:18 UTC, merged

2019-08-12 15:18 UTC, huffmanca commented
/cherrypick enterprise-3.11