When deploying logging, storage config is stripped out of the imported ClusterLogging instance
openshift/openshift-docs pull request #16056
Opened 2019-07-29 20:22 UTC by mburke5678

https://bugzilla.redhat.com/show_bug.cgi?id=1734107

2019-07-29 20:27 UTC, mburke5678 commented
@ewolinetz PTAL

2019-07-29 20:31 UTC, jcantrill commented on modules/efk-logging-deploying-about.adoc
> +          storageClassName:
it should be:
```
storageClassName: "gp2"
size: "200G"
```
no name key

2019-07-29 20:31 UTC, ewolinetz commented on modules/efk-logging-deploying-about.adoc
> -          storageClass:
the whole structure should be
```
elasticsearch:
    storage:
        storageClassName: "gp2"
        size: "200G"
```

2019-07-29 20:32 UTC, ewolinetz requested changes
`storageClassName` and `size` are at the same level. there is no `name`

2019-07-29 21:06 UTC, mburke5678 commented on modules/efk-logging-deploying-about.adoc
> +          storageClassName:
Ooops! Sorry!

2019-07-29 21:24 UTC, ewolinetz commented on modules/efk-logging-elasticsearch-storage.adoc
> +          storageClassName:
same edit here

2019-07-30 21:09 UTC, mburke5678 commented
@xltian PTAL or assign to someone who can review. Thank you!

2019-07-30 23:31 UTC, ewolinetz commented
:+1:

2019-08-05 05:13 UTC, anpingli commented
LGTM

2019-08-05 05:14 UTC, anpingli approved these changes

2019-08-05 13:27 UTC, mburke5678 commented
Verified in BZ

2019-08-05 13:27 UTC, merged