Allow Whitelisting of Sysctls Configuration
openshift/openshift-docs pull request #16194
Opened 2019-08-09 17:08 UTC by mburke5678

https://jira.coreos.com/browse/PROD-1038
https://jira.coreos.com/browse/NODE-140

2019-08-09 17:16 UTC, rphillips requested changes
Looks great overall... Just a couple comments.

2019-08-09 17:16 UTC, rphillips commented on modules/nodes-containers-sysctls-about.adoc
> +$ podman run --rm -ti docker.io/fedora \
this section on running podman is awesome, but is somewhat contrary to us not wanting customers to SSH into machines. I vote on removing this blurb on checking the namespaced sysctls.

2019-08-09 17:16 UTC, rphillips commented on modules/nodes-containers-sysctls-unsafe.adoc
> +    custom-kubelet: small-pods <1>
The label here should be `custom-kubelet: sysctl`

2019-08-11 16:14 UTC, mburke5678 commented
@rphillips I added a section to `nodes-containers-sysctls-unsafe.adoc` with steps to verify that the cluster is rebooted and ready before creating the pod with unsafe sysctls. Can you verify if these are the best ways to verify the reboot?
@vikram-redhat I am not sure who the br QE resource is. Could I bother you to assign this? 

I am on PTO until 8/16 and won't be checking email until 8/15 at earliest. I would like to get the procedures in this PR reviewd. Please don't worry about obvious typos. I will fix them when I get back.

2019-08-12 06:29 UTC, xltian commented
@sunilcio from QE will take a look at this.

2019-08-12 20:49 UTC, rphillips approved these changes

2019-08-14 11:16 UTC, sunilcio commented on modules/nodes-containers-sysctls-unsafe.adoc
> +source,yaml]
Small syntax error. `[source,yaml]`

2019-08-16 16:42 UTC, mburke5678 commented
@openshift/team-documentation PTAL.
I am replacing the _sysctl_ topic from 3.11 back into 4.2 and modularizing.  It appears that the original topic was pulled from upstream in large part. I tried cleaning things up a bit. But i don't know sysctl. 
I likely could have found more introductory info. Not sure it's needed though, as I am assuming that any user who would use sysctl would understand what they are doing.

2019-08-16 19:33 UTC, adellape reviewed
Minor suggestions. :+1:

2019-08-16 19:33 UTC, adellape commented on modules/nodes-containers-sysctls-about.adoc
> +Additionally, most of the sysctls in the **net.*** group are known
Check markup choice here.

2019-08-16 19:33 UTC, adellape commented on modules/nodes-containers-sysctls-about.adoc
> +- Gain CPU or memory resources outside of the resource limits of a pod
Periods at the end of these?

2019-08-16 19:33 UTC, adellape commented on modules/nodes-containers-sysctls-setting.adoc
> +to launch on any node unless the admin explicitly enables unsafe sysctls for
s/will fail/fails/
s/admin/cluster administrator/

2019-08-16 19:33 UTC, adellape commented on modules/nodes-containers-sysctls-unsafe.adoc
> +. Add a label to the Machine Config Pool where the containers where containers
MachineConfigPool?

2019-08-16 19:33 UTC, adellape commented on modules/nodes-containers-sysctls-unsafe.adoc
> +<1> Specify the label from the Machine Config Pool.
MachineConfigPool?

2019-08-16 19:33 UTC, adellape commented on modules/nodes-containers-sysctls-unsafe.adoc
> +[source,yaml]
Maybe don't add this syntax highlighting if the other YAML blocks aren't going to get it, for consistency within the assembly at least. With the combination of the CLI command + YAML output, it makes the command look wacky, too.

2019-08-16 19:33 UTC, adellape commented on modules/nodes-containers-sysctls-unsafe.adoc
> +oc get machineconfig 99-worker-XXXXXX-XXXXX-XXXX-XXXXX-kubelet -o json | grep ownerReference -A7
`$` prompt at front, and maybe add a blank line after the command to give it some room from the output.

2019-08-16 20:26 UTC, mburke5678 commented
@adellape Thanks for the review!!

2019-08-16 20:31 UTC, merged

2019-08-16 20:32 UTC, mburke5678 commented
/cherrypick enterprise-4.2