[WIP] osdocs636 default GCP install
openshift/openshift-docs pull request #16233
Opened 2019-08-13 19:43 UTC by kalexand-rh

https://jira.coreos.com/browse/OSDOCS-636

2019-08-21 19:40 UTC, kalexand-rh commented
@abhinavdahiya, @jstuever, will you PTAL at these draft GCP docs? If this looks ok to you, I'll send it over to QE.

2019-08-26 16:53 UTC, jstuever requested changes
It appears `installing-gcp-customizations.html` refers to aws in `Installation configuration parameters`. Other than that, just a few minor issues.

2019-09-23 12:18 UTC, kalexand-rh commented
@openshift/team-documentation PTAL

2019-09-23 18:40 UTC, bobfuru reviewed
A few suggestions, similar to https://github.com/openshift/openshift-docs/pull/16374/

2019-09-23 18:40 UTC, bobfuru commented on modules/installation-configuration-parameters.adoc
> +|Whether to enable or disable simultaneous multithreading, or `hyperthreading`
s/`hyperthreading` on/`hyperthreading`, on

2019-09-23 18:40 UTC, bobfuru commented on modules/installation-gcp-config-yaml.adoc
> +setting the parameter value to `Disabled`. If you disable simultanous
s/simultanous/simultaneous

2019-09-23 18:40 UTC, bobfuru commented on modules/installation-gcp-config-yaml.adoc
> +process uses to the installation program.
s/to the/to access the

2019-09-23 18:40 UTC, bobfuru commented on modules/installation-launching-installer.adoc
> +for the GCP account that you configured for your cluster and are stored in the
s/and are/and that are

2019-09-23 19:16 UTC, kalexand-rh commented
Thanks @bobfuru!

2019-09-23 21:26 UTC, merged

2019-09-23 21:26 UTC, kalexand-rh commented
/cherrypick enterprise-4.2

2019-10-09 00:13 UTC, vikram-redhat commented
@wmengRH is the default GCP install content ok from QE's point of view?

2019-10-09 00:48 UTC, wmengRH commented
Yes, the default GCP install content LGTM.