BZ-1745765: Add step to force MCD to accept cert update
openshift/openshift-docs pull request #16399
Opened 2019-08-27 12:28 UTC by bergerhoffer

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1745765

2019-08-27 13:06 UTC, rphillips requested changes

2019-08-27 13:07 UTC, rphillips approved these changes

2019-08-28 09:40 UTC, zhouying7780 commented
Works fine, LGTM

2019-08-28 19:10 UTC, adellape approved these changes
:+1:

2019-08-29 12:00 UTC, merged

2019-08-29 12:00 UTC, bergerhoffer commented
/cherrypick enterprise-4.2

2019-09-11 18:13 UTC, rphillips commented
/cherrypick enterprise-4.1