Update CNV doc attributes
openshift/openshift-docs pull request #16426
Opened 2019-08-29 09:50 UTC by vikram-redhat

@ousleyp @aburdenthehand @bgaydosrh - FYI.

2019-08-29 13:24 UTC, bgaydosrh approved these changes
Looks good to me. :+1: 

Bob

2019-08-29 14:31 UTC, ousleyp requested changes
For the most part, this LGTM, but there were a few places where I think we should use `{CNVProductNameStart}` instead of `{CNVProductName}`.

2019-08-30 01:03 UTC, vikram-redhat commented
Great catches @ousleyp! Now only if @aburdenthehand would give us the ack as well ....

2019-08-30 09:41 UTC, aburdenthehand commented on cnv/cnv_install/cnv-about-cnv.adoc
> +== {CNVProductName} support
Starts a title - should this be `{CNVProductNameStart}`?

2019-08-30 09:46 UTC, aburdenthehand commented on cnv/cnv_release_notes/cnv-release-notes.adoc
>  (link:https://bugzilla.redhat.com/show_bug.cgi?id=1707427[*BZ#1707427*])
Not an issue with this line, but on line 69 there is an instance of `CNV` that should be replaced with `{CNVProductNameStart}`

2019-08-30 09:48 UTC, aburdenthehand commented on cnv/cnv_release_notes/cnv-release-notes.adoc
> +=== {CNVProductName} support
Starts a title - should this be `{CNVProductNameStart}`?

2019-08-30 09:49 UTC, aburdenthehand commented on modules/cnv-networking-glossary.adoc
> += {CNVProductName} networking glossary
Starts a title - should this be `{CNVProductNameStart}`?

2019-08-30 09:53 UTC, aburdenthehand commented
@vikram-redhat - there's a few instances of ProductName starting a title, which I think should be capitalised, and one instance (release notes) of `CNV`.
Otherwise it's a go.

2019-09-02 04:34 UTC, vikram-redhat commented
Thanks @aburdenthehand. All fixed, and found a few more. 

Merging and CPing this.

2019-09-02 04:34 UTC, merged

2019-09-02 04:34 UTC, vikram-redhat commented
/cherrypick enterprise-4.1

2019-09-02 04:34 UTC, vikram-redhat commented
/cherrypick enterprise-4.2