Bug 1757573, updated Cluster Loader docs
openshift/openshift-docs pull request #17219
Opened 2019-10-11 15:32 UTC by ahardin-rh

https://bugzilla.redhat.com/show_bug.cgi?id=1757573

2019-10-11 15:46 UTC, ahardin-rh commented
@sjug Thanks for your guidance on these updates! Please review and let me know if I missed anything.

2019-10-14 14:49 UTC, ahardin-rh commented
@mffiedler PTAL as well. Thanks!

2019-10-14 15:16 UTC, mffiedler commented
@wabouhamad Please review

2019-10-14 18:26 UTC, wabouhamad commented
@ahardin-rh sorry took me a while to build a cluster to test the commands, I am still unable to run the sample commands successfully

2019-10-14 18:27 UTC, wabouhamad commented on modules/running-cluster-loader.adoc
> +$ sudo podman run -v ${LOCAL_KUBECONFIG}:/root/.kube/config:z -i
we need a backslack for continuation of command at the of this line

2019-10-14 18:28 UTC, wabouhamad commented on modules/running-cluster-loader.adoc
> +$ sudo podman run -v ${LOCAL_KUBECONFIG}:/root/.kube/config:z
Also here need a backslack for continuation of command at the of this line

2019-10-14 18:35 UTC, wabouhamad requested changes
When I run these commands on a jump host, I get the following error `podman run -v ${LOCAL_KUBECONFIG}:/root/.kube/config:z -i quay.io/openshift/origin-tests:4.2 /bin/bash -c 'export KUBECONFIG=/root/.kube/config && \
openshift-tests run-test "[Feature:Performance][Serial][Slow] Load cluster should load the \
cluster [Suite:openshift]"'
I1014 18:21:20.283831       8 test.go:182] openshift-tests excluded test regex is "\\[Disabled:|\\[Disruptive\\]|\\[Skipped\\]|\\[Slow\\]|\\[Flaky\\]|\\[local\\]|\\[Suite:openshift/test-cmd\\]|\\[Skipped:skeleton\\]|\\[Skipped:Network/OpenShiftSDN\\]"
Oct 14 18:21:20.369: INFO: >>> kubeConfig: /root/.kube/config
Oct 14 18:21:20.370: INFO: Waiting up to 30m0s for all (but 100) nodes to be schedulable
Oct 14 18:21:20.393: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Oct 14 18:21:20.416: INFO: 0 / 0 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Oct 14 18:21:20.416: INFO: expected 0 pod replicas in namespace 'kube-system', 0 are Running and Ready.
Oct 14 18:21:20.416: INFO: Waiting up to 5m0s for all daemonsets in namespace 'kube-system' to start
Oct 14 18:21:20.424: INFO: e2e test version: v1.14.6+f9b5405
Oct 14 18:21:20.425: INFO: kube-apiserver version: v1.14.6+2e5ed54
[BeforeEach] [Top Level]
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/test.go:59
[BeforeEach] [Feature:Performance][Serial][Slow] Load cluster
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:149
STEP: Creating a kubernetes client
Oct 14 18:21:20.428: INFO: >>> kubeConfig: /root/.kube/config
[BeforeEach] [Feature:Performance][Serial][Slow] Load cluster
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/cluster/cl.go:44
Oct 14 18:21:20.431: INFO: Undefined config file, using built-in config /tmp/fixture-testdata-dir668249003/test/extended/testdata/cluster/master-vert.yaml

[It] should load the cluster [Suite:openshift]
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/cluster/cl.go:65
Oct 14 18:21:20.432: INFO: Our tuning set is: &{default {{5 0s 0s} {0s}} {{0 0s 0s} {0s}}}
Oct 14 18:21:20.440: INFO: Configuration requested deletion of project clusterloader-cakephp-mysql0
Oct 14 18:21:20.440: INFO: Deleting project clusterloader-cakephp-mysql0 ...
Oct 14 18:21:30.460: INFO: Running 'oc --namespace= --config= adm new-project clusterloader-cakephp-mysql0'
Created project clusterloader-cakephp-mysql0
Oct 14 18:21:30.572: INFO: 1/1 : Created new namespace: clusterloader-cakephp-mysql0
[AfterEach] [Feature:Performance][Serial][Slow] Load cluster
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/client.go:120
[AfterEach] [Feature:Performance][Serial][Slow] Load cluster
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:150
Oct 14 18:21:30.573: INFO: Waiting up to 3m0s for all (but 100) nodes to be ready
Oct 14 18:21:30.582: INFO: Running AfterSuite actions on all nodes
Oct 14 18:21:30.582: INFO: Running AfterSuite actions on node 1
fail [github.com/openshift/origin/test/extended/cluster/cl.go:156]: Unexpected error:
    <*errors.errorString | 0xc003d59e20>: {
        s: "unable to find pod/template file ./test/extended/testdata/cluster/quickstarts/cakephp-mysql.json\n",
    }
    unable to find pod/template file ./test/extended/testdata/cluster/quickstarts/cakephp-mysql.json
    
occurred` not sure if something else needs to be pre-configured

2019-10-14 19:58 UTC, sjug commented
@wabouhamad That's a bug with Cluster Loader, not with the docs.

2019-10-14 21:00 UTC, wabouhamad commented
@sjug should we mention that somewhere, and list Bug id, someone may try these commands and hit that failure ?  If CL bug is being fixed before 4.2 GA, and commands are correct, that would probably be OK

2019-10-14 21:21 UTC, ahardin-rh commented
@sjug @wabouhamad Yeah, if there is a known issue that will stand for 4.2, we should get that noted here. Do you have a BZ number?

2019-10-15 18:10 UTC, bergerhoffer commented on modules/configuring-cluster-loader.adoc
> +templates or pods.
Pods

2019-10-15 18:10 UTC, bergerhoffer commented on modules/running-cluster-loader.adoc
> +In this example, `${LOCAL_KUBECONFIG}` refers to the path to the `kubconfig` on
kubeconfig

2019-10-15 18:18 UTC, wabouhamad commented
@ahardin-rh LGTM

2019-10-15 19:28 UTC, merged

2019-10-15 19:28 UTC, ahardin-rh commented
/cherrypick enterprise-4.2