OSDOCS-715 pull secret doc improvements
openshift/openshift-docs pull request #17565
Opened 2019-10-23 20:16 UTC by bmcelvee

https://jira.coreos.com/browse/OSDOCS-715

2020-08-21 22:24 UTC, gabemontero requested changes

2020-08-25 15:01 UTC, bmcelvee commented on modules/images-samples-credentials-options.adoc
> +You can create an additional secret in the {product-title} namespace, which will get used automatically for the Samples Operator.
Ah crumbs, that's right. Thank you!

2020-09-04 08:13 UTC, xiuwang commented on modules/images-imagestream-import-images-private-registry.adoc
> +When importing from an insecure registry, the registry URL defined in the Secret must include the :80 port suffix or the Secret is not used when attempting to import from the registry.
It's not only for insecure registry. Both insecure and secure registry need add port if they defined one.
such as “upshift.mirror-registry.qe.devcluster.openshift.com:5000” and “upshift.mirror-registry.qe.devcluster.openshift.com:5001”， they are secure registries but could be configured with different authication.
@gabemontero  Could you help confirm this NOTE ?

2020-09-04 08:19 UTC, xiuwang commented on modules/images-imagestream-import-images-private-registry.adoc
> +    --from-file=<file>.txt
The cmd should be 
`oc create secret generic <secret_name> --from-file=.dockercfg=<file_absolute_path> --type=kubernetes.io/dockercfg`
or `oc create secret generic <secret_name> --from-file=.dockerconfigjson=<file_absolute_path> --type=kubernetes.io/dockerconfigjson`

e.g

`oc create secret generic test --from-file=.dockerconfigjson=/home/wxj/.docker/config.json --type=kubernetes.io/dockerconfigjson
secret/test created`

2020-09-04 08:23 UTC, xiuwang commented on modules/images-imagestream-import-images-private-registry.adoc
> +$ oc import-image <image-name>
When create a new imagestream, we could use cmds:
`oc tag <image> <imagestreamtag>`
or 
`oc import-image <imagestreamtag> --from=<image> --confirm`

2020-09-04 08:34 UTC, xiuwang commented on openshift_images/managing_images/using-image-pull-secrets.adoc
> +You use this pull secret to authenticate with the services that are provided by the included authorities, including Quay.io and registry.redhat.io, which serves the container images for {product-titl
s/Quay.io/quay.io

2020-09-04 08:37 UTC, xiuwang commented on openshift_images/managing_images/using-image-pull-secrets.adoc
> +.Example config.json fole
s/fole/file

2020-10-28 01:53 UTC, xiuwang commented
LGTM, thanks

2020-11-12 20:16 UTC, bmcelvee commented
@openshift/team-documentation PTAL :fallen_leaf:

2020-11-12 21:07 UTC, jeana-redhat approved these changes
Small suggestions! Looks nice overall.

2020-11-12 21:07 UTC, jeana-redhat commented on openshift_images/managing_images/using-image-pull-secrets.adoc
> +You use this pull secret to authenticate with the services that are provided by the included authorities, including link:quay.io[Quay.io] and link:registry.redhat.io[registry.redhat.io], which serves
s/serves/serve (unless I'm misunderstanding and that's not really plural :slightly_smiling_face:)

2020-11-12 21:16 UTC, bmcelvee commented on modules/images-imagestream-import-images-private-registry.adoc
> += Importing images and imagestreams from private registries
Crumbs. Forgot about that one. -_- It's flip-floped so many times. TY

2020-11-12 21:59 UTC, bmcelvee commented on openshift_images/managing_images/using-image-pull-secrets.adoc
> +.Example config.json file
Couldn't hurt :)

2020-11-12 22:03 UTC, merged

2020-11-12 22:04 UTC, bmcelvee commented
/cherrypick enterprise-4.5

2020-11-12 22:04 UTC, bmcelvee commented
/cherrypick enterprise-4.6

2020-11-12 22:04 UTC, bmcelvee commented
/cherrypick enterprise-4.7