OSP: instruct users to uncompress the artifact
openshift/openshift-docs pull request #18156
Opened 2019-11-18 17:19 UTC by miabbott

We've received multiple reports from users who did not uncompress the
OpenStack artifact before trying to use it in their cluster.  Let's
explicitly instruct them to uncompress the artifact before having them
try to use it in a cluster.

2019-11-18 18:09 UTC, maxwelldb commented
@miabbott Can you confirm that these customers are retrieving the artifact from the portal downloads page that's linked in these docs?

@morenod As I recall, this problem is related to the outcome of this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1763803#c6

Can we verify what the safest recommendation is here?

2019-11-18 18:12 UTC, maxwelldb requested changes

2019-11-18 18:12 UTC, maxwelldb commented on modules/installation-osp-creating-image.adoc
> +. After downloading the file, use `gunzip` to uncompress the file before trying to create an image in OpenStack.
>Use `gunzip` to decompress the image.

Alternatively, combine this step with step 1:

>Download the _Red Hat Enterprise Linux CoreOS - OpenStack Image (QCOW)_ and extract the image.

2019-11-18 18:12 UTC, maxwelldb commented on modules/installation-osp-creating-image.adoc
>  . From the image that you downloaded, create an image that is named `rhcos` in your cluster by using the {rh-openstack} CLI:
"downloaded" -> "extracted"/"decompressed"

2019-11-18 18:42 UTC, miabbott commented
> @miabbott Can you confirm that these customers are retrieving the artifact from the portal downloads page that's linked in these docs?

See https://bugzilla.redhat.com/show_bug.cgi?id=1764856 as an example.

> @morenod As I recall, this problem is related to the outcome of this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1763803#c6
> 
> Can we verify what the safest recommendation is here?

Unfortunately there is going to be some slight differences between 4.2 and 4.3. 

 In 4.2, some of the artifacts were compressed, but lacked the `.gz` file extension.  This caused more grief than anything, so for 4.3 we made the choice to have *ALL* compressed artifacts include the `.gz` extension.

Thus, this change is to reflect that the OpenStack artifact is in fact compressed (it should ship with the `.gz` extension) and users have to decompress it before it can be usable.  I didn't want this to be omitted from the docs, since I've seen reports in Slack about folks not being aware they need to decompress the OpenStack artifact before trying to use it.

2019-11-18 18:48 UTC, maxwelldb commented
> > @miabbott Can you confirm that these customers are retrieving the artifact from the portal downloads page that's linked in these docs?
> 
> See https://bugzilla.redhat.com/show_bug.cgi?id=1764856 as an example.
> 
> > @morenod As I recall, this problem is related to the outcome of this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1763803#c6
> > Can we verify what the safest recommendation is here?
> 
> Unfortunately there is going to be some slight differences between 4.2 and 4.3.
> 
> In 4.2, some of the artifacts were compressed, but lacked the `.gz` file extension. This caused more grief than anything, so for 4.3 we made the choice to have _ALL_ compressed artifacts include the `.gz` extension.
> 
> Thus, this change is to reflect that the OpenStack artifact is in fact compressed (it should ship with the `.gz` extension) and users have to decompress it before it can be usable. I didn't want this to be omitted from the docs, since I've seen reports in Slack about folks not being aware they need to decompress the OpenStack artifact before trying to use it.

@miabbott IIRC, the customer groups RHCOS images by major version only. Does it follow that this change should apply to both 4.2 and 4.3, then?

2019-11-18 18:54 UTC, miabbott commented
> @miabbott IIRC, the customer groups RHCOS images by major version only. Does it follow that this change should apply to both 4.2 and 4.3, then?

Yes, in both versions the user will have to decompress the artifact before it can be used in the OpenStack cluster.  The difference I was trying to highlight was that the 4.3 artifacts will have the `.gz` extension if they are compressed, whereas the 4.2 artifacts may be missing the extension.

2019-11-18 19:04 UTC, maxwelldb requested changes

2019-11-18 19:04 UTC, maxwelldb commented on modules/installation-osp-creating-image.adoc
> +. Download the _Red Hat Enterprise Linux CoreOS - OpenStack Image (QCOW)_ and decompress the image..
Doubled periods at the end of line 22.

2019-11-18 19:04 UTC, maxwelldb commented on modules/installation-osp-creating-image.adoc
> +The OpenStack image must be decompressed before being used by the cluster.
"You must decompress the OpenStack image before the cluster can use it."

Otherwise, :+1:

2019-11-18 19:19 UTC, maxwelldb approved these changes
Thanks! Just waiting on a nod from QE before merging.

2019-12-02 08:28 UTC, morenod approved these changes
lgtm

2019-12-02 14:19 UTC, kalexand-rh commented
Thank you, @morenod! Since Max says that this change was just pending QE, I'm going to merge it.

2019-12-02 14:20 UTC, merged

2019-12-02 14:20 UTC, kalexand-rh commented
/cherrypick enterprise-4.2

2019-12-02 14:20 UTC, kalexand-rh commented
/cherrypick enterprise-4.3