Adding MCG and OCP Operator
openshift/openshift-docs pull request #18678
Opened 2019-12-16 17:24 UTC by apinnick

2019-12-16 19:46 UTC, jwmatthews commented on migration/migrating-3-4/migrating-openshift-3-to-4.adoc
> +* The cluster on which the CAM tool is installed must have a 50 GB PVC for the MCG replication repository.
We are looking more at confirming this.

@jmontleon please update as we learn what the default requirements are.

2019-12-16 19:59 UTC, jwmatthews requested changes

2019-12-16 19:59 UTC, jwmatthews commented on migration/migrating-3-4/migrating-openshift-3-to-4.adoc
> +MCG, which is installed automatically on the same cluster as the CAM tool, does not support the snapshot copy method.
Please remove the text on 'does not support the snapshot copy method.'
Snapshots are a feature of services providing volumes, block devices, etc, not for object storage.

A user who is using MCG for Object Store could still perform a snapshot on their PVs if the PV backing store supported snapshots.

but MCG/S3, etc is not involved in the snapshot piece.

2019-12-16 19:59 UTC, jwmatthews commented on migration/migrating-4-4/migrating-openshift-4_1-to-4.adoc
> +* The cluster on which the CAM tool is installed must have a 50 GB PVC for the MCG replication repository.
Similar to 3.x side, we are confirming what the default requirement is.

2019-12-16 19:59 UTC, jwmatthews commented on migration/migrating-4-4/migrating-openshift-4_1-to-4.adoc
> +MCG does not support the snapshot copy method.
Please remove this text

2019-12-16 19:59 UTC, jwmatthews commented on migration/migrating-4-4/migrating-openshift-4_1-to-4.adoc
> +:targetcluster-4_1-4_2!:* The cluster on which the CAM tool is installed must have a 50 GB PVC for the MCG replication repository.
Verifying the actual requirement

2019-12-16 19:59 UTC, jwmatthews commented on modules/migration-installing-cam-operator-ocp-4.adoc
> +.. Scroll or type a keyword into the *Filter by keyword* field (in this case, *Migration*) to find the *CAM Operator*.
I'm not aware of any name change to 'CAM Operator', it should be 'Cluster Application Migration Operator'.

2019-12-16 22:31 UTC, jwmatthews commented
@apinnick please keep this PR on hold and do _not_ merge it.

The support for MCG/NooBaa will not be part of our 1.0.1 release.   
We will likely bring it in with 1.1.0 or perhaps 1.1.1, it's not ready for what we need in 1.0.1.

2019-12-17 09:34 UTC, apinnick commented
> @apinnick please keep this PR on hold and do _not_ merge it.
> 
> The support for MCG/NooBaa will not be part of our 1.0.1 release.
> We will likely bring it in with 1.1.0 or perhaps 1.1.1, it's not ready for what we need in 1.0.1.

@jwmatthews Understood. I will make the changes and keep this PR as 'draft PR' so that it won't be merged.

2020-02-25 10:00 UTC, apinnick commented
Closing this PR and opening new one

2020-02-25 10:00 UTC, closed without merging