Change the apiVersion to apps/v1
openshift/openshift-docs pull request #19568
Opened 2020-02-06 14:13 UTC by rh-max

2020-02-06 14:15 UTC, lilic approved these changes
Thanks! 👍 

/lgtm

2020-02-06 14:15 UTC, rh-max commented
@soltysh Changing apiVersion per your request. The other parts of the docs will do the same shortly.

2020-02-06 14:16 UTC, LiliC commented
Thanks for spotting it @soltysh :)

2020-02-06 14:16 UTC, rh-max commented
@LiliC Thank you!
@juzhao Could you please review the change?

2020-02-07 09:13 UTC, juzhao commented
LGTM if the change is for 4.4 only, 4.3 can still use "extensions/v1beta1"

2020-02-07 11:52 UTC, rh-max commented
@juzhao According to @LiliC and @soltysh, while `extensions/v1beta1` _can_ be used in 4.3, it is deprecated and should be avoided.

2020-02-07 14:28 UTC, LiliC commented
4.3 should also follow best practices and migrate from using the extensions/v1beta1, so we should avoid mentioning or encouraging users to use it. There are even some ideas of adding alerts to 4.3 that would fire if you are using that api. So switching to both 4.3 and 4.4 is the right thing to do here.

2020-02-07 15:05 UTC, lilic requested changes

2020-02-07 15:05 UTC, LiliC commented on modules/monitoring-configuring-monitoring-for-an-application.adoc
> -apiVersion: extensions/v1beta1
I get the following error when trying to apply this file via the UI in a 4.3 cluster:

> An error occurred
> Error "Required value" for field "spec.selector".

2020-02-07 15:21 UTC, LiliC commented on modules/monitoring-configuring-monitoring-for-an-application.adoc
> -apiVersion: extensions/v1beta1
We need to also update the very last thing to replace it with:

> oc port-forward -n openshift-user-workload-monitoring svc/prometheus-operated 9090

we did not include namespace.

2020-02-07 15:47 UTC, LiliC commented on modules/monitoring-configuring-monitoring-for-an-application.adoc
> -apiVersion: extensions/v1beta1
There was a bug in the app can you also change the image to: `quay.io/brancz/prometheus-example-app:v0.2.0`

This is my final deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 1
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: quay.io/brancz/prometheus-example-app:v0.2.0
        ports:
        - name: web
          containerPort: 8080
---
```

2020-02-11 12:34 UTC, soltysh approved these changes
lgtm, except the comment from Lili

2020-02-11 13:15 UTC, lilic approved these changes
👍 
/lgtm

2020-02-11 13:17 UTC, rh-max commented
Thanks @soltysh for reporting, thanks @LiliC and @juzhao for help.
@bmcelvee, could you

2020-02-17 19:40 UTC, bmcelvee commented
LGTM - before merging, I can't seem to find where these are building in the docs. Would you mind linking preview builds?

Thanks! :)

2020-02-24 14:25 UTC, lilic reviewed
/lgtm 

👍

2020-02-24 14:36 UTC, rh-max commented
@bmcelvee The only updates that go to the published docs are in`modules/monitoring-deploying-a-sample-service.adoc`, as built here https://monitoring-change-apiversion--ocpdocs.netlify.com/openshift-enterprise/latest/monitoring/monitoring-your-own-services.html#deploying-a-sample-service_monitoring-your-own-services (please re-check, contains two total fixes now). The rest of the updates went into the docs that might be published in a future release, but are currently not included and so are not available for a preview.

2020-02-24 15:26 UTC, merged

2020-02-24 15:27 UTC, bmcelvee commented
/cherrypick enterprise-4.3

2020-02-24 15:27 UTC, bmcelvee commented
/cherrypick enterprise-4.4