[WIP] Updating installation docs for GA
openshift/openshift-docs pull request #19910
Opened 2020-02-21 17:56 UTC by abrennan89

2020-03-10 17:20 UTC, maschmid commented on modules/serverless-uninstalling-knative-serving.adoc
> +$ oc delete crd knativeserving.operator.knative.dev
Should be `knativeservings.operator.knative.dev`   (note the plural)

2020-03-13 10:14 UTC, maschmid commented on serverless/installing_serverless/removing-openshift-serverless.adoc
> +Before you can remove other {ServerlessProductName} components, such as Knative Serving or Eventing, you must remove the {ServerlessOperatorName}.
I think it should be the other way around? (You should delete KnativeServing first, then the serverless-operator.)

2020-03-17 08:40 UTC, maschmid commented
QE approved

2020-03-17 16:37 UTC, jboxman commented
@abrennan89, I think this was introduced somewhere:

```
Building OpenShift Container Platform for branch 'abrennan89-install'
asciidoctor: ERROR: <stdin>: line 24: level 0 sections can only be used when doctype is book
```

2020-03-17 18:02 UTC, jboxman requested changes
I'm still mentally working through "To ... enter the following command", but based on IBM that is the approach.

Otherwise, some comments and LGTM.

2020-03-17 18:02 UTC, jboxman commented on modules/serverless-uninstalling-knative-serving.adoc
> +. Once the command has completed and all pods have been removed from the `knative-serving` namespace, delete the namespace:
s/namespace, delete the namespace:/namespace, delete the namespace by entering the following command/

2020-03-17 18:02 UTC, jboxman commented on modules/serverless-uninstalling-knative-serving.adoc
> +. Remove Knative Serving:
Per IBM,

_To remove Knative Service, enter the following command:_

2020-03-17 18:34 UTC, abrennan89 commented on modules/serverless-uninstalling-knative-serving.adoc
> +. Once the command has completed and all pods have been removed from the `knative-serving` namespace, delete the namespace:
Ack, thanks!

2020-03-17 18:57 UTC, abrennan89 commented
This PR applies for OCP 4.3 and any subsequent releases (4.4, 4.5, afaik)

2020-03-17 20:59 UTC, jboxman approved these changes

2020-03-17 20:59 UTC, merged

2020-03-17 20:59 UTC, jboxman commented
/cherry-pick enterprise-4.4

2020-03-17 20:59 UTC, jboxman commented
/cherry-pick enterprise-4.3