BZ#1807121 - NAD requires a 'name' for the configuration
openshift/openshift-docs pull request #20007
Opened 2020-02-25 18:40 UTC by aburdenthehand

Minor change to the NAD configuration to add a 'name' field and annotation (shuffling the others down).

I checked on our 2.2 environment and this also has an impact there.

cherrypick to enterprise-4.3 and enterprise-4.4

2020-02-26 09:50 UTC, alexxa approved these changes
Looks good to me. Thanks.

2020-02-27 17:11 UTC, phoracek requested changes
We will need the same fix for the PXE docs.

2020-02-27 17:12 UTC, phoracek approved these changes
I was too quick to comment. PXE is fine already.

2020-03-09 10:31 UTC, merged

2020-03-09 10:36 UTC, aburdenthehand commented
/cherrypick enterprise-4.3

2020-03-09 10:39 UTC, aburdenthehand commented
/cherrypick enterprise-4.4