nic partitioning for SRIOV devices
openshift/openshift-docs pull request #20548
Opened 2020-03-18 14:57 UTC by lamek

2020-03-18 19:20 UTC, jboxman requested changes
@lamek, suggested some changes. In the future I want to go back and scrub all of SR-IOV, after the topics are split out.

2020-03-18 19:20 UTC, jboxman commented on modules/nw-sriov-nic-partitioning.adoc
> +In some cases, you may want to split virtual functions (VFs) from the same physical function (PF) into multiple resource pools. For example, you may want some of the VFs with the default driver loade
s/may/might/

2020-03-18 19:20 UTC, jboxman commented on modules/nw-sriov-nic-partitioning.adoc
> +For example, the following YAML shows the selector for an interface named netpf0 with VF 2 through 7:
`netpf0`

2020-03-18 19:20 UTC, jboxman commented on modules/nw-sriov-nic-partitioning.adoc
> +You can select VFs from the same PF by different policy CRs as long as the following requirements are met:
s/by/by using/

2020-03-18 19:20 UTC, jboxman commented on modules/nw-sriov-nic-partitioning.adoc
> +You can select VFs from the same PF by different policy CRs as long as the following requirements are met:
s/as long as/if/

2020-03-18 19:20 UTC, jboxman commented on modules/nw-sriov-nic-partitioning.adoc
> +* The VF index should be in in range of `0` to `<numVfs>-1`. For example, if you have a policy with `numVfs` 8, then the `<FirstVF>` should not be smaller than 0, and the `<LastVF>` should not larger
s/in in/in/

2020-03-18 19:20 UTC, jboxman commented on modules/nw-sriov-nic-partitioning.adoc
> +* The VF index should be in in range of `0` to `<numVfs>-1`. For example, if you have a policy with `numVfs` 8, then the `<FirstVF>` should not be smaller than 0, and the `<LastVF>` should not larger
s/with `numVfs` 8/with `numVfs` set to `8`/

2020-03-18 19:20 UTC, jboxman commented on modules/nw-sriov-nic-partitioning.adoc
> +* The `numVfs` should be identical for policies that select the same PF.
All s/should/must/ I think

2020-03-18 19:20 UTC, jboxman commented on modules/nw-sriov-nic-partitioning.adoc
> +The policy `policy-net-1` defined a resource pool `net-1` which contains the VF 0 of PF netpf0, with the default VF driver. The policy `policy-net-1-dpdk` defined another resource pool `net-1-dpdk` w
s/which/that/

`netpf0`

`0`

`8`

`15`

`vfio` probably

2020-03-18 20:27 UTC, lamek commented
@pliurh can you PTAL?

2020-03-19 02:10 UTC, pliurh commented
LGTM

2020-03-19 18:06 UTC, merged

2020-03-19 18:06 UTC, lamek commented
/cherrypick enterprise-4.4