Enhancement to Kuryr quota documentation
openshift/openshift-docs pull request #20722
Opened 2020-03-27 14:34 UTC by luis5tb

This adds information about the number of amphora VMs needed.
In addition it fixes a typo regarding the usage of CGO_ENABLED,
that is related to the amphora VMs.

2020-03-27 14:36 UTC, luis5tb commented
/bugzilla refresh

2020-03-30 15:36 UTC, eurijon commented
lgtm

2020-03-30 15:42 UTC, maxwelldb requested changes

2020-03-30 15:42 UTC, maxwelldb commented on modules/installation-osp-default-kuryr-deployment.adoc
> +|Resource                | Value
This section will be overwritten by my in-flight changes later, anyway. I'll need to make sure to keep the LB rows. :)

2020-03-30 15:42 UTC, maxwelldb commented on modules/installation-osp-default-kuryr-deployment.adoc
> +considered when deciding the OpenStack deployment size. Note just the
"Although the quota does not account for load balancer VM resources, you must consider them when you decide on the {rh-openstack} deployment's size. In the end, the installation will have more than 50 load balancers; the clusters must be able to accommodate them."

2020-03-31 18:06 UTC, maxwelldb requested changes
Minor stuff.

2020-03-31 18:06 UTC, maxwelldb commented on modules/installation-osp-default-kuryr-deployment.adoc
> +|Load balancer listeners | 500 - 1 needed per Service exposed port
Service exposed -> Service-exposed

2020-03-31 18:06 UTC, maxwelldb commented on modules/installation-osp-default-kuryr-deployment.adoc
> +|Load balancer pools     | 500 - 1 needed per Service exposed port
Service exposed -> Service-exposed

2020-03-31 18:06 UTC, maxwelldb commented on modules/installation-osp-default-kuryr-deployment.adoc
> +consider them when you decide on the {rh-openstack} deployment's size. In the
On second thought:

"The quota does not account for load balancer resources, but you must consider these resources when you decide the {rh-openstack} deployment's size."

2020-04-01 21:04 UTC, maxwelldb approved these changes

2020-04-01 21:04 UTC, maxwelldb commented
@eurijon Can you :+1: this in its current state?

2020-04-02 07:24 UTC, eurijon commented
> @eurijon Can you +1 this in its current state?

Yeah, it looks good to me! :+1:

2020-04-02 12:49 UTC, maxwelldb approved these changes

2020-04-03 13:13 UTC, merged

2020-04-03 13:14 UTC, maxwelldb commented
/cherry-pick enterprise-4.2

2020-04-03 13:14 UTC, maxwelldb commented
/cherry-pick enterprise-4.3

2020-04-03 13:15 UTC, maxwelldb commented
/cherry-pick enterprise-4.4