CNV - BZ#1818068 removing supplmentary NAD example
openshift/openshift-docs pull request #20880
Opened 2020-04-03 12:46 UTC by aburdenthehand

BZ#1818068, removing the supplementary example for adding NAD outside of namespace. This is not possible.

cp to enterprise-4.4

2020-04-03 13:09 UTC, phoracek requested changes

2020-04-03 13:09 UTC, phoracek commented on modules/cnv-creating-bridge-nad-cli.adoc
> -+
Can we add a note explaining that the NetworkAttachmentDefinition is available only to VMs within the same Namespace?

2020-04-03 13:26 UTC, phoracek approved these changes
Thanks!

2020-04-27 13:04 UTC, yossisegev commented
LGTM (CNV Network QE)

2020-04-27 13:30 UTC, ousleyp commented
/lgtm

2020-04-27 13:56 UTC, merged

2020-04-27 13:56 UTC, aburdenthehand commented
/cherry-pick enterprise-4.4

2020-04-27 13:56 UTC, aburdenthehand commented
/cherry-pick enterprise-4.3