Add use case/example for oc rsync
openshift/openshift-docs pull request #2098
Opened 2016-05-13 21:20 UTC by sallyom

2016-05-18 13:52 UTC, sallyom commented
@danmcp @bparees ptal, thanks

2016-05-18 13:55 UTC, bparees commented
I think @danmcp was looking for a full example of copying a db archive into a pod and then rsh'ing into the pod and restoring it. Though that's going to have a lot of overlap w/ what's going into the v2 migration guide.

2016-05-18 13:56 UTC, bparees commented on dev_guide/copy_files_to_container.adoc
> +You can use the CLI to copy local files to or from a remote directory in a container.  This is a useful tool for copying database archives to and from your pods for backup and restore purposes.  Note
path should be absolute (/var/lib/......) but i'm not sure we want to specify this here anyway.  There could be other database images that use other paths, this only covers the images we provide.  Doc about what path specific images use for volumes belongs w/ the image specific documentation.

2016-05-18 14:05 UTC, danmcp commented
> I think @danmcp was looking for a full example of copying a db archive into a pod and then rsh'ing into the pod and restoring it. Though that's going to have a lot of overlap w/ what's going into the v2 migration guide.

@bparees @sallyom 
I am looking for something close to that.  But export from a running v3 container and import to a running v3 container.  Even more generically I am looking for some pointers on how to work with running database containers.  Tuning (like running statistics/analyze) would be another example we could show.

2016-07-01 17:00 UTC, ahardin-rh commented on dev_guide/copy_files_to_container.adoc
> +Note: MySQL is used here, but replace 'mysql|MYSQL' with 'pgsql|PGSQL' or 'mongodb|MONGODB' to use
Let's place this note in a note box

[NOTE]
====
MySQL is used here, but replace 'mysql|MYSQL' with 'pgsql|PGSQL' or 'mongodb|MONGODB' to use any of the three supported databases. 
====

2016-07-01 17:09 UTC, ahardin-rh commented on dev_guide/copy_files_to_container.adoc
> +'/var/lib/<db-service>/data' directory:
Replace '/var/lib/<db-service>/data' with  *_/var/lib/<db-service>/data_*

2016-07-01 17:12 UTC, ahardin-rh commented
@sallyom @danmcp @bparees picking this back up. Made a few style comments, but from the above comments it looks like you're still fleshing this out.

2016-07-01 18:33 UTC, bparees commented
@sallyom based on @danmcp's comments:

> I am looking for something close to that. But export from a running v3 container and import to a running v3 container. 

can you update this to include exporting from the db pod, then restoring to a different db pod?

> Even more generically I am looking for some pointers on how to work with running database containers. Tuning (like running statistics/analyze) would be another example we could show.

i think this can be a separate PR/item.

2016-07-01 18:52 UTC, sallyom commented
@bparees, sure, I'm hoping to get to this by the end of the day, if not first thing Tues, thanks for clarifying the comment above.  @ahardin-rh thanks for the style review, I'll get it fixed up.

2016-07-02 15:30 UTC, sallyom commented
@bparees, I updated to include the export of (already existing) archive files to local /tmp and import from local /tmp.  Since each db service has different backup/restore cmds, we could omit the restore cmds and link to the migration doc instead for the db-specific cmds.  Should we hold off on this PR until then or are the specific restore cmds useful here?

2016-07-02 15:51 UTC, bparees commented
hm. you're also already omitting the backup commands.

I suggest you simplify this down to one good example that shows the full flow (oc rsh to old pod, run backup commands, oc rsync to local, oc rsync to new pod, oc rsh to new pod, run restore commands) for one DB system.  And then reference the migration doc like "to see exact commands for all our supported images, see the migration doc" (of course that means this PR can't merge until the migration doc is merged)

2016-10-10 17:50 UTC, sallyom commented
@bparees, finally got back to this PR.  I added one mysql example that shows:
 - link to migration doc to find exact db backup/restore cmds
 - backup cmd for mysql 
 - rsync archive file to local from existing running db pod
 - oc new-app 2nd mysql pod w/ unique service name and persistent storage
 - rsync archive file from local to running 2nd mysql pod
 - restore db using mysql source command into the new persistent mysql pod

@ahardin-rh please review, not sure if I referenced the migration doc link correctly.  thanks!

2016-10-10 17:57 UTC, bparees requested changes
couple nits and lgtm.

2016-10-10 17:57 UTC, bparees commented on dev_guide/copy_files_to_container.adoc
> +[[copying-usage-with-database-restore]]
match the anchor text w/ the actual heading text

2016-10-10 17:57 UTC, bparees commented on dev_guide/copy_files_to_container.adoc
> +== Usage With Database Restore
change title to "Backing up and Restoring Databases"

2016-10-10 18:11 UTC, sallyom commented on dev_guide/copy_files_to_container.adoc
> +== Usage With Database Restore
changed, thanks

2016-10-10 18:11 UTC, sallyom commented on dev_guide/copy_files_to_container.adoc
> +[[copying-usage-with-database-restore]]
changed, thanks

2016-10-10 18:18 UTC, sallyom commented
@ahardin-rh, ready for any style edits you have :) thanks

2016-10-10 19:30 UTC, ahardin-rh commented
Work continued in https://github.com/openshift/openshift-docs/pull/3022

2016-10-10 19:30 UTC, closed without merging