DevExp RN additions
openshift/openshift-docs pull request #21241
Opened 2020-04-16 21:05 UTC by codyhoag

Preview: http://file.rdu.redhat.com/~choag/041620/rn-4.4-updates-4/release_notes/ocp-4-4-release-notes.html

2020-04-16 21:08 UTC, codyhoag commented
@adambkaplan this PR adds release notes for several of your DEVEXP comments. Can you review this to make sure I got everything right? Thanks!

2020-04-16 23:08 UTC, adambkaplan commented
/assign @adambkaplan

2020-04-20 18:12 UTC, adambkaplan requested changes
@codyhoag a few nits.

2020-04-20 18:12 UTC, adambkaplan commented on release_notes/ocp-4-4-release-notes.adoc
> +Operator, which creates a CronJob to run periodic image pruning.
Late breaking issue - cluster admins will need to enable this feature in 4.4.

See https://bugzilla.redhat.com/show_bug.cgi?id=1825284

2020-04-20 18:12 UTC, adambkaplan commented on release_notes/ocp-4-4-release-notes.adoc
> +block storage types like Elastic Block Store on Amazon Web Services.
```suggestion
registry. This lets you use `ReadWriteOnce` persistent volumes, such as Elastic Block Storage on AWS.
When using such storage types, the `Recreate` rollout strategy must be used to successfully upgrade an {product-title} cluster.
```

2020-04-20 18:12 UTC, adambkaplan commented on release_notes/ocp-4-4-release-notes.adoc
> +transition.
```suggestion
You can also use commands like `oc wait` to wait for a specific build phase to be reached.
```

2020-04-20 18:40 UTC, codyhoag commented
@adambkaplan thanks for your feedback. Can you take a second look?

2020-04-21 01:56 UTC, adambkaplan requested changes
Minor nits.

2020-04-21 01:56 UTC, adambkaplan commented on release_notes/ocp-4-4-release-notes.adoc
> +You can now enable automatic image pruning. This is not available by default;
```suggestion
You can now enable automatic image pruning. This is not turned on by default;
```

2020-04-21 01:56 UTC, adambkaplan commented on release_notes/ocp-4-4-release-notes.adoc
> +{product-title} 4.4. This automation is managed by the Registry Operator, which
```suggestion
{product-title} 4.4. This automation is managed by the Image Registry Operator, which
```

2020-04-21 13:09 UTC, codyhoag commented
@adambkaplan I made those additional adjustments. Let me know if there's anything else. Thanks!

2020-04-21 17:51 UTC, adambkaplan approved these changes
/lgtm

2020-04-21 18:18 UTC, bobfuru commented on release_notes/ocp-4-4-release-notes.adoc
> +registry. This lets you use `ReadWriteOnce` persistent volumes, such as Elastic
s/such as Elastic Block Storage on AWS/such as AWS Elastic Block Store/
(This is how we reference it [elsewhere](https://docs.openshift.com/container-platform/4.3/storage/persistent_storage/persistent-storage-aws.html) in the docs.)

2020-04-21 18:19 UTC, bobfuru commented
One small nit and then LGTM.

2020-04-21 18:25 UTC, merged