Suggested changes to the log forwarding section
openshift/openshift-docs pull request #21391
Opened 2020-04-22 15:14 UTC by mburke5678

https://docs.google.com/document/d/1abKabUALXa2O6-cbFu8iGY7uo5vcLR3ago9JyQC7xjE/edit?ts=5e9ee5b7#

2020-04-22 17:54 UTC, mburke5678 commented
@sichvoge PTAL

2020-05-05 15:49 UTC, sichvoge requested changes
Two small changes but otherwise LGTM

2020-05-05 15:49 UTC, sichvoge commented on modules/cluster-logging-collector-log-forward.adoc
> +The cluster logging Log Forwarding API enables administrators to configure custom pipelines to send your container and node logs to specific endpoints within or outside of your cluster. You can send
How about changing this to "The Log Forwarding API" only?

2020-05-05 15:49 UTC, sichvoge commented on modules/cluster-logging-collector-log-forward.adoc
> += Forwarding cluster logs using the Log Forwarding API
We should remove "cluster" to be consistent with the other sub section.

2020-05-05 19:54 UTC, mburke5678 commented
@jcantrill @alanconway PTAL
@sichvoge proposed merging the two log forwarding topics in hte docs into one topic, plus other suggestions in a Google doc. [1] 
Please take a look at the preview [2] and let us know what you think.
[1] https://suggested-changes-to-the-log-forwarding-section--ocpdocs.netlify.app/openshift-enterprise/latest/logging/config/cluster-logging-external.html
[2] https://suggested-changes-to-the-log-forwarding-section--ocpdocs.netlify.app/openshift-enterprise/latest/logging/config/cluster-logging-external.html

2020-05-11 18:37 UTC, mburke5678 commented
@jcantrill @alanconway PTAL

2020-05-11 18:41 UTC, mburke5678 commented
Preview: https://suggested-changes-to-the-log-forwarding-section--ocpdocs.netlify.app/openshift-enterprise/latest/logging/config/cluster-logging-external.html

2020-05-12 07:37 UTC, sichvoge commented
@mburke5678 based on some recent discussions, we decided to not restrict forwarding using Fluentd's forward protocol to Fluentd only. It seems that there are systems that accept data using that protocol as well and we should handle it like the syslog protocol.

Obviously, it is important to note that like the syslog protocol, we only support the sending side not the receiver.

Therefore, can we make the appropriate changes so it looks similar to syslog and remove any text that restricts only to fluentd. For example: _s/Forwarding logs to another Fluentd instance/Forwarding logs using the out_forward protocol_

2020-05-12 15:10 UTC, alanconway commented
> @mburke5678 based on some recent discussions, we decided to not restrict forwarding using Fluentd's forward protocol to Fluentd only. It seems that there are systems that accept data using that protocol as well and we should handle it like the syslog protocol.

Makes sense. The fluent forward protocol is supported by several log stores and log processing tools. 

> Therefore, can we make the appropriate changes so it looks similar to syslog and remove any text that restricts only to fluentd. For example: _s/Forwarding logs to another Fluentd instance/Forwarding logs using the out_forward protocol_

I would suggest "Forwarding logs using the Fluent forward protocol"

Then name of the protocol is "forward", but you need to prefix with "Fluent" as it's a pretty vague name otherwise. The names "in_forward" and "out_forward" refer to the fluentd input/output *plugins* that speak the receiving/sending ends of the "forward" protocol.

2020-05-12 16:06 UTC, mburke5678 commented
@sichvoge @alanconway PTAL: http://file.rdu.redhat.com/~mburke/Suggested-changes-to-the-log-forwarding-section/logging/config/cluster-logging-external.html#cluster-logging-collector-log-forward_cluster-logging-external

2020-05-15 16:30 UTC, sichvoge commented
PM: ack :)

2020-05-15 18:23 UTC, jcantrill approved these changes
minor edit that @alanconway introduced https://github.com/openshift/cluster-logging-operator/pull/532 for GA

2020-05-15 19:03 UTC, merged

2020-05-15 20:18 UTC, mburke5678 commented
/cherrypick enterprise-4.5