Understanding Buffer Chunk Limiting for Fluentd documentation is missing the prerequisite section
openshift/openshift-docs pull request #21458
Opened 2020-04-23 20:59 UTC by mburke5678

https://bugzilla.redhat.com/show_bug.cgi?id=1827182

2020-04-23 21:01 UTC, mburke5678 commented
@periklis @koep Please see my questions in https://bugzilla.redhat.com/show_bug.cgi?id=1827182#c1

2020-04-24 14:53 UTC, mburke5678 commented
@periklis @koep   PTAL

2020-04-24 15:07 UTC, koep commented
@mburke5678 LGTM

2020-04-25 07:35 UTC, periklis requested changes

2020-04-25 07:35 UTC, periklis commented on modules/nodes-cluster-overcommit-buffer-chunk.adoc
> +To modify the `BUFFER_QUEUE_LIMIT`, `FILE_BUFFER_LIMIT`, or `BUFFER_SIZE_LIMIT` parameters
As mentioned in [BZ-1827182](https://bugzilla.redhat.com/show_bug.cgi?id=1827182) you a cannot modify `BUFFER_QUEUE_LIMIT` directly.

2020-04-27 06:39 UTC, periklis approved these changes
LGTM

2020-05-06 01:14 UTC, xltian commented
@anpingli Can you please take a look at this change?

2020-05-06 01:45 UTC, anpingli approved these changes
LGTM

2020-05-06 13:35 UTC, merged

2020-05-06 13:44 UTC, mburke5678 commented
/cherrypick enterprise-4.2

2020-05-06 13:49 UTC, mburke5678 commented
/cherrypick enterprise-4.3

2020-05-06 13:54 UTC, mburke5678 commented
/cherrypick enterprise-4.4

2020-05-06 13:58 UTC, mburke5678 commented
/cherrypick enterprise-4.5