Bug 1832293, update metrics for Pods per node
openshift/openshift-docs pull request #21992
Opened 2020-05-11 17:07 UTC by ahardin-rh

https://bugzilla.redhat.com/show_bug.cgi?id=1832293

2020-05-11 18:21 UTC, chaitanyaenr approved these changes
LGTM

2020-05-11 18:22 UTC, chaitanyaenr commented
@RobertKrawitz PTAL.

2020-05-11 18:43 UTC, RobertKrawitz commented
/hold

I'm in the process of testing 500 pods/node on 4.4, but we don't want to increase 4.3 without also increasing 4.4.

2020-05-14 17:13 UTC, RobertKrawitz commented
500 pods/node test succeeded on 4.4.3.  So,
/hold cancel

2020-05-14 17:13 UTC, RobertKrawitz commented
/hold cancel

2020-05-14 23:13 UTC, RobertKrawitz requested changes

2020-05-14 23:13 UTC, RobertKrawitz commented on modules/openshift-cluster-maximums.adoc
>  | 250
Needs to go to 500.

2020-05-14 23:14 UTC, RobertKrawitz commented
I see the 4.3 tested max was raised; the 4.4 does also.

2020-05-15 16:35 UTC, ahardin-rh commented
@RobertKrawitz Updated. Thanks!

2020-05-15 16:35 UTC, merged

2020-05-15 16:37 UTC, ahardin-rh commented
/cherrypick enterprise-4.4

2020-05-15 16:38 UTC, ahardin-rh commented
/cherrypick enterprise-4.5