Added documentation abouth Insights tab (CCXDEV-1285)
openshift/openshift-docs pull request #22066
Opened 2020-05-13 09:36 UTC by mmuehlfeldRH

This update adds documentation about the Insights tab on cloud.redhat.com to the "Support" section of the docs.

This doc enhancement is for OpenShift 4.5.

@openshift/team-documentation

2020-05-13 10:03 UTC, radekvokal commented
Reviewed by CCX PM - ack

2020-05-13 11:19 UTC, janzeleny requested changes

2020-05-13 11:19 UTC, janzeleny commented on modules/displaying-potential-issues-of-your-cluster.adoc
> +This section describes how to display the Insights report the {cloud-redhat-com} has created.
This translates to statement that OCM generates the Insights report for you which is factually wrong and might be confusing in the future when OCM is not the only UI we use. My choice of words would be something in lines of "Insights generates the report, OCM displays it".

2020-05-13 11:19 UTC, janzeleny commented on modules/displaying-potential-issues-of-your-cluster.adoc
> +* A list of issues {cloud-redhat-com} has detected, prioritized by risk.
Same as above, OCM does not detect the issues, just shows the results.

2020-05-13 11:19 UTC, janzeleny commented on modules/displaying-potential-issues-of-your-cluster.adoc
> +* *Your cluster passed all health checks*, if {cloud-redhat-com} did not identify any issues.
Same as above, OCM does not detect the issues, just shows the results.

2020-05-13 11:19 UTC, janzeleny commented on modules/displaying-potential-issues-of-your-cluster.adoc
> +* *No health checks to display*, if {cloud-redhat-com} has not yet analyzed the cluster. The analysis starts shortly after the cluster has been installed and connected to the internet.
Same as above, OCM does not detect the issues, just shows the results.

2020-05-13 11:19 UTC, janzeleny commented on support/remote_health_monitoring/using-insights-to-identify-issues-of-your-cluster.adoc
> +{cloud-redhat-com} repeatedly analyzes the data Insights Operator sends. Users of {product-title} can display the report on the *Insights* tab of each cluster in {cloud-redhat-com}.
Same as above, OCM does not detect the issues, just shows the results.

2020-05-13 14:24 UTC, janzeleny commented
Thanks for addressing my comments - ack

2020-05-18 11:05 UTC, mmuehlfeldRH commented
@openshift/team-documentation , can you please review the PR and merge it if everything is OK? Thanks.

2020-05-18 17:44 UTC, ahardin-rh commented on modules/displaying-potential-issues-of-your-cluster.adoc
> +. Click to the cluster's name to display the details of the cluster.
s/to the cluster's name/the cluster's name

2020-05-18 17:45 UTC, ahardin-rh commented on support/remote_health_monitoring/using-insights-to-identify-issues-of-your-cluster.adoc
> += Using Insights to identify issues of your cluster
s/of your/with your

2020-05-18 17:50 UTC, ahardin-rh commented
@yapei Can you please provide a QE review? Thanks!

2020-05-20 22:27 UTC, ahardin-rh commented on modules/displaying-potential-issues-with-your-cluster.adoc
> += Displaying potential issues of your cluster
with your cluster

2020-05-21 08:20 UTC, yapei commented
@ahardin-rh  OpenShift UI QE didn't test this Insights feature, maybe this is owned by Insights team?

2020-05-21 15:30 UTC, ahardin-rh commented
@jneedle Can you or a member of your team provide QE review? Thanks!

2020-05-21 15:43 UTC, jneedle commented
Let me see if I can find someone on that team to have a look.

2020-05-22 08:43 UTC, mmuehlfeldRH commented on modules/displaying-potential-issues-with-your-cluster.adoc
> += Displaying potential issues of your cluster
Sorry. I missed this one. Fixed.

2020-05-22 08:49 UTC, tisnik approved these changes
LGTM @mmuehlfeldRH

2020-05-22 09:01 UTC, bond95 reviewed
Basically looks good, but could we say a little bit more about Remediate modal window and maybe slightly more describe each Total risk level. WDYT?

2020-05-22 10:38 UTC, mmuehlfeldRH commented
@bond95 I added the risk levels to step 3 (second bullet), and updated the last paragraph in step 4.

2020-05-22 10:40 UTC, bond95 approved these changes
LGTM, thank you!

2020-05-22 14:55 UTC, ahardin-rh commented
Thank you, all!

2020-05-22 14:55 UTC, merged

2020-05-22 14:55 UTC, ahardin-rh commented
/cherrypick enterprise-4.5