Fix Deployment sidecar example
openshift/openshift-docs pull request #22301
Opened 2020-05-20 01:31 UTC by jboxman

- https://github.com/openshift/openshift-docs/issues/22215

2020-05-22 18:42 UTC, tvieira requested changes

2020-05-22 18:42 UTC, tvieira commented on modules/ossm-automatic-sidecar-injection.adoc
> +        sidecar.istio.io/inject: "true"
This can be returned to its original position.

2020-05-22 18:45 UTC, tvieira commented
tagging @neal-timpe for visibility.

2020-05-27 16:58 UTC, neal-timpe approved these changes
LGTM

2020-05-27 17:10 UTC, sheriff-rh approved these changes
LGTM!

2020-05-27 19:07 UTC, merged

2020-05-27 19:07 UTC, jboxman commented
/cherry-pick enterprise-4.5

2020-05-27 19:07 UTC, jboxman commented
/cherry-pick enterprise-4.4