Fix errors in pruning commands
openshift/openshift-docs pull request #22302
Opened 2020-05-20 01:54 UTC by jboxman

- https://github.com/openshift/openshift-docs/issues/22258

2020-05-21 02:13 UTC, wzheng1 commented on modules/pruning-images.adoc
> +  schedule: "0 0 * * *" <1>
Acked by QE.

2020-05-21 07:16 UTC, rhpmali requested changes

2020-05-21 07:16 UTC, rhpmali commented on modules/pruning-groups.adoc
> +$ oc adm prune groups --sync-config==ldap-sync-config.yaml
Please remove one `=` from `--sync-config==` command

2020-05-21 07:16 UTC, rhpmali commented on modules/pruning-groups.adoc
> +$ oc adm prune groups --sync-config==ldap-sync-config.yaml --confirm
Please remove one `=` from `--sync-config==` command

2020-05-22 03:39 UTC, jboxman commented on modules/pruning-images.adoc
> +  schedule: "0 0 * * *" <1>
@wzheng1 thank you!

2020-05-22 03:40 UTC, jboxman commented on modules/pruning-groups.adoc
> +$ oc adm prune groups --sync-config==ldap-sync-config.yaml
@rhpmali, oops, thanks!

2020-05-22 03:45 UTC, merged

2020-05-22 03:45 UTC, jboxman commented
/cherry-pick enterprise-4.5

2020-05-22 03:45 UTC, jboxman commented
/cherry-pick enterprise-4.4

2020-05-22 03:45 UTC, jboxman commented
/cherry-pick enterprise-4.3

2020-05-22 03:45 UTC, jboxman commented
/cherry-pick enterprise-4.2

2020-05-22 03:49 UTC, rhpmali reviewed
Edit: added comment in correct place

2020-05-22 03:50 UTC, rhpmali commented on modules/pruning-groups.adoc
> +$ oc adm prune groups --sync-config=ldap-sync-config.yaml --confirm
Acked by QE.

2020-05-22 03:50 UTC, rhpmali commented on modules/pruning-groups.adoc
> +$ oc adm prune groups --sync-config=ldap-sync-config.yaml
Acked by QE.