sriov: update notes for mellanox dpdk
openshift/openshift-docs pull request #22417
Opened 2020-05-27 07:34 UTC by zshi-redhat

2020-05-27 21:20 UTC, jboxman commented
@zshi-redhat for what other version is this applicable?

2020-05-27 22:54 UTC, zshi-redhat commented
> @zshi-redhat for what other version is this applicable?

@jboxman it applies to 4.5, 4.4 and 4.3

2020-05-27 23:09 UTC, jboxman commented
@zshi-redhat, for 4.4 and 4.3, is this a doc fix or a change in functionality? If it's just a doc fix, I can merge it. If the functionality actually changed, I'm required to ask support and other stakeholders if it's okay to update the docs.

Does that make sense? Thanks!

2020-05-27 23:12 UTC, zshi-redhat commented
> @zshi-redhat, for 4.4 and 4.3, is this a doc fix or a change in functionality? If it's just a doc fix, I can merge it. If the functionality actually changed, I'm required to ask support and other stakeholders if it's okay to update the docs.

Hi Jason, good point! 
It is a doc fix, not adding new functions.
> 
> Does that make sense? Thanks!

Yes, makes sense.

2020-05-29 21:12 UTC, jboxman requested changes
@zshi-redhat, added a few comments.

2020-05-29 21:12 UTC, jboxman commented on modules/nw-sriov-configuring-device.adoc
> +For a Mellanox card to work in dpdk mode on Bare metal nodes, use the netdevice driver type and set `isRdma` to `true`.
`netdevice`

s/Bare metal/bare metal/

2020-05-29 21:12 UTC, jboxman commented on modules/nw-sriov-configuring-device.adoc
> +For a Mellanox card to work in dpdk mode on Bare metal nodes, use the netdevice driver type and set `isRdma` to `true`.
s/dpdk/DPDK/

2020-05-29 21:12 UTC, jboxman commented on modules/nw-sriov-configuring-device.adoc
> +For a Mellanox card to work in dpdk mode with Container-Native Virtualization (CNV), use the vfio-pci driver type and set `isRdma` to `false`.
s/dpdk/DPDK/

`vfio-pci`

2020-05-29 21:35 UTC, jboxman commented
Refs https://github.com/openshift/openshift-docs/pull/22456 because we need a product variable for CNV; Eventually this may need to change to _OpenShift Virtualization_.

2020-06-01 03:34 UTC, zshi-redhat commented on modules/nw-sriov-configuring-device.adoc
> +For a Mellanox card to work in dpdk mode with Container-Native Virtualization (CNV), use the vfio-pci driver type and set `isRdma` to `false`.
Done

2020-06-01 03:34 UTC, zshi-redhat commented on modules/nw-sriov-configuring-device.adoc
> +For a Mellanox card to work in dpdk mode on Bare metal nodes, use the netdevice driver type and set `isRdma` to `true`.
Done

2020-06-01 03:34 UTC, zshi-redhat commented on modules/nw-sriov-configuring-device.adoc
> +For a Mellanox card to work in dpdk mode on Bare metal nodes, use the netdevice driver type and set `isRdma` to `true`.
Done

2020-06-10 22:45 UTC, zshi-redhat commented
> @zshi-redhat, looks like this has a merge conflict.

@jboxman thanks for reminding! conflict resolved.

2020-06-10 23:42 UTC, jboxman approved these changes

2020-06-10 23:43 UTC, merged

2020-06-10 23:43 UTC, jboxman commented
/cherry-pick enterprise-4.5

2020-06-10 23:43 UTC, jboxman commented
/cherry-pick enterprise-4.4

2020-06-10 23:43 UTC, jboxman commented
/cherry-pick enterprise-4.3