[WIP] Change v1alpha1 to v1 in Serverless docs code samples
openshift/openshift-docs pull request #22608
Opened 2020-06-03 13:22 UTC by abrennan89

2020-06-03 13:46 UTC, bbrowning reviewed
Just one nit on the capitalization - otherwise, looks good!

2020-06-03 13:46 UTC, bbrowning commented on modules/configuring-scale-bounds-knative.adoc
> +ApiVersion: serving.knative.dev/v1
This should be a lowercase `a`

2020-06-03 13:48 UTC, cardil requested changes

2020-06-03 13:48 UTC, cardil commented on modules/configuring-scale-bounds-knative.adoc
> +ApiVersion: serving.knative.dev/v1
I'd not adding this here. This was a YAML fragment. By adding this it seems like this is fully working example, but it isn't.

2020-06-05 14:36 UTC, bmcelvee commented
LGTM - I'll merge and cherry pick as soon as I get a few cherry picks in the queue merged :)

2020-06-05 14:53 UTC, merged

2020-06-05 14:54 UTC, bmcelvee commented
/cherrypick enterprise-4.3

2020-06-05 14:54 UTC, bmcelvee commented
/cherrypick enterprise-4.4

2020-06-05 14:54 UTC, bmcelvee commented
/cherrypick enterprise-4.5