Disconnected cluster upgrade improvements for 4.5 RNs
openshift/openshift-docs pull request #23258
Opened 2020-06-24 14:58 UTC by codyhoag

2020-06-24 15:02 UTC, codyhoag commented
@LalatenduMohanty can you confirm this release note for the disconnected cluster upgrade improvements? I'll update the link here when the docs are available, which I'm tracking in your PR: #21993

2020-06-30 20:05 UTC, codyhoag commented
@LalatenduMohanty bump. Can you verify this release note for disconnected cluster upgrade improvements? Thanks!

2020-07-01 16:22 UTC, LalatenduMohanty requested changes

2020-07-01 16:22 UTC, LalatenduMohanty commented on release_notes/ocp-4-5-release-notes.adoc
> +restricted network environment.
> the Cluster Version Operator (CVO) now downloads the release image for a specific {product-title}
version and verifies whether the image has been compromised

It was always the case. However previously CVO could only verfiy the images if it has access to `mirror.openshift.com` or to `https://storage.googleapis.com/openshift-release/official/signatures`. Hence customers had to use `--force` while upgrading disconnected environments. 

So as part of 4.5 we have added feature where CVO can verify the release payload if the image signature is available as a ConfigMap. So customers do not need to `--force` anymore.

2020-07-01 16:22 UTC, LalatenduMohanty commented on release_notes/ocp-4-5-release-notes.adoc
> +restricted network environment.
Suggestion for the above text

```
CVO can now verify the release images if the image signature is available as a ConfigMap in the cluster during the upgrade process for a disconnected cluster.  This removes the need for using `--force` flag while doing upgrades in disconnected environment. 
```

2020-07-01 17:01 UTC, kalexand-rh commented on release_notes/ocp-4-5-release-notes.adoc
> +==== Disconnected cluster upgrade improvements
s/Disconnected/Restricted network

2020-07-01 17:01 UTC, kalexand-rh commented on release_notes/ocp-4-5-release-notes.adoc
> +//../updating/updating-disconnected-cluster.adoc#updating-restricted-network-cluster[Updating a restricted network cluster]
./updating/updating-restricted-network-cluster.adoc#updating-restricted-network-cluster[Updating a restricted network cluster]

2020-07-01 20:11 UTC, merged