Monitor your own workload - RNs 4.5
openshift/openshift-docs pull request #23270
Opened 2020-06-24 18:42 UTC by codyhoag

2020-06-24 18:43 UTC, codyhoag commented
@rh-max I noticed you were working on this in #22879. Can you confirm this release note is accurate?

2020-07-01 15:29 UTC, codyhoag commented
@rh-max bump. Can you take a look at this 4.5 release note for monitoring?

2020-07-01 15:39 UTC, rh-max commented
@openshift/openshift-team-monitoring Could you PTAL?

2020-07-02 17:32 UTC, rh-max requested changes
Hi @codyhoag, I've made a few suggestions to make some items more precise and to call the Technology Preview in question the same way as done in the main docs.

2020-07-02 17:32 UTC, rh-max commented on release_notes/ocp-4-5-release-notes.adoc
> +==== Monitor your own workload (Technology Preview)
```suggestion
==== Monitor your own services (Technology Preview)
```

2020-07-02 17:32 UTC, rh-max commented on release_notes/ocp-4-5-release-notes.adoc
> +own cluster workload:
```suggestion
own services:
```

2020-07-02 17:32 UTC, rh-max commented on release_notes/ocp-4-5-release-notes.adoc
> +[id="ocp-4-5-monitor-your-own-workload-tp"]
```suggestion
[id="ocp-4-5-monitor-your-own-services-tp"]
```

2020-07-02 17:32 UTC, rh-max commented on release_notes/ocp-4-5-release-notes.adoc
> +* Allow cross-correlation of in-cluster metrics.
```suggestion
* Allow cross-correlation of the metrics of your own service with the cluster metrics.
```

2020-07-02 17:32 UTC, rh-max commented on release_notes/ocp-4-5-release-notes.adoc
> +* Allow user workload monitoring metrics in user namespaces in recording and
```suggestion
* Allow using metrics of services in user namespaces in recording and
```

2020-07-06 14:57 UTC, merged