BZ-1851054 Fixed CLI secondary network attachment procedure
openshift/openshift-docs pull request #23551
Opened 2020-07-08 16:26 UTC by sjhala-ccs

BZ-1851054  https://bugzilla.redhat.com/show_bug.cgi?id=1851054

Fixed CLI procedure to connect VM to secondary network

Applies to 4.5, 4.4, and 4.3 docs

2020-07-08 16:57 UTC, aburdenthehand commented on modules/virt-creating-bridge-nad-cli.adoc
> +    "name": "cnv-bridge-conf", <1>
Not sure if it's strictly necessary but this should probably match the name of the NAD (a-bridge-network)
@phoracek will keep me honest.

2020-07-08 16:59 UTC, aburdenthehand commented on modules/virt-creating-bridge-nad-cli.adoc
> +  name: bridge-net
This should be replaceable (wrapped in <>) and correspond to the name used above (a-bridge-network)

2020-07-09 14:22 UTC, phoracek requested changes

2020-07-09 14:22 UTC, phoracek commented on modules/virt-creating-bridge-nad-cli.adoc
> +access port with the requested VLAN.
we don't request any VLAN in the example

2020-07-09 14:22 UTC, phoracek commented on modules/virt-creating-bridge-nad-cli.adoc
> +.. Specify the network and MAC address, if required by the server. If the MAC address is not specified, a value is assigned
This is conditioned by the namespace being opted in to MAC pool.

Let's just drop the MAC notion, at least from this PR. Usually, user would not need to set it.

2020-07-09 14:22 UTC, phoracek commented on modules/virt-creating-bridge-nad-cli.adoc
> +- masquerade: {}
Worth a note that this VM will be connected to both the default pod network and to the bridge.

2020-07-09 14:22 UTC, phoracek commented on modules/virt-creating-bridge-nad-cli.adoc
> +  bootOrder: 1
Not interesting outside of the PXE context.

2020-07-09 21:23 UTC, sjhala-ccs commented
@phoracek I have incorporated your comments. Can you please review again? Thanks.

2020-07-10 08:08 UTC, phoracek requested changes

2020-07-10 08:08 UTC, phoracek commented on modules/virt-creating-bridge-nad-cli.adoc
> +networks:
We need to keep the YAML example with `interfaces` list. Both `networks` and `interfaces` is needed to build the configuration.

2020-07-10 14:11 UTC, phoracek requested changes

2020-07-10 14:11 UTC, phoracek commented on modules/virt-creating-bridge-nad-cli.adoc
> +    - name: bridge-net
Would be worth marking this with a note and connecting it to the same name on line 73.

2020-07-10 14:11 UTC, phoracek commented on modules/virt-creating-bridge-nad-cli.adoc
> +  interfaces:
`interfaces` are not directly under `spec`. They are under `spec.domain.devices`.

2020-07-10 16:39 UTC, phoracek approved these changes
/lgtm

Thanks

2020-07-21 15:17 UTC, sjhala-ccs commented
@myakove Can you please review? Thanks.

2020-07-22 07:56 UTC, myakove commented
/lgtm

2020-07-22 20:13 UTC, ousleyp reviewed
Just a couple of nits, otherwise LGTM.

2020-07-22 20:13 UTC, ousleyp commented on modules/virt-creating-bridge-nad-cli.adoc
> +The virtual machine instance will be connected to both the `default` Pod network and `bridge-net` which is
This note is kind of hard to parse -- could it be split into two sentences?

2020-07-22 20:13 UTC, ousleyp commented on modules/virt-creating-bridge-nad-cli.adoc
> +. Edit the configuration file of a virtual machine or virtual machine instance that you want to connect to the bridge network.
Maybe say "For example:" at the end of this step?

2020-07-23 14:54 UTC, merged

2020-07-23 14:54 UTC, ousleyp commented
/cherrypick enterprise-4.5

2020-07-23 14:54 UTC, ousleyp commented
/cherrypick enterprise-4.6