Reorganize network policy related content
openshift/openshift-docs pull request #23802
Opened 2020-07-15 00:56 UTC by jboxman

- https://issues.redhat.com/browse/OSDOCS-794

This is a prelude to updates specific to OVN-Kubernetes for 4.6. This content has been static for a year, so it applies to all prior supported releases.

Additional bug fixes and such forthcoming under separate cover once this merges.

2020-07-17 21:04 UTC, ahardin-rh commented
Checked preview build and confirmed all links are functioning and content is rendering as expected. Everything LGTM!

2020-07-17 21:32 UTC, jboxman commented
Hi @anuragthehatter,

I updated the multitenant docs (`modules/nw-networkpolicy-multitenant-isolation.adoc`) to include an additional policy rule, `allow-same-namespace`:

- [Configuring multitenant mode with network policy](https://osdocs-794--ocpdocs.netlify.app/openshift-enterprise/latest/networking/network_policy/multitenant-network-policy.html)

Does this addition make sense?

Thanks!

2020-07-20 18:22 UTC, jboxman commented
Hi @juanluisvaladas,

I updated the procedure for multitenancy by using network policy:

- [Configuring multitenant mode with network policy](https://osdocs-794--ocpdocs.netlify.app/openshift-enterprise/latest/networking/network_policy/multitenant-network-policy.html)

Does this look reasonable?

Thanks!

2020-07-20 18:42 UTC, anuragthehatter commented
> Hi @anuragthehatter,
> 
> I updated the multitenant docs (`modules/nw-networkpolicy-multitenant-isolation.adoc`) to include an additional policy rule, `allow-same-namespace`:
> 
> * [Configuring multitenant mode with network policy](https://osdocs-794--ocpdocs.netlify.app/openshift-enterprise/latest/networking/network_policy/multitenant-network-policy.html)
> 
> Does this addition make sense?
> 
> Thanks!

@jboxman That looks good to me. Thanks

2020-07-21 10:02 UTC, juanluisvaladas requested changes
The ones where I say this is important really need to be changed because they are technically wrong.
The others are just suggestions

2020-07-21 18:21 UTC, jboxman commented
@juanluisvaladas, glad I asked, this is invaluable. Thanks!

(I'm going to be revising the content after this PR to include `egress` for OVN-Kubernetes and also `ipBlock` which are both absent, with a target of 4.6 GA.)

2020-07-22 03:52 UTC, jboxman commented on modules/nw-networkpolicy-delete.adoc
> +// * networking/network_policy/deleting-network-policy.adoc
@juanluisvaladas, this was probably my first work with OCP, ever, so I'm not sure where that came from. I'll fix it. Thanks!

2020-07-22 03:56 UTC, jboxman commented on modules/nw-networkpolicy-edit.adoc
> +set. This mode is the default for OpenShift SDN.
@juanluisvaladas, thanks, I'll fix this throughout. I'll probably update it again to explicitly mention OVN-Kubernetes for the GA as well.

2020-07-22 10:40 UTC, juanluisvaladas commented
> (I'm going to be revising the content after this PR to include egress for OVN-Kubernetes and also ipBlock which are both absent, with a target of 4.6 GA.)

We don't have ipblock? That was included in 4.3: https://github.com/openshift/sdn/blob/release-4.3/pkg/network/node/networkpolicy.go#L538-L546 so when you include it, this probably should be backported all the way back.

When you add it please make sure to mention that we don't support except in ipblock in openshift-sdn (true for all versions).

Also in the delete document, I know it's not part of this PR, but instead of: `$ oc delete networkpolicy -l name=<policy-name> ` it should be `$ oc delete networkpolicy <policy-name> `. You're not guaranteed to have the label name, maybe you are deleting more policies than you want or maybe you are not deleting anything.

2020-07-22 15:48 UTC, jboxman commented
@juanluisvaladas, ipBlock didn't make it yet; I updated the `oc delete` and force-pushed. Thanks for catching that. I'd wanted to revisit that, but hadn't realized how dangerous it was.

2020-07-22 16:35 UTC, jboxman commented on modules/nw-networkpolicy-multitenant-isolation.adoc
> +. Create the following NetworkPolicy objects:
@juanluisvaladas, I'll tackle that in a subsequent PR.

2020-07-22 19:33 UTC, merged

2020-07-22 19:34 UTC, jboxman commented
/cherry-pick enterprise-4.6

2020-07-22 19:34 UTC, jboxman commented
/cherry-pick enterprise-4.5

2020-07-22 19:34 UTC, jboxman commented
/cherry-pick enterprise-4.4

2020-07-22 19:34 UTC, jboxman commented
/cherry-pick enterprise-4.3

2020-07-22 19:35 UTC, jboxman commented
/cherry-pick enterprise-4.5