Logging update added better wording around Kibana
openshift/openshift-docs pull request #23892
Opened 2020-07-16 21:40 UTC by mburke5678

Improving wording in update section to reference the visualizations and index patterns are removed by update.

2020-07-16 21:42 UTC, mburke5678 commented
@sichvoge PTAL

2020-07-21 09:13 UTC, sichvoge approved these changes
Added a small comment, which I believe might be a mistake only. Please make sure to look into it but otherwise LGTM.

2020-07-21 09:13 UTC, sichvoge commented on logging/cluster-logging-upgrading.adoc
> +Cluster logging 4.5 introduces a new Elasticsearch version, Elasticsearch 6.8.1, and an enhanced security plug-in, Open Distro for Elasticsearch. The new Elasticsearch version introduces a new Elasti
"by only by type" ? :)

2020-07-21 15:41 UTC, mburke5678 commented
Notes from meeting with Christian

[Christian Meeting Deprecate.txt](https://github.com/openshift/openshift-docs/files/4954564/Christian.Meeting.Deprecate.txt)

2020-07-21 17:00 UTC, adellape requested changes
Some suggestions, but the `+` should be fixed at least.

2020-07-21 17:00 UTC, adellape commented on modules/cluster-logging-deploy-console.adoc
> +.. Select *4.5* as the *Update Channel*.
Same suggestion here re: unordered list.

2020-07-21 19:18 UTC, merged

2020-07-21 19:18 UTC, mburke5678 commented
/cherrypick enterprise-4.5

2020-07-21 19:20 UTC, mburke5678 commented
/cherrypick enterprise-4.6