updated cluster loader image pull spec to use public registry again
openshift/openshift-docs pull request #24578
Opened 2020-08-07 13:41 UTC by ahardin-rh

Continuation of https://github.com/openshift/openshift-docs/pull/23321 (rebased and solved merge conflicts)

This resolves https://bugzilla.redhat.com/show_bug.cgi?id=1817620 and https://github.com/openshift/openshift-docs/issues/23009

@JaredBurck FYI. Getting this moving along.

@RH-ematysek @cpmeadors Can you please provide QE review?

2020-08-07 13:45 UTC, kalexand-rh reviewed
LGTM

2020-08-07 14:18 UTC, jtaleric approved these changes
LGTM, thanks!

2020-08-07 15:40 UTC, cpmeadors requested changes
Changes look good with the exception of the missing single quotes.  All commands execute correctly.  I verified that I removed credentialsfor registry.svc.ci.openshift.org. and was able to access quay.io without any special credentials.  Looks publicly accessible to me.

2020-08-07 15:40 UTC, cpmeadors commented on modules/running-cluster-loader.adoc
>  should populate the cluster [Slow][Serial] [Suite:openshift]"
I think you are missing a closing single quote at the end of the command.

2020-08-07 15:40 UTC, cpmeadors commented on modules/running-cluster-loader.adoc
>  should populate the cluster [Slow][Serial] [Suite:openshift]"
Missing closing single quote here too.

2020-08-07 16:32 UTC, ahardin-rh commented
@cpmeadors Nice catch! Thank you for the review!

2020-08-07 16:33 UTC, merged

2020-08-07 16:33 UTC, ahardin-rh commented
/cherrypick enterprise-4.6

2020-08-07 16:34 UTC, ahardin-rh commented
/cherrypick enterprise-4.5

2020-08-07 16:34 UTC, ahardin-rh commented
/cherrypick enterprise-4.4

2020-08-10 15:03 UTC, cpmeadors reviewed
Closing single quotes are good.  Coping the command and pasting without any modifications works as expected now.

2020-08-10 15:09 UTC, cpmeadors reviewed
Approved