Adding compute machines to vSphere/bare metal UPI environments
openshift/openshift-docs pull request #25046
Opened 2020-08-26 17:34 UTC by codyhoag

A subset of content from #15773, specifically covering vSphere and bare metal use cases.

2020-08-26 20:26 UTC, codyhoag commented
@jiajliu @morenod can you review these docs for adding compute machines to vSphere and bare metal UPI installations? Does this apply for OCP 4.3-4.6?

2020-08-27 01:32 UTC, jiajliu commented
@jinyuma Could u help review vsphere part? Thx!

2020-08-27 10:06 UTC, morenod commented
> @jiajliu @morenod can you review these docs for adding compute machines to vSphere and bare metal UPI installations? Does this apply for OCP 4.3-4.6?
> 
> [vSphere preview](https://adding-workers--ocpdocs.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-vsphere-compute-user-infra.html)
> [bare metal preview](https://adding-workers--ocpdocs.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-bare-metal-compute-user-infra.html)

baremetal steps will be valid from 4.3 to 4.5

starting on 4.6, PXE parameters have changed to live kernel

2020-08-27 17:20 UTC, codyhoag commented
>baremetal steps will be valid from 4.3 to 4.5
>
>starting on 4.6, PXE parameters have changed to live kernel

@morenod I did some digging and updated the bare metal PXE params (ed0292a711b2f7c43680d088779580ee932bc426) based on what I found. Can you review and let me know if I'm on the right track and if any additional changes are required? I'll separate this change from 4.3-4.5 after I have verification. Thanks!

2020-09-01 13:20 UTC, codyhoag commented
@morenod can you review the updates I added for bare metal live kernel PXE params based on your feedback (3f19ec61714d5f5aff891351d2c7f9d5c1f343cf)? I'll separate this change from 4.3-4.5 after I have verification.

@jinyunma can you review the vSphere portion of this PR?

[bare metal preview](https://adding-workers--ocpdocs.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-bare-metal-compute-user-infra.html)
[vSphere preview](https://adding-workers--ocpdocs.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-vsphere-compute-user-infra.html)

2020-09-04 02:23 UTC, jinyunma commented
During I verified the steps, I have already added some comments above, but seems not consider yet in [vSphere preview](https://adding-workers--ocpdocs.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-vsphere-compute-user-infra.html)
Could you please help to check?

2020-09-04 02:23 UTC, jinyunma commented
During I verified the steps, I have already added some comments above, but seems not consider yet in [vSphere preview](https://adding-workers--ocpdocs.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-vsphere-compute-user-infra.html)
Could you please help to check?

2020-09-04 12:54 UTC, codyhoag commented
@jinyunma I don't see any of your comments in this PR. Please let me know if I'm overlooking something.

2020-09-07 08:39 UTC, morenod requested changes

2020-09-07 08:39 UTC, morenod commented on modules/machine-user-infra-machines-pxe.adoc
> +    APPEND ip=dhcp rd.neednet=1 initrd=http://<HTTP_server>/rhcos-<version>-installer-live-initramfs.<architecture>.img console=tty0 console=ttyS0 coreos.inst=yes coreos.inst.install_dev=sda coreos.i
This is not correct. if using live kernel and initramfs, coreos.inst.install_dev needs to point to the full path (/dev/sda) and coreos.inst.image_url is not required.

Also ip=dhcp, rd.neednet and coreos.inst should be removed, as they are deprecated.

Correct line on 4.6 is:

initrd=http://\<HTTP_server\>/rhcos-\<version\>-installer-live-initramfs.\<architecture\>.img console=ttyS0 console=tty0 coreos.inst.install_dev=/dev/sda coreos.inst.ignition_url=http://\<HTTP_server\>/worker.ign coreos.live.rootfs_url=http://\<HTTP_server\>/rhcos-\<version\>-installer-live-rootfs.\<architecture\>.img

2020-09-07 08:39 UTC, morenod commented on modules/machine-user-infra-machines-pxe.adoc
> +kernel http://<HTTP_server>/rhcos-<version>-installer-kernel-<architecture> ip=dhcp rd.neednet=1 initrd=http://<HTTP_server>/rhcos-<version>-installer-initramfs.<architecture>.img console=tty0 consol
Same than PXE, correct line is:

kernel http://\<HTTP_server\>/rhcos-\<version\>-installer-kernel-\<architecture\> initrd=http://\<HTTP_server\>/rhcos-\<version\>-installer-live-initramfs.\<architecture\>.img console=ttyS0 console=tty0 coreos.inst.install_dev=/dev/sda coreos.inst.ignition_url=http://\<HTTP_server\>/worker.ign coreos.live.rootfs_url=http://\<HTTP_server\>/rhcos-\<version\>-installer-live-rootfs.\<architecture\>.img

2020-09-08 18:38 UTC, codyhoag commented
@morenod @jinyunma thanks for your feedback! Can you verify the updated content?

**bare metal**
- Changes: b79c70f0fe2bdf1bc608d949a83a0c490a7a3a00
- Preview: https://adding-workers--ocpdocs.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-bare-metal-compute-user-infra.html

**vSphere**
- Changes: ce9e0de85bb692ed88e171247e1e4a81bb1edebe
- Preview: https://adding-workers--ocpdocs.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-vsphere-compute-user-infra.html

2020-09-09 03:25 UTC, jinyunma commented
LGTM for vsphere part.

2020-09-09 08:25 UTC, morenod approved these changes
LGTM

2020-09-09 18:30 UTC, codyhoag commented
Since this includes 4.6-only edits, I will separate the PRs for 4.3-4.5. The 4.5 PR (which will match 4.3-4.4) is #25361. This content has also been verified by QE.

2020-09-10 16:49 UTC, bobfuru reviewed
This is great work! A couple of prereqs aren't rendering in the preview build, might just be a caching issue. A few other suggestions but overall, LGTM!

Technically, I believe the `Milestone` label should be `Future release` since this is for the as-yet-unreleased 4.6.

2020-09-10 19:46 UTC, codyhoag commented on machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
> +== Prerequisites
Yeah, that was a last minute change I made to follow our updated guidelines for assembly prereq headings. It appears the bot didn't want to update the preview :disappointed: . Just checked locally and it appears as expected: http://file.rdu.redhat.com/~choag/091020/adding-workers/machine_management/user_infra/adding-bare-metal-compute-user-infra.html

2020-09-10 19:47 UTC, codyhoag commented on machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
> +include::modules/installation-approve-csrs.adoc[leveloffset=+1]
Confirmed locally: http://file.rdu.redhat.com/~choag/091020/adding-workers/machine_management/user_infra/adding-vsphere-compute-user-infra.html

2020-09-10 19:53 UTC, codyhoag commented on modules/installation-approve-csrs.adoc
> +When you add machines to a cluster, two pending certificate signing requests
This term appears to be used quite often outside of OCP and the hyphen is not used in those cases.

2020-09-10 20:38 UTC, merged

2020-09-10 20:38 UTC, codyhoag commented
/cherrypick enterprise-4.6