Converting S2I to devfiles procedure.
openshift/openshift-docs pull request #25099
Opened 2020-08-28 11:04 UTC by boczkowska

2020-08-31 17:48 UTC, prietyc123 requested changes

2020-08-31 17:48 UTC, prietyc123 commented on modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
> +$ odo preference set experimental true
I think we don't need this step now.

2020-09-03 13:49 UTC, bobfuru reviewed
A few minor suggestions, including adding `[source,terminal]` formatting.

2020-09-03 13:49 UTC, bobfuru commented on modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
> +[id="converting-an-s2i-component-into-a-devfile-component_{context}"]
This is missing the module metadata, so it can be difficult to know which assemblies this file is included in.

2020-09-03 13:49 UTC, bobfuru commented on modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
> +With `{odo-title}`, you can create both S2I and devfile components. If you have an existing S2I component, you can convert it into a devfile component using the `odo utils` command.
s/both S2I and/both Source-to-Image (S2I) and/

2020-09-03 13:49 UTC, bobfuru commented on modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
> +. Run the `odo utils convert-to-devfile` command which creates `devfile.yaml` and `env.yaml` based on your component:
s/command which/command, which/

2020-09-03 13:49 UTC, bobfuru commented on modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
> +. Run the `odo utils convert-to-devfile` command which creates `devfile.yaml` and `env.yaml` based on your component:
s/creates `devfile.yaml` and `env.yaml` based/creates the `devfile.yaml` and `env.yaml` files based/

2020-09-03 13:49 UTC, bobfuru commented on modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
> +. Verify that the devfile component is deployed successfully:
s/component is deployed/component deployed/

2020-09-03 13:49 UTC, bobfuru commented on modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
> +$ odo utils convert-to-devfile
With each command block, you'll need to add source formatting for consistency, for example:

```
+
[source,terminal]
----
$ odo utils convert-to-devfile 
----
```

2020-09-03 13:49 UTC, bobfuru commented on modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
> ++
[source,terminal]

2020-09-03 13:49 UTC, bobfuru commented on modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
> +----
[source,terminal]

2020-09-03 13:49 UTC, bobfuru commented on modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
> ++
[source,terminal]

2020-09-04 14:34 UTC, bobfuru commented on modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
> +. Run the `odo utils convert-to-devfile` command, which the creates `devfile.yaml` and `env.yaml` based on your component:
s/which the creates/which creates the/

2020-09-04 14:42 UTC, merged

2020-09-04 14:43 UTC, bobfuru commented
/cherrypick enterprise-4.5

2020-09-04 14:43 UTC, bobfuru commented
/cherrypick enterprise-4.6