[WIP] Deprecated CLI command deletion and rpm update
openshift/openshift-docs pull request #25152
Opened 2020-08-31 21:39 UTC by Preeticp

2020-08-31 21:40 UTC, Preeticp commented
@ppitonak request you to review, please.

2020-09-01 08:24 UTC, ppitonak requested changes
`tkn resource create` still exists but only in interactive mode, the `-f` flag was removed, our example needs to be updated

2020-09-01 08:24 UTC, ppitonak commented on modules/op-tkn-pipeline-management.adoc
>  $ tkn pipeline --help
All three download links in this doc need to be updated to https://mirror.openshift.com/pub/openshift-v4/clients/pipeline/0.11.0/

2020-09-01 18:02 UTC, piyush-garg commented
Following example in `tkn resource create` command need to be modified/removed. We have the command there by `-f` flag has been removed

```
Example: Create Pipeline Resource defined by the myresource.yaml file in a namespace
```

2020-09-02 10:07 UTC, piyush-garg commented on modules/op-tkn-pipeline-resource-management.adoc
> +$ tkn resource create myresource.yaml -n myspace
This command will be `tkn resource create -n myspace`

2020-09-02 10:07 UTC, Preeticp commented
@ppitonak @piyush-garg fixed, please LGTM if you see fit.

2020-09-02 10:37 UTC, ppitonak approved these changes
LGTM

2020-09-02 10:52 UTC, piyush-garg commented
/lgtm

2020-09-02 13:15 UTC, bergerhoffer reviewed
Just one suggestion.

Then be sure to squash your commits please.

2020-09-02 13:15 UTC, bergerhoffer commented on modules/op-tkn-pipeline-resource-management.adoc
> +This is an interactive command that will ask your inputs on the name of the Resource, type of the Resource, and the values based on the type of the Resource.
that will ask your inputs on -> that asks for input on

2020-09-02 13:30 UTC, Preeticp commented
@bergerhoffer fixed the comment and squashed the commits. Please merge. This applies to 4.5 and 4.6.

2020-09-02 13:49 UTC, bergerhoffer commented
LGTM, just need to remove WIP before I can merge.

2020-09-02 13:50 UTC, merged

2020-09-02 13:50 UTC, bergerhoffer commented
/cherrypick enterprise-4.6

2020-09-02 13:50 UTC, bergerhoffer commented
/cherrypick enterprise-4.5