machine_management: add note about using original boot media
openshift/openshift-docs pull request #26215
Opened 2020-10-07 21:32 UTC by miabbott

We don't support using newer boot media to add nodes to a cluster born
before 4.6.

2020-10-07 21:32 UTC, miabbott commented
cc: @ashcrow @bobfuru @yuqi-zhang @kikisdeliveryservice

2020-10-07 21:33 UTC, miabbott commented
This should be added to the 4.6 docs, too

2020-10-07 21:50 UTC, yuqi-zhang approved these changes
Note that this isn't just 4.6, we've technically never "supported" updating boot media directly in any way. It just so happens that the 4.6 ignition spec upgrade is the first time we've updated the pointer config

2020-10-07 23:07 UTC, kikisdeliveryservice commented
> Note that this isn't just 4.6, we've technically never "supported" updating boot media directly in any way. It just so happens that the 4.6 ignition spec upgrade is the first time we've updated the pointer config

Maybe worth being extra clear then and just saying to use the original boot media wiht no 4.6 caveat

2020-10-08 12:56 UTC, ashcrow approved these changes

2020-10-08 13:35 UTC, miabbott commented
> Maybe worth being extra clear then and just saying to use the original boot media wiht no 4.6 caveat

Pushed an update that was more clear

2020-10-08 13:47 UTC, ashcrow approved these changes

2020-10-08 14:03 UTC, kalexand-rh reviewed
I have a few requests, but this is looking good.

2020-10-08 14:03 UTC, kalexand-rh commented on machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
> +{product-title} 4.4, you should add additional compute machines using {op-system} 4.4
```suggestion
{product-title} 4.4, you must add additional compute machines using {op-system} 4.4
```

2020-10-08 14:03 UTC, kalexand-rh commented on machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
> +===
Please add a sentence about upgrading the machines after you add them.

2020-10-08 17:38 UTC, bobfuru requested changes
Added a suggestion to Kathryn's. Thanks!

2020-10-08 17:38 UTC, bobfuru commented on machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
> +It is not supported to add additional compute machines to your cluster using newer
Adding additional compute machines to your cluster using newer {op-system} boot media is not supported.
```suggestion
It is not supported to add additional compute machines to your cluster using newer
```

2020-10-08 17:38 UTC, bobfuru commented on machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
> +[IMPORTANT]
Same comments apply for this module as well.

2020-10-08 17:38 UTC, bobfuru approved these changes

2020-10-08 18:05 UTC, miabbott commented
Thanks @kalexand-rh @bobfuru; pushed update with your feedback

2020-10-08 22:46 UTC, bobfuru reviewed
One minor nit that I missed before, please use a single space between sentences. Otherwise, LGTM. Thanks!

2020-10-08 22:46 UTC, bobfuru commented on machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
> +install the {product-title} cluster.  For example, if you installed
cluster. For example,
```suggestion
install the {product-title} cluster. For example, if you installed
```

2020-10-08 22:46 UTC, bobfuru commented on machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
> +media is not supported.  After adding the compute machines, they will automatically
supported.  After
```suggestion
media is not supported. After adding the compute machines, they will automatically
```

2020-10-08 22:46 UTC, bobfuru commented on machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
> +install the {product-title} cluster.  For example, if you installed
cluster. After
```suggestion
install the {product-title} cluster. For example, if you installed
```

2020-10-08 22:46 UTC, bobfuru commented on machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
> +media is not supported.  After adding the compute machines, they will automatically
supported. After
```suggestion
media is not supported. After adding the compute machines, they will automatically
```

2020-10-12 19:36 UTC, miabbott commented
@bobfuru The content looks good to me; ready for squash and merge

2020-10-12 19:49 UTC, merged

2020-10-12 19:51 UTC, bobfuru commented
> @bobfuru The content looks good to me; ready for squash and merge

Well, the button said "Squash and merge" but I guess it kept it as 5 commits ¯\_(ツ)_/¯ but at least it merged. Thanks, @miabbott !

2020-10-12 19:51 UTC, bobfuru commented
/cherrypick enterprise-4.6

2020-10-12 19:52 UTC, bobfuru commented
/cherrypick enterprise-4.5

2020-10-12 19:52 UTC, bobfuru commented
/cherrypick enterprise-4.4

2020-10-12 19:53 UTC, bobfuru commented
/cherrypick enterprise-4.3