CCXDEV-3313: Moved Insights documentation one level up (into Support area)
openshift/openshift-docs pull request #26487
Opened 2020-10-15 07:56 UTC by mmuehlfeldRH

This moves the "Using Insights to identify issues with your cluster" page from its current location ("Remote health monitoring with connected clusters") to "Support".

This change should be applied to master, 4.6, and 4.5.

@openshift/team-documentation, please review this PR. Thanks.

2020-10-15 08:36 UTC, radekvokal commented
Requested by me to raise emphasis on proactive support. 
/lgtm

2020-10-15 10:43 UTC, vikram-redhat commented
@mmuehlfeldRH looks like the build is failing. I think it is because you are missing an anchor at the end of the file location: https://travis-ci.com/github/openshift/openshift-docs/builds/190198440#L260.

Also - ideally we should be adding redirects for this before merging but I don't know how well used this is in its current location to justify the expense of adding a redirect.

@openshift/team-documentation PTAL.

2020-10-15 11:01 UTC, mmuehlfeldRH commented
@vikram-redhat I was told that I can't use xref in modules (builds locally, but fails on Travis). Therefore, I moved the xref from the module to the assembly (to "Additional Resources") to work around this limitation.

However, now it fails with a different [error](https://travis-ci.com/github/openshift/openshift-docs/builds/190230008#L331). Do you have any idea why this happens and where the "-1" in the id comes from? A local build works and I don't see this error.

2020-10-15 16:13 UTC, bergerhoffer requested changes
@mmuehlfeldRH Thanks! Just a few comments. 

Also a question for you and @radekvokal - is Insights not considered to be part of remote health monitoring? We can definitely do some things to raise visibility on this, but I'm not sure whether actually moving this file away from the rest of the related files inside the "Remote health monitoring" section is appropriate.

CC @pneedle-rh too

2020-10-19 06:52 UTC, mmuehlfeldRH commented on support/getting-support.adoc
> +.Additional resources
Fixed.

2020-10-19 06:53 UTC, mmuehlfeldRH commented on support/getting-support.adoc
> +* For details about identifying issues with your cluster, see xref:../support/using-insights-to-identify-issues-with-your-cluster.adoc[Using Insights to identify issues with your cluster].
Fixed.
Thanks. This solved the build error.

2020-10-19 08:15 UTC, radekvokal commented
My 2 cents
-- Remote health monitoring - information about data that we collect from customer Red Hat purposes
-- Getting support -- ways how customer can get effective support from Red Hat which includes opening support case but also OCM Insights tab that shows remediations for known issues. 

From this perspective, I would even move the must-gather section under remote health. Must-gather should be only requested by support when Support engineering fails to debug cluster from information that he/she already has thru telemetry and insights. Eg. if these two are insufficient to triage the issues than we request from customer to upload must-gather but not the other way round.

2020-10-19 08:27 UTC, pneedle-rh commented
@radekvokal hi! Thanks for your description. One point I would like to add is that since `must-gather` is often run manually by customers and the output is then uploaded manually to support cases, I think it is broader than the 'Remote health monitoring with connected clusters' subsection.

2020-10-19 08:46 UTC, radekvokal commented
> @radekvokal hi! Thanks for your description. One point I would like to add is that since `must-gather` is often run manually by customers and the output is then uploaded manually to support cases, I think it is broader than the 'Remote health monitoring with connected clusters' subsection.

HI Paul, yes, I agree .. my point is that in chronological order, must-gather is coming as last instance when everything else fails. I'd like to reflect that in the documentation as well and point customers to the OCM Insights tab before telling them about how to file a support case and attach must-gather.

2020-10-19 08:49 UTC, pneedle-rh commented
@radekvokal thank you for clarifying that.

2020-10-19 13:40 UTC, bergerhoffer commented
Thanks @radekvokal for the explanation. Having this information before must-gather makes sense to me. My concern is mostly about moving this particular piece out of the "Remote health monitoring" subsection, since it is related to the other sections still in there.

How about if we keep that section under the "Remote health monitoring", but we move that whole section above the must-gather section? Like this:

```
Support
  Getting support
  > Remote health monitoring with connected clusters
    About remote health monitoring
    Showing data collected by remote health monitoring
    Opting out of remote health reporting
    Using Insights to identify issues with your cluster
  Gathering data about your cluster
  Summarizing cluster specifications
  > Troubleshooting
    ...
```
We could also move "Using Insights to identify issues with your cluster" above the "Opting out of remote health monitoring" content.

I think that this would be a good compromise, as it gets this earlier visibility (plus the links also added in this PR), while keeping the content logically grouped together. wdyt? 

@pneedle-rh wdyt as well?

2020-10-19 14:05 UTC, pneedle-rh commented
> @pneedle-rh wdyt as well?

@bergerhoffer I think that is a good solution.

2020-10-20 13:13 UTC, mmuehlfeldRH commented
I moved the "Remote health monitoring with connected clusters" entry in the way @bergerhoffer suggested.
This PR should now be ready to be merged (from my side).

2020-10-20 13:25 UTC, bergerhoffer approved these changes

2020-10-20 13:31 UTC, bergerhoffer commented
Thanks @mmuehlfeldRH for the update! This LGTM now, merging!

2020-10-20 13:31 UTC, merged

2020-10-20 13:31 UTC, bergerhoffer commented
/cherrypick enterprise-4.6

2020-10-20 13:32 UTC, bergerhoffer commented
/cherrypick enterprise-4.5