RN for audit logging for oc command
openshift/openshift-docs pull request #26656
Opened 2020-10-22 18:24 UTC by codyhoag

2020-10-22 18:25 UTC, codyhoag commented
@kasturinarra can you please review this? I had a hard time tracking down any additional info for this, so I'm not sure if it's correct. Thanks!

2020-10-23 07:02 UTC, kasturinarra commented
@codyhoag can we add something as below ? Run oc command with -- /usr/bin/gather_audit_logs to be able to collect the audit logs.
 
Not for documenting, but for your reference,  below is the help example just pasing for you
Examples:
  # gather information using the default plug-in image and command, writing into ./must-gather.local.<rand>
  oc adm must-gather
  
  # gather information with a specific local folder to copy to
  oc adm must-gather --dest-dir=/local/directory
  
  # gather audit information
  oc adm must-gather -- /usr/bin/gather_audit_logs
  
  # gather information using multiple plug-in images
  oc adm must-gather --image=quay.io/kubevirt/must-gather --image=quay.io/openshift/origin-must-gather
  
  # gather information using a specific image stream plug-in
  oc adm must-gather --image-stream=openshift/must-gather:latest
  
  # gather information using a specific image, command, and pod-dir
  oc adm must-gather --image=my/image:tag --source-dir=/pod/directory -- myspecial-command.sh

2020-10-23 07:03 UTC, kasturinarra commented
@soltysh could you please help review as well ? Thanks !!

2020-10-23 11:10 UTC, soltysh requested changes

2020-10-23 11:10 UTC, soltysh commented on release_notes/ocp-4-6-release-notes.adoc
> +The `oc adm must-gather` command no longer collects audit logs by default. You must include the `--audit-logs` parameter in the `oc` command to gather audit logs.
You should use `oc adm must-gather -- /usr/bin/gather_audit_logs` command to gather audit logs.

2020-10-23 13:11 UTC, codyhoag commented
@soltysh can you please confirm my edits? Thanks!

2020-10-23 14:21 UTC, soltysh approved these changes
/lgtm

2020-10-23 14:37 UTC, bmcelvee commented
LGTM!

2020-10-23 14:38 UTC, bmcelvee approved these changes

2020-10-23 14:41 UTC, merged