Bug-1882726 update ssh access doc
openshift/openshift-docs pull request #26724
Opened 2020-10-26 19:12 UTC by lmandavi

This PR is associated with:
https://bugzilla.redhat.com/show_bug.cgi?id=1882726

It focuses on adding some edits and minor changes to the existing procedure and output associated with accessing a VMI by using ssh. The defect has notes regarding the changes made to the doc.

2020-10-26 19:13 UTC, lmandavi commented
@phoracek Requesting your review - for details please see the defect notes.

2020-10-26 20:47 UTC, lmandavi commented
https://bug-1882726-ssh-ext-ip-addr--ocpdocs.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-accessing-vm-consoles.html#virt-accessing-vm-consoles-cli

2020-10-27 16:47 UTC, phoracek approved these changes
/lgtm

2020-10-29 09:43 UTC, ofirnash1 commented
/lgtm

2020-10-29 12:33 UTC, ofirnash1 commented
/lgtm

2020-10-29 13:39 UTC, lmandavi commented
These are the only changes that were made as part of this PR in the "updates to ssh access" commit:
https://github.com/openshift/openshift-docs/pull/26724/commits/46185e4f7a4a882e5530128ecf51e1259cfa1caf
(The changes were quite minor in scope).

The other files showing changes do not belong to this PR, they were addressed via a different PR:
https://github.com/openshift/openshift-docs/pull/26298 - and this PR is presently in QE review stage.

2020-10-29 13:40 UTC, lmandavi commented
If it makes sense to wait for this PR #26298  to be merged first, then merge this PR, we can do that.

2020-10-30 02:02 UTC, adellape commented on modules/virt-installing-virtio-drivers-installing-windows.adoc
> + for the storage driver to load. The drivers are arranged hierarchically
I think there's an extra space at the beginning of this line, though that wouldn't affect rendering.

2020-10-30 02:07 UTC, adellape approved these changes
LGTM after squashing to 1 commit. :+1:

2020-10-30 13:21 UTC, lmandavi commented
@adellape -This commit in this PR:
https://github.com/openshift/openshift-docs/pull/26724/commits/3b44c9fd72328ea401d91aeb2fa8e756f148b911

was picked up from the PR that was just merged:
https://github.com/openshift/openshift-docs/pull/26298

I might want to decouple this commit because it was already included in the merged PR? Will connect with you to get your thought on this.

2020-10-30 16:06 UTC, lmandavi commented
CP to 4.6, 4.7. Please see my note above.

2021-02-17 16:07 UTC, adellape requested changes

2021-02-17 16:07 UTC, adellape commented on _topic_map.yml
> +>>>>>>> 9e342832d... Bug-1882726 update ssh access doc
Conflict here.

2021-02-17 16:07 UTC, adellape commented on _topic_map.yml
> +>>>>>>> 9e342832d... Bug-1882726 update ssh access doc
Another conflict.

2021-02-17 16:07 UTC, adellape commented on virt/virtual_machines/virt-installing-qemu-guest-agent.adoc
> +== Prerequisites
This heading should get an anchor/ID added.

2021-02-17 16:07 UTC, adellape commented on virt/virtual_machines/virt-installing-qemu-guest-agent.adoc
> ++
Extra `+` here can be removed.

2021-04-06 04:11 UTC, vikram-redhat commented
@lmandavi can this be closed?

2021-04-06 12:58 UTC, lmandavi commented
@vikram-redhat - Yes, this GitHub issue can be closed. The content changes are being completed via a different PR. Thanks.

2021-04-07 03:01 UTC, closed without merging