OSSMDOC-157
openshift/openshift-docs pull request #27188
Opened 2020-11-09 17:19 UTC by neal-timpe

https://issues.redhat.com/browse/OSSMDOC-157

2020-11-10 15:29 UTC, brian-avery commented on modules/ossm-control-plane-profiles.adoc
> +When you configure control plane profiles, which follow the same syntax as the `ServiceMeshControlPlane`, users inherit settings in a hierarchical fashion. The Operator is delivered with a `default`
should this be profile? 
The Operator is delivered with a `default` profile with default settings for {ProductName}.

2020-11-10 15:30 UTC, brian-avery commented on modules/ossm-control-plane-profiles.adoc
> +. You can now use the `template` parameter in the `ServiceMeshControlPlane` to specify a template.
`profiles` parameter

2020-11-10 15:31 UTC, brian-avery approved these changes

2020-11-11 00:41 UTC, gbaufake approved these changes

2020-11-11 15:08 UTC, JStickler requested changes
We probably need to update both v1x and v2x with how the hierarchy is determined.

2020-11-11 15:56 UTC, neal-timpe commented on modules/ossm-control-plane-profiles.adoc
> +. You can use the `proviles` parameter in the `ServiceMeshControlPlane` to specify a template.
It's a list, so it's one or more. Thanks for catching that.

2020-11-11 16:00 UTC, neal-timpe commented on modules/ossm-control-plane-profiles.adoc
> +When you configure control plane profiles, which follow the same syntax as the `ServiceMeshControlPlane`, users inherit settings in a hierarchical fashion. The Operator is delivered with a `default`
I agree this should be improved, but not in this PR. It's been in the docs for a while, and I don't think we should hold up the rest of the changes in this PR. Can you create a bug or improvement to capture this comment @JStickler ?

2020-11-11 16:46 UTC, JStickler commented on modules/ossm-control-plane-profiles.adoc
> +When you configure control plane profiles, which follow the same syntax as the `ServiceMeshControlPlane`, users inherit settings in a hierarchical fashion. The Operator is delivered with a `default`
I created OSSMDOC-163 to capture this.

2020-11-11 16:48 UTC, JStickler approved these changes

2020-11-11 18:31 UTC, merged

2020-11-11 18:31 UTC, JStickler commented
/cherry-pick enterprise-4.6

2020-11-11 18:32 UTC, JStickler commented
/cherry-pick enterprise-4.7