OSDOCS-1590 Release note for OCI support
openshift/openshift-docs pull request #27573
Opened 2020-11-20 19:51 UTC by bmcelvee

https://issues.redhat.com/browse/OSDOCS-1590

2020-11-20 19:58 UTC, bmcelvee commented
@ricardomaraschini would you mind reviewing this PR for the OCI support release note, please? 

Is the statement about scema2 accurate? If so, would it be appropriate to mention OCI schema in the [About the Mirror Registry](https://docs.openshift.com/container-platform/4.6/installing/install_config/installing-restricted-networks-preparations.html#installation-about-mirror-registry_installing-restricted-networks-preparations) topic?

2020-11-20 20:03 UTC, bmcelvee commented on release_notes/ocp-4-7-release-notes.adoc
> +//Add link
Placeholder for link if additional documentation is required.

2020-11-20 20:17 UTC, bmcelvee commented
@wzheng1 would you mind reviewing this release note, please?

2020-11-23 08:59 UTC, ricardomaraschini requested changes

2020-11-23 08:59 UTC, ricardomaraschini commented on release_notes/ocp-4-7-release-notes.adoc
> +The {product-title} Image Registry Operator and Image Pruner now support Open Container Initiative (OCI) images. You can use OCI images in the same way you would use Docker `schema2` images.
It would be better if we replace "Image Registry Operator" and "Image Pruner" by "Image Streams" and "Internal Registry".

2020-12-11 16:16 UTC, bmcelvee commented
@wzheng1 Would you mind reviewing this release note, please? Thank you!

2020-12-15 07:55 UTC, wzheng1 commented
/lgtm

2020-12-15 08:14 UTC, ricardomaraschini approved these changes
/approve

2020-12-15 15:55 UTC, bmcelvee commented
Thank you!

@openshift/team-documentation PTAL

2020-12-15 15:59 UTC, sfortner-RH approved these changes
LGTM!

2020-12-15 18:31 UTC, merged