OSSMDOC-118
openshift/openshift-docs pull request #27735
Opened 2020-11-30 22:22 UTC by neal-timpe

https://issues.redhat.com/browse/OSSMDOC-118

Kiail link moved from the application launcher.

2020-12-03 22:20 UTC, jshaughn requested changes

2020-12-03 22:20 UTC, jshaughn commented on modules/ossm-observability-access.adoc
> +2. Click *Topology*.
For topology, eligible topology nodes will offer a link.  For Admin, eligible projects will have link.

2020-12-03 22:20 UTC, jshaughn commented on modules/ossm-observability-access.adoc
> +4. Click `Kiali` from the toolbar.
Not sure which toolbar this refers to.  After step 3 you should be in the Kiali console.

2020-12-09 14:59 UTC, neal-timpe commented
@jshaughn Can you take another look at this?

2020-12-09 15:33 UTC, jshaughn requested changes
All good with one exception, see the comment.

2020-12-09 15:33 UTC, jshaughn commented on modules/ossm-observability-access.adoc
> +3. Click `Kiali` from the toolbar.
From the topology view the links are not from the toolbar, the links are from relevant nodes in the topology (i.e. a node in a project registered with service mesh).

2020-12-09 22:29 UTC, neal-timpe commented
@jshaughn One more time. Can you approve if this is right?

2020-12-10 13:28 UTC, jshaughn approved these changes
Looks good.

2020-12-11 09:43 UTC, hhovsepy commented on modules/ossm-observability-access.adoc
> +3. Click `Kiali` from a node in the topology you have configured for the service mesh.
Kiali link is not in each topology node but only one on toolbar on the right side.
![Screenshot from 2020-12-11 10-43-27](https://user-images.githubusercontent.com/604313/101887873-b9521280-3b9d-11eb-9599-cdc73306a9ce.png)

2020-12-11 09:45 UTC, hhovsepy commented on modules/ossm-observability-access.adoc
> +3. In the Launcher section, click `Open on Kiali`.
Here 'Launcher' sections are 2, one in Details tab, another in Overview tab of project details page.

2020-12-15 19:43 UTC, mattmahoneyrh reviewed
Seems the Kiali link in the project Overview.Launcher needs to be added

2020-12-15 20:05 UTC, neal-timpe commented
@mattmahoneyrh It looks to me like it's in there in the administrators section.

2020-12-15 21:46 UTC, neal-timpe commented
@hhovsepy @mattmahoneyrh I made a change to the administrator perspective. I understand it's in overview and details in projects, but I think we should only include one in the docs.

2020-12-16 07:38 UTC, hhovsepy approved these changes
looks good now

2020-12-16 13:50 UTC, mattmahoneyrh approved these changes

2020-12-16 18:39 UTC, JStickler requested changes
My only comment is that very last line (GitHub won't let me leave a comment there).  Since we're talking about two different consoles in the same topic, I think it would help to be as specific as possible which console we're talking about.

"When you first log in [to the Kiali Console],  you see the Overview page which displays all the namespaces in your mesh that you have permission to view.

2020-12-16 18:47 UTC, JStickler approved these changes

2020-12-16 19:06 UTC, merged

2020-12-16 19:06 UTC, JStickler commented
/cherry-pick enterprise-4.6

2020-12-16 19:06 UTC, JStickler commented
/cherry-pick enterprise-4.7