OSSMDOC-189
openshift/openshift-docs pull request #28040
Opened 2020-12-10 22:15 UTC by neal-timpe

https://issues.redhat.com/browse/OSSMDOC-189

Ossm release notes. 
Includes https://issues.redhat.com/browse/OSSMDOC-116
https://issues.redhat.com/browse/MAISTRA-1979

2020-12-11 08:32 UTC, dgn commented on modules/ossm-rn-fixed-issues.adoc
> +* link:https://issues.redhat.com/browse/MAISTRA-2010[MAISTRA-2010] AuthorizationPolicy does not support `request.regex.headers` field. The `validatingwebhook` rejects any AuthorizationPolicy with the
"The issue was fixed in 1.1, but not 2.0" sounds a bit like we didn't fix the issue after all. maybe just mention that this was a regression? it is fixed in both versions now

2020-12-11 08:32 UTC, dgn commented on modules/ossm-rn-new-features.adoc
> +This release of {ProductName} adds support for Istio 1.6.5, Jaeger 1.20.0, Kiali 1.24.2, and the 3scale Istio Adapter 2.0 and OpenShift Container Platform 4.6.
we updated to Istio 1.6.14

2020-12-11 08:32 UTC, dgn commented on modules/ossm-vs-istio.adoc
> +kind: ServiceRoleBinding
ServiceRoleBinding is deprecated in 2.x -- we should show an example that uses AuthorizationPolicy to achieve this. You can find one in the jira issue: https://issues.redhat.com/browse/MAISTRA-2010

2020-12-17 20:42 UTC, neal-timpe commented
@dgn Can you take another look at this?

2020-12-17 21:19 UTC, JStickler approved these changes

2020-12-18 08:44 UTC, dgn commented on modules/ossm-vs-istio.adoc
> +----
the AuthorizationPolicy above is the OSSM example

2020-12-18 08:47 UTC, dgn requested changes
still a few things off about the request header matching. description is good, but the examples are wrong

2020-12-18 08:47 UTC, dgn commented on modules/ossm-vs-istio.adoc
> +----
the ServiceRoleBinding resource is not required anymore. We used to have two resources, ServiceRole and ServiceRoleBinding that were required to do this, but now it's just AuthorizationPolicy, both upstream and in OSSM

2020-12-18 08:47 UTC, dgn commented on modules/ossm-vs-istio.adoc
> +----
the upstream one is without the `.regex.` part (see first entry in table here: https://istio.io/latest/docs/reference/config/security/conditions/#supported-conditions)

2020-12-18 19:16 UTC, neal-timpe commented
@dgn Can you take one more look? Thanks!

2020-12-18 20:00 UTC, brian-avery commented on modules/ossm-rn-fixed-issues.adoc
> +* link:https://issues.jboss.org/browse/MAISTRA-1979[MAISTRA-1979] _Migration to 2.0_ The conversion webhook drops the following important fields when converting SMCP.status from v2 to v1:
Should this be: 
```suggestion
* link:https://issues.jboss.org/browse/MAISTRA-1979[MAISTRA-1979] _Migration to 2.0_ The conversion webhook drops the following important fields when converting `SMCP.status` from v2 to v1:
```

2020-12-18 20:02 UTC, brian-avery approved these changes

2020-12-18 22:02 UTC, brian-avery commented on modules/ossm-cr-example.adoc
> +|Addon is used to configure additional features beyond core control plane components, such as visualization, or metric storage.
Shouldn't this be `Addons`? I read this as referring to the field name.... FieldName is used to configure...

2020-12-18 22:50 UTC, rcernich approved these changes
lgtm

2020-12-21 14:01 UTC, gbaufake approved these changes

2020-12-22 18:57 UTC, merged

2020-12-22 18:57 UTC, neal-timpe commented
/cherry-pick enterprise-4.6

2020-12-22 18:58 UTC, neal-timpe commented
/cherry-pick enterprise-4.7