CNV-5260 Modified node maintenance procedure for CLI
openshift/openshift-docs pull request #28041
Opened 2020-12-10 22:24 UTC by sjhala-ccs

The changes in this PR address https://issues.redhat.com/browse/CNV-5260

Modified the node maintenance CLI modules. Removed content related to the `NodeMaintenance` CR as it is no longer valid. Added steps to use the `oc adm cordon` and `oc adm drain` commands to evacuate pods before node maintenance.

Applies to branch/enterprise-4.7

SME review requested from Stu Gott and Daniel Belenky (tagged in Jira)

2020-12-29 15:32 UTC, enp0s3 requested changes
Thank you,  Looks great. One note, please see below.

2020-12-29 15:32 UTC, enp0s3 commented on modules/virt-setting-node-maintenance-cli.adoc
> +. Drain the node in preparation for maintenance. The node live migrates virtual machine instances that have the `evictionStrategy` field set to `LiveMigrate`. All other pods and virtual machines on t
Having 'evictionStrategy: LiveMigrate` is not enough for a VM to be live migrated. The VM Instance must have the 'LiveMigratable' condition with status set to 'True'

2021-01-05 08:50 UTC, enp0s3 approved these changes
Thank you!

2021-01-06 13:46 UTC, kbidarkar requested changes
Sorry for the late reply,  QE is using these extra set of commands to trigger a node drain in our tests.
To successfully Evict all VMs and VMI Pods on a Node, 
we need to use the below command, 

`oc adm drain <node-name> --delete-local-data --ignore-daemonsets=true --force`

2021-01-11 12:25 UTC, kbidarkar approved these changes
LGTM

2021-01-11 15:07 UTC, aburdenthehand commented on modules/virt-setting-node-maintenance-cli.adoc
> +. Mark the node as unschedulable. The node status will change to `NotReady,SchedulingDisabled`.
s/will change/changes

2021-01-11 15:08 UTC, aburdenthehand commented
One little nit, otherwise LGTM

2021-01-11 15:19 UTC, merged

2021-01-11 15:19 UTC, aburdenthehand commented
/cherry-pick enterprise-4.7