Document DNS rules in OVN-Kube egress firewall
openshift/openshift-docs pull request #28422
Opened 2021-01-07 14:32 UTC by knobunc

In 4.7 OVN-Kube egress firewall added support for DNS rules in the same way that OpenShift SDN already does.  This PR changes the docs to reflect that both SDNs implementations implement it the same way.

2021-01-07 21:16 UTC, jboxman commented
@knobunc, this looks good, but there are also changes necessary in `modules/nw-egressnetworkpolicy-object.adoc` to expose the `dnsName` field.

The text for that needs to be duplicated for the ovn-kube section, but they can't be merged because OpenShift SDN doesn't support using `ports`.

I think this is what we ultimately want for the beginning of the `ifdef` block:

```
ifdef::ovn[]
[source,yaml]
----
egress:
- type: <type> <1>
  to: <2>
    cidrSelector: <cidr> <3>
    dnsName: <dns_name> <4>
  ports: <5>
      ...
----
<1> The type of rule. The value must be either `Allow` or `Deny`.

<2> A stanza describing an egress traffic match rule. A value for either the `cidrSelector` field or the `dnsName` field for the rule. You cannot use both fields in the same rule.

<3> An IP address range in CIDR format.

<4> <4> A domain name.

<5> Optional: A stanza describing a collection of network ports and protocols for the rule.
```

2021-01-07 21:18 UTC, jboxman requested changes
See previous comments, thanks!

2021-01-08 18:28 UTC, jboxman commented
@knobunc, after 2 years I've learned how to push to someone else's PR, so I'll push the changes.

Thanks!

2021-01-08 19:20 UTC, jboxman approved these changes

2021-01-08 19:20 UTC, merged

2021-01-08 19:21 UTC, jboxman commented
/cherry-pick enterprise-4.7

2021-01-08 20:13 UTC, knobunc commented
@jboxman thank you!  I was just looping back to this after the escalations I was on... and it was magically merged.