Follow-up edits to PR#2814
openshift/openshift-docs pull request #2850
Opened 2016-09-15 19:03 UTC by ahardin-rh

Follow-up to https://github.com/openshift/openshift-docs/pull/2814

2016-09-15 19:34 UTC, ahardin-rh commented
Preview build: file:///home/ahardin/openshift-docs/_preview/openshift-enterprise/PR2814-followup/install_config/install/prerequisites.html#system-requirements

2016-09-15 19:55 UTC, ahardin-rh commented
Also addresses https://github.com/openshift/openshift-docs/issues/2688

2016-09-15 19:56 UTC, ahardin-rh commented
@jeremyeder @timothysc PTAL

2016-09-16 12:07 UTC, jeremyeder commented on install_config/install/prerequisites.adoc
> +|Minimum 20 GB hard disk space.
I would say ... "Minimum 20 GB hard disk space for etcd data"...just be a little more explicit.  Fair?

2016-09-16 12:08 UTC, jeremyeder requested changes

2016-09-16 14:21 UTC, ahardin-rh commented
@jeremyeder Fixed. Thanks! Merging!

2016-09-16 14:21 UTC, merged

2016-09-16 14:22 UTC, ahardin-rh commented
Rev history in original PR