Docker login steps are missing for exposed registry with both secured and insecured
openshift/openshift-docs pull request #2863
Opened 2016-09-19 06:44 UTC by tpoitras

incorp closed #2710, and updated based on review from Jaspreet Kaur (comment9 in bz): https://bugzilla.redhat.com/show_bug.cgi?id=1360586#c9

2016-09-19 06:45 UTC, tpoitras commented
Nicely rendered docs here.

Added this: http://file.bne.redhat.com/tpoitras/2016/registry/openshift-enterprise/registry-login-2-BZ1360586/install_config/registry/securing_and_exposing_registry.html#access-secure-registry-by-exposing-route

And this: http://file.bne.redhat.com/tpoitras/2016/registry/openshift-enterprise/registry-login-2-BZ1360586/install_config/registry/securing_and_exposing_registry.html#access-insecure-registry-by-exposing-route

2016-09-19 06:53 UTC, tpoitras commented
currently ON QA

2016-09-20 01:50 UTC, bmeng requested changes

2016-09-20 05:23 UTC, tpoitras commented on install_config/registry/securing_and_exposing_registry.adoc
> +OPTIONS='--selinux-enabled --insecure-registry=172.30.0.0/16 --insecure-registry registry.ose-node.openshift.com:80'
@bmeng can I just use any other port in the example? Like port 90?

2016-09-20 05:23 UTC, tpoitras commented on install_config/registry/securing_and_exposing_registry.adoc
> +docker login -e user@company.com -u f83j5h6 -p Ju1PeM47R0B92Lk3AZp-bWJSck2F7aGCiZ66aFGZrs2 registry.ose-node.openshift.com:80
@bmeng can I just use any other port in the example? Like port 90?

2016-09-20 05:30 UTC, tpoitras commented
Thank you, @bmeng 
I made your changes, but just guessed at a port number. Do you have a suggested port number I should use for the secured registry example commands?

2016-09-20 05:51 UTC, bmeng commented on install_config/registry/securing_and_exposing_registry.adoc
> +OPTIONS='--selinux-enabled --insecure-registry=172.30.0.0/16 --insecure-registry registry.ose-node.openshift.com:80'
The secured route will use the 443 port by default.
BTW, seems if we secured the docker registry, the option `--insecure-registry registry.ose-node.openshift.com:80` is not needed in the docker daemon config `/etc/sysconfig/docker`.

2016-09-20 05:51 UTC, bmeng commented on install_config/registry/securing_and_exposing_registry.adoc
> +docker login -e user@company.com -u f83j5h6 -p Ju1PeM47R0B92Lk3AZp-bWJSck2F7aGCiZ66aFGZrs2 registry.ose-node.openshift.com:80
The default port for the secured route should be 443.

2016-09-22 03:17 UTC, tpoitras commented on install_config/registry/securing_and_exposing_registry.adoc
> +OPTIONS='--selinux-enabled --insecure-registry=172.30.0.0/16 --insecure-registry registry.ose-node.openshift.com:80'
@bmeng - I'll remove the part about updating that file, then. Will omitting it be enough, or do you think we should tell users to remove `--insecure-registry` entries from the `/etc/sysconfig/docker` file?

2016-09-22 03:21 UTC, bmeng commented on install_config/registry/securing_and_exposing_registry.adoc
> +OPTIONS='--selinux-enabled --insecure-registry=172.30.0.0/16 --insecure-registry registry.ose-node.openshift.com:80'
I think it is ok to just remove this part, since the `--insecure-registry` should not have such value by default.

2016-09-22 03:39 UTC, tpoitras commented
Updated based on latest suggestions from @bmeng 
Moving along to peer review: @bfallonf @ahardin-rh @adellape 

Nicely rendered docs:

Added this: http://file.bne.redhat.com/tpoitras/2016/registry/openshift-enterprise/registry-login-2-BZ1360586/install_config/registry/securing_and_exposing_registry.html#access-secure-registry-by-exposing-route

And this: http://file.bne.redhat.com/tpoitras/2016/registry/openshift-enterprise/registry-login-2-BZ1360586/install_config/registry/securing_and_exposing_registry.html#access-insecure-registry-by-exposing-route

2016-09-22 14:06 UTC, ahardin-rh commented
@tpoitras LGTM!

2016-09-23 01:26 UTC, tpoitras commented
Thanks @ahardin-rh , merging! :neckbeard:

2016-09-23 01:26 UTC, merged

2016-09-23 03:05 UTC, tpoitras commented
[rev_history]
|xref:../install_config/registry/securing_and_exposing_registry.adoc#install-config-registry-securing-exposing[Installation and Configuration -> Setting up the Registry -> Securing and Exposing the Registry]
|Added two new sections on Exposing a Secure Registry and Exposing a Non-Secure Registry. 
%