Continuation of PR#2834
openshift/openshift-docs pull request #2874
Opened 2016-09-20 16:29 UTC by ahardin-rh

https://github.com/openshift/openshift-docs/pull/2834

2016-09-20 16:32 UTC, ahardin-rh commented
cc @adellape

2016-09-21 20:52 UTC, ahardin-rh commented
Build of revisions: http://file.rdu.redhat.com/~ahardin/09212016/backup-restore/admin_guide/backup_restore.html

2016-09-22 18:54 UTC, adellape commented on admin_guide/backup_restore.adoc
> +xref:../admin_guide/manage_authorization_policy.html#managing-role-bindings[role
s/html/adoc/

2016-09-22 18:54 UTC, adellape commented on admin_guide/backup_restore.adoc
> +== Backing Up Other Resources
As mentioned on IRC, maybe these individual objects could be subsections under "Project Backup"?

2016-09-22 18:55 UTC, adellape requested changes
1 bad link + 1 suggestion. LGTM otherwise!

2016-09-22 19:10 UTC, ahardin-rh commented on admin_guide/backup_restore.adoc
> +xref:../admin_guide/manage_authorization_policy.html#managing-role-bindings[role
Thanks for catching that! :scream_cat:

2016-09-22 19:20 UTC, adellape approved these changes

2016-09-22 19:22 UTC, merged

2016-09-22 19:35 UTC, ahardin-rh commented
[rev_history]
|xref:../admin_guide/backup_restore.adoc#admin-guide-backup-and-restore[Backup and Restore]
|Added Prerequisites details and created new sections for Application Data Backup, Application Data Restore, Project Restore, as well as backing up Role Bindings, Service Accounts, Secrets, and Persistent Volume Claims.
%