[OSP] Deprecate computeFlavor in install-config.yaml
openshift/openshift-docs pull request #28797
Opened 2021-01-25 15:21 UTC by maxwelldb

Context: https://issues.redhat.com/projects/OSDOCS/issues/OSDOCS-1716

2021-01-25 15:27 UTC, Fedosin requested changes
The key is called `type`, not `flavorName`: https://github.com/openshift/installer/blob/master/data/data/install.openshift.io_installconfigs.yaml#L288

2021-01-25 15:29 UTC, maxwelldb commented on modules/installation-configuration-parameters.adoc
> +This property is deprecated. To use a flavor as the default for all machine pools, add it as the value of the `flavorName` key in the `platform.openstack.defaultMachinePlatform` property. You can als
```suggestion
This property is deprecated. To use a flavor as the default for all machine pools, add it as the value of the `type` key in the `platform.openstack.defaultMachinePlatform` property. You can also set a flavor value for each machine pool individually. 
```

2021-01-25 15:29 UTC, maxwelldb commented
> The key is called `type`, not `flavorName`: https://github.com/openshift/installer/blob/master/data/data/install.openshift.io_installconfigs.yaml#L288

TY. Changed in https://github.com/openshift/openshift-docs/pull/28797/commits/c05fe0ac2c7af8e7adfe55641c064036967280da

2021-01-25 15:55 UTC, Fedosin approved these changes
/lgtm

2021-01-25 16:00 UTC, maxwelldb commented
Thanks! @Fedosin

2021-01-25 16:01 UTC, maxwelldb commented
Should get a line in #28504

2021-01-25 16:02 UTC, maxwelldb commented
Preview link: https://osp-deprecate-computeflavor-osdocs1716--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html#installation-configuration-parameters_installing-openstack-installer-custom

2021-02-08 02:03 UTC, wjiangjay commented
@maxwelldb Sorry for the late, LGTM.

2021-02-08 02:03 UTC, wjiangjay commented
/lgtm

2021-02-08 14:34 UTC, maxwelldb commented
@wjiangjay Thanks!

2021-02-08 14:34 UTC, maxwelldb commented
@openshift/team-documentation PTAL. Thanks!

2021-02-08 18:31 UTC, ahardin-rh commented
LGTM! Just need to squash the commits and you're all set. :rocket:

2021-02-08 18:46 UTC, merged

2021-02-08 18:46 UTC, maxwelldb commented
/cherry-pick enterprise-4.7