[OSSMDOC-224] instructions on how to set the minimum and maximum protocol versions is incorrect
openshift/openshift-docs pull request #28904
Opened 2021-01-27 21:36 UTC by jritter

Configuring the ServiceMeshControlPlane object according to the documentation does not work, the documentation specifies incorrect keys.

Fixes https://issues.redhat.com/browse/OSSMDOC-224

2021-02-03 21:36 UTC, JStickler commented
@rcernich, could you please review this configuration?  I think we probably need to update this entire topic for SMCP2.0, not just this code example.

2021-03-01 22:36 UTC, knrc commented
@JStickler Since this documentation is for SMCP 1.1 the values are correct as they stand.  The real issue is that @jritter tried to use them on SMCP 2.0 which would obviously not work so I think your comment about updating this for 2.0 is the correct solution.

2021-03-01 22:40 UTC, knrc requested changes
Should not be merged as this stands, this needs to augment the existing 1.1 content with 2.0 content rather than replace it.

2021-03-15 22:09 UTC, rcernich approved these changes

2021-03-17 14:33 UTC, neal-timpe approved these changes

2021-03-17 14:51 UTC, merged

2021-03-17 14:51 UTC, JStickler commented
/cherry-pick enterprise-4.6

2021-03-17 14:52 UTC, JStickler commented
/cherry-pick enterprise-4.7

2021-03-17 14:53 UTC, JStickler commented
/cherry-pick enterprise-4.8