Docs for KNIDEPLOY-3583
openshift/openshift-docs pull request #29078
Opened 2021-02-02 19:44 UTC by johnwilkins

@ahardin-rh for enterprise-4.7. Still needs a QE review.

https://issues.redhat.com/browse/KNIDEPLOY-3583

Fixes:

https://issues.redhat.com/browse/TELCODOCS-117
https://issues.redhat.com/browse/TELCODOCS-123
https://issues.redhat.com/browse/TELCODOCS-137

2021-02-02 20:02 UTC, ahardin-rh commented on modules/k8s-nmstate-creating-interfaces.adoc
> +// k8s-nmstate-configuration.adoc
List the full path to the assembly: 

    * networking/k8s_nmstate/k8s-nmstate-configuring.adoc

2021-02-02 21:40 UTC, ahardin-rh commented on modules/k8s-nmstate-creating-interfaces.adoc
> +The `kubernetes-nmstate` operator requires the `nmstate.io` API version and the kind of policy, which is `NodeNetworkConfigurationPolicy`. Additionally, each policy has a name as defined by `metadata
s/operator/Operator

2021-02-02 21:40 UTC, ahardin-rh commented on modules/k8s-nmstate-creating-interfaces.adoc
> +The `spec.desiredState.interfaces` section begins the `nmstate` policy. Creating the policy is identical to creating a policy with `nmstate`. Refer to link:nmstate.io[NMState] documentation for addit
Refer to the

2021-02-02 21:52 UTC, ahardin-rh commented on modules/k8s-nmstate-creating-interfaces.adoc
> +The `status.conditions` section describes the condition of the applied policy. In the foregoing example, the `reason` attribute of the status reports is **SuccessfullyConfigured**, indicating that th
s/**SuccessfullyConfigured**/`SuccessfullyConfigured`
s/**Degraded**/`Degraded`

2021-02-02 21:54 UTC, ahardin-rh commented on modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
> +// k8s-nmstate-using-kubernetes-nmstate.adoc
List the full path to the assembly.

2021-02-02 21:54 UTC, ahardin-rh commented on modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
> +You must install the `kubnetes-nmstate` operator from the OpenShift web console while logged in with administrator privileges. Once installed, the operator can deploy the NMState State Controller as
s/operator/Operator

2021-02-02 21:56 UTC, ahardin-rh commented on modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
> +. Select **Operators > OperatorHub**.
*Operators* -> *OperatorHub* per https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#quick-markup-reference

2021-02-02 21:57 UTC, ahardin-rh commented on modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
> +. In the search field below *All Items*, enter `nmstate` and click *Enter*  to search for the `kubernetes-nmstate` operator.
s/operator/Operator

2021-02-02 21:57 UTC, ahardin-rh commented on modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
> +. Click the *Install* button to install the operator.
s/operator/Operator

2021-02-02 21:58 UTC, ahardin-rh commented on modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
> +The name restriction is known issue. The instance is a singleton for the entire cluster.
is a known issue

2021-02-02 21:58 UTC, ahardin-rh commented on modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
> +Once complete, the operator has deployed the NMState State Controller as a daemonset across all of the cluster nodes.
Operator

2021-02-02 21:59 UTC, ahardin-rh commented on modules/k8s-nmstate-reading-the-state-of-a-node.adoc
> +// virt-k8s-nmstate-reporting.adoc
List the full path to the assembly.

2021-02-02 22:00 UTC, ahardin-rh commented on modules/k8s-nmstate-reading-the-state-of-a-node.adoc
> +Replace `<node-name>` with the hostname of the node.
s/hostname/host name   per IBM Style Guide

2021-02-02 22:00 UTC, ahardin-rh commented on modules/k8s-nmstate-reading-the-state-of-a-node.adoc
> +The object name is the short hostname of the node it represents. The `status.currentState` section contains the node's DNS configuration, list of interfaces, and their configuration and routes.
host name

2021-02-02 22:00 UTC, ahardin-rh commented on modules/k8s-nmstate-removing-interfaces.adoc
> +// k8s-nmstate-configuring.adoc
List the full path to the assembly.

2021-02-02 22:05 UTC, ahardin-rh commented on modules/k8s-nmstate-removing-interfaces.adoc
> +.Removing a policy doesn't revert the state
s/doesn't/does not
We use single asterisks to embolden items, not double asterisks per https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#quick-markup-reference

I suggest putting "Removing a policy does not revert the state." inside the text box, not in that heading format

2021-02-02 22:05 UTC, ahardin-rh commented on modules/k8s-nmstate-removing-interfaces.adoc
> +<1> Change the state from `up` to `absent`
`absent`.  (missing period)

2021-02-02 22:06 UTC, ahardin-rh commented on modules/k8s-nmstate-removing-interfaces.adoc
> +Save the modified policy with a different file name. The modified policy uses the `bond0-eth1-eth2_absent.yaml` filename to distinguish it from the original `bond0-eth1-eth2.yaml` filename. The polic
s/filename/file name

2021-02-02 22:08 UTC, ahardin-rh commented on modules/k8s-nmstate-restoring-the-original-configuration.adoc
> +// k8s-nmstate-configuring.adoc
List the full path to the assembly

2021-02-02 22:08 UTC, ahardin-rh commented on modules/k8s-nmstate-restoring-the-original-configuration.adoc
> +Removing an interface configuration **does not** restore the network interfaces to the state they were in before a policy was applied. Instead, the NICs targeted in the policy are down and reflect `s
single asterisks to embolden text

2021-02-02 22:10 UTC, ahardin-rh commented on networking/k8s_nmstate/k8s-nmstate-configuring.adoc
> += Configuring
I suggest renaming this to be more specific than just "Configuring"

2021-02-02 22:11 UTC, ahardin-rh commented on networking/k8s_nmstate/k8s-nmstate-configuring.adoc
> +The `kubernetes-nmstate` operator enables users to configure network interfaces, DNS settings and routing on {product-title} cluster nodes.
s/operator/Operator
settings, and routing

2021-02-02 22:11 UTC, ahardin-rh commented on networking/k8s_nmstate/k8s-nmstate-configuring.adoc
> +The `kubernetes-nmstate` operator can support multiple policies, but you **must** avoid inter-policy dependencies. For example, if you configure policies such that they must be applied in a specific
Operator
remove emphasis around must

2021-02-02 22:13 UTC, ahardin-rh commented on networking/k8s_nmstate/k8s-nmstate-using-kubernetes-nmstate.adoc
> +The `kubernetes-nmstate` operator provides a Kubernetes API for peforming state-driven network configuration across the {product-title} cluster's nodes with `nmstate`. `kubernetes-nmstate` provides u
Operator

2021-02-02 22:14 UTC, ahardin-rh commented on networking/k8s_nmstate/k8s-nmstate-using-kubernetes-nmstate.adoc
> +`nmstate` requires Network Manager installed on each cluster node.
I see both Network Manager and NetworkManager usage, so we just need to be consistent.

2021-02-02 22:16 UTC, ahardin-rh commented on networking/k8s_nmstate/k8s-nmstate-using-kubernetes-nmstate.adoc
> +[NOTE]
There is a module called technology-preview.adoc that you could use here instead

2021-02-02 22:16 UTC, ahardin-rh commented on networking/k8s_nmstate/k8s-nmstate-using-kubernetes-nmstate.adoc
> +====
I would remove the .Technology Preview heading

2021-02-02 22:17 UTC, ahardin-rh commented on networking/k8s_nmstate/k8s-nmstate-using-kubernetes-nmstate.adoc
> +The `kubernetes-nmstate` operator is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be function
Operator

2021-02-02 22:21 UTC, ahardin-rh commented on modules/k8s-nmstate-creating-interfaces.adoc
> +[kni@node ~]$ oc apply -f bond0-eth1-eth2_up.yaml
For each of the commands throughout this PR, do we need the preceding [kni@node ~] ?

2021-02-02 22:22 UTC, ahardin-rh commented on networking/k8s_nmstate/k8s-nmstate-reporting.adoc
> +
Each of the assemblies is missing a TOC 
You can add: 

toc::[]

2021-02-02 22:25 UTC, ahardin-rh commented on networking/k8s_nmstate/k8s-nmstate-using-kubernetes-nmstate.adoc
> +
toc::[]

2021-02-02 22:25 UTC, ahardin-rh commented on networking/k8s_nmstate/k8s-nmstate-configuring.adoc
> +
toc::[]

2021-02-02 22:28 UTC, ahardin-rh commented on _topic_map.yml
> +  - Name: Reporting
Reporting what? I suggest making the title stronger

2021-02-02 22:28 UTC, ahardin-rh commented on _topic_map.yml
> +  - Name: Configuration
Same here. We need to be more specific about what is being configured.

2021-02-02 22:30 UTC, ahardin-rh commented on _topic_map.yml
> +- Name: Kubernetes NMState (Tech Preview)
I don't think we call out Tech Preview in navigation. We use the technology-preview.adoc to consistently state what is in Technology Preview.

2021-02-02 22:32 UTC, ahardin-rh commented
@johnwilkins Overall, looks great! Just some miscellaneous style comments from me.

2021-02-03 03:08 UTC, jboxman requested changes
So I made a first pass on this, and left comments for some items I discovered for your review. Some apply in multiple places throughout, but for brevity I only tagged a specific instance.

Thanks!

2021-02-03 03:08 UTC, jboxman commented on networking/k8s_nmstate/k8s-nmstate-configuring.adoc
> +- `NodeNetworkConfigurationPolicy`: This object defines the policy, which is the desired network configuration on cluster nodes.
We aren't using _desired_.

>desired adjective
Do not use. Use "required" or "the that you want".

Maybe for k8s _intended_ or _target configuration_ is better?

2021-02-03 03:08 UTC, jboxman commented on networking/k8s_nmstate/k8s-nmstate-reporting.adoc
> +Once installed, each node in the cluster contains a `NodeNetworkSState` object. The daemonset periodically reports the state of each object to the API server.
*NodeNetworkState*

2021-02-03 03:08 UTC, jboxman commented on networking/k8s_nmstate/k8s-nmstate-reporting.adoc
> +Once installed, each node in the cluster contains a `NodeNetworkSState` object. The daemonset periodically reports the state of each object to the API server.
s/daemonset/daemon set/

2021-02-03 03:08 UTC, jboxman commented on modules/k8s-nmstate-creating-interfaces.adoc
> +.Status Conditions
s/Conditions/conditions/

2021-02-03 03:35 UTC, jboxman commented
@johnwilkins, I'm unsure about the topics for this. _Using_ is just installing the Operator.

Configuring is both creating and removing interfaces. Is this a single task? Will a user be doing both of these as part of the same user story?

Also, some of this content largely duplicates existing content under `modules/virt-*` as near as I can tell. Is it possible to reuse existing modules, rather than have multiple, similar modules?

2021-02-03 20:03 UTC, johnwilkins commented on _topic_map.yml
> +- Name: Kubernetes NMState (Tech Preview)
Apparently so. https://www.nmstate.io/kubernetes-nmstate/

2021-02-10 17:30 UTC, nataf37 commented
/LGTM

2021-02-10 22:44 UTC, ahardin-rh commented
Closing in favor of https://github.com/openshift/openshift-docs/pull/29400

2021-02-10 22:45 UTC, closed without merging