Changed Topology view to Graph view as text wherever required.
openshift/openshift-docs pull request #29290
Opened 2021-02-09 11:02 UTC by rishumehra

Changed text "**Topology view**" to "**Graph view**" in the documentation.

For Openshift 4.7

This change is based on the dev issue: https://issues.redhat.com/browse/ODC-5355

2021-02-09 11:42 UTC, gajanan-more requested changes

2021-02-09 11:42 UTC, gajanan-more commented on modules/odc-interacting-with-applications-and-components.adoc
> +The *Topology* view in the *Developer* perspective of the web console provides the following options to interact with applications and components:
```suggestion
The *Topology* page in the *Developer* perspective of the web console provides the following options to interact with applications and components:
```

2021-02-09 11:42 UTC, gajanan-more commented on modules/odc-interacting-with-applications-and-components.adoc
> +Serverless applications take some time to load and display on the *Graph view*. When you create a serverless application, it first creates a service resource and then a revision. After that, it is de
```suggestion
Serverless applications take some time to load and display on the *Graph view*. When you deploy a serverless application, it first creates a service resource and then a revision. After that, it is deployed and displayed on the *Graph view*. If it is the only workload, you might be redirected to the *Add* page. After the revision is deployed, the serverless application is displayed on the *Graph view*.
```

2021-02-09 11:42 UTC, gajanan-more commented on modules/odc-viewing-application-topology.adoc
> +You can navigate to the *Topology* view using the left navigation panel in the *Developer* perspective. After you create an application, you are directed automatically to the *Graph view* where you c
```suggestion
You can navigate to the *Topology* page using the left navigation panel in the *Developer* perspective. After you deploy an application, you are directed automatically to the *Graph view* where you can see the status of the application pods, quickly access the application on a public URL, access the source code to modify it, and see the status of your last build. You can zoom in and out to see more details for a particular application.
```

2021-02-09 11:42 UTC, gajanan-more commented on modules/odc-viewing-application-topology.adoc
> +The *Topology* view also provides you the option to monitor your applications using the *List* view. Use the *List view* icon (image:odc_list_view_icon.png[title="List view icon"]) to see a list of a
```suggestion
The *Topology* page also provides you the option to monitor your applications using the *List* view. Use the *List view* icon (image:odc_list_view_icon.png[title="List view icon"]) to see a list of all your applications and use the *Graph view* icon (image:odc_topology_view_icon.png[title="Topology view icon"]) to switch back to the graph view.
```

2021-02-09 14:36 UTC, andrewballantyne requested changes

2021-02-09 14:36 UTC, andrewballantyne commented on modules/odc-interacting-with-applications-and-components.adoc
> +* Use the *Shortcuts* menu on the upper-right of the screen to navigate components in the *Graph view*.
Hmmm... the Shortcuts menu is NEXT to the icon, it's not the name of the icon. it's a different interaction point.

Maybe something like:
```suggestion
* Use the icon (<insert the icon here>) in the upper-right of the screen to navigate components in the *Graph view*.
```

2021-02-09 19:07 UTC, rishumehra commented
@andrewballantyne As discussed with you over slack I have dropped the Shortcuts menu bullet point as it is not marking any major functionality.

@gajanan-more After having a discussion with @Preeticp we've finalized to retain the "**Topology** view" as is. Otherwise, we need to make the same change to the whole documentation.

@andrewballantyne @gajanan-more @Preeticp Kindly check the changes in the commit. If no further changes are required then please merge this PR.

2021-02-09 19:33 UTC, andrewballantyne approved these changes
👍  LGTM

2021-02-10 02:31 UTC, gajanan-more commented
/lgtm

2021-02-10 11:45 UTC, ahardin-rh commented
LGTM! We just need to squash your commits down to one and we should be good to go. Thank you!

2021-02-10 12:21 UTC, rishumehra commented
> LGTM! We just need to squash your commits down to one and we should be good to go. Thank you!

@ahardin-rh Squashed commits now. Please go ahead and merge the PR now. Thanks for the review.

2021-02-10 13:11 UTC, merged

2021-02-10 13:21 UTC, ahardin-rh commented
/cherrypick enterprise-4.7