Add documentation for memory eviction, update documentation about swap
openshift/openshift-docs pull request #2956
Opened 2016-09-28 17:58 UTC by ahardin-rh

2016-09-28 18:30 UTC, ahardin-rh commented
@adellape please peer review

cc @derekwaynecarr

2016-09-28 19:42 UTC, vikram-redhat commented
Thanks @ahardin-rh . @bfallonf  - Ashley has done the follow up. Can you do a peer review today please?

2016-09-28 19:45 UTC, adellape commented on admin_guide/out_of_resource_handling.adoc
> +The node will map one or more eviction signals to a corresponding node
s/will/can/

2016-09-28 19:45 UTC, adellape commented on admin_guide/out_of_resource_handling.adoc
> +constantly oscillates between true and false, which can cause poor scheduling
Maybe mark up "true" and "false".

2016-09-28 19:45 UTC, adellape commented on admin_guide/out_of_resource_handling.adoc
> +. By their quality of service, and
Something we can link "quality of service" to explain the available classes? There's a "Quality of Service Classes" in `admin_guide/overcommit`.

2016-09-28 19:45 UTC, adellape commented on admin_guide/out_of_resource_handling.adoc
> +. By their quality of service, and
Or maybe simply list out the three in a parenthetical or something: BestEffort, Burstable, Guaranteed.

2016-09-28 19:45 UTC, adellape commented on admin_guide/out_of_resource_handling.adoc
> +unexpected consumption to other `Guaranteed` pods.
If there's a way to break up this long sentence, that'd be nice. Not a super big deal.

2016-09-28 19:45 UTC, adellape commented on admin_guide/out_of_resource_handling.adoc
> +<eviction-signal><operator><quantity>
s/eviction-signal/eviction_signal/

2016-09-28 19:45 UTC, adellape commented on admin_guide/out_of_resource_handling.adoc
> +The node will report a condition when a compute resource is under pressure. The
s/will report/reports/

2016-09-28 19:51 UTC, adellape commented on admin_guide/out_of_resource_handling.adoc
> +event, the `*oom_killer*` will calculate an `*oom_score*` based on the percentage of
s/will calculate/calculates/

2016-09-28 19:52 UTC, adellape commented
@ahardin-rh Added minor comments, and we talked about a few things on IRC: adding a link to this from the Release Notes entry on pod eviction, adding an example config snippet early in the topic as to how this stuff is set on the node in general, and adding a link to housekeeping docs.

2016-09-28 21:04 UTC, ahardin-rh commented
@adellape Thanks! Edits complete. Please let me know if I missed anything. The Release Notes are updated as well.

2016-09-28 21:42 UTC, ahardin-rh commented on admin_guide/out_of_resource_handling.adoc
> +----
@derekwaynecarr can you please confirm that this syntax looks okay? Decided to note earlier on in the doc how to configure the settings.

2016-09-28 21:45 UTC, ahardin-rh commented on admin_guide/out_of_resource_handling.adoc
> +The node evaluates eviction thresholds per its configured housekeeping interval.
@derekwaynecarr how is the housekeeping interval set exactly? Is this another node setting? If so, what does the syntax look like? Thanks!

2016-09-28 21:47 UTC, adellape approved these changes

2016-09-28 21:47 UTC, adellape commented on admin_guide/out_of_resource_handling.adoc
> +(`BestEffort`,`Burstable`, or `Guaranteed`), and
Space before `Burstable`

2016-09-28 21:47 UTC, adellape commented
LGTM :+1:

2016-09-28 22:07 UTC, ahardin-rh commented on admin_guide/out_of_resource_handling.adoc
> +(`BestEffort`,`Burstable`, or `Guaranteed`), and
Nice catch! This is updated.

2016-09-29 02:24 UTC, bfallonf commented
@ahardin-rh @adellape I think this is fine for the Origin docs, but I'd argue it's not really up to Enterprise standard... I think this can be merged when you guys are ready, and I'll go through it when it's merged. Might be a good chance to have an example of the difference too.

2016-09-29 03:13 UTC, derekwaynecarr requested changes
We need to fix the stanza as desired then this is Lgtm.

2016-09-29 03:13 UTC, derekwaynecarr commented on admin_guide/out_of_resource_handling.adoc
> +----
There is an example below in this document.  The argument is either "eviction-hard" or "eviction-soft" so the use of eviction_signal is not accurate.

2016-09-29 03:13 UTC, derekwaynecarr commented on admin_guide/out_of_resource_handling.adoc
> +The node evaluates eviction thresholds per its configured housekeeping interval.
Hmm, this is an error on my part.  We should just state that it monitors every 10s and the value is not modifiable.

2016-09-29 17:40 UTC, ahardin-rh commented
@derekwaynecarr @adellape Thanks! This is now updated.

2016-09-29 18:47 UTC, adellape commented
:+1:

2016-09-29 18:55 UTC, merged

2016-09-29 19:06 UTC, ahardin-rh commented
[rev_history]
|xref:../admin_guide/out_of_resource_handling.adoc#admin-guide-out-of-resource-handling[Out of Resource Handling]
|New topic about memory eviction.
%
|xref:../admin_guide/overcommit.adoc#admin-guide-overcommit[Overcommiting]
|Added a Warning box about swap in the xref:../admin_guide/overcommit.adoc#disabling-swap-memory[Disabling Swap Memory] section.
%

2016-10-02 23:12 UTC, vikram-redhat commented
@bfallonf / @ahardin-rh - Brice you mentioned that this not suitable in its current form for merging into the enterprise docs, but Ashley has tagged it with enterprise branch for next release, and it is now merged and will make it into the next release. So, I will add a follow up to this till you have had a chance to fix this for the enterprise docs.

2016-10-04 06:52 UTC, vikram-redhat commented
Discussed with Brice - he will create a new PR after discussion in a Google doc. I have removed the to_followup flag. So this is now ready to go into the release. If need be, it can be cherry picked this week.

2016-10-11 05:51 UTC, vikram-redhat commented
@bfallonf / @ahardin-rh Follow up PR (https://github.com/openshift/openshift-docs/pull/3023) coming soon so this can wait till that is finished. @aheslin