[enterprise-4.5]Fix URLs in the cluster logging templates
openshift/openshift-docs pull request #29679
Opened 2021-02-23 05:09 UTC by lbscorpio

Based on the feedback from #29637, 4.5 used the wrong URLs in the cluster logging templates.

This PR is only for the branch `enterprise-4.5`, thanks.

2021-02-23 05:30 UTC, vikram-redhat commented
I see QE approval was granted in https://github.com/openshift/openshift-docs/pull/29637. @openshift/team-documentation when you have a chance, please review and merge away.

2021-02-23 10:47 UTC, rolfedh requested changes
Please make a similar change here:
/home/rdlugyhe/openshift-docs/modules/cluster-logging-elasticsearch-audit.adoc:
  115:       endpoint: elasticsearch-insecure.svc.messaging.cluster.local

2021-02-23 13:59 UTC, lbscorpio commented
@rolfedh Thanks for your finding, updated new change in the new commit `f05d39a`.

2021-03-07 00:48 UTC, bobfuru commented
LGTM

2021-03-07 00:48 UTC, merged