Bug 1380563, updated Enabling Features in Technology Preview section
openshift/openshift-docs pull request #2989
Opened 2016-10-04 19:01 UTC by ahardin-rh

https://bugzilla.redhat.com/show_bug.cgi?id=1380563

2016-10-04 19:03 UTC, ahardin-rh commented
@adellape PTAL

2016-10-06 14:31 UTC, ahardin-rh commented
@bfallonf peer review please :bowing_woman:

2016-10-07 03:27 UTC, bfallonf commented
@ahardin-rh LGTM :star2:

2016-10-10 20:33 UTC, ahardin-rh commented
@jwforres PTAL. Thanks!

2016-10-10 20:41 UTC, jwforres requested changes

2016-10-10 20:41 UTC, jwforres commented on install_config/web_console_customization.adoc
> +. As a cluster administrator, run the following command to give users the
this is really specific to jenkins pipelines, this wont be true of all tech preview features

2016-10-10 20:42 UTC, jwforres commented on install_config/web_console_customization.adoc
> +. As a cluster administrator, run the following command to give users the
@bparees are there docs about this in the build doc already?

2016-10-10 20:46 UTC, bparees commented on install_config/web_console_customization.adoc
> +. As a cluster administrator, run the following command to give users the
permission to use pipeline strategies should be on by default already, not sure where this is coming from?

i think all strategies are on by default, though we've been discussing turning off custom by default.

2016-10-12 13:30 UTC, ahardin-rh commented on install_config/web_console_customization.adoc
> +. As a cluster administrator, run the following command to give users the
@jwforres @bparees This was sourced from https://github.com/nickschuetz/ocp-3.3-pipelines/blob/master/README.md. However, it is noted that the steps arose from a possible edge case during an upgrade from 3.2 to 3.3, so this content may not be valid.

2016-10-12 15:08 UTC, bparees commented on install_config/web_console_customization.adoc
> +. As a cluster administrator, run the following command to give users the
yeah, i'm pretty sure that guy just didn't run reconcile roles which is a standard part of the upgrade process.

2016-10-12 15:08 UTC, bparees commented on install_config/web_console_customization.adoc
> +. As a cluster administrator, run the following command to give users the
so yes i'm pretty sure this should be closed.

2016-10-12 15:21 UTC, closed without merging