Be explicit that ingress ipam is non-cloud only
openshift/openshift-docs pull request #3008
Opened 2016-10-06 18:19 UTC by marun

2016-10-06 18:36 UTC, marun commented
cc: @knobunc

2016-10-06 19:22 UTC, knobunc requested changes
Thanks Maru.

2016-10-06 19:22 UTC, knobunc commented on admin_guide/tcp_ingress_external_ports.adoc
> +cloud (GCE/AWS/OpenStack) deployments, services of type
Wait... do we do something special for OpenStack?

2016-10-06 19:22 UTC, knobunc commented on admin_guide/tcp_ingress_external_ports.adoc
> +xref:../dev_guide/getting_traffice_into_cluster.adoc#using-the-loadbalancer[LoadBalancer]
s/traffice/traffic//

2016-10-06 22:07 UTC, marun commented
@knobunc Would it make more sense to just move the warning on line 65?

2016-10-07 19:43 UTC, knobunc commented
@marun I like the new wording and would leave the one at line 65 there.  My only concern is about whether we do anything special for openstack.

2016-10-10 23:01 UTC, marun commented on admin_guide/tcp_ingress_external_ports.adoc
> +cloud (GCE/AWS/OpenStack) deployments, services of type
Yes, OpenStack supports autoprovisioning of a loadbalancer for a service of type loadbalancer just like aws and gce.

2016-10-12 17:48 UTC, knobunc commented
LGTM. @adellape PTAL

2016-10-12 17:50 UTC, knobunc approved these changes
LGTM.  @adellape PTAL

2016-10-13 15:08 UTC, marun commented on admin_guide/tcp_ingress_external_ports.adoc
> +xref:../dev_guide/getting_traffice_into_cluster.adoc#using-the-loadbalancer[LoadBalancer]
Done

2016-11-10 17:15 UTC, ahardin-rh commented
Thanks! I will make minor style edits in a follow-up PR

2016-11-10 17:15 UTC, merged

2016-11-10 17:20 UTC, ahardin-rh commented
[rev_history]
|xref:../admin_guide/tcp_ingress_external_ports.adoc#admin-guide-unique-external-ips-ingress-traffic[Assigning Unique External IPs for Ingress Traffic]
|Added a NOTE stating that this feature is only supported in non-cloud deployments.
%