OSSMDOC-260
openshift/openshift-docs pull request #30202
Opened 2021-03-08 18:24 UTC by neal-timpe

release notes for 1.1.13 and 2.0.3 z-streams.

2021-04-21 18:32 UTC, tvieira requested changes

2021-04-21 18:32 UTC, tvieira commented on modules/ossm-about-collecting-ossm-data.adoc
> +To collect {ProductName} data for a specific namespace with `must-gather`, you must specify the {ProductName} image and namespace. In this example, replace  `<namespace>` with your namespace.
"for a specific control plane namespace" and the other part of the paragraph "... replace `<namespace>` with your control plane namespace.

2021-04-21 18:48 UTC, tvieira commented on modules/ossm-about-collecting-ossm-data.adoc
> +To collect {ProductName} data for a specific namespace with `must-gather`, you must specify the {ProductName} image and namespace. In this example, replace  `<namespace>` with your namespace.
@neal-timpe if you have questions about what I mentioned above, please check this on maistra io docs: https://github.com/maistra/maistra.github.io/pull/176

2021-04-21 19:20 UTC, tvieira commented on modules/ossm-rn-new-features.adoc
> +This release of {ProductName} addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.
In addition, this release has the following improvements:

* Added an option to must-gather to allow gathering only specific control plane namespace (OSSM-351)
* Improved performance for control planes with hundreds of namespaces

2021-04-21 20:24 UTC, neal-timpe commented
@tvieira I made those changes you suggested. I changed the wording of the new features. Let me know if this looks right to you or if there's any more content.

2021-04-21 20:42 UTC, tvieira approved these changes
LGTM

2021-04-22 14:22 UTC, jc-berger commented on modules/gathering-data-specific-features.adoc
>  |`registry.redhat.io/rhcam-1-2/openshift-migration-must-gather-rhel8`
Sorry I can't comment on the actual line in `gathering data about specific features` section. The first `note` right before the prereqs, you say, `...add the `--image gather` argument.` Maybe say, `...add the argument, `--image gather.` 

This is totally a preference things. Whenever there's something the user might copy and paste or click, I tend to link to put it at the end of the sentence to make it easier to copy or click. Again, totally up to you and it's good as is. Simply a suggestion, thanks!

2021-04-22 14:25 UTC, jc-berger commented on modules/gathering-data-specific-features.adoc
>  |`registry.redhat.io/rhcam-1-2/openshift-migration-must-gather-rhel8`
Again, I can't comment on the specific line. For `prereqs` the second bullet says, `The OpenShift Container Platform (oc) installed.` To be consistent with the first bullet, consider phrasing in the imperative so both bullets are actions. So the rephrase would be, `Install the OpenShift Container Platform (oc).`

2021-04-22 14:29 UTC, jc-berger commented on modules/ossm-about-collecting-ossm-data.adoc
> +To collect {ProductName} data for a specific control plane namespace with `must-gather`, you must specify the {ProductName} image and namespace. In this example, replace  `<namespace>` with your cont
In the previous code snippet, you introduced it with a colon, `...Service Mesh image:` 

So wouldn't you need to introduce this code snippet with a colon too? So, it'd be, `...such as `istio-system`:`

2021-04-22 16:10 UTC, JStickler commented on modules/ossm-rn-fixed-issues.adoc
> +* link:https://issues.redhat.com/browse/OSSM-419[OSSM-419] Namespaces with similar names will all show in Kiali namespace list, even though namespaces may not be defined in Service Mesh Member Role.
It looks like the convention for including issue links as part of a New Feature is to put it at the end of the description and format it as "See [issue link] for more information.

https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-rhcos

2021-04-22 16:27 UTC, merged

2021-04-22 16:27 UTC, JStickler commented
/cherry-pick enterprise-4.5

2021-04-22 16:27 UTC, JStickler commented
/cherry-pick enterprise-4.6

2021-04-22 16:27 UTC, JStickler commented
/cherry-pick enterprise-4.7

2021-04-22 16:28 UTC, JStickler commented
/cherry-pick enterprise-4.8

2021-04-22 20:54 UTC, rolfedh commented on modules/ossm-rn-fixed-issues.adoc
> +* link:https://issues.redhat.com/browse/OSSM-419[OSSM-419] Namespaces with similar names will all show in Kiali namespace list, even though namespaces may not be defined in Service Mesh Member Role.
Hi, @neal-timpe. This looks like a description of the bug from OSSM-419. I'm not familiar with how ossm handles release notes. However, a typical release notes describes the bug behavior in past tense, followed by a description of the fix in the present tense. For example, see https://docs.google.com/presentation/d/1TaI1jbV-dhYueUfElPjS_HEqLag_HexFWp85Kdst4y8/edit#slide=id.gc78664d2cb_1_47

2021-04-22 20:56 UTC, rolfedh commented on modules/ossm-rn-fixed-issues.adoc
> +* link:https://issues.redhat.com/browse/OSSM-419[OSSM-419] Namespaces with similar names will all show in Kiali namespace list, even though namespaces may not be defined in Service Mesh Member Role.
A naive reading of "Namespaces with similar names will all show in Kiali namespace list" under the `== {ProductShortName} fixed issues` heading suggests that you're describing the new fixed behavior.