OSSMDOC-177 Missing removal steps.
openshift/openshift-docs pull request #30605
Opened 2021-03-17 18:42 UTC by JStickler

This PR updates the steps for removing Service Mesh, resolving OSSMDOC-177 and OSSMDOC-164.
 - Splits the ossm-operatorhub-remove module into two new files, ossm-remove-operators (common) and ossm-remove-cleanup (V1 and V2)
 - Updates the assembly files to point to the new modules.

(4.5 branch only needs V1 files and will be a manual cherry pick)

2021-03-18 10:39 UTC, FilipB requested changes
- newly added changes for 1.x are also valid for 2.0 and should be added there. I have not checked on 1.x, but admission-controller does not exist in 2.x. it's named maistra-admission-controller in 2.x.

2021-03-18 10:39 UTC, FilipB commented on modules/ossm-remove-cleanup-1x.adoc
> +$ oc delete svc admission-controller -m <operator-project>
-m is a typo, it should be -n

2021-03-23 16:13 UTC, FilipB commented
Following are still missing from 2.x:
oc delete clusterrole istio-view istio-edit
oc delete clusterrole jaegers.jaegertracing.io-v1-admin jaegers.jaegertracing.io-v1-crdview jaegers.jaegertracing.io-v1-edit jaegers.jaegertracing.io-v1-view
oc delete crds jaegers.jaegertracing.io

There should be probably a note about jaeger items that it might not be safe to remove those when using external jaeger. Somebody from jaeger team should confirm.

2021-03-23 17:56 UTC, JStickler commented
@jpkrohling  @jkandasa Philip makes a good point in his comment.   Should I add a note to this, something like, "NOTE: If you intend to keep using Jaeger as a stand alone service without service mesh, do not delete the Jaeger resources."

2021-03-24 11:30 UTC, jpkrohling commented
Yes, if Jaeger wasn't part of the installation of OSSM, it shouldn't be part of its removal.

2021-03-30 06:12 UTC, FilipB commented
LGTM

2021-03-30 20:15 UTC, neal-timpe approved these changes

2021-03-30 20:15 UTC, neal-timpe commented on modules/ossm-remove-cleanup.adoc
> +* An account with cluster administration access.
We gotta remember to add this to https://github.com/openshift/openshift-docs/pull/30066 after this is merged. Nothing to change, just a note.

2021-03-30 20:15 UTC, neal-timpe commented on modules/ossm-remove-cleanup.adoc
> +[NOTE]
The second note about Jaeger seems more like a Note. Do we really need to double note here? Can this sentence be a normal sentence?

2021-03-31 19:45 UTC, merged

2021-03-31 19:45 UTC, neal-timpe commented
/cherrypick enterprise-4.5

2021-03-31 19:50 UTC, neal-timpe commented
/cherrypick enterprise-4.7

2021-03-31 20:01 UTC, neal-timpe commented
/cherrypick enterprise-4.8