Jira: OSDOCS-1878 Add Marketplace URL to ROSA Docs
openshift/openshift-docs pull request #30685
Opened 2021-03-19 12:36 UTC by kmccarron-rh

For Rosa
Jira: https://issues.redhat.com/browse/OSDOCS-1878

Direct link to doc preview: <pending>

2021-03-19 16:52 UTC, kmccarron-rh commented
Added Marketplace URL. Please review! 
@jeremyeder, @vkareh 
@okashi18 - Made changes to prerequisites and order of steps as requested. 

@yufchang - Just a heads-up, once finalized, this will require QE ack. 
Thanks all!

2021-03-19 20:38 UTC, sfortner-RH requested changes
One minor edit. Please make the change and squash or amend your commit.

2021-03-19 20:38 UTC, sfortner-RH commented on modules/rosa-setting-up-environment.adoc
> +.. To enable ROSA, go to the link:https://console.aws.amazon.com/rosa/[ROSA service] and select Enable.
One minor edit Enable -> *Enable*.

2021-03-19 21:06 UTC, sfortner-RH approved these changes
LGTM! Thanks!

2021-03-22 12:31 UTC, kmccarron-rh commented
@sfortner-RH - QE ack received in the card. Looks like we are good to merge!

2021-03-22 12:36 UTC, merged