Bz1933918
openshift/openshift-docs pull request #30957
Opened 2021-03-25 20:19 UTC by stevsmit

Adds a module for passthrough routes to the Routes assembly. 

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1933918

Preview at

2021-03-26 06:00 UTC, lihongan commented
Looks great! Thank you @stevsmit

2021-03-26 14:03 UTC, bmcelvee commented
@wgordon17 would you mind giving this PR a quick review, please? Thank you!

2021-03-26 14:09 UTC, bmcelvee commented on modules/nw-ingress-creating-a-passthrough-route.adoc
> +requiring client certificates (also known as two-way authentication).
Sorry I didn't catch this before! The IBM style guide advises against using parenthesis.  

Suggested edits: 

This is currently the only method that can support
requiring client certificates, also known as two-way authentication.

The only valid values are `None`, empty for disabled, or `Redirect`.

2021-03-26 14:32 UTC, bmcelvee commented
LGTM!

2021-03-28 21:09 UTC, wgordon17 requested changes

2021-03-28 21:09 UTC, wgordon17 commented on modules/nw-ingress-creating-a-passthrough-route.adoc
> +You can configure a secure route using passthrough termination by using the `oc create route` command. With passthrough termination, encrypted traffic is sent straight to the destination without the
```suggestion
You can configure a secure route using passthrough termination by using the `oc create route` command. With passthrough termination, encrypted traffic is sent straight to the destination without the router providing TLS termination. Therefore no key or certificate is required on the route.
```

The key and certificate are still required on the pod

2021-03-28 21:09 UTC, wgordon17 commented on modules/nw-ingress-creating-a-passthrough-route.adoc
> +    termination: passthrough <2>
```suggestion
    termination: passthrough <2>
    insecureEdgeTerminationPolicy: None <3>
```

2021-03-28 21:09 UTC, wgordon17 commented on modules/nw-ingress-creating-a-passthrough-route.adoc
> +<2> The `*termination*` field is set to `passthrough`. No other encryption fields are needed.
```suggestion
<2> The `*termination*` field is set to `passthrough`. This is the only required `tls` field.
<3> Optional `insecureEdgeTerminationPolicy`. The only valid values are `None`, `Redirect`, or empty for disabled.
```

2021-03-28 21:09 UTC, wgordon17 commented on modules/nw-ingress-creating-a-passthrough-route.adoc
> +[NOTE]
This note is no longer necessary

2021-03-28 21:09 UTC, wgordon17 commented on networking/routes/secured-routes.adoc
> +Secure routes provide the ability to use several types of TLS termination to serve certificates to the client. The follow sections describe how to create re-encrypt, edge, and passthrough routes with
```suggestion
Secure routes provide the ability to use several types of TLS termination to serve certificates to the client. The following sections describe how to create re-encrypt, edge, and passthrough routes with custom certificates.
```

2021-03-29 14:37 UTC, wgordon17 commented
LGTM, thanks!

2021-03-29 14:38 UTC, wgordon17 approved these changes

2021-03-29 14:42 UTC, stevsmit commented
@wgordon17 @bmcelvee All edits have been made! Thank you both.

2021-03-29 15:53 UTC, merged

2021-03-29 15:53 UTC, bmcelvee commented
/cherrypick enterprise-4.5

2021-03-29 15:53 UTC, bmcelvee commented
/cherrypick enterprise-4.6

2021-03-29 15:54 UTC, bmcelvee commented
/cherrypick enterprise-4.7

2021-03-29 15:54 UTC, bmcelvee commented
/cherrypick enterprise-4.8

2021-03-29 16:59 UTC, bmcelvee commented
/cherrypick enterprise-4.7