CNV-11391 Removed wording that says SR-IOV network does not support live migr…
openshift/openshift-docs pull request #31757
Opened 2021-04-21 15:17 UTC by sjhala-ccs

…ation.

Addresses [CNV-11391](https://issues.redhat.com/browse/CNV-11391)

OpenShift Virtualization 4.8 will support live migration on SR-IOV network connections. Deleted wording from existing modules that says SR-IOV prevents live migration.

Preview build:

2021-04-22 13:56 UTC, ormergi commented
Hi @sjenning, please keep in mind that currently SRIOV migration is feature-gated
CNV allow migration for VMs with SRIOV interfaces only when SRIOVLiveMigration feature-gate is open.

2021-04-25 07:36 UTC, ormergi requested changes
Hi @sjenning, 
We need to mention that SRIOV migration is feature-gated.
CNV allow migration for VMs with SRIOV interfaces only when SRIOVLiveMigration feature-gate is open.

2021-04-26 13:30 UTC, sjhala-ccs commented
> We need to mention that SRIOV migration is feature-gated.
> CNV allow migration for VMs with SRIOV interfaces only when SRIOVLiveMigration feature-gate is open.

@ormergi What do you mean by "feature gate is open"? Is there a parameter in the `SriovNetwork` object that needs to be set?

2021-04-26 17:37 UTC, ormergi commented
> @ormergi What do you mean by "feature gate is open"? Is there a parameter in the `SriovNetwork` object that needs to be set?

We added new feature gate for SRIOV Live Migration, the feature-gate is SRIOVLiveMigration.
When enabled:
- VM's with SRIOV network interfaces can be live migrated.
- ` virt-launcher` pod will run with `SYS_RESOURCE` capability, having this capability could place regression to virt-launcher security.
Like other feaute-gate this can be configured by hyper-converged-operator CustomResource
https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/docs/cluster-configuration.md#featuregates
https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/docs/cluster-configuration.md#sriovlivemigration-feature-gate

To provide better user experience It work in a way that if `SRIOVLiveMigration` feature-gate is open, 
`LiveMigration` feature gate will takes affect as well.
But not the counterpart; if only `LiveMigration` feature-gate is open then `SRIOVLiveMigration` will not take affect.

2021-04-27 13:20 UTC, sjhala-ccs commented
@ormergi I have changed the content per your suggestion. Can you please review again and add LGTM to this PR if the changes look good? Thank you.

2021-04-29 11:01 UTC, ormergi commented
Thanks you 

/lgtm

2021-05-09 10:47 UTC, myakove commented
/lgtm

2021-05-10 15:33 UTC, ousleyp reviewed
LGTM, just a couple of nits/suggestions for clarity. Take 'em or leave 'em :)

2021-05-10 15:33 UTC, ousleyp commented on virt/virtual_machines/vm_networking/virt-configuring-sriov-device-for-vms.adoc
> +Live migration is supported for virtual machines that are attached to an SR-IOV network interface only if the `sriovLiveMigration` feature gate is enabled in the HyperConverged Cluster custom resourc
The previous comment also applies here.

2021-05-11 13:44 UTC, merged

2021-05-11 13:44 UTC, sjhala-ccs commented
/cherrypick enterprise-4.8