Bug 1384746 added section on tuning sysctl values
openshift/openshift-docs pull request #3242
Opened 2016-11-17 06:26 UTC by bfallonf

As per: https://bugzilla.redhat.com/show_bug.cgi?id=1384746

@jeremyeder @jmencak @ahardin-rh as per email.

I changed around some of the wording. Any thoughts?

2016-11-17 08:41 UTC, jmencak commented
Rewording seems good to me.

2016-11-17 13:59 UTC, ahardin-rh commented on install_config/router/default_haproxy_router.adoc
> +https://access.redhat.com/solutions/1305833[custom tuned profile].
link:https://access.redhat.com/solutions/1305833[custom tuned profile]

2016-11-17 13:59 UTC, ahardin-rh commented
Just one comment. Otherwise, LGTM. Thanks!

2016-11-17 14:38 UTC, jeremyeder requested changes

2016-11-17 14:38 UTC, jeremyeder commented on install_config/router/default_haproxy_router.adoc
> +In clusters, the kernel messages would be similar to the following:
s/In clusters, t/T

2016-11-17 14:38 UTC, jeremyeder commented on install_config/router/default_haproxy_router.adoc
> +When using the `oc` client, the commands fail and the user receives the following:
When this issue occurs, you may begin to see the `oc` client commands being to fail with the following error:

2016-11-17 14:38 UTC, jeremyeder commented on install_config/router/default_haproxy_router.adoc
> +threshold, increase the values. The following sysctl values are recommended for large-scale clusters:
s/recommended/suggested for clusters with large numbers of routes.

Note: we should state which machine this needs to be run on...nodes running router pods only, right?  So, most likely the infra nodes?

2016-11-17 14:53 UTC, jmencak commented on install_config/router/default_haproxy_router.adoc
> +threshold, increase the values. The following sysctl values are recommended for large-scale clusters:
This is correct, I've seen nodes running router pods affected with this only.  So, perhaps something like this? 

The following sysctl values are suggested for clusters with large numbers of routes on infra nodes running router pods:

2016-11-17 14:57 UTC, jeremyeder commented on install_config/router/default_haproxy_router.adoc
> +threshold, increase the values. The following sysctl values are recommended for large-scale clusters:
ack

2016-11-28 04:52 UTC, bfallonf commented on install_config/router/default_haproxy_router.adoc
> +threshold, increase the values. The following sysctl values are recommended for large-scale clusters:
Added a sentence on running it on the router pods. There's a chance it won't be on the infra nodes, but if so, it'll be easier to find.

2016-11-28 06:51 UTC, jmencak commented on install_config/router/default_haproxy_router.adoc
> +When using the `oc` client, the commands fail and the user receives the
Please remove now duplicate lines 1371-1373.

2016-11-29 03:44 UTC, bfallonf commented
@jmencak Thanks for that. Mistake on my part.

@adellape @ahardin-rh @gaurav-nelson peer review please?

2016-11-29 03:47 UTC, bfallonf commented
[rev_history]
|xref:../install_config/router/default_haproxy_router.adoc#install-config-router-default-haproxy[Setting up a Router -> Using the Default HAProxy Router]
|Added the xref:../install_config/router/default_haproxy_router.adoc#deploy-router--arp-cach-tuning-for-large-scale-clusters[ARP Cache Tuning for Large-scale Clusters] section.
%

2016-11-29 14:25 UTC, ahardin-rh commented
Just 2 minor comments. Otherwise, LGTM.

2016-11-30 05:27 UTC, bfallonf commented
Thanks @ahardin-rh . I'll merge away.

2016-11-30 05:29 UTC, merged