document all the route annotations and PR11984
openshift/openshift-docs pull request #3301
Opened 2016-11-30 16:01 UTC by JacobTanenbaum

2016-11-30 21:24 UTC, ramr requested changes

2016-11-30 21:24 UTC, ramr commented on architecture/core_concepts/routes.adoc
> +By default, or using an environment variable a number of configuration options
Maybe reword this - sounds a bit odd `by default or using` - something like `Using environment variables as defined in <add-link-to-section>, a router can set the default options for all the routes it exposes. An individual route can choose to override some of these defaults by providing specific configuration via/in (I like via but its normally not used in docs) its annotations`.

2016-12-01 14:53 UTC, JacobTanenbaum commented
@ramr does this clear it up?

2016-12-01 18:59 UTC, ramr commented
LGTM

2016-12-01 18:59 UTC, ramr reviewed
LGTM

2016-12-01 19:00 UTC, ramr approved these changes

2016-12-06 13:24 UTC, knobunc requested changes

2016-12-06 13:24 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +|`*ROUTER_LOAD_BALANCE_ALGORITHM*` | leastconn | Load-balanceing strategy for multiple endpoints for edge and reencrypt terminated routes. Available options are `source`, `roundrobin`, or `leastconn`
Load-balanceing => Load-balancing

Doesn't this also apply to http routes?

2016-12-06 13:24 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +|Variable | Description
Can we sort this section alphabetically by annotation?

2016-12-06 13:24 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +|`*haproxy.router.openshift.io/balance*`| sets the load balance algorithm. Available options are `source`, `roundrobin`, or `leastconn`.
The first letter of the description should be uppercase to match the other table.

Should we indicate the ENV that provides the default (perhaps in a new column)

load-balancing (or make the pervious one match this case)

2016-12-06 13:24 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +|`*haproxy.router.openshift.io/timeout*` | sets a server side timeout. overwrites `*ROUTER_DEFAULT_SERVER_TIMEOUT*` for that route
server-side

Just make the default env be noted in a new column

2016-12-06 13:24 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +|`*haproxy.router.openshift.io/rate-limit-connections*`| setting to true enables rate limiting functionality
Should true be in quotes?  Or in a fixed width font?  What's the style elsewhere?

2016-12-06 13:24 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +|`*haproxy.router.openshift.io/rate-limit-connections.concurrent-tcp*`| limits the number of concurrent tcp connections shared by an IP address
TCP?  What's the style?

2016-12-06 13:24 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +|`*haproxy.router.openshift.io/rate-limit-connections.rate-http*`| limits the rate at which an IP address can make http requests
HTTP?  What's the style?

2016-12-06 13:24 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +|`*haproxy.router.openshift.io/disable_cookies*`| disables the use of cookies, the balance algorithm is used to determine which backend serves connections everytime
Disables the use of cookies to track related connections.  If set to 'true' the balance algorithm is used to choose which back-end serves connections for each HTTP request.

2016-12-06 13:24 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +|`*router.openshift.io/haproxy.health.check.interval*`| set the health check interval for backend endpoints
Sets the interval for the back-end health checks.

2016-12-08 14:58 UTC, knobunc approved these changes
LGTM

2016-12-08 14:58 UTC, knobunc commented
@JacobTanenbaum What releases should this be for?  Please put that in the PR description.

@openshift/team-documentation PTAL.  This has passed technical review.

2016-12-08 16:41 UTC, ahardin-rh commented
LGTM. I added a to_followup label, as I will make some minor follow-up edits to the topic as a whole in a follow-up PR. @JacobTanenbaum Is this for 3.4? Thanks!

2016-12-08 21:36 UTC, ahardin-rh commented
@JacobTanenbaum Also, can you please give this a squash?

2016-12-18 15:59 UTC, JacobTanenbaum commented
@ahardin-rh  squashed

2016-12-19 12:51 UTC, ahardin-rh commented
@JacobTanenbaum Thanks! Can you please check my labels? I am assuming this is for 3.4. is that correct?

2017-01-03 19:33 UTC, JacobTanenbaum commented
@knobunc is this for 3.4 or 3.5?

2017-01-06 16:26 UTC, knobunc commented
@JacobTanenbaum if all of the annotations are in 3.4, then it can be for 3.4.  Can you confirm if they are?

2017-01-06 17:54 UTC, JacobTanenbaum commented
they are in 3.4

2017-01-06 18:42 UTC, merged

2017-01-06 18:49 UTC, ahardin-rh commented
[rev_history]
|xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
|Added descriptions of all xref:../architecture/core_concepts/routes.adoc#route-specific-annotations[route annotations].
%