[WIP] CNV-10277: live migration limits update
openshift/openshift-docs pull request #33094
Opened 2021-06-04 18:39 UTC by ousleyp

- CNV-10277
- enterprise-4.8 only
- This PR does not cover the default CPU model part of the Jira subtask (that will be covered in a release note)
- WIP: need to add the command that opens the HyperConverged CR. Disregard the existing configmap command.

2021-06-07 13:11 UTC, nunnatsa requested changes

2021-06-07 13:11 UTC, nunnatsa commented on modules/virt-configuring-live-migration-limits.adoc
> +* Edit the `HyperConverged` configuration file and add the necessary
The HyperConverged is not a "configuration file" please change to:

> Edit the `HyperConverged` custom resource and add the necessary...

2021-06-16 20:19 UTC, sjhala-ccs reviewed
LGTM!

2021-06-16 20:24 UTC, merged

2021-06-16 20:24 UTC, ousleyp commented
/cherrypick enterprise-4.8