OSDOCS-1880: Cloud/Cluster Infra 4.8 Release Notes
openshift/openshift-docs pull request #33148
Opened 2021-06-07 15:07 UTC by lbarbeevargas

4.8 Cloud/Cluster Infra release notes epic: https://issues.redhat.com/browse/OSDOCS-1880

Preview: https://deploy-preview-33148--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-8-release-notes.html#ocp-4-8-machine-api

2021-06-07 16:05 UTC, lbarbeevargas commented
@elmiko Release note for vSphere machine autoscaler to/from zero is ready for review. Thank you!

2021-06-07 17:37 UTC, elmiko requested changes
looks mostly good, just a minor nit about the autoscaler name

2021-06-07 17:37 UTC, elmiko commented on release_notes/ocp-4-8-release-notes.adoc
> +==== Scaling machines running in vSphere to and from zero with the machine autoscaler
minor nit
```suggestion
==== Scaling machines running in vSphere to and from zero with the cluster autoscaler
```

2021-06-07 17:37 UTC, elmiko commented on release_notes/ocp-4-8-release-notes.adoc
> +When running machines in vSphere, you can now set the `minReplicas` value to `0` in the `MachineAutoscaler` resource definition. When this value is set to `0`, the machine autoscaler scales the machi
same here
```suggestion
When running machines in vSphere, you can now set the `minReplicas` value to `0` in the `MachineAutoscaler` resource definition. When this value is set to `0`, the cluster autoscaler scales the machine set to and from zero depending on if the machines are in use. For more information, see the xref:../machine_management/applying-autoscaling.html#machine-autoscaler-cr_applying-autoscaling[MachineAutoscaler resource definition].
```

2021-06-07 17:48 UTC, lbarbeevargas commented on release_notes/ocp-4-8-release-notes.adoc
> +==== Scaling machines running in vSphere to and from zero with the machine autoscaler
Good catch! Thank you 👍

2021-06-08 11:00 UTC, JoelSpeed commented
With Mike's suggested fixes applied, LGTM

2021-06-08 20:02 UTC, lbarbeevargas commented
@elmiko All set on updating "machine autoscaler" to "cluster autoscaler." 👍  Quick question on if I need to make the same wording update to the product docs pertaining to this feature as well:

> You can save on costs by setting this value to 0 for use cases such as running expensive or limited-usage hardware that is used for specialized workloads, or by scaling a machine set with extra large machines. The _machine autoscaler_ scales the machine set down to zero if the machines are not in use.

2021-06-08 20:03 UTC, lbarbeevargas commented
@miyadav PTAL, thank you!

2021-06-08 20:10 UTC, sagidlow reviewed
Looks good! 
Could you also update the title of the PR:

> OSDOCS-1880: Cloud/Cluster Infra 4.8 Release Notes

Just so that we can comply with rules for labeling our PRs (:

2021-06-09 14:00 UTC, elmiko commented
> Quick question: do I need to make the same wording update to the product docs pertaining to this feature as well?

good question. imo, in general we should be calling this thing the "cluster autoscaler". that is how the project is referred to in the community, it is also what that application does. so, yes i think we should be using that terminology.

imo, the confusion comes in here because we are manipulating API objects named `MachineAutoscalers`, and technically it is adding `Machines` to the cluster. i can understand how these terms could get jumbled up.

2021-06-10 09:02 UTC, listey commented
Asked to look at this by @lbarbeevargas - all seems good to me.

2021-06-11 01:56 UTC, sunzhaohua2 commented
/lgtm

2021-06-11 16:26 UTC, merged