Ipfailover check and notify script support
openshift/openshift-docs pull request #3355
Opened 2016-12-09 18:16 UTC by pecameron

Openshift 3.5 feature.
[WIP] need to add example of using configMap

Add options to 'oadm ipfailover' to configure the check script and
notify scripts and also control the period the check script runs.

Keepalived periodically checks whether the application is running
properly.  In the default case the test is a simple verification that
something is listening on the watch port. This PR permits the user to
supply an additional check script that is run in the ipfailover container
context to verify that the application is operating properly. For
example, a web server can be tested by accessing the watch port and
verifying the response.

Whenever a node changes state to MASTER, BACKUP, or FAULT a notify
script can be called. This script has 3 parameters filled in by
keepalived:
$1 - "GROUP"|"INSTANCE"
$2 - name of group or instance
$3 - target state of transition ("MASTER"|"BACKUP"|"FAULT")

--check-script="check_script"
The check script is a script in the keepalived container that verifies
the service is running properly. The script must return 0 for OK and 1
for FAIL.
These checks are in addition to verifying that the watch port is
listening.

--notify-script="notify_script"
The notify script is a script in the keepalived container that is
called whenever the keepalived state transitions to
(MASTER|BACKUP|FAULT)

--check-interval=
The check script is run every seconds. Default is 2.

Note: the scripts name is the full path to the script.

Fixes bug 1362163
https://trello.com/c/228zu7Br/267-5-improve-the-configurability-of-the-ipfailover-container-operations

Signed-off-by: Phil Cameron <pcameron@redhat.com>

2016-12-14 15:26 UTC, pecameron commented
@knobunc PTAL

2016-12-16 19:12 UTC, knobunc requested changes

2016-12-16 19:12 UTC, knobunc commented on admin_guide/high_availability.adoc
> +The *keepalived* port monitoring feature uses a simple port check ( </dev/tcp/<ip>/<watch-port> ) to verify that the application is running. The admin can provide a script that does whatever addition
how about "uses a simple tcp connect to verify"

And should we say that if watch-port is 0 the test is skipped?

2016-12-16 19:12 UTC, knobunc commented on admin_guide/high_availability.adoc
> +For each VIP, *keepalived* keeps the state of the node. The VIP on the node may be in *MASTER*, *BACKUP*, or *FAULT* state.  All nodes that are not in the *FAULT* state negotiate to decide who will b
`When the check script fails *keepalived* enters the *FAULT* state. When the check script passes again it exits *FAULT* and negotiates for *MASTER*.`

When the first one fails, do all then start testing?  Or do they always test and move from BACKUP to FAULT?

Surely after the first fails and moves to FAULT, one of the others in BACKUP will try to take control?

2016-12-16 19:12 UTC, knobunc commented on admin_guide/high_availability.adoc
> +The script has no input arguments and must return 0 for OK and 1 for fail.
1 or non-zero?

2016-12-16 19:55 UTC, pecameron commented on admin_guide/high_availability.adoc
> +The *keepalived* port monitoring feature uses a simple port check ( </dev/tcp/<ip>/<watch-port> ) to verify that the application is running. The admin can provide a script that does whatever addition
OK

2016-12-16 20:20 UTC, pecameron commented on admin_guide/high_availability.adoc
> +For each VIP, *keepalived* keeps the state of the node. The VIP on the node may be in *MASTER*, *BACKUP*, or *FAULT* state.  All nodes that are not in the *FAULT* state negotiate to decide who will b
The every keepalived (on all nodes) runs the check script on a set period.  When MASTER fails, trigger a renegotiation for MASTER. When BACKUP fails just enter FAULT. When FAULT fails do nothing. When FAULT passes, trigger a renegotiation. When MASTER or BACKUP passes, do nothing.

2016-12-16 20:21 UTC, pecameron commented on admin_guide/high_availability.adoc
> +The script has no input arguments and must return 0 for OK and 1 for fail.
keepalived looks for 1 for FAIL.

2016-12-16 20:36 UTC, pecameron commented
@knobunc PTAL

2016-12-16 21:16 UTC, knobunc approved these changes
LGTM @openshift/team-documentation over to you

2016-12-19 19:12 UTC, ahardin-rh commented
Thank you! I will apply minor style edits in a follow-up PR.

2016-12-19 19:12 UTC, merged

2016-12-19 21:57 UTC, ahardin-rh commented
[rev_history]
|xref:../admin_guide/high_availability.adoc#admin-guide-high-availability[High Availability]
|Added new options to 'oadm ipfailover' to configure the *check* and *notify* scripts and to control the period of time the *check* script runs.
%