Bug 1260240 fixed info on creating node config files
openshift/openshift-docs pull request #3361
Opened 2016-12-12 03:55 UTC by bfallonf

As per: https://bugzilla.redhat.com/show_bug.cgi?id=1260240

I added the cert options to the example command. Also, did some rewording.

@DirectXMan12 can I get an ack this is what you were explaining to me over email? Thanks!

cc: @rjhowe

2017-02-09 19:24 UTC, DirectXMan12 requested changes
minor nit, otherwise I think this looks good

2017-02-09 19:24 UTC, DirectXMan12 commented on install_config/master_node_configuration.adoc
> +files are located in an *_openshift.local.config/master/_* directory. If they
not sure this line is needed any more, since we explicitly specify the path to the certs above

2017-02-10 00:59 UTC, bfallonf commented
Thanks @DirectXMan12 . I've made the suggested change.

@ahardin-rh @bmcelvee @adellape Peer review please?

2017-02-10 14:19 UTC, ahardin-rh commented on install_config/master_node_configuration.adoc
> +Creating new configuration files is useful to get a starting point for defining
This sentence is a little awkward to me. Maybe we can edit it to something like the following? 
To define your configuration, start by creating new configuration files.

2017-02-10 14:20 UTC, ahardin-rh commented
Just one comment from me, otherwise looks good! :star2:

2017-02-13 01:51 UTC, bfallonf commented
[rev_history]
|xref:../install_config/master_node_configuration.adoc#install-config-master-node-configuration[Aggregating Container Logs]
|Fixed the options for creating a configuration file in the xref:../install_config/master_node_configuration.adoc#creating-new-configuration-files[Creating New Configuration Files] section.
%

2017-02-13 01:51 UTC, merged