[RFE] Router sets its dns name in admitted routes
openshift/openshift-docs pull request #3377
Opened 2016-12-13 20:40 UTC by pecameron

Openshift 3.5 feature

The router is managed by the cluster admin and the admin knows the
external dns name of the router. The user creates routes to route
desired
host DNS names to the the application. The user doesn't have access
to the router (which is usually in a diffeent namespace). When a router
admits a route the user needs to work with the external DNS admin to
point the route's hostname to the router. Previously the user had to
contact the cluster admin to find the dns name of the router.

This change adds the --router-dns-name= option to oadm router which
creates and populates the ROUTER_DNS_NAME environment variable in the
router's dc. Whenever the router reloads and evaluates the routes the
route's status is edited to include the router's dns name and namespace
so the user can quickly access the information. If the ROUTER_DNS_NAME
is updated or added to an existing router the new information is updated
in the admitted routes on the next reload.

The route (oc get route -o yaml) status reports the name
of the router(s) that have admitted the route. This change adds the
Router's DNS name and namespace to the status in the route.

The information is also reported in "oc describe route" as shown below.

Example:

oadm router myroutername --router-dns-name=oh.my.heavens.org

oc get dc/myroutername -o yaml
...
spec:
  template:
    spec:
      containers:
        - env:
          - name: ROUTER_DNS_NAME
            value: oh.my.heavens.org

oc get route hello-route3 -o yaml
...
status:
  ingress:

    conditions:
      lastTransitionTime: 2016-12-07T15:20:57Z
      status: "True"
      type: Admitted
      host: hello-openshift-v3.not.in3.mycloud.com
      routerDnsName: oh.my.heavens.org
      routerName: myroutername
      routerNamespace: default
      wildcardPolicy: None

oc describe route/hello-route3
...
Requested Host: hello-openshift-v3.not.in3.mycloud.com
exposed on router default/myroutername (DNS oh.my.heavens.org) 12 minutes ago

Resolves: 1393489 https://bugzilla.redhat.com/show_bug.cgi?id=1393489
Resolves origin-web-console issue 336
Trello:
https://trello.com/c/BLASUOQC/376-5-add-a-way-to-pass-a-preferred-dns-name-to-routers-to-populate-route-statuses-ingress-usability
https://github.com/openshift/origin/pull/12195

Signed-off-by: Phil Cameron <pcameron@redhat.com>

2016-12-13 20:43 UTC, pecameron commented
@knobunc First draft of router DNS Name doc changes PTAL

2017-01-13 21:38 UTC, pecameron commented
@knobunc changed from dns name to hostname PTAL

2017-01-18 16:19 UTC, pecameron commented
@knobunc changed to --router-canonical-hostname and ROUTER_CANONICAL_HOSTNAME 
PTAL

2017-01-18 17:06 UTC, knobunc requested changes

2017-01-18 17:06 UTC, knobunc commented on install_config/router/default_haproxy_router.adoc
> +For routers that already exist, the cluster admin can edit the router's dc and add the information
Say deployment config not dc (here and throughout)

2017-01-18 17:06 UTC, knobunc commented on install_config/router/default_haproxy_router.adoc
> +list and finds the host name of the router to pass along to the network admin.
Hopefully the cluster administrator documents how to make that selection if multiple admit the route...

2017-01-18 17:06 UTC, knobunc commented on install_config/router/default_haproxy_router.adoc
> +The user can run *oc get route -o yaml* to show the route status. The route status
Should this paragraph be lower?  It feels out of order.

2017-01-18 17:06 UTC, knobunc commented on install_config/router/default_haproxy_router.adoc
> +With the above information in hand, the user can ask the network admin to have traffic to
Maybe not network admin, but DNS admin?  And ask them to set up a CNAME from ... to ...

2017-01-18 17:06 UTC, knobunc commented on install_config/router/default_haproxy_router.adoc
> +the route the router places the value in the routerHostname field in the route status.  The user
the route, the router

2017-01-18 18:10 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +This can be done by setting up a DNS CNAME record to point to the host name of the router.
@knobunc changed

2017-01-18 18:10 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +The host name of the router may not be know to the user. When it is not, the cluster administrator
Chanaged

2017-01-18 18:11 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +creating the router. The *--routeri-canonical-hostname* is a string that contains the external
Changed

2017-01-18 18:12 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +For routers that already exist, the cluster admin can edit the router's dc and add the information
Changed.

2017-01-18 18:13 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +in the *ROUTER_CANONICAL_HOSTNAME* environment variable.  The current *ROUTER_iCANONICAL_HOSTNAME*
Changed

2017-01-18 18:16 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +The user can run *oc get route -o yaml* to show the route status. The route status
Moved it lower

2017-01-18 18:19 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +list and finds the host name of the router to pass along to the network admin.
@knobunc Isn't router to application a potentially many to one mapping? You can pick any router that admits the route and get traffic to the application. What do you want to say here?

2017-01-18 18:21 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +the route the router places the value in the routerHostname field in the route status.  The user
Changed

2017-01-18 18:25 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +With the above information in hand, the user can ask the network admin to have traffic to
Reworded this.

2017-01-23 18:12 UTC, pecameron commented
@knobunc Any further changes needed before moving this along?

2017-01-23 21:02 UTC, knobunc requested changes

2017-01-23 21:02 UTC, knobunc commented on install_config/router/default_haproxy_router.adoc
> +The user can set up their DNS with a CNAME that points to this hostname.
We need to either say 'host name' or 'hostname' consistently throughout.  I think hostname is now preferred in the later RFCs.

2017-01-23 21:02 UTC, knobunc commented on install_config/router/default_haproxy_router.adoc
> +creating the router. The *--router-canonical-hostname* is a string that contains the external
The argument to ... ?  The flag itself isn't that...

2017-01-23 21:02 UTC, knobunc commented on install_config/router/default_haproxy_router.adoc
> +in the *ROUTER_CANONICAL_HOSTNAME* environment variable.  The current *ROUTER_CANONICAL_HOSTNAME*
The current _value of_ ...

2017-01-24 16:10 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +The user can set up their DNS with a CNAME that points to this hostname.
OK changed to hostname

2017-01-24 16:14 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +creating the router. The *--router-canonical-hostname* is a string that contains the external
Changed wording

2017-01-24 16:17 UTC, pecameron commented on install_config/router/default_haproxy_router.adoc
> +in the *ROUTER_CANONICAL_HOSTNAME* environment variable.  The current *ROUTER_CANONICAL_HOSTNAME*
Changed wording.

2017-01-24 16:20 UTC, pecameron commented
@knobunc PTAL

2017-01-24 19:22 UTC, knobunc approved these changes
LGTM.  Thanks!

2017-01-24 19:23 UTC, knobunc commented
@openshift/team-documentation tech review complete.  Over to you

2017-01-25 00:08 UTC, vikram-redhat commented
@bfallonf - PTAL.

2017-01-25 05:06 UTC, bfallonf commented on architecture/core_concepts/routes.adoc
> +|`*ROUTER_CANONICAL_HOSTNAME*` | | The (optional) hostname of the router that is shown in the in route statuses.
@pecameron Can I ask: "that is shown in the in route statuses".

Should that be "that is shown in the route status" or should it have markup (is it some sort of parameter or variable) like "that is shown in the `IN_ROUTE` statuses"

?

2017-01-25 05:08 UTC, bfallonf commented
@pecameron I just have one question, but when that's answered I can merge and perhaps do some style followups. Otherwise, looks good!

2017-01-25 13:37 UTC, pecameron commented on architecture/core_concepts/routes.adoc
> +|`*ROUTER_CANONICAL_HOSTNAME*` | | The (optional) hostname of the router that is shown in the in route statuses.
@bfallonf should be status. Fixed...

2017-01-30 04:05 UTC, bfallonf commented on architecture/core_concepts/routes.adoc
> +|`*ROUTER_CANONICAL_HOSTNAME*` | | The (optional) hostname of the router that is shown in the in route statuses.
Sure. Thanks @pecameron . I'll merge this and do a followup.

2017-01-30 04:05 UTC, merged