MIG-744: MTC 1.5.0 release notes
openshift/openshift-docs pull request #33807
Opened 2021-06-23 08:55 UTC by apinnick

2021-06-28 12:58 UTC, eriknelson requested changes

2021-06-28 12:58 UTC, eriknelson commented on migration-toolkit-for-containers/mtc-1-5-release-notes.adoc
> +* The web console can contain up to 50 migration plans. Previously, performance was impaired if multiple migration plans were created.
> The web console can contain up to 50 migration plans.

This isn't correct, unsure where this comes from. There is no concrete limit; it's paginated.

Performance was impaired at *scale*, think 100s of plans. The way this is worded, it suggests a handful of plans impaired the performance, which is also not true.

1.5.0 is designed to support hundreds of plans, which we believe to be a likely quantity based on the default limitation of the amount of namespaces that a plan supports and the fact that many customers will likely have thousands of namespaces.

2021-06-28 14:19 UTC, mikemckiernan commented on _topic_map.yml
> +- Name: Release notes
Please include the product name, project name, or some other way to identify these release notes as separate from the platform release notes.  As an example, see how [CI/CD pipelines](https://docs.openshift.com/container-platform/4.7/cicd/pipelines/op-release-notes.html) did it.

2021-06-28 14:22 UTC, mikemckiernan commented on migrating_from_ocp_3_to_4/migrating-applications-3-4.adoc
> +During migration, the {mtc-full} ({mtc-short}) preserves the following namespace annotations:
One consideration, you can prolly get away with {mtc-short} like you did in the preceding para. Up to you.

2021-06-28 14:23 UTC, mikemckiernan commented on migration-toolkit-for-containers/migrating-applications-with-mtc.adoc
> +During migration, the {mtc-full} ({mtc-short}) preserves the following namespace annotations:
If you removed mtc-full in the previous file, friendly reminder to remove it here.

2021-06-28 14:28 UTC, mikemckiernan approved these changes
Looks good.  Only thought (beside qualifying that the release notes are for MTC) is that this PR merges to master whereas the platform release notes are branch specific.  I do not know the advantages and disadvantages, just sharing in case it affects which branch you want to merge to.

2021-06-29 07:07 UTC, merged

2021-06-29 07:07 UTC, apinnick commented
/cherrypick enterprise-4.8