[WIP] TELCODOCS-237: updating version number 4.7 to 4.8
openshift/openshift-docs pull request #33875
Opened 2021-06-24 12:50 UTC by kquinn1204

TELCODOCS-237 - updating hardcoded version numbers to 4.8

Making updates to the version number in section "Performance Addon Operator for low latency nodes"

4.7 updated to 4.8 here https://docs.openshift.com/container-platform/4.8/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.html#installing-the-performance-addon-operator_cnf-master 

At release time the version will report 4.8. Now if you test it will read 4.7 but at release time the PAO version to be picked up will be 4.8. 
CNF tests sections have been revised from 4.7 to 4.8 https://docs.openshift.com/container-platform/4.8/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.html#cnf-performing-end-to-end-tests-for-platform-verification_cnf-master

2021-06-24 14:02 UTC, kquinn1204 commented
Hi @MarSik I was checking through section on Performance Addon Operator for low latency nodes and made updates to ensure version 4.8 was reflected in the correct place. Content is here https://deploy-preview-33875--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes. CNF tests had reference to 4.6 which I believe would be incorrect for 4.8 so I updated that section. 
https://deploy-preview-33875--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes#cnf-performing-end-to-end-tests-for-platform-verification_cnf-master
plus this section had 4.6 reference and I updated to 4.8 
https://deploy-preview-33875--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes#configuring_for_irq_dynamic_load_balancing_cnf-master

plus here https://deploy-preview-33875--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes#install-operator-cli_cnf-master

I think I captured all changes in this section. I am just looking for someone to check. Hoping you may be able to do that.

2021-07-01 10:38 UTC, jcfrye77 commented
@MarSik Could you please let us know if you have compeleted the review of version number updates? Thanks very much.

2021-07-01 16:29 UTC, mrniranjan commented
@kquinn1204  i went through  the document some minor changes. 
Under the section **Tuning nodes for low latency with the performance profile**
```
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
 name: performance
spec:
 cpu:
  isolated: "5-15" 
  reserved: "0-4" 
 hugepages:
  defaultHugepagesSize: "1G"
  pages:
  -size: "1G"
   count: 16
   node: 0
 realTimeKernel:
  enabled: true  
 numa:  
  topologyPolicy: "best-effort"
 nodeSelector:
  node-role.kubernetes.io/worker-cnf: "" 
  ```
  Please make sure there is space between the parameter: "-size" to "- size" 
  Same in other places like "Adjusting the NIC queues with the performance profile"
  
  ```
  apiVersion: performance.openshift.io/v2
  kind: PerformanceProfile
  metadata:
    name: manual
  spec:
    cpu:
    isolated: 3-51,54-103
    reserved: 0-2,52-54

    net:
    - userLevelNetworking: true         
    #!

    more examples:

      net:
        userLevelNetworking: true
        devices:
            -interfaceName: “eth0”
            -interfaceName: “eth1”      
            -vendorID: “0x1af4”
             deviceID: “0x1000”

      net:
       userLevelNetworking: true        
       devices:
        -interfaceName: “eth*”

      net:
       userLevelNetworking: true        
       devices:
        -interfaceName: “!eno1”

     net:
       userLevelNetworking: true        
       devices:
        -interfaceName: “eth0”
         vendorID: “0x1af4”
         deviceID: “0x1000”

    #!

      nodeSelector:
          node-role.kubernetes.io/worker-cnf: ""
```
to 
```
apiVersion: performance.openshift.io/v2
  kind: PerformanceProfile
  metadata:
    name: manual
  spec:
    cpu:
    isolated: 3-51,54-103
    reserved: 0-2,52-54

    net:
        userLevelNetworking: true         
    #!

    more examples:

      net:
         userLevelNetworking: true
         devices:
         -  interfaceName: “eth0”
         -  interfaceName: “eth1”      
         -  vendorID: “0x1af4”
         -  deviceID: “0x1000”

      net:
          userLevelNetworking: true        
        devices:
        -   interfaceName: “eth*”

      net:
         userLevelNetworking: true        
       devices:
       -  interfaceName: “!eno1”

     net:
         userLevelNetworking: true        
        devices:
        -   interfaceName: “eth0”
        -   vendorID: “0x1af4”
        -   deviceID: “0x1000”

    #!

      nodeSelector:
          node-role.kubernetes.io/worker-cnf: ""
```

2021-07-01 19:22 UTC, ktothill requested changes
Line 613 of _cnf-performing-end-to-end-tests-for-platform-verification.adoc_ needs space between hyphen and the word size (should be "- size"), per QE review. Otherwise, lgtm.

2021-07-05 10:59 UTC, kquinn1204 commented
So @ktothill and @jcfrye77 the only change requested here is "space between hyphen and the word size (should be "- size")". The adjusting netqueues feature is dealt with by another PR which was already reviewed by @mrniranjan and the changes are reflected in the published docs https://docs.openshift.com/container-platform/4.8/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.html#adjusting-nic-queues-with-the-performance-profile_cnf-master

2021-07-05 12:43 UTC, kquinn1204 commented
@mrniranjan Are you happy with the changes I have made?

2021-07-05 13:13 UTC, mrniranjan commented
@kquinn1204  Can you change this:
```
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: manual
spec:
  cpu:
    isolated: 3-51,54-103
    reserved: 0-2,52-54
  net:
    userLevelNetworking: true
    devices:
    - interfaceName: “eth0”
    - interfaceName: “eth1”
    - vendorID: “0x1af4”
    deviceID: “0x1000”
   nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
```
Please change the above to:
```
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: manual
spec:
  cpu:
    isolated: 3-51,54-103
    reserved: 0-2,52-54
  net:
    userLevelNetworking: true
    devices:
    - interfaceName: “eth0”
    - interfaceName: “eth1”
    - vendorID: “0x1af4”
    - deviceID: “0x1000”   
   nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""    
```

2021-07-05 13:14 UTC, mrniranjan commented
Rest everything looks good.

2021-07-05 13:26 UTC, vikram-redhat approved these changes
lgtm

2021-07-07 19:26 UTC, merged

2021-07-07 19:27 UTC, vikram-redhat commented
/cherrypick enterprise-4.8