Improve discussion on HTTP Proxies
openshift/openshift-docs pull request #3405
Opened 2016-12-16 18:37 UTC by pecameron

This was motivated by:
https://bugzilla.redhat.com/show_bug.cgi?id=1380342

Signed-off-by: Phil Cameron <pcameron@redhat.com>

2016-12-16 18:38 UTC, pecameron commented
@knobunc PTAL

2016-12-16 19:16 UTC, knobunc requested changes

2016-12-16 19:16 UTC, knobunc commented on install_config/http_proxies.adoc
>  `*NO_PROXY*` accepts a comma-separated list of hosts:
hosts and CIDRs and IPs?

2016-12-16 20:27 UTC, pecameron commented on install_config/http_proxies.adoc
>  `*NO_PROXY*` accepts a comma-separated list of hosts:
Yes. I made the change.

2016-12-16 20:36 UTC, pecameron commented
@knobunc PTAL

2017-01-05 20:18 UTC, pecameron commented
@knobunc I made the change you suggested. Is there more to do here? PTAL

2017-01-05 20:59 UTC, knobunc approved these changes
LGTM.  Over to you @openshift/team-documentation

2017-01-05 20:59 UTC, knobunc commented
@pecameron presumably this applies to all releases they want to put it in?  (3.2 and up)

2017-01-06 01:32 UTC, vikram-redhat commented
@ahardin-rh - PTAL. Also @knobunc - applies to 3.2 and above?

2017-01-06 14:22 UTC, ahardin-rh commented
Overall, LGTM! I will apply some minor follow-up edits in a separate PR. Thanks!

2017-01-06 14:22 UTC, merged

2017-01-06 14:27 UTC, knobunc commented
@vikram-redhat @ahardin-rh: I believe it applies to all releases ( @pecameron please confirm).  But you needn't apply it to all of those versions if you don't want to.

2017-01-06 15:27 UTC, ahardin-rh commented
[rev_history]
|xref:../install_config/http_proxies.adoc#install-config-http-proxies[Working with HTTP Proxies]
|Added clarifying details about HTTP proxies.
%