Document enabling wildcard routes in the web console
openshift/openshift-docs pull request #3439
Opened 2017-01-03 15:23 UTC by spadgett

See https://github.com/openshift/origin-web-console/pull/853

2017-01-03 15:33 UTC, jwforres requested changes

2017-01-03 15:33 UTC, jwforres commented on install_config/router/default_haproxy_router.adoc
> +xref:../../install_config/web_console_customization.adoc#web-console-enable-wildcard-routes[Learn how to configure the web console for wildcard routes].
Is this consistent with how we normally link to other doc pages, seems like a lot of link text
cc @ahardin-rh ?

2017-01-03 15:33 UTC, jwforres commented on install_config/web_console_customization.adoc
> +. Save this script to a file (for example, *_enable-wildcard-routes.js_*):
Looks like you are missing the actual script content

2017-01-03 15:36 UTC, spadgett commented on install_config/web_console_customization.adoc
> +. Save this script to a file (for example, *_enable-wildcard-routes.js_*):
I see it?

2017-01-03 15:39 UTC, jwforres commented on install_config/web_console_customization.adoc
> +. Save this script to a file (for example, *_enable-wildcard-routes.js_*):
nevermind, my eyes were skipping right over it

2017-01-03 15:57 UTC, ahardin-rh commented on install_config/router/default_haproxy_router.adoc
> +xref:../../install_config/web_console_customization.adoc#web-console-enable-wildcard-routes[Learn how to configure the web console for wildcard routes].
@jwforres Yes, this seems verbose, but it is correct.

2017-01-03 16:26 UTC, knobunc approved these changes
LGTM.  Thanks!

2017-01-03 16:30 UTC, jwforres approved these changes

2017-01-03 16:30 UTC, jwforres commented
@ahardin-rh ok technical review is done on this

2017-01-03 16:32 UTC, ahardin-rh commented
Is this for 3.4?

2017-01-03 16:33 UTC, spadgett commented
@ahaile-redhat it's for 3.5

2017-01-05 22:44 UTC, ahardin-rh commented
Will do some minor follow-up edits in a follow-up PR. Thanks!

2017-01-05 22:44 UTC, merged

2017-01-05 22:55 UTC, ahardin-rh commented
[rev_history]
|xref:../install_config/web_console_customization.adoc#install-config-web-console-customization[Customizing the Web Console]
|Added a new section on xref:../install_config/web_console_customization.adoc#web-console-enable-wildcard-routes[enabling wildcard routes] in the web console.
%