TELCODOCS-82: Cluster provisioning
openshift/openshift-docs pull request #34819
Opened 2021-07-23 17:06 UTC by StephenJamesSmith

For version 4.8 Webscale Dev Preview

https://issues.redhat.com/browse/TELCODOCS-82

Direct link to doc preview: 

Signed-off-by: Stephen Smith stesmith@redhat.com

2021-07-23 18:48 UTC, skrthomas reviewed
One small comment and a question. Nice work :)

2021-07-23 18:48 UTC, skrthomas commented on modules/ztp-performance-addon-operator.adoc
> +The administrator can specify whether to update the kernel to rt-kernel, the CPUs to be reserved for
The list here needs to be more parallel. Suggest something like this, but up to you: The administrator can specify uptdating the kernel to rt-kernel, reserving CPUs for management workloads, and using CPUs for running the workloads.

2021-07-23 18:48 UTC, skrthomas commented on modules/ztp-sriov-operator.adoc
> +The SR-IOV Operator allows network interfaces to be virtualized and shared at a device level with networking functions running within the cluster.
Could virtualized just be virtual?

2021-07-23 18:49 UTC, ijolliffe requested changes
/lgtm would like the one minor comment addressed, but, not critical

2021-07-23 18:49 UTC, ijolliffe commented on modules/ztp-applying-the-ran-policies-for-monitoring-cluster-activity.adoc
> +Zero touch provisioning (ZTP) uses {rh-rhacm-first} as an orchestrator to apply the radio access network (RAN) policies using a policy-based governance approach to automatically monitor cluster activ
strike orchestrator (overloaded term)

2021-07-23 19:19 UTC, StephenJamesSmith commented
@juphoff @ijolliffe  Can I get your /lgtm?

2021-07-23 19:43 UTC, ijolliffe reviewed
/lgtm

2021-07-23 19:51 UTC, juphoff approved these changes
/lgtm

2021-07-24 12:59 UTC, StephenJamesSmith commented
@vikram-redhat Distros: openshift-webscale added back to topic map, Final assembly file included. Please merge.

2021-07-26 11:47 UTC, StephenJamesSmith commented
Conflict resolved.

2021-07-26 11:54 UTC, StephenJamesSmith commented
@vikram-redhat  Resolved conflict.

2021-07-26 14:18 UTC, bergerhoffer commented
Commits/diff/preview looks correct to me now. This can be merged.

2021-07-26 14:20 UTC, bobfuru approved these changes

2021-07-26 14:21 UTC, merged

2021-07-26 14:25 UTC, bergerhoffer commented
/cherrypick enterprise-4.8

2021-07-26 15:08 UTC, bergerhoffer commented
/cherrypick enterprise-4.8