Added description of the allowed/denied domain feature
openshift/openshift-docs pull request #3483
Opened 2017-01-12 20:12 UTC by knobunc

We have added a feature when we supported wildcard routes to also
limit some domains that can be used.  This adds the documentation of
the environment variables that control it.

2017-01-13 01:15 UTC, bfallonf commented
@knobunc Thanks! This is a new feature? So is it set for 3.4? I ask because this seems like something that would need more context somewhere else in the docs (perhaps a section named "Denying Domains" off the top of my head". I'm wondering if this is something being tracked for us.

2017-01-13 13:05 UTC, knobunc commented
@bfallonf it is in 3.4, but in tech-preview.  It was needed for the wildcard domain support that we added, but that is only usable by using JSON/YAML to create / edit objects.  We are going to improve the documentation for the wildcard routes and the allow/deny soon.  I was just making sure that the part of the docs that described all of the environment variables was at least complete.

2017-01-13 13:05 UTC, knobunc commented
@openshift/networking PTAL

2017-01-16 22:20 UTC, rajatchopra requested changes
Opinionated feedback :)

2017-01-16 22:20 UTC, rajatchopra commented on architecture/core_concepts/routes.adoc
> +|`*ROUTER_ALLOWED_DOMAINS*` | | A comma separated list of domains that the hostname in a route can only be part of.  Any subdomain in the domain can be used either.  Checked after denied domains.  If
s/either/too ?
s/Checked after denied domains/Option 'ROUTER_DENIED_DOMAINS' overrides any values given in this option/ ?

2017-01-16 22:20 UTC, rajatchopra commented on architecture/core_concepts/routes.adoc
> +|`*ROUTER_DENIED_DOMAINS*` | | A comma separated list of domains that the hostname in a route can not be part of.  No subdomain in the domain can be used either.  Checked before allowed domains.
s/Checked before allowed domains/Overrides option 'ROUTER_ALLOWED_DOMAINS'/ ?

2017-01-17 18:57 UTC, knobunc commented
@bfallonf it was released in 3.4 but not documented.  Wildcard domains is much better supported (with CLI and webconsole) in 3.5 so it's probably okay if the rest of the docs go there alone.

We are tracking the further work at https://trello.com/c/Gj4hbRd3

2017-01-17 20:38 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +|`*ROUTER_ALLOWED_DOMAINS*` | | A comma separated list of domains that the hostname in a route can only be part of.  Any subdomain in the domain can be used either.  Checked after denied domains.  If
I was trying to be terse, but I like these edits more.

2017-01-19 18:12 UTC, knobunc commented
@rajatchopra took your suggestions.  PTAL

2017-01-23 18:23 UTC, ramr commented
LGTM 
@knobunc thanks for documenting this. It is tech-preview (originally more of a testing tool) but I wonder if it would make more sense to have these values read from a file which allows a blacklist set to be more extensible. Setting the whitelist is probably `ok/manageable`  via a environment variable but blacklist could well be `yuge` (why is that now in my vocabulary!!).

2017-01-23 19:03 UTC, rajatchopra approved these changes

2017-01-23 19:03 UTC, rajatchopra commented
LGTM. Ready to merge.

2017-01-23 19:06 UTC, ramr approved these changes
LGTM

2017-01-23 20:25 UTC, knobunc commented
@ramr @rajatchopra thanks for the reviews.

@openshift/team-documentation tech review is done, over to you.

2017-02-06 16:49 UTC, knobunc commented
@openshift/team-documentation Any thoughts?

2017-02-06 19:25 UTC, ahardin-rh commented
Thanks! I will apply some minor style edits in a separate PR.

2017-02-06 19:25 UTC, merged

2017-02-06 20:27 UTC, ahardin-rh commented
[rev_history]
|xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
|Added descriptions for `ROUTER_ALLOWED_DOMAINS` and `ROUTER_DENIED_DOMAINS` in the xref:../architecture/core_concepts/routes.adoc#env-variables[Router Configuration Parameters] table.
%