CNF-500 - fix xref typo
openshift/openshift-docs pull request #34852
Opened 2021-07-26 19:03 UTC by aireilly

Adds a typo doc fix for https://issues.redhat.com/browse/CNF-1500. An xref typo causes a 404.

2021-07-29 13:27 UTC, cadawson requested changes
New link: link: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html/install/installing#install-on-disconnected-networks[Install {rh-rhacm} on disconnected networks]

2021-08-16 13:06 UTC, mburke5678 commented
@aireilly Is there a preview available for this change?

2021-08-16 13:49 UTC, aireilly commented
> @aireilly Is there a preview available for this change?

There is not - this is for the openshift-webscale password protected developer preview, which is not supported in the current GH preview build. However - for the purposes of review, I've "hot-wired" `_topic_map.yml` to allow a preview, once you review, I will undo this change. Preview is at: https://deploy-preview-34852--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp-deploying-disconnected.html#installing-disconnected-rhacm_ztp-deploying-disconnected

2021-08-16 13:59 UTC, mburke5678 commented
@aireilly LGTM. Thanks for the hot-wired preview.

2021-08-16 14:01 UTC, aireilly commented
@mburke5678 Great! just removed the "hot-wire", so good for merge, thank you :)

2021-08-18 18:07 UTC, merged

2021-08-18 18:08 UTC, mburke5678 commented
/cherrypick enterprise-4.8

2021-08-24 12:42 UTC, aireilly commented
/cherrypick enterprise-4.9