MIG-766: proxy config
openshift/openshift-docs pull request #35065
Opened 2021-08-01 09:16 UTC by apinnick

2021-08-19 13:20 UTC, XinRedhat commented
LGTM

2021-08-19 14:27 UTC, sergiordlr approved these changes
Looks good to me. Thank you very much!

2021-08-19 14:39 UTC, EricPonvelle requested changes
Small suggestion

2021-08-19 14:43 UTC, apinnick commented on modules/migration-configuring-proxies.adoc
> +For {product-title} 3.x and 4.1, you must configure proxies in the `MigrationController` custom resource (CR) manifest after you install the {mtc-short} Operator because these versions do not support
No, that is the correct name of the Operator. I am referring to the MTC Operator, not the product.

2021-08-23 08:25 UTC, merged

2021-08-23 08:26 UTC, apinnick commented
/cherrypick enterprise-4.6

2021-08-23 08:26 UTC, apinnick commented
/cherrypick enterprise-4.7

2021-08-23 08:26 UTC, apinnick commented
/cherrypick enterprise-4.8

2021-08-23 08:26 UTC, apinnick commented
/cherrypick enterprise-4.9