Notes for 4.7.24 release
openshift/openshift-docs pull request #35475
Opened 2021-08-12 20:28 UTC by opayne1

Release notes for 4.7.24 release

- Applies to `enterprise-4.7`

2021-08-16 15:34 UTC, opayne1 commented on release_notes/ocp-4-7-release-notes.adoc
> +
PTAL lines 2775-2780 especially. TY!

2021-08-16 17:46 UTC, EricPonvelle requested changes

2021-08-16 17:46 UTC, EricPonvelle commented on release_notes/ocp-4-7-release-notes.adoc
> +*  Previously, the installer created out-of-order noProxy values due to allowiuing for spaces in the imput paseed for noProxy. With this update, spaces in the imput were removed to sort the values. (
s/allowiuing/allowing

2021-08-16 17:46 UTC, EricPonvelle commented on release_notes/ocp-4-7-release-notes.adoc
> +*  Previously, `ovn-kubernetes` handled some NetworkPolicies with multiple `ipBlocks` unable to reach all IPs . With this update, generating OVN ACLs from kubernetes NetworkPolicies with multiple `ip
Remove the extra space between IPs and the period.

2021-08-16 17:46 UTC, EricPonvelle commented on release_notes/ocp-4-7-release-notes.adoc
> +*  Previously, custome tolerations from `spec.tolerations` were only applied when `spec.nodeSelector` was set. With this update, the operator will use custom tolerations if `spec.tolerations` is set.
I believe s/custome/custom

2021-08-16 18:01 UTC, EricPonvelle commented on release_notes/ocp-4-7-release-notes.adoc
> +*  Previously, `ovn-kubernetes` handled some NetworkPolicies with multiple `ipBlocks` unable to reach all IPs . With this update, generating OVN ACLs from kubernetes NetworkPolicies with multiple `ip
s/IPs/IP addresses

2021-08-16 18:04 UTC, EricPonvelle commented on release_notes/ocp-4-7-release-notes.adoc
> +*  Previously, the installer created out-of-order noProxy values due to allowiuing for spaces in the imput paseed for noProxy. With this update, spaces in the imput were removed to sort the values. (
s/installer/installation program.

s/imput/input (2x)

s/paseed/passed

s/noProxy values/`noProxy` values

2021-08-16 18:05 UTC, EricPonvelle commented on release_notes/ocp-4-7-release-notes.adoc
> +*  Previously, `ovn-kubernetes` handled some NetworkPolicies with multiple `ipBlocks` unable to reach all IPs . With this update, generating OVN ACLs from kubernetes NetworkPolicies with multiple `ip
s/kubernetes NetworkPolicies/Kubernetes NetworkPolicies

2021-08-16 18:06 UTC, EricPonvelle commented on release_notes/ocp-4-7-release-notes.adoc
> +*  Previously, custome tolerations from `spec.tolerations` were only applied when `spec.nodeSelector` was set. With this update, the operator will use custom tolerations if `spec.tolerations` is set.
s/operator/Operator

2021-08-16 18:11 UTC, EricPonvelle commented
enterprise-4.7

2021-08-16 19:39 UTC, EricPonvelle commented on release_notes/ocp-4-7-release-notes.adoc
> +*  Previously, OVN-Kubernetes handled some NetworkPolicies with multiple `ipBlocks` unable to reach all IPs. With this update, generating Open Virtual Network (OVN) ACLs from kubernetes NetworkPolici
s/IPs/IP addresses

2021-08-17 13:38 UTC, EricPonvelle approved these changes
/lgtm

2021-08-17 13:40 UTC, merged