Document the experimental registry signature endpoint
openshift/openshift-docs pull request #3556
Opened 2017-01-23 10:09 UTC by mfojtik

This is WIP, I would like to add example of how you can sign the image using `atomic sign` or `atomic push` (@aweiteka to the rescue :-)

@openshift/team-documentation @miminar @legionus PTAL

Also i'm not sure what is the "right" section where this documentation should live (do we have something like "advanced registry" chapter?

The relevant Origin PR: https://github.com/openshift/origin/pull/12504

Also this documentation is for 3.4.1+ (do we have any label that says what is the target release? ;-)

2017-01-23 16:35 UTC, aweiteka requested changes
- Since this is a reference for someone integrating with the API it would be good to have a pointer to this page from the rest_api/index.adoc overview page. That would also tie in the story that these are useful OCP extensions found all in one place.
- Consider swapping the order so writing comes before reading to make for an example that actually works.

2017-01-24 10:45 UTC, mfojtik commented
@aweiteka thanks! comments addressed.

2017-01-24 13:34 UTC, miminar requested changes
Just a few remarks.

2017-01-24 13:34 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +{product-title} API, but this endpoint allows you to read and write them without
*API* - can we use etcd, storage or database instead?

2017-01-24 13:34 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +PUT /extensions/v2/{namespace}/{name}/signatures/sha256:{digest}
`digest` includes `sha256:` prefix

2017-01-24 13:34 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +the following format: `sha256:<digest>@<name>`. The `name` has to be 32 character long.
Explain that the first part is image name and the second is signature name. And that the first part must match the `<digest>` parameter of the endpoint.

2017-01-24 13:34 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +GET /extensions/v2/{namespace}/{name}/signatures/sha256:{digest}
`digest` includes `sha256:`
https://github.com/docker/distribution/blob/master/docs/spec/api.md#content-digests

2017-01-24 13:34 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +following format: `sha256:<digest>@<name>`. The `name` has to be 32 character long.
`<image-name>@<signature-name>` or something like that

2017-01-24 14:50 UTC, mfojtik commented on install_config/registry/accessing_registry.adoc
> +{product-title} API, but this endpoint allows you to read and write them without
we can but we don't at this point? (don't want to make it more confusing)

2017-01-25 08:18 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +{product-title} API, but this endpoint allows you to read and write them without
Let me explain. When you say API, I imagine just an interface, not a storage. So I find it hard to imagine that API stores something.So I wonder if there's any better word we can use as a replacement for the API. Another attempt: *key value store*?

2017-01-25 13:53 UTC, aweiteka commented on install_config/registry/accessing_registry.adoc
> +{product-title} API, but this endpoint allows you to read and write them without
How about, "The image signatures are stored in the {product-title} key-value store via API"?

2017-02-07 18:12 UTC, ahardin-rh commented on install_config/registry/accessing_registry.adoc
> +See https://docs.docker.com/registry/spec/api/[upstream API documentation] for general
link:https://docs.docker.com/registry/spec/api/[upstream API documentation]

2017-02-07 18:13 UTC, ahardin-rh commented on install_config/registry/accessing_registry.adoc
> +
Place this ID above the heading:
[[writing-image-signatures]]

2017-02-07 18:13 UTC, ahardin-rh commented on install_config/registry/accessing_registry.adoc
> +the following format: `sha256:<digest>@<name>`. The `name` has to be 32 character long.
s/character/characters

2017-02-07 18:14 UTC, ahardin-rh commented on install_config/registry/accessing_registry.adoc
> +In order to attach the signature to the Docker Image the user needs to have the `system:image-signer` role.
s/Image/image,
s/needs to have/must have

2017-02-07 18:16 UTC, ahardin-rh commented on install_config/registry/accessing_registry.adoc
> +Assuming that you have already pushed signed Docker Image into {product-title} integrated Docker
the signed Docker image into the {product-title} ...

2017-02-07 18:17 UTC, ahardin-rh commented on install_config/registry/accessing_registry.adoc
> +
add this ID before the heading:
[[reading-image-signatures]]

2017-02-07 18:17 UTC, ahardin-rh commented on install_config/registry/accessing_registry.adoc
> +refers to the name of the Image. The `digest` represents the SHA256 checksum of the Image.
s/Image/image  (a few instances across the page)

2017-03-07 10:40 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +The `name` field contains the name of the image signature, which has to be unique and in
The `name` field can be confused with the `<name>` from the curl command above. Maybe `<isname> could be used instead there?

2017-03-07 10:42 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +Where the `namespace` represents the {product-title} project name or Docker Registry repository name and the `name`
`name` refers to the repository, not the image

2017-03-07 11:05 UTC, mfojtik commented on install_config/registry/accessing_registry.adoc
> +{product-title} API, but this endpoint allows you to read and write them without
fixed.

2017-03-07 11:07 UTC, mfojtik commented on install_config/registry/accessing_registry.adoc
> +The `name` field contains the name of the image signature, which has to be unique and in
it says "name field"

2017-03-07 11:11 UTC, mfojtik commented on install_config/registry/accessing_registry.adoc
> +refers to the name of the Image. The `digest` represents the SHA256 checksum of the Image.
tried to fix them all.. in some cases I was refering to image and in some cases to API Image object... I dunno if we make distincion between them.

2017-03-07 11:12 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +with the JSON payload sent the extensions endpoint:
The sentence makes sense to me until **`sent`**.

2017-03-07 11:13 UTC, mfojtik commented
@ahardin-rh @miminar tried to address all comments, PTAL

2017-03-07 11:18 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +with the JSON payload sent the extensions endpoint:
I understand this sentence until **`sent`**.

2017-03-07 11:22 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +$ curl -X PUT --data @signature.json http://<user>:<token>@<registry-endpoint>:5000/extensions/v2/<namespace>/<name>/signatures/sha256:<digest>
To be consistent, replace all the occurences of `sha256:<digest>` with just `<digest>`.

2017-03-07 11:24 UTC, miminar requested changes
Just a few minor glitches.

2017-06-08 21:16 UTC, adellape commented
![](https://github.trello.services/images/mini-trello-icon.png) [Document: Add registry endpoint for reading and writing image signatures](https://trello.com/c/RacGhyYi/445-document-add-registry-endpoint-for-reading-and-writing-image-signatures)

2017-06-12 08:53 UTC, miminar commented on install_config/registry/accessing_registry.adoc
> +with the JSON payload sent the extensions endpoint:
Still valid.

2017-06-20 20:49 UTC, adellape commented
Closing this and continuing via https://github.com/openshift/openshift-docs/pull/4623, PTAL there.

2017-06-20 20:49 UTC, closed without merging