Rel Notes doc text for 4.8.9 release
openshift/openshift-docs pull request #35867
Opened 2021-08-27 18:26 UTC by jeana-redhat

For release 2021.08.31.

2021.08.30: version bumped to 4.8.9

Preview: https://deploy-preview-35867--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-8-release-notes#ocp-4-8-9

2021-08-27 19:05 UTC, EricPonvelle requested changes
Just a small nitpick over a comma. Looks good otherwise!

2021-08-27 19:18 UTC, EricPonvelle approved these changes
/lgtm

2021-08-30 19:10 UTC, jeana-redhat commented on release_notes/ocp-4-8-release-notes.adoc
> +* The address set naming convention used in OVN-Kubernetes for {product-title} 4.5 was changed in {product-title} 4.6, but the migration of existing address sets to the new naming convention was not
@jboxman thanks for taking a look! That makes me wonder if it's TMI, but it doesn seem to have some things a user might need to know. I will check in with #forum-sdn

2021-08-31 13:48 UTC, jeana-redhat commented on release_notes/ocp-4-8-release-notes.adoc
> +* The address set naming convention used in OVN-Kubernetes for {product-title} 4.5 was changed in {product-title} 4.6, but the migration of existing address sets to the new naming convention was not
SME acked :+1:

2021-08-31 14:02 UTC, sagidlow commented
LGTM.

2021-08-31 15:23 UTC, merged