OSDOCS-2471: Update capabilities list for SR-IOV DPDK and RDMA examples
openshift/openshift-docs pull request #35934
Opened 2021-08-30 21:28 UTC by jboxman

- https://issues.redhat.com/browse/OSDOCS-2471

This updates the examples with some required capabilities. Applies to all versions.

2021-08-30 21:28 UTC, jboxman commented
@EinatGlottmann, I've created this PR for the changes that apply to all releases.

2021-08-31 12:37 UTC, EinatGlottmann commented on modules/nw-sriov-dpdk-example-intel.adoc
>       capabilities:
Please add "runAsUser: 0" under the securityContext

securityContext structure should look as follows: 
securityContext:
  runAsUser: 0
  capabilities:
    add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"]

2021-08-31 12:37 UTC, EinatGlottmann commented on modules/nw-sriov-dpdk-example-mellanox.adoc
>      securityContext:
Please add "runAsUser: 0" under the securityContext

securityContext structure should look as follows: 
securityContext:
  runAsUser: 0
  capabilities:
    add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"]

2021-08-31 12:37 UTC, EinatGlottmann commented on modules/nw-sriov-rdma-example-mellanox.adoc
>      securityContext:
Please add "runAsUser: 0" under the securityContext

securityContext structure should look as follows: 
securityContext:
  runAsUser: 0
  capabilities:
    add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"]

2021-08-31 12:39 UTC, EinatGlottmann commented
@jboxman, please also update the securityContext in the following page:
https://docs.openshift.com/container-platform/4.8/networking/hardware_networks/about-sriov.html#example-vf-use-in-pod_about-sriov

2021-09-12 02:49 UTC, jboxman commented
@EinatGlottmann, updated!

2021-09-12 10:20 UTC, EinatGlottmann requested changes
@jboxman, please update ipam config example 
https://github.com/openshift/openshift-docs/pull/35934/files#diff-4046d70daeba3eb42605e7d700c3cb9c3839d89d5b9cbd386fb5389e5e99fdc7R69 
to be the same as in the Mellanox NIC example in the document (it is the same as the correction you made here: https://github.com/openshift/openshift-docs/pull/35276)

2021-09-12 10:24 UTC, EinatGlottmann requested changes
@jboxman, please update the security context here as well 
https://github.com/openshift/openshift-docs/pull/35934/commits/a9d5a085fe1b5209343207f129466ac0a84f4728#diff-b654e3eca41e31ffaf2fd78074cd05a34d2326c0c1b91d84cf2f4136f838812eR48

2021-09-12 18:06 UTC, jboxman commented
> @jboxman, please update the security context here as well (same link, line 48)
> [a9d5a08#diff-b654e3eca41e31ffaf2fd78074cd05a34d2326c0c1b91d84cf2f4136f838812eR48](https://github.com/openshift/openshift-docs/commit/a9d5a085fe1b5209343207f129466ac0a84f4728#diff-b654e3eca41e31ffaf2fd78074cd05a34d2326c0c1b91d84cf2f4136f838812eR48)

I have this added in all 4 places now:

```
modules/nw-sriov-dpdk-example-intel.adoc:
  105        capabilities:
  106:         add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"] <3>
  107      volumeMounts:

modules/nw-sriov-dpdk-example-mellanox.adoc:
  108        capabilities:
  109:         add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"] <3>
  110      volumeMounts:

modules/nw-sriov-example-vf-function-in-pod.adoc:
  28        capabilities:
  29:         add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"]
  30      command: ["sleep", "infinity"]

modules/nw-sriov-rdma-example-mellanox.adoc:
  111        capabilities:
  112:         add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"] <3>
  113      volumeMounts:
```

Is that what you mean?

Thanks!

2021-09-12 18:16 UTC, EinatGlottmann commented
There is 1 more place: 
modules/nw-sriov-example-vf-function-in-pod.adoc  in line 48

2021-09-12 20:01 UTC, jboxman commented
@EinatGlottmann added

2021-09-13 06:43 UTC, EinatGlottmann approved these changes
LGTM

2021-09-14 02:28 UTC, jboxman commented
@zhaozhanqi, this PR adds changes that apply to all OCP versions; Does this look okay? Thanks!

2021-09-14 04:13 UTC, zhaozhanqi commented
ok, /lgtm

2021-09-14 17:16 UTC, merged

2021-09-14 17:16 UTC, jboxman commented
/cherry-pick enterprise-4.9

2021-09-14 17:18 UTC, jboxman commented
/cherry-pick enterprise-4.8

2021-09-14 17:24 UTC, jboxman commented
/cherry-pick enterprise-4.7