Add BestEffort definition
openshift/openshift-docs pull request #3596
Opened 2017-01-27 05:32 UTC by brennv

Wording from https://kubernetes.io/docs/admin/resourcequota/walkthrough/

2017-01-27 12:51 UTC, bparees commented on admin_guide/quota.adoc
> +pods that require a higher quality of service.
this still doesn't really tell me how i create a besteffort pod.  

The other page says that the BestEffort scope will "Match pods that have best effort quality of service for either cpu or memory."

I still don't understand how I set memory or cpu to "best effort"  (the reality, I believe, is that if you set a limit, but no request, for a given resource(eg memory or cpu) that is considered best effort for that resource, but I don't think we state that explicitly anywhere)

2017-01-27 13:36 UTC, brennv commented on admin_guide/quota.adoc
> +pods that require a higher quality of service.
Good point, maybe we need a new section with examples drawing inspiration from https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-qos.md#qos-classes

2017-02-01 18:29 UTC, derekwaynecarr requested changes

2017-02-01 18:29 UTC, derekwaynecarr commented on admin_guide/quota.adoc
> +pods that require a higher quality of service.
A BestEffort pod can use slack compute resources that are unused on its scheduled node.

A BestEffort pod is a pod that does not have a compute resource requirement for cpu and memory.

2017-02-01 18:31 UTC, derekwaynecarr commented on admin_guide/quota.adoc
> +pods that require a higher quality of service.
or just link to https://docs.openshift.org/latest/admin_guide/overcommit.html#qos-classes ?

2017-07-13 21:01 UTC, ahardin-rh commented
This is an old one, but is it about ready to go? Once this is updated, can you please give it a squash so that I can merge? Thanks!

2017-08-14 15:22 UTC, ahardin-rh commented
Continued work in https://github.com/openshift/openshift-docs/pull/5012

2017-08-14 15:22 UTC, closed without merging