MIG-813: MTC 1.6.0 release notes
openshift/openshift-docs pull request #36096
Opened 2021-09-05 14:27 UTC by apinnick

https://issues.redhat.com/browse/MIG-813

Release notes

4.6+

2021-09-09 11:12 UTC, apinnick commented
@XinRedhat  Please review.

2021-09-09 11:51 UTC, eriknelson requested changes
I'm seeing a blank section for "Technical Changes", what normally goes in this section?

2021-09-09 11:51 UTC, eriknelson commented on modules/migration-mtc-release-notes-1-6.adoc
> +You can migrate an application's state by selecting persistent volume claims (PVCs) and Kubernetes objects for migration.
Normal migrations have always migrated state. The way this is worded suggests this is a new feature to me. I think I would stress, with this release we've added new functionality that allows for ad-hoc, repeatable state only transfers on a PVC by PVC basis.

2021-09-09 11:51 UTC, eriknelson commented on modules/migration-mtc-release-notes-1-6.adoc
> +* Direct volume migration from a classic OpenShift cluster on IBM Cloud fails unless the application is stopped during migration. The IBM block storage plugin does not allow the same volume to be mou
To unblock this, the workload can be quiesced prior to a migration to ensure that there is only ever one pod mounting an RWO volume.

2021-09-09 13:16 UTC, sagidlow commented
LGTM!

2021-09-09 13:38 UTC, eriknelson approved these changes
LGTM

2021-09-12 09:06 UTC, apinnick commented
@XinRedhat Can you review the last item in "known issues"? BZ1963927

2021-09-13 08:50 UTC, XinRedhat commented
LGTM

2021-09-13 15:35 UTC, skrthomas approved these changes
LGTM!

2021-09-19 09:30 UTC, apinnick commented
Releasing with module commented out so that I can create separate PRs for additions to the RN.

2021-09-19 09:32 UTC, merged

2021-09-19 09:32 UTC, apinnick commented
/cherrypick enterprise-4.6

2021-09-19 09:32 UTC, apinnick commented
/cherrypick enterprise-4.7

2021-09-19 09:32 UTC, apinnick commented
/cherrypick enterprise-4.8

2021-09-19 09:33 UTC, apinnick commented
/cherrypick enterprise-4.9