RHDEVDOCS-3095
openshift/openshift-docs pull request #36314
Opened 2021-09-13 18:42 UTC by libander

- Aligned team: Dev Tools
- For branches: 
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3095
- Direct link to doc preview: TBD
- SME review: @
- QE review: @ tbd
- Peer review: @ 	tbd
- <All reviews complete. Please merge now>

2021-10-25 18:55 UTC, alanconway reviewed
/lgtm

2021-10-26 11:08 UTC, rolfedh approved these changes

2021-11-12 15:03 UTC, abrennan89 requested changes
@libander one small nit before merging, also can you please add a title for this PR

2021-11-12 15:03 UTC, abrennan89 commented on modules/cluster-logging-logstore-limits.adoc
> +<3> The minimum resources required to schedule a Pod.
There should be "pod" I think, see https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#general-references

2021-11-12 15:36 UTC, abrennan89 approved these changes

2021-11-12 15:39 UTC, merged

2021-11-12 15:39 UTC, abrennan89 commented
/cherrypick enterprise-4.7

2021-11-12 15:39 UTC, abrennan89 commented
/cherrypick enterprise-4.8

2021-11-12 15:39 UTC, abrennan89 commented
/cherrypick enterprise-4.9

2021-11-12 15:40 UTC, abrennan89 commented
/cherrypick enterprise-4.10