RHDEVDOCS-3296 - Add a link to OL 5.1.2 advisory to 5.1 release notes.
openshift/openshift-docs pull request #36379
Opened 2021-09-15 14:25 UTC by libander

- Aligned team: Dev Tools
- For branches: master, enterpris-4.8+
- https://issues.redhat.com/browse/RHDEVDOCS-3296
- Direct link to doc preview: TBD
- SME review: TBD
- QE review: TBD
- Peer review: TBD
- Please merge now.

2021-09-15 14:30 UTC, periklis reviewed
LGTM

2021-09-15 18:32 UTC, rolfedh commented on logging/cluster-logging-release-notes.adoc
> +This release includes link:https://access.redhat.com/errata/RHBA-2021:3550[RHBA-2021:3550 OpenShift Logging Bug Fix Release 5.2.1].
```suggestion
* This release includes link:https://access.redhat.com/errata/RHBA-2021:3550[RHBA-2021:3550 OpenShift Logging Bug Fix Release 5.2.1].
```

2021-09-15 18:32 UTC, rolfedh commented on logging/cluster-logging-release-notes.adoc
>  This release includes link:https://access.redhat.com/errata/RHBA-2021:3393[RHBA-2021:3393 OpenShift Logging Bug Fix Release 5.2.0].
```suggestion
* This release includes link:https://access.redhat.com/errata/RHBA-2021:3393[RHBA-2021:3393 OpenShift Logging Bug Fix Release 5.2.0].
```

2021-09-15 18:35 UTC, rolfedh commented on modules/cluster-logging-release-notes-5.1.0.adoc
>  This release includes:
The following advisories are available for OpenShift Logging 5.2.x:

2021-09-16 00:23 UTC, kabirbhartiRH commented
/lgtm

2021-09-16 06:32 UTC, periklis requested changes

2021-09-16 06:32 UTC, periklis commented on modules/cluster-logging-release-notes-5.1.0.adoc
> +The following advisories are available for OpenShift Logging 5.2.x:
Should that be `The following advisories are available for OpenShift Logging 5.1.x`?

2021-09-16 13:48 UTC, rolfedh approved these changes
@libander: After updating this PR for @periklis comment, please confirm that the advisory is live (the team decided to release the advisories today), and ask the merge-person to merge this PR.

2021-09-16 14:14 UTC, periklis approved these changes
/lgtm

2021-09-21 21:39 UTC, merged

2021-09-21 21:40 UTC, abrennan89 commented
/cherrypick enterprise-4.8

2021-09-21 21:40 UTC, abrennan89 commented
/cherrypick enterprise-4.9