OSDOCS-2358: release notes for custom error code response pages
openshift/openshift-docs pull request #36498
Opened 2021-09-17 14:10 UTC by skrthomas

https://issues.redhat.com/browse/OSDOCS-2358

Preview:

2021-09-23 09:25 UTC, miheer requested changes

2021-09-23 09:25 UTC, miheer commented on release_notes/ocp-4-9-release-notes.adoc
> +You can specify a custom error code response page for either 503, 404, or both error pages.
You can specify a custom **http** error code response page for either 503, 404, or both error pages.

2021-09-23 09:25 UTC, miheer commented on release_notes/ocp-4-9-release-notes.adoc
> +* Cluster administrators can specify a custom error code response page for either 503, 404, or both error pages. The router does not reload to reflect custom error code pages updates. As a workaround
Cluster administrators can specify a custom **http** error code response page for either 503, 404, or both error pages

2021-09-29 00:56 UTC, jechen0648 commented
> https://issues.redhat.com/browse/OSDOCS-2358
> 
> For 4.9
> 
> Known Issue: https://deploy-preview-36498--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes?utm_source=github&utm_campaign=bot_dp#ocp-4-9-known-issues
> 
> Preview: https://deploy-preview-36498--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes?utm_source=github&utm_campaign=bot_dp#ocp-4-9-networking
> 
> @miheer @jechen0648 ready for QA.

From this preview for ocp-4-8-networking, I saw under "Customizing HAProxy error code response pages" section, there is "For more information, see Customizing HAProxy error code response pages", if I click on hyperlink for "Customizing HAProxy error code response pages", it leads me to page:  https://deploy-preview-36498--osdocs.netlify.app/openshift-enterprise/latest/networking/ingress-operator.html#nw-customize-ingress-error-pages_configuring-ingress, and in this page, I do not see any place describe how to customize HAProxy error code response pages.      Did I look at wrong place?

2021-09-29 13:17 UTC, jechen0648 commented
> > https://issues.redhat.com/browse/OSDOCS-2358
> > For 4.9
> > Known Issue: https://deploy-preview-36498--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes?utm_source=github&utm_campaign=bot_dp#ocp-4-9-known-issues
> > Preview: https://deploy-preview-36498--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes?utm_source=github&utm_campaign=bot_dp#ocp-4-9-networking
> > @miheer @jechen0648 ready for QA.
> 
> From this preview for ocp-4-8-networking, I saw under "Customizing HAProxy error code response pages" section, there is "For more information, see Customizing HAProxy error code response pages", if I click on hyperlink for "Customizing HAProxy error code response pages", it leads me to page: https://deploy-preview-36498--osdocs.netlify.app/openshift-enterprise/latest/networking/ingress-operator.html#nw-customize-ingress-error-pages_configuring-ingress, and in this page, I do not see any place describe how to customize HAProxy error code response pages. Did I look at wrong place?

Thanks for clarification from Sara, this PR looks good to me.

2021-09-29 13:32 UTC, jechen0648 commented
/lgtm

2021-10-01 18:28 UTC, mikemckiernan reviewed
/lgtm

2021-10-01 18:28 UTC, merged

2021-10-12 14:02 UTC, skrthomas commented
#33497 (RN Tracker)