monitoring: Describe query log file feature for Prometheus
openshift/openshift-docs pull request #36495
Opened 2021-09-17 13:26 UTC by PhilipGough

2021-09-21 05:40 UTC, sthaha commented on modules/monitoring-setting-query-log-file-for-prometheus.adoc
> +$ oc -n openshift-monitoring exec prometheus-k8s-0 cat <path>
syntax for `oc exec` is `oc exec (POD | TYPE/NAME) [-c CONTAINER] [flags] -- COMMAND [args...]` 
hence it is safer to use `--` to separate `command` to be run

2021-10-08 07:49 UTC, Preeticp commented
@PhilipGough thank you for the PR, please note that since this PR is for the 4.10 version of docs, we can merge this PR only post the 4.9 GA. Meanwhile, depending on @bburt-rh 's capacity he will start reviewing the PR.

2021-11-15 09:15 UTC, PhilipGough commented
/hold

Depends on https://github.com/openshift/cluster-monitoring-operator

2022-02-14 13:20 UTC, jan--f requested changes
A copy/paste error sneaked in.

2022-02-14 13:20 UTC, jan--f commented on modules/monitoring-setting-query-log-file-for-prometheus.adoc
> +    prometheus:
```suggestion
    prometheusK8s:
```

2022-02-14 13:20 UTC, jan--f commented on modules/monitoring-setting-query-log-file-for-prometheus.adoc
> +.. Add `queryLogFile: <path>` for `prometheus` under `data/config.yaml`:
```suggestion
.. Add `queryLogFile: <path>` for `prometheusK8s` under `data/config.yaml`:
```

2022-03-17 20:22 UTC, bburt-rh commented
I've created an updated PR for this content at https://github.com/openshift/openshift-docs/pull/43449

2022-04-19 13:52 UTC, bburt-rh commented
@PhilipGough This PR can be closed, since the content from https://github.com/openshift/openshift-docs/pull/43449 has already been completed and merged.

2022-04-29 16:19 UTC, closed without merging