OSDOCS-1837: Release note for Ingress TLS 1.3 support
openshift/openshift-docs pull request #36649
Opened 2021-09-22 10:52 UTC by skrthomas

https://issues.redhat.com/browse/OSDOCS-1837

For 4.9

Preview:

2021-09-23 09:46 UTC, miheer requested changes

2021-09-23 09:46 UTC, miheer commented on release_notes/ocp-4-9-release-notes.adoc
> +==== Support added for TLS 1.3 and the Modern Profile
Support added for TLSv1.3 and the Modern Profile

2021-09-23 09:46 UTC, miheer commented on release_notes/ocp-4-9-release-notes.adoc
> +This release adds Ingress Controller support for TLS 1.3 and the `Modern` profile.
This release adds Ingress Controller support for using TLSv1.3 and the `Modern` profile in haproxy.

2021-09-23 09:57 UTC, miheer commented
@skrthomas 

In the product documentation, please delete statements that TLSv1.3 is not supported.

We also want to release notes in OCP 4.6, 4.7, 4.8 as follows -

In OCP 4.6, 4.7 and 4.8, 

The “Modern” profile will continue to be unsupported on OpenShift 4.6, 4.7, and 4.8; selecting it will continue to have the effect of enabling the “Intermediate” profile.
Specifying TLSv1.3 cipher suites will continue to have no effect; OpenShift router will enable Red Hat distributed OpenSSL’s default set of TLSv1.3 cipher suites which are  TLS_AES_128_CCM_SHA256,  TLS_CHACHA20_POLY1305_SHA256, TLS_AES_256_GCM_SHA384, TLS_AES_128_GCM_SHA256

2021-10-07 13:45 UTC, jeana-redhat reviewed
Just a couple small formatting things and a URL fix.

2021-10-08 19:48 UTC, merged

2021-10-12 13:59 UTC, skrthomas commented
#33497 (RN Tracker)