ipfailover - `Permission denied for check and notify scripts
openshift/openshift-docs pull request #3680
Opened 2017-02-06 19:06 UTC by pecameron

Openshift 3.5

Document setting execute permission in configMap in the RC
volumes:configMap:defaultMode: 493

bug 1408172
https://bugzilla.redhat.com/show_bug.cgi?id=1408172

2017-02-06 19:16 UTC, pecameron commented
@knobunc PTAL

2017-02-06 19:18 UTC, knobunc requested changes

2017-02-06 19:18 UTC, knobunc commented on admin_guide/high_availability.adoc
> +<4> This sets execute permission on the files. It is displayed in decimal, 493.
How about: "When it is read back it will be displayed in decimal (493)."

2017-02-06 19:40 UTC, pecameron commented on admin_guide/high_availability.adoc
> +<4> This sets execute permission on the files. It is displayed in decimal, 493.
OK

2017-02-06 19:40 UTC, pecameron commented
@knobunc PTAL

2017-02-07 14:44 UTC, knobunc requested changes

2017-02-07 14:44 UTC, knobunc commented on admin_guide/high_availability.adoc
> +    --source='{"configMap": { "name": "mycustomcheck", "defaultMode": 493}}'
Was 0755 not taken?

2017-02-07 15:00 UTC, pecameron commented
@knobunc - Do you want me to change it back?

https://bugzilla.redhat.com/show_bug.cgi?id=1408172 Comment 15
zhaozhanqi 2017-02-07 05:04:12 EST
@Phil Cameron

https://github.com/openshift/openshift-docs/pull/3680/files#diff-a61f10a803ea6517400a5aea7f6cf169R360

Please correct it to '493' instead of '0755' in json format.

2017-02-07 15:17 UTC, knobunc commented
I saw that.  I think people would rather define it in octal (unless for some reason it doesn't work).  So, if the command works, then revert the change.

2017-02-13 16:05 UTC, pecameron commented on admin_guide/high_availability.adoc
> +    --source='{"configMap": { "name": "mycustomcheck", "defaultMode": 493}}'
"defaultMode": 0755 does not work.
error: invalid character '7' after object key:value pair

2017-02-13 16:09 UTC, pecameron commented
Since 0755 doesn't work, do you want to go with 493? Is this OK to merge?

2017-02-13 18:23 UTC, knobunc commented
@pecameron Does '0755' work?  I know when I set it for testing on your machine I set 0755... but perhaps as a string.

2017-02-13 18:28 UTC, pecameron commented
0755 does not work. Use the example in the doc.

On 02/13/2017 01:23 PM, Ben Bennett wrote:
>
> @pecameron <https://github.com/pecameron> Does '0755' work? I know 
> when I set it for testing on your machine I set 0755... but perhaps as 
> a string.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/openshift/openshift-docs/pull/3680#issuecomment-279477126>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ANUgeqEHdTKZwpbXFa-ZLy3eTtLjm82fks5rcJ-TgaJpZM4L4l0S>.
>

2017-02-13 21:55 UTC, pecameron commented
@knobunc 
oc volume dc/rrr --add --overwrite --name=config-volume --mount-path=/etc/keepalive --source='{"configMap": { "name": "phil-keepalived", "defaultMode": '0755'}}'
error: invalid character '7' after object key:value pair

2017-02-13 22:36 UTC, knobunc commented
Huh weird.  I would have sworn I put in 0755 when we tested it.

-ben

On Mon, Feb 13, 2017 at 4:55 PM, Phil Cameron <notifications@github.com>
wrote:

> @knobunc <https://github.com/knobunc>
> oc volume dc/rrr --add --overwrite --name=config-volume
> --mount-path=/etc/keepalive --source='{"configMap": { "name":
> "phil-keepalived", "defaultMode": '0755'}}'
> error: invalid character '7' after object key:value pair
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/openshift-docs/pull/3680#issuecomment-279535440>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJkavQiuUPAQMzBgGpWmm58maevGpoOOks5rcNE-gaJpZM4L4l0S>
> .
>

2017-02-14 14:04 UTC, pecameron commented
You did put 0755 in the defaultMode while editing the dc. It took that 
and gave back 493.

On 02/13/2017 05:36 PM, Ben Bennett wrote:
> Huh weird. I would have sworn I put in 0755 when we tested it.
>
> -ben
>
> On Mon, Feb 13, 2017 at 4:55 PM, Phil Cameron <notifications@github.com>
> wrote:
>
> > @knobunc <https://github.com/knobunc>
> > oc volume dc/rrr --add --overwrite --name=config-volume
> > --mount-path=/etc/keepalive --source='{"configMap": { "name":
> > "phil-keepalived", "defaultMode": '0755'}}'
> > error: invalid character '7' after object key:value pair
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > 
> <https://github.com/openshift/openshift-docs/pull/3680#issuecomment-279535440>,
> > or mute the thread
> > 
> <https://github.com/notifications/unsubscribe-auth/AJkavQiuUPAQMzBgGpWmm58maevGpoOOks5rcNE-gaJpZM4L4l0S>
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/openshift/openshift-docs/pull/3680#issuecomment-279546104>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ANUgev7DFqvJk48spGdATLfoYCzVBMZkks5rcNrlgaJpZM4L4l0S>.
>

2017-02-14 14:11 UTC, knobunc approved these changes

2017-02-14 14:11 UTC, knobunc commented
OK LGTM then.  @openshift/team-documentation over to you.

2017-02-14 16:01 UTC, ahardin-rh commented
Looks good! Thank you! I am going to follow up with some very minor style edits in a separate PR.

2017-02-14 16:01 UTC, merged

2017-02-14 16:27 UTC, ahardin-rh commented
[rev_history]
|xref:../admin_guide/high_availability.adoc#admin-guide-high-availability[High Availability]
|In the xref:../admin_guide/high_availability.adoc#check-notify[Check and Notify Scripts] section, added that the `defaultMode` for the mounted `configMap` files must allow execution.
%