[SRVCOM-1559] Remove outdated sizing requirements
openshift/openshift-docs pull request #36964
Opened 2021-09-30 20:26 UTC by abrennan89

Jira: https://issues.redhat.com/browse/SRVCOM-1559

Applies for OCP 4.6+

Direct preview link: TBA

2021-09-30 21:15 UTC, cardil requested changes

2021-09-30 21:15 UTC, cardil commented on modules/serverless-cluster-sizing-req.adoc
> -====
I wonder if we should leave those. This is not minimal requirements, but something we've checked is okay to support.

2021-09-30 21:15 UTC, cardil commented on modules/serverless-cluster-sizing-req.adoc
> -The total size requirements to run {ServerlessProductName} are dependent on the applications deployed. By default, each pod requests approximately 400m of CPU, so the minimum requirements are based o
This paragraph I think is worth keeping as well.

2021-09-30 21:15 UTC, cardil commented on serverless/admin_guide/install-serverless-operator.adoc
> -HA is enabled for some Knative Serving components by default. You can disable HA by following the documentation on xref:../../serverless/admin_guide/serverless-ha.adoc#serverless-ha[Configuring high
This is valid information for sure relates to current state. I think it should be left.

2021-10-05 21:10 UTC, closed without merging

2021-10-05 21:17 UTC, abrennan89 commented
Superseded by https://github.com/openshift/openshift-docs/pull/37121