BZ1962929: documentation for increasing the AWS master flavor size
openshift/openshift-docs pull request #37639
Opened 2021-10-18 16:42 UTC by chinmayi-chandrasekar

Applies to 4.6+

https://bugzilla.redhat.com/show_bug.cgi?id=1962929

[Doc preview](https://deploy-preview-37639--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-host-practices)

Requires QE approval from @duanwei33

2021-10-19 11:25 UTC, mffiedler requested changes

2021-10-19 14:21 UTC, mffiedler approved these changes
/lgtm

2021-10-20 14:37 UTC, EricPonvelle reviewed
Few nitpicks in this. Let me know when you update, and I can re-review.

2021-10-21 13:00 UTC, merged

2021-10-21 13:01 UTC, EricPonvelle commented
/cherry-pick enterprise-4.9