some jenkins image plugin curation
openshift/openshift-docs pull request #3777
Opened 2017-02-17 20:09 UTC by gabemontero

@bparees ptal

2017-02-17 20:57 UTC, bparees requested changes

2017-02-17 20:57 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +of the OpenShift Pipeline plug-in has expanded.
i'm thinking we don't need so much justification in the docs.  "Here's the new thing, here's what it replaces, here are the advantages"

2017-02-17 20:57 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +Wit these realizations in mind, the new experimental https://github.com/openshift/jenkins-client-plugin[OpenShift Client Plugin for Jenkins]
s/Wit/With/ but i think based on my comment above this whole sentence is likely to change.

2017-02-17 21:10 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +of the OpenShift Pipeline plug-in has expanded.
rework pushed

2017-02-17 21:10 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +Wit these realizations in mind, the new experimental https://github.com/openshift/jenkins-client-plugin[OpenShift Client Plugin for Jenkins]
rework pushed

2017-02-17 21:22 UTC, bparees requested changes
one nit and lgtm.

2017-02-17 21:22 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +and OpenShift, have provided valueable insight into how to best provide {product-title} integration from Jenkins jobs.
valuable

2017-02-17 21:24 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +and OpenShift, have provided valueable insight into how to best provide {product-title} integration from Jenkins jobs.
fixed - thanks

2017-02-17 21:25 UTC, gabemontero commented
@openshift/team-documentation ptal

2017-04-18 13:27 UTC, gabemontero commented
@openshift/team-documentation bump

3.6 is on the horizon now ...any ETA on when we can merge this?

2017-04-18 13:57 UTC, ahardin-rh commented on using_images/other_images/jenkins.adoc
> +assists in the creating of CI/CD workflows in Jenkins that run against an {product-title}
s/creating/creation

2017-04-18 14:01 UTC, ahardin-rh commented on using_images/other_images/jenkins.adoc
> +and OpenShift, have provided valuable insight into how to best provide {product-title} integration from Jenkins jobs.
s/best provide {product-title} integration from Jenkins jobs/integrate {product-title} from Jenkins jobs.

2017-04-18 14:02 UTC, ahardin-rh commented on using_images/other_images/jenkins.adoc
> +As such, the new experimental https://github.com/openshift/jenkins-client-plugin[OpenShift Client Plugin for Jenkins]
We need to include link:  before all external URL paths, so:
link:https://github.com/openshift/jenkins-client-plugin[OpenShift Client Plug-in for Jenkins]

(note the - in plug-in)

2017-04-18 14:09 UTC, ahardin-rh commented on using_images/other_images/jenkins.adoc
> +and docker.io/openshift/jenkins-2-centos7:latest). The plugin is also available from the Jenkins Update Center.  Envisioned as the long term
*docker.io/openshift/jenkins-1-centos7:latest* and *docker.io/openshift/jenkins-2-centos7:latest*

2017-04-18 14:09 UTC, ahardin-rh commented on using_images/other_images/jenkins.adoc
> +and docker.io/openshift/jenkins-2-centos7:latest). The plugin is also available from the Jenkins Update Center.  Envisioned as the long term
s/plugin/plug-in

2017-04-18 14:15 UTC, ahardin-rh commented on using_images/other_images/jenkins.adoc
> +and docker.io/openshift/jenkins-2-centos7:latest). The plugin is also available from the Jenkins Update Center.  Envisioned as the long term
The OpenShift Client plug-in will eventually replace the OpenShift Pipeline plug-in as the tool for OpenShift integration from Jenkins jobs. The OpenShift Client Plug-in provides:

2017-04-18 14:16 UTC, ahardin-rh commented on using_images/other_images/jenkins.adoc
> +- A Fluent sytled syntax for use in Jenkins Pipelines
Fluent-styled

2017-04-18 14:18 UTC, ahardin-rh commented on using_images/other_images/jenkins.adoc
> +- Integration with Jenkins Credentials and Clusters
Jenkins credentials and clusters

2017-04-18 14:21 UTC, ahardin-rh commented on using_images/other_images/jenkins.adoc
> +between Jenkins and {product-title}, the https://github.com/openshift/jenkins-sync-plugin[OpenShift Sync plug-in] monitors the
link:https://github.com/openshift/jenkins-sync-plugin[OpenShift Sync plug-in]

2017-04-18 14:21 UTC, ahardin-rh commented on using_images/other_images/jenkins.adoc
> +and OpenShift, have provided valuable insight into how to best provide {product-title} integration from Jenkins jobs.
looks like a strange line break here

2017-04-18 14:23 UTC, ahardin-rh commented on using_images/other_images/jenkins.adoc
> +API server of {product-title} for updates `*BuildConfigs*` and `*Builds*` that employ the Pipeline strategy and either creates
Looks like a strange line break here.

    `BuildConfigs  and `Builds` 

(several instances)

2017-04-18 14:24 UTC, ahardin-rh commented
@gabemontero Sorry for the delay. I made some comments. It looks like you also have to rebase before we can get this moving forward. Thanks!

2017-04-18 15:17 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +assists in the creating of CI/CD workflows in Jenkins that run against an {product-title}
part of next push

2017-04-18 15:19 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +As such, the new experimental https://github.com/openshift/jenkins-client-plugin[OpenShift Client Plugin for Jenkins]
part of next push

2017-04-18 15:21 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +and docker.io/openshift/jenkins-2-centos7:latest). The plugin is also available from the Jenkins Update Center.  Envisioned as the long term
part of next push

2017-04-18 15:21 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +and docker.io/openshift/jenkins-2-centos7:latest). The plugin is also available from the Jenkins Update Center.  Envisioned as the long term
part of next push

2017-04-18 15:22 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +and docker.io/openshift/jenkins-2-centos7:latest). The plugin is also available from the Jenkins Update Center.  Envisioned as the long term
part of next push

2017-04-18 15:22 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +- A Fluent sytled syntax for use in Jenkins Pipelines
part of next push

2017-04-18 15:23 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +- Integration with Jenkins Credentials and Clusters
part of next push

2017-04-18 15:23 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +between Jenkins and {product-title}, the https://github.com/openshift/jenkins-sync-plugin[OpenShift Sync plug-in] monitors the
part of next push

2017-04-18 15:24 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +API server of {product-title} for updates `*BuildConfigs*` and `*Builds*` that employ the Pipeline strategy and either creates
part of next push

2017-04-18 15:25 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +and OpenShift, have provided valuable insight into how to best provide {product-title} integration from Jenkins jobs.
hmm ... not seeing with my editor ... I'll switch to a couple of others, see if it emerges

2017-04-18 15:28 UTC, gabemontero commented
thanks @ahardin-rh !  ... updates and rebase pushed

2017-04-18 20:55 UTC, ahardin-rh commented
@gabemontero Thanks!

2017-04-18 20:55 UTC, merged

2017-04-18 21:01 UTC, ahardin-rh commented
[rev_history]
|xref:../using_images/other_images/jenkins.adoc#using-images-other-images-jenkins[Other Images -> Jenkins]
|New sections about xref:../using_images/other_images/jenkins.adoc#client-plugin-in[{product-title} Client Plug-in] and xref:../using_images/other_images/jenkins.adoc#sync-plug-in[{product-title} Sync Plug-in].
%