Remove s2i extended build documentation
openshift/openshift-docs pull request #3785
Opened 2017-02-20 22:19 UTC by csrwng

Removes extended build documentation from the docs because we are deprecating the feature and adds documentation on how this can be achieved using image source and chaining builds.

2017-02-20 22:20 UTC, csrwng commented
@bparees ptal 
I wasn't sure where to best put this doc, so I put it in the advanced build operations section. Let me know if you think it can go in a better spot.

2017-02-21 02:43 UTC, bparees requested changes
advanced operations seems like as a good a place as any.

2017-02-21 02:43 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> +For compiled languages (Go, C, C++, Java, etc.) the dependencies necessary for compilation might increase the size of the
s/the dependencies necessary for compilation/including the dependencies necessary for compilation in the application image/

2017-02-21 02:43 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> +xref:../../architecture/core_concepts/builds_and_image_streams.adoc#docker-build[Docker]
any 2 build types can be chained together, it doesn't have to be s2i -> docker.

2017-02-21 02:43 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> +The first build, which takes source and produces a binary artifact, is a a regular Source-to-Image
s/a a/a/

2017-02-21 02:43 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> +build. In the following example, a JEE source repository is to build a WAR file that is output to
"a JEE source repository is used to build an image containing a WAR file.  The image is output to(pushed to?) the `artifact-image` ImageStream."

2017-02-21 02:43 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> +      uri: https://github.com/bparees/openshift-jee-sample.git
i think it's time to put a copy of this repo in the openshift org, i don't need my name in the official product docs :)

2017-02-21 02:43 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> +      uri: https://github.com/bparees/openshift-jee-sample.git
i've moved it into openshift.

2017-02-21 02:43 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> +The second build uses Image Source and, in this case, an inline Dockerfile to place the binary artifact resulting
link to the imagesource doc

2017-02-21 20:25 UTC, csrwng commented on dev_guide/builds/advanced_build_operations.adoc
> +xref:../../architecture/core_concepts/builds_and_image_streams.adoc#docker-build[Docker]
Yes they can, but this is about a specific solution to the problem of capturing binary output from one build and including it in a runtime image. Maybe we should have a different title?

2017-02-21 20:43 UTC, csrwng commented
comments addressed

2017-02-21 20:46 UTC, bparees requested changes
needs a little more detail around the fact that the runtime image doesn't have/need any compilation tools in it, and pointing out that anytime the first build produces a new image, the second build will automatically be triggered due to the imagechangetrigger (but this is optional), making it effectively act as a single build flow.

2017-02-22 19:55 UTC, csrwng commented
@bparees added a paragraph explaining what you said :)

2017-02-22 19:58 UTC, bparees requested changes

2017-02-22 19:58 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> +build to compile an artifact that is then placed in a separate runtime image.
"Note: although this example chains an s2i build and a docker build, the first build can use any strategy that will produce an image containing the desired artifacts, and the second build can use any strategy that can consume input content from an image."

(wordsmith as desired).

2017-02-22 20:03 UTC, csrwng commented on dev_guide/builds/advanced_build_operations.adoc
> +build to compile an artifact that is then placed in a separate runtime image.
done

2017-02-22 20:45 UTC, bparees approved these changes

2017-02-22 20:45 UTC, bparees commented
lgtm @openshift/team-documentation ptal

2017-02-23 20:36 UTC, adellape commented
@csrwng Picking this up via https://github.com/openshift/openshift-docs/pull/3829.

2017-02-23 20:36 UTC, closed without merging