BZ2002582: Rewording supported cluster section for updated OCP version support
openshift/openshift-docs pull request #38206
Opened 2021-10-29 15:37 UTC by mgarrell777

This PR addresses (https://bugzilla.redhat.com/show_bug.cgi?id=2002582) and its associated JIRA story (https://issues.redhat.com/browse/CNV-14113).

The bug is about modifying the OpenShift Virtualization Supported Cluster Version section to indicate that the latest OCP version is needed.

CP: 4.7-4.10

Preview: https://deploy-preview-38206--osdocs.netlify.app/openshift-enterprise/latest/virt/about-virt#virt-supported-cluster-version_about-virt

NOTE: The preview build is based on main. So the version number will show as the most recent, rather than the older version specified in the bug. However, the version number that will show in the final build will be the correct, cherrypicked branch.

2021-10-29 17:46 UTC, dominikholler requested changes

2021-11-03 16:08 UTC, dominikholler approved these changes
Thanks, looks good.

2021-11-08 20:31 UTC, dbasunag commented
lgtm

2021-11-08 21:46 UTC, sjhala-ccs reviewed
Just one nit and a suggestion for you to consider, thanks Matthew!

2021-11-08 21:46 UTC, sjhala-ccs commented on modules/virt-supported-cluster-version.adoc
> +{VirtProductName} {VirtVersion} is supported for use on {product-title} {product-version} clusters. To use the latest z-stream release of {VirtProductName}, you must have updated your cluster to the
You don't need the {product-version} variable at the end of the second sentence. 

I would rewrite the second sentence as: "To use the latest z-stream release of {VirtProductName}, you must first upgrade to the latest version of {product-title}."

2021-11-09 15:36 UTC, merged

2021-11-09 15:37 UTC, sjhala-ccs commented
/cherrypick enterprise-4.7

2021-11-09 15:37 UTC, sjhala-ccs commented
/cherrypick enterprise-4.9

2021-11-09 15:37 UTC, sjhala-ccs commented
/cherrypick enterprise-4.10