BZ2010913: Updated note about bare metal cloud providers
openshift/openshift-docs pull request #38260
Opened 2021-11-01 15:23 UTC by sjhala-ccs

https://bugzilla.redhat.com/show_bug.cgi?id=2010913

Reopened the bug to accomodate last minute change request by the CNV leads. 

For 4.9, support for AWS bare metal nodes is Technology Preview. Updated note to reflect this.

Preview:

2021-11-01 15:28 UTC, sjhala-ccs commented
@fabiand @peterclauterbach Can you please review?

2021-11-01 18:48 UTC, peterclauterbach requested changes

2021-11-01 18:48 UTC, peterclauterbach commented on virt/install/preparing-cluster-for-virt.adoc
> +* You can install {VirtProductName} on AWS bare metal instances (Technology Preview). Infrastructure solutions offered by other bare metal cloud providers are not supported.
revise:
Bare metal instances offered by other cloud providers are not supported.

2021-11-01 18:48 UTC, peterclauterbach commented on virt/install/preparing-cluster-for-virt.adoc
> +* You can install {VirtProductName} on AWS bare metal instances (Technology Preview). Infrastructure solutions offered by other bare metal cloud providers are not supported.
Please link this to the appropriate spot in OCP 4.9 release notes
> You can install {VirtProductName} on AWS bare metal instances (Technology Preview).

2021-11-01 21:15 UTC, peterclauterbach approved these changes
LGTM

2021-11-02 13:36 UTC, ousleyp commented
LGTM!

2021-11-02 14:01 UTC, merged

2021-11-02 14:05 UTC, sjhala-ccs commented
/cherrypick enterprise-4.9

2021-11-02 14:05 UTC, sjhala-ccs commented
/cherrypick enterprise-4.10