RHDEVDOCS-3365 4.7 - Add cluster logging supported versions table.
openshift/openshift-docs pull request #38824
Opened 2021-11-16 22:49 UTC by libander

- Aligned team: Dev Tools
- For branches: enterprise-4.7
- https://issues.redhat.com/browse/RHDEVDOCS-3365
- Direct link to doc preview: 
- SME review: @alanconway 
- QE review: @anpingli 
- Peer review:

2021-11-18 14:08 UTC, Srivaralakshmi requested changes
@libander I have left some suggestions, PTAL. Thanks!

2021-11-18 14:08 UTC, Srivaralakshmi commented on modules/cluster-logging-supported-versions.adoc
> +.{product-title} version support for Red Hat OpenShift Logging (RHOL)
Suggestion:

- I do not see any module file metadata here. Please refer to this section: https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#module-file-metadata and if you plan to retain the module, implement the guidelines referenced here. 

But if you decide to move the content from the cluster-logging-supported-versions.adoc module and put it under the Supported versions heading, then there is no action required as you will be deleting the include statement Line 19 and the cluster-logging-supported-versions.adoc file from the modules folder.
- Also, if you decide that Line 13 (Red Hat OpenShift Logging 5.1) and Line 33 (Red Hat OpenShift Logging 5.0) can go as modules, then ensure to implement the guidelines referenced here.

2021-11-18 14:12 UTC, Srivaralakshmi commented
> * Direct link to doc preview: https://deploy-preview-38824--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-release-notes.html#cluster-logging-release-notes-5-1-0

Please ensure to add the direct doc preview link in the PR description. I have added it to this one ^^.

2021-11-19 20:43 UTC, libander commented on logging/cluster-logging-release-notes.adoc
Thank you!

2021-11-22 08:16 UTC, Srivaralakshmi commented
> * Direct link to doc preview: [Supported Versions](https://deploy-preview-38824--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-release-notes#supported-versions)

@libander Again, that same comment: Please ensure to add the direct doc preview link in the PR description. I have added it to this one ^^.

2021-11-22 08:17 UTC, Srivaralakshmi approved these changes
@libander Thanks for addressing the comments. Approved it erroneously. Then checked the missing anchor ID and have left a suggestion, PTAL.

2021-11-22 08:23 UTC, Srivaralakshmi requested changes

2021-11-22 08:23 UTC, Srivaralakshmi commented on logging/cluster-logging-release-notes.adoc
> +== Supported Versions
@libander Needs an anchor ID for this section heading. Please refer to: https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#anchoring-titles-and-section-headings

2021-11-30 16:56 UTC, merged