Edits changes to new Enviroment Variables section in Builds -> Build Strategy
openshift/openshift-docs pull request #3894
Opened 2017-03-08 18:36 UTC by mburke5678

@gabemontero I might have gotten a bit carried away when editing. Can you review my changes to make sure I didn't change anything technical?

2017-03-08 19:09 UTC, gabemontero requested changes
It still was pretty close ... I've offered up a specific replacement in one spot, and they a specific addition where I deferred to you on how to exactly wordsmith it.

thanks

2017-03-08 19:09 UTC, gabemontero commented on dev_guide/builds/build_strategies.adoc
> +* *oc start-build -e*. If you start the build using the `oc start-build -e` command option, the values for the environment variables specified in the `BuildConfig` and with `-e` option take precedenc
I think it is important to explicitly capture this aspect of the order of precedence:  env vars specified via `-e` can override env vars of the same name listed in the build config ... don't think we capture that currently.

2017-03-08 19:09 UTC, gabemontero commented on dev_guide/builds/build_strategies.adoc
> +* *oc start-build*. If you start the build using the `oc start-build` CLI command the environment variables specified in the `BuildConfig` take precedence. Any changes you make to the default  parame
How about this:

"If you start the build uisng `oc start-build` CLI command the current values for the environment variables specified in the `BuildConfig` take precedence over whatever default value the corresponding parameter in the Jenkins job may have."

It dawned on my that citing *how* they changed the value was irrelevant and *might* muddy the waters a little.

2017-03-08 19:45 UTC, mburke5678 commented on dev_guide/builds/build_strategies.adoc
> +* *oc start-build -e*. If you start the build using the `oc start-build -e` command option, the values for the environment variables specified in the `BuildConfig` and with `-e` option take precedenc
@gabemontero How about:

If you start the build using the oc start-build -e command option, the values for the environment variables specified with the -e option take precedence. The variables not specified with in the -e option are taken from the BuildConfig.
Note:
 *  The environment varaibles specified with -e override environment variables of the same name listed in the BuildConfig.

 * If you specify an environment variable not listed in the BuildConfig, that variable will be added as a Jenkins job parameter definition.

Any changes you make from the Jenkins console to the parameters corresponding to the environment variables are ignored.

2017-03-08 20:35 UTC, gabemontero requested changes
Just one minor suggestion / question.  Pending the resolution of that one way or the other, I'm good to go.

2017-03-08 20:35 UTC, gabemontero commented on dev_guide/builds/build_strategies.adoc
> +* The environment varaibles specified with `-e` override environment variables of the same name listed in the `BuildConfig`.
Should this sentence be moved from here and combined with the first sentence in line 589.  specifically:

"...specified with the `-e` option take precedence, overriding environment variables of the same name listed in the `BuildConfig`."

2017-03-08 22:15 UTC, mburke5678 commented on dev_guide/builds/build_strategies.adoc
> +* The environment varaibles specified with `-e` override environment variables of the same name listed in the `BuildConfig`.
Yeah. I can move that sentence. I wanted to highlight, so I put it in a Note. But, the two notes aren't as related.

"If you start the build using the `oc start-build -e` command option, the values for the environment variables specified with the `-e` option take precedence and override any environment variables of the same name listed in the `BuildConfig`. The variables not specified with in the `-e` option are taken from the `BuildConfig`.

2017-03-09 15:27 UTC, gabemontero requested changes
Apologies if I'm nit picking (or if I missed this previously) but one sentence I believe is still a bit off.

Let me know what you think.

Otherwise I'm good to go.

2017-03-09 15:27 UTC, gabemontero commented on dev_guide/builds/build_strategies.adoc
> +* *oc start-build -e*. If you start the build using the `oc start-build -e` command option, the values for the environment variables specified with the `-e` option take precedence and override any en
The last sentence seems a little off.   "... not specified with in the `--e` options ..."

How about:

"Any variables specified in the `BuildConfig` that are not referenced with the `--e` options are still taken."

2017-03-09 18:25 UTC, mburke5678 commented on dev_guide/builds/build_strategies.adoc
> +* *oc start-build -e*. If you start the build using the `oc start-build -e` command option, the values for the environment variables specified with the `-e` option take precedence and override any en
Sounds fine to me. 
http://file.rdu.redhat.com/~mburke/3855/build_strategies.html#jenkins-pipeline-strategy-environment

2017-03-09 18:26 UTC, mburke5678 commented
@bfallonf can you take a look at my changes for RH style and any other editorial issues?

2017-03-09 18:32 UTC, mburke5678 commented
This is a follow-up PR related to https://github.com/openshift/openshift-docs/pull/3855/files

2017-03-09 18:33 UTC, gabemontero approved these changes
http://file.rdu.redhat.com/%7Emburke/3855/build_strategies.html#jenkins-pipeline-strategy-environment looks good

Thanks !

2017-03-09 23:49 UTC, bfallonf commented on dev_guide/builds/build_strategies.adoc
> +* *oc start-build*. If you start the build using the `oc start-build` CLI command, the current values for the environment variables specified in the BuildConfig take precedence over whatever default
For the above, can I suggest:

``oc start-build`: the current values for the environment variables specified in the BuildConfig take precedence over whatever default value the corresponding parameter in the Jenkins job has.`

2017-03-09 23:50 UTC, bfallonf commented on dev_guide/builds/build_strategies.adoc
> +* *oc start-build*. If you start the build using the `oc start-build` CLI command, the current values for the environment variables specified in the BuildConfig take precedence over whatever default
Note the markup around oc start-build

2017-03-09 23:51 UTC, bfallonf commented on dev_guide/builds/build_strategies.adoc
> +* *oc start-build -e*. If you start the build using the xref:../../cli_reference/basic_cli_operations.html#start-build[oc start-build -e] command option, the values for the environment variables spec
Then similar to the comment above:

`oc start-build -e`: the values for the environment variables specified with the `-e` option take precedence and override any environment variables of the same name listed in the `BuildConfig`. Any variables specified in the BuildConfig that are not referenced with the `-e` options are still taken.

2017-03-09 23:51 UTC, bfallonf commented on dev_guide/builds/build_strategies.adoc
> +* *oc start-build*. If you start the build using the `oc start-build` CLI command, the current values for the environment variables specified in the BuildConfig take precedence over whatever default
Also, unless it's in backticks, BuildConfig should be spelled out "build configuration". But if you want to add the backticks to the above, that'll work as well.

2017-03-09 23:53 UTC, bfallonf commented on dev_guide/builds/build_strategies.adoc
> +* *Jenkins console*. If you start the Jenkins job usng the Jenkins console, you set the environment variable though the Jenkins console as part of starting the build job.
Then similar:

*Jenkins console*: set the environment variable though the Jenkins console as part of starting the build job.

2017-03-09 23:54 UTC, bfallonf commented on dev_guide/builds/build_strategies.adoc
> +--
For the above, an actual Note box would be best:

[NOTE]
====
If you specify an environment variable not listed in the `BuildConfig`, that variable will be added as a Jenkins job parameter definition. 
====

2017-03-09 23:55 UTC, bfallonf commented
@mburke5678 I made some comments. A few to fox some repetitiveness, and a couple on style-ey things.

Overall, good job :star:

2017-03-10 00:38 UTC, mburke5678 commented on dev_guide/builds/build_strategies.adoc
> +* *oc start-build*. If you start the build using the `oc start-build` CLI command, the current values for the environment variables specified in the BuildConfig take precedence over whatever default
>>Note the markup around oc start-build (hard to see in Github)
What should the markup around oc start-build be?

2017-03-10 01:39 UTC, bfallonf commented on dev_guide/builds/build_strategies.adoc
> +* *oc start-build*. If you start the build using the `oc start-build` CLI command, the current values for the environment variables specified in the BuildConfig take precedence over whatever default
As it's a command, backticks.

(If I'm ever confused, I click on the "edit" button in a comment, and you can see the markup without Github rendering it :) )

2017-03-10 18:36 UTC, gabemontero commented
I-Still-GTM  after the latest edits :-)

2017-03-15 04:09 UTC, vikram-redhat commented
@mburke5678 - needs labels and milestones adding.

2017-05-12 00:16 UTC, mburke5678 commented
This is a follow up to https://github.com/openshift/openshift-docs/pull/3855.

2017-06-16 19:13 UTC, ahardin-rh commented
@mburke5678 Are you still working on this, or can it be merged? Looks like it just needs to be squashed into one commit, then we can remove the to_followup label from the original PR when this merges.

2017-06-16 19:52 UTC, merged