added a ref link
openshift/openshift-docs pull request #39687
Opened 2021-12-09 13:48 UTC by Amrita42

- Applies to 4.6+ versions
- [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1999387)
- [Preview](url)

2021-12-09 17:55 UTC, mjpytlak requested changes

2021-12-09 17:55 UTC, mjpytlak commented on backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc
> +.Additional resources
Please add a unique anchor ID for `Additional resources` (see [Documentation guidelines](https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#anchoring-prerequisites-additional-resources-and-next-steps-titles-in-assemblies))

2021-12-09 17:55 UTC, mjpytlak commented on backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc
> +* See xref:../../../networking/accessing-hosts.adoc#accessing-hosts[Accessing the hosts] for how to create bastion host to access {product-title} instances and access the control plane nodes with sec
```suggestion
* See xref:../../../networking/accessing-hosts.adoc#accessing-hosts[Accessing the hosts] for how to create a bastion host to access {product-title} instances and the control plane nodes with secure shell (SSH).
```

2021-12-10 09:07 UTC, Amrita42 commented on backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc
> +* See xref:../../../networking/accessing-hosts.adoc#accessing-hosts[Accessing the hosts] for how to create bastion host to access {product-title} instances and access the control plane nodes with sec
Good catch.

2021-12-10 10:13 UTC, mjpytlak commented
Peer review LGTM.

2021-12-10 13:29 UTC, gangwgr commented
lgtm

2021-12-15 13:24 UTC, mjpytlak commented
@Amrita42 Ready for merge?

2021-12-15 13:30 UTC, Amrita42 commented
yes @mjpytlak

2021-12-15 13:31 UTC, mjpytlak commented
@jeana-redhat Please merge when you have a moment.

2021-12-15 13:46 UTC, merged

2021-12-15 13:46 UTC, jeana-redhat commented
/cherrypick enterprise-4.10

2021-12-15 13:46 UTC, jeana-redhat commented
/cherrypick enterprise-4.9

2021-12-15 13:46 UTC, jeana-redhat commented
/cherrypick enterprise-4.8

2021-12-15 13:46 UTC, jeana-redhat commented
/cherrypick enterprise-4.7

2021-12-15 13:47 UTC, jeana-redhat commented
/cherrypick enterprise-4.6