Adds a small known issue to the 4.9 RNs
openshift/openshift-docs pull request #39722
Opened 2021-12-09 22:12 UTC by stevsmit

No BZ. Request from Lalatendu.

Preview: https://deploy-preview-39722--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes#ocp-4-9-9

For 4.9.

Can be merged upon approval.

2021-12-09 22:30 UTC, LalatenduMohanty requested changes

2021-12-09 22:31 UTC, LalatenduMohanty commented
> No BZ. Request from Lalatendu.

https://bugzilla.redhat.com/show_bug.cgi?id=2022570 this is the bug which got fixed in 4.9.9

2021-12-09 22:47 UTC, wking approved these changes

2021-12-09 22:49 UTC, LalatenduMohanty approved these changes
/lgtm

2021-12-10 14:46 UTC, jeana-redhat reviewed
Just one nit, LGTM

2021-12-10 14:46 UTC, jeana-redhat commented on release_notes/ocp-4-9-release-notes.adoc
> +* Previously, the Cluster Version Operator (CVO) ignored the `spec.overrides[].group` when deciding whether to override a manifest. Consequently, overridden entries might match multiple resources, wh
s/admin/administrator (probably specifically "cluster administrator" but you might want Trevor or Lala to confirm that) throughout.

2021-12-10 15:01 UTC, merged