CNV13721: Adding CNV Network operator alerts section
openshift/openshift-docs pull request #40008
Opened 2021-12-17 16:19 UTC by mgarrellRH

This PR addresses JIRA story CNV-13721 (https://issues.redhat.com/browse/CNV-13721).

The story asks for adding downstream documentation related to alerts for the CNV Network operator

CP: 4.10

Preview:

2021-12-19 14:27 UTC, sradco commented
In d/s documentation I think we can replace "kubectl" command with "oc" command and for the namespace use "openshift-cnv".
For example : 
"kubectl -n $NAMESPACE describe pods -l name=cluster-network-addons-operator" =>
"oc -n openshift-cnv describe pods -l name=cluster-network-addons-operator"

and in this case the command:
export NAMESPACE="$(kubectl get deployment -A | grep cluster-network-addons-operator | awk '{print $1}')"
Can be removed.

@erkanerol am I correct?

2021-12-20 06:34 UTC, erkanerol commented
@sradco  You are correct. Will we duplicate all alert documents for D/S here? If so, why did we put https://kubevirt.io/monitoring/runbooks/ into alert definitons and why did we wrote the runbooks as platform-agnostic?

2021-12-20 06:44 UTC, sradco commented
As far as I understand, only critical alerts documentation was targeted for this version.
Its also not in the runbook_url so our customers will not be directed to it at this point. This may change , since I added a story to make all alerts have the url to the runbook with a prefix that we can set based on u/s and d/s.

2022-01-17 09:04 UTC, sradco commented
> In d/s documentation I think we can replace "kubectl" command with "oc" command and for the namespace use "openshift-cnv". For example : "kubectl -n $NAMESPACE describe pods -l name=cluster-network-addons-operator" => "oc -n openshift-cnv describe pods -l name=cluster-network-addons-operator"
> 
> and in this case the command: export NAMESPACE="$(kubectl get deployment -A | grep cluster-network-addons-operator | awk '{print $1}')" Can be removed.
> 
> @erkanerol am I correct?

Hi @mgarrellRH , Did you see my comment above?

2022-01-17 09:41 UTC, phoracek requested changes
Just a minor note, the rest looks good

2022-01-17 09:41 UTC, phoracek commented on modules/virt-cnv-network-alerts-networkaddonsconfignotready.adoc
> +For example, if the message is `DaemonSet "cluster-network-addons/macvtap-cni" update is being processed...`, the namespace is `cluster-network-addons` and DaemonSet name is `macvtap-cni`.
macvtap-cni is not deployed on D/S. Could we use cluster-network-addons/kube-cni-linux-bridge-plugin instead?

2022-01-17 15:25 UTC, closed without merging