Documented new GitLab and Bitbucket webhooks
openshift/openshift-docs pull request #4043
Opened 2017-03-28 21:03 UTC by oatmealraisin

@ahardin-rh @gabemontero ptal? Does this content warrant a different place to display the info?

2017-03-29 14:22 UTC, gabemontero requested changes
On correction and then a couple of minor suggestions.

2017-03-29 14:22 UTC, gabemontero commented on dev_guide/builds/triggering_builds.adoc
> +http://<openshift_api_host:port>/oapi/v1/namespaces/<namespace>/buildconfigs/<name>/webhooks/<secret>/bitbucket
says `bitbucket` at the end ... should say `gitlab`

2017-03-29 14:22 UTC, gabemontero commented on dev_guide/builds/triggering_builds.adoc
> +The payload URL is returned as the GitLab Webhook URL by the `describe` command
Perhaps clarify that `describe` is a command off of our CLI ... i.e. the `oc` executable.

2017-03-29 14:22 UTC, gabemontero commented on dev_guide/builds/triggering_builds.adoc
> +The payload URL is returned as the Bitbucket Webhook URL by the `describe` command
Same suggestion to clarify that `describe` is an option on the CLI, `oc` executable, etc.

2017-03-29 14:22 UTC, gabemontero commented on dev_guide/builds/triggering_builds.adoc
> +As with other webhooks, you must specify a secret, which will be part of
s/As with other webhooks/As with the other webhooks/

2017-03-29 19:47 UTC, oatmealraisin commented
@gabemontero I've implemented your suggestions

2017-03-29 19:49 UTC, gabemontero approved these changes
IGTM

2017-03-29 19:49 UTC, gabemontero commented
@bparees fyi / ptal

2017-03-29 20:01 UTC, bparees requested changes
one nit and lgtm

2017-03-29 20:01 UTC, bparees commented on dev_guide/builds/triggering_builds.adoc
> +https://developer.github.com/webhooks/[GitHub webhooks],
s/GitHub webhooks/GitHub/

2017-03-30 14:33 UTC, php-coder commented on dev_guide/builds/triggering_builds.adoc
> +Given a file containing a valid JSON payload, you can manually trigger the
The command below is expecting the file with particular name. I suggest to specify file name here explicitly.

2017-03-30 14:33 UTC, php-coder commented on dev_guide/builds/triggering_builds.adoc
> +$ curl -H "X-GitLab-Event: Push Hook" -H "Content-Type: application/json" -k -X POST --data-binary @gitlub_payload_file.json https://<openshift_api_host:port>/oapi/v1/namespaces/<namespace>/buildconf
s/gitlub_payload_file/gitlab_payload_file/

2017-03-30 14:35 UTC, php-coder commented on dev_guide/builds/triggering_builds.adoc
> +$ curl -H "X-Event-Key: repo:push" -H "Content-Type: application/json" -k -X POST --data-binary @gitlub_payload_file.json https://<openshift_api_host:port>/oapi/v1/namespaces/<namespace>/buildconfigs
s/gitlub_payload_file/bitbucket_payload_file/

Or even better -- we can use similar `payload_file.json` name in all examples.

2017-03-30 18:18 UTC, oatmealraisin commented
@php-coder @bparees I've implemented your changes!

2017-03-30 18:20 UTC, bparees commented
@openshift/team-documentation ptal.  @oatmealraisin please link the PR that implements this feature so the docs team knows when they can merge it.

2017-03-30 18:22 UTC, oatmealraisin commented
[Related Origin PR](https://github.com/openshift/origin/pull/13389), thanks @bparees!

2017-03-30 19:49 UTC, ahardin-rh commented on dev_guide/builds/triggering_builds.adoc
> +https://developer.github.com/webhooks/[GitHub],
we need to add link: in front of all links to external websites per our [doc guidelines](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#links-hyperlinks-and-cross-references) for example:

    link:https://developer.github.com/webhooks/[GitHub]

2017-03-30 19:49 UTC, ahardin-rh commented on dev_guide/builds/triggering_builds.adoc
> +https://docs.gitlab.com/ce/user/project/integrations/webhooks.html[GitLab webhooks]
link:https://docs.gitlab.com/ce/user/project/integrations/webhooks.html[GitLab webhooks]

2017-03-30 19:50 UTC, ahardin-rh commented on dev_guide/builds/triggering_builds.adoc
> +. Follow the https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#webhooks[GitLab setup instructions]
link:https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#webhooks[GitLab setup instructions]

2017-03-30 19:51 UTC, ahardin-rh commented on dev_guide/builds/triggering_builds.adoc
> +https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html[Bitbucket webhooks]
link:https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html[Bitbucket webhooks]

2017-03-30 19:53 UTC, ahardin-rh commented on dev_guide/builds/triggering_builds.adoc
> +----
Add a new line between the code block and the next step

2017-03-30 19:53 UTC, ahardin-rh commented on dev_guide/builds/triggering_builds.adoc
> +. Follow the https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html[Bitbucket setup instructions]
link:

2017-03-30 19:55 UTC, ahardin-rh commented
@oatmealraisin Overall, looks good! Just a few minor comments from me. I will mark this [do not merge] to prevent premature merging on the docs end. Thanks so much! :beers:

2017-03-30 19:57 UTC, ahardin-rh commented
@oatmealraisin Also, to answer your original question, placement of the information LGTM right now. If this topic continues to expand, we may choose to chunk it up later.

2017-03-31 14:41 UTC, oatmealraisin commented
@ahardin-rh I've implemented your changes!

2017-03-31 14:46 UTC, ahardin-rh commented
@oatmealraisin LGTM!

2017-04-03 21:23 UTC, oatmealraisin commented
@ahardin-rh The source PR was merged, could we merge this PR?

2017-04-03 21:38 UTC, merged

2017-04-03 22:02 UTC, ahardin-rh commented
[rev_history]
|xref:../dev_guide/builds/triggering_builds.adoc#dev-guide-triggering-builds[Builds -> Triggering Builds]
|Added new sections on xref:../dev_guide/builds/triggering_builds.adoc#gitlab-webhooks[GitLab] and  xref:../dev_guide/builds/triggering_builds.adoc#bitbucket-webhooks[Bitbucket] webhooks.
%