Updating apirequestcount admin ack with a better query and to show an…
openshift/openshift-docs pull request #40561
Opened 2022-01-13 17:48 UTC by bergerhoffer

…other user to ignore

Previews: 
* https://deploy-preview-40561--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-prepare.html#update-preparing-evaluate-apirequestcount_updating-cluster-prepare
* https://deploy-preview-40561--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-prepare.html#update-preparing-evaluate-apirequestcount-workloads_updating-cluster-prepare

2022-01-13 17:53 UTC, bergerhoffer commented
@sanchezl @wangke19 Can you please review? 

Preview: https://deploy-preview-40561--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-prepare.html#update-preparing-evaluate-apirequestcount_updating-cluster-prepare

2022-01-13 18:14 UTC, stevsmit commented
/lgtm

2022-01-13 19:00 UTC, sanchezl requested changes

2022-01-13 19:11 UTC, bergerhoffer commented on modules/update-preparing-evaluate-apirequestcount.adoc
> +* The `system:kube-controller-manager` and `system:cluster-policy-controller` users might appear in the results because they walk through all resources to count them while enforcing various policies.
Updated!

2022-01-13 19:12 UTC, sanchezl approved these changes
/lgtm

2022-02-11 19:55 UTC, bergerhoffer commented
@wangke19 Can you please QE review this?

Preview: https://deploy-preview-40561--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-prepare.html#update-preparing-evaluate-apirequestcount_updating-cluster-prepare

2022-02-22 08:37 UTC, wangke19 commented
/lgtm

2022-02-22 13:39 UTC, merged