[WIP] Add End-to-End Steps for Exposing Service IP
openshift/openshift-docs pull request #4072
Opened 2017-04-03 20:46 UTC by mburke5678

2017-05-09 06:10 UTC, smarterclayton requested changes
I would prefer this be a guide for end users as well as admins.  Nothing in the openshift CLI flows require elevated priviliges, and this is a common user level task.  Consider separating admin setup / verification from user goal

2017-05-09 06:10 UTC, smarterclayton commented on admin_guide/expose_external_ip.adoc
> +. Make sure you have xref:end-to-end-login[logged into  {product-title} as a user with the cluster admin role].
Why do they need cluster admin?  Nothing here needs that.

2017-05-09 06:10 UTC, smarterclayton commented on admin_guide/expose_external_ip.adoc
> +. Make sure you have xref:end-to-end-login[logged into  {product-title} as a user with the cluster admin role].
Doesn't require this

2017-05-09 06:10 UTC, smarterclayton commented on admin_guide/expose_external_ip.adoc
> +. Make sure you to the have xref:end-to-end-login[logged into  {product-title} as a user with the cluster admin role].
No

2017-05-09 16:49 UTC, mburke5678 commented on admin_guide/expose_external_ip.adoc
> +If you want to expose a service on all nodes in the cluster, you can use xref:../dev_guide/getting_traffic_into_cluster.adoc#using-nodeport[NodePort]. However, this method is requires additional port
Fixed

2017-05-09 16:49 UTC, mburke5678 commented on admin_guide/expose_external_ip.adoc
> +. Make sure you have xref:end-to-end-login[logged into  {product-title} as a user with the cluster admin role].
Removed

2017-05-09 16:49 UTC, mburke5678 commented on admin_guide/expose_external_ip.adoc
> +. Make sure you have xref:end-to-end-login[logged into  {product-title} as a user with the cluster admin role].
Removed

2017-05-09 16:49 UTC, mburke5678 commented on admin_guide/expose_external_ip.adoc
> +. Make sure you to the have xref:end-to-end-login[logged into  {product-title} as a user with the cluster admin role].
Removed

2017-06-22 20:18 UTC, mburke5678 commented
@zhaozhanqi 

I broke each method for exposing the IP address into separate topics:

Overview (index.adoc)
Using a Router (expose_internal_ip_router.adoc)
Using a Load Balancer (expose_internal_ip_load_balancer.adoc)
Using a Service ExternalIP (expose_internal_ip_service.adoc)
Using a NodePort (expose_internal_ip_nodeport.adoc)

The "expose_external_ip.html" topic is a single page with all of the information. 

For reference, see:
http://file.rdu.redhat.com/~mburke/mburke-BZ-1421924/mburke-BZ-1421924-2/dev_guide/expose_service/index.html

2017-07-13 01:47 UTC, mburke5678 commented
@openshift/team-documentation 
Please take a look. 
I was tasked with creating "a complete example about how to expose a non standard port using an externalIP service." It is an odd piece, as there are admin tasks (modify the master config, networking, user creation, etc.), developer tasks, and network configuration. Not sure where it should go. 
Currently, it is in the developer doc, per @smarterclayton's comment above. It has been reviewed by QA; but none of the principals who requested it have responded to repeated review requests.  
https://bugzilla.redhat.com/show_bug.cgi?id=1421924

Within the topics, there is shared information: 
Administrator Prerequisites
Defining the Public IP Range
Create a Project and Service (not in the Node Port topic)
Expose the Service
Configure IP Failover

These need to be reviewed once, not in every topic. 
And, in the topic map, you will see two topics with similar names (Getting Traffic into the Cluster). The first one is the original topic currently in the docs (from which I poached material). Not quite sure how to integrate the new material in. I will sort this out before merging; no worries. Just want to keep this thing moving!

2017-07-13 04:43 UTC, bfallonf commented
@mburke5678 Hmm the built link above doesn't work. Hard to give it a good look over in Github. As it stands, I'm not sure the dev guide is the best place for it, but because it hits both admins and devs, the admin guide isn't best either. I wonder if @aheslin has an opinion?

2017-07-13 15:09 UTC, mburke5678 commented
@openshift/team-documentation Updated link:
http://file.rdu.redhat.com/~mburke/mburke-BZ-1421924-2/mburke-BZ-1421924-2/dev_guide/expose_service/index.html

2017-07-18 14:02 UTC, bmcelvee commented on dev_guide/expose_service/expose_internal_ip_nodeport.adoc
> +. Execute the following command to xref:../dev_guide/application_lifecycle/new_app.html#dev-guide-new-app[create the service]:
This link seems to be broken.

2017-07-18 14:04 UTC, ahardin-rh commented on dev_guide/expose_service/expose_internal_ip_nodeport.adoc
> +. Execute the following command to xref:../dev_guide/application_lifecycle/new_app.html#dev-guide-new-app[create the service]:
s/.html/.adoc

2017-07-18 14:07 UTC, bmcelvee commented on dev_guide/expose_external_ip.adoc
> +You must xref:../cli_reference/basic_cli_operations.html#expose[expose the service as a route] using the `oc expose` command.
This link is also broken.

2017-07-18 14:08 UTC, mburke5678 commented on dev_guide/expose_external_ip.adoc
> +You must xref:../cli_reference/basic_cli_operations.html#expose[expose the service as a route] using the `oc expose` command.
s/.html/.adoc

2017-07-18 14:10 UTC, bmcelvee commented on dev_guide/expose_external_ip.adoc
> +xref:../install_config/install/prerequisites.adoc#prereq-dns[wildcard DNS]
This link appears to be broken, but it could just be something wonky with the ifdef in preview.

2017-07-18 17:03 UTC, bmcelvee commented on dev_guide/expose_service/expose_internal_ip_service.adoc
> +* xref:manually-assign-ips-network[The network administrator configures networking to the service]
Full stop (period) for consistency.

2017-07-18 17:04 UTC, bmcelvee commented
Just a few minor nits, otherwise LGTM! 🎆

2017-10-09 07:36 UTC, vikram-redhat commented
@mburke5678 - I finally got around to looking at this.

Overall it is great and ready. The only issue that remains is the location. Dev Guide or Admin Guide. 

I think you have done well to separate out the Administrator tasks at the top, so the dev who is following the guide knows that that is a prerequisite for the admin to have done, so they can reach out to the admin and request those tasks are done beforehand. 

Unless anyone else has any objections @openshift/team-documentation, I would put this into the dev guide. 

cc: @aheslin .

2017-10-09 17:09 UTC, aheslin commented
I think it's ok to include in the Dev Guide.

2017-10-23 21:43 UTC, mburke5678 commented
This original PR for this task is outdated and had too many merge issues to use.
Created a new branch. Used git checkout to get the new files into a new branch and updated links. Closing this PR and opening new https://github.com/openshift/openshift-docs/pull/5880.

2017-10-23 21:43 UTC, closed without merging

2017-10-23 23:59 UTC, vikram-redhat commented
Thanks Michael - also removing the labels and milestones.

2017-10-31 15:47 UTC, mburke5678 commented
@smarterclayton Can the changes I made (ultimately via  https://github.com/openshift/openshift-docs/pull/6053) be applied to 3.4, 3.5, and/ or 3.6 and forward?

2017-10-31 19:23 UTC, smarterclayton commented
Yes. New clusters can also get access to node ports via `openshift_node_port_range` in ansible, but that probably belongs to the admin section.

2017-11-01 15:48 UTC, mburke5678 commented
@smarterclayton Where can we get info on `openshift_node_port_range`? Doesn't seem that we cover that in the docs. Is there a Trello?