initial CNS volume create/delete recommendations
openshift/openshift-docs pull request #4103
Opened 2017-04-07 17:41 UTC by ekuric

- this document should be added as part of admin_guide
- it gives overview of results related to create/delete of CNS volumes up to 100 CNS volumes
- currently 100 cns volumes per TSP is supported number, it was possible to create more CNS volumes than 100, but not *supported* at time 

Signed-off-by: Elvir Kuric <elvirkuric@gmail.com>

2017-04-07 17:46 UTC, ekuric commented
@humblec @jeremyeder ptal , @ahardin-rh you too, please check it and move document where necessary

2017-04-07 18:14 UTC, ekuric commented
this document contains links to graphs, please get graphs from these location 
https://raw.githubusercontent.com/ekuric/openshift/master/cns/images/create_10_50_100.png
https://raw.githubusercontent.com/ekuric/openshift/master/cns/images/delete_10_50_100.png
to avoid dependency on my local branch

2017-04-10 11:43 UTC, jeremyeder requested changes

2017-04-10 11:43 UTC, jeremyeder commented on admin_guide/cns_recommendations.adoc
> +for instructions how to configure CNS as part of OCP cluster.
probably want to link to the gluster 3.2 and ocp 3.5 docs?

2017-04-10 11:43 UTC, jeremyeder commented on admin_guide/cns_recommendations.adoc
> +
drop url and say "hardware configuration for CNS per documentation" ?

2017-04-10 11:43 UTC, jeremyeder commented on admin_guide/cns_recommendations.adoc
> +image::https://raw.githubusercontent.com/ekuric/openshift/master/cns/images/create_10_50_100.png[Create CNS volumes]
have we been including performance graphs anywhere else in our docs? i dont think so -- i wonder if we can just phrase this as "creation time scales linearly up through 100 volumes.  in our tests, each volume takes approximately 6 seconds to be created, allocated and bound to a pod."

2017-04-10 11:43 UTC, jeremyeder commented on admin_guide/cns_recommendations.adoc
> +trusted storage pool, but currently it is not supported***
Probably best to drop this sentence until CNS actually supports more volumes.

2017-04-10 11:43 UTC, jeremyeder commented on admin_guide/cns_recommendations.adoc
> +image::https://raw.githubusercontent.com/ekuric/openshift/master/cns/images/delete_10_50_100.png[Delete CNS volumes]
same comment as above, can this be phrased as "deletion time of CNS volumes scales linearly up to 100 volumes"...

2017-04-12 00:03 UTC, ahardin-rh commented
Continuing work in https://github.com/openshift/openshift-docs/pull/4131

@ekuric @jeremyeder Many thanks for this information!

2017-04-12 00:03 UTC, closed without merging