SRVCOM-1532: Add the Troubleshooting Serverless section
openshift/openshift-docs pull request #41061
Opened 2022-01-26 17:51 UTC by rh-max

For versions: ?

Preview:

2022-02-02 22:24 UTC, abrennan89 commented on modules/serverless-rn-1-19-0.adoc
> +See the workaround in the xref:../serverless/serverless-troubleshooting.adoc#failure-to-build-a-function-by-using-podman[Troubleshooting section].
can't have an xref in a module afaik

2022-02-02 22:25 UTC, abrennan89 commented on modules/serverless-deprecated-removed-features.adoc
> += Deprecated and removed features
wasn't this added in a different PR for release notse?

2022-02-02 22:25 UTC, abrennan89 commented on modules/serverless-rn-1-20-0.adoc
> += Release Notes for Red Hat {ServerlessProductName} 1.20.0
Confused about why this is in two different PRs - is this troubleshooting guide being pushed out for 1.21.0?

2022-02-02 22:26 UTC, abrennan89 commented on modules/serverless-troubleshooting-functions.adoc
> +== Failure to build a function by using podman
needs intro paragraph and ID I think for the h2

2022-02-02 22:26 UTC, abrennan89 commented on _topic_maps/_topic_map.yml
> +  File: serverless-troubleshooting
I'd maybe put this inside the Support or Reference section, wdyt?

2022-02-02 22:27 UTC, abrennan89 requested changes
It looks like the relnotes content is still duplicated here, will this be ready for the release tomorrow?

2022-02-03 11:59 UTC, rh-max commented
> It looks like the relnotes content is still duplicated here, will this be ready for the release tomorrow?

As discussed in the channel, Troubleshooting doesn't go out in 1.20, so I'll close this. This duplicated the 1.20 release notes PR for the goal of getting some material for illustrative purposes for Troubleshooting; it's outdated now.

2022-02-03 11:59 UTC, closed without merging