admin_guide/manage_scc: couple of improvements
openshift/openshift-docs pull request #4213
Opened 2017-04-21 16:57 UTC by php-coder

PTAL @pweil-

2017-05-11 13:21 UTC, php-coder commented
Ping @pweil-

2017-05-19 15:29 UTC, php-coder commented
@pweil- @mfojtik PTAL.

2017-05-22 21:42 UTC, ahardin-rh commented on admin_guide/manage_scc.adoc
> +administrator group access to create more **privileged pods**. To do so, you can:
To provide emphasis use this format instead:

    _privileged pods_

2017-05-22 21:45 UTC, ahardin-rh commented on admin_guide/manage_scc.adoc
> +Granting access to a user works only for the pods. For other resources
You can only grant access to a user for the pods. For other resources like deployments and StatefulSets, give access to a service account under which the related controller is operated upon.

2017-05-22 21:47 UTC, ahardin-rh commented on admin_guide/manage_scc.adoc
> +The next step is to ensure that resource is being created in behalf of the
Then, ensure that the resource is being created on behalf of the service account. To do so, set the . . .

2017-05-22 21:49 UTC, ahardin-rh commented
@php-coder Just a few minor comments from me. This will also need to be squashed into a single commit before we can merge. Perhaps @pweil- has other comments, however. Thanks!

2017-05-23 22:37 UTC, pweil- requested changes

2017-05-23 22:37 UTC, pweil- commented on admin_guide/manage_scc.adoc
> +If you delete the default SCC, it will be regenerated upon restart.
s/the/a

2017-05-23 22:37 UTC, pweil- commented on admin_guide/manage_scc.adoc
> +Granting access to a user works only for the pods. For other resources
Granting access to a user only works when the user directly creates a pod.  For pods created on behalf of a user, in most cases by the system itself, access ....

Examples of resources that create pods on behalf of a user are ...

2017-05-24 10:54 UTC, php-coder commented
@ahardin-rh @pweil- Thank you for the comments! I've updated the PR and incorporated all these comments. PTAL.

2017-05-24 11:14 UTC, pweil- approved these changes
minor nit and LGTM.  thanks!

2017-05-24 11:14 UTC, pweil- commented on admin_guide/manage_scc.adoc
> +account. To do so, set the `spec.serviceAccountName` field to a service account
Leaving the service account name blank will result in the `default` service account being used.

2017-05-24 11:27 UTC, php-coder commented on admin_guide/manage_scc.adoc
> +account. To do so, set the `spec.serviceAccountName` field to a service account
Good addition! Updated.

2017-05-24 13:22 UTC, ahardin-rh commented
Thanks so much!

2017-05-24 13:22 UTC, merged

2017-05-24 13:33 UTC, ahardin-rh commented
[rev_history]
|xref:../admin_guide/manage_scc.adoc#admin-guide-manage-scc[Managing Security Context Constraints]
|Added a warning about pod creation on behalf of a user within the xref:../admin_guide/manage_scc.adoc#grant-access-to-the-privileged-scc[Grant Access to the Privileged SCC] section.
%