BZ-2055147: correcting output of oc get bmh
openshift/openshift-docs pull request #42550
Opened 2022-03-01 11:49 UTC by kquinn1204

Addreses BZ https://bugzilla.redhat.com/show_bug.cgi?id=2055147

2022-03-01 15:21 UTC, kquinn1204 commented
@elfosardo please review the PR that addresses https://bugzilla.redhat.com/show_bug.cgi?id=2055147

2022-03-01 15:55 UTC, elfosardo requested changes

2022-03-01 15:55 UTC, elfosardo commented on modules/ipi-install-provisioning-the-bare-metal-node.adoc
> +The `provisioning` state remains until the {product-title} cluster provisions the node. This can take 30 minutes or more. After the node is provisioned, the state will change to `provisioned`.
this should be "The `provisioning status`"

2022-03-02 08:24 UTC, elfosardo approved these changes

2022-03-02 09:53 UTC, reihl approved these changes

2022-03-02 13:42 UTC, kalexand-rh reviewed
LGTM!

2022-03-02 13:42 UTC, merged

2022-03-02 13:42 UTC, kalexand-rh commented
/cherrypick enterprise-4.9