review-dev_guide_for_online
openshift/openshift-docs pull request #4261
Opened 2017-04-26 15:43 UTC by sallyom

WIP 
@ahardin-rh I'm goint to have @Miciah (if you will please) look this over..

2017-04-26 16:00 UTC, Miciah requested changes

2017-04-26 16:00 UTC, Miciah commented on dev_guide/routes.adoc
> +  host: frontend-projectname.{product-title} {product-version} hostname
What's up with `.{product-title} {product-version} hostname`? Anyway, `host` should not be specified at all.

2017-04-26 16:00 UTC, Miciah commented on dev_guide/routes.adoc
> +ifdef::openshift-online[]
Could we used a finer-grained ifdef? It's just the command and yaml that need to be conditionalised.

2017-04-26 16:00 UTC, Miciah commented on dev_guide/routes.adoc
> +====
Might as well include yaml for an edge route for Online too.

2017-04-26 16:16 UTC, ahardin-rh commented on dev_guide/routes.adoc
> +  host: frontend-projectname.{product-title} {product-version} hostname
In code blocks, {product-title} and {product-version} will not render properly

2017-04-26 21:01 UTC, sallyom commented
@Miciah, I've followed your suggestions here, mind checking it again? Thanks.

2017-04-26 21:23 UTC, Miciah approved these changes
A couple modest suggestions, but looks fine.

2017-04-26 21:23 UTC, Miciah commented on dev_guide/routes.adoc
> +ifndef::openshift-online[]
Would it be clearer to include this with the `ifndef::openshift-online[]` block again, without the intervening `ifdef::openshift-online[]` block?

2017-04-26 21:23 UTC, Miciah commented on dev_guide/routes.adoc
> +you can use the `create route` command.
Only the last sentence of the paragraph varies between Online and non-Online, so the ifdeffing could be still a little more fine-grained, but I don't feel strongly about it.

2017-04-29 02:19 UTC, merged

2017-04-29 02:20 UTC, ahardin-rh commented
No revision history needed