Document new egress-router features [DO NOT MERGE]
openshift/openshift-docs pull request #4277
Opened 2017-04-27 14:37 UTC by danwinship

This updates the egress router documentation for
- https://github.com/openshift/origin/pull/13837 (multiple destinations)
- https://github.com/openshift/origin/pull/13586 (HTTP proxy mode)
- https://trello.com/c/mdbZRAgZ (initContainer mode)
- https://trello.com/c/DCDdY7eA (document how to use ConfigMap)

The new features haven't merged yet so the exact syntax in the examples might change and this shouldn't merge until then, but you can review for style / asciidoc issues /etc now.

2017-05-01 20:07 UTC, weliang1 requested changes
Better change "Deploying an Egress Router Pod" to "Deploying an Egress Router Redirect Pod"

2017-05-01 20:26 UTC, weliang1 reviewed
"This only works for clients talking to HTTP-based services,"
Should it works for clients talking to HTTPs-based services too?

2017-05-24 20:52 UTC, danwinship commented
Repushed without the HTTP proxy docs since that didn't make it in for this devcut. But everything else is merged and this PR is ready to go.

2017-05-31 03:30 UTC, bmeng commented on admin_guide/managing_networking.adoc
> +<1> This uses the YAML syntax for a multi-line string. In this
Should we note that only tcp and udp are supported here?

2017-05-31 13:53 UTC, danwinship commented on admin_guide/managing_networking.adoc
> +<1> This uses the YAML syntax for a multi-line string. In this
updated to clarify the syntax better

2017-06-06 05:52 UTC, vikram-redhat commented
![](https://github.trello.services/images/mini-trello-icon.png) [Document: Add an HTTP proxy mode for egress-router](https://trello.com/c/I6Is4843/490-document-add-an-http-proxy-mode-for-egress-router)

2017-06-09 14:23 UTC, danwinship commented
re-pushed with the HTTP proxy stuff added back again since that has now merged

2017-06-15 04:19 UTC, bfallonf commented
Thanks @danwinship . I'll merge this and do a followup. I'll ping you with any questions if I have them.

2017-06-15 04:19 UTC, merged

2017-06-21 11:16 UTC, knobunc reviewed
LGTM thanks Dan

2017-06-23 19:24 UTC, weliang1 reviewed
We should describe below configuration in the pod to make feature works:
`export http_proxy=http://my-egress-router-service:8080/ `, and `export https_proxy=http://my-egress-router-service:8080/ `

2017-06-26 00:41 UTC, bfallonf commented
@weliang1 Sorry, I'm not sure where you're asking to place this. Should this be part of the "Deploying an Egress Router Pod in Redirect Mode" procedure? After the pod is created and before the verification step? In this PR, I mean around line 365.

2017-06-26 14:18 UTC, danwinship commented
@bfallonf it should probably go around where it talks about configuring clients to use an http proxy by setting an environment variable.

There are actually two aspects to this: first, we don't mention anywhere that the proxy runs on port 8080. The best way to address that might be to provide an example of a service definition to go with the egress http proxy pod definition. (It would be similar to the service definition in the redirecting egress router case, but needs to specify targetPort 8080 always.)

Second, we ought to give a better hint on how to configure clients to use it. What Weibin suggests isn't correct for *all* clients, but it will work in most cases. We might want to show an example of setting those variables in the `env` section of a client pod.

2017-06-28 02:47 UTC, bfallonf commented
@weliang1 @danwinship I think I understand. Thanks for the clarification. I've made a followup to this PR, so it would be great for some feedback there. I'll tag the relevant parts.

2017-07-26 12:38 UTC, sferich888 reviewed
@aheslin @vikram-redhat while this is merged, can we get someone to looked at the comments here and work with @danwinship to fill in any missing details.

2017-07-26 12:38 UTC, sferich888 commented on admin_guide/managing_networking.adoc
> +Note that the egress router will not automatically update when the
@derekwaynecarr @bparees not sure who to ask on this but is this a bug (or do I just not understand how configmap and DC/RC's work)? Shouldn't DC/RC's be update with config maps referenced by them change?

2017-07-26 12:38 UTC, sferich888 commented on admin_guide/managing_networking.adoc
> +.Example Pod Definition for an Egress Router HTTP Proxy
Should this say 'HTTP/HTTPS'

2017-07-26 12:38 UTC, sferich888 commented on admin_guide/managing_networking.adoc
> +- If the last line is `*`, then anything that hasn't been denied will be allowed. Otherwise, anything that hasn't been allowed will be denied.
I don't see in here where we talk about how https://bugzilla.redhat.com/show_bug.cgi?id=1435803 is addressed by such a configuration. 

Is the SSL offloaded (to the endpoint) or are we terminating at the egress pod, and re-connecting? If its the latter, what CA and Server certificate is the proxy using?

2017-07-26 12:45 UTC, bparees commented on admin_guide/managing_networking.adoc
> +Note that the egress router will not automatically update when the
@pmorie should know the details of that.  The DC/RC certainly won't be, but a pod that mounts in a configmap as a volume, or that consumes a configmap as env, is, I think, supposed to get restarted if the configmap changes.  But i can't remember, that might be wishful thinking.

2017-07-26 15:52 UTC, knobunc commented on admin_guide/managing_networking.adoc
> +.Example Pod Definition for an Egress Router HTTP Proxy
We could... people usually just call them HTTP proxies, even if they handle both.  But there is no harm in making that change.

2017-07-26 15:57 UTC, knobunc commented on admin_guide/managing_networking.adoc
> +- If the last line is `*`, then anything that hasn't been denied will be allowed. Otherwise, anything that hasn't been allowed will be denied.
When you are using a forward HTTP proxy, the client has to be aware of that and talk to the proxy differently.  https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_tunneling

Basically, the client asks the proxy to open a connection over HTTP and then the client sends the HTTPS traffic through a tunneled connection.

2017-07-31 13:28 UTC, danwinship commented on admin_guide/managing_networking.adoc
> +- If the last line is `*`, then anything that hasn't been denied will be allowed. Otherwise, anything that hasn't been allowed will be denied.
(This was clarified over email, but rhbz 1435803 covered two different features, only one of which was implemented in 3.6 and documented here.)