RHDEVDOCS-3813 - added steps to install the operator using CLI
openshift/openshift-docs pull request #42879
Opened 2022-03-07 09:39 UTC by DebarghoGhosh

Aligned team: Dev Tools
OCP version for cherry-picking: enterprise-4.9, 4.10
JIRA issue: https://issues.redhat.com/browse/RHDEVDOCS-3813
Preview pages:

SME+QE review:
Peer-review:

2022-03-07 09:49 UTC, jannfis commented on modules/logging-in-to-the-argo-cd-instance-by-using-the-argo-cd-admin-account.adoc
> +You cannot create two Argo CD CRs in the same namespace.logging-in-to-the-argo-cd-instance-by-using-the-argo-cd-admin-account.adoc-in-to-the-argo-cd-instance-by-using-the-argo-cd-admin-account.adoc
That looks weird to me.

2022-03-07 09:50 UTC, jannfis reviewed
LGTM with a minor concern

2022-03-07 14:21 UTC, Srivaralakshmi requested changes
@DebarghoGhosh Good work, left a few suggestions, PTAL. Thanks!

2022-03-07 14:21 UTC, Srivaralakshmi commented on modules/installing-gitops-operator-using-cli.adoc
> +. After the installation is complete, the following pods will appear:
@DebarghoGhosh I like the verification step :)

```suggestion
. After the installation is complete, ensure that all the pods in the `openshift-gitops` namespace are running:
```

2022-03-07 14:21 UTC, Srivaralakshmi commented on modules/installing-gitops-operator-using-cli.adoc
> ++
```suggestion
+
.Example output
```

2022-03-07 14:21 UTC, Srivaralakshmi commented on modules/installing-gitops-operator-using-cli.adoc
> +$ oc get pods -n openshift-gitops
```suggestion
+
[source,terminal]
----
$ oc get pods -n openshift-gitops
----
```

2022-03-07 14:21 UTC, Srivaralakshmi commented on modules/installing-gitops-operator-using-cli.adoc
> +NAME                                                      	READY   STATUS	RESTARTS   AGE
```suggestion
+
The output, which takes a few minutes to display, verifies that the {gitops-title} Operator is now installed in the `openshift-operators` default target namespace:
+
.Example output
[source,terminal]
----
NAME                                                      	READY   STATUS	RESTARTS   AGE
```

2022-03-08 08:34 UTC, Srivaralakshmi requested changes
@DebarghoGhosh PTAl and let me know once you address the comments. Will take a final look.

2022-03-08 08:34 UTC, Srivaralakshmi commented on modules/installing-gitops-operator-using-cli.adoc
> ++
```suggestion

```

2022-03-08 08:34 UTC, Srivaralakshmi commented on modules/installing-gitops-operator-using-cli.adoc
> +. Apply the `Subscription` to the cluster:
Suggestion: The output is not coming good. Please check and rectify. This is coming as step 1 and all the steps are spilling over to the right pane.

2022-03-08 09:39 UTC, Srivaralakshmi approved these changes
@DebarghoGhosh Good work! Thanks for the changes. LGTM.

2022-03-08 09:39 UTC, Srivaralakshmi commented
/lgtm

2022-03-17 13:15 UTC, merged

2022-03-17 13:15 UTC, JStickler commented
/cherry-pick enterprise-4.9

2022-03-17 13:15 UTC, JStickler commented
/cherry-pick enterprise-4.10

2022-03-17 13:16 UTC, JStickler commented
/cherry-pick enterprise-4.11