Corrects callout numbers in procedure
openshift/openshift-docs pull request #43044
Opened 2022-03-10 08:43 UTC by RichardHoch

Bug fix
MTC 1.6+

The callouts in step 3 of "Migrating an application by using the MTC API" (section 9.2.4) are missing numerals. This PR adds them.

2022-03-10 09:54 UTC, RichardHoch commented
@stoobie -- Please review this Pr.

2022-03-13 13:14 UTC, stoobie requested changes
LGTM. Just make sure you indicate which version of OpenShift this applies to. I guess it would be 4.6-4.10, right?

2022-03-14 14:36 UTC, merged

2022-03-14 18:03 UTC, mburke5678 commented
/cherrypick enterprise-4.6

2022-03-14 18:14 UTC, mburke5678 commented
/cherrypick enterprise-4.7

2022-03-14 18:19 UTC, mburke5678 commented
/cherrypick enterprise-4.9

2022-03-14 18:20 UTC, mburke5678 commented
/cherrypick enterprise-4.10