4.10 OCP Docs Engineering Feedback PR - Not to be merged.
openshift/openshift-docs pull request #43944
Opened 2022-03-29 21:22 UTC by libander

Please review for general accuracy. 
Specific questions are commented via '//Eng-Feedback-Req:' inline for ease of reference.

2022-03-31 13:49 UTC, alanconway requested changes
Minor comments. We also need to add a tech preview section where we talk about using vector as the collector and using LokiStack to depoy loki. Here are some quick comments, need to confirm details once coding frenzy subsides:

Vector is an alternative collector to fluentd with better scaling characteristics. Using vector does not change the way the ClusterLogging and ClusterLogForwarder APIs work, it is a drop in replacement that should improve performance at scale (large numbers of containers producing logs)
Vector is enabled by setting 'collector: vector' on ClusterLogging. The current preview is not production quaity and does not have all the features offered by fluentd (need to confirm the list),it is offered for POC and experimental use only. 
LokiStack is an operator that deploys loki with a reverse proxy for security and multi-tenancy. [Note we use "LokiStack" to distinguish from plain Loki, since we deploy some extra components to complement loki] LokiStack _will_ be the future default store, but for this preview you need to configure forwarding like you would for an external Loki store (need instructions)
Peri can fill in more info here on how to view logs in Loki etc.

2022-03-31 13:49 UTC, alanconway commented on modules/cluster-logging-about-logstore.adoc
>  = About the log store
"Optionally, you can use the log forwarding features to forward logs to external log stores using Fluentd protocols, syslog protocols, or the {product-title} Log Forwarding API." ===>
"Optionally you can use the Log Forwarder API to forward logs to an external store. Several types of store are supported, including fluentd, rsyslog, kafka and others.

2022-03-31 13:49 UTC, alanconway commented on modules/cluster-logging-about.adoc
> +
Nope, see previous comment.

2022-03-31 13:49 UTC, alanconway commented on modules/cluster-logging-collector-log-forward-loki.adoc
> +
Probably this section will remain to document connecting to an external Loki. There are some differences in authentication when connecting to a local Loki.  As we talked about before, my preference would be to have a quick example of the most common way to connect to an external loki, a quick section explaining the (mostly automatic) connection to a local default loki, both linked to an independent, detailed reference section explaining _all_ of the options for a Loki output, so the user can handle their specific requirements.

2022-03-31 13:49 UTC, alanconway commented on modules/cluster-logging-collector-log-forwarding-about.adoc
> +
No change

2022-03-31 13:49 UTC, alanconway commented on modules/cluster-logging-collector-log-forwarding-supported-plugins-5-2.adoc
> +
Add loki if it wasn't there already, but it may have been.

2022-03-31 13:49 UTC, alanconway commented on modules/cluster-logging-dashboards-logging.adoc
> +//Eng-Feedback-Req: Does the 5.4 release change console dashboard visually, or is the current version in the 4.10 dashboard unaffected?
No change.

2022-03-31 17:55 UTC, libander commented
Thank you for the feedback, @alanconway. Do you have any input re where the 'tech preview' section should go structurally? I'm thinking top level under Uninstalling Logging (with a link/ blurb in Release Notes, of course) - I think nesting it would create the potential for confusion.

2022-04-04 15:50 UTC, jcantrill commented on logging/cluster-logging-upgrading.adoc
> +
AFAIK the name does not change.  Note however that logging 5.4 will  require OCP 4.9 or better.  @periklis team is reviewing how we can make it possible to deploy on earlier versions but for the moment we are restricted to 4.9. @periklis please confirm

2022-04-25 04:06 UTC, closed without merging