WINC clarify Getting Support wording
openshift/openshift-docs pull request #44112
Opened 2022-04-01 19:19 UTC by mburke5678

Per [Slack conversation](https://coreos.slack.com/archives/CM4ERHBJS/p1648832040363479?thread_ts=1648789414.418059&cid=CM4ERHBJS).

 https://docs.openshift.com/container-platform/4.9/windows_containers/windows-containers-release-notes-4-x.html#getting-support is confusing,...  I thus recommend fixing docs and pointing to https://access.redhat.com/support/policy/updates/openshift#windows `

2022-04-01 19:20 UTC, mburke5678 commented
@Anandnatraj @sreber84 @mtnbikenc PTAL

2022-04-01 19:26 UTC, mtnbikenc requested changes
Looks good except there appears to be a missing colon.

2022-04-01 19:26 UTC, mtnbikenc commented on windows_containers/windows-containers-release-notes-4-x.adoc
> +For more information, see the Red Hat OpenShift Container Platform Life Cycle Policy document for linkhttps://access.redhat.com/support/policy/updates/openshift#windows[OpenShift Container Platform f
```suggestion
For more information, see the Red Hat OpenShift Container Platform Life Cycle Policy document for link:https://access.redhat.com/support/policy/updates/openshift#windows[OpenShift Container Platform for Windows Containers].
```

2022-04-04 18:26 UTC, Anandnatraj commented
I see mu changes above have been incorporated. Much thanks. LGTM

2022-04-04 19:51 UTC, mburke5678 commented
@rrasouli Can you PTAL? Thank you!

2022-04-05 08:22 UTC, rrasouli commented
/lgtm thanks!

2022-04-05 15:03 UTC, mburke5678 commented
@rrasouli Thank you for the quick review. However, we probably should remove this statement from the OKD docs. Can you take another quick look?
https://github.com/openshift/openshift-docs/pull/44112/commits/ddc522401530cf77b15b2c09ff23bbf32f653c30

2022-04-05 15:40 UTC, rrasouli commented
@mburke5678 hey, I can't see the diff on the preview

2022-04-05 17:29 UTC, mburke5678 commented
@rrasouli Apologies. 

Here is a preview of [OKD with the _Getting support_ section](https://deploy-preview-44112--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/windows-containers-release-notes-4-x.html#getting-support)
Here is a preview of [OKD without the _Getting support_ section](https://deploy-preview-44112--osdocs.netlify.app/openshift-origin/latest/windows_containers/windows-containers-release-notes-4-x).

2022-04-05 19:24 UTC, mburke5678 commented
Closing in favor of https://github.com/openshift/openshift-docs/pull/44201

2022-04-05 19:24 UTC, closed without merging