OSDOCS-3333: add supported AWS instance types
openshift/openshift-docs pull request #44154
Opened 2022-04-04 20:27 UTC by bmcelvee

https://issues.redhat.com/browse/OSDOCS-3333

2022-04-05 18:20 UTC, bmcelvee commented
@yuwang-RH would you mind reviewing this PR, please? Thanks!

2022-04-05 18:58 UTC, bmcelvee commented on modules/rosa-sdpolicy-account-management.adoc
> +- i3.xlarge	(4 vCPU, 30.5 GiB)
I double checked the spacing here and in the high frequency section. It is correct, but rendering strangely on the diff view.

2022-04-05 19:00 UTC, bergerhoffer reviewed
LGTM!

2022-04-05 20:07 UTC, arendej commented
Please remove the .large instances.

2022-04-05 20:08 UTC, arendej commented
Please ensure the i3en.* sizes are also listed.

2022-04-05 20:33 UTC, arendej requested changes
Please remove the .large instance types from the ROSA files.
Please ensure the i3en.* sizes are also listed.

2022-04-06 09:04 UTC, yuwang-RH commented
LGTM~

2022-04-06 15:02 UTC, arendej requested changes
c5.xlarge is missing

2022-04-06 20:40 UTC, arendej requested changes
r6i.large (2 vCPU, 16 GiB) should be removed.

2022-04-06 21:05 UTC, merged

2022-04-06 21:06 UTC, bmcelvee commented
/cherrypick enterprise-4.10

2022-04-06 21:06 UTC, bmcelvee commented
/cherrypick enterprise-4.11