RHDEVDOCS-3942 Tracker for 2069771 - surface maven/nodejs pod templat…
openshift/openshift-docs pull request #44220
Opened 2022-04-05 20:38 UTC by rolfedh

…e deprecation in main jenkins related doc

 Aligned team: Dev Tools
- For branches: 4.10+
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3942
- Direct link to doc preview: tbd
- SME review: @gabemontero 
- QE review: @prietyc123 
- Peer review: @ 	tbd
- <All reviews complete. Please merge now>

2022-04-06 15:29 UTC, gabemontero requested changes
some suggestions @rolfedh to transition the release note into the surrounding before and after context in the actual docs 

It also "advertises" our change in approach a bit better I think.

WDYT?

2022-04-06 15:29 UTC, gabemontero commented on modules/images-other-jenkins-config-kubernetes.adoc
> +With this update, you can run Jenkins agents as sidecar containers. You can use this capability to run any container image in a Jenkins pipeline that has a correctly configured pod template and Jenki
```suggestion
In {product-title} 4.10 and later, use of multi-container Kubernetes plug-in Pod Template as Jenkins agents, where one container is the 'jnlp' container and the other 'sidecar' container is a container whose image has the tools needed to build in a particular language, is now the recommended pattern. You can use this capability to run any container image from the Red Hat Container Catalog in a Jenkins pipeline that has a correctly configured pod template and Jenkins file. The {product-title} Jenkins image has two pod templates named `java-build` and `nodejs-builder` with sidecar containers that demonstrate this approach. These two pod templates use the latest Java and NodeJS versions provided by the `java` and `nodejs` image streams in the `openshift` namespace.
```

2022-04-06 15:29 UTC, gabemontero commented on modules/images-other-jenkins-config-kubernetes.adoc
> +In {product-title} 4.10 and later, the non-sidecar `maven` and `nodejs` pod templates for Jenkins are deprecated. These pod templates are planned for removal in a future release. Bug fixes and suppor
```suggestion
With this, in {product-title} 4.10 and later, the non-sidecar `maven` and `nodejs` pod templates for Jenkins are deprecated. These pod templates are planned for removal in a future release. Bug fixes and support are provided through the end of that future life cycle, after which no new feature enhancements are made. Instead, with this update, you can run Jenkins agents as sidecar containers.
```

2022-04-06 16:45 UTC, rolfedh commented on modules/images-other-jenkins-config-kubernetes.adoc
> +With this update, you can run Jenkins agents as sidecar containers. You can use this capability to run any container image in a Jenkins pipeline that has a correctly configured pod template and Jenki
Thanks. Updated.

2022-04-06 16:45 UTC, rolfedh commented on modules/images-other-jenkins-config-kubernetes.adoc
> +In {product-title} 4.10 and later, the non-sidecar `maven` and `nodejs` pod templates for Jenkins are deprecated. These pod templates are planned for removal in a future release. Bug fixes and suppor
Thanks. Updated.

2022-04-06 16:56 UTC, gabemontero requested changes
Sorry, I don't know if my last suggestion was not what was needed entirely, or if your editing tweaked it, but looking at it again, it did not flow / resonate correctly from a technical perspective.

Here is another attempt by me to get the wording at least "technically" on point.

2022-04-06 17:37 UTC, rolfedh commented on modules/images-other-jenkins-config-kubernetes.adoc
> +In {product-title} 4.10 and later, the recommended pattern for running Jenkins agents is to use the `jnlp` and `sidecar` containers as Kubernetes plug-in pod templates. The `sidecar` container image
Thank you! Update. WDYT now?

2022-04-06 17:49 UTC, gabemontero approved these changes
/lgtm

2022-04-07 05:11 UTC, prietyc123 commented
/label qe-approved

2022-04-07 13:45 UTC, rolfedh commented
/assign @jitendar-singh

2022-04-07 18:37 UTC, bburt-rh commented on modules/images-other-jenkins-config-kubernetes.adoc
> +With this, in {product-title} 4.10 and later, the non-sidecar `maven` and `nodejs` pod templates for Jenkins are deprecated. These pod templates are planned for removal in a future release. Bug fixes
```suggestion
With this update, in {product-title} 4.10 and later, the non-sidecar `maven` and `nodejs` pod templates for Jenkins are deprecated. These pod templates are planned for removal in a future release. Bug fixes and support are provided through the end of that future life cycle, after which no new feature enhancements are made.
```
- The antecedent of  `this` is unclear. "With this update"? "With this change"? "With this fix"?

2022-04-07 19:12 UTC, merged

2022-04-07 19:12 UTC, JStickler commented
/cherry-pick enterprise-4.10

2022-04-07 19:12 UTC, JStickler commented
/cherry-pick enterprise-4.11

2022-04-07 19:18 UTC, bburt-rh commented
lgtm