Trello  documentation for quota by storage class
openshift/openshift-docs pull request #4436
Opened 2017-05-17 17:41 UTC by mburke5678

Based on https://github.com/openshift/openshift-docs/pull/3349

@derekwaynecarr PTAL

2017-05-31 02:10 UTC, derekwaynecarr requested changes
one update requested, then LGTM

2017-05-31 02:10 UTC, derekwaynecarr commented on admin_guide/quota.adoc
> +exceed this value. `*storage*` and `*requests.storage*` are the same value and can
the only supported value is `requests.storage`  - i am not sure why we stated `storage` as interchangeable.  it never has been.

2017-05-31 15:23 UTC, mburke5678 commented
@qwang1 PTAL

2017-06-06 14:52 UTC, mburke5678 commented
https://trello.com/c/Sbn4CyZz/386-document-quota-ability-to-scope-pvc-quotas-by-storage-class

2017-06-06 14:53 UTC, mburke5678 commented
@qwang1  PTAL

2017-06-12 03:31 UTC, qwang1 commented
@mburke5678 LGTM, thanks.

2017-06-12 14:33 UTC, mburke5678 commented
@openshift/team-documentation PTAL

2017-06-12 15:34 UTC, ahardin-rh commented on admin_guide/quota.adoc
> +|The total number of persistent volume claims with a matching storage class that can exist in the project .
looks like there's an extra space before the period

2017-06-12 15:39 UTC, ahardin-rh commented
@mburke5678 Just one comment from me. Also, needs a squash. Otherwise, looks good!

2017-06-12 16:25 UTC, merged

2017-06-13 02:41 UTC, mburke5678 commented
[rev_history]
|xref:../admin_guide/admin_guide/quota.adoc#admin-guide-quota[Setting Quotas]
|Added section on Storage Resources Managed by Quota.
%