Secure vs insecure image pruning
openshift/openshift-docs pull request #4471
Opened 2017-05-24 15:26 UTC by miminar

Document new options related to secure connection to integrated docker registry and a mechanism that decides whether to fall-back to insecure connection.

Resolves #4232

Is blocked on openshift/origin#14114

2017-05-24 15:27 UTC, miminar commented
@legionus PTAL

2017-05-31 07:24 UTC, miminar commented
@soltysh PTAL

2017-06-02 16:37 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +link:#using-insecure-connection-against-secured-registry[the one below].
xref:using-insecure-connection-against-secured-registry[the one below]

2017-06-02 16:38 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +is allowed only in case where neither certificate-authority nor registry-url is
`certificate-authority`
    `registry-url`

2017-06-02 16:42 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +`--certificate-authority` flag. Otherwise, the prune command will fail with
`prune` command

s/with error similar to/with an error similar to

2017-06-02 16:48 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +user's config are used - the same for communication with the master API.
s/config/configuration file
s/-/--

2017-06-02 16:50 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +connection verification. By default, the certificate authority data stored in
I would move the code block to just before "By default...." so that the first sentence does not get broken up.

2017-06-02 16:52 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +|Include images that were not pushed to the registry but have been mirrored by
registry, but

2017-06-02 17:37 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +.Using secure or insecure connection
Perhaps we can use [discrete headings ](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#discrete-headings)here instead?

2017-06-02 17:37 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +.Determining images and layers eligible for pruning
Perhaps we can use a [discrete heading](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#discrete-headings)here instead?

2017-06-05 10:26 UTC, soltysh requested changes
I left you some comments.

2017-06-05 10:26 UTC, soltysh commented on admin_guide/pruning_resources.adoc
> +specified. Whenever possible, use `--certificate-authority` instead of this
I'd move the last sentence as a NOTE below. Additionally, reword this to something like:

Whenever possible use `--certificate-authority`, instead. Use of this option is strongly discouraged.

2017-06-05 10:26 UTC, soltysh commented on admin_guide/pruning_resources.adoc
> +connection will be initiated. To allow a fall-back to insecure transport, use
Don't encourage using `--force-insecure` anywhere, so drop the last sentence. It's already explained and that's it, it should not be used anywhere, though.

2017-06-05 10:26 UTC, soltysh commented on admin_guide/pruning_resources.adoc
> +The secure connection is preferred for production use. It is done over HTTPS
Suggestion:
The secure connection is the preferred and recommended approach.

It's the recommended as a rule, not only for production.

2017-06-05 10:26 UTC, soltysh commented on admin_guide/pruning_resources.adoc
> +The fall-back to insecure connection is allowed in following cases unless
s/following/the following

2017-06-05 10:26 UTC, soltysh commented on admin_guide/pruning_resources.adoc
> +The fall-back to insecure connection is allowed in following cases unless
following cases **,** unless

2017-06-05 10:26 UTC, soltysh commented on admin_guide/pruning_resources.adoc
> +1. The prune command is run with `--force-insecure` option.
Add info in parenthesis this is not recommended.

2017-06-05 10:26 UTC, soltysh commented on admin_guide/pruning_resources.adoc
> +connection by appending `--force-insecure` to the command.
Add not recommended at the end in parens.

2017-06-05 10:29 UTC, miminar commented
Now blocked on openshift/origin#14405. I will need to update error messages once it lands.

2017-06-27 15:59 UTC, miminar commented
New blocked on openshift/origin#14914

2017-07-03 14:54 UTC, miminar commented on admin_guide/pruning_resources.adoc
> +specified. Whenever possible, use `--certificate-authority` instead of this
I've ditched it. There is plenty of other places advocating the same. Instead, I've put *(Dangerous)* at the beginning.

2017-07-11 11:55 UTC, miminar commented
Thanks for all the comments. They should be addressed now. The dependency PR is still waiting for the unblocked merge queue.

2017-10-03 13:29 UTC, miminar commented
No longer blocked. @ahardin-rh could you please review once more?

2017-10-03 18:09 UTC, bparees commented
@miminar if we label this PR for 3.5 and 3.6, the changes will be applied there.
 
if 3.5 and 3.6 need a *different* set of doc, then you'll need to open a separate PR and only label it for 3.5 and 3.6.

2017-10-03 18:10 UTC, bparees commented
@miminar so which versions is this specific PR appropriate for?

2017-10-04 08:57 UTC, miminar commented
@bparees 3.6 - latest; I'll re-submit new PRs for 3.4 and 3.5

2017-10-04 14:28 UTC, bparees commented
@miminar ok.

@openshift/team-documentation ptal/merge.

2017-10-04 16:23 UTC, miminar commented
I did some small corrections to the descriptions of flags.

2017-10-04 16:55 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +|*(Dangerous)* Allow an insecure connection to the docker registry that is
Instead of labeling this Dangerous, maybe we can say:

    *Use caution with this option.* Allow...

2017-10-04 16:56 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
s/below/Using Secure or Insecure Connections

2017-10-04 16:56 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +=== Using secure or insecure connection
Using Secure or Insecure Connections

2017-10-04 16:57 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +The secure connection is preferred and recomended approach. It is done over
is the preferred and recommended approach

2017-10-04 16:58 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +fall-back to insecure connection which is dangerous. In this case, either
connection, which is dangerous

2017-10-04 16:58 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +1. *(Dangerous)* The `prune` command is run with `--force-insecure` option.
run with the

2017-10-04 16:59 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +2. Provided registry-url is prefixed with `http://` scheme
The provided `registry-url` is prefixed with the `http://` scheme.

2017-10-04 17:00 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +3. Provided registry-url is a local-link address or localhost.
The provided `registry-url`

2017-10-04 17:00 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +4. Config of the current user allows for insecure connection. This may be
The configuration of the current user allows for an insecure connection.

2017-10-04 17:01 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +`--certificate-authority` flag. Otherwise, the `prune` command will fail with
using the `--certificate-authority` flag.

2017-10-04 17:03 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +xref:using-wrong-certificate-authority[the one] or
similar to those seen in xref:using-wrong-certificate-authority[Using the Wrong Certificate Authority] or xref:using-insecure-connection-against-secured-registry[Using an Insecure Connection Against a Secured Registry].

2017-10-04 17:09 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +==== Images not being pruned
Images Not Being Pruned

2017-10-04 17:10 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +==== Using secure connection against insecure registry
Using a Secure Connection Against an Insecure Registry

2017-10-04 17:13 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +If you see similar message in the output of the `oadm prune images` command:
If you see a message similar to the following in the output of the `oadm prune images` command, then your registry is not secured and the `oadm prune images` client will attempt to use a secure connection:

2017-10-04 17:14 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +the registry]. If that is not desired, you may force the client to use insecure
you can force the client to use an insecure

2017-10-04 17:14 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +==== Using insecure connection against secured registry
Using an Insecure Connection Against a Secured Registry

2017-10-04 17:16 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +Use `--certificate-authority` option to provide the right certificate authority
use the

2017-10-04 17:18 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +==== Using wrong certificate authority
Using the Wrong Certificate Authority

2017-10-04 17:19 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +The following error means that certificate authority used to sign the
that the certificate

2017-10-04 17:19 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +certificate of the secured Docker registry is different from the authority used
different than

2017-10-04 17:19 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +As a work-around, the `--force-insecure` flag may be added instead *(not
can be added instead

2017-10-04 17:20 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +|*(Dangerous)* Allow an insecure connection to the docker registry that is
Docker registry

2017-10-04 17:20 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +
Docker registry

2017-10-04 17:21 UTC, ahardin-rh commented on admin_guide/pruning_resources.adoc
> +certificate of the secured Docker registry is different from the authority used
Docker registry

2017-10-04 17:26 UTC, ahardin-rh commented
@miminar Thanks! Just a few minor comments from me. 

Just a heads-up that, given our new docs workflow, if you want to submit separate PRs for 3.4 and 3.5, be sure to do so against enterprise-3.4-stage and enterprise-3.5-stage respectively. Thanks again!

2017-10-05 09:29 UTC, miminar commented
@ahardin-rh thanks a lot! Comments should be addressed now.

2017-10-05 13:37 UTC, ahardin-rh commented
@miminar Excellent. Thank you!

2017-10-05 13:37 UTC, merged

2017-10-05 13:43 UTC, ahardin-rh commented
[rev_history]
|xref:../admin_guide/pruning_resources.adoc#admin-guide-pruning-resources[Pruning Objects]
|Added details on secure versus insecure image pruning.
%