Bug 2079334, corrected and hardcoded version number
openshift/openshift-docs pull request #45036
Opened 2022-04-27 15:52 UTC by ahardin-rh

Version(s):
4.6+

Addresses: 
https://bugzilla.redhat.com/show_bug.cgi?id=2079334

2022-04-28 12:49 UTC, MarSik requested changes
Hi, this has to say 4.7 and later

2022-05-02 15:27 UTC, ahardin-rh commented
@MarSik Thanks for confirming! There was some confusion around that, as the statement was first introduced in 4.6. I will apply this change to 4.7+.
@aireilly FYI

@juzhao PTAL. Thanks!

2022-05-04 20:53 UTC, GroceryBoyJr reviewed
/lgtm - Nice catch! Stand by for follow-on.

2022-05-04 20:55 UTC, bergerhoffer reviewed
LGTM too!

2022-05-06 18:55 UTC, ahardin-rh commented
Received QE review in the BZ

2022-05-06 18:55 UTC, merged

2022-05-06 18:56 UTC, ahardin-rh commented
/cherrypick enterprise-4.7

2022-05-06 18:56 UTC, ahardin-rh commented
/cherrypick enterprise-4.8

2022-05-06 18:56 UTC, ahardin-rh commented
/cherrypick enterprise-4.9

2022-05-06 18:56 UTC, ahardin-rh commented
/cherrypick enterprise-4.10

2022-05-06 18:56 UTC, ahardin-rh commented
/cherrypick enterprise-4.11

2022-05-06 19:07 UTC, ahardin-rh commented
Removing the 4.7 label because this file doesn't exist in that version