RHDEVDOCS-4032 - Added release notes for 1.3.7
openshift/openshift-docs pull request #45076
Opened 2022-04-28 13:14 UTC by DebarghoGhosh

OCP version for cherry-picking: enterprise-4.9
JIRA issues: https://issues.redhat.com/browse/RHDEVDOCS-4032

Preview pages:

SME+QE review:
Peer-review:

2022-05-02 07:44 UTC, chetan-rns commented on modules/gitops-release-notes-1-3-6.adoc
> +{gitops-title} 1.3.6 is now available on {product-title} 4.7, 4.8, and 4.9.
1.3.6 is available on 4.10 as well.

2022-05-02 07:44 UTC, chetan-rns commented on modules/gitops-release-notes-1-3-7.adoc
> +{gitops-title} 1.3.7 is now available on {product-title} 4.7, 4.8, and 4.9.
Same as above. 1.3.7 is also available on 4.10

2022-05-05 05:15 UTC, chetan-rns commented
/lgtm

2022-05-06 09:24 UTC, Srivaralakshmi requested changes
@DebarghoGhosh Please self-review once before submitting for review. Left some suggestions. PTAL. Thanks!

2022-05-09 09:02 UTC, Srivaralakshmi requested changes
@DebarghoGhosh Minor nitpicks. PTAL. Thanks!

2022-05-09 09:02 UTC, Srivaralakshmi commented on modules/gitops-release-notes-1-3-7.adoc
> +* Before this update, a flaw was found in OpennSSL. This update fixes the issue by updating the base images to the latest version to avoid OpenSSL flaw. link:https://access.redhat.com/security/cve/CV
```suggestion
* Before this update, a flaw was found in OpenSSL. This update fixes the issue by updating the base images to the latest version to avoid the OpenSSL flaw. link:https://access.redhat.com/security/cve/CVE-2022-0778[(CVE-2022-0778)].
```

2022-05-09 09:48 UTC, Srivaralakshmi approved these changes
@DebarghoGhosh Approved. Thanks!

2022-05-09 09:48 UTC, Srivaralakshmi commented
/lgtm

2022-05-10 13:21 UTC, Preeticp reviewed
@DebarghoGhosh a few comments, please fix.

2022-05-10 13:21 UTC, Preeticp commented on modules/gitops-release-notes-1-3-6.adoc
> +* A path traversal allows leaking out-of-bound files link:https://access.redhat.com/security/cve/CVE-2022-24731[(CVE-2022-24731)]. This update fixes the issue.
A path traversal flaw
leaking of out-of-bound files

2022-05-10 13:21 UTC, Preeticp commented on modules/gitops-release-notes-1-3-6.adoc
> +* A path traversal and improper access control allows leaking out-of-bound files link:https://access.redhat.com/security/cve/CVE-2022-24730[(CVE-2022-24730)]. This update fixes the issue.
A path traversal flaw
leaking of out-of-bound files

2022-05-10 13:21 UTC, Preeticp commented on modules/gitops-release-notes-1-3-6.adoc
> +* In {gitops-title} improper access control allows admin privilege escalation link:https://access.redhat.com/security/cve/CVE-2022-1025[(CVE-2022-1025)]. This update fixes the issue.
Comma before 'improper' @Srivaralakshmi  has also pointed this out. Please add it.

2022-05-10 14:57 UTC, merged

2022-05-10 19:21 UTC, bergerhoffer commented
@Preeticp it looks like the CPs to 4.10 and 4.9 didn't work because the right branch name wasn't specified. Can you please reissue them?

Also, this wasn't marked for 4.11, but if it's going into main then it most likely be going into 4.11 as well. Can you please confirm?

2022-05-11 06:43 UTC, Preeticp commented
Thank you @bergerhoffer I had kept this one open as I had to jump on to another thing, and wanted to check on the CPs. Fixing them now.

2022-05-11 06:43 UTC, Preeticp commented
/cherrypick enterprise-4.9

2022-05-11 06:44 UTC, Preeticp commented
/cherrypick enterprise-4.10

2022-05-11 12:27 UTC, Preeticp commented
/cherrypick enterprise-4.11