Add documentation for build pruning
openshift/openshift-docs pull request #4536
Opened 2017-06-05 23:15 UTC by coreydaley

Provides supporting documentation for https://github.com/openshift/origin/pull/13788 and https://github.com/openshift/origin/pull/14375

@openshift/devex ptal

2017-06-06 01:26 UTC, bparees requested changes

2017-06-06 01:26 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> +You can limit the number of previous builds that are kept around by supplying a positive
s/kept around/retained/

2017-06-06 01:26 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> +<2> `failedBuildsHistoryLimit` will prune builds with a status of `failed`, `cancelled`, or `error`
"will retain up to 2 builds with a status of completed"
"will retain up to 2 builds with a status of failed, cancelled, or error"

2017-06-06 01:26 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> + - a build completes it's lifecycle
s/it's/its/

2017-06-06 01:29 UTC, coreydaley commented
@bparees updated

2017-06-06 01:33 UTC, bparees requested changes

2017-06-06 01:33 UTC, bparees commented on dev_guide/builds/advanced_build_operations.adoc
> +<1> `successfulBuildsHistoryLimit` will retain up to 2  builds with a status of `completed`
somehow you put an extra space after the "2" :)

2017-06-06 13:50 UTC, coreydaley commented
@bparees fixed

2017-06-06 13:59 UTC, bparees commented
please cross-link this new section and the existing build pruning section to each other:
https://docs.openshift.org/latest/admin_guide/pruning_resources.html#pruning-builds

people reading about one technique will probably want to be aware of the existence of the other technique.

2017-06-06 15:32 UTC, coreydaley commented
@bparees updated

2017-06-06 16:00 UTC, bparees commented
lgtm. @openshift/team-documentation ptal/merge.

2017-06-06 19:00 UTC, bmcelvee commented
LGTM

2017-06-06 19:00 UTC, merged

2017-06-06 20:10 UTC, bmcelvee commented
[rev_history]
|xref:..admin_guide/pruning_resources.adoc#admin-guide-pruning-resources[Pruning Objects]
|Added note to xref:..admin_guide/pruning_resources.adoc#pruning-builds[Pruning Builds] linking to the xref:../dev_guide/builds/advanced_build_operations.adoc#build-pruning[Build Pruning] section.
%
|xref:../dev_guide/builds/advanced_build_operations.adoc#dev-guide-advanced-build-operations[Advanced Build Operations]
|Added the xref:../dev_guide/builds/advanced_build_operations.adoc#build-pruning[Build Pruning] section.
%

2017-11-07 01:40 UTC, bparees commented
@bmcelvee this doc appears to have found its way into 3.4/3.5:
https://docs.openshift.com/container-platform/3.4/dev_guide/builds/advanced_build_operations.html#build-pruning

it should not have (the feature is 3.6+)

2017-11-07 03:42 UTC, vikram-redhat commented
@bparees sorry about that. It has now been removed:

3.4: https://docs.openshift.com/container-platform/3.4/dev_guide/builds/advanced_build_operations.html

3.5: https://docs.openshift.com/container-platform/3.5/dev_guide/builds/advanced_build_operations.html