(WIP) adding documentation for using valueFrom
openshift/openshift-docs pull request #4557
Opened 2017-06-08 19:38 UTC by coreydaley

Dependent on https://github.com/openshift/origin/pull/14143

2017-06-13 15:48 UTC, coreydaley commented
@bparees @bmcelvee ptal

2017-06-13 16:08 UTC, bparees requested changes

2017-06-13 16:08 UTC, bparees commented on _topic_map.yml
> +      - Name: BuildConfig Environment
s/BuildConfig Environment/Build Environment/  (pretty much everywhere)

2017-06-13 16:08 UTC, bparees commented on dev_guide/builds/buildconfig_environment.adoc
> +
this needs some sort of context/introductory text.

2017-06-13 16:08 UTC, bparees commented on dev_guide/builds/buildconfig_environment.adoc
> +
also build_loglevel is a problematic example.  pick something less special, eg "examplevariable=examplevalue"

2017-06-13 16:08 UTC, bparees commented on dev_guide/builds/buildconfig_environment.adoc
> +string as shown below.
it doesn't seem like we should have to be documenting this.  is this behavior (which is general k8s env var behavior) not already covered elsewhere in the docs?  if not, i would propose that it should be and we shouldn't have to say anything about it specific to builds.

2017-06-13 16:08 UTC, bparees commented on dev_guide/builds/buildconfig_environment.adoc
> +You can escape an environment variable reference by using a double dollar sign.
same thing here..this isn't build specific behavior.  we're just finally supporting what everything else already did.

2017-06-13 16:08 UTC, bparees commented on dev_guide/builds/buildconfig_environment.adoc
> +resolve to.
and same thing here, except that we are a little specialized in terms of what references we do/do not support, which is worthy of a note somewhere in the builds doc.

2017-06-13 16:08 UTC, bparees commented on dev_guide/builds/buildconfig_environment.adoc
> +----
it seems a bit silly to have this example repeated immediately below.  i'd say this section (which is just an intro to the concept of valuefrom) maybe doesn't need a specific example, given the subsections provide examples.

(but i also think all this content should be refactored to be generic product doc on the behavior of envvars, not build specific, aside from whatever special cases we have in builds)

2017-06-13 16:40 UTC, coreydaley commented on dev_guide/builds/buildconfig_environment.adoc
> +
updated in next push

2017-06-13 18:34 UTC, coreydaley commented on _topic_map.yml
> +      - Name: BuildConfig Environment
Updated in next push

2017-06-20 16:18 UTC, bmcelvee commented
@coreydaley thanks for the rebase! @bparees are you still reviewing this PR? 

Thanks!

2017-06-20 17:38 UTC, bparees requested changes

2017-06-20 17:38 UTC, bparees commented on dev_guide/builds/build_strategies.adoc
> +section for more advanced topics.
this all looks redundant to the content immediately below it?  (everything except the new link to the advanced topics anyway).

also s/topics/usage/ here.

2017-06-20 17:38 UTC, bparees commented on dev_guide/downward_api.adoc
> -....
this is here for a reason, it indicates this is not a fully complete pod definition.

2017-06-20 17:38 UTC, bparees commented on dev_guide/downward_api.adoc
> -....
leave this here or complete the example

2017-06-20 17:38 UTC, bparees commented on dev_guide/downward_api.adoc
> -....
so either it should be left, or this should be fleshed out as a fully creatable example.

2017-06-20 17:39 UTC, bparees commented
@bmcelvee yes, sorry. just did another round.

2017-06-20 18:51 UTC, coreydaley commented on dev_guide/builds/build_environment.adoc
> +
I had previously removed it via your comment: https://github.com/openshift/openshift-docs/pull/4557#discussion_r121723411

2017-06-20 18:54 UTC, coreydaley commented on dev_guide/downward_api.adoc
> -....
updated in next push

2017-06-20 18:54 UTC, coreydaley commented on dev_guide/downward_api.adoc
> -....
updated in next push

2017-06-20 18:55 UTC, coreydaley commented on dev_guide/builds/build_environment.adoc
> +== Using valueFrom References
updated in next push

2017-06-20 18:55 UTC, coreydaley commented on dev_guide/builds/build_strategies.adoc
> +section for more advanced topics.
updated in next push

2017-06-20 18:55 UTC, coreydaley commented on dev_guide/builds/build_strategies.adoc
> +section for more advanced topics.
updated in next push

2017-06-20 18:55 UTC, coreydaley commented on dev_guide/builds/build_strategies.adoc
> +section for more advanced topics.
updated in next push

2017-06-20 18:55 UTC, coreydaley commented on dev_guide/builds/build_strategies.adoc
> +section for more advanced topics.
updated in next push

2017-06-21 14:43 UTC, coreydaley commented on dev_guide/builds/build_environment.adoc
> +
updated in next push

2017-06-21 14:59 UTC, coreydaley commented on dev_guide/builds/build_environment.adoc
> +== Overview
updated

2017-06-21 14:59 UTC, coreydaley commented on dev_guide/builds/build_environment.adoc
> +
Added to the Downward API page

2017-06-21 15:00 UTC, coreydaley commented
@bparees ptal

2017-06-21 15:40 UTC, bparees commented on dev_guide/builds/build_environment.adoc
> +Referencing container resources using valueFrom in build environment variables is currently not supported
s/currently//

2017-06-21 15:40 UTC, bparees commented on dev_guide/builds/build_strategies.adoc
> +section for more advanced usage.
@gabemontero please review this revised content (just this pipeline env section specifically)

2017-06-21 15:40 UTC, bparees commented on dev_guide/builds/build_strategies.adoc
> +section for more advanced usage.
i'm not sure moving all of the content into a true "note" annotation make sense.  it's an awfully long note :)

2017-06-21 15:40 UTC, bparees commented
pending my one nit and @gabemontero's sign off on the pipeline env content, this lgtm.

2017-06-21 15:45 UTC, coreydaley commented
@bparees updated

2017-06-21 15:53 UTC, gabemontero approved these changes
pipeline env specifics look correct

2017-06-21 15:57 UTC, coreydaley commented
@bmcelvee ptal, I think this one is finally ready!

2017-06-21 15:58 UTC, bparees approved these changes

2017-06-21 19:27 UTC, bmcelvee commented on dev_guide/builds/build_strategies.adoc
> +section for more advanced usage.
I agree, it's a bit too much for a note. :) I'll merge what we have here and open a follow-up PR.

2017-06-21 20:15 UTC, bmcelvee commented
[rev_history]
|xref:../dev_guide/builds/build_environment.adoc#dev-guide-build-build-environment[Build Environment]
|Added xref:../dev_guide/builds/build_environment.adoc#dev-guide-build-build-environment[Build Environment] chapter.
%
|xref:../dev_guide/builds/build_strategies.adoc#dev-guide-build-strategy-options[Build Strategy Options]
|Added links pointing to the xref:../dev_guide/builds/build_environment.adoc#dev-guide-build-build-environment[Build Environment] chapter, and added content on mapping between `BuildConfig` environment variables and Jenkins job parameters to the xref:../dev_guide/builds/build_strategies.adoc#jenkins-pipeline-strategy-environment[Environment Variables] section.
%
|xref:../dev_guide/downward_api.adoc#dev-guide-downward-api[Downward API]
|Updated `.json` references to `.yaml`, and added valueFrom content to the xref:../dev_guide/downward_api.adoc#dev-guide-downward-api[Downward API] chapter.
%

2017-06-21 20:22 UTC, merged