RHDEVDOCS-4103 Replace kubectl with oc in pipelines docs
openshift/openshift-docs pull request #45800
Opened 2022-05-18 12:31 UTC by sounix000

2022-05-18 12:58 UTC, VeereshAradhya approved these changes

2022-05-18 15:28 UTC, JStickler requested changes
There are two instances here where the command and the output are in the same code block.  This makes it harder for customers to use the copy/paste feature to copy the command.

2022-05-18 15:28 UTC, JStickler commented on modules/op-specifying-pipelines-resource-quota-using-priority-class.adoc
> +$ oc describe quota
From the OCP doc standards "Separate a command and its related example output into individual code blocks."

2022-05-19 14:03 UTC, JStickler approved these changes
LGTM

2022-05-19 14:04 UTC, merged

2022-05-19 14:04 UTC, JStickler commented
/cherry-pick enterprise-4.10

2022-05-19 14:04 UTC, JStickler commented
/cherry-pick enterprise-4.11