adjust doc for new pod template support
openshift/openshift-docs pull request #4580
Opened 2017-06-14 14:20 UTC by gabemontero

for https://trello.com/c/hS9lzo1v/1202-5-better-jenkins-slave-template-configuration-jenkinsintegration

@bparees @bmcelvee

2017-06-14 14:20 UTC, gabemontero commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Better jenkins slave template configuration [jenkins_integration]](https://trello.com/c/hS9lzo1v/1202-5-better-jenkins-slave-template-configuration-jenkinsintegration)

2017-06-14 14:25 UTC, bparees requested changes

2017-06-14 14:25 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +projects listed in the plug-in's configuration. The search specifically looks for:
it's actually either it searches the project it's running in, OR it searches the projects listed in the configuration, i believe.  If you want to search your own project and another one, you need to list both.

2017-06-14 14:25 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +When it finds an image stream with the appropriate label, or image stream tag with the appropriate  annontation, it generates the corresponding Kubernetes plug-in
typo on annotation

2017-06-14 14:25 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +        <name>asdf</name>
better sample name please

2017-06-14 14:25 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +        <label>asdf</label>
same

2017-06-14 14:25 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +    asdf: |-
better sample key

2017-06-14 14:25 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +    fdsa: |-
same here and in name/label

2017-06-14 14:34 UTC, gabemontero commented on using_images/other_images/jenkins.adoc
> +projects listed in the plug-in's configuration. The search specifically looks for:
yep misread the code earlier

2017-06-14 14:39 UTC, gabemontero commented
updates pushed

2017-06-14 14:47 UTC, bparees approved these changes

2017-06-14 14:47 UTC, bparees commented
lgtm

2017-06-14 20:09 UTC, bmcelvee commented
LGTM

2017-06-14 20:09 UTC, merged

2017-06-15 19:37 UTC, bmcelvee commented
[rev_history]
|xref:../using_images/other_images/jenkins.adoc#using-images-other-images-jenkins[Jenkins]
|Added content to the xref:../using_images/other_images/jenkins.adoc#using-the-jenkins-kubernetes-plug-in-to-run-jobs[Using the Jenkins Kubernetes Plug-in to Run Jobs] section for new pod template support.
%

2017-06-16 06:17 UTC, dongboyan77 commented
@gabemontero hi, do you think we need to add some descriptions for annotation `"slave-label": "<label>"` in imagestream and imagestreamTag

2017-06-16 12:54 UTC, gabemontero commented
hey @dongboyan77 - good catch!  Forgot about that nuance.  I'll submit a follow up PR.