Route security management by end user
openshift/openshift-docs pull request #4590
Opened 2017-06-16 14:07 UTC by pecameron

Openshift 3.6

Add a new route annotation "haproxy.router.openshift.io/ip_whitelist"
that specifies a space separated list of white listed source IP
addresses and/or CIDRs. Requests from IP addresses that are not in
the whitelist are dropped.

origin PR 14536
https://github.com/openshift/origin/pull/14536

Trello: TbZPhHKE Route security management by end user
https://trello.com/c/TbZPhHKE/

Bug: 1426562
https://bugzilla.redhat.com/show_bug.cgi?id=1426562

2017-06-16 14:08 UTC, pecameron commented
@knobunc @bfallonf PTAL

2017-06-16 15:18 UTC, knobunc requested changes

2017-06-16 15:18 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +separated list of IP addresses and/or CIDRs for the approved users.  Requests from
users isn't quite right... how about source addresses, or client addresses or something.

2017-06-16 15:18 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +source ip's. Alternatively, oc annotate route <name> may be used.
Wrap the "code" in backticks please: `oc annotate route <name>`

2017-06-16 15:18 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +*haproxy.router.openshift.io/ip_whitelist* annotation on the route. The whitelist is a space
Why asterisks not backticks?  I'd have thought we wanted to typeset them in fixed width.

2017-06-16 15:18 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +Allow only one ip:
IP address

2017-06-16 15:18 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +Several ip's:
IP addresses

2017-06-16 15:18 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +Ip ranges:
IP CIDR network

2017-06-16 15:18 UTC, knobunc commented on architecture/core_concepts/routes.adoc
> +Ip's and ranges:
Mixed IP addresses and networks

2017-06-16 17:15 UTC, ahardin-rh commented on architecture/core_concepts/routes.adoc
> +When the annotation is present for a route, an acl is set up in the route's haproxy backend with the whitelist.
s/acl/ACL
What is an ACL?

2017-06-16 17:15 UTC, ahardin-rh commented on architecture/core_concepts/routes.adoc
> +source ip's. Alternatively, oc annotate route <name> may be used.
s/ip's/IPs

2017-06-19 15:12 UTC, pecameron commented on architecture/core_concepts/routes.adoc
> +|`*haproxy.router.openshift.io/p_whitelist*` | xref:whitelist[Whitelist] |
OK

2017-06-19 15:14 UTC, pecameron commented on architecture/core_concepts/routes.adoc
> +*haproxy.router.openshift.io/ip_whitelist* annotation on the route. The whitelist is a space
Got me... I changed them.

2017-06-19 15:15 UTC, pecameron commented on architecture/core_concepts/routes.adoc
> +separated list of IP addresses and/or CIDRs for the approved users.  Requests from
Changed.

2017-06-19 15:16 UTC, pecameron commented on architecture/core_concepts/routes.adoc
> +source ip's. Alternatively, oc annotate route <name> may be used.
OK

2017-06-19 15:17 UTC, pecameron commented on architecture/core_concepts/routes.adoc
> +Allow only one ip:
OK. Cleaning up the rest in the description as well.

2017-06-19 15:19 UTC, pecameron commented on architecture/core_concepts/routes.adoc
> +Several ip's:
OK

2017-06-19 15:20 UTC, pecameron commented on architecture/core_concepts/routes.adoc
> +Ip ranges:
OK

2017-06-19 15:20 UTC, pecameron commented on architecture/core_concepts/routes.adoc
> +Ip's and ranges:
OK

2017-06-19 15:27 UTC, pecameron commented on architecture/core_concepts/routes.adoc
> +When the annotation is present for a route, an acl is set up in the route's haproxy backend with the whitelist.
Deleted 841. It is a level of detail that won't be interesting to the reader. The discussion is found in the haproxy 1.5 documentation. FYI haproxy includes addess control lists (acl). A list can be created and later used in the backend for different purposes. This PR uses the acl as a source of white list source IP addresses.

2017-06-19 15:28 UTC, pecameron commented on architecture/core_concepts/routes.adoc
> +source ip's. Alternatively, oc annotate route <name> may be used.
Changed.

2017-06-19 15:34 UTC, pecameron commented
@knobunc @ahardin-rh PTAL

2017-06-19 20:44 UTC, ahardin-rh commented
LGTM

2017-06-20 14:46 UTC, merged

2017-06-20 15:44 UTC, ahardin-rh commented
[rev_history]
|xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
|Added a new xref:../architecture/core_concepts/routes.adoc#whitelist[Route-specific IP Whitelists] section.
%