OSDOCS-3663: Various changes to ROSA prereqs
openshift/openshift-docs pull request #46027
Opened 2022-05-25 18:07 UTC by EricPonvelle

Version(s):
4.10+

Issue:
This PR adds changes that cover the following JIRA cards:

1. https://issues.redhat.com/browse/OSDOCS-3663
2. https://issues.redhat.com/browse/OSDOCS-3664
3. https://issues.redhat.com/browse/OSDOCS-3665
4. https://issues.redhat.com/browse/OSDOCS-3666
5. https://issues.redhat.com/browse/OSDOCS-3667
6. https://issues.redhat.com/browse/OSDOCS-3669

Link to docs preview:

Additional information:
This PR tracks changes from 6 JIRA cards. The changes are individually small, and I note which link relates to which JIRA card.

2022-06-10 19:38 UTC, mburke5678 commented on modules/rosa-sts-aws-requirements.adoc
> +{product-title} (ROSA) cluster provisioning tasks require linked `ocm-role` and `user-role` {cluster-manager} IAM resources to your AWS account using your Amazon Resource Name (ARN).
s/cluster provisioning/cluster-provisioning ?? (I had to read it a few times to understand.)

s/linked/linking ?? require the `ocm-role` and `user-role` {cluster-manager} IAM resources be linked to   (Seems like there needs to be another verb somewhere.)

2022-06-13 19:07 UTC, arendej requested changes
see comment

2022-06-13 19:07 UTC, arendej commented on modules/rosa-sts-aws-requirements.adoc
> +* The customer ensures that the AWS limits are sufficient to support {product-title} provisioned within the customer's AWS account. Running `rosa verify quota` in the CLI validates that you have the
Can we also add
> Please note that quota verification takes into account your AWS quota, but does note compare your consumption versus your quota.
.. or similar

2022-06-13 21:43 UTC, tmalove commented on modules/rosa-sts-aws-requirements.adoc
> +Quota verification checks your AWS quota, but it does note compare your consumption versus your AWS quota. See the "Limits and scalability" link in the Additional resources for more information.
```suggestion
Quota verification checks your AWS quota, but it does not compare your consumption to your AWS quota. See the "Limits and scalability" link in Additional resources for more information.
```

2022-06-13 21:48 UTC, tmalove commented on modules/rosa-sts-aws-requirements.adoc
> +* Your account must have a service-linked role set up as it is required for elastic load balancers (ELBs) to be configured. See AWS Limits in the  Additional resources for information on creating a s
```suggestion
* Your account must have a service-linked role set up as it is required for elastic load balancers (ELBs) to be configured. See AWS Limits in the  Additional resources for information about creating a service-linked role for your ELB if you have not created a load balancer in your AWS account previously.
```

2022-06-13 21:53 UTC, tmalove commented on modules/rosa-sts-aws-requirements.adoc
> +* You must not use the AWS account to elevate their permissions within the {product-title} cluster.
```suggestion
* You must not use the AWS account to elevate your permissions within the {product-title} cluster.
```

2022-06-13 21:54 UTC, tmalove commented on modules/rosa-sts-aws-requirements.adoc
> +* You do not need to have a preconfigured domain to deploy ROSA clusters. If you wish to use a custom domain, see the Additional resources for information.
```suggestion
* You do not need to have a preconfigured domain to deploy ROSA clusters. If you want to use a custom domain, see Additional resources for information.
```

2022-06-14 15:17 UTC, jeana-redhat reviewed
A couple really small nits and one very big annoying suggestion (sorry about that one)

2022-06-14 15:17 UTC, jeana-redhat commented on modules/rosa-sts-aws-requirements.adoc
> +* Red Hat must have egress allowed to the documented domains. See the "AWS firewall prerequisites" section for the designated domains.
If you split the module as suggested, you could even do `.Additional resources` links to sections farther down the page (I have had to do this for similar situations)

2022-06-14 15:17 UTC, jeana-redhat commented on modules/rosa-troubleshooting-deployment.adoc
> +== Creating the service role for the Elastic load balancer (ELB)
```suggestion
== Creating the service role for the elastic load balancer (ELB)
```

2022-06-14 15:17 UTC, jeana-redhat commented on rosa_planning/rosa-sts-aws-prereqs.adoc
>  == Additional resources
Needs a unique ID, e.g. from guidelines:
```
[role="_additional-resources"]
[id="additional-resources_configuring-alert-notifications"]
== Additional resources
```
But! if you break the stuff I mentioned above into modules, it is possible all of these would be distributed throughout the assembly under the modules they go with anyway. So use your judgement here :slightly_smiling_face:

2022-06-14 19:36 UTC, merged

2022-06-14 19:37 UTC, EricPonvelle commented
I'll address @jeana-redhat's module split comments in #46287.

2022-06-14 19:37 UTC, EricPonvelle commented
/cherrypick enterprise-4.10

2022-06-14 19:37 UTC, EricPonvelle commented
/cherrypick enterprise-4.11