OSSMDOC-595: service mesh 2.1.3 z stream release notes
openshift/openshift-docs pull request #46223
Opened 2022-06-01 17:13 UTC by rh-tokeefe

Version(s):

Issue:

Link to docs preview:

Additional information:

2022-06-08 15:53 UTC, jwendell approved these changes

2022-06-08 17:08 UTC, pbajjuri20 commented on _attributes/common-attributes.adoc
> +:SMProductVersion1x: 1.1.19
@rh-tokeefe: The version for SM 1.1 is 1.1.18-2.

FYI: 1.1 Errata name: Red Hat OpenShift Service Mesh 1.1.18.2 Containers

2022-06-08 17:10 UTC, pbajjuri20 commented on modules/ossm-rn-new-features-1x.adoc
> +== New features {SMProductName} 1.1.19
The version for SM 1.1 is 1.1.18-2.

FYI: 1.1 Errata name for 2.1.3 release: Red Hat OpenShift Service Mesh 1.1.18.2 Containers

2022-06-08 17:59 UTC, JStickler requested changes

2022-06-08 17:59 UTC, JStickler commented on modules/ossm-rn-known-issues.adoc
> +OpenShift Service Mesh Federation failover Transport Layer Security (TLS) error when setting `importAsLocal` to `true` in two separate federated meshes.
I think we need to be clearer here, the problem is not so much that there is an error message as that Failover doesn't work.  Maybe something like, "Configuring Federated service meshes for failover does not work as expected.  There is no workaround at this time."

2022-06-09 13:26 UTC, jshaughn reviewed
Kiali versions look good.  A couple of comments re: the 1.1 version.

2022-06-09 13:26 UTC, jshaughn commented on _attributes/common-attributes.adoc
> +:SMProductVersion1x: 1.1.18-2
is it supposed to be `1.1.18.2` ?  I don't know the answer but  I see above that it was `2.1.2.1`.

2022-06-09 15:30 UTC, JStickler approved these changes
LGTM

2022-06-13 16:09 UTC, merged

2022-06-13 16:09 UTC, JStickler commented
/cherry-pick enterprise-4.6

2022-06-13 16:09 UTC, JStickler commented
/cherry-pick enterprise-4.7

2022-06-13 16:09 UTC, JStickler commented
/cherry-pick enterprise-4.8

2022-06-13 16:09 UTC, JStickler commented
/cherry-pick enterprise-4.9

2022-06-13 16:09 UTC, JStickler commented
/cherry-pick enterprise-4.11