Bug 1451910 - Caution about egress network policy limitation
openshift/openshift-docs pull request #4630
Opened 2017-06-21 17:07 UTC by pravisankar

2017-06-21 17:07 UTC, pravisankar commented
@openshift/team-documentation PTAL

2017-06-21 17:22 UTC, ahardin-rh commented on admin_guide/managing_networking.adoc
> +will ignore `EgressNetworkPolicy`. We do egress network policy service endpoint filtering
s/*routes*/routes

2017-06-21 17:24 UTC, ahardin-rh commented on admin_guide/managing_networking.adoc
> +will ignore `EgressNetworkPolicy`. We do egress network policy service endpoint filtering
Egress network policy service endpoint filtering is done at node `kubeproxy`. When the router is involved, `kubeproxy` is bypassed and egress network policy enforcement is not applied.

2017-06-21 17:38 UTC, knobunc requested changes
Do we want to suggest that if admins want to prevent this bypass, they can limit the ability of people to create routes?

2017-06-21 17:38 UTC, knobunc commented on admin_guide/managing_networking.adoc
> +at node kubeproxy and when router is involved, kubeproxy is bypassed and egress
at _the_ node kubeproxy ... when _the_ router is involved, ...

2017-06-21 22:03 UTC, pravisankar commented
@knobunc @ahardin-rh Updated, ptal

2017-06-22 13:57 UTC, knobunc approved these changes
LGTM, thanks Ravi

2017-06-22 18:38 UTC, ahardin-rh commented
Thanks!

2017-06-22 18:38 UTC, merged

2017-06-22 18:44 UTC, ahardin-rh commented
[rev_history]
|xref:../admin_guide/managing_networking.adoc#admin-guide-manage-networking[Managing Networking]
|Added a note about limitations with the egress network policy.
%

2017-06-27 20:34 UTC, ahardin-rh commented
@knobunc Is this for OCP 3.6 forward, or can it apply to other versions?

2017-06-27 23:47 UTC, pravisankar commented
@ahardin-rh Applies to OCP 3.3+ (starting from version where we introduced egress network policy)