Windows Server 2022 support in WINC 5.1.0 Take 2
openshift/openshift-docs pull request #46460
Opened 2022-06-08 17:25 UTC by mburke5678

[Properly i](https://issues.redhat.com/browse/OSDOCS-3575
For 5.1.0:
2022 support for vSphere, and 20H2 still supported
no changes to other platforms

Preview:
WINC prereqs: 
[Supported Windows Server version](http://file.rdu.redhat.com/~mburke/OSDOCS-3575-windows-2022-winc-51/windows_containers/windows-containers-release-notes-5-x.html#wmco-prerequisites-supported-5.0.0_windows-containers-release-notes)
[Supported networking](http://file.rdu.redhat.com/~mburke/OSDOCS-3575-windows-2022-winc-51/windows_containers/windows-containers-release-notes-5-x.html#supported-networking)
[Creating the vSphere Windows VM golden image](http://file.rdu.redhat.com/~mburke/OSDOCS-3575-windows-2022-winc-51/windows_containers/creating_windows_machinesets/creating-windows-machineset-vsphere.html#creating-the-vsphere-windows-vm-golden-image_creating-windows-machineset-vsphere). Updated Step 1)

See https://github.com/openshift/openshift-docs/pull/45238 for conversations and reviews

2022-06-08 18:28 UTC, mtnbikenc requested changes
I think it is important to have sections for each release to show the differences.

2022-06-08 18:28 UTC, mtnbikenc commented on modules/wmco-prerequisites.adoc
> +|* Windows Server 20H2
```suggestion
|Windows Server 2019 (version 1809) 
```
This should not be changed from 2019 to 20H2.
Remove `*` for consistency with other rows.

2022-06-08 18:28 UTC, mtnbikenc commented on modules/wmco-prerequisites.adoc
> +* Windows Server 20H2
```suggestion
* Windows Server 2019 (version 1809) 
```
This should be 2019.

2022-06-08 18:28 UTC, mtnbikenc commented on modules/wmco-prerequisites.adoc
> +|* Windows Server 20H2
```suggestion
|Windows Server 20H2 
```
Remove for consistency with other rows.

2022-06-08 18:28 UTC, mtnbikenc commented on modules/wmco-prerequisites.adoc
> +|a|* Windows Server 2022 with the Windows link:https://support.microsoft.com/en-us/topic/april-25-2022-kb5012637-os-build-20348-681-preview-2233d69c-d4a5-4be9-8c24-04a450861a8d[KB5012637] patch.
```suggestion
a|* Windows Server 2022 with the Windows link:https://support.microsoft.com/en-us/topic/april-25-2022-kb5012637-os-build-20348-681-preview-2233d69c-d4a5-4be9-8c24-04a450861a8d[KB5012637] patch.
```
Incorrect table generation.

2022-06-09 05:09 UTC, jfrancoa commented
/lgtm

2022-06-09 18:32 UTC, mtnbikenc commented
/lgtm

2022-06-09 18:52 UTC, jldohmann commented
LGTM

2022-06-13 14:57 UTC, merged

2022-06-13 14:58 UTC, mtnbikenc commented on modules/wmco-prerequisites.adoc
> +* Windows Server 20H2
We are, until August.