OSSMDOC-227: update output from comand oc get smcp
openshift/openshift-docs pull request #46473
Opened 2022-06-08 20:08 UTC by rh-tokeefe

Version(s):

Issue:

Link to docs preview:

Additional information:

2022-06-08 20:23 UTC, jwendell approved these changes

2022-06-08 20:35 UTC, mattmahoneyrh commented
LGTM

2022-06-09 18:49 UTC, JStickler requested changes
I checked this against a cluster, and we need to update the output to match the current status.

2022-06-09 19:46 UTC, rh-tokeefe commented on modules/ossm-control-plane-deploy-1x.adoc
> +basic-install   9/9     ComponentsReady     default    v1.1      4m25s
@JStickler thanks for noticing this; the change has been made and the preview is now available.

2022-06-09 20:46 UTC, JStickler approved these changes
LGTM

2022-06-13 14:29 UTC, merged

2022-06-13 14:30 UTC, JStickler commented
/cherry-pick enterprise-4.6

2022-06-13 14:30 UTC, JStickler commented
/cherry-pick enterprise-4.7

2022-06-13 14:31 UTC, JStickler commented
/cherry-pick enterprise-4.8

2022-06-13 14:31 UTC, JStickler commented
/cherry-pick enterprise-4.8

2022-06-13 14:32 UTC, JStickler commented
/cherry-pick enterprise-4.9

2022-06-13 14:32 UTC, JStickler commented
/cherry-pick enterprise-4.10

2022-06-13 14:33 UTC, JStickler commented
/cherry-pick enterprise-4.11