Document subprotocol access token
openshift/openshift-docs pull request #4659
Opened 2017-06-27 18:00 UTC by liggitt

2017-06-29 06:50 UTC, vikram-redhat commented
![](https://github.trello.services/images/mini-trello-icon.png) [Document: Authenticate websocket API requests using subprotocols, not query parameters](https://trello.com/c/821iB8pP/578-document-authenticate-websocket-api-requests-using-subprotocols-not-query-parameters)

2017-06-29 12:49 UTC, ahardin-rh requested changes

2017-06-29 12:49 UTC, ahardin-rh commented on architecture/additional_concepts/authentication.adoc
> +- Sent as an `Authorization: Bearer...` header
header.

2017-06-29 12:49 UTC, ahardin-rh commented on architecture/additional_concepts/authentication.adoc
> +- Sent as an `access_token=...` query parameter for websocket requests prior to 3.6
ifdef::openshift-enterprise[]
prior to {product-title} 3.6.
endif::[]
ifdef::openshift-origin[]
prior to {product-title}1.6.
endif::[]

2017-06-29 12:49 UTC, ahardin-rh commented on architecture/additional_concepts/authentication.adoc
ifdef::openshift-enterprise[]
{product-title} versions 3.6 and later.
endif::[]
ifdef::openshift-origin[]
{product-title} versions 3.6 and later.
endif::[]

2017-06-29 12:49 UTC, ahardin-rh commented on architecture/additional_concepts/authentication.adoc
I think may need to further conditionalize for Online and Dedicated. The added content may not be applicable to those products. Is that correct?

2017-07-05 02:55 UTC, liggitt commented on architecture/additional_concepts/authentication.adoc
it's just as applicable to those products as the access_token query param doc was

2017-07-24 18:03 UTC, ahardin-rh commented
I am going to merge this to get this moving along, then do a follow-up PR for minor style edits. Thanks!

2017-07-24 18:03 UTC, merged

2017-07-24 18:21 UTC, ahardin-rh commented
No revision history needed