BZ-2093995: Add content of creating type: kubernetes.io/service-account-token secret
openshift/openshift-docs pull request #46882
Opened 2022-06-21 14:48 UTC by mburke5678

https://bugzilla.redhat.com/show_bug.cgi?id=2093995

2022-06-22 14:50 UTC, coreydaley requested changes

2022-06-22 17:56 UTC, mburke5678 commented on modules/nodes-pods-secrets-creating-basic.adoc
> +You can create an opaque secret to pass the credentials used for basic authentication. Using the basci authentication secret helps better defines the purpose of the secret, and sets a convention for
Thank you! I should have said I haven't proofread it all yet. Just wanted a sense that I am going in the right direction.

2022-08-10 13:00 UTC, bergerhoffer commented
The enterprise-4.12 label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.11. And any PR going into `main` must also target the latest version branch (enterprise-4.12).

If the update in your PR does NOT apply to version 4.12 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2022-10-28 13:03 UTC, kalexand-rh commented
Only versions 4.8+ are still in maintenance. I am removing labels from earlier versions from this PR.

2023-01-16 20:21 UTC, bergerhoffer commented
The `branch/enterprise-4.13` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.12. And any PR going into `main` must also target the latest version branch (enterprise-4.13).

If the update in your PR does NOT apply to version 4.13 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2023-04-25 15:38 UTC, kalexand-rh commented
Only versions 4.10+ are still in maintenance. I am removing labels from earlier versions from this PR.

2023-05-16 18:04 UTC, kalexand-rh commented
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2023-09-11 14:50 UTC, kalexand-rh commented
Only versions 4.11+ are still in maintenance. I am removing labels from earlier versions from this PR.

2023-10-12 17:42 UTC, kalexand-rh commented
/remove-lifecycle stale

@mburke5678, is this still valid?

2023-10-12 20:19 UTC, mburke5678 commented
@kalexand-rh WDYT? Are these changes worthwhile to persue?

2023-10-12 20:28 UTC, kalexand-rh commented
> @kalexand-rh WDYT? Are these changes worthwhile to persue?

I think it's worth rebasing. If that works, it'll be worth putting out for QE. I think the reorg makes sense, and node content has a substantial number of views.

2024-04-22 00:01 UTC, closed without merging