OSDOCS-3205: Added information about the Network Ingress to OCM book
openshift/openshift-docs pull request #47050
Opened 2022-06-24 18:10 UTC by EricPonvelle

Version(s):
4.10+

Issue:

Link to docs preview:
https://people.redhat.com/eponvell/062322/OSDOCS-3205_Network-Ingress/ocm/ocm-overview.html#ocm-networking-tab_ocm-overview

Additional information:
This PR explains how to add a new additional ingress in OCM.

2022-06-27 19:18 UTC, wgordon17 commented on modules/ocm-networking-tab-adding-ingress.adoc
> +.. **Make router private**: This checkbox allows you to control cluster privacy. By default, your ingress router is publicly exposed allowing anyone access. If you intend to run an application or web
```suggestion
.. **Make router private**: This checkbox allows you to control cluster privacy. By default, your ingress router is publicly exposed allowing anyone access. If you intend to run an application or website with access limited to individuals within your own organization, such as employees, then you can click this checkbox to make the network ingress private and requiring a private connection, such as a virtual private network (VPN) or virtual private cloud (VPC) peering, to access. 
```

2022-06-27 19:19 UTC, wgordon17 requested changes, later dismissed
LGTM with suggested changes

2022-06-29 13:40 UTC, xueli181114 commented on modules/ocm-networking-tab-concept.adoc
> +{cluster-manager-first} does not support the networking tab for Google Cloud Platform (GCP) non-CCS clusters--clusters running in a Red Hat GCP project.
sts cluster don't support additional ingress either. Should we clarify it here?

2022-06-30 01:21 UTC, xueli181114 commented
LGTM with the suggested change.

2022-06-30 14:54 UTC, stevsmit commented on modules/ocm-networking-tab-adding-ingress.adoc
> +. From the **Networking** tab in {cluster-manager}, click the "Additional application router" toggle to enable the ingress. There are two options you can add to the additional router:
Is "Additional application router" a GUI button? Would it be in asterisks? (*)

2022-06-30 15:00 UTC, stevsmit commented on modules/ocm-networking-tab-adding-ingress.adoc
> +. From the **Networking** tab in {cluster-manager}, click the "Additional application router" toggle to enable the ingress. There are two options you can add to the additional router:
Does "the ingress" need a noun after it? For example, "the ingress route," or "the ingress port," or "the ingress load balancer"? That said, there are a very few instances of "the Ingress" popping up (capitalized). Ingress is always capitalized on the Kubernetes website (https://kubernetes.io/docs/concepts/services-networking/ingress/), except in rare cases (ingress-nginix).

I think "the Ingress" is ok.

2022-06-30 15:04 UTC, stevsmit commented on modules/ocm-networking-tab-adding-ingress.adoc
> +.. **Make router private**: This checkbox allows you to control cluster privacy. By default, your ingress router is publicly exposed allowing anyone access. If you intend to run an application or web
Ingress (and following instances of Ingress should be capitalized I think)

2022-06-30 15:15 UTC, stevsmit commented on modules/ocm-networking-tab-adding-ingress.adoc
> +.. **Make router private**: This checkbox allows you to control cluster privacy. By default, your ingress router is publicly exposed allowing anyone access. If you intend to run an application or web
By default, your ingress router is publicly exposed allowing anyone access. could maybe be: 

 By default, your ingress router is publicly exposed and allows anyone access. 

Or maybe your sentence could just use a comma (ie., "your ingress router is publicly exposed, allowing. . . "

2022-06-30 15:17 UTC, stevsmit commented on modules/ocm-networking-tab-adding-ingress.adoc
> +.. **Make router private**: This checkbox allows you to control cluster privacy. By default, your ingress router is publicly exposed allowing anyone access. If you intend to run an application or web
The second sentence is really long and might need split into two. That might be difficult to work through since it's all one idea.

2022-06-30 15:18 UTC, stevsmit commented on modules/ocm-networking-tab-adding-ingress.adoc
> +A commonly used setup has a private default router, which means any applications deployed requires a VPN or VPC peering to access. You create an additional public router with a label match of  `route
s/ requires/ require

2022-06-30 15:23 UTC, stevsmit commented on modules/ocm-networking-tab-adding-ingress.adoc
> +You can add a network ingress to your cluster from the {cluster-manager-url} web UI.
According to Brandi, Ingress should always be capitalized.

2022-06-30 15:25 UTC, stevsmit commented on modules/ocm-networking-tab-adding-ingress.adoc
> +A commonly used setup has a private default router, which means any applications deployed requires a VPN or VPC peering to access. You create an additional public router with a label match of  `route
Maybe...

s/ You create/ You can create

2022-06-30 19:38 UTC, merged

2022-06-30 19:38 UTC, EricPonvelle commented
/cherrypick enterprise-4.10

2022-06-30 19:38 UTC, EricPonvelle commented
/cherrypick enterprise-4.11

2022-06-30 19:53 UTC, stevsmit commented
/lgtm