RN updates for Helm 4.11
openshift/openshift-docs pull request #47720
Opened 2022-07-13 12:24 UTC by Srivaralakshmi

[RHDEVDOCS-4088](https://issues.redhat.com//browse/RHDEVDOCS-4088): Document Helm Release Notes for 4.11

- **Aligned team**: Dev Tools
- **OCP version for cherry-picking**: enterprise-`4.11`
- **JIRA issues**: [RHDEVDOCS-4088](https://issues.redhat.com/browse/RHDEVDOCS-4088)
- **Preview pages**: [Download to see the preview in your browser](https://drive.google.com/file/d/1t3ZSCZXhyBdN80rgN46CbRAIXwmIY_A-/view?usp=sharing)
- **SME Review**: @dperaza4dustbit, @Kartikey-star 
- **QE review**:  @tisutisu
- **Peer-review**:

2022-07-19 11:59 UTC, Srivaralakshmi commented
@dperaza4dustbit, @Kartikey-star, and @tisutisu: PTAL at the PR and provide your feedback. Thanks!

2022-07-19 14:09 UTC, Kartikey-star reviewed
/lgtm

2022-07-20 02:02 UTC, dperaza4dustbit commented on release_notes/ocp-4-11-release-notes.adoc
> +* There is currently a known issue when a user is creating an instance of ProjectHelmChartRepository custom resource (CR) or HelmChartRepository CR with TLS verification. As a result, the user cannot
Is this only for ProjectHelmChartRepository or also for HelmChartRepository @Kartikey-star

2022-07-20 06:19 UTC, Srivaralakshmi commented on release_notes/ocp-4-11-release-notes.adoc
> +* There is currently a known issue when a user is creating an instance of ProjectHelmChartRepository custom resource (CR) or HelmChartRepository CR with TLS verification. As a result, the user cannot
Done.

2022-07-20 06:20 UTC, Srivaralakshmi commented
@Kartikey-star Thanks for the approval.

@dperaza4dustbit and @tisutisu Please review and provide feedback.

2022-07-21 11:43 UTC, dperaza4dustbit approved these changes
lgtm

2022-07-22 09:46 UTC, rolfedh commented on release_notes/ocp-4-11-release-notes.adoc
> +* There is currently a known issue when a user is creating an instance of ProjectHelmChartRepository custom resource (CR) with TLS verification. As a result, the user cannot list the repositories and
```suggestion
* There is currently a known issue. If you create an instance of `ProjectHelmChartRepository` custom resource (CR) that uses TLS verification, you cannot list repositories and perform Helm-related operations. There is currently no workaround for this issue. (link:https://issues.redhat.com/browse/HELM-343[*HELM-343*])
```

2022-07-22 09:48 UTC, rolfedh requested changes

2022-07-22 09:48 UTC, rolfedh commented on release_notes/ocp-4-11-release-notes.adoc
> +* There is currently a known issue when a user is creating an instance of ProjectHelmChartRepository custom resource (CR) with TLS verification. As a result, the user cannot list the repositories and
Please consider making these changes.

2022-07-25 07:09 UTC, tisutisu commented
LGTM

2022-07-26 08:45 UTC, Srivaralakshmi commented on release_notes/ocp-4-11-release-notes.adoc
> +* There is currently a known issue when a user is creating an instance of ProjectHelmChartRepository custom resource (CR) with TLS verification. As a result, the user cannot list the repositories and
Done.

2022-07-26 13:40 UTC, rolfedh approved these changes

2022-07-27 13:57 UTC, merged