OSDOCS-3826: Updated the compute section
openshift/openshift-docs pull request #47934
Opened 2022-07-18 19:17 UTC by EricPonvelle

Version(s):
4.10+

Issue:
https://issues.redhat.com/browse/OSDOCS-3826

Link to docs preview:

[ROSA preview](https://people.redhat.com/eponvell/071822/OSDOCS-3826_Workload-Clarity/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-compute_rosa-service-definition) - same content in OSD.

Additional information:
Updated the compute section in OSD and ROSA to note that no workloads should be deployed to Control plane and infrastructure nodes.

2022-07-18 20:08 UTC, stevsmit commented on modules/rosa-sdpolicy-account-management.adoc
> +Control plane and infrastructure nodes are deployed and managed by Red Hat. Shutting down the underlying infrastructure through the cloud provider console is unsupported and can lead to data loss. Th
Should we use the attributes here? 

For example, :pipelines-title: for Red Hat OpenShift Pipelines?

2022-07-22 16:26 UTC, wgordon17 requested changes

2022-07-22 16:26 UTC, wgordon17 commented on modules/rosa-sdpolicy-am-compute.adoc
> +Control plane and infrastructure nodes are deployed and managed by Red Hat. Shutting down the underlying infrastructure through the cloud provider console is unsupported and can lead to data loss. Th
```suggestion
Control plane and infrastructure nodes are deployed and managed by Red Hat. Shutting down the underlying infrastructure through the cloud provider console is unsupported and can lead to data loss. There are at least 3 control plane nodes that handle etcd- and API-related workloads. There are at least 2 infrastructure nodes that handle metrics, routing, the web console, and other workloads. You must not run any workloads on the control and infrastructure nodes. Any workloads you intend to run must be deployed on worker nodes. See the Red Hat Operator support section below for more information on Red Hat workloads that must be deployed on worker nodes.
```

2022-07-22 16:26 UTC, wgordon17 commented on modules/sdpolicy-am-aws-compute-types-non-ccs.adoc
> +.General purpose
Perhaps you can incorporate this PR here: https://github.com/openshift/openshift-docs/pull/47807

2022-07-22 16:26 UTC, wgordon17 commented on modules/sdpolicy-am-compute.adoc
> +Control plane and infrastructure nodes are also provided by Red Hat. There are at least 3 control plane nodes that handle etcd and API-related workloads. There are at least 2 infrastructure nodes tha
```suggestion
Control plane and infrastructure nodes are also provided by Red Hat. There are at least 3 control plane nodes that handle etcd and API-related workloads. There are at least 2 infrastructure nodes that handle metrics, routing, the web console, and other workloads. You must not run any workloads on the control plane and infrastructure nodes. Any workloads you intend to run must be deployed on worker nodes. See the Red Hat Operator support section below for more information on Red Hat workloads that must be deployed on worker nodes.
```

2022-07-22 16:26 UTC, wgordon17 commented on modules/sdpolicy-platform.adoc
> +Red Hat workloads typically refer to any Red Hat Operator. These Operators may require additional Red Hat subscriptions, and may incur additional cloud infrastructure costs. Some of the Red Hat Opera
```suggestion
Red Hat workloads typically refer to Red Hat-provided operators made available through Operator Hub. Red Hat workloads are not managed by the Red Hat SRE team, and must be deployed on worker nodes. These operators may require additional Red Hat subscriptions, and may incur additional cloud infrastructure costs. Examples of these Red Hat-provided operators are:
```

2022-07-22 16:26 UTC, wgordon17 commented on modules/rosa-sdpolicy-platform.adoc
> +Red Hat workloads typically refer to any Red Hat Operator. These Operators may require additional Red Hat subscriptions, and may incur additional cloud infrastructure costs. Some of the Red Hat Opera
```suggestion
Red Hat workloads typically refer to Red Hat-provided operators made available through Operator Hub. Red Hat workloads are not managed by the Red Hat SRE team, and must be deployed on worker nodes. These operators may require additional Red Hat subscriptions, and may incur additional cloud infrastructure costs. Examples of these Red Hat-provided operators are:
```

2022-07-23 16:49 UTC, wgordon17 approved these changes
LGTM 👍

2022-07-25 19:41 UTC, bmcelvee commented
LGTM!

2022-07-25 19:42 UTC, merged

2022-07-25 19:43 UTC, EricPonvelle commented
/cherrypick enterprise-4.10

2022-07-25 19:43 UTC, EricPonvelle commented
/cherrypick enterprise-4.11