BZ#2086986 remove references to instance_type_id parameter
openshift/openshift-docs pull request #47948
Opened 2022-07-19 13:49 UTC by emarcusRH

[BZ#2086986](https://bugzilla.redhat.com/show_bug.cgi?id=2086986)

Version(s):
PR applies to enterprise-4.11 or later

Issue:

Remove references to "instance_type_id" parameter from the documentation 
This applies specifically to  

- sample YAML for creating a machineset on RHV, 

and to 
- example installation config YAML example for installing on RHV with customizations

Link to docs preview:
http://file.tlv.redhat.com/emarcus/2086986/installing/installing_rhv/installing-rhv-customizations.html#installation-configuration-parameters-additional-machine_installing-rhv-customizations

http://file.tlv.redhat.com/emarcus/2086986/machine_management/creating_machinesets/creating-machineset-rhv.html#machineset-yaml-rhv_creating-machineset-rhv

Additional information:

2022-07-19 16:15 UTC, emarcusRH commented
@engelmi please review
@Darth-Mera  please review

2022-07-22 13:25 UTC, engelmi requested changes

2022-07-22 13:25 UTC, engelmi commented on modules/machineset-yaml-rhv.adoc
>  [WARNING]
This warning regarding the deprecation of the `instance_type_id` should be removed as well.

2022-07-27 12:29 UTC, engelmi approved these changes

2022-07-27 14:10 UTC, emarcusRH commented
BZ comment from QE: 
"Veronika Fuxova 2022-07-18 16:46:49 UTC
Hi Eli, 
yes, it's enough to remove just the line "instance_type_id: <instance_type_id> <8>" from this example. In general, remove all the lines that describe instance_type_id, no other lines, please. If you delete all those lines you mention in your first comment, that should be enough."

2022-07-27 14:17 UTC, jeana-redhat approved these changes
LGTM

2022-07-27 16:11 UTC, jeana-redhat commented
Picked up in #48399 due to weird commit squash/build errors

2022-07-27 16:11 UTC, closed without merging