[enterprise-4.11] RN entry for BZ2102230
openshift/openshift-docs pull request #48039
Opened 2022-07-20 18:32 UTC by jldohmann

Version(s): 4.11

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2102230

Link to docs preview:

Additional information: RN entry for #48037

2022-07-20 18:51 UTC, mike-nguyen commented
I don't think customers can browser `rhcos.mirror.openshift.com`. It is a redirector to the S3 backend so customers will need to know the exact URL to the image they are looking for.

2022-07-20 19:59 UTC, jldohmann commented
@mike-nguyen good point 😅 I've updated the text and included a link to the relevant doc, could you PTAL again?

273ed5c..19ce228
19ce228..3e22fc7

2022-07-21 00:08 UTC, mike-nguyen requested changes

2022-07-21 00:08 UTC, mike-nguyen commented on release_notes/ocp-4-11-release-notes.adoc
> +The redirector host name for downloading {op-system} boot images is now `rhcos.mirror.openshift.com`. You must configure your firewall to grant access to this registry. See xref:../installing/install
```suggestion
The redirector host name for downloading {op-system} boot images is now `rhcos.mirror.openshift.com`. You must configure your firewall to grant access to the boot images. See xref:../installing/install_config/configuring-firewall.html#configuring-firewall_configuring-firewall[Configuring your firewall for {product-title}] for more information.
```

2022-07-21 00:08 UTC, mike-nguyen commented on release_notes/ocp-4-11-release-notes.adoc
> +The redirector host name for downloading {op-system} boot images is now `rhcos.mirror.openshift.com`. You must configure your firewall to grant access to this registry. See xref:../installing/install
Its more like a file server than a registry.

2022-07-21 10:03 UTC, travier reviewed
Same comment as Mike but otherwise LGTM

2022-07-21 14:15 UTC, jldohmann commented on release_notes/ocp-4-11-release-notes.adoc
> +The redirector host name for downloading {op-system} boot images is now `rhcos.mirror.openshift.com`. You must configure your firewall to grant access to this registry. See xref:../installing/install
thanks, Mike. Fixed 👍

2022-07-21 14:15 UTC, jldohmann commented
3e22fc7..db38682 implement feedback

2022-07-21 14:30 UTC, bergerhoffer commented on release_notes/ocp-4-11-release-notes.adoc
> +The redirector host name for downloading {op-system} boot images is now `rhcos.mirror.openshift.com`. You must configure your firewall to grant access to the boot images. See xref:../installing/insta
Recommend spelling out RHCOS in the first sentence
hostname one word per ISG
Consider putting "For more information," first, as that's preferred by the ISG

```suggestion
The redirector hostname for downloading {op-system-first} boot images is now `rhcos.mirror.openshift.com`. You must configure your firewall to grant access to the boot images. For more information, see xref:../installing/install_config/configuring-firewall.adoc#configuring-firewall_configuring-firewall[Configuring your firewall for {product-title}].
```

2022-07-21 14:45 UTC, jldohmann commented
db38682..1d9ee4d implement peer review feedback

2022-07-21 15:36 UTC, opayne1 commented
lgtm!

2022-07-21 15:50 UTC, merged