[WIP] vSphere Virtual Volume Support
openshift/openshift-docs pull request #4853
Opened 2017-07-27 01:10 UTC by gaurav-nelson

WIP

2017-07-27 01:12 UTC, gaurav-nelson commented
![](https://github.trello.services/images/mini-trello-icon.png) [Document: Backport vsphere fixes to openshift](https://trello.com/c/gSsay1n6/464-document-backport-vsphere-fixes-to-openshift)

2017-07-27 01:38 UTC, gnufied commented on architecture/additional_concepts/storage.adoc
> +- vSphere Volume
We should call this VMWare Vsphere

2017-07-27 01:39 UTC, gnufied commented on install_config/persistent_storage/persistent_storage_vsphere_volume.adoc
> += Persistent Storage Using vSphere Virtual Volume Plug-ins
Same as above - the title should read "Persistent Storage using VMware vSphere"

2017-08-02 05:48 UTC, gaurav-nelson commented
@gnufied Can you please check the updates?

2017-08-02 14:13 UTC, ron1 commented
A vSphere/VMWare "Virtual Volume", i.e., VVol, is a new capability available since vSphere 6.0 [see "vSphere 6.0 New Features – What is VMware Virtual Volumes (VVols)?" http://www.vmwarearena.com/vsphere-6-0-what-is-vmware-virtual-volumes-vvols/]. It is my understanding that the Kubernetes vSphere Cloud Provider does not currently support Virtual Volumes. As a result, please be careful to avoid references to the term "Virtual Volume" in the OpenShift documentation.

2017-08-04 00:18 UTC, gaurav-nelson commented
@gnufied Up for review :globe_with_meridians: 
I have included most of the information, please let me know if something is missing.

2017-08-06 05:12 UTC, gaurav-nelson commented
@gnufied bump!

2017-08-06 06:23 UTC, ron1 commented
OpenShift documentation should either reference Kubernetes vSphere Cloud Provider documentation or include most of what is contained therein. In particular, the content in sections "vSphere Cloud Provider" (https://kubernetes.io/docs/getting-started-guides/vsphere/#vsphere-cloud-provider) and "Enabling vSphere Cloud Provider Steps 1-7" (https://kubernetes.io/docs/getting-started-guides/vsphere/#enable-vsphere-cloud-provider) should be completely covered in their entirety. Specifically, Steps 1-4 seem to be completely missing. Also confirm that OpenShift 3.6 does not support "vSphere Storage Policy Based Management for Containers orchestrated by OpenShift/Kubernetes" and does not support Datastore Clusters as both of these appear to be Kubernetes 1.7/1.8 features. OpenShift docs should also describe Dynamic Provisioning of vSphere Volume PVCs in more detail including an example. Just a few thoughts.

2017-08-08 06:58 UTC, jhou1 requested changes

2017-08-08 06:58 UTC, jhou1 commented on install_config/configuring_vsphere.adoc
> +xref:../install_config/persistent_storage/persistent_storage_vsphere.adoc#install-config-persistent-storage-persistent-storage-vsphere[using VMWare vSphere VMDK Volumes as persistent storage] for app
`After VMDL Volume is configured`: `VMDL` -> `VMDK`.

2017-08-08 07:31 UTC, jhou1 commented on install_config/configuring_vsphere.adoc
> +<8> The vCenter VM folder path, in which the node VMs are located.  It can be set to an empty path(`working-dir = ""`), if Node VMs are located in the root VM folder.
`working-dir` is optional

2017-08-08 09:22 UTC, vikram-redhat commented
Thanks @jhou1 .

@bfallonf - Please review, merge and do a follow up for the fixes as required.

2017-08-08 20:29 UTC, ahardin-rh commented
@bfallonf Once this merges and you do any follow-ups, in a separate PR can you please add a link to this content in the[ vSphere section of release notes](http://file.rdu.redhat.com/~ahardin/07282017/ocp-3-6-release-notes/release_notes/ocp_3_6_release_notes.html#ocp-36-vmware-vsphere-storage)?

2017-08-08 20:29 UTC, ahardin-rh commented
FYI @gaurav-nelson and @vikram-redhat on the above note

2017-08-08 22:47 UTC, bfallonf commented
Thank you @jhou1 . I'll merge this and fix those in a separate PR.

@ahardin-rh will do :)

2017-08-08 22:51 UTC, bfallonf commented
[rev_history]
|xref:../install_config/configuring_vsphere.adoc#install-config-configuring-vsphere[Configuring for VMWare vSphere]
|Added the Configuring for VMWare vSphere topic.
%
|xref:../install_config/persistent_storage/persistent_storage_vsphere.adoc#install-config-persistent-storage-persistent-storage-vsphere[Configuring Persistent Storage -> Persistent Storage Using VMWare vSphere Volume]
|Added the Persistent Storage Using VMWare vSphere Volume topic.
%

2017-08-08 22:51 UTC, merged

2017-08-09 01:29 UTC, jhou1 commented on install_config/configuring_vsphere.adoc
> +<9> (Optional) VM name of the Master Node. If this parameter is specified , `vsphere.conf` file on the worker node does not need vCenter credentials.
According to https://kubernetes.io/docs/getting-started-guides/vsphere/, `vm-name` is introduced in kubernetes 1.6.4. Our latest OCP has kubernetes `v1.6.1+5115d708d7`. So I think this parameter isn't supported in our product yet.

2017-08-09 01:42 UTC, bfallonf commented on install_config/configuring_vsphere.adoc
> +<9> (Optional) VM name of the Master Node. If this parameter is specified , `vsphere.conf` file on the worker node does not need vCenter credentials.
Thank you @jhou1 . This PR was merged, so I created another: #4962 

Please let me know if there's anything more for this PR.