BZ2108643: Update file system overhead documentation
openshift/openshift-docs pull request #48616
Opened 2022-07-31 17:27 UTC by maya-r

- Refer to openshift virtualization instead of CDI
- Mention that the specific storage class overrides the global
- Mention that we want to look at CDIConfig for verification,
it doesn't appear in the CDI object.

There was some confusion about where to put the tunable when it
was introduced, and whether it's tunable downstream at all.
It wasn't tunable downstream since its introduction as HCO will
override changes to CDI object.
As of 4.11, it is tunable downstream, but you need to use the HCO
object to do so.

Version(s):
PR applies to all versions after 4.11, but we wanted to document these changes only from 4.12.

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2108643

2022-08-08 09:42 UTC, kgoldbla requested changes

2022-08-08 09:42 UTC, kgoldbla commented on modules/virt-overriding-default-fs-overhead-value.adoc
> +. Edit the `spec.filesystemOverhead` fields. You can choose from either or both a global value that will apply to all storage classes, or a storage class specific value.
You can choose from either or both a global value that will apply to all storage classes, or a storage class specific value. --> Changed to:
  You can choose to populate either a global value that will apply to all storage classes, or a storage class specific value or both.

2022-08-08 09:42 UTC, kgoldbla commented on modules/virt-overriding-default-fs-overhead-value.adoc
> +<2> The file system overhead percentage for the specified storage class. For example, `mystorageclass: "0.04"` changes the default overhead value for PVCs in the `mystorageclass` storage class to 4%.
If both a global value and a storage class value appear, the storage class specific value will be used. --> 
Change to:
If both a global value and a storage class value are configured, the storage class specific value will be used.

2022-08-09 10:32 UTC, apinnick commented
There are too many issues for me to comment on, including the fact that there is no preview build. I will create a CNV docs bug so that a writer can make these changes.

2022-08-09 10:33 UTC, apinnick reviewed
Most changes are OK but some require a writer, such as using correct doc attributes for the product name and creating a preview build. Moving this task to a CNV writer.

2023-01-08 00:01 UTC, closed without merging