OSSMDOC-644: Update service mesh rel notes for Kial version
openshift/openshift-docs pull request #48744
Opened 2022-08-03 17:46 UTC by rh-tokeefe

Version(s):

Issue:

Link to docs preview:

Additional information:

2022-08-03 18:32 UTC, jshaughn requested changes
I believe the container versions are dash1 as opposed to dot1.

2022-08-03 18:32 UTC, jshaughn commented on modules/ossm-rn-new-features.adoc
> +|1.48.2.1
```suggestion
|1.48.2-1
```

2022-08-03 18:32 UTC, jshaughn commented on modules/ossm-rn-new-features.adoc
> +|1.36.12.1
```suggestion
|1.36.12-1
```

2022-08-03 18:32 UTC, jshaughn commented on modules/ossm-rn-new-features.adoc
> +|1.24.16.1
```suggestion
|1.24.16-1
```

2022-08-03 18:56 UTC, FilipB commented
I'm wondering if it's necessary to include the last part. Is it accessible to users anywhere? Kiali operator is shown as 1.48.2 in OCP console and Kiali about dialog also shows 1.48.2.

2022-08-03 19:06 UTC, rh-tokeefe commented
@FilipB that's a good question. On prior releases, we tended to list the fourth value for additional clarity, even though the console does not show it.

2022-08-03 19:19 UTC, jshaughn approved these changes

2022-08-03 19:38 UTC, rh-tokeefe commented on modules/ossm-rn-new-features.adoc
> +|1.48.2.1
Done

2022-08-03 19:39 UTC, rh-tokeefe commented on modules/ossm-rn-new-features.adoc
> +|1.36.12.1
Done

2022-08-03 19:39 UTC, rh-tokeefe commented on modules/ossm-rn-new-features.adoc
> +|1.24.16.1
Done

2022-08-04 12:14 UTC, FilipB commented
LGTM

2022-08-04 14:46 UTC, JStickler approved these changes
LGTM

2022-08-08 12:45 UTC, merged

2022-08-08 12:45 UTC, JStickler commented
/cherry-pick enterprise-4.6

2022-08-08 12:46 UTC, JStickler commented
/cherry-pick enterprise-4.7

2022-08-08 12:46 UTC, JStickler commented
/cherry-pick enterprise-4.8

2022-08-08 12:46 UTC, JStickler commented
/cherry-pick enterprise-4.9

2022-08-08 12:46 UTC, JStickler commented
/cherry-pick enterprise-4.10

2022-08-08 12:46 UTC, JStickler commented
/cherry-pick enterprise-4.11