[ROX-11918]: Add custom route to central configuration
openshift/openshift-docs pull request #48792
Opened 2022-08-04 16:32 UTC by andykrohg

Version(s):
4.11+

Issue:
[](https://issues.redhat.com/browse/ROX-11918)

Link to docs preview:
https://github.com/andykrohg/openshift-docs/blob/rhacs-docs/modules/central-configuration-options-operator.adoc

Additional information:

Pending merge of PR in stackrox: https://github.com/stackrox/stackrox/pull/2621

2022-08-11 04:29 UTC, porridge requested changes

2022-08-11 04:29 UTC, porridge commented on modules/central-configuration-options-operator.adoc
> +|Specify a custom host name to use for Central's route. Leave this blank to accept the default value from OpenShift.
```suggestion
|Specify a custom host name to use for Central's route. Leave this unset to accept the default value from OpenShift.
```
Not sure how a route would behave if host is set to an empty string (as opposed to unset), but better safe than sorry.

2022-08-17 15:59 UTC, andykrohg commented
Ready for merge whenever this makes sense! Stackrox PR was merged @gaurav-nelson  : https://github.com/stackrox/stackrox/pull/2621

2022-09-26 18:29 UTC, andykrohg commented
Looks like this change is live in ACS 3.72. Is this ready for merge?

2022-09-30 04:08 UTC, gaurav-nelson commented on modules/central-configuration-options-operator.adoc
> +|Specify a custom host name to use for Central's route. Leave this unset to accept the default value from OpenShift.
```suggestion
|Specify a custom hostname to use for Central's route. Leave this unset to accept the default value that {ocp} provides.
```

2022-10-20 19:17 UTC, michaelryanmcneill commented
/label peer-review-needed

2022-10-20 19:19 UTC, michaelryanmcneill commented
Make sure to rebase your commits!

2022-10-20 19:39 UTC, andykrohg commented
> Make sure to rebase your commits!

All set!

2022-10-20 19:43 UTC, michaelryanmcneill commented
Per Slack, removing `peer-review-required`, adding `peer-review-done`, and adding `merge-review-needed`. 

Merge team, please cherry pick into: `rhacs-docs-3.72`

/label peer-review-done
/label merge-review-needed
/remove-label peer-review-needed

2022-10-20 20:40 UTC, merged

2022-10-21 18:06 UTC, jboxman-rh commented
/cherry-pick rhacs-docs-3.72

2022-10-21 19:20 UTC, michaelryanmcneill commented
This is weird....going to try again for you @jboxman-rh 

/cherry-pick rhacs-docs-3.72

2022-10-21 20:05 UTC, jboxman-rh commented
/cherry-pick rhacs-docs-3.72

2022-10-21 20:05 UTC, jboxman-rh commented
I guess this needs to be manually cherry picked?

2022-10-27 23:49 UTC, michaelryanmcneill commented
@jboxman-rh can you help manually cherry pick it?