dnsManagementPolicy
openshift/openshift-docs pull request #49057
Opened 2022-08-11 20:03 UTC by Amrita42

- Applies to main and 4.12
- [Jira](https://issues.redhat.com/browse/CFE-526)
- [Preview](http://file.del.redhat.com/asakthiv/CFE-520-526/networking/ingress-operator.html#nw-configure-dns-mgt-ingress-controller-lb_configuring-ingress)
- @thejasn ptal

Note that Operators API content cant be edited because it is auto-generated.

2022-08-29 14:39 UTC, thejasn requested changes

2022-08-29 20:31 UTC, thejasn requested changes

2022-08-29 20:31 UTC, thejasn commented on modules/nw-configure-dns-mgt-ingress-controller-lb.adoc
> +If the domain on the Ingress Controller does not match with `dnsConfig.Spec.BaseDomain` , the policy is automatically set to `Unmanaged`.
This is only available on AWS cloud.

2022-08-29 20:33 UTC, thejasn commented on modules/nw-configure-dns-mgt-ingress-controller-lb.adoc
> +If the domain on the Ingress Controller does not match with `dnsConfig.Spec.BaseDomain` , the policy is automatically set to `Unmanaged`.
```suggestion
On AWS cloud plaform, if the domain on the Ingress Controller does not match with `dnsConfig.Spec.BaseDomain` , the `dnsManagementPolicy` on the Ingress Controller is set to `Unmanaged`.
```

2022-08-30 10:04 UTC, Amrita42 commented on modules/nw-configure-dns-mgt-ingress-controller-lb.adoc
> +
Its not possible to add a link/xref within the module due to tool limitations however we can add it here >> Additional Resources >>https://docs.openshift.com/container-platform/4.11/networking/ingress-operator.html#additional-resources

2022-08-30 10:19 UTC, Amrita42 commented on modules/nw-configure-dns-mgt-ingress-controller-lb.adoc
> +. Modify an `IngressController` custom resource to set `dnsManagementPolicy`:
Yes, I think it is a good idea to document both.

2022-08-30 14:42 UTC, Amrita42 commented
Closing this PR , opened a new PR >> https://github.com/openshift/openshift-docs/pull/49752

2022-08-30 14:42 UTC, closed without merging