OADP-742: Add documentation regarding OADP-MTC support versions
openshift/openshift-docs pull request #50032
Opened 2022-09-05 10:40 UTC by RichardHoch

OADP -- 1.0.x; 1.1.0 OCP 4.6+

Resolves https://issues.redhat.com/browse/OADP-742 by adding a note about OADP compatibility with MTC to the introduction to all installation instructions. The location was chosen to maximize the chances that users will see this note before beginning any other installation activity or pre-activity.

2022-09-06 05:45 UTC, mperetzred requested changes

2022-09-06 05:45 UTC, mperetzred commented on backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.adoc
> +Use OADP 1.0._x_ with MTC 1.7._x_.
I don't think these are suppose to be the warning messages; the OADP operator is installed as part of the MTC installation automatically and is limited to a specifc range (as @rayfordj mentioned in the jira ticket).

We should tell the customer that the next OADP 1.0.x releases starting from 1.0.4 are only supported when used as a dependency of MTC 1.7.z, and not as a standalone operator.

2022-09-07 08:52 UTC, RichardHoch commented
@shubham-pampattiwar @mperetzred -- Please review this PR again. I reduced the strength of the note from "IMPORTANT" to "NOTE" and changed the text as Maya suggested.

2022-09-07 10:22 UTC, mperetzred commented
@RichardHoch could you please use my words as in the jira ticket?
We need to mention the availability of 1.0.4 images and the current statement is not addressing that.

2022-09-07 11:48 UTC, mperetzred commented
- Starting from 1.0.4, all 1.0.z can only be used as a dependency of MTC and are not available as a standalone operator

2022-09-08 06:30 UTC, mperetzred approved these changes

2022-09-08 12:28 UTC, nalhadef commented on snippets/oadp-mtc-operator.adoc
> +//This snippet appears in the following assemblies:
This. needs :_content-type: SNIPPET.
[https://docs.google.com/document/d/1o4rrsgowUzGiVSH84Wg-Tt4DxmDXE_hg2H946NnXj6s/edit](https://docs.google.com/document/d/1o4rrsgowUzGiVSH84Wg-Tt4DxmDXE_hg2H946NnXj6s/edit)

2022-09-08 13:01 UTC, shubham-pampattiwar approved these changes

2022-09-13 16:18 UTC, merged

2022-09-13 16:18 UTC, jeana-redhat commented
/cherrypick enterprise-4.12

2022-09-13 16:19 UTC, jeana-redhat commented
/cherrypick enterprise-4.10

2022-09-13 16:19 UTC, jeana-redhat commented
/cherrypick enterprise-4.9