document template readiness
openshift/openshift-docs pull request #5007
Opened 2017-08-11 17:26 UTC by jim-minter

This will be a 3.7 feature.

@bparees @coreydaley ptal

2017-08-11 17:27 UTC, jim-minter commented
Please merge after https://github.com/openshift/origin/pull/15402

2017-08-11 18:48 UTC, bparees commented on dev_guide/templates.adoc
> +| Object reports Progressing condition as Failed
s/Failed/False/?

(same for the others?)

2017-08-16 18:20 UTC, bparees requested changes

2017-08-16 18:20 UTC, bparees commented on dev_guide/templates.adoc
> +instantiation will fail.
can you add a sample?  I worry people are not going to put the annotation in the right place otherwise.

2017-08-17 01:44 UTC, jim-minter commented on dev_guide/templates.adoc
> +instantiation will fail.
@bparees pushed.

2017-08-17 15:11 UTC, bparees commented
lgtm, and #15402 has merged.  @openshift/team-documentation ptal/merge.

2017-08-17 17:17 UTC, bmcelvee commented
Thanks, @jim-minter and @bparees! LGTM. I'll merge and make some minor edits in a follow-up PR.

2017-08-17 17:18 UTC, merged

2017-08-18 18:19 UTC, bmcelvee commented
[rev_history]
|xref:../dev_guide/templates.adoc#dev-guide-templates[Templates]
|Added xref:../dev_guide/templates.adoc#waiting-for-template-readiness[Waiting for Template Readiness] section.
%