Added a Benefits of Using the Overlay Graph Driver with SELinux section
openshift/openshift-docs pull request #5040
Opened 2017-08-17 20:11 UTC by ahardin-rh

https://trello.com/c/C1QKofOk/478-3-scale37-ocp-document-openshift-with-docker-overlay2selinux-enabled-performance-improvements

@jeremyeder Here's my first pass at expanding the documentation on Overlay + SELInux. PTAL. Thanks!

2017-08-18 14:58 UTC, jeremyeder commented
Thanks Ashley -- I'll need to tweak some of it. Will put some comments in soon.

2017-09-08 20:52 UTC, ahardin-rh commented
@jeremyeder bump

2017-09-14 17:04 UTC, jeremyeder requested changes

2017-09-14 17:04 UTC, jeremyeder commented on scaling_performance/optimizing_storage.adoc
> +Now that Overlay is in the upstream kernel and support for SELinux is extended,
This paragraph needs to be largely re-written, I will give it a shot.

2017-09-14 17:04 UTC, jeremyeder commented on scaling_performance/optimizing_storage.adoc
> +furthered with the addition of SELinux support.
How about this:

The default docker storage configuration on RHEL remains device-mapper.  As of Red Hat Enterprise Linux 7.2, overlay became a supported graph driver.  And, as of Red Hat Enterprise Linux 7.4, SELinux and the overlay2 graph driver became a supported combination.

The main advantage of the overlay filesystem is Linux page cache sharing among containers on the same node.  This attribute of overlay leads to reduced I/O during container startup (and thus faster container startup time by several hundred milliseconds), as well as reduced memory usage when similar images are running on a node.  Both side-effects lend themselves well towards many environments, especially those with the goal of optimizing for density and/or that have high container churn rate (such as a build farm), or those that have significant overlap in image content.

Page cache sharing is not possible with device-mapper due to how allocating thin-provisioned devices on a per-container basis.

2017-09-20 03:34 UTC, ahardin-rh commented
@jeremyeder Updated. Thanks!

@openshift/team-documentation Please peer review

2017-09-20 11:01 UTC, jeremyeder commented
@rhatdan @rhvgoyal can you please review this small doc paragraph?

2017-09-20 12:12 UTC, rhatdan commented
LGTM  (Only question I would have as a customer would why is not this the default?)

2017-09-20 12:24 UTC, jeremyeder commented
@rhatdan Thanks!  I didn't want to speculate, and I didn't feel mentioning Fedora 27's change to Overlay as default made sense in enterprise docs because it does not imply any *guarantee* that RHEL will change.  If you feel otherwise, can you propose a sentence or two to add to these docs?

2017-09-20 12:24 UTC, rhvgoyal commented on scaling_performance/optimizing_storage.adoc
> +containers on the same node. This attribute of Overlay leads to reduced
I would say mention page cache sharing happens only if containers are sharing any image. so something like, `page cache sharing among containers sharing image on same node`

2017-09-20 13:21 UTC, mburke5678 commented on scaling_performance/optimizing_storage.adoc
> +storage is recommended.
Is "root file systems storage" correct? Just sounds odd.
"root file system storage"?

2017-09-20 13:25 UTC, mburke5678 commented on scaling_performance/optimizing_storage.adoc
> +continues to be device-mapper. As of RHEL 7.2, Overlay became a supported graph
"continues to be a/the device-mapper"?
Also, do we need the hyphen in device-mapper?  Super quick Google search shows no hyphen.

2017-09-20 13:27 UTC, mburke5678 commented on scaling_performance/optimizing_storage.adoc
> +Page cache sharing is not possible with device-mapper because thin-provisioned
Same here "device-mapper"

2017-09-20 13:39 UTC, mburke5678 commented on scaling_performance/optimizing_storage.adoc
> +similar images are running on a node. Both side-effects lend themselves well to
"Both side-effects lend themselves well" seems too marketing-speak to me. Not sure what to replace it with. "These effects are beneficial in many environments..." ??

2017-09-20 13:39 UTC, mburke5678 commented
@ahardin-rh Couple of comments.

2017-09-20 21:26 UTC, ahardin-rh commented
Thanks, all! This is updated.

2017-09-21 10:09 UTC, rhatdan commented
@jeremyeder Perhaps.

As we monitor the use of Overlay as the containers storage backend,  we will consider moving RHEL to Overlay as default in future releases.

2017-09-21 14:58 UTC, ahardin-rh commented
@jeremyeder @rhatdan Thanks! Updated.

2017-09-21 15:08 UTC, jeremyeder commented
@ahardin-rh I don't see @rhatdan sentence in the PR?

2017-09-21 15:27 UTC, ahardin-rh commented
@jeremyeder @rhatdan I edited it a bit to avoid using "we": 
While the use of Overlay as the containers storage back-end is being monitored, moving RHEL to Overlay as the default in future releases is under consideration.

2017-09-21 15:39 UTC, jeremyeder commented
LGTM

2017-09-21 17:02 UTC, rhatdan commented
LGTM

2017-09-26 15:10 UTC, ahardin-rh commented
[rev_history]
|xref:../scaling_performance/optimizing_storage.adoc#scaling-performance-optimizing-storage[Optimizing Storage]
|Added a xref:../scaling_performance/optimizing_storage.adoc#benefits-of-using-the-overlay-graph-driver[Benefits of Using the Overlay Graph Driver with SELinux] section.
%

2017-09-26 15:11 UTC, merged