RHDEVDOCS-4346
openshift/openshift-docs pull request #50487
Opened 2022-09-15 15:46 UTC by libander

Version(s):

Issue:

Link to docs preview:

Additional information:

2022-09-29 17:24 UTC, periklis requested changes

2022-09-29 17:24 UTC, periklis commented on modules/cluster-logging-elasticsearch-audit.adoc
> +     type: "collectorForward"
The type is still `fluentdForward`. Probably a greedy search/replace editor mistake here.

2022-09-29 17:24 UTC, periklis commented on modules/cluster-logging-json-log-forwarding.adoc
> +  outputRefs: mycollector
I can't see the full CR here, but probably we want to keep `myFluentd`

2022-09-29 17:24 UTC, periklis commented on modules/cluster-logging-troubleshooting-loki-entry-out-of-order-errors.adoc
> +{collector_thread=\"flush_thread_0\", log_type=\"audit\"},\nentry with timestamp 2021-08-18 06:01:18.290229 +0000 UTC ignored, reason: 'entry out of order' for stream: {collector_thread="flush_thread
`fluentd_thread` is a label set by fluentd here, so you can't rename it to `collector_thread`

2022-09-29 17:24 UTC, periklis commented on modules/cluster-logging-updating-logging-to-5-0.adoc
> +"containerName": "collector-init"
I am not sure if renamed to collector anything beyond 5.4. So fluentd should still apply on 5.0 (cc @jcantrill )

2022-09-29 17:24 UTC, periklis commented on modules/cluster-logging-updating-logging-to-5-1.adoc
> +"containerName": "collector-init"
I am not sure if renamed to collector anything beyond 5.4. So fluentd should still apply on 5.1 (cc @jcantrill )

2022-09-29 17:52 UTC, jcantrill requested changes

2022-09-29 17:52 UTC, jcantrill commented on logging/config/cluster-logging-systemd.adoc
>  :_content-type: ASSEMBLY
I can not find where this is referenced.  It looks like a hold over from 3.11 from before CRIO when you could configure nodes to write logs to journal.  If you can not find any reference I would consider removing it.

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-about-collector.adoc
> +The logging collector is a daemon set that deploys pods to each {product-title} node. System and infrastructure logs are generated by journald log messages from the operating system, the container ru
The 'collector'

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-about-components.adoc
> +* collection - This is the component that collects logs from the cluster, formats them, and forwards them to the log store. The current implementation is the fluentd or vector collector.
implementations are...

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-about-components.adoc
> +* log store - This is where the logs are stored. The default implementation was Elasticsearch, which is now deprecated. Loki is in development as the new default store. You can use the default log st
@alanconway @periklis what do we want to say here.  loki is GA.  Elasticsearch is still the "default" implementation until probably logging CR 2.0.  Does the statement about optimization and testing still hold true for Loki

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-about-components.adoc
> +This document might refer to log store or Elasticsearch, visualization or Kibana, collection or collector, interchangeably, except where noted.
collection or fluentd, vector ?

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-about-crd.adoc
> +      type: "collector"
vector

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-about-crd.adoc
> +      type: "collector"
if this type remains "fluent" we can keep the ref to resources.limits, if we use vector we should consider removing

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-about-logstore.adoc
> +By default, {product-title} uses link:https://www.elastic.co/products/elasticsearch[Elasticsearch (ES)] to store log data. Optionally, you can use the log forwarding features to forward logs to exter
@alanconway @periklis what to say here?

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-about-logstore.adoc
> +Elasticsearch organizes the log data from collector into datastores, or _indices_, then subdivides each index into multiple pieces called _shards_, which it spreads across a set of Elasticsearch node
the collectors or collectors

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-about.adoc
> +collector, and Kibana in the `openshift-logging` namespace. The operators are
a collector... but seems like there is additional rewrite needed to include loki

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-collector-alerts.adoc
> +|`collectorHighErrorRate`
revert.  still named this

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-collector-alerts.adoc
> +|`collectorNodeDown`
revert

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-collector-alerts.adoc
> +|`collectorQueueLengthIncreasing`
revert

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-collector-limits.adoc
>  spec:
format is now:
```
collection:
  type:
  resources:
```

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-collector-log-forwarding-supported-plugins-5-2.adoc
> +| collectorForward
revert

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-collector-tolerations.adoc
> -      type: "fluentd"
format changes to 
```
collection:
  type:
  tolerations
```

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-collector-tuning.adoc
> -// Module included in the following assemblies:
this is all relevent to fluentd

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-configuring-image-about.adoc
> +collector_IMAGE=registry.redhat.io/openshift-logging/collector-rhel8:latest@sha256:ffdf79da7386871d2bc24cd937e02284b30f85a9979dc8c635fb73021cbca2f3 <1>
ther3e are multiple images here https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Ajcantrill%2Fcluster-logging-operator.git&branch=log2759_val&file=bundle%2Fmanifests%2Fclusterlogging.clusterserviceversion.yaml&editor=JetBrains&version=v1.2.2&start_row=413&start_col=25&end_row=413&end_col=25

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-configuring-node-selector.adoc
> +      type: "collector"
```
collection:
  type:
  nodeSelector:

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-cpu-memory.adoc
> -      type: "fluentd"
see previous ref

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-deploy-cli.adoc
>      logs:
api changed

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-deploy-console.adoc
>      logs:
api change

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-deploy-storage-considerations.adoc
> +collector ships any logs from *systemd journal* and */var/log/containers/* to Elasticsearch.
/var/log/pods/*

2022-09-29 17:52 UTC, jcantrill commented on modules/cluster-logging-deploying-about.adoc
>      logs:
api change

2022-09-30 02:47 UTC, anpingli commented on logging/cluster-logging-exported-fields.adoc
>  To search these fields from Elasticsearch and Kibana, use the full dotted field name when searching. For example, with an Elasticsearch */_search URL*, to look for a Kubernetes pod name, use `/_searc
_search?q=kubernetes.pod_name:name-of-my-pod`

2022-09-30 03:02 UTC, anpingli commented on modules/cluster-logging-about-crd.adoc
> +      type: "collector"
Type should be either fluentd or vector.

2022-09-30 03:05 UTC, anpingli commented on modules/cluster-logging-about-crd.adoc
> +      collector: {}
There isn't properties collector.
https://github.com/openshift/cluster-logging-operator/blob/release-5.5/bundle/manifests/logging.openshift.io_clusterloggings.yaml#L51

2022-09-30 03:06 UTC, anpingli commented on modules/cluster-logging-about-crd.adoc
> +      collector:
Same as above

2022-09-30 03:20 UTC, anpingli commented on modules/cluster-logging-clo-status.adoc
> +      collectorStatus:
It is fluentdStatus when use fluentd as collector.

2022-09-30 08:01 UTC, anpingli commented on modules/cluster-logging-clo-status.adoc
> +      collectorStatus:
Filed a ticket https://issues.redhat.com/browse/LOG-3126

2022-09-30 08:03 UTC, anpingli commented on modules/cluster-logging-clo-status.adoc
> +        Daemon Set:  collector
https://issues.redhat.com/browse/LOG-3126

2022-09-30 08:18 UTC, anpingli commented on modules/cluster-logging-collector-alerts.adoc
> +|`collectorHighErrorRate`
The alert names are still Fluent-xxxx. Filed a bug https://issues.redhat.com/browse/LOG-3127

2022-09-30 08:19 UTC, anpingli commented on modules/cluster-logging-collector-alerts.adoc
> +|`collectorNodeDown`
Same as above

2022-09-30 08:22 UTC, anpingli commented on modules/cluster-logging-collector-limits.adoc
> +      collector:
collector is not a  valid  properties. @jcantrill  Do we need a bug?
https://github.com/openshift/cluster-logging-operator/blob/master/bundle/manifests/logging.openshift.io_clusterloggings.yaml#L54

2022-09-30 08:39 UTC, anpingli commented on modules/cluster-logging-collector-log-forward-about.adoc
>  An output can be either:
LogForwarding API had been removed. I think we can drop this file and replace with ClusterLogForwarder

2022-09-30 08:45 UTC, anpingli commented on modules/cluster-logging-collector-log-forwarding-about.adoc
> +* `collectorForward`. An external log aggregation solution that supports collector. This option uses the collector *forward* protocols. The `fluentForward` output can use a TCP or TLS connection and
fluentdForward is fluentd only feature. Please roll back the changes

2022-09-30 08:46 UTC, anpingli commented on modules/cluster-logging-collector-log-forwarding-supported-plugins-5-1.adoc
> +| collectorForward
collectorForward -> fluentdForward

2022-09-30 08:47 UTC, anpingli commented on modules/cluster-logging-collector-log-forwarding-supported-plugins-5-1.adoc
> +a| collector 1.7.4
collector-> fluentd

2022-09-30 08:47 UTC, anpingli commented on modules/cluster-logging-collector-log-forwarding-supported-plugins-5-2.adoc
> +| collectorForward
collectorForward->fluentdForward

2022-09-30 08:48 UTC, anpingli commented on modules/cluster-logging-collector-tolerations.adoc
> +      type: "collector"
type should be either fluentd or vector, it can not be 'collector'

2022-09-30 08:51 UTC, anpingli commented
@libander  Lots of changes from fluentd-> collector are wrong. 
Please refer to CRD below to correct them.

https://github.com/openshift/cluster-logging-operator/blob/release-5.5/bundle/manifests/logging.openshift.io_clusterloggings.yaml
https://github.com/openshift/cluster-logging-operator/blob/release-5.5/bundle/manifests/logging.openshift.io_clusterlogforwarders.yaml

2022-09-30 19:33 UTC, libander commented on modules/cluster-logging-configuring-image-about.adoc
> +collector_IMAGE=registry.redhat.io/openshift-logging/collector-rhel8:latest@sha256:ffdf79da7386871d2bc24cd937e02284b30f85a9979dc8c635fb73021cbca2f3 <1>
reverted, text already states your list may differ based on config.

2022-10-04 16:14 UTC, jc-berger requested changes

2022-10-04 16:14 UTC, jc-berger commented on logging/cluster-logging-eventrouter.adoc
> +The Event Router collects events from all projects and writes them to `STDOUT`. The The collector collect those events and forwards them into the {product-title} log store, writing these events to th
Double `the`

`The collector collects those events and forwards them into...`

2022-10-04 16:14 UTC, jc-berger commented on modules/cluster-logging-about-collector.adoc
> +The logging collector is a daemon set that deploys pods to each {product-title} node. System and infrastructure logs are generated by journald log messages from the operating system, the container ru
Verb tense 

`The collector collects the logs from these sources and forwards them internally or externally as you configure in {product-title}.`

2022-10-04 16:14 UTC, jc-berger commented on modules/cluster-logging-eventrouter-about.adoc
> +The Event Router collects events from all projects and writes them to `STDOUT`. The collector collect those events and forwards them into the {product-title} Elasticsearch instance. Elasticsearch ind
Verb tense

`The collector collects those events and forwards them into the {product-title} Elasticsearch instance. Elasticsearch indexes the events to the `infra` index.`

2022-12-15 17:05 UTC, closed without merging