[RHACS] Update docs with correct variable info for wildcard Prometheus monitoring
openshift/openshift-docs pull request #50724
Opened 2022-09-22 15:15 UTC by kcarmichael08

Version(s):

Merge to:
- `rhacs-docs`

Cherry pick to:
- `rhacs-docs-3.72`
- `rhacs-docs-3.71`
- `rhacs-docs-3.70`

[Issue](https://issues.redhat.com/browse/ROX-12478)

Link to docs preview

2022-09-22 21:01 UTC, misberner requested changes

2022-09-22 21:01 UTC, misberner commented on modules/enable-monitoring-customize-port.adoc
> +* `0.0.0.0:<port_number>` to bind it to a wildcard address.
```suggestion
* `:<port_number>` to bind it to a wildcard address.
```
is what should be stated here, nothing else

2022-09-23 12:24 UTC, pneedle-rh commented
LGTM

2022-09-23 12:50 UTC, merged

2022-09-23 12:50 UTC, kalexand-rh commented
/cherrypick rhacs-docs-3.70

2022-09-23 12:50 UTC, kalexand-rh commented
/cherrypick rhacs-docs-3.71

2022-09-23 12:50 UTC, kalexand-rh commented
/cherrypick rhacs-docs-3.72