OSDOCS-3673.2-Private Link Warning
openshift/openshift-docs pull request #50823
Opened 2022-09-23 18:46 UTC by EricPonvelle

Version(s):
Enterprise-4.11

Issue:
Continuation of [OSDOCS-3673](https://issues.redhat.com/browse/OSDOCS-3673).

Link to docs preview:

Additional information:
Added an important note that PrivateLink clusters can only be created when the cluster is being configured. Not on an existing cluster.

2022-09-29 20:09 UTC, michaelryanmcneill requested changes

2022-09-29 20:09 UTC, michaelryanmcneill commented on modules/osd-aws-privatelink-about.adoc
> +You can only make a PrivateLink cluster at installation time. You cannot change a cluster to private after installation.
I think this needs to be changed from "You cannot change a cluster to private after installation." to "You cannot change a cluster to PrivateLink after installation."

2022-09-29 20:51 UTC, michaelryanmcneill approved these changes
LGTM

2022-09-30 13:15 UTC, EricPonvelle commented
@xueli181114 Can you give me QE approval on this PR?

2022-09-30 15:14 UTC, kelbrown20 commented
/label peer-review-in-progress

2022-09-30 15:29 UTC, kelbrown20 reviewed
Looks great! 
/lgtm

2022-09-30 15:33 UTC, kelbrown20 commented
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

2022-10-05 19:23 UTC, merged

2022-10-05 19:23 UTC, EricPonvelle commented
/cherrypick enterprise-4.11

2022-10-05 19:23 UTC, EricPonvelle commented
/cherrypick enterprise-4.12