RHDEVDOCS-4475: understanding odo
openshift/openshift-docs pull request #51136
Opened 2022-10-03 14:24 UTC by gabriel-rh

Version(s):
4.8+

Issue:
https://issues.redhat.com/browse/RHDEVDOCS-4475

Link to docs preview:

QE review:
- [ ] QE has approved this change.

2022-10-12 09:01 UTC, Preeticp reviewed
Looks great overall. Left a few suggestions, PTAL.

2022-10-12 09:01 UTC, Preeticp commented on cli_reference/developer_cli_odo/understanding-odo.adoc
> +- You do not want to learn Kubernetes and DevOps, to deploy to enterprise infrastructure.
How about: You want to deploy to enterprise infrastructure though you might not have a deep knowledge of Kubernetes and DevOps.

2022-10-13 10:51 UTC, Preeticp commented
/lgtm

2022-10-28 18:07 UTC, valaparthvi requested changes

2022-10-28 18:07 UTC, valaparthvi commented on cli_reference/developer_cli_odo/understanding-odo.adoc
> +`odo` focuses on application developers and cloud engineers, whereas `kubectl` and `oc`, the command line interface for {product-title}, are DevOps tools. The latter help you to deploy applications t
```suggestion
`odo` focuses on application developers and cloud engineers, whereas `kubectl` and `oc`, the command line interface for {product-title}, are DevOps tools. The latter help you to deploy applications to a cluster, and to support on-going maintenance, provided you already have a good knowledge of Kubernetes. `odo` does not support system administration or maintenance tasks for production clusters, but it does not require you to have a deep understanding of Kubernetes if you want to develop in the cluster.
```

2023-01-16 20:18 UTC, bergerhoffer commented
The `branch/enterprise-4.13` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.12. And any PR going into `main` must also target the latest version branch (enterprise-4.13).

If the update in your PR does NOT apply to version 4.13 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2023-01-17 06:25 UTC, valaparthvi commented
@gabriel-rh since we're going to un-publish odo docs from the upstream docs, do you think it might be time to close this PR and the others?

2023-05-16 18:04 UTC, kalexand-rh commented
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2023-07-16 08:01 UTC, closed without merging