[WIP] [OSDOCS-3889]: release note for NE-942
openshift/openshift-docs pull request #51186
Opened 2022-10-04 13:44 UTC by ShaunaDiaz

This is the WIP release note for https://issues.redhat.com/browse/OSDOCS-3889
Engineering story: https://issues.redhat.com/browse/NE-942: Add field in installer to get LB type for AWS

Version(s):
PR applies to : 4.12 only

Link to docs preview: 
https://51186--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-aws-load-balancer-customization
or
http://file.rdu.redhat.com/shdiaz/OSDOCS-3889-RN-v2/release_notes/ocp-4-12-release-notes.html#ocp-4-12-aws-load-balancer-customization

Additional information:
Docs content is not ready; xref if FPO (for placement only).
PR replaces 51174
WIP docs content here: https://github.com/openshift/openshift-docs/pull/51460

QE review:
- [ ] QE has approved this change.

2022-10-04 14:36 UTC, ShaunaDiaz commented
@miheer and @lihongan 
Please take a look and either approve or suggest revisions. Thank you!

2022-10-04 14:39 UTC, ShaunaDiaz commented
@bmcelvee If you'd like to take a look for the ROSA side.

2022-10-17 11:42 UTC, lihongan commented
/lgtm
Thank you!

2022-10-18 13:11 UTC, miheer requested changes

2022-10-18 13:13 UTC, miheer requested changes

2022-10-18 14:22 UTC, ShaunaDiaz commented
@miheer @Miciah Let's go back to the shorter RN text and I will footnote the table in the [docs](https://github.com/openshift/openshift-docs/pull/51460) entry.

2022-10-19 19:23 UTC, ShaunaDiaz commented
@miheer @Miciah PTAL and let me know if this PR looks good now.

2022-10-20 18:11 UTC, miheer commented
/lgtm

2022-10-20 19:17 UTC, ShaunaDiaz commented
/label peer-review-needed

2022-10-21 01:04 UTC, jboxman-rh reviewed
Not sure if it makes sense to clarify this a bit further. I'm not that familiar with AWS particulars.

2022-10-21 01:04 UTC, jboxman-rh commented on release_notes/ocp-4-12-release-notes.adoc
> +Beginning with {product-title} {product-version}, you can specify either NLB or Classic as a persistent load balancer type in AWS during installation. Afterwards, if an ingress controller is deleted,
Do we know what NLB is? I probably should known this, but I don't.

We're capitalizing Ingress Controller, although I don't recall why: https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/term_glossary.adoc#ingress-controller

This seems related to: https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support

Is `lbType` an object field?

2022-10-21 01:10 UTC, jboxman-rh commented
Looks like this describes the particulars: https://github.com/openshift/api/pull/1209/files

But that just tells it to create the Ingress Controller with the right LB type. So that API field is in the Ingress API somewhere.

2022-10-21 20:06 UTC, ShaunaDiaz commented
/label merge-review-needed

2022-10-21 20:13 UTC, merged