RHDEVDOCS-4476: key features in odo 3.0
openshift/openshift-docs pull request #51192
Opened 2022-10-04 15:00 UTC by gabriel-rh

Version(s):
4.8+

Issue:
https://issues.redhat.com/browse/RHDEVDOCS-4476

Link to docs preview:

QE review:
- [ ] QE has approved this change.

2022-10-12 09:27 UTC, Preeticp reviewed
Looks great, left some minor suggestions, PTAL.

2022-10-12 09:27 UTC, Preeticp commented on modules/odo-new-commands-30.adoc
> +The `odo dev` command allows you to code, build, run, debug and test your applications on the cluster in a continuous workflow. It combines the `odo push` and `odo watch` commands from `odo` version
Nit: Serial comma after debug.

2022-10-12 09:27 UTC, Preeticp commented on modules/odo-new-commands-30.adoc
> +Manual trigger to apply local changes on the cluster:: By default, `odo dev` automatically detects any changes in the directory, and synchronizes with the application running on the cluster. However,
Nit: ...it is possible to trigger this manually...

2022-10-12 09:27 UTC, Preeticp commented on modules/odo-new-commands-30.adoc
> +Interactive mode:: The `odo add binding` command improves the developer experience by providing an interactive mode that lists bindable service in all the namespaces, and providing a way to personali
s/service/services
s/ and providing a way to personalize/and the mechanism to personalize - ? Trying to avoid the repetition of - 'providing'

2022-10-12 09:27 UTC, Preeticp commented on modules/odo-new-commands-30.adoc
> +Detailed information about the Devfiles:: The `odo registry` command can provide detailed information about all the Devfiles, when you run it with `--details` flag.
nit: the `--details` flag.

2022-10-12 09:27 UTC, Preeticp commented on modules/odo-new-commands-30.adoc
> +The `odo list` command provides a better developer experience by outputting information about your application such as the mode it is running in, what tool and version is managing it, and the project
Principle of parallelism: s/what tool and version is managing it/the tool and version managing it

2022-10-12 09:27 UTC, Preeticp commented on modules/odo-new-commands-30.adoc
> += New commands in odo 3.0
I love the way the section is structured.
A suggestion: Can we change the title to make it feel like it belongs to the Understanding section? I find the emphasis on commands in the title a bit misleading. Just reading the title I thought it belonged to the CLI reference section. Also the section highlights the key features too though they are part of those commands.
How about Major highlights of odo 3.0?

2022-10-13 10:56 UTC, Preeticp commented
/lgtm

2022-10-28 18:18 UTC, valaparthvi reviewed
LGTM.

2022-10-28 18:28 UTC, valaparthvi requested changes
You are already using 'v2' and 'v3' in the [migration doc](https://51479--docspreview.netlify.app/openshift-enterprise/latest/cli_reference/developer_cli_odo/odo-migration-guide.html), it would be nice if you can use the same in this doc instead of 'version 2' and 'version 3'.

2022-10-28 18:28 UTC, valaparthvi commented on modules/odo-new-commands-30.adoc
> +The `odo dev` command allows you to code, build, run, debug, and test your applications on the cluster in a continuous workflow. It combines the `odo push` and `odo watch` commands from `odo` version
```suggestion
The `odo dev` command allows you to code, build, run, debug, and test your applications on the cluster in a continuous workflow. It combines the `odo push` and `odo watch` commands from `odo` v2 into a single command.
```

2022-10-28 18:28 UTC, valaparthvi commented on modules/odo-new-commands-30.adoc
> +The version 2 `odo link` command links an application to another application and any Operator-backed service. However, `odo` version 3 currently only supports connecting to services backed by Operato
```suggestion
Work without a running application:: Compared to v2, the `odo add binding` command does not require the application to be running on the cluster, making it even faster.

Only supports bindable Operators::
The `odo link` command of v2 links an application to another application and any Operator-backed service. However, `odo` v3 currently only supports connecting to services backed by Operators that are considered bindable by the Service Binding Operator.
```

2023-01-16 20:16 UTC, bergerhoffer commented
The `branch/enterprise-4.13` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.12. And any PR going into `main` must also target the latest version branch (enterprise-4.13).

If the update in your PR does NOT apply to version 4.13 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2023-04-25 15:38 UTC, kalexand-rh commented
Only versions 4.10+ are still in maintenance. I am removing labels from earlier versions from this PR.

2023-05-16 18:04 UTC, kalexand-rh commented
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2023-07-16 08:01 UTC, closed without merging