Agent-61: Adds FIPS compliance for Agent-based Installer
openshift/openshift-docs pull request #52701
Opened 2022-11-10 16:31 UTC by Amrita42

- Applies to main and 4.12
- [Agent-61](https://issues.redhat.com/browse/AGENT-61)
- [Preview](http://file.del.redhat.com/asakthiv/Agent-61/installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.html#agent-installer-fips-compliance_preparing-to-install-with-agent-based-installer) Requires VPN
- @celebdor ptal Additionally note that in [Sample install-config.yaml](https://52701--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.html#installation-bare-metal-agent-installer-config-yaml_preparing-to-install-with-agent-based-installer) callout 12 defines FIPS.

2022-11-10 17:24 UTC, Amrita42 commented on modules/agent-installer-fips-compliance.adoc
> +During a cluster deployment, the FIPS change is applied when the Red Hat Enterprise Linux CoreOS (RHCOS) machines are deployed in your cluster. For Red Hat Enterprise Linux (RHEL) machines, you must
@celebdor I am not sure if this is applicable to the Agent-based Install?

2022-11-11 10:29 UTC, celebdor commented
/lgtm

2022-11-14 05:25 UTC, Amrita42 commented
@mhanss can you please review . Thanks.

2022-11-14 12:40 UTC, mhanss commented
/lgtm

2022-11-14 12:54 UTC, Amrita42 commented
/label peer-review-needed

2022-11-14 14:48 UTC, celebdor commented
/lgtm

2022-11-14 15:06 UTC, sheriff-rh requested changes
I have a few comments, please let me know if you have any questions!

2022-11-14 15:06 UTC, sheriff-rh commented
/remove-label peer-review-in-progress
/label peer-review-done

2022-11-14 15:21 UTC, Amrita42 commented on modules/agent-installer-fips-compliance.adoc
> +The use of FIPS Validated / Modules in Process cryptographic libraries is only supported on {product-title} deployments on the `x86_64` architecture.
@sheriff-rh the content has been re-used from the existing module/content! >> agent-installer-fips-compliance.adoc.

2022-11-14 15:23 UTC, Amrita42 commented on modules/agent-installer-fips-compliance.adoc
> +For many {product-title} customers, regulatory readiness, or compliance, on
Reuse of existing content from security/container_security/security-compliance.adoc

2022-11-14 16:37 UTC, Amrita42 commented
/label merge-review-needed

2022-11-14 19:43 UTC, maxwelldb reviewed
@Amrita42 Quick thing before merge--ISG requires that most acronyms be defined at first use. I only see "FIPS" here. Do you think it is so common that it doesn't need to be expanded, e.g. HTML, or should it appear in full at the beginning of each module?

2022-11-14 19:51 UTC, Amrita42 commented
@maxwelldb good question. Come to think of it , FIPS is not common. Give me 10 mins, I will make the change

2022-11-14 20:08 UTC, Amrita42 commented
Done @maxwelldb (netlify preview now doesnt seem to work).

2022-11-15 11:06 UTC, celebdor commented
/lgtm

2022-11-15 13:42 UTC, maxwelldb approved these changes

2022-11-15 13:43 UTC, merged

2022-11-15 13:43 UTC, maxwelldb commented
/cherry-pick enterprise-4.12

2022-11-23 10:50 UTC, Amrita42 commented
@maxwelldb  https://github.com/openshift/openshift-docs/pull/53128