[WIP] SRVCOM-2100 install serverless operator using cli
openshift/openshift-docs pull request #52908
Opened 2022-11-16 19:07 UTC by gabriel-rh

Version(s):
4.8+

Issue:
https://issues.redhat.com/browse/SRVCOM-2100

Link to docs preview:

QE review:
- [ ] QE has approved this change.

2022-11-29 08:38 UTC, skonto commented
LGTM

2022-11-29 11:00 UTC, cardil requested changes
Some minor requests.

2022-11-29 11:00 UTC, cardil commented on modules/serverless-install-cli.adoc
> +<2> Name of the Operator to subscribe to.
This is always `serverless-operator`.

2022-11-29 15:59 UTC, gabriel-rh commented
> Some minor requests.

@cardil I have made the changes suggested and updated the preview here:

https://52908--docspreview.netlify.app/openshift-enterprise/latest/serverless/install/install-serverless-operator.html#serverless-install-cli_install-serverless-operator

2022-12-08 16:25 UTC, jc-berger approved these changes
/lgtm

2022-12-08 16:30 UTC, cardil approved these changes
/lgtm

from QE

2022-12-13 15:18 UTC, merged

2022-12-13 15:19 UTC, gabriel-rh commented
/cherry-pick enterprise-4.12

2022-12-13 15:19 UTC, gabriel-rh commented
/cherry-pick enterprise-4.10

2022-12-13 15:19 UTC, gabriel-rh commented
/cherry-pick enterprise-4.9

2022-12-13 15:19 UTC, gabriel-rh commented
/cherry-pick enterprise-4.8