OSDOCS#4551: Add the common terms for networking book
openshift/openshift-docs pull request #52972
Opened 2022-11-18 06:57 UTC by xenolinux

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2022-11-18 13:59 UTC, sheriff-rh commented
/label peer-review-in-progress
/remove-label peer-review-needed

2022-11-18 14:00 UTC, sheriff-rh commented
Please add the build preview to the top:
https://52972--docspreview.netlify.app/openshift-enterprise/latest/networking/understanding-networking.html#nw-networking-glossary-terms_understanding-networking

2022-11-18 15:05 UTC, sheriff-rh requested changes
Overall this content is very good and was much needed. 

Many of my comments are proofreading-related, such as sentence capitalization or missing periods. Please also remember to include a build preview in the description. 

To improve this content at a later time, consider moving it to it's own assembly. You can `xref::` to  modules in the documentation where customers can learn more about a topic. 

It's possible some of these terms may not be available in all distributions, which could cause confusion for some customers. 

In all - this is a much needed improvement to our docs, thank you!

2022-11-18 15:06 UTC, sheriff-rh commented
/label peer-review-done
/remove-label peer-review-in-progress

2022-11-21 09:34 UTC, xenolinux commented on modules/nw-networking-glossary-terms.adoc
> +Single Root I/O Virtualization (SR-IOV) Network Operator:: The Single Root I/O Virtualization (SR-IOV) Network Operator manages the SR-IOV network devices and network attachments in your cluster.
acked

2022-11-21 09:34 UTC, xenolinux commented on modules/nw-networking-glossary-terms.adoc
> +The PTP Operator creates and manages the linuxptp services.
acked

2022-11-21 09:34 UTC, xenolinux commented on modules/nw-networking-glossary-terms.adoc
> +{product-title} uses load balancer for communicating from outside the cluster with services running in the cluster.
acked

2022-11-21 09:34 UTC, xenolinux commented on modules/nw-networking-glossary-terms.adoc
> +domain is a DNS name serviced by the Ingress Controller.
acked

2022-11-21 09:34 UTC, xenolinux commented on modules/nw-networking-glossary-terms.adoc
> +Certificates::
acked

2022-11-21 09:34 UTC, xenolinux commented on modules/nw-networking-glossary-terms.adoc
> +The AWS Load Balancer (ALB) Operator deploys and manages an instance of the aws-load-balancer-controller.
acked

2022-11-21 09:34 UTC, xenolinux commented on modules/nw-networking-glossary-terms.adoc
> +This glossary defines common terms that are used in the architecture content. These terms help you understand {product-title} architecture effectively
acked

2022-11-21 09:34 UTC, xenolinux commented on modules/nw-networking-glossary-terms.adoc
> += Common terms
acked

2022-11-21 13:19 UTC, bergerhoffer commented
/label merge-review-in-progress

2022-11-21 13:36 UTC, bergerhoffer reviewed
Just a few minor things if you wouldn't mind taking a look before I merge?

2022-11-21 13:36 UTC, bergerhoffer commented on modules/nw-networking-glossary-terms.adoc
> +Load balancers::
L should be lowercase here

2022-11-21 13:45 UTC, xenolinux commented on modules/nw-networking-glossary-terms.adoc
> +Network information of {product-title} cluster.
acked

2022-11-21 13:45 UTC, xenolinux commented on modules/nw-networking-glossary-terms.adoc
> +As a cluster administrator, you can add the MetalLB Operator to your cluster so that when a service of type LoadBalancer is added to the cluster, MetalLB can add an external IP address for the servic
acked

2022-11-21 13:45 UTC, xenolinux commented on modules/nw-networking-glossary-terms.adoc
> +Load balancers::
acked

2022-11-21 13:46 UTC, xenolinux commented
> Just a few minor things if you wouldn't mind taking a look before I merge?

@bergerhoffer Thanks for the review! I addressed the changes

2022-11-21 16:21 UTC, bergerhoffer commented
Thanks, LGTM now! Merging

2022-11-21 16:21 UTC, merged

2022-11-21 16:21 UTC, bergerhoffer commented
/cherrypick enterprise-4.12

2022-11-21 16:21 UTC, bergerhoffer commented
/cherrypick enterprise-4.11

2022-11-21 16:21 UTC, bergerhoffer commented
/cherrypick enterprise-4.10

2022-11-21 16:21 UTC, bergerhoffer commented
/cherrypick enterprise-4.9

2022-11-21 16:21 UTC, bergerhoffer commented
/cherrypick enterprise-4.8