Bug#1493091 - Add addition information about F5 router
openshift/openshift-docs pull request #5314
Opened 2017-09-21 02:45 UTC by gaurav-nelson

For https://bugzilla.redhat.com/show_bug.cgi?id=1493091

- Highlighted not supported section and added more points under it

2017-09-21 07:05 UTC, lihongan commented
@rajatchopra @knobunc  please also help to take a look.

2017-09-27 00:26 UTC, gaurav-nelson commented
@rajatchopra @knobunc bump

2017-10-16 17:11 UTC, rajatchopra requested changes

2017-10-16 17:11 UTC, rajatchopra commented on install_config/router/f5_router.adoc
> +* Re-encrypt routes.
Re-encrypt routes are supported.

2017-10-16 17:11 UTC, rajatchopra commented on install_config/router/f5_router.adoc
> +* Certificates specifically configured for particular routes.
Not sure what this means. We do take specific certs for edge/re-encrypt routes.

2017-10-19 01:45 UTC, gaurav-nelson commented
@rajatchopra @knobunc 
It would be great if I can get list of things that are supported and not supported.

2017-10-19 16:53 UTC, rajatchopra commented
This PR looks good. Coming  up with a comprehensive comparison will take dedicated effort. Get this merged, I say because this information is correct. Eventually we want container-connector from F5 to take over anyway.

2017-10-31 05:31 UTC, gaurav-nelson commented
@openshift/team-documentation PTAL

2017-10-31 05:39 UTC, gaurav-nelson commented
minor changes no revision history needed

2017-10-31 15:56 UTC, mburke5678 commented on install_config/router/f5_router.adoc
> +* Wildcard routes together with re-encrypt - you must supply a certificate and key in the route. And if you provide a certificate, a key and a CA, the CA is never used.
Should this be _Wildcard routes together with re-encryption_? Seems like something is missing here. The [3.6 release notes](https://github.com/openshift/openshift-docs/blob/f6a965f6af48b852f838f12160ca42aff3ffb5c7/release_notes/ocp_3_6_release_notes.adoc) talk about _re-encrypt routes_.

2017-10-31 15:58 UTC, mburke5678 commented on install_config/router/f5_router.adoc
> +* Wildcard routes together with re-encrypt - you must supply a certificate and key in the route. And if you provide a certificate, a key and a CA, the CA is never used.
s/a certificate, a key and a CA/a certificate, a key, and a CA ??

2017-10-31 15:58 UTC, mburke5678 commented
@gaurav-nelson A few nits. LGTM

2017-11-01 01:22 UTC, gaurav-nelson commented
Thanks @mburke5678 

minor updates no rev history needed.

2017-11-15 03:42 UTC, merged