encryption restoration details
openshift/openshift-docs pull request #53152
Opened 2022-11-23 22:08 UTC by asme30

Version(s): 4.3+

Issue:  More details about backup/restore of encrypted etcd

Link to docs preview:  https://docs.openshift.com/container-platform/4.11/security/encrypting-etcd.html

QE review:
- [ ] QE has approved this change.

Additional information:

2022-11-23 22:28 UTC, EmilyM1 commented
@lahinson and @tmalove would you mind taking a look? 
This is to handle the case of encryption on restore for etcd.

2022-11-28 05:24 UTC, tmalove commented on modules/about-etcd-encryption.adoc
> +During etcd backup, if etcd encryption is enabled then static_kuberesources_<datetimestamp>.tar.gz: file also contains the encryption keys for the etcd snapshot and it is recommended to store this fi
```suggestion
If etcd encryption is enabled during a backup, the static_kuberesources_<datetimestamp>.tar.gz: file contains the encryption keys for the etcd snapshot. You should store this file separately from the etcd snapshot for security reasons. However, this file is required to restore a previous state of etcd from the respective etcd snapshot.
```

2022-11-28 15:04 UTC, lahinson commented
@EmilyM1 I added a couple of comments. Otherwise, LGTM!

2022-11-28 15:50 UTC, tmalove approved these changes
>

2022-11-30 17:51 UTC, EmilyM1 commented
/lgtm

2022-11-30 22:28 UTC, asme30 commented
Thank you teams @lahinson  verified all the changes and it looks good

2022-12-01 15:42 UTC, lahinson commented
Great, thanks @asme30! Can you incorporate the edits, or is that something that @tmalove and I need to help with?

2022-12-01 16:30 UTC, asme30 commented
@lahinson  and @tmalove Please guide me with this.

2022-12-06 19:19 UTC, lahinson commented on modules/about-etcd-encryption.adoc
> +If etcd encryption is enabled during a backup, the `__static_kuberesources_<datetimestamp>.tar.gz: file__` contains the encryption keys for the etcd snapshot. You should store this file separately fr
@asme30 To keep the text aligned with IBM and Red Hat style guidance, please update the second sentence from `You should store this file separately...` to `Store this file separately...`. After that change has been made, I can help you move this forward to be reviewed and merged by the OpenShift docs team. Thanks!

2022-12-06 19:19 UTC, lahinson requested changes
See my comment about line 26.

2022-12-13 12:57 UTC, asme30 commented
Hey @lahinson and @tmalove  Added recommended changes please review and let me know.

2022-12-13 18:04 UTC, lahinson commented
@asme30 Looks good. Thanks!

@geliu2016 PTAL at this small change to the docs when you can.

2022-12-14 06:22 UTC, gangwgr commented on modules/about-etcd-encryption.adoc
>  Keep in mind that etcd encryption only encrypts values, not keys. This means that resource types, namespaces, and object names are unencrypted.
@geliu2016 I'm not sure, will check with @wangke19 and dev

2022-12-15 03:41 UTC, gangwgr commented on modules/about-etcd-encryption.adoc
>  Keep in mind that etcd encryption only encrypts values, not keys. This means that resource types, namespaces, and object names are unencrypted.
@lahinson Please find the details in slack https://coreos.slack.com/archives/CC3CZCQHM/p1670999032684989.
What other info you need?

2022-12-15 03:42 UTC, gangwgr commented
@geliu2016 @lahinson Doc looks find to me.

2022-12-15 14:02 UTC, lahinson commented
Thanks, @geliu2016 @gangwgr!

2022-12-15 14:02 UTC, lahinson approved these changes

2022-12-15 14:04 UTC, lahinson commented
@asme30 When you can, please update the first comment in this PR to indicate that QE has approved this change.

2022-12-15 14:05 UTC, lahinson commented
/label peer-review-needed

Hi peer review squad - This XS update to the etcd docs has been reviewed and approved by engineering and QE. PTAL. Thanks!

2022-12-15 14:45 UTC, kelbrown20 commented
/label peer-review-in-progress

2022-12-15 15:07 UTC, kelbrown20 reviewed
Hey Laura! Great work! Just some minor suggestions to consider, otherwise this LGTM!

2022-12-15 15:07 UTC, kelbrown20 commented on modules/about-etcd-encryption.adoc
> +Keep in mind that etcd encryption only encrypts values, not keys. Resource types, namespaces, and object names are unencrypted.
I don't think that the "Keep in mind" part is really necessary. This statement works on its own 
```suggestion
Etcd encryption only encrypts values, not keys. Resource types, namespaces, and object names are unencrypted.
```

2022-12-15 15:07 UTC, kelbrown20 commented on modules/about-etcd-encryption.adoc
> +If etcd encryption is enabled during a backup, the `__static_kuberesources_<datetimestamp>.tar.gz: file__` contains the encryption keys for the etcd snapshot. Store this file separately from the etcd
Up to you! 
```suggestion
If etcd encryption is enabled during a backup, the `__static_kuberesources_<datetimestamp>.tar.gz: file__` contains the encryption keys for the etcd snapshot. For security reasons, store this file separately from the etcd snapshot. However, this file is required to restore a previous state of etcd from the respective etcd snapshot.
```

2022-12-15 15:08 UTC, kelbrown20 commented
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

2022-12-15 15:11 UTC, lahinson commented
Thanks, @kelbrown20! Good suggestions. @asme30 Please see the two comments from Kelly and make the updates. After that, we can move this forward to be merged.

2022-12-15 17:58 UTC, lahinson commented
LGTM!

2022-12-15 20:02 UTC, jboxman-rh reviewed
I have a question before merging, thanks!

2022-12-15 20:02 UTC, jboxman-rh commented on modules/about-etcd-encryption.adoc
> +If etcd encryption is enabled during a backup, the `__static_kuberesources_<datetimestamp>.tar.gz: file__` contains the encryption keys for the etcd snapshot. For security reasons, store this file se
@asme30 

I hate to dig this up again, but this still looks wrong. I've never seen a filename of the form: static_kuberesources_<datetimestamp>.tar.gz: file, so I'm not sure this is correct? Or is it: static_kuberesources_<datetimestamp>.tar.gz?

2022-12-15 20:02 UTC, jboxman-rh commented on modules/about-etcd-encryption.adoc
> +If etcd encryption is enabled during a backup, the `__static_kuberesources_<datetimestamp>.tar.gz: file__` contains the encryption keys for the etcd snapshot. For security reasons, store this file se
```suggestion
If etcd encryption is enabled during a backup, the `__static_kuberesources_<datetimestamp>.tar.gz__` file contains the encryption keys for the etcd snapshot. For security reasons, store this file separately from the etcd snapshot. However, this file is required to restore a previous state of etcd from the respective etcd snapshot.
```

2022-12-15 21:18 UTC, asme30 commented
@jboxman-rh made suggested changes. PTAL

2022-12-15 22:59 UTC, merged

2022-12-15 22:59 UTC, jboxman-rh commented
/cherry-pick enterprise-4.12

2022-12-16 00:26 UTC, jboxman-rh commented
/cherry-pick enterprise-4.11

2022-12-16 00:26 UTC, jboxman-rh commented
/cherry-pick enterprise-4.10

2022-12-16 03:10 UTC, jboxman-rh commented
/cherry-pick enterprise-4.9

2022-12-16 03:11 UTC, jboxman-rh commented
/cherry-pick enterprise-4.8