OSDOCS-3160: Console optional capability
openshift/openshift-docs pull request #53899
Opened 2022-12-15 16:29 UTC by opayne1

OSDOCS-3160: Console optional capability

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-3922

Link to docs preview:

QE review:
- [ ] QE has approved this change.

2022-12-15 18:40 UTC, bscott-rh requested changes

2022-12-15 18:40 UTC, bscott-rh commented on modules/console-operator.adoc
>  = Console Operator
```suggestion
ifdef::operator-ref[= Console Operator]
ifdef::cluster-caps[= Web console capability]
```
similar to Michael's PR, the title will show up slightly differently in the Operator reference page vs. the Cluster capabilities page(s).

2022-12-15 18:40 UTC, bscott-rh commented on modules/console-operator.adoc
```suggestion
ifdef::cluster-caps[]

Add any relevant information here about what side-effects or considerations the customer should consider if they disable this capability during installation.

endif::cluster-caps[]
```

Suggestion for additional content

2022-12-16 12:43 UTC, jhadvig commented
/lgtm

2022-12-16 13:40 UTC, opayne1 commented
Removed the` :cluster-caps:` attribute

2022-12-16 14:10 UTC, opayne1 commented
Hi @yanpzhan could you provide a QE review for this PR? Thank you!

2022-12-16 15:38 UTC, jhadvig commented
/lgtm

2022-12-20 14:18 UTC, yanpzhan commented
LGTM from QE side, thanks!

2022-12-20 15:09 UTC, jeana-redhat reviewed
Just tried some tweaks to avoid future tense, but idk it might sound too awkward that way - I leave it to your preference :)

Do you think it might help to add an _Additional resources_ follow-on to this module with a link out to the _Cluster capabilities_ page?

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2022-12-20 15:09 UTC, jeana-redhat commented on modules/console-operator.adoc
> +The Console Operator installs and maintains the {product-title} web console on a cluster. The Console Operator is installed by default and will automatically maintain a console.
```suggestion
The Console Operator installs and maintains the {product-title} web console on a cluster. The Console Operator is installed by default and automatically maintains a console.
```

2022-12-20 15:09 UTC, jeana-redhat commented on modules/console-operator.adoc
> +The Console Operator is an optional cluster capability that can be disabled by cluster administrators during installation. If you disable the Console Operator at installation, you will still have a s
```suggestion
The Console Operator is an optional cluster capability that can be disabled by cluster administrators during installation. If you disable the Console Operator at installation, your cluster is still supported and upgradable. For more information about optional cluster capabilities, see "Cluster capabilities" in _Post-installation configuration_.
```

2022-12-21 13:47 UTC, merged

2022-12-21 13:47 UTC, mburke5678 commented
/cherrypick enterprise-4.12