CNV-20148: VM export RN
openshift/openshift-docs pull request #54125
Opened 2022-12-26 12:51 UTC by apinnick

Version(s): 4.12

Issue: CNV-20148

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information: Links to be added after docs PR is merged.

2023-01-03 18:15 UTC, kelbrown20 commented
/label peer-review-in-progress

2023-01-03 18:32 UTC, kelbrown20 reviewed
/lgtm

2023-01-03 18:33 UTC, kelbrown20 commented
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

2023-01-05 14:56 UTC, jpeimer requested changes

2023-01-05 15:03 UTC, kgoldbla approved these changes
lgtm

2023-01-05 15:29 UTC, awels commented on virt/virt-4-12-release-notes.adoc
> +* You can export and download a volume from a virtual machine (VM), a VM snapshot, or a persistent volume claim (PVC) for forensic analysis by using the `virtctl vmexport` command or by creating a `V
Yeah one of the main use cases is exporting the volume to another cluster (or some external storage). The forensic analysis IMO is a secondary use case. I like the recommended wording

2023-01-05 16:03 UTC, apinnick commented on virt/virt-4-12-release-notes.adoc
> +* You can export and download a volume from a virtual machine (VM), a VM snapshot, or a persistent volume claim (PVC) for forensic analysis by using the `virtctl vmexport` command or by creating a `V
Great. I'll add that.

2023-01-05 16:03 UTC, apinnick commented on virt/virt-4-12-release-notes.adoc
> +//CNV-20148 VM export - links to be added after doc PR is merged.
Yes, it's merged. Thanks for the reminder. I forgot to add the link. Will fix.

2023-01-08 10:12 UTC, merged