CNV-19923: 4.11 updates to Reserving PVC space for file system overhead
openshift/openshift-docs pull request #54363
Opened 2023-01-09 15:27 UTC by sabrinajess

Version(s): 4.11+

Issue: CNV-19923

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-01-10 21:41 UTC, maya-r commented on modules/virt-overriding-default-fs-overhead-value.adoc
>  <2> The file system overhead percentage for the specified storage class. For example, `mystorageclass: "0.04"` changes the default overhead value for PVCs in the `mystorageclass` storage class to 4%.
I think it's still not clear from the wording that the per-storage class value overrides the global value.
(otherwise looks good to me)

2023-01-14 19:11 UTC, maya-r commented
lgtm

2023-01-15 11:32 UTC, kgoldbla requested changes

2023-01-15 11:32 UTC, kgoldbla commented on modules/virt-overriding-default-fs-overhead-value.adoc
> +$ oc get cdiconfig -o yaml
You can also more specifically verify your changes with:
oc get cdiconfig -o jsonpath='{.items..status.filesystemOverhead}'
The output looks like this:
{"global":"0.055","storageClass":{"csi-manila-ceph":"0.055","hostpath-csi-basic":"0.055","hostpath-csi-pvc-block":"0.055","local-block-hpp":"0.055","local-block-ocs":"0.055","nfs":"0.055","ocs-storagecluster-ceph-rbd":"0.055","ocs-storagecluster-ceph-rgw":"0.055","ocs-storagecluster-cephfs":"0.055","standard-csi":"0.055"}}

2023-01-18 19:10 UTC, kcarmichael08 reviewed
I had a few suggestions but this looks good to me!

2023-01-18 19:10 UTC, kcarmichael08 commented
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2023-01-31 16:16 UTC, sabrinajess commented
/label merge-review-requested

2023-01-31 16:23 UTC, sabrinajess commented
/label merge-review-needed

2023-01-31 20:46 UTC, mburke5678 commented
@sabrinajess What is the [ocp-preview file](https://github.com/openshift/openshift-docs/pull/54363/files#diff-8e24f1e4ddaa5b05d68130565297dfc9340624899ca43c412e223a9ca975863b) (that doesn't seem to be a file)?

2023-02-03 16:16 UTC, sabrinajess commented
This PR has gone off the rails with hitchhikers. Closing to easily create a new, clean PR. New PR here: https://github.com/openshift/openshift-docs/pull/55556

2023-02-03 16:16 UTC, closed without merging