[OSDOCS-4767] Add Kuryr deprecation module to some assemblies
openshift/openshift-docs pull request #54414
Opened 2023-01-10 15:44 UTC by maxwelldb

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-01-10 16:01 UTC, dulek requested changes

2023-01-10 16:16 UTC, maxwelldb commented on networking/load-balancing-openstack.adoc
> +
@dulek So, it seems like I have some play with the banner as long as it's thoughtful. 

What do you mean by "that section" specifically, and is it different from "the warning"? 

Like, some part of the deprecated-feature banner is at the top of the page, and the rest is elsewhere, or the banner stays as-is and there are smaller notes placed throughout the page?

2023-01-10 16:53 UTC, dulek requested changes

2023-01-10 16:53 UTC, dulek commented on networking/load-balancing-openstack.adoc
> +
"That section" is `nw-osp-configuring-external-load-balancer.adoc`. This one is independent from Kuryr, so shouldn't be subject of the deprecation. Putting the banner at the top suggests it applies to all the content on this page, which won't be true.

2023-01-10 17:13 UTC, maxwelldb commented on networking/load-balancing-openstack.adoc
> +
Ah, got it. 

I now have permission to change how we do deprecation content to make this easier. Will need to make some changes in another PR and the incorporate them here. NBD, but will take an hour or so.

2023-01-10 18:28 UTC, maxwelldb commented on networking/load-balancing-openstack.adoc
> +
@dulek Getting this merged will allow more freedom here: https://github.com/openshift/openshift-docs/pull/54434

Shouldn't take long.

2023-01-11 20:49 UTC, maxwelldb commented
@dulek This shows the deprecation snippet inserted into some of the Kuryr sections: https://54414--docspreview.netlify.app/openshift-enterprise/latest/networking/load-balancing-openstack.html

Thoughts?

2023-01-12 10:07 UTC, dulek commented
Looks good, thanks!
/lgtm

2023-01-13 09:50 UTC, eurijon commented
lgtm

2023-01-13 13:17 UTC, mjpytlak reviewed
Peer review LGTM @maxwelldb

2023-01-13 13:28 UTC, maxwelldb commented
Thanks

2023-01-13 15:20 UTC, merged

2023-01-13 15:21 UTC, maxwelldb commented
/cherry-pick enterprise-4.12