Add release notes for SBO v1.3.3
openshift/openshift-docs pull request #55095
Opened 2023-01-24 08:08 UTC by pmacik

Signed-off-by: Pavel Macík <pavel.macik@gmail.com>

Version(s):
* 4.11
* 4.12

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-03-02 15:19 UTC, Srivaralakshmi requested changes
@pmacik Excellent work! Enjoyed reviewing. PTAL at my suggestions. Thanks!

2023-03-02 15:19 UTC, Srivaralakshmi commented on modules/sbo-release-notes-1-3-3.adoc
> +* Before this update, a security vulnerability `CVE-2022-41717` was noted for {servicebinding-title}. This update fixes `CVE-2022-41717` error and updates the `golang.org/x/net` package from v0.0.0-2
```suggestion
* Before this update, a security vulnerability `CVE-2022-41717` was noted for {servicebinding-title}. This update fixes the `CVE-2022-41717` error and updates the `golang.org/x/net` package from v0.0.0-20220906165146-f3363e06e74c to v0.4.0. link:https://issues.redhat.com/browse/APPSVC-1256[APPSVC-1256]
```

2023-03-02 15:19 UTC, Srivaralakshmi commented on modules/sbo-release-notes-1-3-3.adoc
> +* Before this update Provisioned Services were only detected if the respective resource had "servicebinding.io/provisioned-service: true" annotation set while other Provisioned Services were missed.
```suggestion
* Before this update, Provisioned Services were only detected if the respective resource had the "servicebinding.io/provisioned-service: true" annotation set while other Provisioned Services were missed. With this update, the detection mechanism identifies all Provisioned Services correctly based on the "status.binding.name" attribute. link:https://issues.redhat.com/browse/APPSVC-1204[APPSVC-1204]
```

2023-03-06 09:22 UTC, Srivaralakshmi commented
@pmacik Thanks for the changes! LGTM.

2023-03-06 09:22 UTC, Srivaralakshmi commented
/lgtm

2023-03-06 09:22 UTC, Srivaralakshmi approved these changes
@pmacik Approved!

2023-03-07 09:48 UTC, pmacik commented
@Srivaralakshmi I've squashed the commits. PTAL

2023-03-07 10:25 UTC, merged

2023-03-07 10:25 UTC, gabriel-rh commented
/cherry-pick enterprise-4.12

2023-03-07 10:25 UTC, gabriel-rh commented
/cherry-pick enterprise-4.11

2023-03-07 14:54 UTC, gabriel-rh commented
/cherry-pick enterprise-4.13