BZ2151324: Updated namespace requirement for live migration
openshift/openshift-docs pull request #55168
Opened 2023-01-25 17:18 UTC by sjhala-ccs

Version(s): 4.11+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2151324
CNV-23200

Link to docs preview:

QE review:
- [ ] QE has approved this change.

2023-01-25 20:18 UTC, yossisegev requested changes

2023-01-25 20:36 UTC, sjhala-ccs commented on modules/virt-configuring-secondary-network-vm-live-migration.adoc
> +<4> The name of the CNI plugin that provides the network for this network attachment definition.
Thanks for catching this, fixing it now

2023-01-25 21:08 UTC, yossisegev reviewed
/LGTM

2023-01-26 12:50 UTC, GroceryBoyJr commented
/remove-label peer-review-needed
/label peer-review-in-progress

2023-01-26 14:55 UTC, GroceryBoyJr reviewed
LGTM

2023-01-26 14:55 UTC, GroceryBoyJr commented
/remove-label peer-review-in-progress
/label peer-review-done

2023-01-26 14:59 UTC, merged

2023-01-26 15:00 UTC, sjhala-ccs commented
/cherrypick enterprise-4.11

2023-01-26 15:00 UTC, sjhala-ccs commented
/cherrypick enterprise-4.12

2023-01-26 15:00 UTC, sjhala-ccs commented
/cherrypick enterprise-4.13