RHDEVDOCS-4426
openshift/openshift-docs pull request #55237
Opened 2023-01-26 21:40 UTC by libander

Version(s): 4.11+

Issue: RHDEVDOCS-4426

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-01-27 12:10 UTC, kabirbhartiRH commented on modules/logging-loki-retention.adoc
> +apiVersion: loki.grafana.com/v1
This look like the correct LokiStack for 'per-tenant stream based retention'. We can also define global stream based retention' for LokiStack.

For e.g.
 ```
apiVersion: loki.grafana.com/v1
 kind: LokiStack
 metadata:
   name: lokistack-sample
   namespace: openshift-logging
 spec:
   limits:
     global:
       retention:
         days: 2
         streams:
         - days: 4
           priority: 1
           selector: '{kubernetes_namespace_name=~"test.+"}'
         - days: 1
           priority: 1
           selector: '{log_type="application"}'
         - days: 15
           priority: 1
           selector: '{log_type="audit"}'
   managementState: Managed
   replicationFactor: 1
   size: 1x.small
   storage:
    schemas:
    - effectiveDate: "2020-10-11"
       version: v11
    secret:
      name: gcs-secret
      type: gcs
  storageClassName: standard
  tenants:
    mode: openshift-logging
```

2023-01-30 20:36 UTC, rolfedh approved these changes
I've offered some suggestions. Pre-approving to expedite.

2023-01-30 20:36 UTC, rolfedh commented on modules/logging-loki-retention.adoc
> += Enabling stream based retention with Loki
```suggestion
= Enabling stream-based retention with Loki
```

2023-01-30 20:36 UTC, rolfedh commented on modules/logging-loki-retention.adoc
> +With Logging version 5.6 and higher, you can configure retention policies based on stream globally, per tenant, or both. If you configure both, tenant rules apply before global rules.
"based on stream globally" sounds a bit odd.

2023-01-30 20:36 UTC, rolfedh commented on modules/logging-loki-retention.adoc
> +. To enable stream based retention,  create or edit the `LokiStack` custom resource:
```suggestion
. To enable stream-based retention, create or edit the `LokiStack` custom resource (CR):
```

2023-01-31 02:25 UTC, QiaolingTang commented on modules/logging-loki-retention.adoc
> +                periodDays: 1
This is not a valid LokiStack CR, many fields are not in the lokistack CRD: https://github.com/openshift/loki/blob/release-5.6/operator/bundle/manifests/loki.grafana.com_lokistacks.yaml.

Some examples:
1. Per-Tenant stream-based retention
```
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: lokistack-sample
  namespace: openshift-logging
spec:
  limits:
    global:
      retention:
        days: 20
    tenants:
      application:
        retention:
          days: 1
          streams:
            - days: 4
              selector: '{kubernetes_namespace_name=~"test.+"}'
      infrastructure:
        retention:
          days: 5
          streams:
            - days: 1
              selector: '{kubernetes_namespace_name=~"openshift-cluster.+"}'
  managementState: Managed
  replicationFactor: 1
  size: 1x.extra-small
  storage:
    schemas:
    - effectiveDate: "2020-10-11"
      version: v11
    secret:
      name: gcs-secret
      type: gcs
  storageClassName: standard
  tenants:
    mode: openshift-logging 
```
2. Global stream-based retention
```
 apiVersion: loki.grafana.com/v1
 kind: LokiStack
 metadata:
   name: lokistack-sample
   namespace: openshift-logging
 spec:
   limits:
     global:
       retention:
         days: 20
         streams:
         - days: 4
           priority: 1
           selector: '{kubernetes_namespace_name=~"test.+"}'
         - days: 1
           priority: 1
           selector: '{log_type="infrastructure"}'
   managementState: Managed
```

2023-01-31 07:20 UTC, periklis requested changes

2023-01-31 07:20 UTC, periklis commented on modules/logging-loki-retention.adoc
> +With Logging version 5.6 and higher, you can configure retention policies based on stream. Rules for these may be set globally, per tenant, or both. If you configure both, tenant rules apply before g
```suggestion
With Logging version 5.6 and higher, you can configure retention policies based on log streams. Rules for these may be set globally, per tenant, or both. If you configure both, tenant rules apply before global rules.
```

2023-01-31 07:20 UTC, periklis commented on modules/logging-loki-retention.adoc
> +<3> Sets retention policy for all logs.
```suggestion
<3> Sets retention policy for all log streams.
```

We should highlight in a note below that this field is not to be used as the global retention policy of 30days that OpenShift Logging includes as a maximum supported policy. The global 30 days policy across all stored logs has to be defined on the Object Storage provider side for the LokiStack bucket. The key wording here is:
- OpenShift Logging 30 days retention -> Affects **stored logs** on object storage -> Configuration on the object storage provider only
- The field mentioned in `<3>` is a global **log stream** retention policy and applying it is at best effort by the compactor. In addition if someone mixes tenant with global retention policies the global policy is overridden anyway.

2023-02-01 05:27 UTC, QiaolingTang commented on modules/logging-loki-retention.adoc
> +    limits:
Too many blanks before `limits`, here should be:
```
spec:
  limits:
    global:
```

2023-02-01 08:31 UTC, periklis reviewed
Besides what @QiaolingTang marked, looks good to me. I have not tested or validated the YAML TBH. The remarks I asked for are in place. Thank you so much :tada:

2023-02-02 00:25 UTC, QiaolingTang commented
The changes LGTM.

2023-02-02 18:38 UTC, merged

2023-02-02 18:38 UTC, rolfedh commented
/cherry-pick enterprise-4.11

2023-02-02 18:38 UTC, rolfedh commented
/cherry-pick enterprise-4.12

2023-02-02 18:38 UTC, rolfedh commented
/cherry-pick enterprise-4.13