TELCODOCS-1169: Corrections to power saving configuration docs
openshift/openshift-docs pull request #55468
Opened 2023-02-02 13:17 UTC by amolnar-rh

Version(s): 4.12, 4.13

Issue: https://issues.redhat.com/browse/TELCODOCS-1169

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-02-02 13:58 UTC, bartwensley requested changes
Looks great - I changed my mind about the wording of one sentence so one small update is required.

2023-02-02 13:58 UTC, bartwensley commented on modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
> +<1> The `max_perf_pct` controls the maximum frequency the `cpufreq` driver is allowed to set as a percentage of the maximum supported cpu frequency. This value applies to all CPUs. You can check the
Reword last sentence to:
This is the frequency that all cores will run at when they are all fully occupied.

2023-02-02 14:41 UTC, bartwensley approved these changes
Thanks Alexandra for the quick updates.

2023-02-02 15:08 UTC, amolnar-rh commented
/label peer-review-needed

2023-02-02 16:03 UTC, amolnar-rh commented on modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
> +<1> The `max_perf_pct` controls the maximum frequency the `cpufreq` driver is allowed to set as a percentage of the maximum supported cpu frequency. This value applies to all CPUs. You can check the
It's the All Cores Turbo frequency. I'll spell it out for clarity

2023-02-03 11:45 UTC, mrniranjan commented
/lgtm

2023-02-03 12:29 UTC, amolnar-rh commented
/label merge-review-needed

2023-02-03 14:59 UTC, merged

2023-02-03 15:00 UTC, mburke5678 commented
/cherrypick enterprise-4.12

2023-02-03 15:03 UTC, mburke5678 commented
/cherrypick enterprise-4.13