RHDEVDOCS-4926- Logging 5.4.11 Release Notes
openshift/openshift-docs pull request #55637
Opened 2023-02-07 15:50 UTC by libander

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-02-08 01:27 UTC, anpingli commented
/lgtm

2023-02-08 12:59 UTC, gabriel-rh approved these changes
/lgtm

2023-02-15 09:35 UTC, Srivaralakshmi requested changes
@libander Nice work! PTAL at the suggestions. Thanks!

2023-02-15 09:35 UTC, Srivaralakshmi commented on modules/cluster-logging-rn-5.4.11.adoc
> +//module included in cluster-logging-release-notes.adoc
```suggestion
// Module included in the following assemblies:
//
// * logging/cluster-logging-release-notes.adoc


```
**Suggestion**: Refer to the guideline and example [here](https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#module-file-metadata).

2023-02-15 09:35 UTC, Srivaralakshmi commented on modules/cluster-logging-rn-5.4.11.adoc
> +This release includes link:https://access.redhat.com/errata/RHSA-2023:0632[OpenShift Logging Bug Fix Release 5.4.11].
Getting 404 PAGE NOT FOUND for the errata link. Hope it is correct. Please check.

2023-02-15 18:13 UTC, merged

2023-02-15 18:13 UTC, rolfedh commented
/cherry-pick enterprise-4.9

2023-02-15 18:13 UTC, rolfedh commented
/cherry-pick enterprise-4.10

2023-02-15 18:13 UTC, rolfedh commented
/cherry-pick enterprise-4.11

2023-02-15 18:13 UTC, rolfedh commented
/cherry-pick enterprise-4.12

2023-02-15 18:13 UTC, rolfedh commented
/cherry-pick enterprise-4.13