RHDEVDOCS-4861: Updated GitOps1.7 RN for an inaccuracy
openshift/openshift-docs pull request #55985
Opened 2023-02-16 11:26 UTC by shipsing

**NOTE**: From GitOps 1.7.0 onwards, we will be documenting security issues in a new advisory format as part of errata updates. 

**Aligned team**: Dev Tools

**Purpose**: To resolve the following issue: 
https://issues.redhat.com/browse/RHDEVDOCS-4861

**OCP version this PR applies to**:  enterprise 4.9 and later

**Link to docs preview**:  

**Change Management**
Need an ACK from Eng:  
Need an ACK from PM: @harrietgrace @wtam2018 
Need an ACK from Product experience: @RickJWagner 
Need an ACK from QE: @varshab1210 
Need an ACK from DPM: @pmkovar 
Need an ACK from CS: @Preeticp 

Peer review:

2023-02-16 11:36 UTC, shipsing commented
@jaideepr97 @harrietgrace @wtam2018 @RickJWagner @varshab1210 @pmkovar @Preeticp, Could you please review this PR and share your feedback? Thanks

2023-02-16 11:49 UTC, jaideepr97 commented
LGTM thanks @shipsing

2023-02-16 11:57 UTC, varshab1210 commented
LGTM
Thanks!

2023-02-16 13:22 UTC, wtam2018 commented
@ishitasequeira Please confirm the correction is correct It changes quite a bit from the original note.

2023-02-16 13:28 UTC, RickJWagner commented
/label px-approved

2023-02-16 13:30 UTC, ishitasequeira commented
LGTM! Thanks!

2023-02-16 13:43 UTC, wtam2018 commented
/lgtm

2023-02-17 08:57 UTC, Preeticp commented
LGTM

2023-02-17 09:41 UTC, Srivaralakshmi requested changes
@shipsing PTAL at the suggestions. Thanks!

2023-02-17 09:41 UTC, Srivaralakshmi commented on modules/gitops-release-notes-1-7-0.adoc
> +** Add the namespace to `.spec.sourceNamespaces` in the `AppProject` custom resource that is associated with the application 
```suggestion
** Add the namespace to the `.spec.sourceNamespaces` attribute in the `AppProject` custom resource that is associated with the application. 
```

2023-02-17 09:41 UTC, Srivaralakshmi commented on modules/gitops-release-notes-1-7-0.adoc
> +** Add the namespace to the `.spec.sourceNamespaces` attribute for a cluster-scoped Argo CD instance that manages the application
```suggestion
** Add the namespace to the `.spec.sourceNamespaces` attribute for a cluster-scoped Argo CD instance that manages the application.
```

2023-02-17 10:55 UTC, shipsing commented
Thank you @Srivaralakshmi, incorporated your suggestions. Could you please verify and confirm?

2023-02-17 12:48 UTC, Srivaralakshmi commented
/lgtm

2023-02-17 12:48 UTC, Srivaralakshmi approved these changes
@shipsing Approved!

2023-02-20 15:06 UTC, merged

2023-02-20 15:07 UTC, bburt-rh commented
/cherrypick enterprise-4.9

2023-02-20 15:07 UTC, bburt-rh commented
/cherrypick enterprise-4.10

2023-02-20 15:07 UTC, bburt-rh commented
/cherrypick enterprise-4.11

2023-02-20 15:07 UTC, bburt-rh commented
/cherrypick enterprise-4.13