CNV-22364
openshift/openshift-docs pull request #56089
Opened 2023-02-17 19:05 UTC by aspauldi

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-02-23 22:10 UTC, aspauldi commented
@phoracek, This PR is ready for dev review; thanks!

2023-02-27 15:45 UTC, phoracek requested changes

2023-02-27 16:27 UTC, aspauldi commented on modules/virt-about-services.adoc
> +====
Hi Petr, That line came from info in the Jira story description.

2023-02-28 12:48 UTC, phoracek commented on modules/virt-about-services.adoc
> +====
I see. It's true that this provides a better performance than connecting via SSH though a proxy. However, out of the context this note sounds that services add performance benefit on their own, which is not the case.

I would suggest we drop this note and rely on https://docs.openshift.com/container-platform/4.12/virt/virtual_machines/virt-accessing-vm-consoles.html#virt-accessing-vmi-ssh_virt-accessing-vm-consoles which already describes downsides of `virtctl ssh`. I would treat Services as the default, they are not particularly slow (like virtctl ssh) nor fast (like SR-IOV).

2023-02-28 17:33 UTC, aspauldi commented
@phoracek 

Can you take another look? I removed the NOTE. Thanks!

2023-02-28 17:37 UTC, phoracek approved these changes
Looks good, thanks!

2023-02-28 17:39 UTC, aspauldi commented
Thanks, Petr!

2023-02-28 17:40 UTC, aspauldi commented
@yossisegev , Hello! Can you please take a look at this update? Thanks!

2023-02-28 18:07 UTC, yossisegev commented
LGTM

2023-02-28 18:27 UTC, aspauldi commented
Thanks, @yossisegev !

2023-02-28 18:35 UTC, aspauldi commented
/label CNV

/label peer-review-needed

2023-02-28 20:55 UTC, kowen-rh commented
/label peer-review-in-progress

2023-02-28 21:05 UTC, kowen-rh approved these changes
LGTM! :+1:

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

2023-02-28 21:07 UTC, aspauldi commented
/label merge-review-needed

2023-02-28 21:45 UTC, merged

2023-02-28 21:45 UTC, mburke5678 commented
/cherrypick enterprise-4.13