Adding known issue to z-stream 41126 TELCODOCS-1185
openshift/openshift-docs pull request #56220
Opened 2023-02-21 16:00 UTC by kquinn1204

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-02-22 10:06 UTC, kquinn1204 commented
@cgoncalves can you PTAL the known issue I added

2023-02-22 10:54 UTC, cgoncalves commented on release_notes/ocp-4-11-release-notes.adoc
> +* This release regresses functionality where SR-IOV secondary network interfaces configured with static MAC address attached to pods may not provide full network connectivity. This issue only impacts
Wrong OCPBUGS

2023-02-22 11:32 UTC, cgoncalves commented
LGTMT
The bug has meanwhile been fixed and released in OCP 4.11.28 (https://access.redhat.com/errata/RHBA-2023:0775

2023-02-22 11:40 UTC, kquinn1204 commented
Great @cgoncalves I guess I should make that clear - WDYT ?

2023-02-22 11:44 UTC, cgoncalves commented
I don't know if there's any Docs guidance on this. Perhaps we shouldn't start doing that, otherwise we open a precedence where customers expect us to always go back to past z-stream release notes and amend the notes to state that issues have been addressed in newer streams. That is why I suggested earlier to link to the OCPBUGS, it contains all that info. IMO it should be fine as is.

2023-02-22 11:50 UTC, kquinn1204 commented
Good point thanks Yes I made a mistake with the bug number.

2023-02-22 12:07 UTC, kquinn1204 commented
/label peer-review-needed

2023-02-23 18:48 UTC, eohartman commented
/remove-label peer-review-needed

2023-02-23 18:49 UTC, eohartman commented
/remove-label peer-review-in-progress

2023-02-23 18:49 UTC, eohartman requested changes

2023-02-23 18:49 UTC, eohartman commented on release_notes/ocp-4-11-release-notes.adoc
> +* This release regresses functionality where SR-IOV secondary network interfaces configured with static MAC address attached to pods may not provide full network connectivity. This issue only impacts
Change "may" to "might," per [IBM standards.](https://www.ibm.com/docs/en/ibm-style?topic=word-usage#may)

2023-02-23 19:55 UTC, eohartman commented
/label peer-review-done

2023-02-27 09:12 UTC, kquinn1204 commented
/label merge-review-needed

2023-02-27 14:38 UTC, merged