TELCODOCS-1165 - Support multiple storage/device classes
openshift/openshift-docs pull request #56366
Opened 2023-02-23 12:11 UTC by aireilly

Adds docs for multiple storage/device classes support

Version(s):
enterprise-4.13

Issue:
https://issues.redhat.com/browse/TELCODOCS-1165

Link to docs preview:

QE review:
- [ ] QE has approved this change.

2023-03-06 16:15 UTC, suleymanakbas91 requested changes

2023-03-06 17:31 UTC, suleymanakbas91 commented
/lgtm

2023-03-07 13:37 UTC, aireilly commented
/label peer-review-needed

2023-03-07 15:25 UTC, kcarmichael08 commented
/label peer-review-in-progress

2023-03-07 15:25 UTC, kcarmichael08 reviewed
Can you please squash to one commit?

2023-03-07 16:17 UTC, kcarmichael08 reviewed
You did a great job with the writing and the flow of info! I had some comment/questions but it looks really good.

2023-03-07 16:17 UTC, kcarmichael08 commented on modules/lvms-creating-an-logical-volume-manager-cluster.adoc
> +`LVMVolumeGroup` CRs provide the backend storage for the persistent volumes that you create.
IBM Style suggests "back-end" (usually hyphenated) - I found both hyphenated and non-hyphenated versions in the OCP docs repo - more hyphenated than not, so I'm not sure about this particular usage. 
```suggestion
`LVMVolumeGroup` CRs provide the back-end storage for the persistent volumes that you create.
```

2023-03-10 20:44 UTC, radeore commented
/lgtm

2023-03-11 08:58 UTC, aireilly commented
/label merge-review-needed

2023-03-13 16:55 UTC, skrthomas reviewed
Merge review LGTM

2023-03-13 16:57 UTC, merged

2023-03-13 16:57 UTC, skrthomas commented
/cherrypick enterprise-4.13