OSDOCS-4582
openshift/openshift-docs pull request #56783
Opened 2023-03-03 19:46 UTC by jneczypor

OSDOCS-4582

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-4582

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-03-03 20:24 UTC, jneczypor commented
Hello @yuwang-RH! Can you please give this PR a review when you have time? Thank you!

2023-03-10 14:02 UTC, xueli181114 commented
/lgtm

2023-03-20 13:23 UTC, arendej approved these changes
LGTM, thanks.

2023-03-20 17:22 UTC, eohartman commented
/label peer-review-in-progress

2023-03-20 18:54 UTC, eohartman requested changes

2023-03-20 18:54 UTC, eohartman commented on modules/osd-aws-privatelink-firewall-prerequisites.adoc
> +|The `registry.access.redhat.com` and `http://registry.redhat.io` sites redirect through `catalog.redhat.com`.
For catalog.redhat.com, the website address should be https:, not http:. Everything else looks great!

2023-03-20 20:37 UTC, eohartman commented
/remove-label peer-review-needed

2023-03-20 21:00 UTC, eohartman commented
/remove-label peer-review-in-progress
/label peer-review-done

2023-03-20 21:08 UTC, arendej approved these changes
lgtm

2023-03-21 12:32 UTC, kelbrown20 reviewed
LGTM as well

2023-03-21 12:33 UTC, merged

2023-03-21 12:38 UTC, kelbrown20 commented
/cherrypick enterprise-4.12