Appended note for not to use openshift-.io/cluster-monitoring label o…
openshift/openshift-docs pull request #56853
Opened 2023-03-06 18:43 UTC by dhgautam99

…n user-defined projects

`openshift-.io/cluster-monitoring` is reserved for platform projects and should not be configured on any user-defined projects. A note has been appended for the same.

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-03-13 13:04 UTC, rkratky requested changes

2023-03-13 13:04 UTC, rkratky commented on modules/monitoring-enabling-monitoring-for-user-defined-projects.adoc
> +[Note]
```suggestion
[NOTE]
```
But consider using IMPORTANT.

2023-03-13 13:04 UTC, rkratky commented on modules/monitoring-enabling-monitoring-for-user-defined-projects.adoc
> +Label `openshift.io/cluster-monitoring` is reserved for platform specific projects. You must not use the label `openshift.io/cluster-monitoring` on any user-defined projects.
```suggestion
The `openshift.io/cluster-monitoring` label is reserved for platform-specific projects. Do not use the label `openshift.io/cluster-monitoring` on any user-defined projects.
```

2023-03-14 09:27 UTC, juzhao commented
strictly speaking, for user projects, should not set value `true` for label `openshift.io/cluster-monitoring`, if we set `openshift.io/cluster-monitoring: "false"` label to user project, the project is monitored by UWM, if set `openshift.io/cluster-monitoring: "true"` label to user project, the project will be monitored by platform monitoring. the note in the PR is make sense, since avoid using `openshift.io/cluster-monitoring` label is recommended for user project.
/lgtm

2023-03-14 10:58 UTC, simonpasquier commented
/lgtm
I agree with @juzhao that mentioning ` openshift.io/cluster-monitoring` is enough (no need to go into the details that CMO will only monitor namespaces with `openshift.io/cluster-monitoring=true`).

2023-03-30 18:39 UTC, cbremble commented
@dhgautam99 (cc @kalexand-rh ) you have feedback to implement on this one, PTAL. I have a review pending, but would not feel comfortable approving until that's been done. Thank you!

2023-04-06 19:02 UTC, bburt-rh commented
@dhgautam99 Thanks for your help with this PR! Per the [contributor's guidelines](https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/create_or_edit_content.adoc#submit-pr-to-merge-your-work), we need you to squash the four commits in this PR to one commit, and then push the changes. Then, we will be able to merge it. Thank you!

2023-07-04 16:48 UTC, dhgautam99 commented
Closing the PR as there are issues while squashing the commits. I will open another one with a single commit.
CC @bburt-rh

2023-07-04 16:48 UTC, closed without merging