OSDOCS-4328: Edits from the Optimizing Routing content audit
openshift/openshift-docs pull request #56929
Opened 2023-03-07 19:24 UTC by ahardin-rh

Version(s):
4.9+

Issue:
https://issues.redhat.com/browse/OSDOCS-4328

Link to docs preview:

2023-03-07 20:40 UTC, candita commented on modules/router-performance-optimizations.adoc
>  You can modify the Ingress Controller deployment, but if the Ingress Operator is enabled, the configuration is overwritten.
```suggestion
You can modify the Ingress Controller deployment using the information provided in:

https://docs.openshift.com/container-platform/4.12/networking/ingress-operator.html#nw-ingress-setting-thread-count_configuring-ingress for threads and 
https://docs.openshift.com/container-platform/4.12/networking/ingress-operator.html#nw-ingress-controller-configuration-parameters_configuring-ingress for timeouts and other tuning configuration in the ingress controller specification.
```

2023-03-07 20:44 UTC, candita requested changes
Also add a link to the sharding docs in https://docs.openshift.com/container-platform/4.12/networking/ingress-operator.html#nw-ingress-sharding_configuring-ingress

2023-03-07 20:51 UTC, candita commented
/assign

2023-03-21 17:54 UTC, ahardin-rh commented
@candita @Miciah I made some updates and refactored some of the content. PTAL. Thanks!

2023-03-21 19:36 UTC, GroceryBoyJr commented
/label peer-review-in-progress
/remove-label peer-review-needed

2023-03-21 20:43 UTC, GroceryBoyJr reviewed
@ahardin-rh only a couple of nits. I have taken liberties, use my suggestions as you see fit.

2023-03-21 20:43 UTC, GroceryBoyJr commented on modules/baseline-router-performance.adoc
> +The default Ingress Controller configuration was used with the `spec.tuningOptions.threadCount` field set to `4`. Two different endpoint publishing strategies were tested, Load Balancer Service and H
```suggestion
The default Ingress Controller configuration was used with the `spec.tuningOptions.threadCount` field set to `4`. Two different endpoint publishing strategies were tested: Load Balancer Service and Host Network. TLS session resumption was used for encrypted routes. With HTTP keep-alive, a single HAProxy router is capable of saturating a 1 Gbit NIC at page sizes as small as 8 kB.
```

2023-03-21 20:43 UTC, GroceryBoyJr commented on modules/baseline-router-performance.adoc
> +The {product-title} Ingress Controller, or router, is the ingress point for ingress traffic for applications and services that are configured using routes and ingresses.
```suggestion
The {product-title} Ingress Controller provides a means for traffic external to the cluster to access services internal to the cluster. When routing HTTP or HTTPS traffic, this is also called an HAProxy router."
```

2023-03-21 20:43 UTC, GroceryBoyJr commented on modules/baseline-router-performance.adoc
>  When evaluating a single HAProxy router performance in terms of HTTP requests handled per second, the performance varies depending on many factors. In particular:
```suggestion
When evaluating a single HAProxy router performance in terms of HTTP requests handled per second, the performance varies according to the following factors:
```

2023-03-21 20:43 UTC, GroceryBoyJr commented
/remove-label peer-review-in-progress
/label peer-review-done

2023-03-21 22:05 UTC, candita commented on modules/baseline-router-performance.adoc
> +The {product-title} Ingress Controller, or router, is the ingress point for ingress traffic for applications and services that are configured using routes and ingresses.
No, this is not correct.

2023-03-21 22:06 UTC, candita commented on modules/baseline-router-performance.adoc
>  When evaluating a single HAProxy router performance in terms of HTTP requests handled per second, the performance varies depending on many factors. In particular:
No, that changes the meaning.

2023-03-21 22:15 UTC, candita commented on modules/baseline-router-performance.adoc
> +In general, HAProxy can support routes for 5 to 1000 applications, depending on the technology in use. Ingress Controller performance might be limited by the
There is really no lower bound on the number of applications, so you could say "In general, HAProxy can support routes for up to 1000 applications, depending on..."

2023-03-21 22:16 UTC, candita commented on modules/router-performance-optimizations.adoc
Where did the content from this file end up?

2023-03-21 22:22 UTC, candita commented
Thanks @ahardin-rh - this looks much better.  I had a few comments, and it would be great to have the link to sharding docs as I mentioned in I think it is missing the link to sharding documents that I mentioned in https://github.com/openshift/openshift-docs/pull/56929#pullrequestreview-1329498373

2023-03-22 14:10 UTC, ahardin-rh commented on modules/router-performance-optimizations.adoc
@candita It is now moved to scalability_and_performance/routing-optimization.adoc (the assembly file) because after making the requested edits that file was basically empty.

2023-03-23 15:28 UTC, merged

2023-03-23 15:29 UTC, ahardin-rh commented
/cherrypick enterprise-4.13

2023-03-23 15:29 UTC, ahardin-rh commented
/cherrypick enterprise-4.12

2023-03-23 15:29 UTC, ahardin-rh commented
/cherrypick enterprise-4.10