BZ 1499035 Added note on latest glusterfs package
openshift/openshift-docs pull request #5726
Opened 2017-10-16 15:39 UTC by mburke5678

https://bugzilla.redhat.com/show_bug.cgi?id=1499035

2017-10-16 15:42 UTC, mburke5678 commented
@eparis We got a request to add the minimum required version of glusterfs that is needed to install OpenShift. The version in subscription-manager (glusterfs-*-3.7.9) is apparently wrong for 3.6. 
Is this in your purview?

2017-10-25 17:03 UTC, jarrpa commented
@mburke5678 I can start looking into this. I'll comment on the BZ.

2017-11-02 13:11 UTC, jarrpa requested changes
I think this should do towards the end of the document, something like:

```
If the package was already installed, make sure the latest version is installed:

----
# yum update glusterfs-fuse
----
```

2017-11-02 15:06 UTC, mburke5678 commented
@jarrpa I added your sentence and command at the end of the topic. Moving the BZ to `On_QA`.

2017-11-08 16:53 UTC, mburke5678 commented
@openshift/team-documentation PTAL

2017-11-08 16:55 UTC, ahardin-rh commented on install_config/install/prerequisites.adoc
> +If GlusterFS is already installed on the nodes, make sure the latest version is installed:
s/make sure the/ensure that the

2017-11-08 16:55 UTC, ahardin-rh commented
@mburke5678 Just one suggestion from me. Otherwise, looks good!

2017-11-08 17:40 UTC, merged

2017-11-08 17:59 UTC, mburke5678 commented
[rev_history]
|xref:../install_config/install/prerequisites.adoc#install-config-install-prerequisites[Installation and Configuration -> Prerequisites]
|Added note to ensure the lastest version of Glusterfs is installed.
%