Pac for 1 9
openshift/openshift-docs pull request #57455
Opened 2023-03-21 05:43 UTC by gtrivedi88

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-03-21 11:07 UTC, shipsing commented on modules/op-creating-pipeline-run-using-pipelines-as-code.adoc
> +* `event_title`: Matches the title of the event, such as the commit title for a `push` event, and the title of a pull or merge request for a `pull_request` event. Currently, only GitHub, Gitlab, and
```suggestion
* `event_title`: Matches the title of the event, such as the commit title for a `push` event, and the title of a pull or merge request for a `pull_request` event. Currently, only GitHub, Gitlab, and Bitbucket Cloud are the supported providers.
```

2023-03-21 13:02 UTC, Srivaralakshmi requested changes
@gtrivedi88 There was a huge number of review comments. Thanks for your effort in addressing all the changes and suggestions requested. Some of them were missed out - PTAL at my suggestions. Thanks again!

2023-03-21 16:20 UTC, Srivaralakshmi approved these changes
@gtrivedi88: Thanks for the changes. Approved!

2023-03-21 16:21 UTC, Srivaralakshmi commented
/lgtm

2023-03-22 05:29 UTC, shipsing commented
> tkn-pac

@gtrivedi88 There is still an instance of `tkn-pac` in this section: https://57455--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/using-pipelines-as-code.html#pac-key-features.

Please check. Rest all looks good.

2023-03-22 06:52 UTC, shipsing approved these changes
/lgtm

2023-03-23 13:19 UTC, merged

2023-03-23 13:32 UTC, rolfedh commented
/cherrypick enterprise-4.13