OCPBUGS-10270: Add a note that you have to include the default channel
openshift/openshift-docs pull request #57487
Opened 2023-03-21 17:01 UTC by bergerhoffer

Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OCPBUGS-10270

Link to docs preview:
https://57487--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-creating-image-set-config_installing-mirroring-disconnected

QE review:
- [x] QE has approved this change.

Additional information:

2023-03-21 17:32 UTC, bergerhoffer commented
@sherine-k Can you please review and let me know if this works for the note about the default channel being required?

Preview: https://57487--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-creating-image-set-config_installing-mirroring-disconnected

2023-03-21 17:32 UTC, bergerhoffer commented
/label peer-review-needed

2023-03-21 18:06 UTC, michaelryanpeter commented
/label peer-review-in-progress

2023-03-30 07:45 UTC, sherine-k requested changes
Hi @bergerhoffer 
Sorry for the delay. I realise I never clicked the submit button!
Luckily github saved my comment!

2023-03-30 13:19 UTC, bergerhoffer commented on modules/oc-mirror-creating-image-set-config.adoc
> +<8> Specify only certain channels of the Operator packages to include in the image set. You must always include the default channel for the Operator package.
@sherine-k thanks! Updated, PTAL

https://57487--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-creating-image-set-config_installing-mirroring-disconnected

2023-03-30 13:22 UTC, sherine-k approved these changes
Yes! Thanks @bergerhoffer

2023-03-30 13:33 UTC, zhouying7780 commented
/lgtm

2023-03-30 14:47 UTC, merged

2023-03-30 14:47 UTC, bergerhoffer commented
/cherrypick enterprise-4.12

2023-03-30 14:47 UTC, bergerhoffer commented
/cherrypick enterprise-4.11