TELCODOCS-1120 removing section on incompatibility with IP failover
openshift/openshift-docs pull request #57579
Opened 2023-03-22 14:37 UTC by kquinn1204

[TELCODOCS-1120]: Misleading text in MetalLB incompatibility section
[OCPBUGS-9222]: This section has generated quite a lot of discussions on e-mails and on slack
Version(s):
main, 4.13, 4.12, 4.11, 4.10, 4.9

Issue:
https://issues.redhat.com/browse/TELCODOCS-1120

Link to docs preview:https://57579--docspreview.netlify.app/openshift-enterprise/latest/networking/metallb/about-metallb.html

QE review:
- [x] QE has approved this change.

Additional information:

2023-03-23 13:53 UTC, kquinn1204 commented
/label telco

2023-03-23 13:59 UTC, kquinn1204 commented
@asood-rh can you please review this PR providing clarity around MetalLB and IP failover

2023-03-23 14:06 UTC, msherif1234 commented
/lgtm

2023-03-23 14:11 UTC, kquinn1204 commented
/label peer-review-needed

2023-03-23 20:07 UTC, stevsmit commented on modules/nw-metallb-when-metallb.adoc
> +MetalLB provides support for failover by utilizing a mechanism similar to IP failover. However, instead of relying on virtual router redundancy protocol (VRRP) and keepalived, MetalLB leverages a mem
the virtual router redundancy protocol? (with "the" added)?

2023-03-23 20:07 UTC, stevsmit commented on modules/nw-metallb-when-metallb.adoc
> +Using MetalLB instead of IP failover is a more preferable option for ensuring high availability of pods and services.
consider: 

s/ "more preferable" / "preferable" or "is the preferring option"

2023-03-23 20:07 UTC, stevsmit commented
@kquinn1204 2 nits. Be sure to squash your commits as well. Thanks!

2023-03-24 16:48 UTC, kelbrown20 reviewed
Updates LGTM, merging!

2023-03-27 09:37 UTC, kquinn1204 commented
@asood-rh I need QE approval to get this change implemented it is a clarification on MetalLB and IP failover in docs that causes some confusion. Can you set a LGTM please?

2023-03-27 12:42 UTC, asood-rh commented
/lgtm

2023-03-27 12:49 UTC, kquinn1204 commented
@kelbrown20 I got a LGTM in keeping with the process. Thanks for flagging, so should be good to merge now.

2023-03-27 12:49 UTC, kquinn1204 commented
@kelbrown20 I got a LGTM in keeping with the process. Thanks for flagging, so should be good to merge now.

2023-03-27 12:51 UTC, kquinn1204 commented
@kelbrown20 I got a LGTM in keeping with the process. Thanks for flagging, so should be good to merge now.

2023-03-27 12:51 UTC, kquinn1204 commented
@kelbrown20 I got a LGTM in keeping with the process. Thanks for flagging, so should be good to merge now.

2023-03-27 13:25 UTC, russellb requested changes
@fedepaol can you give this another look?

2023-03-27 13:28 UTC, fedepaol commented on modules/nw-metallb-when-metallb.adoc
> +MetalLB provides support for failover by utilizing a mechanism similar to IP failover. However, instead of relying on the virtual router redundancy protocol (VRRP) and keepalived, MetalLB leverages a
:+1 and thanks for the review!

2023-03-28 08:54 UTC, kquinn1204 commented
/label merge-review-needed

2023-03-28 14:57 UTC, merged

2023-03-28 14:57 UTC, kelbrown20 commented
/cherrypick enterprise-4.13

2023-03-28 14:58 UTC, kelbrown20 commented
/cherrypick enterprise-4.12

2023-03-28 15:03 UTC, kelbrown20 commented
/cherrypick enterprise-4.11

2023-03-28 15:04 UTC, kelbrown20 commented
/cherrypick enterprise-4.10

2023-03-28 15:26 UTC, kelbrown20 commented
@kquinn1204 Looks like the CP to 4.9 failed so this need a manual one :'( . I can merge the manual CP when ready