Release Note for TELCODOCS-782 - workload partitioning
openshift/openshift-docs pull request #58139
Opened 2023-04-03 14:31 UTC by slovern

Version(s): 4.13

Issue: https://issues.redhat.com/browse/TELCODOCS-782

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-04-04 07:58 UTC, aireilly requested changes
Nice work. 

General comment - this release note seems to miss the fact that workload partitioning has been extended to cover 3NC and standard clusters. Previously, only SNO clusters could have workload partitioning.  

My suggested updates incorporate this change.

2023-04-04 07:58 UTC, aireilly commented on release_notes/ocp-4-13-release-notes.adoc
> +You can use workload partitioning to isolate {product-title} services, cluster management workloads, and infrastructure pods to run on a reserved set of CPUs. Workload partitioning isolates user work
```suggestion
Previously, workload partitioning was supported for {sno} clusters only.
Now, you can also configure workload partitioning for three-node compact clusters and standard clusters.
Use workload partitioning to isolate {product-title} services, cluster management workloads, and infrastructure pods to run on a reserved set of CPUs.
```

2023-04-05 16:16 UTC, slovern commented on release_notes/ocp-4-13-release-notes.adoc
> +==== Workload partitioning
Thanks - done

2023-04-14 12:41 UTC, slovern commented
/label peer-review-needed

2023-04-14 14:32 UTC, GroceryBoyJr commented
/remove-label peer-review-needed
/label peer-review-in-progress

2023-04-14 14:35 UTC, GroceryBoyJr reviewed
@slovern only one tiny nit, otherwise LGTM. Happy to see your link works beautifully! :+1:

2023-04-14 14:35 UTC, GroceryBoyJr commented on release_notes/ocp-4-13-release-notes.adoc
> +Previously, workload partitioning was supported for {sno} clusters only.
```suggestion
Before this update, workload partitioning was supported for {sno} clusters only.
```

2023-04-14 14:36 UTC, GroceryBoyJr commented
/label peer-review-done
/remove-label peer-review-in-progress

2023-04-14 15:00 UTC, slovern commented on release_notes/ocp-4-13-release-notes.adoc
> +Previously, workload partitioning was supported for {sno} clusters only.
Thanks for the review @GroceryBoyJr

2023-04-14 15:16 UTC, slovern commented
/label merge-review-needed

2023-04-14 16:36 UTC, stevsmit commented
lgtm

2023-04-14 16:36 UTC, merged