[SRVCOM-2105] Serverless: s/v1alpha/v1beta1 in examples
openshift/openshift-docs pull request #58245
Opened 2023-04-05 12:29 UTC by rh-max

Version(s):
4.8+

Issue:
https://issues.redhat.com/browse/SRVCOM-2105

Link to docs preview:
FIXME

QE review:
- [ ] QE has approved this change.

2023-04-05 14:13 UTC, skonto commented on modules/serverless-kafka-sasl-channels.adoc
> +apiVersion: operator.serverless.openshift.io/v1beta1
All kafka ones stay as v1alpha1. Only Eventing & Serving are moving.

2023-04-05 14:15 UTC, skonto commented on modules/serverless-kafka-sink.adoc
> +apiVersion: eventing.knative.dev/v1beta1
Only the operator ones with prefix  ```operator.serverless.openshift.io/``` for Serving & Eventing have changed. cc @pierDipi

2023-04-05 14:25 UTC, mgencur requested changes
Hey @rh-max , I've stopped commenting.  We should be changing only group `operator.knative.dev`  to v1beta1. No other groups. There are many places in this PR where other groups are changed.

2023-04-05 14:25 UTC, mgencur commented on modules/serverless-configuring-event-delivery-examples.adoc
> +        apiVersion: eventing.knative.dev/v1beta1
Only operator.knative.dev (KnativeServing,KnativeEventing) should be changed. Not `eventing.knative.dev`

2023-04-05 14:58 UTC, mgencur commented
LGTM. I'm not able to tell if all occurrences were changed but I trust you :)

2023-04-05 14:59 UTC, rh-max commented
Hey @skonto and @mgencur , thanks.

Stavros, I implemented Martin's version, so the change to `v1beta1` is now only in `operator.knative.dev` examples. You wrote something different (`operator.serverless.openshift.io/`), let me know if you disagree with the current version.

2023-04-05 15:06 UTC, rh-max commented
/label serverless
/label peer-review-needed

2023-04-05 18:38 UTC, lahinson commented
/remove-label peer-review-needed
/label peer-review-in-progress

2023-04-05 18:38 UTC, lahinson reviewed
lgtm

2023-04-05 18:39 UTC, lahinson commented
/remove-label peer-review-in-progress
/label peer-review-done

2023-04-06 09:36 UTC, rh-max commented
/label merge-review-needed

2023-04-06 14:34 UTC, maxwelldb approved these changes
Spot checked in preview, e.g. https://58245--docspreview.netlify.app/openshift-enterprise/latest/serverless/admin_guide/serverless-configuration.html.

2023-04-06 14:35 UTC, maxwelldb commented
/cherry-pick enterprise-4.8

2023-04-06 14:35 UTC, maxwelldb commented
/cherry-pick enterprise-4.9

2023-04-06 14:35 UTC, maxwelldb commented
/cherry-pick enterprise-4.10

2023-04-06 14:35 UTC, maxwelldb commented
/cherry-pick enterprise-4.10

2023-04-06 14:36 UTC, maxwelldb commented
/cherry-pick enterprise-4.11

2023-04-06 14:36 UTC, maxwelldb commented
/cherry-pick enterprise-4.12

2023-04-06 14:36 UTC, maxwelldb commented
/cherry-pick enterprise-4.13

2023-04-06 14:36 UTC, merged