[RHDEVDOCS-5040] Bump up image folder versions for pipelines 1.10 release
openshift/openshift-docs pull request #58250
Opened 2023-04-05 13:20 UTC by SNiemann15

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-04-06 06:02 UTC, ppitonak requested changes

2023-04-06 06:02 UTC, ppitonak commented on modules/op-installing-pipelines-as-code-cli.adoc
> +You can install the `tkn pac` and `opc` version `1.10.1` binaries for the supported platforms:
This should be 1.10.0

2023-04-06 08:10 UTC, rupalibehera commented
LGTM

2023-04-06 10:42 UTC, ppitonak approved these changes
lgtm

2023-04-06 10:47 UTC, shipsing approved these changes
LGTM @SNiemann15

2023-04-06 10:54 UTC, shipsing commented
A generic question, if i look at the compatibility matrix here: http://dashboard.apps.cicd.ospqa.com/releases/componentmatrix/, i see the compatible OCP versions for pipelines 1.10 are 4.11, 4.12, 4.13. In the PR, do we need to change the version for cherry-picking to 4.11+, instead of 4.12+ ?

2023-04-14 14:33 UTC, concaf approved these changes

2023-04-14 15:07 UTC, merged

2023-04-14 15:08 UTC, rolfedh commented
/cherrypick enterprise-4.12

2023-04-14 15:08 UTC, rolfedh commented
/cherrypick enterprise-4.13