CNF-6351 updating agent based install
openshift/openshift-docs pull request #58492
Opened 2023-04-11 09:36 UTC by kquinn1204

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-04-11 10:47 UTC, cgoncalves requested changes

2023-04-11 10:47 UTC, cgoncalves commented on modules/installing-ocp-agent-boot.adoc
> +$ sudo dnf install http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/nmstate-1.4.2-4.el8.x86_64.rpm http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/python3-l
This should definitely not be documented. I took this step just to confirm that a newer nmstate version worked.

2023-04-11 11:25 UTC, kquinn1204 commented
@cgoncalves I moved to just one note in the appropriate section and removed the extra guidance about upgrading the nmstate version.

2023-04-12 09:40 UTC, cgoncalves requested changes

2023-04-12 09:40 UTC, cgoncalves commented on modules/nw-sriov-dual-nic-con.adoc
> +* `2.2.7` for RHEL versions `9.2` or higher.
1.4.2-4 for RHEL 8 versions
2.2.7 for RHEL 9 versions

2023-04-12 11:45 UTC, cgoncalves commented
/lgtm

2023-04-12 11:52 UTC, kquinn1204 commented
/label telco

2023-04-12 11:52 UTC, kquinn1204 commented
/label peer-review-needed

2023-04-12 18:28 UTC, JoeAldinger reviewed
/lgtm

2023-04-13 08:10 UTC, kquinn1204 commented
/label merge-review-needed

2023-04-13 15:06 UTC, abhatt-rh commented
/label merge-review-in-progress

2023-04-13 15:33 UTC, merged

2023-04-13 15:33 UTC, abhatt-rh commented
/cherrypick enterprise-4.13