OSDOCS-4906: Adding oc-mirror OCI GA to RNs
openshift/openshift-docs pull request #58933
Opened 2023-04-18 18:05 UTC by bergerhoffer

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-05-03 13:09 UTC, bergerhoffer commented
@sherine-k @zhouying7780 Can you please review?

Preview: https://58933--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html#ocp-4-13-installation-oc-mirror-oci-ga

2023-05-03 13:15 UTC, bergerhoffer commented
/label peer-review-needed

2023-05-03 14:15 UTC, sjhala-ccs reviewed
LGTM

2023-05-04 07:50 UTC, zhouying7780 commented
/lgtm

2023-05-04 10:49 UTC, sherine-k requested changes
Hi @bergerhoffer 
I spotted just a few nits... nothing major. 
Thanks so much

2023-05-04 10:49 UTC, sherine-k commented on release_notes/ocp-4-13-release-notes.adoc
> +This release introduces support for the following features when using the OCI feature:
```suggestion
This release introduces support for the following features when local oci catalogs are included:
```

2023-05-04 10:49 UTC, sherine-k commented on release_notes/ocp-4-13-release-notes.adoc
> +* If you used the Technology Preview OCI feature for the oc-mirror plugin for OpenShift Container Platform 4.12, you can no longer use the OCI feature of the oc-mirror plugin to create an image set a
```suggestion
* If you used the Technology Preview OCI local catalogs feature for the oc-mirror plugin for OpenShift Container Platform 4.12, you can no longer use the OCI feature of the oc-mirror plugin to copy the catalog image locally as a first step to mirroring to a fully disconnected cluster.
```

2023-05-09 01:20 UTC, zhouying7780 commented
/lgtm

2023-05-09 09:33 UTC, sherine-k approved these changes
Thank you so much @bergerhoffer

2023-05-09 13:40 UTC, merged