RHDEVDOCS-2671 - Logging support considerations
openshift/openshift-docs pull request #59109
Opened 2023-04-20 20:01 UTC by libander

Version(s):

Issue: RHDEVDOCS-2671 

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-04-20 20:05 UTC, jcantrill commented on modules/logging-support-considerations.adoc
> +* Designed for optional use with low retention managed centralized storage.
everything lgtm  other then I do not understand what this bullet means

2023-04-25 15:51 UTC, libander commented
@r2d2rnd - Any feedback?

2023-04-27 07:23 UTC, r2d2rnd commented
Many thanks for this. It looks good to me

2023-04-27 08:38 UTC, anpingli reviewed
/lgtm

2023-04-27 10:39 UTC, shipsing requested changes
@libander Please see my suggestions. Thanks

2023-04-27 18:26 UTC, libander commented on modules/logging-support-considerations.adoc
> +* *Changes to secrets or configmaps not specified in the documentation.*
> Why did we bold the text? Is there any recommendation to highlight this piece of information? 

https://docs.openshift.com/container-platform/4.12/monitoring/configuring-the-monitoring-stack.html#support-considerations_configuring-the-monitoring-stack - was used as a reference per the request of Support Engineering.

2023-04-27 18:37 UTC, libander commented on modules/logging-support-considerations.adoc
> +* An opinionated collector and normalizer of application, infrastructure, and audit logs.
Opinionated has a well understood meaning in the context of software and is not prohibited by the IBM Style Guide, Red Hat Supplementary Style Guide, or the OpenShift Contribution Guide glossary.

2023-04-28 16:19 UTC, merged

2023-04-28 16:20 UTC, rolfedh commented
/cherrypick enterprise-4.11

2023-04-28 16:20 UTC, rolfedh commented
/cherrypick enterprise-4.13