CNV-22041: RN for VM export manifests
openshift/openshift-docs pull request #59862
Opened 2023-05-10 18:05 UTC by ousleyp

Version(s): 4.13 only/no CP

Issue: CNV-22041

Link to docs preview: http://file.rdu.redhat.com/pousley/CNV-22041/virt/virt-4-13-release-notes.html#virt-4-13-new

QE review:
- [ ] QE has approved this change.

2023-05-10 20:11 UTC, bergerhoffer reviewed
Minor suggestion, but LGTM!

2023-05-10 20:11 UTC, bergerhoffer commented on virt/virt-4-13-release-notes.adoc
> +* You can now obtain the `VirtualMachine`, `DataVolume`, and `ConfigMap` manifests from the export server after you export a VM or snapshot. Learn more about xref:../virt/virtual_machines/virt-export
Totally fine if you use this wording often other places, but the "Learn more about" sounds slightly off to me. I think people more often do the "For more information, see <link>."  wording

2023-05-11 06:20 UTC, jpeimer requested changes

2023-05-11 06:20 UTC, jpeimer commented on virt/virt-4-13-release-notes.adoc
> +* You can now obtain the `VirtualMachine`, `DataVolume`, and `ConfigMap` manifests from the export server after you export a VM or snapshot. For more information, see xref:../virt/virtual_machines/vi
```suggestion
* You can now obtain the `VirtualMachine`, `ConfigMap`, and `Secret` manifests from the export server after you export a VM or snapshot. For more information, see xref:../virt/virtual_machines/virt-exporting-vms.adoc#virt-accessing-exported-vm-manifests_virt-exporting-vms[accessing exported VM manifests].
```

2023-05-11 16:18 UTC, jpeimer approved these changes
Thanks, Pan!
/lgtm

2023-05-11 16:18 UTC, merged