OSDOCS#5975: Custom RHCOS image for control plane and compute machines
openshift/openshift-docs pull request #60348
Opened 2023-05-22 14:16 UTC by mjpytlak

Version(s):
4.14+

Issue:
This PR addresses [osdocs-5975](https://issues.redhat.com/browse/OSDOCS-5975).

Link to docs preview:

- [Additional Google Cloud Platform (GCP) configuration parameters](https://60348--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations.html#installation-configuration-parameters-additional-gcp_installing-gcp-customizations)
- [Sample customized install-config.yaml file for GCP](https://60348--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations.html#installation-gcp-config-yaml_installing-gcp-customizations)
- [Using a GCP Marketplace image](https://60348--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations.html#installation-gcp-marketplace_installing-gcp-customizations)

QE review:
- [ ] QE has approved this change.

2023-05-22 21:46 UTC, mjpytlak commented
@AnnaZivkovic @r4f4 Draft docs ready for SME review.

@nirfarkas Do you ever get any feedback on your question about the use of the `Licenses` field? See your comment from 5/5/20023 in https://issues.redhat.com/browse/CORS-2445. Not sure if docs has to state anything explicitly.

2023-05-23 13:06 UTC, r4f4 commented
Replied on Slack, but for the record: the Licenses field will be incompatible with specifying boot images.

2023-05-30 15:33 UTC, mjpytlak commented
> Replied on Slack, but for the record: the Licenses field will be incompatible with specifying boot images.

@r4f4 Thanks for the update. I cannot seem to find the reply in Slack. Based on this, I do not think there is anything else left to say, correct. If not, PTAL at the draft content when you have a moment.

@AnnaZivkovic PTAL as well. Thank you.

2023-05-30 15:46 UTC, r4f4 commented
/lgtm

2023-06-02 21:48 UTC, AnnaZivkovic commented
LGTM

2023-06-08 16:22 UTC, mjpytlak commented
@jianli-wei Ready for QE review. PTAL.

2023-06-09 02:19 UTC, jianli-wei requested changes

2023-06-09 02:19 UTC, jianli-wei commented on modules/installation-configuration-parameters.adoc
> +|`controlPlane.platform.gcp.osimage.project`
Shall `osimage.project` be `osImage.Project` instead? FYI the [PR](https://github.com/openshift/installer/pull/7215/).

2023-06-09 02:19 UTC, jianli-wei commented on modules/installation-configuration-parameters.adoc
> +|`controlPlane.platform.gcp.osimage.name`
Similarly, shall `osimage.name` be `osImage.Name`?

2023-07-05 08:09 UTC, jianli-wei requested changes

2023-07-05 08:09 UTC, jianli-wei commented on modules/installation-gcp-config-yaml.adoc
> +        name: example-image-name
"osimage" => "osImage"?
"project" => "Project"?
"name" => "Name"?

2023-07-05 08:09 UTC, jianli-wei commented on modules/installation-gcp-config-yaml.adoc
> +          name: example-image-name
Similar to the above, thanks!

2023-07-05 08:09 UTC, jianli-wei commented on modules/installation-gcp-config-yaml.adoc
> +        name: example-image-name
Similar to the above, thanks!

2023-07-05 08:09 UTC, jianli-wei commented on modules/installation-gcp-config-yaml.adoc
> +<7> Optional: A custom {op-system-first} that should be used to boot control plane and compute machines. The `project` and `name` parameters under `platform.gcp.defaultMachinePlatform.osimage` apply
Similar to the above, thanks!

2023-07-05 08:09 UTC, jianli-wei commented on modules/installation-gcp-marketplace.adoc
> +** Set the `name` parameter to one of the following offers:
Similar to the above, thanks!

2023-07-05 08:10 UTC, jianli-wei commented
> Update the parameter names. Please take one more look.

@mjpytlak Sorry for the late reply, some minor suggestions, could you please update again? Thanks in advance!

2023-07-13 16:18 UTC, mjpytlak commented
> Sorry for the late reply, some minor suggestions, could you please update again? Thanks in advance!

Thanks @jianli-wei I believe this should do it. PTAL.

2023-07-14 07:47 UTC, r4f4 commented
/hold
Patrick suggested in the PR the fields should be lowercase

2023-07-17 19:16 UTC, mjpytlak commented
@r4f4 Thanks for info. Reverted all instances of `Project` and `Name` to `project` and `name`. PTAL.

2023-07-17 21:27 UTC, r4f4 commented
/lgtm
but let's wait a bit to make sure there will be no more changes in the Installer PR.

2023-07-31 06:24 UTC, jianli-wei commented
/label qe-approved

2023-07-31 12:54 UTC, mjpytlak commented
@r4f4 PTAL and remove the merge hold, please. :smile:

2023-07-31 13:12 UTC, r4f4 commented
/hold cancel
My bad, forgot about this.

2023-07-31 18:42 UTC, nalhadef commented
/label peer-review-in-progress
/remove-label peer-review-needed

2023-07-31 19:08 UTC, nalhadef commented on modules/installation-gcp-marketplace.adoc
> +Using the GCP Marketplace offering lets you deploy an {product-title} cluster, which is billed on pay-per-use basis (hourly, per core) through GCP, while still being supported directly by Red Hat.
Need a nonbreaking space between "Red" and "Hat?"
![image](https://github.com/openshift/openshift-docs/assets/83772007/16999161-cf47-4d8f-a59f-9b5d424150df)[
]
(https://redhat-documentation.github.io/supplementary-style-guide/#introduction)

2023-07-31 19:09 UTC, nalhadef commented
One small comment, @mjpytlak.

2023-07-31 19:09 UTC, nalhadef commented
/lgtm

2023-07-31 19:09 UTC, nalhadef commented
/remove-label peer-review-in-progress
/label peer-review-done

2023-08-02 20:12 UTC, mjpytlak commented
Thanks for catching the new requirement @nalhadef. Updated.

2023-08-02 20:18 UTC, merged

2023-08-02 20:18 UTC, mjpytlak commented
/cherrypick enterprise-4.14