OSDOCS-6051: Known Issue for Nutanix 4.13 update
openshift/openshift-docs pull request #60472
Opened 2023-05-23 19:29 UTC by skopacz1

[OSDOCS-6051](https://issues.redhat.com/browse/OSDOCS-6051)

This PR adds a known issue to the 4.13 Release Notes, regarding 4.12 Nutanix clusters that report as Upgradeable=False due to missing configuration needed to integrate Nutanix CCM. This issue only applies to Nutanix clusters updating from 4.12 to 4.13. Once the configuration is made, further updates should not encounter this same condition. Nutanix clusters installed on 4.13 also should not have this issue.

This PR will go through change management in addition to the typical review cycle.

QE review:
- [ ] QE has approved this change.

Preview:

2023-05-23 19:37 UTC, skopacz1 commented
🚨 **_Note to all reviewers_**  🚨

The corresponding bug ticket ([OCPBUGS-7898](https://issues.redhat.com/browse/OCPBUGS-7898)) linked in OSDOCS-6051 has a Red Hat Employee level of security, and thus will not be linked in the RN entry since customers won't be able to read it anyways. Please let me know if there is a bug ticket that I should link to instead.

One possible alternative would be [OCPBUGS-9984](https://issues.redhat.com/browse/OCPBUGS-9984), which was closed as a duplicate of 7898 but does not have the same security level. Would this be an acceptable substitution?

2023-05-24 13:53 UTC, elmiko reviewed
this change lgtm

2023-05-24 14:16 UTC, LalatenduMohanty requested changes

2023-05-24 16:06 UTC, LalatenduMohanty approved these changes
/lgtm

2023-05-24 20:12 UTC, skopacz1 commented
Hi everyone! I'm tagging you all in my PR because it needs to go through documentation change management, and you are all stakeholders that need to be notified as part of this process. If you are tagged in this comment, could you please leave any feedback you may have, and otherwise leave a comment if the PR looks good? 

Thanks in advance!

@sferich888 @xltian @kalexand-rh @sjstout @sub-mod

2023-05-24 20:15 UTC, skopacz1 commented
@sunzhaohua2 and @shellyyang1989 could you PTAL? Thanks!

2023-05-25 02:47 UTC, shellyyang1989 commented
Looks good to me

2023-05-25 15:34 UTC, kalexand-rh commented
From a CM perspective, this LGTM.

2023-05-31 15:50 UTC, sferich888 commented
/lgtm
However as a tangent I wonder if these instructions should be in a KCS and not in our upgrade docs (for nutanix) as this is a new requirement that must be done when upgrading.

2023-05-31 16:23 UTC, skopacz1 commented
@sferich888 thanks for your acknowledgement! As to your point about the KCS, @wking provides a comprehensive rationale for limiting this doc fix to a Release Note with a link to the KCS in the corresponding Jira Issue: https://issues.redhat.com/browse/OSDOCS-6051

The TLDR, though, is that we generally want to avoid using the more generic update docs as a space to describe every possible `Upgradeable=False` condition. And in this case, where it is an issue with a one-time workaround/fix, only for clusters going from 4.12 to 4.13, and only for Nutanix clusters, we felt that this would not be a justified exception to that general rule. Let me know if you have any questions!

2023-06-08 00:24 UTC, xltian commented
lgtm

2023-06-08 18:02 UTC, sub-mod commented
LGTM

2023-06-12 16:49 UTC, JoeAldinger reviewed
small minimalism suggestion

2023-06-12 16:49 UTC, JoeAldinger commented on release_notes/ocp-4-13-release-notes.adoc
> +* {product-title} 4.12 clusters on the Nutanix platform may have an `Upgradeable=False` condition if they are missing configuration needed for the Nutanix Cloud Control Manager (CCM). To resolve this
```suggestion
* {product-title} 4.12 clusters on the Nutanix platform may have an `Upgradeable=False` condition if they are missing configuration needed for the Nutanix Cloud Control Manager (CCM). To resolve this condition, see: link:https://access.redhat.com/solutions/7014068[How to create the ConfigMaps and Secrets needed to upgrade to OpenShift 4.13 when using Nutanix as a Platform].
```

2023-06-12 21:25 UTC, sjstout commented
LGTM!

2023-06-14 16:03 UTC, skopacz1 commented
/label peer-review-needed

2023-06-15 14:28 UTC, mjpytlak reviewed
@skopacz1 peer review lgtm.

2023-06-15 18:58 UTC, merged