OSDOCS#6116: Add RWOP access mode
openshift/openshift-docs pull request #60556
Opened 2023-05-25 14:06 UTC by lpettyjo

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-05-26 10:24 UTC, aireilly commented
/remove-label peer-review-needed

2023-05-26 12:14 UTC, aireilly requested changes
Good work on a tricky subject! Left a few general comments. 

Please consider correcting the hard line breaks in the file. It makes reviews harder and can lead to unintended output errors.

2023-05-26 12:14 UTC, aireilly commented on modules/storage-persistent-storage-pv.adoc
> +|ReadWriteOncePod ^[1]^
Also a general comment. Is ReadWriteOncePod the actual name of the feature?

Consider "`ReadWriteOncePod` access mode for `PersistentVolume` resources" as a better name for the feature.

2023-05-26 12:14 UTC, aireilly commented on modules/storage-persistent-storage-pv.adoc
> +|Volume plugin  |ReadWriteOnce ^[1]^ | ReadWriteOncePod ^[2]^ |ReadOnlyMany|ReadWriteMany
Nit: I'd prefer to see actual AsciiDoc footnotes here.

2023-05-26 12:15 UTC, aireilly commented on modules/storage-persistent-storage-pv.adoc
>  |ReadWriteOnce
General comment about the access modes fields. IMO these should be marked with backticks since they refer to fields on a PV resource.

2023-05-26 12:16 UTC, aireilly commented
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed

2023-05-26 12:18 UTC, aireilly commented on modules/storage-persistent-storage-pv.adoc
> +For example, NFS offers `ReadWriteOnce` access mode. You must
Also, is `read-only` a valid access mode? https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

2023-08-07 09:20 UTC, gcharot commented on modules/storage-persistent-storage-pv.adoc
>  The following table lists the access modes:
Since we're listing the different access mode and what they do we should also add ReadWriteMany & ReadOnlyMany.

2023-08-14 15:04 UTC, radeore commented on modules/storage-persistent-storage-pv.adoc
> +:FeatureName: ReadWriteOnlyPod access node for persistent volumes
Couple of typo, need to update 'ReadWriteOnlyPod' to 'ReadWriteOncePod' and 'node' to 'mode'

2023-08-28 11:51 UTC, jsafrane commented
LGTM

2023-09-12 04:00 UTC, radeore commented
LGTM

2023-09-12 09:33 UTC, gcharot commented
LGTM

2023-09-13 00:33 UTC, merged

2023-09-13 00:34 UTC, lpettyjo commented
/cherrypick enterprise-4.14