SRVCOM-2474 Add docs on locking kn CLI version, and on upgrading after locking
openshift/openshift-docs pull request #60663
Opened 2023-05-30 12:11 UTC by rh-max

Version(s):
Serverless 1.29+

Issue:
https://issues.redhat.com/browse/SRVCOM-2474

Link to docs preview:

QE review:
- [ ] QE has approved this change.

2023-05-30 12:23 UTC, rh-max commented
@dsimansk @cardil Could you PTAL?

2023-05-30 16:11 UTC, cardil requested changes

2023-06-02 09:09 UTC, gabriel-rh approved these changes
LGTM

2023-06-02 09:09 UTC, merged

2023-06-02 09:10 UTC, gabriel-rh commented
/cherry-pick serverless-docs-1.29