OSDOCS-6390: Delete deployments running under the cert-manager namespace
openshift/openshift-docs pull request #60837
Opened 2023-06-05 14:51 UTC by xenolinux

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-06-08 12:26 UTC, swghosh commented
@xenolinux Need to change the sequence a bit from functionality point,
- deployment removal should be first step and please make it non-optional i.e. via avoiding wordings like "alternatively" and or "optionally"
- plus, the section about removal the first part says "optionally", can we change it a bit? Deleting CRDs like certificates, issuers, etc. can be optional but the deployment deletion and that section in general should be mandated

Let me know if you have any further queries.

2023-06-14 11:08 UTC, xenolinux commented
> @xenolinux Need to change the sequence a bit from functionality point,
> 
>     * deployment removal should be first step and please make it non-optional i.e. via avoiding wordings like "alternatively" and or "optionally"
> 
>     * plus, the section about removal the first part says "optionally", can we change it a bit? Deleting CRDs like certificates, issuers, etc. can be optional but the deployment deletion and that section in general should be mandated
> 
> 
> Let me know if you have any further queries.

@swghosh Addressed changes. I adjusted the usage of "optional" and the sequence.

2023-06-14 15:21 UTC, swghosh approved these changes
Minor nit, otherwise lgtm.
Thanks again!

2023-06-16 07:42 UTC, swghosh commented
/lgtm
@xingxingxia please review for QE approval, TIA!

2023-06-20 08:19 UTC, xingxingxia requested changes
LGTM from QE side except below comments.

2023-06-20 08:19 UTC, xingxingxia commented on modules/cert-manager-remove-resources-console.adoc
> +. Delete deployments of the cert-manager components such as `cert-manager`, `cainjector` and `webhook` present in the `cert-manager` namespace by using the command-line interface (CLI).
If previous `Remove the deployments of the cert-manager components ...` in web console is done, then it already does what `Delete deployments of the cert-manager components ...` by CLI will do. By console and by CLI are equivalent.
```suggestion
. Alternatively, delete deployments of the cert-manager components such as `cert-manager`, `cainjector` and `webhook` present in the `cert-manager` namespace by using the command-line interface (CLI).
```

2023-06-20 08:23 UTC, xenolinux commented
@xingxingxia Addressed comments

2023-06-20 08:45 UTC, xingxingxia commented
LGTM from QE side.
/lgtm

2023-06-20 08:54 UTC, xenolinux commented
/label peer-review-needed

2023-06-20 12:21 UTC, snarayan-redhat reviewed
Looks good. Few suggestions.

2023-06-20 12:21 UTC, snarayan-redhat commented on modules/cert-manager-remove-resources-console.adoc
> +. Optional: Remove CRDs that were installed by the {cert-manager-operator}:
```suggestion
. Optional: Remove the custom resource definitions (CRDs) that were installed by the {cert-manager-operator}:
```

2023-06-20 16:02 UTC, xenolinux commented
/label merge-review-needed

2023-06-20 16:06 UTC, merged

2023-06-20 16:06 UTC, snarayan-redhat commented
/cherrypick enterprise-4.12