updated the pipelines version
openshift/openshift-docs pull request #60832
Opened 2023-06-05 07:26 UTC by krishnanshruthi

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-06-13 13:43 UTC, ppitonak requested changes

2023-06-13 13:43 UTC, ppitonak commented on modules/op-installing-pipelines-as-code-cli.adoc
> +* link:https://mirror.openshift.com/pub/openshift-v4/clients/pipeline/1.11.0/tkn-linux-amd64.tar.gz[Linux (x86_64, amd64)]
1.10 binaries are uploaded on URL with both `pipeline` and `pipelines` in path. We could update it to `pipelines` in this doc for 1.11, it's closer to official product name.

2023-06-14 08:56 UTC, ppitonak approved these changes

2023-06-15 07:55 UTC, shipsing commented
@krishnanshruthi the changes look good to me.
But, I found 4 instances of 1.10 here: https://60832--docspreview.netlify.app/openshift-enterprise/latest/cli_reference/tkn_cli/installing-tkn.html#installing-tkn-on-linux-using-rpm

Do we need to update those instances to 1.11?
 subscription-manager repos --enable="pipelines-1.10-for-rhel-8-s390x-rpms" to  subscription-manager repos --enable="pipelines-1.11-for-rhel-8-s390x-rpms"

cc @ppitonak

2023-06-15 08:56 UTC, SNiemann15 commented
> @krishnanshruthi the changes look good to me. But, I found 4 instances of 1.10 here: https://60832--docspreview.netlify.app/openshift-enterprise/latest/cli_reference/tkn_cli/installing-tkn.html#installing-tkn-on-linux-using-rpm
> 
> Do we need to update those instances to 1.11? subscription-manager repos --enable="pipelines-1.10-for-rhel-8-s390x-rpms" to subscription-manager repos --enable="pipelines-1.11-for-rhel-8-s390x-rpms"
> 
> cc @ppitonak

Good catch @shipsing We missed those.

2023-06-15 09:04 UTC, ppitonak commented
Yes, it needs to be updated, too.

2023-06-15 09:05 UTC, krishnanshruthi commented
Replaced the 1.10 instances in https://60832--docspreview.netlify.app/openshift-enterprise/latest/cli_reference/tkn_cli/installing-tkn.html#installing-tkn-on-linux-using-rpm in the latest commit: https://github.com/openshift/openshift-docs/pull/60832/commits/b603cb4aac126d8e200011cc9d2a3b0d9fc71068

cc: @shipsing , @ppitonak , @SNiemann15

2023-06-16 14:55 UTC, abrennan89 reviewed
/lgtm

Confirming if QE have approved before merging

2023-06-16 15:20 UTC, merged

2023-06-16 15:20 UTC, abrennan89 commented
/cherrypick enterprise-4.14

2023-06-16 15:20 UTC, abrennan89 commented
/cherrypick enterprise-4.13

2023-06-16 15:20 UTC, abrennan89 commented
/cherrypick enterprise-4.12