OADP-1306 backup storage location noobaa bucket secret hvider
openshift/openshift-docs pull request #61424
Opened 2023-06-19 15:38 UTC by HagayVider1

GH# : 
OCPBUGS# : [OADP-1306](https://issues.redhat.com//browse/OADP-1306)
OSDOCS# : [OADP-1306](https://issues.redhat.com//browse/OADP-1306)

Version(s): OADP-1.2.1

Issue: https://issues.redhat.com/browse/OADP-1306

Link to docs preview: https://61901--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.html#oadp-about-backup-snapshot-locations_installing-oadp-azure

QE review:
- [ ] QE has approved this change.

Additional information:

2023-06-19 15:53 UTC, HagayVider1 commented
@weshayutin @kaovilai 
See added sections:
* Create noobaa bucket for backups
* Creating a Secret for backupStorageLocation

Replaces PR# 61081

2023-06-20 21:11 UTC, kaovilai requested changes

2023-06-20 21:11 UTC, kaovilai commented on modules/oadp-about-backup-snapshot-locations-secrets.adoc
> +app:                noobaa
Indents are incorrect.

2023-07-03 17:41 UTC, kaovilai commented on modules/oadp-about-backup-snapshot-locations-secrets.adoc
> +app:                noobaa
@HagayVider1 where did you get these from? is there a source document you could reference to fix the indents here?

2023-10-10 03:53 UTC, kaovilai commented
/remove-lifecycle stale

2024-06-10 08:01 UTC, closed without merging