CNV -28700: Update VM static IP YAML
openshift/openshift-docs pull request #61905
Opened 2023-06-29 13:21 UTC by apinnick

Version(s): 4.10+

Issue: CNV-28700

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-07-03 12:25 UTC, phoracek requested changes

2023-07-05 15:25 UTC, GroceryBoyJr reviewed
LGTM

2023-07-05 15:25 UTC, GroceryBoyJr commented
/remove-label peer-review-needed
/label peer-review-done

2023-07-05 15:52 UTC, merged

2023-07-05 15:52 UTC, apinnick commented
/cherrypick enterprise-4.12

2023-07-05 15:52 UTC, apinnick commented
/cherrypick enterprise-4.13

2023-07-05 15:52 UTC, apinnick commented
/cherrypick enterprise-4.14