add documentation for template.openshift.io/bindable
openshift/openshift-docs pull request #6206
Opened 2017-11-07 17:45 UTC by jim-minter

3.7.  After https://github.com/openshift/origin/pull/17215 has merged.
@bmcelvee @bparees

2017-11-07 17:52 UTC, bparees requested changes

2017-11-07 17:52 UTC, bparees commented on dev_guide/templates.adoc
> +The template service broker advertises one service in its catalogue for each
s/catalogue/catalog/  (sorry)

2017-11-07 17:52 UTC, bparees commented
one nit and lgtm.

2017-11-07 17:56 UTC, jim-minter commented
nit fixed, thanks

2017-11-07 20:24 UTC, bmcelvee commented
Thanks, @jim-minter! Looks like has merged, so I'll move forward with this PR. Label for enterprise-3.7, dedicated (3.7), and online (3.7)?

2017-11-09 18:03 UTC, jim-minter commented
@bmcelvee sgtm!

2017-11-09 18:42 UTC, bmcelvee commented
[rev_history]
|xref:../dev_guide/templates.adoc#dev-guide-templates[Templates]
|Added xref:../dev_guide/templates.adoc#writing-marking-templates-as-bindable[Marking Templates as Bindable] section.
%

2017-11-09 18:42 UTC, merged