TELCODOCS-1111: D/S: OCPVE-218 LVMO recover from failure
openshift/openshift-docs pull request #63394
Opened 2023-08-09 20:23 UTC by johnwilkins

Added troubleshooting for persistent volumes.

Fixes: TELCODOCS-1111

See https://issues.redhat.com/browse/TELCODOCS-1111 for additional details.

Preview URL: http://jowilkin.com:8080/TELCODOCS-1111/welcome/index.html

For release(s): 4.14, 4.13, 4.12
QE Review: 

- [ ] QE has approved this change. 

Signed-off-by: John Wilkins <jowilkin@redhat.com>

2023-08-09 20:38 UTC, johnwilkins commented
@suleymanakbas91 @radeore can you have a look at this?

2023-08-10 19:55 UTC, radeore commented
Recovery procedures looks good to me. Since, this section is specific to persistent storage using LVMS, should it be placed under http://184.23.213.161:8080/TELCODOCS-1111/storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.html ? cc. @suleymanakbas91

2023-08-11 14:01 UTC, suleymanakbas91 requested changes

2023-08-11 14:01 UTC, suleymanakbas91 commented on modules/lvms-troubleshooting-recovering-from-missing-lvm-storage-or-operator-components.adoc
> +Sometimes the cluster is stuck in a state where it has lost the volume group. If you encounter a storage class "not found" error, check the `LVMCluster` resource and ensure that all the LVM Storage (
I didn't quite understand this sentence: `Sometimes the cluster is stuck in a state where it has lost the volume group`. Can we maybe delete it?

2023-08-14 20:00 UTC, johnwilkins commented
/label peer-review-needed

2023-08-14 20:29 UTC, johnwilkins commented
> @johnwilkins Is it possible if we can place it under section "Persistent storage using local storage", right after "Persistent storage using LVM storage"?

That's where I placed it. Re-click the preview hyperlink, because it's in a different location. I think reload will just have the old cache copy.

2023-08-14 20:33 UTC, radeore commented
> > @johnwilkins Is it possible if we can place it under section "Persistent storage using local storage", right after "Persistent storage using LVM storage"?
> 
> @radeore That's where I placed it. Re-click the preview hyperlink, because it's in a different location. I think reload will just have the old cache copy.

Somehow I couldn't see it updated earlier, now I can see the change in pre-view. Thanks!

2023-08-14 20:33 UTC, radeore commented
/lgtm

2023-08-15 12:39 UTC, ShaunaDiaz commented
/remove-label peer-review-needed

2023-08-15 15:04 UTC, ShaunaDiaz reviewed
Please squash your commits down to one. Otherwise, left some comments and suggestions. Nice work!

2023-08-15 15:04 UTC, ShaunaDiaz commented on modules/lvms-troubleshooting-recovering-from-node-failure.adoc
> ++
```suggestion
+
.Example output
```

2023-08-15 15:04 UTC, ShaunaDiaz commented on modules/lvms-troubleshooting-recovering-from-node-failure.adoc
> +After resolving the issue with the node, if the problem persists and reoccurs, it may be necessary to perform the forced cleanup procedure.
```suggestion
After you resolve any issues with the node, you might need to perform the forced cleanup procedure if the PVC is still stuck in a `Pending` state.
```

2023-08-15 15:05 UTC, ShaunaDiaz commented
@ousleyp Would you please verify my peer review and then switch the peer-review-in-progress label for the peer-review-done label? Thank you!

2023-08-15 18:34 UTC, ousleyp reviewed
I generally +1 all of @ShaunaDiaz 's comments on this, with a few exceptions that I commented on. I wasn't able to look extremely closely at this due to some other things going on today, so I'd recommend a follow-up peer review after you make changes from this first round. Thanks!

2023-08-15 22:00 UTC, johnwilkins commented
/label merge-review-needed

2023-08-16 15:08 UTC, skrthomas commented
Merge review LGTM.

2023-08-16 15:08 UTC, merged

2023-08-16 15:08 UTC, skrthomas commented
/cherrypick enterprise-4.13

2023-08-16 15:09 UTC, skrthomas commented
/cherrypick enterprise-4.12