remove incorrect note about scheduled import
openshift/openshift-docs pull request #6344
Opened 2017-11-13 19:47 UTC by bparees

2017-11-13 19:48 UTC, bparees commented
according to @smarterclayton this note isn't accurate (scheduled import is *enabled* by default).  That matches what i see when i do an openshift start --write-config (the config contains disabled=false).

@soltysh @mfojtik ptal/confirm.

2017-11-14 15:34 UTC, soltysh requested changes

2017-11-14 15:34 UTC, soltysh commented on dev_guide/managing_images.adoc
> -By default, `*importPolicy.scheduled*` is disabled and must be enabled in the
Wait, there are two things mixed here. One is `importPolicy.scheduled` which is set *on an Image Stream*, per-tag to be honest. And second is the master config option `disableScheduledImport` which indeed is `false` by default. I'd suggest changing this description to explicitly mention that the IST's `scheduled` is disabled, and needs to be enabled explicitly.

2017-11-14 15:42 UTC, soltysh commented
I've just spoke with @bparees on IRC, give the context of this change, this LGTM.

2017-11-14 15:42 UTC, soltysh approved these changes

2017-11-14 15:43 UTC, bparees commented
@openshift/team-documentation got confirmation from @soltysh on irc, please merge.

2017-11-14 17:12 UTC, bmcelvee commented
No revision history needed.

2017-11-14 17:12 UTC, merged