BZ2229164: Minor update to bridge NAD YAML
openshift/openshift-docs pull request #63552
Opened 2023-08-14 16:52 UTC by sjhala-ccs

Version(s): 4.12+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2229164

Link to docs preview:

QE review:
- [ ] QE has approved this change.

2023-08-15 21:17 UTC, yossisegev commented
/lgtm
(CNV network QE)

2023-08-16 15:22 UTC, phoracek commented on modules/virt-creating-linux-bridge-nad-cli.adoc
> +<8> Indicates whether the default VLAN must be preserved on the virtual ethernet (veth) end connected to the bridge. This must be set to `false`.
```suggestion
<8> Indicates whether the VM will be connected to the bridge through the default VLAN.
```

2023-08-16 15:25 UTC, phoracek requested changes

2023-08-16 15:25 UTC, phoracek commented on modules/virt-creating-linux-bridge-nad-cli.adoc
> +    "vlan": 1, <7>
We should make it something else than 1 (which is typically the default VLAN)

2023-08-21 13:20 UTC, sjhala-ccs commented
@phoracek I incorporated your comments. Can you please review again?

2023-08-21 13:49 UTC, stevsmit commented
lgtm

2023-08-21 18:45 UTC, phoracek approved these changes

2023-08-30 17:33 UTC, merged

2023-08-30 17:33 UTC, sjhala-ccs commented
/cherrypick enterprise-4.12

2023-08-30 17:33 UTC, sjhala-ccs commented
/cherrypick enterprise-4.13

2023-08-30 17:33 UTC, sjhala-ccs commented
/cherrypick enterprise-4.14

2023-08-30 17:43 UTC, sjhala-ccs commented
/cherrypick enterprise-4.13

2023-08-30 17:43 UTC, sjhala-ccs commented
/cherrypick enterprise-4.14