OSDOCS#7563: Custom RHCOS image for control plane and compute machines
openshift/openshift-docs pull request #63874
Opened 2023-08-23 18:40 UTC by mjpytlak

Version(s):
4.12

Issue:
This PR addresses [osdocs-7563](https://issues.redhat.com/browse/OSDOCS-7563)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:
This feature was originally planed for 4.14 and was documented by https://github.com/openshift/openshift-docs/pull/60348. However, per [CORS-2445](https://issues.redhat.com/browse/CORS-2445), there is a request to have this backported to 4.12.

2023-08-24 14:44 UTC, mjpytlak commented
@r4f4 and @jianli-wei Getting ahead of the 4.12 backport of using a custom RHCOS image when deploying a GCP cluster. This is the same content that we added for 4.14. PTAL.

@JoeAldinger When this feature ships in 4.12 z, please use the release note from https://github.com/openshift/openshift-docs/pull/63767#issuecomment-1686804160. Unclear at this point which 4.12 z release this is going out in, so nothing to do at this point.

2023-08-24 14:48 UTC, r4f4 reviewed
/lgtm

2023-08-30 13:38 UTC, mjpytlak commented
@jianli-wei Looks like we have a Jira up for the 4.12 backport. PTAL. I would like to get your approval ahead of sending out the additional requests for change management.

2023-09-06 12:47 UTC, kalexand-rh commented
From a CM perspective, LGTM.

2023-09-07 00:51 UTC, patrickdillon commented
/lgtm

2023-09-07 08:01 UTC, jianli-wei requested changes

2023-09-07 08:01 UTC, jianli-wei commented on modules/installation-gcp-marketplace.adoc
> +{product-title}:: `redhat-coreos-ocp-48-x86-64-202210040145`
According to the [KCS](https://access.redhat.com/articles/6976804), the images like `redhat-coreos-{ocp|opp|oke}-48` are for 4.12 or earlier, and 4.13+ should use `redhat-coreos-{ocp|opp|oke}-413` ones. Thanks!

2023-09-07 08:02 UTC, jianli-wei commented
/label qe-approved

2023-09-07 19:54 UTC, tmalove commented
/remove-label peer-review-needed
/label peer-review-in-progress

2023-09-07 20:04 UTC, mjpytlak commented
@JoeAldinger Looks like https://issues.redhat.com/browse/OCPBUGS-18320 is shipping in the next 4.12 z stream release on September 12th. Please use the text here for the release notes. https://github.com/openshift/openshift-docs/pull/63767#issuecomment-1686804160

2023-09-07 20:24 UTC, tmalove commented
/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

2023-09-08 08:51 UTC, xltian commented
lgtm

2023-09-08 11:49 UTC, sjstout commented
LGTM

2023-09-11 13:39 UTC, sferich888 commented
/lgtm

2023-09-12 10:52 UTC, makentenza approved these changes
LGTM

2023-09-12 11:25 UTC, merged