OCPBUGS-17088: Baremetal IPI install doc is missing required port access information
openshift/openshift-docs pull request #63913
Opened 2023-08-24 17:35 UTC by johnwilkins

Added a section for required open ports.

Fixes: OCPBUGS-17088

See https://issues.redhat.com/browse/OCPBUGS-17088 for additional details.

Preview URL: http://jowilkin.com:8080/OCPBUGS-17088/welcome/index.html

For release(s): 4.14, 4.13
QE Review: 

- [ ] QE has approved this change. 

Signed-off-by: John Wilkins <jowilkin@redhat.com>

2023-08-25 14:28 UTC, elfosardo requested changes

2023-08-25 14:28 UTC, elfosardo commented on modules/ipi-install-network-requirements.adoc
> +|`6180`| The baseboard management controllers (BMC) of the cluster nodes must be able to access the control plane nodes using port `6180`.
6180 and 6183 give access to the same backend, it's just the former is not secured, the latter is

2023-08-25 14:28 UTC, elfosardo commented on modules/ipi-install-network-requirements.adoc
> +|`6385`| The Ironic API server runs intially on the bootstrap VM and later on the control plane nodes and listens on port `6385` by default. The Ironic API allows clients to interact with Ironic for
I would mention 6388 as well with 6385

2023-08-28 07:44 UTC, elfosardo requested changes
sorry John, had to review again as I made a mistake on the exposed ports
thanks!

2023-08-28 07:44 UTC, elfosardo commented on modules/ipi-install-network-requirements.adoc
> +|`5050`, `5051`| The Ironic Inspector API runs on the control plane nodes and listens on port `5050` and on secured port `5051`. The Inspector API is responsible for hardware introspection, which col
5051 is a private port, let's not mention it

2023-08-28 07:44 UTC, elfosardo commented on modules/ipi-install-network-requirements.adoc
> +|`6180`, `6183`| The baseboard management controllers (BMC) of the cluster nodes must be able to access the control plane nodes using port `6180` or secured port `6183`.
let's say that 6183 is the preferred option and this is needed to get the inspection and deployment images

2023-08-28 07:44 UTC, elfosardo commented on modules/ipi-install-network-requirements.adoc
> +|`6385`, `6388`| The Ironic API server runs intially on the bootstrap VM and later on the control plane nodes and listens on port `6385` and secured port `6388`. The Ironic API allows clients to inte
6388 is a private, let's not mention it
6385 is used as either secured or not, the secure option is the preferred one

2023-08-29 14:25 UTC, carbonin commented
@elfosardo do we also want to mention 9999 here?

2023-08-31 07:38 UTC, elfosardo commented
> @elfosardo do we also want to mention 9999 here?

yes, let's mention it here

port 9999 is needed to reach the ironic python agent from the metal3 pod, specifically from the ironic service

2023-09-01 00:25 UTC, johnwilkins commented
@elfosardo Can you have another look. I've conflated this with TELCODOCS-1389. There are quite a few more ports we needed to document.

2023-09-10 04:35 UTC, jadhaj commented
/lgtm

2023-09-13 14:10 UTC, johnwilkins commented
/label peer-review-needed

2023-09-13 18:54 UTC, kcarmichael08 reviewed
I marked a couple of typos and a style issue. Please squash into one commit before requesting merge review. Thanks!

2023-09-13 18:54 UTC, kcarmichael08 commented on modules/ipi-install-network-requirements.adoc
> +Certain ports must be open between cluster nodes for installer-provisioned installations to compelete successfully. In certain situations, such as using separate subnets for far edge worker nodes, yo
```suggestion
Certain ports must be open between cluster nodes for installer-provisioned installations to complete successfully. In certain situations, such as using separate subnets for far edge worker nodes, you must ensure that the nodes in these subnets can communicate with nodes in other subnets on the following required ports.
```

2023-09-13 18:54 UTC, kcarmichael08 commented on modules/ipi-install-network-requirements.adoc
> +|`6385`| The Ironic API server runs intially on the bootstrap VM and later on the control plane nodes and listens on port `6385`. The Ironic API allows clients to interact with Ironic for bare metal
```suggestion
|`6385`| The Ironic API server runs initially on the bootstrap VM and later on the control plane nodes and listens on port `6385`. The Ironic API allows clients to interact with Ironic for bare metal host provisioning and management, including operations like enrolling new hosts and managing their power state, deploying images, and cleaning the hardware.
```

2023-09-13 18:54 UTC, kcarmichael08 commented on modules/ipi-install-network-requirements.adoc
> +| `69` | When using a provisioning network, cluster nodes communicate with the TFTP server on port `69` using their provisioning network interfaces. The TFTP server runs on the bootrap VM. The bootst
```suggestion
| `69` | When using a provisioning network, cluster nodes communicate with the TFTP server on port `69` using their provisioning network interfaces. The TFTP server runs on the bootstrap VM. The bootstrap VM runs on the provisioner node.
```

2023-09-13 18:54 UTC, kcarmichael08 commented on modules/ipi-install-network-requirements.adoc
> +The out-of-band management IP address is on a separate network from the node. To ensure that the out-of-band management can communicate with the provisioner node during installation, the out-of-band
```suggestion
The out-of-band management IP address is on a separate network from the node. To ensure that the out-of-band management IP address can communicate with the provisioner node during installation, the out-of-band management IP address must be granted access to port `6180` on the provisioner node and on the {product-title} control plane nodes. TLS port `6183` is required for virtual media installation, for example, by using Redfish.
```

2023-09-13 18:54 UTC, kcarmichael08 commented on modules/ipi-install-network-requirements.adoc
> +The out-of-band management IP address is on a separate network from the node. To ensure that the out-of-band management can communicate with the provisioner node during installation, the out-of-band
Per IBM Style, "via" should only be used to refer to routing data. https://www.ibm.com/docs/en/ibm-style?topic=word-usage#v

2023-09-13 18:56 UTC, kcarmichael08 commented
I also see that it was reviewed so please check the QE approved box if that is the case.

2023-09-18 18:10 UTC, johnwilkins commented
/label merge-review-needed

2023-09-18 20:08 UTC, kelbrown20 reviewed
Updates LGTM!

2023-09-18 20:09 UTC, merged

2023-09-18 20:09 UTC, kelbrown20 commented
/cherrypick enterprise-4.14

2023-09-18 20:10 UTC, kelbrown20 commented
/cherrypick enterprise-4.13