OSDOCS-6922: Infrastructure Node Utilization Update
openshift/openshift-docs pull request #63960
Opened 2023-08-25 18:21 UTC by EricPonvelle

Version(s):
`enterprise-4.13+`

Issue:
[OSD-15310](https://issues.redhat.com/browse/OSD-15310)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:
Updated the infrastructure node scaling to specify high-sustained utilization.

2023-08-25 20:59 UTC, EricPonvelle commented
@mjlshen Can you tell me if this is what you envisioned for these changes? Thanks!

2023-08-25 21:21 UTC, mjlshen commented
cc @clcollins

2023-08-25 21:26 UTC, mjlshen requested changes
Some feedback on the details, overall looks good!

2023-08-25 21:26 UTC, mjlshen commented on modules/sd-planning-considerations.adoc
> +* An infrastructure node sustains over 50% utilization in a classic ROSA cluster with a single availability zones using 2 infrastructure nodes.
```suggestion
* Infrastructure nodes sustain over 50% utilization on average in a classic ROSA cluster with a single availability zones using 2 infrastructure nodes.
```

The alert triggers off of the total average (e.g. one node at 60% and one node at 30% wouldn't trigger a scaleup, but both nodes at 60% would) - open to other ways to word this too.

2023-08-25 21:26 UTC, mjlshen commented on modules/sd-planning-considerations.adoc
> +* An infrastructure node sustains over 66% utilization in a classic ROSA cluster with with multiple availability zones using 3 infrastructure nodes.
Whatever we update the previous line's wording to should be mirrored here

2023-08-28 20:37 UTC, cbippley reviewed
You've got a double "with" on line 76. Other than that, LGTM!

2023-08-28 20:42 UTC, cbippley commented
/label peer-review-done
/remove-label peer-review-in-progress
As I'm in training, please wait for @opayne1 to take a look as well before requesting merge review.

2023-08-28 20:49 UTC, cbippley commented on modules/sd-planning-considerations.adoc
> +* Infrastructure nodes sustain over 66% utilization on average in a classic ROSA cluster with with multiple availability zones using 3 infrastructure nodes.
```suggestion
* Infrastructure nodes sustain over 66% utilization on average in a classic ROSA cluster with multiple availability zones using 3 infrastructure nodes.
```

2023-08-28 22:15 UTC, mjlshen commented on modules/sd-planning-considerations.adoc
> +Resizing alerts are triggered for the infrastructure nodes in a cluster when the CPU or the memory has high sustained utilization. This high-sustained utilization status is:
```suggestion
Resizing alerts are triggered for the infrastructure nodes in a cluster when it has high-sustained CPU or memory utilization. This high-sustained utilization status is: 
```

Standardizing the hyphenated `high-sustained` and removing the `the CPU`/`the memory` wording

2023-08-29 12:57 UTC, mjlshen approved these changes
/lgtm

Thanks Eric!

2023-08-29 13:28 UTC, mjlshen approved these changes
/lgtm

2023-08-29 13:51 UTC, merged

2023-08-29 13:51 UTC, EricPonvelle commented
/cherrypick enterprise-4.13

2023-08-29 13:51 UTC, EricPonvelle commented
/cherrypick enterprise-4.14