[RHACS] ROX-19656: Documenting updates to build-time network policy tools
openshift/openshift-docs pull request #64628
Opened 2023-09-12 14:50 UTC by agantony

Version(s):
4.2+

Issue:
https://issues.redhat.com/browse/ROX-19656

Link to docs preview:

SME review:
- [ ] SME has approved this change.

Additional information:
Merge into `rhacs-docs` and cherry-pick into:
- `rhacs-docs-4.2`

2023-09-12 14:50 UTC, agantony commented
/label RHACS

2023-09-13 06:40 UTC, zivnevo requested changes
Thanks @agantony , please see the two comments below.

2023-09-13 06:40 UTC, zivnevo commented on modules/connectivity-mapping-using-the-roxctl-connectivity-map-command.adoc
Change `connectivity-map` to `connectivity map` throughout this file

2023-09-13 06:40 UTC, zivnevo commented on modules/identifying-the-differences-in-allowed-connections-between-project-versions.adoc
Line 13 still states the command is used "to perform a comparison between the Kubernetes manifests in the specified directories" rather than "to perform a comparison between the **connectivity postures implied by** the Kubernetes manifests in the specified directories"

2023-09-13 08:20 UTC, agantony commented on modules/identifying-the-differences-in-allowed-connections-between-project-versions.adoc
Thank you for the suggestion. However, the suggested sentence sounds to be a bit complex. 
How about we say, "Run the following command to determine the connectivity differences between the Kubernetes manifests in the specified directories:"

@kcarmichael08 WDYT?

2023-09-13 09:18 UTC, zivnevo commented on modules/identifying-the-differences-in-allowed-connections-between-project-versions.adoc
This can work.
It's slightly less precise technically, but probably more fluent. I think at this point in the text, readers already got used to the concept of "Kubernetes manifests imply connectivity posture" so probably no need to be 100% accurate.

2023-09-13 09:39 UTC, zivnevo approved these changes

2023-09-13 14:13 UTC, kcarmichael08 reviewed
Couple of minor suggestions; lgtm!

2023-09-13 14:13 UTC, kcarmichael08 commented on operating/manage-network-policies.adoc
> +|Generates Kubernetes network policies by analyzing your project's YAML manifests in a specified directory, and was previously known as `roxctl generate netpol`. For more information, see xref:../ope
```suggestion
|Generates Kubernetes network policies by analyzing your project's YAML manifests in a specified directory. The previous syntax was `roxctl generate netpol`. For more information, see xref:../operating/manage-network-policies.adoc#using-the-build-time-network-policy-generator[Using the build-time network policy generator].
```

2023-09-13 14:13 UTC, kcarmichael08 commented on operating/manage-network-policies.adoc
> +|Lists the allowed connections between workloads in your project directory, considering the workload and Kubernetes network policy manifests. Additionally, a graphical representation in `.dot` format
```suggestion
|Lists the allowed connections between workloads in your project directory by examining the workload and Kubernetes network policy manifests. Additionally, a graphical representation in `.dot` format is included. For more information, see xref:../operating/manage-network-policies.adoc#connectivity-mapping-using-the-roxctl-connectivity-map-command_manage-network-policies[Connectivity mapping using the roxctl connectivity-map command].
```

2023-09-14 15:39 UTC, merged

2023-09-14 15:39 UTC, kcarmichael08 commented
/cherrypick rhacs-docs-4.2