OSDOCS-7769: Migrated the Cloudwatch logs and STS topic from MOBB docs to ROSA product docs
openshift/openshift-docs pull request #64846
Opened 2023-09-18 16:19 UTC by EricPonvelle

Version(s):
`enterprise-4.13+`

Issue:
[OSDOCS-7769](https://issues.redhat.com/browse/OSDOCS-7769)

Link to docs preview:
- Configuring the Cluster Log Forwarder for Cloudwatch logs and STS

QE review:
- [ ] QE has approved this change.

Additional information:
Migrated the tutorial for configuring the Cluster Log Forwarder Operator to use Cloudwatch Logs and STS.

2023-09-18 19:19 UTC, EricPonvelle commented
@paulczar can you review this PR and let me know if there are any changes? Thank you

2023-09-19 13:40 UTC, EricPonvelle commented
@michaelryanmcneill can you review this PR?

2023-09-19 13:45 UTC, paulczar commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +   if [[ -z "${POLICY_ARN}" ]]; then
This can't be indented as it breaks the HEREDOC

2023-09-19 13:47 UTC, paulczar requested changes

2023-09-19 13:47 UTC, paulczar commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +   {
This can't be indented as it breaks the HEREDOC

2023-09-19 13:47 UTC, paulczar commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +$ cat << EOF | oc apply -f -
This can't be indented as it breaks the HEREDOC

2023-09-19 13:47 UTC, paulczar commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +   apiVersion: v1
This can't be indented as it breaks the HEREDOC

2023-09-19 13:47 UTC, paulczar commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +   apiVersion: "logging.openshift.io/v1"
This can't be indented as it breaks the HEREDOC

2023-09-19 13:47 UTC, paulczar commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +   apiVersion: logging.openshift.io/v1
This can't be indented as it breaks the HEREDOC

2023-09-19 20:48 UTC, bhardesty commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +Change the cluster name to match your ROSA cluster and ensure you're logged into the cluster as an Administrator. Ensure all fields are outputted correctly before moving on.
```suggestion
Change the cluster name to match your ROSA cluster and ensure you are logged into the cluster as an Administrator. Ensure all fields are outputted correctly before moving on.
```

2023-09-20 04:48 UTC, anpingli commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +  EOF
Can you remove the prefix spaces. '  EOF'  to 'EOF'

2023-09-20 14:04 UTC, michaelryanmcneill commented
/hold 

Pending further discussion on including MOBB helm charts in Red Hat product documentation (even with the banner).

2023-09-20 20:27 UTC, paulczar commented
@michaelryanmcneill this doc doesn't use Helm ?

2023-09-20 20:33 UTC, paulczar requested changes
still broken indenting

2023-09-20 20:33 UTC, paulczar commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +  cat << EOF > ${SCRATCH}/policy.json
this whole section from the `cat << EOF` to the `EOF` needs to be unindented by one.  the opening `{` and closing `}` need to be at the same indent level as the EOF.

2023-09-20 20:33 UTC, paulczar commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +  {
same as the above from { to EOF needs to be at the same indent level as the `$`.

2023-09-20 20:33 UTC, paulczar commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +$ cat << EOF | oc apply -f -
this indenting is still broken.

2023-09-20 20:33 UTC, paulczar commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +$ cat << EOF | oc apply -f -
this indenting is still broken.

2023-09-20 20:33 UTC, paulczar commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +  apiVersion: logging.openshift.io/v1
this indenting is still broken.

2023-09-20 21:18 UTC, EricPonvelle commented
@paulczar I tried to fix the indenting again, but I am copying the raw text from this link https://raw.githubusercontent.com/rh-mobb/documentation/main/content/docs/rosa/clf-cloudwatch-sts/_index.md

2023-09-21 14:06 UTC, michaelryanmcneill commented
/unhold sorry for the confusion, too many tabs.

2023-09-22 15:14 UTC, anpingli commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +    forwarder:
forwarder can be deleted.

2023-09-22 15:21 UTC, anpingli commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +  EOF
Delete the suffix space for  HEREDOC.

2023-09-22 15:21 UTC, anpingli commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +  EOF
Delete the suffix space for  HEREDOC.

2023-09-23 06:43 UTC, anpingli commented on rosa_tutorials/rosa-mobb-cloudwatch-sts.adoc
> +   EOF
and this one

2023-09-27 14:40 UTC, michaelryanmcneill approved these changes
/lgtm Thanks Eric!

2023-09-27 16:58 UTC, merged

2023-09-27 16:58 UTC, EricPonvelle commented
/cherrypick enterprise-4.13

2023-09-27 16:59 UTC, EricPonvelle commented
/cherrypick enterprise-4.14