OSDOCS-7780: Porting RDS database with STS tutorial.
openshift/openshift-docs pull request #64937
Opened 2023-09-19 21:01 UTC by eohartman

Version(s):
enterprise-4.13+

Issue:
[MOBB F2F] Connect to RDS database with STS from ROSA](https://issues.redhat.com/browse/OSDOCS-7780)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-09-25 14:07 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   export AWS_REGION=$(rosa describe cluster -c ${ROSA_CLUSTER_NAME} -o json | jq -r .region.id)
```suggestion
   export AWS_REGION=$(rosa describe cluster -c ${CLUSTER_NAME} -o json | jq -r .region.id)
```

2023-09-25 14:08 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   export AWS_REGION=$(rosa describe cluster -c ${ROSA_CLUSTER_NAME} -o json | jq -r .region.id)
Keep alignment with context

2023-09-25 14:23 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +$ (`rosa list cluster`)
This line is meaningless and will cause the command fail.
If we want to show customer how to find the <cluster name>, move it out from current command text to a single command

2023-09-25 14:24 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +    --region $AWS_REGION \
```suggestion
    --region $AWS_REGION --output json\
```

2023-09-25 14:24 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   export ROSA_IP_OUT=$(aws ec2 describe-nat-gateways --filter "Name=vpc-id,Values=${VPC_ROSA}" --region ${AWS_REGION} \
```suggestion
   export ROSA_IP_OUT=$(aws ec2 describe-nat-gateways --filter "Name=vpc-id,Values=${VPC_ROSA}" --region ${AWS_REGION} --output json \
```

2023-09-25 14:25 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +    | jq -r .NatGateways[].NatGatewayAddresses[].PublicIp)
```suggestion
    | jq -r '.NatGateways[].NatGatewayAddresses[].PublicIp')
```

2023-09-25 14:27 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   $ VPC_DB=$(aws ec2 create-vpc --cidr-block 10.23.0.0/16 --region ${AWS_REGION} | jq -r .Vpc.VpcId)
```suggestion
   $ VPC_DB=$(aws ec2 create-vpc --cidr-block 10.23.0.0/16 --region ${AWS_REGION} --output json | jq -r .Vpc.VpcId)
```

2023-09-25 14:27 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   SUBNET_A=$(aws ec2 create-subnet --vpc-id ${VPC_DB} --cidr-block 10.23.1.0/24 --availability-zone ${AWS_REGION}a | jq -r .Subnet.SubnetId)
```suggestion
   SUBNET_A=$(aws ec2 create-subnet --vpc-id ${VPC_DB} --cidr-block 10.23.1.0/24 --availability-zone ${AWS_REGION}a --output json | jq -r .Subnet.SubnetId)
```

2023-09-25 14:28 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   SUBNET_B=$(aws ec2 create-subnet --vpc-id ${VPC_DB} --cidr-block 10.23.2.0/24 --availability-zone ${AWS_REGION}b | jq -r .Subnet.SubnetId)
```suggestion
   SUBNET_B=$(aws ec2 create-subnet --vpc-id ${VPC_DB} --cidr-block 10.23.2.0/24 --availability-zone ${AWS_REGION}b --output json | jq -r .Subnet.SubnetId) 
```

2023-09-25 14:28 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   SUBNET_C=$(aws ec2 create-subnet --vpc-id ${VPC_DB} --cidr-block 10.23.3.0/24 --availability-zone ${AWS_REGION}c | jq -r .Subnet.SubnetId)
```suggestion
   SUBNET_C=$(aws ec2 create-subnet --vpc-id ${VPC_DB} --cidr-block 10.23.3.0/24 --availability-zone ${AWS_REGION}c  --output json| jq -r .Subnet.SubnetId)
```

2023-09-25 14:35 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +  $ IGW=$(aws ec2 create-internet-gateway --region ${AWS_REGION} | jq -r .InternetGateway.InternetGatewayId)
```suggestion
  $ IGW=$(aws ec2 create-internet-gateway --region ${AWS_REGION}  --output json| jq -r .InternetGateway.InternetGatewayId)
```

2023-09-25 14:40 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   export PSQL_PASSWORD=$(openssl rand -base64 12)
This line may not work. The random password may contain unusable characters. I got `IIbvew2/bTQsB5oT` first time which cannot work due to password validation `An error occurred (InvalidParameterValue) when calling the CreateDBInstance operation: The parameter MasterUserPassword is not a valid password. Only printable ASCII characters besides '/', '@', '"', ' ' may be used.`

2023-09-25 14:54 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +       --region ${AWS_REGION} \
--output json

2023-09-25 15:05 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +----
The file generated by above command cannot be used for creation unless I format the content again with jsonformatter

2023-09-25 15:09 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   echo $POLICY
Run the two command together will get empty value, unless I run them separatedly

2023-09-25 15:25 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   &Version=2011-06-15" | jq
The copied command has whitespaces those caused command run failure

2023-09-25 15:29 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +----
lack of `\q` to exit psql
lack of `exit` to quit pod

2023-09-25 15:30 UTC, xueli181114 commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   quit
lack of `\q` to quit psql

2023-09-27 18:32 UTC, michaelryanmcneill requested changes
Indentation is causing severe issues across all of the code blocks. In addition to the identified changes, please ensure that you fix any indentation in code blocks that is unintentional.

2023-09-27 18:32 UTC, michaelryanmcneill commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   exit
Replace with:

```
$ psql -h ${DB_ENDPOINT} -U iamuser -d iamdb
$ CREATE TABLE if not exists ref_ip_blocks
$ (
  iprange iprange,
  geoname varchar

);
$ \copy ref_ip_blocks FROM 'geolite2-country-ipv4.csv' DELIMITER ',' CSV;
$ CREATE INDEX ref_ip_blocks_ip4r_idx on ref_ip_blocks using gist(iprange);
$ quit
$ exit
```

2023-09-27 18:32 UTC, michaelryanmcneill commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   oc patch deployment ip-finder-api --type=merge -p '{"spec":{"template":{"spec":{"volumes":[{"name":"bound-sa-token","projected":{"sources":[{"serviceAccountToken":{"audience":"openshift","expirati
The indentation is breaking this command. Replace with:

```
$ oc apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
type: Opaque 
stringData: 
  credentials: |
    [default]
    role_arn = ${ROLE}
    web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
EOF
$ oc patch deployment ip-finder-api --type=merge -p '{"spec":{"template":{"spec":{"volumes":[{"name":"bound-sa-token","projected":{"sources":[{"serviceAccountToken":{"audience":"openshift","expirationSeconds":3600,"path":"token"}}]}},{"name":"aws-creds","secret":{"secretName":"aws-creds"}}]}}}}'
$ oc patch deployment ip-finder-api --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/volumeMounts", "value": [{"name":"bound-sa-token","readOnly":true,"mountPath":"/var/run/secrets/openshift/serviceaccount"},{"name":"aws-creds","mountPath":"/opt/app-root/src/.aws"}]}]'
```

2023-09-27 18:32 UTC, michaelryanmcneill commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   oc patch route ip-finder-api --patch '{"spec":{"tls":{"termination":"edge","insecureEdgeTerminationPolicy":"Redirect"}}}'
Broken; replace with:

```
$ oc expose service ip-finder-api
$ oc patch route ip-finder-api --patch '{"spec":{"tls":{"termination":"edge","insecureEdgeTerminationPolicy":"Redirect"}}}'
```

2023-09-27 18:32 UTC, michaelryanmcneill commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   }
With my changes this error is not detected.

2023-09-27 18:32 UTC, michaelryanmcneill commented on rosa_tutorials/rosa-mobb-sts-rds-database-connect.adoc
> +   aws rds delete-db-subnet-group --db-subnet-group-name db-group-${CLUSTER_NAME}
Replace:

```
$ oc delete ns rds-sts-app
$ aws rds delete-db-instance --db-instance-identifier psql-${CLUSTER_NAME} --region ${AWS_REGION} --skip-final-snapshot
$ aws ec2 detach-internet-gateway --vpc-id ${VPC_DB} --internet-gateway-id ${IGW}
$ aws ec2 delete-internet-gateway --internet-gateway-id ${IGW} --region ${AWS_REGION}
$ aws ec2 delete-subnet --subnet-id ${SUBNET_A} --region ${AWS_REGION}
$ aws ec2 delete-subnet --subnet-id ${SUBNET_B} --region ${AWS_REGION}
$ aws ec2 delete-subnet --subnet-id ${SUBNET_C} --region ${AWS_REGION}
$ aws ec2 delete-vpc --vpc-id ${VPC_DB} --region ${AWS_REGION}
$ aws rds delete-db-subnet-group --db-subnet-group-name db-group-${CLUSTER_NAME}
```

2023-11-01 15:13 UTC, eohartman commented
@michaelryanmcneill @xueli181114 Can y'all please take a look at this and let me know what you think? 

Note: There are still some formatting issues under the "IAM Permissions" section, regarding step numbering and indentation of a code block. I'm still working on that, but wanted to get y'all to review the content to ensure the rest of the requested changes have been resolved.

Thank you!

2023-11-13 18:25 UTC, closed without merging