OSDOCS#6367:Installing specific Operator version in web console
openshift/openshift-docs pull request #64953
Opened 2023-09-20 11:15 UTC by opayne1

OSDOCS#6367:Installing specific Operator version in web console

Version(s):
4.14

Issue:
https://issues.redhat.com/browse/OSDOCS-6367

Link to docs preview:
https://64953--docspreview.netlify.app/openshift-enterprise/latest/operators/admin/olm-adding-operators-to-cluster#olm-installing-specific-version-web-console_olm-adding-operators-to-a-cluster

QE review:
- [x] QE has approved this change.

Additional information:

2023-09-20 21:08 UTC, sg00dwin requested changes

2023-09-26 11:18 UTC, XiyunZhao commented
Hi @opayne1, the content is looks good for me
/qe-approved

2023-09-26 11:19 UTC, XiyunZhao commented
/label qe-approved

2023-09-26 12:49 UTC, mburke5678 commented on modules/olm-installing-specific-version-web-console.adoc
> +Installing an Operator with manual approval causes all Operators installed within the namespace to function with the _Manual approval_ strategy and will be updated altogether. Install Operators into
```suggestion
Installing an Operator with manual approval causes all Operators installed within the namespace to function with the _Manual approval_ strategy and all Operators are be updated together. Install Operators into separate namespaces for updating independently.
```

2023-09-26 12:51 UTC, mburke5678 commented on modules/olm-installing-specific-version-web-console.adoc
> +* When the operator is installed, the metadata will indicate which channel and version are installed.
```suggestion
* When the operator is installed, the metadata indicates which channel and version are installed.
```

2023-09-26 12:54 UTC, mburke5678 commented
@opayne1 A few nits, and an ignorant question. Otherwise LGTM

2023-09-26 15:54 UTC, opayne1 commented on modules/olm-installing-specific-version-web-console.adoc
> +_Manual approval applies to all operators installed in a namespace_
You are correct. I was getting the lowercase italics confused with another UI element that requires that. Thanks!

2023-09-27 17:48 UTC, merged

2023-09-27 17:48 UTC, opayne1 commented
/cherrypick enterprise-4.14