OSDOCS-7900: Documented the 4.11.50 z-stream release notes
openshift/openshift-docs pull request #65225
Opened 2023-09-26 13:20 UTC by dfitzmau

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-09-26 13:51 UTC, dfitzmau commented
/label peer-review-needed

2023-09-26 15:04 UTC, cbippley commented
/label peer-review-in-progress
/remove-label peer-review-needed

2023-09-26 15:08 UTC, cbippley reviewed
LGTM! Please wait for @opayne1 to review before requesting merge review since I'm still in training, thanks!

2023-09-26 15:08 UTC, cbippley commented
/label peer-review-done
/remove-label peer-review-in-progress

2023-09-26 15:10 UTC, opayne1 reviewed
Just one tiny nit but otherwise lgtm

2023-09-26 15:10 UTC, opayne1 commented on release_notes/ocp-4-11-release-notes.adoc
> +* Previously, the cloud credentials used in Manila CSI Driver Operator were cached, resulting in authentication issues if these credentials were rotated. With this update, this issue is resolved. (li
```suggestion
* Previously, the cloud credentials used in the Manila CSI Driver Operator were cached, resulting in authentication issues if these credentials were rotated. With this update, this issue is resolved. (link:https://issues.redhat.com/browse/OCPBUGS-18782[*OCPBUGS-18782*])
```

2023-10-04 12:24 UTC, JoeAldinger requested changes
@dfitzmau please make sure to include the RHCOS content so we don't have to do CM.

2023-10-04 12:24 UTC, JoeAldinger commented on release_notes/ocp-4-11-release-notes.adoc
> +Issued: 2023-09-26
```suggestion
Issued: 2023-10-04
```

2023-10-04 12:24 UTC, JoeAldinger commented on release_notes/ocp-4-11-release-notes.adoc
> +
This needs to be included like in 4.13 and 4.12 https://issues.redhat.com/browse/OCPBUGS-18545 as a feature write up that is a backport. [This](https://docs.openshift.com/container-platform/4.13/release_notes/ocp-4-13-release-notes.html#ocp-4-13-12-custom-rhcos-image-for-gcp) content needs to be added to this RN.

2023-10-04 13:18 UTC, JoeAldinger requested changes
Small organizational move

2023-10-05 10:26 UTC, dfitzmau commented
/label merge-review-needed

2023-10-05 11:28 UTC, JoeAldinger approved these changes

2023-10-05 11:28 UTC, merged