CNV-20458: Hot plugging VM seconday network interface
openshift/openshift-docs pull request #66051
Opened 2023-10-10 19:48 UTC by sjhala-ccs

Version(s): 4.14

Issue: CNV-20458

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information: A release note covering this feature was added in https://github.com/openshift/openshift-docs/pull/63953. I edited the text and added an xref to the associated documentation.

2023-10-11 07:50 UTC, segevyos requested changes

2023-10-11 07:50 UTC, segevyos commented on virt/release_notes/virt-4-14-release-notes.adoc
> +* You can xref:../../virt/vm_networking/virt-hot-plugging-network-interfaces.adoc#virt-hot-plugging-network-interfaces[hot plug a bridge network interface] to a running virtual machine (VM). Hot unpl
> Hot unplugging is supported only for VMs created with {VirtProductName} 4.14 or later

This is also true for hot-plug.

2023-10-12 08:28 UTC, phoracek approved these changes
/lgtm

2023-10-12 17:20 UTC, skrthomas commented
/lgtm

2023-10-16 13:30 UTC, merged