Added a new Planning Your Environment According to Application Requirements section
openshift/openshift-docs pull request #6620
Opened 2017-12-05 21:20 UTC by ahardin-rh

https://trello.com/c/RY5BrWYB/632-3-scale-convert-app-sizing-section-of-whitepaper-over-to-openshift-docs

Preview Build:
http://file.rdu.redhat.com/~ahardin/12052017/scale-sizing-chart/scaling_performance/cluster_limits.html#scaling-performance-planning-your-environment-according-to-application-requirements

2017-12-05 21:20 UTC, ahardin-rh commented
@jeremyeder PTAL

2017-12-15 18:54 UTC, jeremyeder requested changes

2017-12-15 18:54 UTC, jeremyeder commented on scaling_performance/cluster_limits.adoc
> +You might have a deployment such as {product-title} running on virtual machines
I think we can drop this sentence and replace with:

Let's take an example application environment:

2017-12-15 18:54 UTC, jeremyeder commented on scaling_performance/cluster_limits.adoc
> +(VMs) on top of Red Hat OpenStack Platform with application requirements such
Because we cannot quota or QoS on network, I'd like you to drop the Network Bandwidth column to avoid confusion.

2017-12-15 18:54 UTC, jeremyeder commented on scaling_performance/cluster_limits.adoc
> +Extrapolated requirements: 550 CPU cores, 450GB RAM, 1.4TB storage and < 1Gbit
drop the "and < 1 Gbit network".

2017-12-15 18:54 UTC, jeremyeder commented on scaling_performance/cluster_limits.adoc
> +To fulfill these resource requirements, a highly available topology might
Drop this first table that discusses the control plane topology.  This is documented elsewhere.  No need to duplicate.

2017-12-21 00:04 UTC, ahardin-rh commented
@jeremyeder This is now updated: http://file.rdu.redhat.com/~ahardin/12052017/scale-sizing-chart/scaling_performance/cluster_limits.html#scaling-performance-planning-your-environment-according-to-application-requirements

2018-01-02 17:01 UTC, jeremyeder commented
Hmm, something is very wrong with the first table.

It doesn't match what's in the PDF at all.  Cell contents do not match column headers.

2018-01-02 19:20 UTC, ahardin-rh commented
@jeremyeder Whoops! I had an incorrect value for the number of columns. Not sure how I missed that. Fixed. Thanks!
http://file.rdu.redhat.com/%7Eahardin/12052017/scale-sizing-chart/scaling_performance/cluster_limits.html#scaling-performance-planning-your-environment-according-to-application-requirements

2018-01-02 19:21 UTC, mffiedler commented
/cc: @schituku

2018-01-02 19:26 UTC, jeremyeder commented
@ahardin-rh cool. Is there a new preview docs build with the columns fixed?

2018-01-02 19:29 UTC, ahardin-rh commented
@jeremyeder Yeah, I pushed the latest changes to http://file.rdu.redhat.com/%7Eahardin/12052017/scale-sizing-chart/scaling_performance/cluster_limits.html#scaling-performance-planning-your-environment-according-to-application-requirements, but you may need to refresh the page or clear your cache.

2018-01-02 20:02 UTC, jeremyeder commented
ah yeah. thats better now, thanks.

I also see footnote 1 is wrong.

1. Having clusters with more than 5000 nodes is not the best option. Consider splitting into multiple clusters.

We only support 2000 nodes. and the language "not the best option" is weak.

2018-01-02 21:11 UTC, ahardin-rh commented
@jeremyeder Updated. Thanks! 
http://file.rdu.redhat.com/%7Eahardin/12052017/scale-sizing-chart/scaling_performance/cluster_limits.html#scaling-performance-planning-your-environment-according-to-application-requirements

2018-01-06 16:12 UTC, jeremyeder commented
I think this is ready to go, boss.

2018-01-08 17:27 UTC, ahardin-rh commented
@jeremyeder Good point. Updated: http://file.rdu.redhat.com/%7Eahardin/12052017/scale-sizing-chart/scaling_performance/cluster_limits.html#scaling-performance-planning-your-environment-according-to-application-requirements
Thanks!

2018-01-08 17:27 UTC, ahardin-rh commented
@openshift/team-documentation Please peer review

2018-01-08 19:45 UTC, ncbaratta approved these changes
A few comments.

2018-01-08 19:45 UTC, nengard commented on scaling_performance/cluster_limits.adoc
> +huge pages are examples of applications that would not allow for overcommit.
"overcommitment" maybe? This sounds a bit awkward.

2018-01-08 19:45 UTC, nengard commented on scaling_performance/cluster_limits.adoc
> +That memory cannot be used for other applications. In the example above, the
can not is 2 words per IBM Stylguide

2018-01-09 21:51 UTC, ahardin-rh commented
[rev_history]
|xref:../scaling_performance/cluster_limits.adoc#scaling-performance-cluster-limits[Cluster Limits]
|Added a new xref:../scaling_performance/cluster_limits.adoc#scaling-performance-planning-your-environment-according-to-application-requirements[Planning Your Environment According to Application Requirements] section.
%

2018-01-09 21:51 UTC, merged