DPDK vmi: Update vmi docs
openshift/openshift-docs pull request #66246
Opened 2023-10-15 10:37 UTC by RamLavi

Updating some relevant VMI spec and guest changes needed in order to configure a DPDK VMI:
* Remove `isolcpu` from linux cmd.
* Refactor Hugepages API to be more specific.

Version(s):
4.15

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-10-15 12:29 UTC, orelmisan reviewed
Thank you @RamLavi 
Could you please change the applicable versions to 4.13 and above? (in the PR description)

2023-10-15 12:43 UTC, orelmisan approved these changes

2023-10-16 06:50 UTC, orelmisan requested changes
@RamLavi the changes are made to a VM (and not to a VMI), could you please update the commit message + PR desc and title?

2023-10-16 06:52 UTC, orelmisan commented
/cc @segevyos

2023-10-16 07:27 UTC, segevyos commented
/lgtm

2023-10-16 07:43 UTC, RamLavi commented
> @RamLavi the changes are made to a VM (and not to a VMI), could you please update the commit message + PR desc and title?

Fixed.

2023-10-16 07:46 UTC, orelmisan approved these changes
Thank you

2023-10-16 07:48 UTC, RamLavi commented
/cc @sjhala-ccs 

can you please take a look?

2023-10-16 10:25 UTC, segevyos commented
/lgtm

2023-10-16 15:50 UTC, sjhala-ccs reviewed
LGTM. I can merge the PR after you squash the commits. Thank you!

2023-10-17 06:32 UTC, RamLavi commented
> LGTM. I can merge the PR after you squash the commits. Thank you!

DONE

2023-10-17 12:57 UTC, merged

2023-10-17 12:57 UTC, sjhala-ccs commented
/cherrypick enterprise-4.13

2023-10-17 12:58 UTC, sjhala-ccs commented
/cherrypick enterprise-4.14