WIP PR for SRVKS-1121: Update DomainMapping `v1alpha1` to `v1beta1`
openshift/openshift-docs pull request #66248
Opened 2023-10-16 05:36 UTC by kaldesai

**Tracking JIRA:** https://issues.redhat.com/browse/SRVKS-1121

**Doc preview:** 

**Description:**

2023-10-18 07:29 UTC, kaldesai commented
@nak3 and @skonto 
can you please check and verify the changes? We are going to include the deprecation note in the release notes as well.

2023-10-18 07:47 UTC, nak3 requested changes
Thank you!

Could you update in this page
* https://github.com/openshift/openshift-docs/blob/03ca38894b332200706d44d50c006981aeb7c0c0/modules/serverless-domain-mapping-custom-tls-cert.adoc
* https://github.com/openshift/openshift-docs/blob/03ca38894b332200706d44d50c006981aeb7c0c0/modules/serverless-domain-mapping-odc-admin.adoc
 
with same change `apiVersion: serving.knative.dev/v1alpha1` to `apiVersion: serving.knative.dev/v1beta1`?

2023-10-18 08:20 UTC, kaldesai commented
> Thank you!
> 
> Could you update in the following pages:
> 
> * https://github.com/openshift/openshift-docs/blob/03ca38894b332200706d44d50c006981aeb7c0c0/modules/serverless-domain-mapping-custom-tls-cert.adoc
> * https://github.com/openshift/openshift-docs/blob/03ca38894b332200706d44d50c006981aeb7c0c0/modules/serverless-domain-mapping-odc-admin.adoc
> 
> with same change `apiVersion: serving.knative.dev/v1alpha1` to `apiVersion: serving.knative.dev/v1beta1`?

Yes, definitely! Thank you!

2023-10-18 09:53 UTC, nak3 requested changes
Thank you! We want to update DomainMapping's `serving.knative.dev/v1alpha1` so some changes are not necessary.

2023-10-18 09:53 UTC, nak3 commented on modules/serverless-domain-mapping-custom-tls-cert.adoc
> +    apiVersion: serving.knative.dev/v1beta1
```suggestion
    apiVersion: serving.knative.dev/v1
```

This is not necessary.

2023-10-18 09:53 UTC, nak3 commented on modules/serverless-domain-mapping-odc-admin.adoc
> +   apiVersion: serving.knative.dev/v1beta1
```suggestion
   apiVersion: serving.knative.dev/v1
```

2023-10-18 09:53 UTC, nak3 commented on modules/serverless-domain-mapping-odc-admin.adoc
> +   apiVersion: serving.knative.dev/v1beta1
```suggestion
   apiVersion: serving.knative.dev/v1
```

2023-10-18 09:57 UTC, kaldesai commented on modules/serverless-domain-mapping-custom-tls-cert.adoc
> +    apiVersion: serving.knative.dev/v1beta1
Done! Corrected!

2023-10-18 09:57 UTC, kaldesai commented on modules/serverless-domain-mapping-odc-admin.adoc
> +   apiVersion: serving.knative.dev/v1beta1
Done! Corrected!

2023-10-18 09:58 UTC, kaldesai commented on modules/serverless-domain-mapping-odc-admin.adoc
> +   apiVersion: serving.knative.dev/v1beta1
Done! Corrected!

2023-10-18 09:58 UTC, nak3 commented
/lgtm

2023-10-18 10:36 UTC, mgencur commented
LGTM from QE

2023-10-18 12:31 UTC, skonto commented
LGTM don't see other references that need update.

2023-10-18 13:46 UTC, kaldesai commented
/label peer-review-needed

2023-10-18 14:01 UTC, bergerhoffer commented
/label peer-review-in-progress

2023-10-18 14:04 UTC, bergerhoffer reviewed
The actual updates LGTM!

But before you request merge review, please be sure to squash your commits and remove the "WIP" from the title.

2023-10-18 14:04 UTC, bergerhoffer commented
/label peer-review-done
/remove-label peer-review-needed
/remove-label peer-review-in-progress

2023-10-19 04:24 UTC, kaldesai commented
> The actual updates LGTM!
> 
> But before you request merge review, please be sure to squash your commits and remove the "WIP" from the title.

Thank you so much, @bergerhoffer for reviewing. Yes, I am going to squash the commits before proceeding with the merge request.

2023-10-20 06:32 UTC, kaldesai commented
/label merge-review-needed

2023-10-20 13:32 UTC, opayne1 reviewed
/lgtm

2023-10-20 13:33 UTC, merged

2023-10-20 13:34 UTC, opayne1 commented
/cherrypick serverless-1.31

2023-10-20 13:38 UTC, opayne1 commented
/cherrypick serverless-docs-1.31