WIP -- NooBaa in OADP documentation
openshift/openshift-docs pull request #66247
Opened 2023-10-15 13:30 UTC by RichardHoch

OADP 1.3

Resolves https://issues.redhat.com/browse/OADP-2854 by removing references to NooBaa in downstream documentation and resolving the specific question about support the Jira raised.

2023-10-23 13:15 UTC, RichardHoch commented
@kaovilai @weshayutin Please review this PR, especially previews 2 and 5.

2023-10-23 15:29 UTC, kaovilai requested changes
In `modules/oadp-s3-compatible-backup-storage-providers.adoc`
```diff
The following AWS S3 compatible object storage providers, are known to work with Velero through the AWS plugin, for use as backup storage locations, however, they are unsupported and have not been tested by Red Hat:
* IBM Cloud
* Oracle Cloud
* DigitalOcean
-* NooBaa
+* NooBaa (support is only available when installed via Multicloud Object Gateway (MCG))
```

2023-10-23 18:24 UTC, weshayutin commented
Red Hat OpenShift Data Foundation deploys three operators.
One of which is the noobaa operator.  
The NooBaa operator deploys and manages the [NooBaa](https://www.noobaa.io/) Multi-Cloud Gateway on OpenShift, which provides object storage.

![Screenshot from 2023-10-23 12-18-42](https://github.com/openshift/openshift-docs/assets/138787/8274fde2-af43-438c-949b-3d782a6df169)

MCG / Nooba Documentation.  https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.8/html/managing_hybrid_and_multicloud_resources/accessing-the-multicloud-object-gateway-with-your-applications_rhocs

AFAICT the official product name is MCG, but there are many references to Nooba where providing a little context and doc may be helpful in these cases.

2023-10-24 10:17 UTC, RichardHoch commented
@weshayutin I'm not quite sure about the scope of what you're asking.  Are you asking that I add a few comments to the existing text (and maybe leave some references to NooBaa in) or for a new section or two? Either is good, of course, but if you mean the latter, maybe that could be a new Jira so I can just correct the error quicker. 
@kaovilai I made the change you requested.

2023-10-24 13:35 UTC, kaovilai requested changes

2023-10-24 13:35 UTC, kaovilai commented on backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.adoc
> +* AWS S3 compatible object storage, such as MinIO
```suggestion
* AWS S3 compatible object storage, such as Multicloud Object Gateway or MinIO
```

2023-10-24 13:35 UTC, kaovilai commented on modules/oadp-configuring-noobaa-for-dr.adoc
> +* Configure MCG as an external object store as described in link:https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.11/html/managing_hybrid_and_multicloud_resources/add
```suggestion
* Configure MCG as an external object store as described in link:https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.13/html/managing_hybrid_and_multicloud_resources/adding-storage-resources-for-hybrid-or-multicloud_rhodf#doc-wrapper[Adding storage resources for hybrid or Multicloud].
```

2023-10-25 11:51 UTC, RichardHoch commented
@kaovilai @weshayutin I made the changes you suggested, Please review this PR again.

2023-10-25 12:31 UTC, weshayutin approved these changes
perfect!

2023-10-25 12:31 UTC, weshayutin approved these changes

2023-10-25 12:59 UTC, kaovilai approved these changes

2023-11-01 08:26 UTC, amastbau commented
Referring to the documentation, and adding the note distinguishing noobaa from MCG  is helpiong clear the confusion.
LGTM

2023-11-02 12:47 UTC, sbeskin-redhat commented on modules/oadp-configuring-noobaa-for-dr.adoc
> += Configuring Multicloud Object Gateway for disaster recovery on {rh-storage}
@RichardHoch 
I would add the acronym here: "...Multicloud Object Gateway (MCG) for...", otherwise the next sentence becomes impossibly heavy.

2023-11-02 12:47 UTC, sbeskin-redhat commented on modules/oadp-configuring-noobaa-for-dr.adoc
> +If you use cluster storage for your Multicloud Object Gateway (MCG) bucket `backupStorageLocation` on {rh-storage}, configure MCG as an external object store.
@RichardHoch 
Pedantic:  `backupStorageLocation` is used here (not by you) as meaning "backup storage location". I don't think this is correct. `backupStorageLocation` does not mean 'location', it's the name of a spec. I would suggest changing to:
"If you use cluster storage as your MCG bucket's backup storage location` on {rh-storage}, configure MCG ... " 
But up to you.

2023-11-02 12:47 UTC, sbeskin-redhat commented on modules/oadp-creating-object-bucket-claim.adoc
> +If you use cluster storage for your Multicloud Object Gateway (MCG) bucket `backupStorageLocation` on {rh-storage}, create an Object Bucket Claim (OBC) using the OpenShift Web Console.
@RichardHoch  
As above

2023-11-02 12:47 UTC, sbeskin-redhat commented on snippets/snip-noobaa-and-mcg.adoc
> +Unless specified otherwise, "NooBaa" refers to the open source project that provides lightweight object storage  while "Multicloud Object Gateway (MCG)" refers to the Red Hat distribution of NooBaa.
@RichardHoch 
Comma before 'while'

2023-11-02 14:32 UTC, RichardHoch commented
// label OADP
// label peer-review-needed

2023-11-06 08:54 UTC, RichardHoch commented
/ label OADP
/ label peer-review-needed

2023-11-06 14:49 UTC, jeana-redhat reviewed
Nice work, I like the new snippet :nerd_face: 

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2023-11-06 14:49 UTC, jeana-redhat commented on snippets/snip-noobaa-and-mcg.adoc
> +For more information on the MCG, see link:https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.14/html-single/managing_hybrid_and_multicloud_resources/index#accessing-the
```suggestion
For more information on the MCG, see link:https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.14/html-single/managing_hybrid_and_multicloud_resources/index#accessing-the-multicloud-object-gateway-with-your-applications_rhodf[Accessing the Multicloud Object Gateway with your applications].
```

2023-11-06 16:54 UTC, RichardHoch commented
Fixing existing documentation bugs; please merge and publish now, if OK.

2023-11-06 17:06 UTC, RichardHoch commented
/label merge-review-needed

2023-11-06 19:45 UTC, jeana-redhat approved these changes
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

2023-11-06 19:46 UTC, merged

2023-11-06 19:47 UTC, jeana-redhat commented
/cherrypick enterprise-4.15

2023-11-06 19:47 UTC, jeana-redhat commented
/cherrypick enterprise-4.14

2023-11-06 19:47 UTC, jeana-redhat commented
/cherrypick enterprise-4.13

2023-11-06 19:47 UTC, jeana-redhat commented
/cherrypick enterprise-4.12

2023-11-06 19:47 UTC, jeana-redhat commented
/cherrypick enterprise-4.11