TELCODOCS-1305 - Adding 4.14 ZTP software versions
openshift/openshift-docs pull request #66252
Opened 2023-10-16 10:48 UTC by aireilly

Adding ZTP solution software versions for 4.14.

Version(s):
main, enterprise-4.14

Issue:
https://issues.redhat.com/browse/TELCODOCS-1305

Link to docs preview:

QE review:
- [ ] QE has approved this change.

2023-10-16 14:41 UTC, aireilly commented
/label peer-review-needed

2023-10-16 15:55 UTC, aireilly commented
@mpmaruthu can you PTAL for QE review.

2023-10-16 16:56 UTC, jldohmann approved these changes
LGTM

2023-10-17 12:29 UTC, sabbir-47 requested changes
@aireilly for CLO operator we need to downgrade the version from 5.8 -> 5.7

2023-10-23 12:14 UTC, aireilly commented on modules/ztp-telco-ran-software-versions.adoc
> +|5.8
Updated

2023-10-23 13:16 UTC, sabbir-47 commented
/lgtm

2023-10-23 13:23 UTC, aireilly commented
@mpmaruthu Can you QE review this one too please.

2023-10-23 14:57 UTC, mpmaruthu commented
Telco QE: Looks good to me.
/Peri M

2023-10-23 15:06 UTC, aireilly commented
/label merge-review-needed

2023-10-23 16:41 UTC, merged

2023-10-23 16:41 UTC, skrthomas commented
/cherrypick enterprise-4.14