RHDEVDOCS-5631: Adding procedural examples for builds
openshift/openshift-docs pull request #66522
Opened 2023-10-19 07:43 UTC by shipsing

2023-10-20 08:05 UTC, apoorvajagtap commented on modules/ob-creating-a-buildah-build.adoc
> +----
```suggestion
```
We can remove this complete block. This kind of shows up v1alpha1 API, so let's avoid that.. Also, this one's not really mandatory & was just for information.

2023-10-23 10:37 UTC, shipsing commented
/label peer-review-needed

2023-10-23 13:25 UTC, jkhelil commented on modules/ob-creating-a-buildah-build.adoc
> +
We need a step here to check the build
 To view the *Build* which you just created:
oc get builds.shipwright.io
NAME                   REGISTERED   REASON      BUILDSTRATEGYKIND      BUILDSTRATEGYNAME   CREATIONTIME
buildah-golang-build   True         Succeeded   ClusterBuildStrategy   buildah             16s

And explanation for the output
@apoorvajagtap can you please give these

2023-10-23 13:25 UTC, jkhelil commented on modules/ob-creating-a-buildah-build.adoc
> +
I can see the verification are done at the end
wondering if we should rather do each verification after commands

so here for thebuildrun we retrive the buildrun
Wait until your *BuildRun* is completed and then you can view it as follows:

oc get buildruns
  
  NAME                              SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
  buildpack-nodejs-buildrun-xyzds   True        Succeeded   69s         2s

2023-10-23 17:21 UTC, adellape commented on modules/ob-creating-a-s2i-build.adoc
> +You can create a `source-to-image` build and push the created image to a custom quay repository.
```suggestion
You can create a `source-to-image` build and push the created image to a custom Quay repository.
```

2023-10-23 17:21 UTC, adellape commented on modules/ob-creating-a-s2i-build.adoc
> +<4> The location where the built image is pushed. You must push the built image to a custom quay repo. `pushSecret` is the secret name that stores the credentials for pushing container images. To gen
```suggestion
<4> The location where the built image is pushed. You must push the built image to a custom Quay repo. `pushSecret` is the secret name that stores the credentials for pushing container images. To generate a secret of the type `docker-registry` for authentication, see _Authentication to container registries_ in the _Additional resources_ section.
```

2023-10-23 17:21 UTC, adellape commented on modules/ob-creating-a-buildah-build.adoc
> +. Create a `BuildRun` resource and and apply it to the {ocp-product-title} cluster:
```suggestion
. Create a `BuildRun` resource and apply it to the {ocp-product-title} cluster:
```

2023-10-23 17:21 UTC, adellape commented on modules/ob-creating-a-s2i-build.adoc
> +----
Same suggestion as above re: breaking up the commands/outputs.

2023-10-25 06:12 UTC, shipsing commented on modules/ob-creating-a-buildah-build.adoc
> +$ podman pull image-registry.openshift-image-registry.svc:5000/buildah-example/sample-go-app
Thank you for this suggestion :)

2023-10-25 07:40 UTC, jkhelil approved these changes

2023-10-25 08:03 UTC, apoorvajagtap requested changes

2023-10-25 09:44 UTC, shipsing commented on modules/ob-creating-a-buildah-build.adoc
> +oc get builds.shipwright.io <build_resource_name>
Thank you for this suggestion

2023-10-25 12:15 UTC, apoorvajagtap requested changes

2023-10-25 12:15 UTC, apoorvajagtap commented on modules/ob-creating-a-s2i-build.adoc
> +    value: “quay.io/centos7/nodejs-12-centos7”
```suggestion
    value: quay.io/centos7/nodejs-12-centos7
```
The `"` is leading to a failure at the later stages, can we please remove these?

2023-10-25 12:18 UTC, apoorvajagtap commented on work_with_builds/using-builds.adoc
> +After installing {builds-shortname}, you can create a `buildah` or `source-to-image` build for use. You can also delete resources that are not required for a build.
If we can explicitly specify what resources we are talking to be deleted here, that'll be great.

2023-10-25 12:52 UTC, apoorvajagtap commented
LGTM.

2023-10-25 13:29 UTC, jitendar-singh commented
/label qe-approved

2023-10-25 13:59 UTC, shipsing commented
/label merge-review-needed

2023-10-25 14:14 UTC, merged

2023-10-25 14:14 UTC, adellape commented
/cherrypick build-docs-1.0