Updated OCP 3.4 Release Notes for RHSA-2017-3389
openshift/openshift-docs pull request #6654
Opened 2017-12-06 22:02 UTC by ahardin-rh

2017-12-06 22:10 UTC, adellape requested changes

2017-12-06 22:10 UTC, adellape commented on release_notes/ocp_3_4_release_notes.adoc
> +xref:../install_config/upgrading/automated_upgrades.adoc#running-the-upgrade-playbook-directly[Performing Automated In-place Cluster Upgrades] for instructions.
I think this was a copy/paste from 3.6 content, needs version tweaks.

2017-12-06 22:10 UTC, adellape commented on release_notes/ocp_3_4_release_notes.adoc
> +==== Images
Not critical, but usually we have the image list right after the intro part (before the list of BZs) in this scenario, right?

2017-12-06 22:13 UTC, adellape commented on release_notes/ocp_3_4_release_notes.adoc
> +`--bind-address=<ip address>:<port>` command-line flag and `bindAddress:`` configuration
Possible extra `` on `bindAddress` here.

2017-12-06 22:15 UTC, adellape commented
@ahardin-rh Also needs the `revhistory_full.adoc` file updated.

2017-12-06 22:16 UTC, adellape commented on release_notes/ocp_3_4_release_notes.adoc
> +xref:../install_config/upgrading/automated_upgrades.adoc#running-the-upgrade-playbook-directly[Performing Automated In-place Cluster Upgrades] for instructions.
Oh actually this looks like it shouldn't be here at all maybe? From the previous section?

2017-12-06 22:46 UTC, ahardin-rh commented
@adellape Thanks! Updated. I'll apply any similar changes to the other branch PRs

2017-12-06 23:18 UTC, ahardin-rh commented
@adellape Also bumped latest-tags for each branch

2017-12-07 19:24 UTC, adellape approved these changes

2017-12-07 19:24 UTC, adellape commented
:shipit:

2017-12-07 20:03 UTC, merged