Add prerequisites.yml to install steps
openshift/openshift-docs pull request #6668
Opened 2017-12-08 19:33 UTC by michaelgugino

Adding reference to running one-time step of
prerequisistes.yml

2017-12-20 15:33 UTC, ncbaratta requested changes

2017-12-20 15:33 UTC, nengard commented on install_config/install/advanced_install.adoc
> +First, running prerequisites will configure base packages and docker. It needs
Consider formatting to match modular templates:

Prequisites

Run `prequisites.yml` to configure the base packages and Docker.  This needs to be run only once between deploying a new cluster.

CODE HERE

Procedure

. Install OpenShift:

2017-12-20 15:33 UTC, nengard commented on install_config/install/advanced_install.adoc
> +First, running prerequisites will configure base packages and docker. It needs
If reformatting is not desired, rewording is still necessary to make the first sentence clearer.

"Run `prequisites.yml` to configure the base packages and Docker.  This needs to be run only once between deploying a new cluster."

2018-03-15 07:41 UTC, vikram-redhat commented
@adellape - PTAL for BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1525357#c12

2018-03-20 16:12 UTC, adellape commented
Taking care of this via https://github.com/openshift/openshift-docs/pull/8205.

2018-03-20 16:12 UTC, closed without merging