MIG-1475: Release notes for MTC 1.7.14
openshift/openshift-docs pull request #66760
Opened 2023-10-23 19:43 UTC by anarnold97

### Issue

* [MIG-1475](https://issues.redhat.com/browse/MIG-1475)

#### Version(s):

* Enterprise 4.11 → branch/enterprise-4.11
* Enterprise 4.12 → branch/enterprise-4.12
* Enterprise 4.13 → branch/enterprise-4.13
* Enterprise 4.14 → branch/enterprise-4.14

#### Issue:

* https://issues.redhat.com/browse/MIG-1475

### Link to docs preview:

* [MTR 1.7.14 release notes](https://66760--docspreview.netlify.app/openshift-enterprise/latest/migration_toolkit_for_containers/mtc-release-notes#migration-mtc-release-notes-1-7-14_mtc-release-notes)

QE review:
- [X](https://github.com/openshift/openshift-docs/pull/66760#pullrequestreview-1693775509) -  QE has approved this change.

Additional information:

2023-10-23 20:17 UTC, anarnold97 commented
/label mtc

2023-10-23 21:00 UTC, rayfordj requested changes

2023-10-23 21:00 UTC, rayfordj commented on modules/migration-mtc-release-notes-1-7-14.adoc
> +.CVE-2023-39325 CVE-2023-44487 openshift-velero-plugin-container: various flaws
Consider removing the "openshift-velero..." text as the preceding CVEs affect more than that single image (as noted by the BZ list which follows below).

2023-10-23 21:52 UTC, anarnold97 commented on modules/migration-mtc-release-notes-1-7-14.adoc
> +.CVE-2023-39325 CVE-2023-44487 openshift-velero-plugin-container: various flaws
Yeah I will remove from both headers
I need to tidy up the attributes as well

2023-10-24 01:15 UTC, rayfordj approved these changes
/lgtm

2023-10-24 09:16 UTC, anarnold97 commented
/label peer-review-needed

2023-10-24 11:57 UTC, ShaunaDiaz commented
/label peer-review-in-progress

2023-10-24 11:57 UTC, ShaunaDiaz commented
/remove-label peer-review-needed

2023-10-24 12:21 UTC, ShaunaDiaz reviewed
Complex release notes, great job. Some of these notes could benefit from having long sentences broken up and using active voice.

2023-10-24 12:21 UTC, ShaunaDiaz commented
/label peer-review-done

2023-10-24 12:21 UTC, ShaunaDiaz commented
/remove-label peer-review-in-progress

2023-10-24 15:07 UTC, anarnold97 commented
/label merge-review-needed

2023-10-24 16:33 UTC, kcarmichael08 commented
From a merge review standpoint, everything looks good to me. I was wondering why parentheses were used to set off all the Bugzilla and CVE entries, but I guess it's something that is normally done for this doc set? (It doesn't seem needed in these cases.)

2023-10-24 16:34 UTC, merged

2023-10-24 16:34 UTC, kcarmichael08 commented
/cherrypick enterprise-4.11

2023-10-24 16:34 UTC, kcarmichael08 commented
/cherrypick enterprise-4.12

2023-10-24 16:34 UTC, kcarmichael08 commented
/cherrypick enterprise-4.13

2023-10-24 16:35 UTC, kcarmichael08 commented
/cherrypick enterprise-4.14

2023-10-24 17:01 UTC, anarnold97 commented
@kcarmichael08 
```
From a merge review standpoint, everything looks good to me. I was wondering why parentheses were used to set off all the Bugzilla and CVE entries, but I guess it's something that is normally done for this doc set? (It doesn't seem needed in these cases.)
```
I know, right... cos it looks really weird!