ROX-20485: Add updates to release notes for 4.1.5 patch release
openshift/openshift-docs pull request #67393
Opened 2023-11-03 19:25 UTC by kcarmichael08

Version(s):
`rhacs-docs-4.1`

[Issue](https://issues.redhat.com/browse/ROX-20485)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-11-07 14:17 UTC, vladbologa requested changes

2023-11-07 14:17 UTC, vladbologa commented on release_notes/41-release-notes.adoc
> +//glibc security issues mentioned because of high visibility and because Collector links these libraries
```suggestion
```

2023-11-07 14:29 UTC, vladbologa commented on release_notes/41-release-notes.adoc
> +* The HTTP/2 webhook in the {product-title-short} Operator has been disabled to mitigate CVE-2023-44487.
Maybe this could be rephrased to something like:

> The HTTP/2 functionality in the {product-title-short} Operator webhook has been disabled to mitigate CVE-2023-44487.

The point is that the webhook is still there, it just never uses HTTP/2 anymore.

2023-11-07 14:38 UTC, vladbologa approved these changes
LGTM!

2023-11-07 16:08 UTC, tmalove commented
/remove-label peer-review-needed
/label peer-review-in-progress

2023-11-07 16:19 UTC, tmalove commented
/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

2023-11-08 00:22 UTC, gaurav-nelson commented
**issue:** @kcarmichael08 Can you please also update the `rhacs-version` variable in the `modules/common-attributes.adoc` file. 🦤

2023-11-08 13:32 UTC, kalexand-rh approved these changes

2023-11-08 17:35 UTC, merged