virt, DPDK checkup: Label the CM and Job
openshift/openshift-docs pull request #67463
Opened 2023-11-07 10:48 UTC by orelmisan

In order for the UI to be able to get ConfigMap and Job objects that were manually created by oc,
label them as belonging to the checkup.

Version(s):

4.15+

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-11-07 10:51 UTC, orelmisan commented
/cc @RamLavi @segevyos

2023-11-07 14:24 UTC, orelmisan commented
@sjhala-ccs do you know if the CI stuck for some reason?

2023-11-07 14:32 UTC, sjhala-ccs commented
> @sjhala-ccs do you know if the CI stuck for some reason?

@orelmisan We are having issues with Travis CI right now. Travis won't start builds unless you have admin access to the repo and have linked your GitHub and Travis accounts! While we work on fixing the issue, I will need to close and re-open your PR to trigger the build.

2023-11-07 16:23 UTC, orelmisan commented
> > @sjhala-ccs do you know if the CI stuck for some reason?
> 
> @orelmisan We are having issues with Travis CI right now. Travis won't start builds unless you have admin access to the repo and have linked your GitHub and Travis accounts! While we work on fixing the issue, I will need to close and re-open your PR to trigger the build.

Thank you @sjhala-ccs

2023-11-08 06:46 UTC, segevyos requested changes

2023-11-08 06:46 UTC, segevyos commented on modules/virt-checking-cluster-dpdk-readiness.adoc
> +    kignose/checkup-type: kubevirt-dpdk
:s/kignose/kiagnose ?

2023-11-08 07:02 UTC, orelmisan commented on modules/virt-checking-cluster-dpdk-readiness.adoc
> +    kignose/checkup-type: kubevirt-dpdk
Good catch!
Thank you

2023-11-08 07:03 UTC, orelmisan commented
[Change](https://github.com/openshift/openshift-docs/compare/3780ef40c9aadd4a8186204dc8ad77f0291ce342..6979194bc79607c5c8d2a4906a685840ce7c5200): Fix a review [comment](https://github.com/openshift/openshift-docs/pull/67463#discussion_r1386082052).

2023-11-08 07:03 UTC, segevyos commented
/lgtm

2023-11-08 14:37 UTC, sjhala-ccs approved these changes
LGTM

2023-11-08 14:37 UTC, merged

2023-11-08 14:37 UTC, sjhala-ccs commented
/cherrypick enterprise-4.15