clarify config map <-> pod template sync in jenkins
openshift/openshift-docs pull request #6756
Opened 2017-12-13 21:16 UTC by gabemontero

Fixes https://github.com/openshift/openshift-docs/issues/6664

@bparees @bmcelvee @codrinbucur ptal

2017-12-13 21:19 UTC, bparees requested changes

2017-12-13 21:19 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +- Similarly, if those objects are in fact removed, the corresponding configuration
s/in fact//

2017-12-13 21:19 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +initial creation, leads to the creation of `PodTemplate` in the Kubernetes-plugin
s/creation of/creation of a/

2017-12-13 21:19 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +Kubernetes plug-in configuration, and will even override any changes made to the
s/even//

2017-12-13 21:29 UTC, gabemontero commented
@bparees comment updates pushed

2017-12-13 21:31 UTC, bparees commented
lgtm.

2017-12-14 15:27 UTC, bmcelvee commented
LGTM. Is this ready to merge? If so, I'll merge and make some minor formatting edits in a follow-up PR. Thanks!

2017-12-14 16:06 UTC, gabemontero commented
yep this is for existing / already release functino @bmcelvee - go ahead and merge at your discretion

2017-12-14 20:11 UTC, bmcelvee commented
[rev_history]
|xref:../using_images/other_images/jenkins.adoc#using-images-other-images-jenkins[Jenkins]
|Clarified ConfigMap and PodTemplate sync definitions in xref:../using_images/other_images/jenkins.adoc#using-the-jenkins-kubernetes-plug-in-to-run-jobs[Using the Jenkins Kubernetes Plug-in to Run Jobs] section.
%

2017-12-14 20:15 UTC, merged