[RHACS] ROX-20486: Adding updates to release notes for 4.2.3 patch release
openshift/openshift-docs pull request #67617
Opened 2023-11-09 12:42 UTC by agantony

Version(s):
4.2

Issue:
https://issues.redhat.com/browse/ROX-20486

Link to docs preview:

SME review:
- [ ] SME has approved this change.

Additional information:
- Merge into `rhacs-docs-4.2`

2023-11-09 12:53 UTC, agantony commented
Tech review needed

2023-11-09 13:41 UTC, vladbologa requested changes

2023-11-09 13:41 UTC, vladbologa commented on release_notes/42-release-notes.adoc
> +* All containers have been rebuilt and now include container CVE fixes for link:https://access.redhat.com/security/cve/cve-2023-44487[CVE-2023-44487]: Flaw in handling multiplexed streams in the HTTP
The 4.2.2 containers are currently not marked as being affected by CVE-2023-44487.

2023-11-09 17:09 UTC, vladbologa approved these changes
LGTM

2023-11-09 17:11 UTC, agantony commented
/label peer-review-needed

2023-11-09 19:00 UTC, tmalove commented
/remove-label peer-review-needed
/label peer-review-in-progress

2023-11-09 19:16 UTC, tmalove commented
/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

2023-11-10 07:41 UTC, agantony commented
/label merge-review-needed

2023-11-10 14:01 UTC, mjpytlak reviewed
@agantony Please squash your commits. Also - I presume you do not want this merged until November 15th?

2023-11-10 18:17 UTC, agantony commented
> @agantony Please squash your commits. Also - I presume you do not want this merged until November 15th?

Oh yeah, that's for November 15, good catch!
I will squash the commits too.

2023-11-10 18:39 UTC, mjpytlak commented
@agantony I will be off the squad next week, but for the sake expediency remind me on the 15th to merge this. Have a good weekend.

2023-11-13 07:42 UTC, agantony commented on release_notes/42-release-notes.adoc
> +* The HTTP/2 functionality in the {product-title-short} Operator webhook has been disabled to mitigate CVE-2023-44487.
I appreciate and value your feedback. However, let us leave it the way it is to maintain consistency with  https://docs.openshift.com/acs/4.1/release_notes/41-release-notes.html#resolved-in-version-415_release-notes-41:~:text=The%20HTTP/2%20functionality%20in%20the%20RHACS%20Operator%20webhook%20has%20been%20disabled%20to%20mitigate%20CVE%2D2023%2D44487.

2023-11-15 12:44 UTC, kcarmichael08 approved these changes
LGTM!

2023-11-16 06:28 UTC, agantony commented
The GA date is yet to be confirmed. Please do not merge this PR.

2023-11-17 14:12 UTC, vladbologa requested changes

2023-11-17 14:12 UTC, vladbologa commented on release_notes/42-release-notes.adoc
> +* link:https://access.redhat.com/security/cve/CVE-2023-40217[CVE-2023-40217]: Python 3 ssl.SSLSocket vulnerability.
```suggestion
```

Please remove this, 4.2.2 is not affected by CVE-2023-40217

2023-11-27 10:45 UTC, vladbologa approved these changes

2023-11-27 20:41 UTC, kcarmichael08 commented
replaced by #68436

2023-11-27 20:41 UTC, closed without merging