MIG-1504: MTC 1.8.2 release notes
openshift/openshift-docs pull request #67775
Opened 2023-11-10 20:16 UTC by anarnold97

### Jira

* [MIG-1504](https://issues.redhat.com/browse/MIG-1504)

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-11-10 20:16 UTC, anarnold97 commented
/label mtc

2023-11-10 21:35 UTC, rayfordj requested changes

2023-11-10 21:35 UTC, rayfordj commented on modules/migration-mtc-release-notes-1-8.adoc
> +
[These](https://github.com/openshift/openshift-docs/pull/67775/files#diff-f1f0c55ea489db1d283dfe452b491e98f1c8179beb042cb810fe81f3a2f648f9R49-R75) are under 1.8 "known issues".  I would expect them to be found under 1.8.2 "resolved issues" [section](https://github.com/openshift/openshift-docs/pull/67775/files#diff-f2ddeabe0025f31b3a1aef70b1da720407483c0ae248594cb5980a5ace1fb9e9R8-R14).

2023-11-10 21:53 UTC, anarnold97 commented on modules/migration-mtc-release-notes-1-8.adoc
> +
sorry forgot to save the 1.8.2 release notes doc

2023-11-13 15:03 UTC, rayfordj approved these changes
/lgtm

2023-11-15 10:04 UTC, anarnold97 commented
/label peer-review-needed

2023-11-15 18:35 UTC, bburt-rh reviewed
Thanks for the PR. Please see my suggested edits and comments to help improve the flow of the language and to align the PR with our style and formatting guidance. After you've pushed your updates to the PR, let me know, and I will take another look. Thanks again!

2023-11-15 18:35 UTC, bburt-rh commented on modules/migration-mtc-release-notes-1-8-2.adoc
> +It is advised to update to {mtc-short} 1.8.2 or later, which resolve this issue.
```suggestion
To resolve this issue, update to {mtc-short} 1.8.2 or later .
```
Don't use "advise" or "recommend". We want to be more prescriptive and prevent any user uncertainty. See the SSG entry on "recommend": https://redhat-documentation.github.io/supplementary-style-guide/#recommend

In any case, I think you can simply delete this line. This item is in the "Resolved issues" section, after all.

2023-11-15 18:35 UTC, bburt-rh commented on modules/migration-mtc-release-notes-1-8-2.adoc
> +It is advised to update to {mtc-short} 1.8.2 or later, which resolve this issue.
```suggestion
To resolve the issue, update to {mtc-short} 1.8.2 or later.
```

Reword, or I think you can simply delete this line. This item is in the "Resolved issues" section, after all.

2023-11-15 18:35 UTC, bburt-rh commented on modules/migration-mtc-release-notes-1-8-2.adoc
> +In previous releases of ({mtc-short}), versions of the package semver before 7.5.2, used in {mtc-short}, were vulnerable to Regular Expression Denial of Service (ReDoS) from the function new Range, w
```suggestion
In previous releases of ({mtc-short}), versions prior to 7.5.2 of the `semver` package used in {mtc-short} were vulnerable to Regular Expression Denial of Service (ReDoS) attacks when untrusted user data was provided as a range in the new `Range` function.
```
- Put `Range` in backticks because it's a code function
- Rephrase for better flow.

2023-11-15 18:35 UTC, bburt-rh commented on modules/migration-mtc-release-notes-1-8-2.adoc
> +There are no major known issues in this release.
```suggestion
No major known issues exist in this release.
```
Per the IBM Style guide, restructure sentences to avoid using "there is" and "there are".

2023-11-15 18:35 UTC, bburt-rh commented on modules/migration-mtc-release-notes-1-8.adoc
> +In {mtc-full} ({mtc-short}), after editing the replication repository, and adding a custom CA, and the repo is successfully connected, when triggering a migration, there is a failure returned on the
```suggestion
In {mtc-full} ({mtc-short}), after a user edited the replication repository, added a custom CA certificate, successfully connected the repository, and triggered a migration, a failure occurred during the backup phase.
```
- See previous comment on similar issue.

2023-11-15 18:35 UTC, bburt-rh commented on modules/migration-mtc-release-notes-1-8.adoc
> +This issue has been resolved in in {mtc-short} 1.8.2.
```suggestion
This issue has been resolved in {mtc-short} 1.8.2.
```
- Remove repeated word
- I think you can delete this line as redundant. You've already mentioned that these are fixed issues, correct?

2023-11-15 18:35 UTC, bburt-rh commented on modules/migration-mtc-release-notes-1-8.adoc
> +It is advised to update to {mtc-short} 1.8.2 or later, which resolve this issue.
```suggestion
In previous releases of ({mtc-short}), versions prior to 7.5.2 of the `semver` package used in {mtc-short} were vulnerable to Regular Expression Denial of Service (ReDoS) attacks when untrusted user data was provided as a range in the new `Range` function.

To resolve the issue, update to {mtc-short} 1.8.2 or later.
```

I have the same comments and suggested edits as in the previous nearly identical item.

2023-11-15 18:35 UTC, bburt-rh commented on modules/migration-mtc-release-notes-1-8.adoc
> +It is advised to update to {mtc-short} 1.8.2 or later, which resolve this issue.
```suggestion
In previous releases of ({mtc-short}), versions prior to 4.13 of the `tough-cookie` package used in {mtc-short} were vulnerable to prototype pollution. This vulnerability occurred because CookieJar did not handle cookies properly when the value of the `rejectPublicSuffixes` setting was set to `false` [maybe also mention in what config file??].

To resolve the issue, update to {mtc-short} 1.8.2 or later.
```
I have the same comments as in the previous nearly identical item. Please revise per those suggestions.

2023-11-15 20:06 UTC, anarnold97 commented
> Thanks for the PR. Please see my suggested edits and comments to help improve the flow of the language and to align the PR with our style and formatting guidance. After you've pushed your updates to the PR, let me know, and I will take another look. Thanks again!

@bburt-rh - changed. please push to merge review as soon as possible

2023-11-15 21:19 UTC, anarnold97 commented
/label merge-review-needed

2023-11-15 21:21 UTC, anarnold97 commented
@bburt-rh - as i presume you did not see that the GA date was changed to today while i was offline last night, i am going to push this to merge review

2023-11-15 22:28 UTC, merged

2023-11-15 22:28 UTC, mburke5678 commented
/cherrypick enterprise-4.11

2023-11-15 22:28 UTC, mburke5678 commented
/cherrypick enterprise-4.12

2023-11-15 22:28 UTC, mburke5678 commented
/cherrypick enterprise-4.13

2023-11-15 22:28 UTC, mburke5678 commented
/cherrypick enterprise-4.14

2023-11-15 22:29 UTC, mburke5678 commented
/cherrypick enterprise-4.15

2023-11-15 22:46 UTC, anarnold97 commented
@mburke5678 - thanks very much. really appreciate you getting this push