WIP: Changed oauthclientauthorization name per Trello
openshift/openshift-docs pull request #6777
Opened 2017-12-14 20:53 UTC by mburke5678

https://trello.com/c/2UC7OSgV/715-document-security-user-management-of-oauthclientauthorization
https://jira.coreos.com/browse/AUTH-30

Per Mo Kahn: It is currently not high enough priority to be worked on. Earliest I expect to see anything in 3.13.

2017-12-14 21:05 UTC, enj commented
The naming change has not been API approved yet, so the docs should not be changed yet.

2018-02-15 18:23 UTC, mburke5678 commented
@enj Can you PTAL. I brought down your text from https://github.com/openshift/origin/pull/11909 and worked it into our existing topic, as you suggested. 
Will this functionality be available in the Web Console or just the CLI?

2018-02-20 18:55 UTC, enj requested changes

2018-02-20 18:55 UTC, enj commented on architecture/additional_concepts/authentication.adoc
> +*_/openshift.io/oauth/clientauthorizations/<userName>/<clientName>_*.
This is an implementation detail that will not be exposed to end users.

2018-02-20 18:55 UTC, enj commented on architecture/additional_concepts/authentication.adoc
> +where the previous format is `<userName>:<clientName>`.
Users never knew the old format, so the new format is not relevant to them.  Thus this information would go into the "admin" section.

2018-02-20 18:55 UTC, enj commented on architecture/additional_concepts/authentication.adoc
> +Having a specific directory allows for faster lookup times for a user.
Implementation detail.

2018-02-20 18:55 UTC, enj commented on architecture/additional_concepts/authentication.adoc
> +oc get oauthclientauthorization -o jsonpath="{range .items[*]}{.metadata.name}{\"\\n\"}{end}" | grep -v '::' | xargs -n 1 echo oc delete oauthclientauthorization
Commands that delete data are dangerous and not something I want to include in the docs.  I am ok with saying the "cluster admin has to delete...", but not ok with giving people copy paste logic that could harm their cluster.

2018-02-20 18:55 UTC, enj commented on architecture/additional_concepts/authentication.adoc
> +Previously, {product-title} maintained OAuth Client Authorizations in etcd.
Umm, everything is still in etcd.  Nothing is stored locally or in some file system.

2018-02-20 18:55 UTC, enj commented on architecture/additional_concepts/authentication.adoc
> +== Managing OAuth Objects
client authorizations

2018-02-20 18:55 UTC, enj commented on architecture/additional_concepts/authentication.adoc
> +<3> The scope of the access request.
The list of authorized scopes from the given user to the specified client

2018-02-20 18:55 UTC, enj commented on architecture/additional_concepts/authentication.adoc
> +oc delete oauthclientauthorization <file-client-name>
```<file-client-name>```?  where did file come from?

2018-02-20 18:58 UTC, enj commented
@mburke5678 lets wait on any further doc changes until after the changes are actually added to origin (3.10+ timeframe).  As a start only the CLI will support this feature, but there is no reason the web console could not support it at some future point (it is an advanced use case so it may be too much for the console).

2018-04-09 14:41 UTC, mburke5678 commented
@enj Is this feature officially scheduled for 3.10? 

cc. @vikram-redhat

2018-04-10 01:03 UTC, enj commented
No we had no cycles in 3.10 to work on this.

2018-04-10 10:42 UTC, vikram-redhat commented
@mburke5678 ok - I have changed the label to 3.11.

2018-07-31 06:04 UTC, vikram-redhat commented
@mburke5678 @enj - is this scheduled for 3.11?

2018-07-31 13:43 UTC, mburke5678 commented
@vikram-redhat Asked Mo via a note in Dev Trello for status

2018-07-31 15:31 UTC, mburke5678 commented
@vikram-redhat Per Mo Kahn: [It is currently not high enough priority to be worked on. Earliest I expect to see anything in 3.13](https://trello.com/c/Tcabgp9F/21-8-user-management-of-oauthclientauthorization#comment-5b607d3d7142130c6411747c).

2018-10-25 06:18 UTC, closed without merging