[DOC] OSSM-5357 Openshift Userworkload Monitoring integration documentation bug
openshift/openshift-docs pull request #67856
Opened 2023-11-14 14:29 UTC by gwynnemonahan

[DOC] OSSM-5357 Openshift Userworkload Monitoring integration documentation bug

Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OSSM-5357 

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

Updates code block to add missing field for Step 2 Configure Kiali for user-workload monitoring:

2023-11-14 17:14 UTC, jmazzitelli requested changes
i will quickly check the name of hte configmap, but for now, there is a trivial change request here

2023-11-14 17:14 UTC, jmazzitelli commented on modules/ossm-integrating-with-user-workload-monitoring.adoc
> +  version: v1.65
trivial: end of line space should be removed

2023-11-14 17:57 UTC, jmazzitelli approved these changes
This is correct. I installed Maistra Operator and Kiali Operator and created an SMCP called "custom" and the configmap matches the docs ("istio-" followed by the SMCP name). Here's what I see:

The name of the SMCP (`custom`):
```
$ oc get smcp -n istio-system
NAME     READY   STATUS            PROFILES      VERSION   AGE
custom   9/9     ComponentsReady   ["default"]   2.4.4     2m52s
```

The name of the ConfigMap (`istio-custom`):
```
$ oc get configmap -n istio-system istio-custom 
NAME           DATA   AGE
istio-custom   2      3m3s
```

The Kiali CR setting:
```
$ oc get kiali kiali -n istio-system -ojsonpath={.spec.external_services.istio} |jq
{
  "config_map_name": "istio-custom",
  "istio_sidecar_injector_config_map_name": "istio-sidecar-injector-custom",
  "istiod_deployment_name": "istiod-custom",
  "url_service_version": "http://istiod-custom.istio-system:15014/version"
}
```

2023-11-14 19:45 UTC, gwynnemonahan commented
/label peer-review-needed

2023-11-15 05:47 UTC, shipsing commented
/label peer-review-in-progress
/remove-label peer-review-needed

2023-11-15 07:02 UTC, shipsing requested changes

2023-11-15 07:03 UTC, shipsing commented
@gwynnemonahan, I have provided a few suggestions for you to consider. Please have a look at them.
 
Since i am new to the peer review squad, i would ask @bburt-rh to give my review the go-ahead. Please wait until Brain applies the peer-review-done label.

2023-11-15 14:02 UTC, bburt-rh commented
@shipsing - The review lgtm. Adding the peer-review-done label.

2023-11-15 14:02 UTC, bburt-rh commented
/label peer-review-done

2023-11-15 19:21 UTC, gwynnemonahan commented
/label merge-review-needed

2023-11-15 20:01 UTC, mburke5678 commented
@gwynnemonahan Please squash your commits.

2023-11-15 20:10 UTC, merged

2023-11-15 20:10 UTC, mburke5678 commented
/cherrypick enterprise-4.11

2023-11-15 20:10 UTC, mburke5678 commented
/cherrypick enterprise-4.12

2023-11-15 20:10 UTC, mburke5678 commented
/cherrypick enterprise-4.13

2023-11-15 20:10 UTC, mburke5678 commented
/cherrypick enterprise-4.15

2023-11-15 20:19 UTC, mburke5678 commented
/cherrypick enterprise-4.14