WIP PodVolumeBackup
openshift/openshift-docs pull request #68042
Opened 2023-11-16 10:18 UTC by RichardHoch

OADP 1.3, OCP 4.11+

Resolves https://issues.redhat.com/browse/OADP-3058

2023-11-19 10:45 UTC, RichardHoch commented
@weshayutin @kaovilai Not sure who the SME is for this; please ask someone to review it.

2023-11-20 17:52 UTC, kaovilai requested changes

2023-11-22 16:00 UTC, RichardHoch commented
@kaovilai I've added the limitations as you suggested. Please review the PR again. Thanks.

2023-11-22 18:09 UTC, kaovilai approved these changes

2023-11-23 11:08 UTC, stillalearner approved these changes
lgtm

2023-11-23 12:35 UTC, RichardHoch commented
/label OADP
/label peer-review-needed

2023-11-24 05:01 UTC, agantony commented
/label peer-review-in-progress

2023-11-24 06:18 UTC, agantony reviewed
I've added a few suggestions for your consideration; overall lgtm!

There are also some formatting issues in https://68042--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/oadp-advanced-topics#oadp-cluster-to-cluster-uid-and-gid-ranges_oadp-advanced-topics

**Suggestion:** Maybe you can use discrete headings to fix them

2023-11-24 06:18 UTC, agantony commented on modules/oadp-pod-volume-backup.adoc
> +VFSB does not work with them as expected.
> PVC/PV

Use "and", "or"??

2023-11-26 09:49 UTC, RichardHoch commented on modules/oadp-backing-up-opt-in.adoc
> +where the volume names are the names of the volumes in the pod spec.
I'm following the third example in that section.

2023-11-26 10:50 UTC, RichardHoch commented on modules/oadp-backing-up-opt-out.adoc
> +You can use the opt-out method to indicate which volumes to *not* back up. You do this by using the `backup.velero.io/backup-volumes-excludes` command.
"should" can imply advice, so I am sticking with a definite statement, as above. I moved "not," though.

2023-11-26 10:51 UTC, RichardHoch commented on modules/oadp-backing-up-opt-out.adoc
> +where the volume names are the names of the volumes in the pod spec.
Likewise.

2023-11-26 11:28 UTC, anarnold97 commented
@agantony hey man how are you?
I am going to ask @RichardHoch to push this to merge review, we have a GA in two days and still have so much stuff to do 
I will come back to this post release and add your suggestions.

Thanks andy

2023-11-26 11:45 UTC, RichardHoch commented on modules/oadp-backing-up-opt-out.adoc
> +* Volumes that mount the default service account token, secrets, and configuration maps.
Don't we need a serial (aka Oxford) comma here?

2023-11-26 12:13 UTC, RichardHoch commented on modules/oadp-cluster-to-cluster-uid-and-gid-ranges.adoc
> +The UID and GID ranges of the namespace might change on the destination cluster. OADP does not back up and restore OpenShift UID range metadata. If the backed application requires a specific UID, ens
Much better! Thanks!

2023-11-26 14:45 UTC, RichardHoch commented
/label merge-review-needed

2023-11-26 14:46 UTC, RichardHoch commented
GA is Tuesday, November 28.

2023-11-27 14:02 UTC, mburke5678 commented on modules/oadp-backing-up-opt-in.adoc
> +<your_volume_name_x> specifies the name of the xth volume in the pod specification.
s/<your_volume_name_x>/`<your_volume_name_x>`::

2023-11-27 14:08 UTC, mburke5678 commented
@RichardHoch I found a couple of things we should get before merging.

2023-11-27 14:15 UTC, agantony commented
> @agantony Is the peer review done?

Yup!
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2023-11-27 15:09 UTC, weshayutin approved these changes
LGTM, thanks Richard

2023-11-27 15:34 UTC, RichardHoch commented on modules/oadp-backing-up-opt-in.adoc
> +<your_volume_name_x> specifies the name of the xth volume in the pod specification.
Thanks! Now I know more.

2023-11-29 08:11 UTC, RichardHoch commented
/label merge-review-needed

2023-11-29 08:12 UTC, RichardHoch commented
Please merge today; release went GA.

2023-11-29 17:16 UTC, merged

2023-11-29 17:16 UTC, mburke5678 commented
/cherrypick enterprise-4.11

2023-11-29 17:17 UTC, mburke5678 commented
/cherrypick enterprise-4.12

2023-11-29 17:17 UTC, mburke5678 commented
/cherrypick enterprise-4.13

2023-11-29 17:17 UTC, mburke5678 commented
/cherrypick enterprise-4.14