OCPBUGS-18412:updates command for changing log levels
openshift/openshift-docs pull request #68168
Opened 2023-11-17 20:48 UTC by JoeAldinger

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-11-28 16:39 UTC, GroceryBoyJr commented
/label peer-review-in-progress
/remove-label peer-review-needed

2023-11-28 16:57 UTC, GroceryBoyJr reviewed
LGTM

2023-11-28 16:57 UTC, GroceryBoyJr commented
/label peer-review-done
/remove-label peer-review-in-progress

2023-11-29 19:07 UTC, rbbratta commented
/lgtm

2023-11-29 19:07 UTC, rbbratta approved these changes

2023-11-29 19:09 UTC, rbbratta requested changes

2023-11-29 19:09 UTC, rbbratta commented on modules/nw-ovn-kubernetes-change-log-levels.adoc
> +$ oc apply -f configmap env-overrides.yaml -n openshift-ovn-kubernetes
no `configmap`

2023-11-29 19:11 UTC, rbbratta commented
/lgtm cancel

2023-11-29 19:17 UTC, JoeAldinger commented on modules/nw-ovn-kubernetes-change-log-levels.adoc
> +$ oc apply -f configmap env-overrides.yaml -n openshift-ovn-kubernetes
@rbbratta look good now?

2023-11-29 19:45 UTC, rbbratta approved these changes
/lgtm

2023-11-30 18:56 UTC, merged

2023-11-30 18:56 UTC, JoeAldinger commented
/cherrypick enterprise-4.14

2023-11-30 18:57 UTC, JoeAldinger commented
/cherrypick enterprise-4.13

2023-11-30 18:57 UTC, JoeAldinger commented
/cherrypick enterprise-4.12