update jenkins doc for new secret->credential sync feature
openshift/openshift-docs pull request #6821
Opened 2017-12-15 21:56 UTC by gabemontero

doc changes for https://trello.com/c/SGvNKyMM/1154-5-make-openshift-secrets-available-in-jenkins-as-credentials-jenkinsintegration

@openshift/sig-developer-experience @bmcelvee ptal

2017-12-15 21:57 UTC, gabemontero commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Make openshift secrets available in jenkins as credentials [jenkins_integration]](https://trello.com/c/SGvNKyMM/1154-5-make-openshift-secrets-available-in-jenkins-as-credentials-jenkinsintegration)

2017-12-15 23:17 UTC, bparees requested changes
couple nits and lgtm

2017-12-15 23:17 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +this plug-in can create `PodTemplate` configuration for the Kubernetes plug-in
configurations

2017-12-15 23:17 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +Jenkins credetials which are placed in the default global domain within
credentials

2018-01-01 17:40 UTC, gabemontero commented
spelling corrections pushed

2018-01-01 17:47 UTC, bparees commented
lgtm

2018-01-02 14:21 UTC, gabemontero commented
@bmcelvee - re: the card referenced above, this is 3.9 content

2018-01-03 01:17 UTC, bmcelvee commented
Thanks @gabemontero! LGTM, I'm just going to make some minor edits in a follow-up PR.

2018-01-03 01:18 UTC, merged

2018-01-04 16:04 UTC, bmcelvee commented
[rev_history]
|xref:../using_images/other_images/jenkins.adoc#using-images-other-images-jenkins[Jenkins]
|Added credential sync content to the xref:../using_images/other_images/jenkins.adoc#sync-plug-in[{product-title} Sync Plug-in] section.
%