OSDOCS-8376: Migrate "Getting Started with Rosa - Deploy the Cluster (HCP)"
openshift/openshift-docs pull request #68291
Opened 2023-11-21 19:21 UTC by jneczypor

OSDOCS-8376: Migrate "Getting Started with Rosa - Deploy the Cluster (HCP)" from rosaworkshop.io into product documentation.

Version(s):
4.14+
Issue:
https://issues.redhat.com/browse/OSDOCS-8376

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-11-27 18:55 UTC, jneczypor commented
Hi @yuwang-RH! Can I please get a QE review of this PR? Thank you!

2023-11-28 13:24 UTC, dupliaka commented on cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-deploying/cloud-experts-getting-started-hcp.adoc
> +. Create the VPC. For this workshop, the following script will create the VPC and its required components for you. It will use the region configured for the `aws` CLI.
workshop

2023-11-28 13:25 UTC, dupliaka commented on cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-deploying/cloud-experts-getting-started-hcp.adoc
> +In this workshop, we will use the automatic mode when creating the OIDC configuration. We will also store the OIDC ID as an environment variable for later use. The command uses the ROSA CLI to create
Workshop leftover

2023-11-28 13:25 UTC, dupliaka commented on cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-deploying/cloud-experts-getting-started-hcp.adoc
> +export OIDC_ID=$(rosa create oidc-config --mode auto --managed --yes -o json | jq -r '.id')
Workshop leftover

2023-11-28 14:00 UTC, dupliaka requested changes
Thanks for the change, however as a QE I need more clarification on this new section, please follow https://issues.redhat.com/browse/OSDOCS-8376

2023-11-29 15:17 UTC, dupliaka commented on cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-deploying/cloud-experts-getting-started-hcp.adoc
> +The control plane and API are ready after about 10 minutes and the worker nodes and cluster are ready and completely useable after about 15 to 20 minutes. The cluster will have a control plane across
That conflicts with Provisioning time mentioned in:
 https://68291--docspreview.netlify.app/openshift-rosa/latest/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly#rosa-hcp-classic-comparison_rosa-hcp-sts-creating-a-cluster-quickly

2023-11-29 19:06 UTC, jneczypor commented
Hi @dupliaka - I made the suggested edits to the tutorial. Is there anything else that needs to be changed in this HCP tutorial before I move it to peer review? Thanks!

2023-11-30 12:30 UTC, dupliaka approved these changes
Thanks @jneczypor, approved for Hosted Control Planes guide

2023-12-04 21:39 UTC, merged

2023-12-04 21:39 UTC, EricPonvelle commented
/cherrypick enterprise-4.14

2023-12-04 21:39 UTC, EricPonvelle commented
/cherrypick enterprise-4.15