[SRVKS-984] Add docs on using Serving with OpenShift ingress sharding
openshift/openshift-docs pull request #68454
Opened 2023-11-28 12:50 UTC by rh-max

Version(s):
`serverless-docs-1.30`+

Issue:
https://issues.redhat.com/browse/SRVKS-984

Link to docs preview:
FIXME

QE review:
- [ ] QE has approved this change.

2023-11-29 13:40 UTC, skonto commented
cc @ReToCode

2023-11-29 13:48 UTC, ReToCode requested changes

2023-11-29 13:49 UTC, ReToCode commented on modules/targeting-a-specific-ingress-shard-in-the-knative-service.adoc
> +.Example KnativeServing CR
<img width="893" alt="image" src="https://github.com/openshift/openshift-docs/assets/16611466/46f57023-5ec1-46f4-8c63-3e60ecba7689">

2023-11-30 10:45 UTC, rh-max commented on modules/targeting-a-specific-ingress-shard-in-the-knative-service.adoc
> +.Example KnativeServing CR
I fixed the broken markup, but as far as I can tell the example is the correct one. See here:
https://openshift-knative.github.io/docs/docs/latest/serverless/serving/serving-with-ingress-sharding.html

2023-11-30 11:53 UTC, ReToCode commented on modules/targeting-a-specific-ingress-shard-in-the-knative-service.adoc
> +.Example KnativeServing CR
Markup is good now, but it is the wrong example. Compare https://68454--docspreview.netlify.app/openshift-serverless/latest/knative-serving/external-ingress-routing/using-serving-with-ingress-sharding#targeting-a-specific-ingress-shard-in-the-knative-service_using-serving-with-ingress-sharding with the one in the draft docs. You have the same YAML twice.

2023-11-30 13:39 UTC, ReToCode commented on modules/targeting-a-specific-ingress-shard-in-the-knative-service.adoc
> +.Example KnativeServing CR
👍  the legend also needs an update `Example KnativeServing CR` should be `Example Service CR`

2023-11-30 19:42 UTC, nalhadef commented
Don't forget to squash your commits.

2023-11-30 20:37 UTC, nalhadef commented on modules/configuring-openshift-ingress-shards.adoc
> +* In the `IngressController` CR, configure {ServerlessProductName} to match specific ingress shards with different domains with a label selector:
is label selector being used to configure the {ServerlessProductName}? If so, I'd shuffle the sentence to put the two items closer toghether:
"Use a label selector in the `IngressController` CR to configure {ServerlessProductName} to match specific ingress shards with different domains"

2023-11-30 20:37 UTC, nalhadef commented
Just a couple of suggestions.

2023-12-04 18:17 UTC, rh-max commented on modules/configuring-custom-domains-in-knativeserving-CR.adoc
> += Configuring custom domains in the KnativeServing CR
Checked the PR and expanded "Serving" to "Knative Serving" in several places.

2023-12-07 14:28 UTC, rh-max commented
/label merge-review-needed

2023-12-07 15:05 UTC, rh-max commented on knative-serving/external-ingress-routing/using-serving-with-ingress-sharding.adoc
> +Even with OpenShift ingress sharding in place, {ServerlessProductName} traffic is still routed through a single Knative Ingress Gateway and the activator component in the `knative-serving` project.
I've added the link, and the PR is currently not building, as it is awaiting https://github.com/openshift/openshift-docs/pull/68618 to be merged.

2023-12-07 18:03 UTC, rh-max commented on knative-serving/external-ingress-routing/using-serving-with-ingress-sharding.adoc
> +Even with OpenShift ingress sharding in place, {ServerlessProductName} traffic is still routed through a single Knative Ingress Gateway and the activator component in the `knative-serving` project.
The build is now successful, since the link works.

2023-12-07 20:09 UTC, jeana-redhat reviewed
Just a  few things to touch up and a couple questions

/remove-label merge-review-in-progress
/remove-label merge-review-needed

2023-12-07 20:09 UTC, jeana-redhat commented on modules/verifying-serving-with-openshift-ingress-sharding-configuration.adoc
> +. Verify that your service uses the correct route and the selected ingress shard:
Not sure if this is an example or a literal command. If an example:
```suggestion
. Verify that your service uses the correct route and the selected ingress shard by running a command similar to the following:
```

If it's the literal command, just the normal "by running the following command"

2023-12-07 20:09 UTC, jeana-redhat commented on modules/verifying-serving-with-openshift-ingress-sharding-configuration.adoc
> +.Example command
If this is the literal command, can drop this line

2023-12-08 12:28 UTC, rh-max commented
/label merge-review-needed

2023-12-08 15:07 UTC, jeana-redhat commented on modules/verifying-serving-with-openshift-ingress-sharding-configuration.adoc
> +. Verify that your service uses the correct route and the selected ingress shard:
```suggestion
. Verify that your service uses the correct route and the selected ingress shard by running the following command:
```

2023-12-11 09:11 UTC, rh-max commented
/label merge-review-needed

2023-12-12 16:02 UTC, merged

2023-12-12 16:02 UTC, jab-rh commented
/cherry-pick serverless-docs-1.30

2023-12-12 16:03 UTC, jab-rh commented
/cherry-pick serverless-docs-1.31