OSSM-3159 Remove routerMode: sni-dnat from federation docs
openshift/openshift-docs pull request #69120
Opened 2023-12-07 20:47 UTC by gwynnemonahan

OSSM-3159 Remove "routerMode: sni-dnat" from federation docs

Version(s):
4.14+ 

Issue:
https://issues.redhat.com/browse/OSSM-3159

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-12-07 20:59 UTC, yxun approved these changes

2023-12-11 16:51 UTC, monroe-dylan-m requested changes

2023-12-11 16:51 UTC, monroe-dylan-m commented on modules/ossm-federation-config-smcp.adoc
I believe you should also remove the references to `routerMode` in the `Table 2. Federation gateway parameters` table under the `Understanding federation gateways` section (lines 146-154 and 192-200) since the parameter no longer has any function.

I'm not sure if we need to leave the reference there since technically it may still be parsed by the operator, but I think including it would just clutter the documentation since the SMCP itself no longer uses it.

Other than that LGTM!

2023-12-11 17:01 UTC, gwynnemonahan commented on modules/ossm-federation-config-smcp.adoc
Good catch. Done.

2023-12-11 17:10 UTC, monroe-dylan-m approved these changes

2023-12-11 17:11 UTC, gwynnemonahan commented
/label peer-review-needed

2023-12-11 20:10 UTC, skrthomas reviewed
/lgtm

2023-12-11 20:14 UTC, gwynnemonahan commented
/label merge-review-needed

2023-12-12 14:37 UTC, merged

2023-12-12 14:37 UTC, bburt-rh commented
/cherrypick enterprise-4.14

2023-12-12 14:37 UTC, bburt-rh commented
/cherrypick enterprise-4.15