OSDOCS-9104: docs scrub for kuryr EOL
openshift/openshift-docs pull request #69170
Opened 2023-12-08 20:25 UTC by JoeAldinger

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-12-12 18:16 UTC, lahinson commented
/label peer-review-in-progress
/remove-label peer-review-needed

2023-12-12 20:03 UTC, lahinson reviewed
@JoeAldinger Nice work on going through the docs to scrub references to kuryr! I left a couple of comments for small things to fix. I assume this will require change management because it's related to the removal public documentation [1]. Is that your understanding, too?

[1] https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit#bookmark=id.khm4rxl210qm

2023-12-12 20:03 UTC, lahinson commented
/label peer-review-done
/remove-label peer-review-in-progress

2023-12-13 18:28 UTC, JoeAldinger commented on installing/installing-preparing.adoc
> +You can also complete a user-provisioned infrastructure installation on your existing hardware. If you use xref:../installing/installing_openstack/installing-openstack-user.adoc#installing-openstack-
Awesome catch this is actually a bug in current docs. I'll fix here and then a different PR for the bug.

2023-12-14 16:24 UTC, dulek commented
This looks good from my perspective, though obviously still a lot of content is left.

2023-12-14 16:26 UTC, dulek requested changes
Okay, one doubt there.

2023-12-14 16:26 UTC, dulek commented on welcome/index.adoc
> +- **Install a cluster on {rh-openstack-first}**: You can install a cluster on {rh-openstack} with customizations on a restricted network on installer-provisioned infrastructure. For more information,
Wait, I think these should be listed as distinct options. We have customizations and we have restricted networks, they can be used together, but doesn't need to.

2023-12-18 19:07 UTC, merged

2023-12-18 19:07 UTC, JoeAldinger commented
/cherrypick enterprise-4.15