OSDOCS-8807: Small update to firewalls
openshift/openshift-docs pull request #69442
Opened 2023-12-14 22:03 UTC by jneczypor

OSDOCS-8807: Small update to firewalls

Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-8807?focusedId=23653231&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23653231

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2023-12-15 18:16 UTC, arendej commented on modules/osd-aws-privatelink-firewall-prerequisites.adoc
> +|Allows for CloudFront support.
change to:
"Used by ROSA for its STS implementation with managed OIDC configuration."
or similar.

2023-12-15 19:15 UTC, arendej requested changes
see line 111-114, I left a comment

2023-12-19 07:21 UTC, yuwang-RH commented
/lgtm

2024-01-03 19:46 UTC, EricPonvelle reviewed
/lgtm

2024-01-03 19:46 UTC, merged

2024-01-03 19:46 UTC, EricPonvelle commented
/cherrypick enterprise-4.14

2024-01-03 19:46 UTC, EricPonvelle commented
/cherrypick enterprise-4.15