[WIP] Jenkins memory usage tuning documentation
openshift/openshift-docs pull request #6981
Opened 2018-01-02 23:45 UTC by jim-minter

2018-01-02 23:48 UTC, jim-minter commented
@bparees all this is just preparing the ground, but I'd appreciate feedback as I'm intending to build on it.

2018-01-02 23:51 UTC, jim-minter commented
@bparees preview at http://file.rdu.redhat.com/~jminter/openshift-docs/_preview/openshift-origin/trello143-jenkins-memory-usage-tuning/using_images/other_images/jenkins.html

2018-01-03 01:29 UTC, bparees reviewed
It's a fine start for documenting the knobs.  Regarding discussing how the variables interact (e.g. container_heap_percent, java_max_heap, and jenkins_java_options), I think rather than discussing it within each variable description, it would be good to have an entire section dedicated to discussing how those variables interact/override each other/etc.

2018-01-03 01:29 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +Specifies additional options for the Jenkins JVM which may be overridden.
I think this needs more details.  If the user sets this, they are replacing all the JVM options we auto-configured and the only JVM options Jenkins will get are whatever they set in this variable (meaning they must explicitly set max heap and anything else they care about):
https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/run#L320-L322

Also not clear what "which may be overridden" means.  Overridden by who/what, and how are they overridden?

2018-01-03 01:29 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +Specifies additional options for the Jenkins JVM which may not be overridden.
I think what really needs to be said here is that these JVM options will appear last in the JVM arguments, meaning they will/can override arguments provided earlier (such as via the automatically generated arguments that appear in JENKINS_JAVA_OPTIONS, or the arguments set by the user in JENKINS_JAVA_OPTIONS if they chose to set it explicitly).

Also worth distinguishing that unlike JENKINS_JAVA_OPTIONS, there is no "default/automatic" value for JENKINS_JAVA_OVERRIDES so if they choose to set this value, they are not erasing any arguments the image would have normally supplied.  (They may, however, be overriding values the image is trying to supply).

2018-01-03 01:29 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +setting: `-Xmx512m`.
Need to discuss how this interacts with JENKINS_JAVA_OPTIONS and JENKINS_JAVA_OVERRIDES.  And CONTAINER_HEAP_PERCENT.

2018-01-03 01:29 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +JVM maximum heap size (-Xmx).
Need to discuss how this interacts with JAVA_MAX_HEAP_PARAM, JENKINS_JAVA_OPTIONS, and JENKINS_JAVA_OVERRIDES.

2018-01-03 01:29 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +setting: `-Xms32m`.
same comments as for JAVA_MAX_HEAP_PARAM

2018-01-03 01:29 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +setting: `0.1`, i.e. 10%.
same comments as CONTAINER_HEAP_PERCENT

2018-01-03 01:29 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +override this.
discuss how this interacts with JENKINS_JAVA_OPTIONS and JENKINS_JAVA_OVERRIDES.

2018-01-03 01:29 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +=== {product-title} Jenkins Pipeline DSL Plug-in
we tend to call this the Jenkins OpenShift Client Plug-in when discussing it, i'd prefer to call it that here. (though I see the github repo doesn't reflect that).  But it is what it's indexed as:
https://wiki.jenkins.io/display/JENKINS/OpenShift+Client+Plugin

So we should just fix the readme in the repo.  (maybe @gabemontero can take care of that).

2018-01-09 01:09 UTC, jim-minter commented
@bparees @bmcelvee updated preview at http://file.rdu.redhat.com/~jminter/openshift-docs/_preview/openshift-origin/trello143-jenkins-memory-usage-tuning/using_images/other_images/jenkins.html

proposed new sections:
http://file.rdu.redhat.com/~jminter/openshift-docs/_preview/openshift-origin/trello143-jenkins-memory-usage-tuning/dev_guide/application_memory_sizing.html
http://file.rdu.redhat.com/~jminter/openshift-docs/_preview/openshift-origin/trello143-jenkins-memory-usage-tuning/using_images/other_images/jenkins_slaves.html

significant changes:
http://file.rdu.redhat.com/~jminter/openshift-docs/_preview/openshift-origin/trello143-jenkins-memory-usage-tuning/using_images/other_images/jenkins.html
(env vars documented, slave info moved out, jenkinsfile examples for k8s plugin, revamped memory information, misc fixes)

got to rebase (aaaah!) and write overview for application_memory_sizing.adoc, but this is getting more or less close to where I think I want to get to.  Feedback appreciated.

2018-01-09 19:08 UTC, bparees requested changes

2018-01-11 18:15 UTC, jim-minter commented on dev_guide/application_memory_sizing.adoc
> +node, then ring-fences the requested memory on the chosen node for the use of
Can you think of a better term?

2018-01-11 18:15 UTC, jim-minter commented on dev_guide/application_memory_sizing.adoc
> +additional information is available
Yes, will update.  I'm still not 100% convinced we've got the right GC arguments but am not going to let it hold up this doc.

2018-01-11 18:16 UTC, jim-minter commented on dev_guide/application_memory_sizing.adoc
> +bewildering to ensure that the right settings are being passed to the
Let's try "challenging" :)

2018-01-11 18:17 UTC, bparees commented on dev_guide/application_memory_sizing.adoc
> +node, then ring-fences the requested memory on the chosen node for the use of
exclusively allocates?

2018-01-11 18:17 UTC, bparees commented on dev_guide/application_memory_sizing.adoc
> +bewildering to ensure that the right settings are being passed to the
works for me.

2018-01-11 18:17 UTC, jim-minter commented on using_images/other_images/jenkins.adoc
> +=== Tutorial
Agreed - that's what was there before, though.  Think I'll rename it as information about the sample job.

2018-01-11 18:21 UTC, jim-minter commented on dev_guide/application_memory_sizing.adoc
> +node, then ring-fences the requested memory on the chosen node for the use of
I was trying to avoid "allocates" as it clashes with the idea of memory being actually allocated from the operating system.

2018-01-11 18:26 UTC, bparees commented on dev_guide/application_memory_sizing.adoc
> +node, then ring-fences the requested memory on the chosen node for the use of
"ensures the availability of"

2018-01-11 18:34 UTC, jim-minter commented on using_images/other_images/jenkins.adoc
> +=== Using the Jenkins Kubernetes Plug-in
I agree.  Cop out perhaps, but I'm inclined to write a trello card to handle that.  What I've written here is specifically kubernetes plugin syntax which IMO is sufficiently fiddly that it desperately needs written examples.  https://docs.openshift.org/latest/dev_guide/dev_tutorials/openshift_pipeline.html is a openshift (DSL) client plugin walkthrough which doesn't use the kubernetes plugin.  Then there's a separate pipeline plugin walkthrough at https://github.com/openshift/origin/blob/master/examples/jenkins/README.md.  All three need rationalisation.

2018-01-11 18:34 UTC, jim-minter commented on using_images/other_images/jenkins.adoc
> +=== Using the Jenkins Kubernetes Plug-in
In the interim, I will link https://docs.openshift.org/latest/dev_guide/dev_tutorials/openshift_pipeline.html from this page.

2018-01-11 19:04 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +=== Using the Jenkins Kubernetes Plug-in
ok.

2018-01-11 19:09 UTC, jim-minter commented on using_images/other_images/jenkins.adoc
> +=== Using the Jenkins Kubernetes Plug-in
https://trello.com/c/BOdzgQ3k/1444-rationalise-jenkins-samples-and-tutorials

2018-01-11 19:10 UTC, jim-minter commented
Overview written and all requested updates made, ptal.

2018-01-11 19:57 UTC, bparees commented
lgtm

2018-01-12 18:18 UTC, bmcelvee commented
@jim-minter LGTM. There are just a few minor edits I'd like to make, but I'll open a follow-up PR for those. Would you mind squashing your commits? Thanks! :)

2018-01-12 19:41 UTC, bmcelvee commented
[rev_history]
|xref:../dev_guide/application_memory_sizing.adoc#dev-guide-application-memory-sizing[Application memory sizing]
|Added xref:../dev_guide/application_memory_sizing.adoc#dev-guide-application-memory-sizing[Application memory sizing] chapter.
%
|xref:../dev_guide/builds/build_strategies.adoc#dev-guide-build-strategy-options[Build Strategy Options]
|Updated example in the xref:../dev_guide/builds/build_strategies.adoc#jenkinsfile[Providing the Jenkinsfile] section.
%
|xref:../using_images/other_images/jenkins.adoc#using-images-other-images-jenkins[Jenkins]
|Updated the xref:../using_images/other_images/jenkins.adoc#using-images-other-images-jenkins[Jenkins] chapter.
%
|xref:../using_images/other_images/jenkins_slaves.adoc#using-images-other-images-jenkins-slaves[Jenkins Slaves]
|Added xref:../using_images/other_images/jenkins_slaves.adoc#using-images-other-images-jenkins-slaves[Jenkins Slaves] chapter.
%

2018-01-12 19:41 UTC, merged

2018-02-22 05:21 UTC, vikram-redhat commented
@jim-minter @bmcelvee - I made some changes to the jenkins.adoc file due to some conflicts that were unresolved. I want to make sure that the file contains content correct for 3.9 and 3.7 respectively.

Could you please review them here for 3.9: 
https://raw.githubusercontent.com/openshift/openshift-docs/enterprise-3.9/using_images/other_images/jenkins.adoc

And here for 3.7:
https://raw.githubusercontent.com/openshift/openshift-docs/enterprise-3.7/using_images/other_images/jenkins.adoc

2018-02-22 14:45 UTC, bmcelvee commented
@vikram-redhat Is this a content leak into 3.7? I didn't have conflicts on this PR or the follow-up PR when I was working on them, and I don't see anything in the blame for 3.7 or 3.9. Do you have a commit or PR that I can review for more information?

Thanks!

2018-02-22 21:18 UTC, vikram-redhat commented
Hey @bmcelvee not a content leak, but unresolved conflict resolution. See here: https://github.com/openshift/openshift-docs/pull/7126/files#r170095649.

I have fixed and pushed the changes, so if you could confirm that the changes that I did for both 3.7 and 3.9 branches are ok.