OSDOCS-8805: Adds etcd version query to MicroShift
openshift/openshift-docs pull request #69917
Opened 2024-01-08 19:47 UTC by ShaunaDiaz

Version(s):
4.15+

Issue:
[OSDOCS-8805](https://issues.redhat.com/browse/OSDOCS-8805)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

2024-01-09 07:49 UTC, ggiguash commented on modules/microshift-etcd-version.adoc
> +{microshift-short}-etcd Version: 4.15.0_0.nightly_arm64_2023_11_20_235936_20231129145639_153b6f993
We should not use macros in executable names, please change to hardcoded `microshift-etcd`

2024-01-09 12:41 UTC, ggiguash commented on modules/microshift-etcd-version.adoc
> +microshift-etcd Version: 4.15.0_0.nightly_arm64_2023_11_20_235936_20231129145639_153b6f993
Please, change this version to `4.15.1` as well.

2024-01-09 17:17 UTC, ggiguash requested changes

2024-01-09 17:17 UTC, ggiguash commented on microshift_support/microshift-etcd.adoc
> +The etcd service is delivered as part of the {product-title} RPM. The etcd service is run as a separate process and the lifecycle is managed automatically by {microshift-short}.
```suggestion
The etcd service is delivered as part of the {product-title} RPM. The etcd service is run as a separate process and its lifecycle is managed automatically by {microshift-short}.
```

2024-01-09 17:17 UTC, ggiguash commented on modules/microshift-etcd-version.adoc
> +To enhance troubleshooting, you can get the version information for the etcd database included with your {microshift-short} version.
I'm not sure about this sentence. The bottom line is that we should tell users - here's how you get etcd version.

2024-01-09 17:17 UTC, ggiguash commented on modules/microshift-etcd-version.adoc
> +microshift-etcd Version: 4.15.1_0.nightly_arm64_2023_11_20_235936_20231129145639_153b6f993
```suggestion
microshift-etcd Version: 4.15.1
```

2024-01-09 22:24 UTC, dhensel-rh commented
/label qe-approved

2024-01-10 11:34 UTC, ShaunaDiaz commented
/label peer-review-needed

2024-01-10 14:36 UTC, tmalove commented
/remove-label peer-review-needed
/label peer-review-in-progress

2024-01-10 16:29 UTC, tmalove approved these changes

2024-01-10 16:29 UTC, tmalove commented on modules/microshift-etcd-version.adoc
> +* To display the full database version information, run the following command using the `-o json` option:
```suggestion
* To display the full database version information, run the following command by using the `-o json` option:
```
Suggestion: See ISG: https://www.ibm.com/docs/en/ibm-style?topic=word-usage#u

2024-01-10 16:30 UTC, tmalove commented
/remove-label peer-review-in-progress
/label peer-review-done

2024-01-11 11:53 UTC, merged

2024-01-11 11:54 UTC, ShaunaDiaz commented
/cherrypick enterprise-4.15