OSDOCS-9023:removes kuryr from networking docs
openshift/openshift-docs pull request #69916
Opened 2024-01-08 19:39 UTC by JoeAldinger

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-01-09 15:04 UTC, dulek requested changes

2024-01-09 15:04 UTC, dulek commented on networking/ovn_kubernetes_network_provider/migrate-from-kuryr-sdn.adoc
This file is included in _topic_map.yml, so I think it should be removed from there?

2024-01-10 09:27 UTC, dulek commented
/lgtm

2024-01-10 14:56 UTC, jeana-redhat approved these changes
looks good, double checked repo for `migrate-from-kuryr-sdn` and I don't see any missed xrefs or anything :+1: 

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2024-01-14 12:32 UTC, yakov103 approved these changes
/lgtm

2024-01-15 14:00 UTC, merged

2024-01-15 14:00 UTC, JoeAldinger commented
/cherrypick enterprise-4.15