Osdocs 7969
openshift/openshift-docs pull request #70006
Opened 2024-01-09 21:20 UTC by mletalie

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-01-12 08:21 UTC, svmrh commented
Since this is the least popular deployment option for OSD, can we have QE validate the steps? @xueli181114: Can you please assign someone from the QE team familiar with OSD deployment on the Red Hat Marketplace to try out the steps and review this PR? 

@mletalie: 
- There are some steps that don't apply to the Red Hat Marketplace. E.g. "4.a Click the Review Google Terms and Agreements link." was verify specific to OSD deployment with GCP Marketplace. 
- Since this is the least popular option, can we move this section as the last deployment option on GCP (i.e. after "Creating a cluster on GCP with a Red Hat cloud account")? 
- I haven't tried this deployment option myself, and therefore unclear about the steps. We should wait for QE to comment.

2024-01-12 13:27 UTC, mletalie commented
> Since this is the least popular deployment option for OSD, can we have QE validate the steps? @xueli181114: Can you please assign someone from the QE team familiar with OSD deployment on the Red Hat Marketplace to try out the steps and review this PR?
> 
> @mletalie:
> 
> * There are some steps that don't apply to the Red Hat Marketplace. E.g. "4.a Click the Review Google Terms and Agreements link." was verify specific to OSD deployment with GCP Marketplace.
Yes, good point. I had not gone through the steps yet, and I need to do that. At this point just getting the template going, so to speak. 

> * Since this is the least popular option, can we move this section as the last deployment option on GCP (i.e. after "Creating a cluster on GCP with a Red Hat cloud account")?
Yes, I can do that. 
> * I haven't tried this deployment option myself, and therefore unclear about the steps. We should wait for QE to comment.
Understood. I will certainly try the full deployment and have QE run through it was well. 

In regard to the opening paragraph, is there anything you would suggest to add to it. Maybe something that differentiates from the other options in a positive light...ie, why it would be a good choice for some users, what its stand out features are, etc? Not sure if that makes sense but I am at a loss for additional info. Hope that question makes sense. Thanks! 

Thanks @svmrh, appreciate the info. Please see comments above.

2024-01-12 14:00 UTC, mletalie commented
Reviewers: The majority of this topic was pulled from already existing topic https://docs.openshift.com/dedicated/osd_install_access_delete_cluster/creating-a-gcp-cluster.html#osd-create-cluster-gcp-account_osd-creating-a-cluster-on-gcp as many of the steps to create the cluster are similar. The differences are specific to the selected market place only (in this case, Red Hat Marketplace).

2024-01-15 02:02 UTC, jianli-wei requested changes

2024-01-15 02:02 UTC, jianli-wei commented on modules/osd-create-cluster-rhm-gcp-account.adoc
> +You must ensure that your VPC is configured with a public and a private subnet for each availability zone that you want the cluster installed into. If you opted to use PrivateLink, only private subne
Suggest to remove this statement, which is not true for installing cluster on GCP. 

FYI To install a cluster in an existing GCP VPC, the VPC is expected to have a subnet for control-plane machine and a subnet for compute machines.

2024-01-15 02:02 UTC, jianli-wei commented on modules/osd-create-cluster-rhm-gcp-account.adoc
> +If you are installing a cluster into a Shared VPC, the VPC name and subnets are shared from the host project.
Suggest to replace "the VPC name and subnets are **shared** from the host project" with "the VPC name and subnets are from the host project".

2024-01-16 13:52 UTC, mletalie commented
**Reviewers**: The majority of this topic was pulled from already existing topic https://docs.openshift.com/dedicated/osd_install_access_delete_cluster/creating-a-gcp-cluster.html#osd-create-cluster-gcp-account_osd-creating-a-cluster-on-gcp as many of the steps to create the cluster are similar. The main differences are specific to the selected market place only (in this case, Red Hat Marketplace).

2024-01-16 13:52 UTC, mletalie commented
/label peer-review-needed

2024-01-16 17:53 UTC, ShaunaDiaz commented
/label peer-review-in-progress

2024-01-16 17:53 UTC, ShaunaDiaz commented
/remove-label peer-review-in-progress

2024-01-16 17:56 UTC, ShaunaDiaz commented
/remove-label peer-review-in-progress

2024-01-16 18:30 UTC, ShaunaDiaz reviewed
Looks great! Just a few questions.

2024-01-16 18:30 UTC, ShaunaDiaz commented on modules/osd-create-cluster-rhm-gcp-account.adoc
> +You must have created the Cloud network address translation (NAT) and a Cloud router. See the additional resources for information about Cloud NATs and Google VPCs.
```suggestion
You must have created the Cloud network address translation (NAT) and a Cloud router. See the "Additional resources" section for information about Cloud NATs and Google VPCs.
```
Usually call that thusly.

2024-01-16 18:30 UTC, ShaunaDiaz commented on modules/osd-create-cluster-rhm-gcp-account.adoc
> +You can review the end-of-life dates in the update lifecycle documentation for {product-title}. For more information, see _{product-title} update lifecycle_.
Can a link be dropped in for the lifecycle?

2024-01-16 18:30 UTC, ShaunaDiaz commented on modules/osd-create-cluster-rhm-gcp-account.adoc
> +For information about administrator acknowledgment, see xref:./../upgrading/osd-upgrading-cluster-prepare.adoc#upgrade-49-acknowledgement_osd-updating-cluster-prepare[Administrator acknowledgment whe
Is there a supported version link? 4.11+?

2024-01-16 19:43 UTC, merged

2024-01-16 19:43 UTC, EricPonvelle commented
/cherrypick enterprise-4.14

2024-01-16 19:43 UTC, EricPonvelle commented
/cherrypick enterprise-4.15