OBSDOCS-722 - Logging 5.6.15 Release Notes
openshift/openshift-docs pull request #70383
Opened 2024-01-16 23:34 UTC by libander

Version(s): 4.11. 4.12, 4.13

Issue: OBSDOCS-722

Link to docs preview:

QE review: @anpingli  / @QiaolingTang / @kabirbhartiRH 
- [ ] QE has approved this change.

Additional information:

2024-01-16 23:36 UTC, libander commented
/label peer-review-needed

2024-01-16 23:37 UTC, libander commented
SME review please: @periklis / @jcantrill / @xperimental / @cahartma

2024-01-17 06:07 UTC, periklis requested changes

2024-01-17 06:07 UTC, periklis commented on modules/logging-release-notes-5-6-15.adoc
> +Currently, the log alert is not available on an IPv6-enabled cluster. There is currently no workaround for this issue. (link:https://issues.redhat.com/browse/LOG-4892[LOG-4892])
As mentioned elsewhere, the new text is available on https://issues.redhat.com/browse/LOG-4892

2024-01-17 15:30 UTC, anpingli commented
/lgtm

2024-01-17 15:39 UTC, periklis reviewed
LGTM

2024-01-17 16:30 UTC, libander commented
/cherry-pick enterprise-4.12

2024-01-17 16:56 UTC, libander commented
/cherry-pick enterprise-4.11

2024-01-17 18:23 UTC, skrthomas reviewed
/lgtm

2024-01-17 18:24 UTC, skrthomas commented
I saw your reply on my other bug fix comment, and I totally get ya. Fine by me to keep it consistent w/ other titles.

2024-01-18 19:39 UTC, libander commented
/label merge-review-needed

2024-01-18 21:06 UTC, skrthomas commented
/cherrypick enterprise-4.11

2024-01-18 21:06 UTC, skrthomas commented
/cherrypick enterprise-4.12

2024-01-18 21:06 UTC, merged