Bug 1522751, Removed template as the label name
openshift/openshift-docs pull request #7049
Opened 2018-01-08 22:42 UTC by ahardin-rh

https://bugzilla.redhat.com/show_bug.cgi?id=1522751

2018-01-09 00:01 UTC, gabemontero requested changes

2018-01-09 00:01 UTC, gabemontero commented on dev_guide/application_lifecycle/promoting_applications.adoc
> +$ oc export dc,is,svc,route,secret,sa -l promotion-group=<application_template_name> -o yaml > export.yaml
change `application_template_name` to `application_name` as well to be consistent with the instruction above

2018-01-09 22:18 UTC, ahardin-rh commented
@gabemontero Thanks! This is updated.

2018-01-09 23:00 UTC, gabemontero approved these changes
/lgtm

2018-01-16 16:03 UTC, ahardin-rh commented
QE verified.

2018-01-16 16:03 UTC, merged

2018-01-16 16:03 UTC, ahardin-rh commented
No revision history needed