OSSM-5725: Add content to exclude the creation of CNI pods
openshift/openshift-docs pull request #70539
Opened 2024-01-18 19:48 UTC by rh-tokeefe

Version(s): OCP 4.12_

Issue: https://issues.redhat.com/browse/OSSM-5725

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-01-18 20:58 UTC, pbajjuri20 approved these changes

2024-01-22 13:16 UTC, mkralik3 commented
LGTM

2024-01-23 18:10 UTC, rh-tokeefe commented
/label peer-review-needed

2024-01-23 18:48 UTC, bergerhoffer commented
/label peer-review-needed

2024-01-23 18:49 UTC, bergerhoffer reviewed
LGTM!

2024-01-23 18:50 UTC, bergerhoffer commented
/label peer-review-done
/remove-label peer-review-needed
/remove-label peer-review-in-progress

2024-01-23 19:27 UTC, rh-tokeefe commented
/label merge-review-needed

2024-01-23 20:23 UTC, michaelryanpeter commented
/label merge-review-in-progress

2024-01-23 20:30 UTC, michaelryanpeter commented
/label ok-to-merge
/remove-label merge-review-in-progress

2024-01-24 23:06 UTC, jewertow requested changes

2024-01-24 23:06 UTC, jewertow commented on modules/ossm-vs-istio.adoc
> +By default, Istio Container Network Interface (CNI) pods are created on all {product-title} nodes. To exclude the creation of CNI pods in a specific node, apply the  `maistra.io/exclude-cni=true` lab
```suggestion
By default, Istio CNI pods are created on all {product-title} nodes. To exclude the creation of CNI pods in a specific node, apply the  `maistra.io/exclude-cni=true` label to the node.
```

2024-02-26 20:41 UTC, kalexand-rh commented
The `branch/enterprise-4.16` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.15. And any PR going into `main` must also target the latest version branch (enterprise-4.16).

If the update in your PR does NOT apply to version 4.16 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2024-03-06 16:29 UTC, rh-tokeefe commented
/retest

2024-03-18 18:38 UTC, rh-tokeefe commented
Rebased PR on March 18. PR was previously through merged review. Product code went live today. Please merge.

2024-03-18 18:38 UTC, rh-tokeefe commented
/label merge-review-needed

2024-03-18 19:54 UTC, merged

2024-03-18 19:54 UTC, skrthomas commented
/cherrypick enterprise-4.12

2024-03-18 19:54 UTC, skrthomas commented
/cherrypick enterprise-4.13

2024-03-18 19:54 UTC, skrthomas commented
/cherrypick enterprise-4.15

2024-03-18 19:54 UTC, skrthomas commented
/cherrypick enterprise-4.16