Do not emphasize disabling SELinux in examples
openshift/openshift-docs pull request #71175
Opened 2024-02-05 14:39 UTC by travier

Update examples to mention SELinux last and ensure that we clearly mention that disabling it in production is unsupported and needs node to be re-provisionned.

Version(s):
All versions.

Issue:
N/A

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-02-05 19:01 UTC, jldohmann approved these changes
minor nit, otherwise LGTM. @mike-nguyen can you PTAL for QE ack? thank you

2024-02-05 23:26 UTC, travier commented on modules/nodes-nodes-kernel-arguments.adoc
> +* **enforcing=0**: Configures Security Enhanced Linux (SELinux) to run in permissive mode. In permissive mode, the system acts as if SELinux is enforcing the loaded security policy, including labelin
Thanks! Fixed

2024-02-06 19:12 UTC, mike-nguyen requested changes
One small typo, otherwise looks good to me!

2024-02-06 19:12 UTC, mike-nguyen commented on modules/installation-special-config-kargs.adoc
> +Once SELinux has been disabled on a node, it must be re-provisionned before re-inclusion in a production cluster.
```suggestion
Once SELinux has been disabled on a node, it must be re-provisioned before re-inclusion in a production cluster.
```

2024-02-08 13:22 UTC, travier commented on modules/installation-special-config-kargs.adoc
> +Once SELinux has been disabled on a node, it must be re-provisionned before re-inclusion in a production cluster.
Thanks, fixed.

2024-02-08 16:29 UTC, merged

2024-02-08 16:30 UTC, jldohmann commented
/cherrypick enterprise-4.15

2024-02-08 16:30 UTC, jldohmann commented
/cherrypick enterprise-4.14

2024-02-08 16:30 UTC, jldohmann commented
/cherrypick enterprise-4.13

2024-02-08 16:30 UTC, jldohmann commented
/cherrypick enterprise-4.12

2024-02-08 16:30 UTC, jldohmann commented
/cherrypick enterprise-4.11