Logging 5.8.3 Release Notes
openshift/openshift-docs pull request #71232
Opened 2024-02-06 01:08 UTC by libander

Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OBSDOCS-778

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-02-07 08:41 UTC, periklis requested changes

2024-02-07 08:41 UTC, periklis commented on modules/logging-release-notes-5-8-3.adoc
> +(None.)
You are looking only on the RHEL-8 errata here. This this the reason there are no fixes. In fact we need always to point to both errata in 5.8 (RHEL-8 and RHEL-9). Latter is here and has issues to be attached: https://errata.engineering.redhat.com/advisory/126476

2024-02-08 14:21 UTC, jcantrill commented on modules/logging-release-notes-5-8-3.adoc
> +* Before this update, outputs configured without a valid URL caused the collector pods to crash. With this update, outputs are subject to URL validation, resolving the issue. (link:https://issues.red
This should mention "loki" since it is those specific outputs that were fixed

2024-02-08 14:21 UTC, jcantrill commented on modules/logging-release-notes-5-8-3.adoc
> +* Before this update the Loki Operator would generate collector configuration fields for outputs that did not specify a secret to utilize the service account bearer token.  With this update, an outpu
the "cluster logging operator"

2024-02-08 14:29 UTC, periklis reviewed
LGTM got log storage bugs.

2024-02-08 14:53 UTC, anpingli commented
can you add release note  for https://issues.redhat.com/browse/LOG-4893

2024-02-08 21:10 UTC, libander commented
/label peer-review-needed

2024-02-09 00:53 UTC, anpingli commented
LGTM

2024-02-09 08:35 UTC, periklis commented
LGTM

2024-02-09 13:44 UTC, tmalove commented
/remove-label peer-review-needed
/label peer-review-in-progress

2024-02-09 14:26 UTC, tmalove commented
@libander will you attach a preview link? Thanks!

2024-02-09 15:45 UTC, tmalove approved these changes

2024-02-09 15:45 UTC, tmalove commented
/remove-label peer-review-in-progress
/label peer-review-done

2024-02-09 23:37 UTC, libander commented
/label merge-review-needed

2024-02-12 11:26 UTC, ShaunaDiaz commented
@libander Did you want to make the peer review corrections? Those are pretty standard style comments.

2024-02-12 11:26 UTC, ShaunaDiaz commented
/label merge-review-in-progress

2024-02-12 11:27 UTC, ShaunaDiaz commented
/remove-label merge-review-needed

2024-02-16 00:51 UTC, libander commented
/label merge-review-needed

2024-02-16 21:46 UTC, ShaunaDiaz commented
/remove-label merge-review-needed

2024-02-16 21:46 UTC, ShaunaDiaz commented
/remove-label merge-review-in-progress

2024-02-16 21:46 UTC, merged

2024-02-16 21:47 UTC, ShaunaDiaz commented
/cherrypick enterprise-4.12

2024-02-16 21:47 UTC, ShaunaDiaz commented
/cherrypick enterprise-4.13

2024-02-16 21:47 UTC, ShaunaDiaz commented
/cherrypick enterprise-4.14

2024-02-16 21:47 UTC, ShaunaDiaz commented
/cherrypick enterprise-4.15