OSDOCS#9456: Adds ODC release notes
openshift/openshift-docs pull request #71590
Opened 2024-02-13 18:38 UTC by opayne1

Adds ODC release notes

Version(s):
4.15

Issue:
https://issues.redhat.com/browse/OSDOCS-9456

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-02-14 14:41 UTC, jerolimov commented on release_notes/ocp-4-15-release-notes.adoc
> +[id="ocp-4-14-developer-perspective"]
Super small thing:

```suggestion
[id="ocp-4-15-developer-perspective"]
```

2024-02-14 16:22 UTC, jerolimov commented
From an eng. perspective this lgtm :+1:

2024-02-14 16:23 UTC, jerolimov requested changes
From an eng. perspective this lgtm 👍

There is just a tiny internal id wrong, see above.

2024-02-15 12:59 UTC, opayne1 commented
@sanketpathak could you help with a QE review of this PR?

2024-02-15 13:32 UTC, mramendi commented
/label peer-review-in-progress
/remove-label peer-review-needed

2024-02-15 13:50 UTC, mramendi reviewed
Please also note that the preview link does not seem to work for me. https://71590--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-web-console works.

As I am on peer review induction, @JoeAldinger will finish the review,

2024-02-15 13:50 UTC, mramendi commented on release_notes/ocp-4-15-release-notes.adoc
> +With this update, a quick start is now available for you to learn more about how to install and use the developer hub.
I would make it "about installing and using". I think "about how to" is somewhat unwieldy.

2024-02-15 13:50 UTC, mramendi commented on release_notes/ocp-4-15-release-notes.adoc
> +With this update, builds for {product-title} 1.0 is supported in the web console. Builds is an extensible build framework based on the link:https://shipwright.io/[Shipwright project], which you can u
I think that the "which" can be read a sreferring to the Shipwright project. I would split the sentence. Also, I would use {product-title}.

2024-02-15 13:50 UTC, mramendi commented on release_notes/ocp-4-15-release-notes.adoc
> +With this update, builds for {product-title} 1.0 is supported in the web console. Builds is an extensible build framework based on the link:https://shipwright.io/[Shipwright project], which you can u
```suggestion
With this update, builds for {product-title} 1.0 is supported in the web console. Builds is an extensible build framework based on the link:https://shipwright.io/[Shipwright project]. You can use builds for {product-title} to build container images on an {product-title} cluster.
```

2024-02-15 13:50 UTC, mramendi commented on release_notes/ocp-4-15-release-notes.adoc
> +For more information, see link:https://docs.openshift.com/builds/1.0/about/ob-release-notes.html[builds for {product-title}].
For consistency with the Pipelines part, I would point to the overview and not to release notes: https://docs.openshift.com/builds/1.0/about/overview-openshift-builds.html

2024-02-15 13:50 UTC, mramendi commented on release_notes/ocp-4-15-release-notes.adoc
> +For more information on the {rh-dev-hub}, see link:https://access.redhat.com/documentation/en-us/red_hat_developer_hub/1.0[Product Documentation for {rh-dev-hub}].
I would use "about" not "on"

2024-02-15 13:50 UTC, mramendi commented on release_notes/ocp-4-15-release-notes.adoc
> +For more information, see link:https://docs.openshift.com/builds/1.0/about/ob-release-notes.html[builds for {product-title}].
```suggestion
For more information about builds for {product-title}, see link:https://docs.openshift.com/builds/1.0/about/overview-openshift-builds.html[builds for {product-title}].
```

2024-02-15 13:50 UTC, mramendi commented on release_notes/ocp-4-15-release-notes.adoc
> +For more information, see link:https://docs.openshift.com/pipelines/latest/about/understanding-openshift-pipelines.html[{pipelines-title}].
```suggestion
For more information about {pipelines-title}, see link:https://docs.openshift.com/pipelines/latest/about/understanding-openshift-pipelines.html[{pipelines-title}].
```

2024-02-15 19:37 UTC, sanketpathak commented
LGTM 
QE approved!

2024-02-15 20:01 UTC, JoeAldinger commented on release_notes/ocp-4-15-release-notes.adoc
> +[id="ocp-4-15-builds-suppot"]
```suggestion
[id="ocp-4-15-builds-support"]
```

2024-02-15 20:01 UTC, JoeAldinger reviewed
A few suggestions, good PR.

2024-02-19 13:02 UTC, JoeAldinger commented
/lgtm

2024-02-19 13:03 UTC, merged