OSDOCS-9571 machine pools in hcp clusters
openshift/openshift-docs pull request #71625
Opened 2024-02-14 15:51 UTC by xJustin

Added a module to describe Machine pool differences in HCP clusters. 

Version(s):

4.14+ 
Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-02-20 13:19 UTC, arendej requested changes
`Multi-AZ HCP clusters` is not an appropriate term for the HCP architecture. With HCP, all cluster control planes are multi-AZ, so there is no concept of multi/single-AZ.  The difference to focus on is that while the control plane is always multi-AZ, the worker machinepools are each single-AZ and so now customers would need to understand that and how it differs from the ROSA Classic machinepools (where machinepools are always trying to be multi-AZ unless in a single-AZ cluster.

2024-02-20 14:51 UTC, bchandra-ocp commented on modules/machine-pools-hcp.adoc
> +In {product-title} (ROSA) HCP clusters, including Multi-AZ HCP clusters, machine pools only exist inside of a single Availability Zone. In Multi-AZ HCP clusters, ROSA creates a group of three machine
Suggest to paraphrase as "Additionally, HCP machine pools can be upgraded independently from each other as well as from cluster's control plane.

2024-02-21 02:37 UTC, bchandra-ocp commented
Justin, I took a stab at this. I'm thinking in the 'About Machine Pools' all we need is an overview of machine pools. What you can create etc must be delegated to other topics such as 'Managing Compute Nodes'. PTAL : https://docs.google.com/document/d/1LcxzeWFc5SYqcj2QfrswcyUVrg8cLtpv0Q2vs4Ye-A0/edit?usp=sharing

2024-03-01 21:05 UTC, bchandra-ocp commented on modules/machine-pools-hcp.adoc
> +In ROSA with HCP clusters, the hosted control plane always spans all three of the Availability Zones (AZ) in the installed cloud region. However, unlike ROSA Classic clusters, machine pools in ROSA w
I'd suggest cutting down the words on this. 

In ROSA with HCP clusters, the hosted control plane always spans all three of the Availability Zones (AZ) in the installed cloud region. Each machine pool in a HCP cluster is deployed in a single subnet within a single AZ. 

The other statements mentioned are not correct. By writing more, we increase the chances of errors.

2024-03-01 21:11 UTC, bchandra-ocp commented on modules/machine-pools-hcp.adoc
> +Machine pools in ROSA with HCP clusters upgrade independently of each other and the control plane. However, the version of a given machine pool in a ROSA with HCP cluster must not be earlier than two
Suggest the following (Versions is ambiguous). 

**Each Machine Pool in ROSA with HCP clusters can be upgraded independently. The versions of the Machine Pools must remain within two minor (Y-stream) versions of that of the Control Plane**

2024-03-01 21:12 UTC, bchandra-ocp requested changes
Can we please update as per review comments. Thanks for your work on this!

2024-03-20 15:02 UTC, xJustin commented
@bchandra-ocp I removed the fluff and incorporated your suggestions. If you could please take a look?

2024-04-03 19:20 UTC, bchandra-ocp commented on modules/machine-pools-hcp.adoc
> +In {hcp-title} clusters, the hosted control plane spans all three of the Availability Zones (AZ) in the installed cloud region. Each machine pool in a {hcp-title} cluster deploys in a single subnet w
I'd also suggest to include: "A single AZ can host only one machine pool." 

> Each machine pool in a {hcp-title} cluster deploys in a single subnet within a single AZ. And, a single AZ can host only one machine pool.

2024-04-03 19:22 UTC, bchandra-ocp requested changes
Suggest including a statement that is not intuitive for customers.

2024-06-05 12:58 UTC, closed without merging