CNV#30164: 4.15 CNV Networking release notes
openshift/openshift-docs pull request #71842
Opened 2024-02-19 18:04 UTC by sjhala-ccs

Version(s): 4.15

Issue: CNV-30164 CNV-30167 CNV-13680 CNV-30170

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information: This PR covers multiple CNV Networking release notes

2024-02-19 18:32 UTC, maiqueb requested changes
I think plural is more correct here.

I apologize for not having caught it in the previous doc ...

2024-02-19 18:32 UTC, maiqueb commented on virt/release_notes/virt-4-15-release-notes.adoc
> +* An OVN-Kubernetes secondary network is compatible with the xref:../../networking/multiple_networks/configuring-additional-network.adoc#compatibility-with-multi-network-policy_configuring-additional
```suggestion
* An OVN-Kubernetes secondary network is compatible with the xref:../../networking/multiple_networks/configuring-additional-network.adoc#compatibility-with-multi-network-policy_configuring-additional-network[multi-network policy API] which provides the `MultiNetworkPolicy` custom resource definition (CRD) to control traffic flow to and from VMs. You can use the `ipBlock` attribute to define network policy ingress and egress rules for specific CIDR blocks.
```

2024-02-20 14:44 UTC, AlonaKaplan commented
lgtm the hotplug part.

2024-02-20 14:54 UTC, maiqueb approved these changes

2024-02-20 17:10 UTC, skopacz1 commented
/label peer-review-in-progress

2024-02-20 17:17 UTC, skopacz1 reviewed
Just a few suggestions but otherwise LGTM!

2024-02-20 17:17 UTC, skopacz1 commented on virt/release_notes/virt-4-15-release-notes.adoc
> +* You can xref:../../virt/vm_networking/virt-hot-plugging-network-interfaces.adoc#virt-hot-plugging-network-interfaces[hot plug a secondary network interface] to a running VM. Hot plugging and hot un
Suggestion to spell out Virtual Machine (especially on the first mention in this section so far):
```suggestion
* You can xref:../../virt/vm_networking/virt-hot-plugging-network-interfaces.adoc#virt-hot-plugging-network-interfaces[hot plug a secondary network interface] to a running virtual machine (VM). Hot plugging and hot unplugging is supported only for VMs created with {VirtProductName} 4.14 or later. Hot unplugging is not supported for Single Root I/O Virtualization (SR-IOV) interfaces.
```

2024-02-20 17:17 UTC, skopacz1 commented on virt/release_notes/virt-4-15-release-notes.adoc
> +* An OVN-Kubernetes secondary network is compatible with the xref:../../networking/multiple_networks/configuring-additional-network.adoc#compatibility-with-multi-network-policy_configuring-additional
Suggestion - I think a comma here might make the long sentence easier to read, up to you:
```suggestion
* An OVN-Kubernetes secondary network is compatible with the xref:../../networking/multiple_networks/configuring-additional-network.adoc#compatibility-with-multi-network-policy_configuring-additional-network[multi-network policy API], which provides the `MultiNetworkPolicy` custom resource definition (CRD) to control traffic flow to and from VMs. You can use the `ipBlock` attribute to define network policy ingress and egress rules for specific CIDR blocks.
```

2024-02-20 17:17 UTC, skopacz1 commented
/remove-label peer-review-needed
/remove-label peer-review-in-progress

/label peer-review-done

2024-02-21 07:37 UTC, segevyos commented
/lgtm (CNV network QE)

2024-02-21 23:55 UTC, sjhala-ccs commented
/retest

2024-02-22 01:30 UTC, sjhala-ccs commented
@Anatw Can you please review the two OVN-K release notes?

2024-02-22 08:49 UTC, Anatw commented
/lgtm Thank you Shikha

2024-02-22 12:03 UTC, merged