OSDOCS-9957: Created a disclaimer in the Terraform docs about modifying resources
openshift/openshift-docs pull request #73107
Opened 2024-03-13 18:19 UTC by EricPonvelle

Version(s):
`enterprise-4.15+`

Issue:
**[OSDOCS-9957](https://issues.redhat.com/browse/OSDOCS-9957)**

Link to docs preview:
- [Preparing Terraform to install ROSA clusters](https://file.rdu.redhat.com/eponvell/OSDOCS-9957_Terraform-Disclaimer/rosa_planning/rosa-understanding-terraform.html#rosa-sts-terraform-prerequisites_rosa-understanding-terraform)
    ![image](https://github.com/openshift/openshift-docs/assets/16167833/2839eef3-5db7-4d4e-9015-0c1eb0e42e64)

- [Creating a default ROSA Classic cluster using Terraform](https://file.rdu.redhat.com/eponvell/OSDOCS-9957_Terraform-Disclaimer/rosa_install_access_delete_clusters/terraform/rosa-sts-creating-a-cluster-quickly-terraform.html#rosa-sts-creating-a-cluster-quickly-terraform-procedure)
    ![image](https://github.com/openshift/openshift-docs/assets/16167833/ab06b323-04b9-44a0-bbc5-e65706fdc41d)

QE review:
- [ ] QE has approved this change.

Additional information:
This PR creates a disclaimer for Terraform content that warns users that they must modify their resources if they break the Terraform process.

2024-03-19 06:30 UTC, jameszwang commented
/lgtm

2024-03-20 21:45 UTC, jneczypor reviewed
My stab at re-writing the note. Take it or leave it.

2024-03-20 21:45 UTC, jneczypor commented on snippets/terraform-modification-disclaimer.adoc
> +Because Terraform uses declarative language to change the current state of a resource, you should use caution when modifying any resources created with Terraform, such as performing upgrades.
Use caution when using resources outside of Terraform, such as the AWS console or Red Hat console, to modify resources created by Terraform. Using tools outside Terraform to manage resources that are already managed by Terraform introduces configuration drift from your declared Terraform configuration.

2024-03-20 21:45 UTC, jneczypor commented on snippets/terraform-modification-disclaimer.adoc
> +If you upgrade your Terraform-created cluster by using the {hybrid-console-url}, you need to reconcile your Terraform states before applying any forthcoming configuration changes. You need to modify
```suggestion
For example, if you upgrade your Terraform-created cluster by using the {hybrid-console-url}, you need to reconcile your Terraform state before applying any forthcoming configuration changes. You need to modify your Terraform plan file with the changed values. For more information, see link:https://developer.hashicorp.com/terraform/tutorials/state/state-cli[Manage resources in Terraform state] in the HashiCorp Developer documentation.
```

2024-03-22 15:57 UTC, mletalie commented on snippets/terraform-modification-disclaimer.adoc
> +Use caution when modifying Terraform created resources. For more information, see link:https://docs.openshift.com/rosa/rosa_planning/rosa-understanding-terraform.html[Considerations when using Terraf
As a reminder/heads up, make sure to direct the link to the specific topic once you are ready to publish (ie "Considerations when using Terraform").

2024-03-22 15:57 UTC, mletalie commented on modules/rosa-sts-terraform-considerations.adoc
> +For example, if you upgrade your Terraform-created cluster by using the {hybrid-console-url}, you need to reconcile your Terraform state before applying any forthcoming configuration changes. You nee
```suggestion
For example, if you upgrade your Terraform-created cluster by using the {hybrid-console-url}, you need to reconcile your Terraform state before applying any forthcoming configuration changes and modify your Terraform plan file with the changed values. For more information, see link:https://developer.hashicorp.com/terraform/tutorials/state/state-cli[Manage resources in Terraform state] in the HashiCorp Developer documentation.
```

2024-03-22 15:57 UTC, mletalie commented on modules/rosa-sts-terraform-considerations.adoc
> +For example, if you upgrade your Terraform-created cluster by using the {hybrid-console-url}, you need to reconcile your Terraform state before applying any forthcoming configuration changes. You nee
May flow better to just combine those sentences if they are dependent of each other.  (or not, your call). :)

2024-03-22 16:13 UTC, mletalie reviewed
/lgtm

2024-03-23 01:04 UTC, arendej requested changes

2024-03-23 01:04 UTC, arendej commented on modules/rosa-sts-terraform-considerations.adoc
> +In general, using Terraform to manage cloud resources should be done with the expectation that any changes should be done using the Terraform methodology. Use caution when using resources outside of
We need to use the word 'resources' to describe cloud resources, so let's not use it to describe the consoles, which could be called 'tools'.

2024-03-23 01:04 UTC, arendej commented on modules/rosa-sts-terraform-considerations.adoc
> +For example, if you upgrade your Terraform-created cluster by using the {hybrid-console-url}, you need to reconcile your Terraform state before applying any forthcoming configuration changes, and mod
please omit
"and modify your Terraform plan file with the changed values."
It's up to the user to decide how they reconcile state.

2024-03-26 19:13 UTC, GroceryBoyJr commented
/label peer-review-in-progress
/remove-label peer-review-needed
/assign GroceryBoyJr

2024-03-26 19:19 UTC, GroceryBoyJr reviewed
LGTM

2024-03-26 19:20 UTC, GroceryBoyJr commented
/label peer-review-done
/remove-label peer-review-in-progress
/unassign GroceryBoyJr

2024-03-26 20:02 UTC, merged

2024-03-26 20:02 UTC, EricPonvelle commented
/cherrypick enterprise-4.15

2024-03-26 20:05 UTC, EricPonvelle commented
/cherrypick enterprise-4.16