[ROX#23218] Update RNs for 4.2.5
openshift/openshift-docs pull request #73286
Opened 2024-03-18 12:56 UTC by kcarmichael08

Version(s):
-rhacs-docs-4.2

[Issue](https://issues.redhat.com/browse/ROX-23218)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-03-18 15:34 UTC, vladbologa requested changes

2024-03-18 15:34 UTC, vladbologa commented on release_notes/42-release-notes.adoc
> +* Fixed an issue where an upgrade to version 4.3 from an earlier version caused the Central component to enter a crash loop.
Should be 4.2 here

2024-03-18 16:11 UTC, vladbologa approved these changes

2024-03-19 20:51 UTC, skrthomas reviewed
/lgtm

2024-03-20 12:31 UTC, merged