[WIP] OSDOCS#9762: Applications for GitOps on MicroShift
openshift/openshift-docs pull request #73761
Opened 2024-03-26 19:26 UTC by kelbrown20

**This is a draft and everything is not correct yet**

**Issue:**
4.15+

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-04-04 10:11 UTC, agullon commented on modules/microshift-gitops-adding-apps.adoc
> +* You installed the GitOps ArgoCD package
```suggestion
* `microshift-gitops` packages is installed and Argo CD pods are running. 
```
I'd add here a link to how to do this prerequisite step that is described here: https://github.com/openshift/openshift-docs/pull/72974/files?short_path=1b72eb8#diff-1b72eb821edc3eac7a2919a4cdabb885dbcb0b179acaccbe8c7966833aefab77

2024-04-04 10:15 UTC, agullon commented on modules/microshift-gitops-adding-apps.adoc
> +
```suggestion
```
Remove this lines because in the step 1 consist only on creating the yaml file, step 2 will run the `oc` command

2024-04-04 10:17 UTC, agullon commented on modules/microshift-gitops-adding-apps.adoc
> +. To apply the changes and deploy the applications, run the following command:
```suggestion
. To deploy the applications defined in the yaml file, run the following command:
```

2024-04-04 10:19 UTC, agullon commented on modules/microshift-gitops-adding-apps.adoc
> +----
```suggestion
----
You may need to wait a few minutes for the app to be in `Healthy` status.
```

2024-04-04 10:20 UTC, agullon commented on modules/microshift-gitops-adding-apps.adoc
> +openshift-gitops   spring-petclinic   Synced        Healthy
```suggestion
openshift-gitops   cert-manager       Synced        Healthy
openshift-gitops   spring-petclinic   Synced        Healthy
```

2024-04-04 17:32 UTC, kelbrown20 commented
@agullon Thank you for the feedback! How do these updates look?

2024-04-05 09:30 UTC, agullon commented
> @agullon Thank you for the feedback! How do these updates look?

it looks good!

2024-04-05 09:30 UTC, agullon approved these changes
/lgtm

2024-04-08 22:04 UTC, adellape commented on modules/microshift-gitops-adding-apps.adoc
> +$ oc get Applications -A
Usually we keep the object/kind type in CLI commands lowercase:
```suggestion
$ oc get applications -A
```
FWIW, I see a similar example of `oc get applications` lowercase here:

https://access.redhat.com/documentation/en-us/red_hat_openshift_gitops/1.12/html-single/argo_cd_applications/index#creating-an-application-by-using-the-oc-tool_deploying-a-spring-boot-application-with-argo-cd

2024-04-08 22:04 UTC, adellape commented on modules/microshift-gitops-adding-apps.adoc
> +It may take a few minutes for the application to show the `Healthy` status.
Per ISG:
```suggestion
It might take a few minutes for the application to show the `Healthy` status.
```

2024-04-09 16:11 UTC, kelbrown20 commented on modules/microshift-gitops-adding-apps.adoc
> +.. The following example creates an application for spring-petclinic:
Ooo, I think that might be better. I was trying to figure out a way to do this while having multiple yaml examples.

2024-04-09 16:13 UTC, kelbrown20 commented
@anandrkskd Hey Anand! Can you take a look at these updates when you get the chance? Thank you!

2024-04-10 14:14 UTC, anandf commented on modules/microshift-gitops-adding-apps.adoc
> +* You installed the `microshift-gitops` packages and the Argo CD pods are running.
pods are running in `openshift-gitops` namespace

2024-04-10 14:15 UTC, anandf commented on modules/microshift-gitops-adding-apps.adoc
> +apiVersion: argoproj.io/v1alpha1
This one too requires the `default` AppProject

2024-04-10 14:17 UTC, anandf requested changes
Few minor comments.

2024-04-10 15:38 UTC, kelbrown20 commented
/retest

2024-04-10 16:54 UTC, kelbrown20 commented
/retest

2024-04-11 13:51 UTC, kelbrown20 commented
/retest

2024-04-12 03:05 UTC, anandf approved these changes
LGTM

2024-04-15 12:11 UTC, merged

2024-04-15 12:11 UTC, kelbrown20 commented
/cherrypick enterprise-4.16

2024-04-15 12:12 UTC, kelbrown20 commented
/cherrypick enterprise-4.15