OCPBUGS-18770: GCP passthrough roles req
openshift/openshift-docs pull request #73841
Opened 2024-03-27 19:45 UTC by jeana-redhat

Version(s):
4.12-4.14

Issue:
[OCPBUGS-18770](https://issues.redhat.com/browse/OCPBUGS-18770)

Link to docs preview:
- [Required GCP roles](https://73841--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-account.html#installation-gcp-permissions_installing-gcp-account) (IPI/general)
- [Required GCP permissions for installer-provisioned infrastructure](https://73841--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-account.html#minimum-required-permissions-ipi-gcp_installing-gcp-account) (IPI)
- [Required GCP roles](https://73841--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra#installation-gcp-permissions_installing-gcp-user-infra) (UPI)
- [Required GCP permissions for user-provisioned infrastructure](https://73841--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra#minimum-required-permissions-upi-gcp_installing-gcp-user-infra) (UPI)

QE review:
- [x] QE has approved this change.

Additional information:
This applies to 4.12-4.14. Should cherrypick cleanly from 4.14 back down.

2024-03-28 18:40 UTC, jstuever commented
/cc

2024-04-01 19:23 UTC, jstuever reviewed
/lgtm

2024-04-01 20:44 UTC, jeana-redhat commented
Thanks, Jeremiah!

@jianping-shu PTAL

2024-04-03 02:12 UTC, jianping-shu commented
Add @jianli-wei to review too

2024-04-03 02:45 UTC, jianli-wei requested changes

2024-04-03 02:45 UTC, jianli-wei commented on modules/minimum-required-permissions-ipi-gcp.adoc
> +For more information, see "Required roles for using passthrough credentials mode."
> see "Required roles for using passthrough credentials mode."

**The suggestion:** `see "Required GCP roles" section.`

2024-04-03 18:16 UTC, jldohmann approved these changes
Nice work Jeana! 😎 LGTM

2024-04-03 21:23 UTC, merged

2024-04-03 21:23 UTC, jeana-redhat commented
/cherrypick enterprise-4.13

2024-04-03 21:23 UTC, jeana-redhat commented
/cherrypick enterprise-4.12