OSDOCS#10129: Remove TP notice for etcd tuning profiles
openshift/openshift-docs pull request #74620
Opened 2024-04-12 20:46 UTC by tmalove

Version(s):
4.16+

Issue:
[OSDOCS-10129](https://issues.redhat.com/browse/OSDOCS-10129)

Link to docs preview:
TBD

QE review:
- [ ] QE has approved this change.

2024-04-16 14:24 UTC, dusk125 requested changes
We should remove the Tech Preview Prereq as well.

2024-04-16 17:56 UTC, tmalove commented
> We should remove the Tech Preview Prereq as well.

Hi @dusk125 The TP prereq is removed from the latest preview...thanks!

2024-04-16 18:08 UTC, dusk125 commented
Thanks! lgtm!

2024-04-16 20:32 UTC, tmalove commented
Hi @geliu2016 Will you review these changes for this 4.16 task for removing the Tech Preview reference for etcd tuning profiles? Thanks!

2024-04-17 05:41 UTC, geliu2016 commented
/lgtm

2024-04-17 14:17 UTC, tmalove commented
/label peer-review-needed

2024-04-17 14:44 UTC, agantony commented
/label peer-review-in-progress

2024-04-17 14:46 UTC, agantony commented
LGTM!
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2024-04-17 14:47 UTC, agantony commented
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2024-04-17 14:49 UTC, tmalove commented
/label merge-review-needed

2024-04-17 16:08 UTC, sjhala-ccs commented
@tmalove Can you please squash your commits to 1?

2024-04-17 17:03 UTC, merged

2024-04-17 17:03 UTC, sjhala-ccs commented
/cherrypick enterprise-4.16

2024-05-21 16:47 UTC, sferich888 commented
/label px-approved