Osdocs 10179
openshift/openshift-docs pull request #74750
Opened 2024-04-16 21:22 UTC by mletalie

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-04-17 11:55 UTC, mletalie commented
Per https://redhat-internal.slack.com/archives/C0308P3FC7R/p1713314177151809?thread_ts=1713303198.310109&cid=C0308P3FC7R, can you please QE review, @yingzhanredhat? Thanks.

2024-04-17 19:08 UTC, bchandra-ocp commented
1. Delete upgrade of machine pool is missing. $ rosa delete upgrade --cluster {} --machinepool {}

2024-04-17 20:43 UTC, bchandra-ocp requested changes
Similar to deleting scheduled upgrades of cluster, we need to document deletion of machine pool upgrades.

2024-04-18 08:36 UTC, yingzhanredhat commented on modules/rosa-upgrade-cluster-cli.adoc
> +$ rosa upgrade machinepool --cluster=mycluster --machinepool=mymachinepool
It is not correct. It should like this
`rosa upgrade machinepool --cluster=mycluster --machinepool=mymachinepool`

2024-04-18 08:39 UTC, yingzhanredhat commented on modules/rosa-upgrade-cluster-cli.adoc
> +$ rosa delete upgrade --cluster=<cluster_name> --machinepool=<machinepool_name>| <cluster_id> <machinepool_id> [arguments]
No "--machinepool" flag

2024-04-19 09:09 UTC, mletalie commented
@yingzhanredhat, 

    I have updated docs based on your comment. Please let me know if that note specifying that the upgraded command is for hcp clusters only, or if it should be just applied to upgrading machine pools. Once that is resolved, I believe the docs will be ready to be published. Thanks.

2024-04-22 11:31 UTC, mletalie commented
> @mletalie Sure.
> 
> 1. upgrade machinepool is only supported for HCP cluster
> 2. upgrade cluster is supported for classic and HCP.
>    For upgrade cluster,
> 
> * --node-drain-grace-period is only supported for classic cluster
> * --control-plane is only supported for HCP cluster

Hello @yingzhanredhat, thanks for this info. I see that `--control plane ` flag is not listed at all currently in the docs, and is outside the scope of this ticket. That being said, I can add it to the docs as part of this doc, but would need to know what the flag does? I can see about checking myself but given this ticket is getting outside of scope, if you could let me know it would save some time. Thanks!

2024-04-23 02:28 UTC, yingzhanredhat commented
/lgtm

2024-04-23 13:23 UTC, mletalie commented
/label peer-review-needed

2024-04-23 13:42 UTC, mletalie commented
/remove-label peer-review-needed

2024-04-23 13:44 UTC, eohartman commented
/label peer-review-in-progress

2024-04-23 19:01 UTC, eohartman commented
Looks great!

2024-04-23 19:01 UTC, eohartman commented
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2024-04-23 19:41 UTC, eohartman commented
/lgtm

2024-04-23 20:15 UTC, mletalie commented
/label merge-review-needed

2024-04-24 15:09 UTC, stevsmit commented
lgtm

2024-04-24 15:10 UTC, merged