OSDOCS 10255:Updated Release notes for 1.13.1
openshift/openshift-docs pull request #74930
Opened 2024-04-22 05:51 UTC by subhtk

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-04-23 07:35 UTC, lunarwhite commented on security/cert_manager_operator/cert-manager-operator-release-notes.adoc
> +Version `1.13.1` of the {cert-manager-operator} is based on the upstream cert-manager version `v1.13.5`. For more information, see the link:https://cert-manager.io/docs/release-notes/release-notes-1.
```suggestion
Version `1.13.1` of the {cert-manager-operator} is based on the upstream cert-manager version `v1.13.5`. For more information, see the link:https://cert-manager.io/docs/release-notes/release-notes-1.13/#v1135[cert-manager project release notes for v1.13.5].
```

2024-04-23 07:40 UTC, lunarwhite commented
Is it intended to remove the 1.13.0 release notes? (Not quite familiar with how this repo's branching works)

2024-04-23 08:09 UTC, swghosh requested changes

2024-04-23 11:29 UTC, subhtk commented on security/cert_manager_operator/cert-manager-operator-release-notes.adoc
> +Version `1.13.1` of the {cert-manager-operator} is based on the upstream cert-manager version `v1.13.5`. For more information, see the link:https://cert-manager.io/docs/release-notes/release-notes-1.
Ack.

2024-04-23 11:30 UTC, subhtk commented on security/cert_manager_operator/cert-manager-operator-release-notes.adoc
> +== {cert-manager-operator} 1.13.1
Ack. I will update it accordingly.

2024-04-23 11:30 UTC, subhtk commented on security/cert_manager_operator/cert-manager-operator-release-notes.adoc
> +
Done.

2024-04-23 11:30 UTC, subhtk commented on security/cert_manager_operator/cert-manager-operator-release-notes.adoc
> +
Ack.

2024-04-23 11:30 UTC, subhtk commented on security/cert_manager_operator/cert-manager-operator-release-notes.adoc
> +
Also, can you provide the errata link for the 1.13.1 version?

2024-05-14 16:39 UTC, swghosh commented
/lgtm

2024-05-15 07:02 UTC, subhtk commented
/label peer-review-needed

2024-05-15 07:04 UTC, snarayan-redhat commented
@subhtk This should apply to 4.13+. Why is this targeting 4.16?

2024-05-15 07:09 UTC, subhtk commented
According to jira- the release note update is only for 4.16, for now.

2024-05-15 07:15 UTC, subhtk commented
Hi, yes, my apologies. We do need from 4.13 to 4.16, Let me create another PR with the commit.

2024-05-15 07:48 UTC, subhtk commented
Created https://github.com/openshift/openshift-docs/pull/75962 to incorporate applicable versions.

2024-05-17 05:47 UTC, subhtk commented
Closing the PR due to incorrect version - changes tracked through new PR - https://github.com/openshift/openshift-docs/pull/75962.

2024-05-17 05:47 UTC, closed without merging