OBSDOCS-974 - Logging 5.7.13 Release Notes
openshift/openshift-docs pull request #75244
Opened 2024-04-29 12:04 UTC by shreyasiddhartha

Change type: Doc update; Logging Z-Stream Release Notes - 5.7.13
Doc JIRA: https://issues.redhat.com/browse/OBSDOCS-974

Fix Version: 4.12, 4.14, 4.14

Doc Preview:

SME Review:
QE Review:
Peer Review:

2024-04-30 08:13 UTC, periklis requested changes
Missing bug fixes: LOG-5393, LOG-5403

2024-04-30 08:13 UTC, periklis commented
/ohld

2024-04-30 08:13 UTC, periklis commented
/hold

2024-04-30 11:29 UTC, periklis commented
/hold cancel

2024-04-30 11:29 UTC, periklis commented
/lgtm

2024-04-30 11:44 UTC, shreyasiddhartha commented
/label peer-review-needed

2024-04-30 12:14 UTC, kabirbhartiRH commented
@shreyasiddhartha FYI, [LOG-5403](https://issues.redhat.com/browse/LOG-5403) and [LOG-5393](https://issues.redhat.com/browse/LOG-5393) are enhancements and not bugs.

2024-04-30 19:22 UTC, mburke5678 commented on modules/logging-release-notes-5-7-13.adoc
> +* Before this update, {loki-op} set up Loki to use path-based style access for AWS S3, which has been deprecated. With this update, it defaults to virtual-host style without users needing to change t
```suggestion
* Before this update, the {loki-op} would set up Loki to use path-based style access for AWS S3, which has been deprecated. With this update, the {loki-op} defaults to virtual-host style without users needing to change their configuration. (link:https://issues.redhat.com/browse/LOG-5403[LOG-5403])
```

2024-04-30 19:33 UTC, mburke5678 commented
@shreyasiddhartha One comment. Otherwise, [pending the issue](https://github.com/openshift/openshift-docs/pull/75244#issuecomment-2085168723) with LOG-5403 and LOG-5393, LGTM.

2024-05-02 11:19 UTC, shreyasiddhartha commented
/label merge-review-needed

2024-05-02 20:29 UTC, merged

2024-05-02 20:29 UTC, mburke5678 commented
/cherrypick enterprise-4.12

2024-05-02 20:29 UTC, mburke5678 commented
/cherrypick enterprise-4.13