CNV-31882: Move common instance types to virt operator
openshift/openshift-docs pull request #75343
Opened 2024-04-30 14:13 UTC by sbeskin-redhat

Resolves: https://issues.redhat.com/browse/CNV-31882

CNV 4.16

Preview:

2024-05-02 13:37 UTC, dominikholler requested changes
@lyarwood

2024-05-02 13:37 UTC, dominikholler commented on modules/virt-about-ssp-operator.adoc
```suggestion
The SSP Operator, `ssp-operator`, deploys the common templates, the related default boot sources, and the template validator.
```
`common templates` and `common instancetypes` are two different things.

The `common templates` stays in ssp-operator. Looks like the `common instancetypes` was not yet documented here.

The ` the pipeline tasks` should be removed, too. https://issues.redhat.com/browse/CNV-29468

2024-05-02 13:37 UTC, dominikholler commented on modules/virt-about-virt-operator.adoc
```suggestion
The {VirtProductName} Operator, `virt-operator`, deploys, upgrades, and manages {VirtProductName} without disrupting current virtual machine (VM) workloads. In addition, the {VirtProductName} Operator deploys the common instance types and common preferences.
```

2024-05-16 13:59 UTC, geetikakay commented
cc @RoniKishner  please review

2024-07-07 17:54 UTC, sbeskin-redhat commented
/label peer-review-needed

2024-07-08 15:21 UTC, lpettyjo reviewed
LGTM!

2024-07-08 15:35 UTC, sbeskin-redhat commented
/label merge-review-needed

2024-07-08 16:23 UTC, jeana-redhat approved these changes
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

2024-07-08 16:25 UTC, jeana-redhat commented
@sbeskin-redhat just verifying, should "CNV 4.16" be interpreted as OCP versions 4.16+?

2024-07-08 16:28 UTC, sbeskin-redhat commented
@jeana-redhat  Yes, I've updated the description. Thank you

2024-07-08 16:57 UTC, merged

2024-07-08 16:57 UTC, jeana-redhat commented
/cherrypick enterprise-4.17

2024-07-08 16:57 UTC, jeana-redhat commented
/cherrypick enterprise-4.16