RHDEVDOCS-5988: Add git resolver override info
openshift/openshift-docs pull request #75378
Opened 2024-05-01 06:53 UTC by nebelsprachen

Version(s):

* Cherrypick to `pipelines 1.14`

Issue:

* https://issues.redhat.com/browse/RHDEVDOCS-5988

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-05-01 17:49 UTC, mramendi commented
/ok-to-test

2024-05-01 17:55 UTC, mramendi requested changes

2024-05-01 17:55 UTC, mramendi commented on create/remote-pipelines-tasks-resolvers.adoc
> -* xref:../hub/using-tekton-hub-with-openshift-pipelines.adoc#using-tekton-hub-with-openshift-pipelines[Using Tekton Hub with {pipelines-shortname}]
please restore as it was

2024-05-01 17:55 UTC, mramendi commented on modules/op-resolver-git-config-scm.adoc
> +* You can use the authenticated SCM API to configure Git connections for your cluster. This configuration allows you to provide a security token that enables all cluster users to access the repositor
```suggestion
* You can configure Git connections using the authenticated SCM API. You can provide a security token that enables all users on your cluster to access one repository. Additionally, you can specify different SCM providers and tokens for specific pipelines or tasks.
```

2024-05-01 17:55 UTC, mramendi commented on modules/op-resolver-git-override-scm.adoc
> += Overriding the Git resolver for the authenticated SCM API
This module does not seem to work. It is not about "overriding", the TektonConfig process is for "configuring" the SCM API for the cluster. You can then "override" it when using the resolver to specify a particular task or pipeline.

2024-05-01 17:55 UTC, mramendi commented on modules/op-resolver-git-override-scm.adoc
> += Overriding the Git resolver for the authenticated SCM API
Aha, I see what happened here, you start with TektonConfig and switch to a pipeline run spec later.

I suggest reworking this part entirely. TektonConfig is already documented, no need to say anything more about it. And the "overriding" part is about using, not configuring, the resolver.

I see two options:

- expand op-resolver-git-scm.adoc to cover the override use case
- have a separate module similar to op-resolver-git-scm.adoc but specifically for the override use case

2024-06-11 11:16 UTC, vdemeester reviewed
The `params` under `taskRef` or `pipelineRef` are for the resolver, are very limited in number and well defined (and documented) by the resolver and most likely do not accept additionnal ones.

2024-06-11 11:16 UTC, vdemeester commented on create/remote-pipelines-tasks-resolvers.adoc
> +== Specifying a remote pipeline or task with authenticated SCM API
I wonder about the usage of "SCM API".. SCM stands for "source code management" I think, and this use (upstream I guess) comes from the fact that we use https://github.com/jenkins-x/go-scm as a library to do those authenticated clone.

We could just say with authenticated API or something like that. In a gist, the "authenticated fetch on the git repository is done through the respective API (github, gitlab, …)".

2024-06-11 11:16 UTC, vdemeester commented on modules/op-resolver-git-anon.adoc
> +        value: test
Why are we putting this "random" parameter here ? It might render the request invalid.

2024-06-11 11:16 UTC, vdemeester commented on modules/op-resolver-git-anon.adoc
> +            value: test
Same here, why are we putting this "random" parameter here ? It might render the request invalid.

2024-06-11 11:16 UTC, vdemeester commented on create/remote-pipelines-tasks-resolvers.adoc
> +== Specifying a remote pipeline or task with authenticated SCM API
So different API depending on the git provider (vs using the "standard" git clone/fetch mechanisms)

2024-06-11 11:16 UTC, vdemeester commented on modules/op-resolver-git-override-scm.adoc
> +       params:
This extram `params` should be removed.

2024-06-11 11:16 UTC, vdemeester commented on modules/op-resolver-git-scm.adoc
> +        value: test
Same here, why are we putting this "random" parameter here ? It might render the request invalid.

2024-06-11 11:16 UTC, vdemeester commented on modules/op-resolver-git-scm.adoc
> +            value: test
Same here, why are we putting this "random" parameter here ? It might render the request invalid.

2024-06-11 11:16 UTC, vdemeester commented on modules/op-resolver-git-scm.adoc
> +        value: test
Same here, why are we putting this "random" parameter here ? It might render the request invalid.

2024-06-12 09:35 UTC, vdemeester reviewed
Do we want to document the available parameters of the git resolver ?
Such as https://github.com/tektoncd/pipeline/blob/main/docs/git-resolver.md#parameters ?

2024-09-11 10:55 UTC, closed without merging