OSDOCS-10476: ROSA cli proxy configuration not documented
openshift/openshift-docs pull request #75706
Opened 2024-05-08 21:13 UTC by jneczypor

[OSDOCS-10476](https://issues.redhat.com//browse/OSDOCS-10476): ROSA cli proxy configuration not documented

Version(s):
4.15+

Issue:
https://issues.redhat.com/browse/OSDOCS-10476

Link to docs preview:
https://75706--ocpdocs-pr.netlify.app/openshift-rosa/latest/cli_reference/rosa_cli/rosa-manage-objects-cli#rosa-create_rosa-managing-objects-cli

QE review:
- [ ] QE has approved this change.

Additional information:

2024-05-09 17:57 UTC, jneczypor commented
Hi @yuwang-RH! Can I please get QE review of this PR? Thanks!

2024-05-09 18:00 UTC, jneczypor commented
Hi @bchandra-ocp or @arendej! May I please have PM review of the attached PR? Thanks!

2024-05-09 18:04 UTC, bchandra-ocp requested changes
Let's revisit documentation for proxy configuration

2024-05-09 18:04 UTC, bchandra-ocp commented on modules/rosa-configure.adoc
> +[NOTE]
Not accurate. This instruction must go when Proxy is configured with ROSA CREATE CLUSTER and ROSA EDIT CLUSTER commands

2024-05-09 19:29 UTC, bchandra-ocp commented on modules/rosa-configure.adoc
> +[NOTE]
I take back my previous comment. Take a closer look, I understand this is different. 

Checking with engineering to see if this is intended feature. We will need confirmation from QA as well.

2024-05-10 19:02 UTC, jneczypor commented
Hi @bchandra-ocp and @ciaranRoche! Can you take a look at tell me if this is the correct place for the note? Thanks so much!

2024-05-14 22:35 UTC, michaelryanmcneill requested changes
I think this warning needs to go under the section at the top of this page and not where it is placed in this PR. 

> # Managing objects with the ROSA CLI
> Managing objects with the Red Hat OpenShift Service on AWS (ROSA) CLI, rosa, such as adding dedicated-admin users, managing clusters, and scheduling cluster upgrades.

2024-05-15 20:03 UTC, michaelryanmcneill commented on modules/rosa-parent-commands.adoc
> +[NOTE]
We should remove this from the section as it is at the header.

2024-05-15 20:03 UTC, michaelryanmcneill requested changes
Just need to remove the extra one.

2024-05-15 20:54 UTC, michaelryanmcneill approved these changes
/lgtm

2024-05-15 21:01 UTC, michaelryanmcneill commented
/lgtm

2024-05-15 21:23 UTC, merged

2024-05-15 21:24 UTC, EricPonvelle commented
/cherrypick enterprise-4.16