[WIP] TELCODOCS-1849: DEV & QE review
openshift/openshift-docs pull request #76309
Opened 2024-05-21 18:00 UTC by StephenJamesSmith

D/S Docs: [MGMT-16640] Move webhooks to a separated deployment. Add commands for webhook logs.

Jira: https://issues.redhat.com/browse/TELCODOCS-1849

Version(s): openshift-4.16.0, openshift-4.15.0, openshift-4.14.0, openshift-4.13.0, openshift-4.12.0

Link to docs preview: 

SME review: @qbarrand
QE review: @cdvultur

2024-05-21 18:10 UTC, StephenJamesSmith commented
@cdvultur @qbarrand Please review and ACK.

2024-05-22 07:23 UTC, qbarrand commented on modules/kmm-reading-operator-logs.adoc
> +$ oc logs -fn "$namespace" deployments/kmm-operator-webhook-server`
```suggestion
$ oc logs -fn openshift-kmm deployments/kmm-operator-webhook-server
```

2024-05-22 07:23 UTC, qbarrand commented on modules/kmm-reading-operator-logs.adoc
> +$ oc logs -fn "$namespace" deployments/kmm-operator-hub-webhook-server`
```suggestion
$ oc logs -fn openshift-kmm deployments/kmm-operator-hub-webhook-server
```

2024-05-22 11:54 UTC, StephenJamesSmith commented on modules/kmm-reading-operator-logs.adoc
> +$ oc logs -fn "$namespace" deployments/kmm-operator-webhook-server`
changed.

2024-05-22 11:54 UTC, StephenJamesSmith commented on modules/kmm-reading-operator-logs.adoc
> +$ oc logs -fn "$namespace" deployments/kmm-operator-hub-webhook-server`
changed.

2024-05-22 12:20 UTC, cdvultur requested changes
Some extra quotes are present, please remove them

2024-05-22 12:20 UTC, cdvultur commented on modules/kmm-reading-operator-logs.adoc
> +$ oc logs -fn openshift-kmm deployments/kmm-operator-webhook-server`
Please remove extra quote ( ` ) at the end of the command

2024-05-22 12:20 UTC, cdvultur commented on modules/kmm-reading-operator-logs.adoc
> +$ oc logs -fn openshift-kmm deployments/kmm-operator-hub-webhook-server`
Please remove extra quote ( ` ) at the end of the command

2024-05-22 13:07 UTC, cdvultur approved these changes
/lgtm

2024-05-22 13:08 UTC, StephenJamesSmith commented
/label telco

2024-05-22 13:09 UTC, StephenJamesSmith commented
/label peer-review-needed

2024-05-22 15:19 UTC, skrthomas reviewed
/lgtm

2024-05-22 17:49 UTC, StephenJamesSmith commented
/label telco

2024-05-22 17:49 UTC, StephenJamesSmith commented
/label merge-review-needed

2024-05-22 20:37 UTC, merged

2024-05-22 20:38 UTC, skrthomas commented
/cherrypick enterprise-4.12

2024-05-22 20:38 UTC, skrthomas commented
/cherrypick enterprise-4.13

2024-05-22 20:38 UTC, skrthomas commented
/cherrypick enterprise-4.14

2024-05-22 20:38 UTC, skrthomas commented
/cherrypick enterprise-4.15

2024-05-22 20:39 UTC, skrthomas commented
/cherrypick enterprise-4.16