[enterprise-4.16] OSDOCS-10574: add RN entry
openshift/openshift-docs pull request #76620
Opened 2024-05-28 21:59 UTC by jldohmann

Version(s): 4.16

Issue: https://issues.redhat.com/browse/OSDOCS-10574

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-06-05 15:12 UTC, SNiemann15 requested changes

2024-06-05 15:12 UTC, SNiemann15 commented on release_notes/ocp-4-16-release-notes.adoc
> +=== {op-system} `dasd` image artifacts no longer supported for LinuxONE and IBM Z systems
```suggestion
=== {op-system} `dasd` image artifacts no longer supported on {ibm-z-name} and {ibm-linuxone-name} (`s390x`)
```

2024-06-05 15:12 UTC, SNiemann15 commented on release_notes/ocp-4-16-release-notes.adoc
> +With this release, `dasd` image artifacts for `s390x` architectures are removed from the {product-title} image building pipeline. You can still use the `metal4k` image artifact, which contains the sa
```suggestion
With this release, `dasd` image artifacts for the `s390x` architecture are removed from the {product-title} image building pipeline. You can still use the `metal4k` image artifact, which contains the same functionality.
```

2024-06-05 18:34 UTC, jldohmann commented
@mike-nguyen can you PTAL at this docs PR for QE ack? it's a RN entry about stopping production of `dasd` image artifacts. thank you!

2024-06-06 17:39 UTC, tmalove commented
/remove-label peer-review-needed
/label peer-review-in-progress

2024-06-06 20:29 UTC, merged