OSDOCS#10143: Release note for no longer generating legacy SA token s…
openshift/openshift-docs pull request #76844
Opened 2024-06-03 21:26 UTC by bergerhoffer

…ecrets

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-06-03 22:19 UTC, bergerhoffer commented
@sanchezl Apologies for the delay, I know it's been awhile since we last talked about the proper wordings on this. Could you PTAL and let me know what you think on this release note for the changes in behavior?

Preview: https://76844--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-legacy-sa-tokens

2024-06-03 22:22 UTC, bergerhoffer commented
@gangwgr can you PTAL for QE review as well? Thanks!

2024-06-06 13:18 UTC, gangwgr commented
seems ok to me

2024-06-10 16:27 UTC, sanchezl requested changes

2024-06-10 16:27 UTC, sanchezl commented on release_notes/ocp-4-16-release-notes.adoc
> +Prior to {product-title} 4.16, an image pull secret and a service account API token secret were generated when a service account was created. Starting with {product-title} 4.16, the service account A
```suggestion
Prior to {product-title} 4.16, when the integrated image registry is enabled, a legacy service account API token secret was generated for every service account in the cluster. Starting with {product-title} 4.16, the legacy service account API token secret is no longer generated for each service account.
```

2024-06-10 16:27 UTC, sanchezl commented on release_notes/ocp-4-16-release-notes.adoc
> +Additionally, the image pull secret no longer uses a legacy service account API token secret. Instead, the image pull secret now uses a bound service account token.
```suggestion
Additionally,  when the integrated image registry is enabled, the image pull secret generated for every service account no longer uses a legacy service account API token. Instead, the image pull secret now uses a bound service account token that is automatically refreshed before it expires.
```

2024-06-10 18:11 UTC, bergerhoffer commented
@sanchezl Updated, PTAL

2024-06-11 12:26 UTC, sanchezl approved these changes
/lgtm

2024-06-12 12:28 UTC, bergerhoffer commented
/label peer-review-needed

2024-06-12 12:29 UTC, bergerhoffer commented
/retest

2024-06-12 12:39 UTC, mletalie reviewed
/label peer-review-in-progress

2024-06-12 12:49 UTC, mletalie reviewed
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/lgtm

2024-06-12 12:49 UTC, mletalie commented
Great job on this, @bergerhoffer!

2024-06-12 19:52 UTC, merged