OSDOCS-9865: Specialized Hardware and Driver Enablement Table
openshift/openshift-docs pull request #77405
Opened 2024-06-12 22:38 UTC by GroceryBoyJr

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-06-12 22:42 UTC, GroceryBoyJr commented
/retest

2024-06-12 23:00 UTC, GroceryBoyJr commented
/assign @cdvultur  PTAL: your qe-approval desired please!

2024-06-12 23:04 UTC, GroceryBoyJr commented
/assign @cdvultur

2024-06-12 23:05 UTC, GroceryBoyJr commented
/label peer-review-needed

2024-06-13 12:08 UTC, JoeAldinger reviewed
/lgtm

2024-06-13 12:19 UTC, GroceryBoyJr commented
@bthurber PTAL

2024-06-13 13:41 UTC, qbarrand commented on release_notes/ocp-4-16-release-notes.adoc
> +|General Availability
```suggestion
|Kernel Module Management Operator
|General Availability
|General Availability
|General Availability

|Kernel Module Management Operator - support for Hub and Spoke topologies
|General Availability
|General Availability
|General Availability
```

2024-06-13 13:42 UTC, cdvultur requested changes

2024-06-13 14:15 UTC, GroceryBoyJr commented on release_notes/ocp-4-16-release-notes.adoc
> +|Hub and spoke cluster support
Done, thank you @cdvultur

2024-06-13 14:15 UTC, GroceryBoyJr commented on release_notes/ocp-4-16-release-notes.adoc
> +|General Availability
Done, thank you @qbarrand

2024-06-13 14:19 UTC, GroceryBoyJr commented on release_notes/ocp-4-16-release-notes.adoc
> +|Hub and spoke cluster support
@cdvultur I was asked not to change the name of the table. But I have gladly made the other changes you requested.

2024-06-13 14:20 UTC, GroceryBoyJr commented
/retest

2024-06-13 14:21 UTC, GroceryBoyJr commented
/retest

2024-06-13 14:55 UTC, GroceryBoyJr commented
@cdvultur @qbarrand I was unable to add a fourth table column for 4.13! (that would explain why all the other tables only have only 3!) :-/ I will research this issue and get back to you. In the meantime, I'll push it to the release notes with three releases shown so the information is not lost from the release notes.

2024-06-13 15:17 UTC, cdvultur commented
/lgtm

2024-06-13 15:45 UTC, GroceryBoyJr commented
/label merge-review-needed

2024-06-13 16:41 UTC, merged