HCIDOCS-72: DS & RN: METAL-650 Attach non-bootable ISO to BMH
openshift/openshift-docs pull request #77467
Opened 2024-06-13 23:25 UTC by johnwilkins

Added a module for attaching a non-bootable ISO after provisioning a node.

Fixes: HCIDOCS-72

See https://issues.redhat.com/browse/HCIDOCS-72 for additional details.

Preview URL: http://jowilkin.com:8080/HCIDOCS-72/welcome/index.html

For release(s): 4.16
QE Review: 

- [ ] QE has approved this change. 

Signed-off-by: John Wilkins <jowilkin@redhat.com>

2024-06-13 23:38 UTC, johnwilkins commented
/label peer-review-needed

2024-06-14 09:27 UTC, agantony commented
/label peer-review-in-progress

2024-06-14 14:41 UTC, agantony reviewed
Added a few suggestions for your consideration; overall lgtm!

2024-06-14 14:41 UTC, agantony commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +// post_installation_configuration/bare-metal-configuration.adoc
```suggestion
// post_installation_configuration/bare-metal-configuration.adoc
```
```suggestion
// * post_installation_configuration/bare-metal-configuration.adoc
```

2024-06-14 14:41 UTC, agantony commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +You can attach a generic non-bootable ISO virtual media image to a provisioned node using the `DataImage` resource. Once you apply the resource, the ISO becomes accessible to the operating system aft
```suggestion
You can attach a generic, non-bootable ISO virtual media image to a provisioned nod by using the `DataImage` resource. Once you apply the resource, the ISO image becomes accessible to the operating system after it has booted. This is useful for configuring a node after the operating system has been deployed and before the node boots for the first time.
```

2024-06-14 14:41 UTC, agantony commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +* The `url` to the ISO image must be valid.
```suggestion
* You have a valid `url` to the ISO image.
```

2024-06-14 14:41 UTC, agantony commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +* The `name` must be the same name as the node as defined in its `BareMetalHost` resource.
```suggestion
* The node must use Redfish or drivers derived from it to support this feature.
* The node must be in the `Provisioned` or `ExternallyProvisioned` state.
* The `name` must be the same as the name of the node defined in its `BareMetalHost` resource.
```

2024-06-14 14:41 UTC, agantony commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +  name: <node_name> <1>
```suggestion
  name: <node_name> # <1>
```

2024-06-14 14:41 UTC, agantony commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +  url: "http://dataimage.example.com/non-bootable.iso" <2>
```suggestion
  url: "http://dataimage.example.com/non-bootable.iso" # <2>
```

2024-06-14 14:41 UTC, agantony commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +<2> Replace `http://dataimage.example.com/non-bootable.iso` with the URL and path to the ISO.
```suggestion
<1> Specify the name of the node as defined in its `BareMetalHost` resource.
<2> Specify the URL and path to the ISO image.
```

2024-06-14 14:41 UTC, agantony commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +. Save the `DataImage` resource to a file:
```suggestion
. Save the `DataImage` resource to a file by running the following command:
```

2024-06-14 14:41 UTC, agantony commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +<1> Ensure that the namespace is the same as the namespace for the `BareMetalHost` resource. For example, `openshift-machine-api`.
```suggestion
<1> Ensure that the namespace matches the namespace for the `BareMetalHost` resource. For example, `openshift-machine-api`.
```

2024-06-14 14:41 UTC, agantony commented
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2024-06-14 16:46 UTC, johnwilkins commented
/label merge-review-needed

2024-06-14 16:46 UTC, johnwilkins commented on post_installation_configuration/bare-metal-configuration.adoc
> +
Fixed.

2024-06-14 17:01 UTC, hroyrh requested changes
Added a few comments, other than that it looks good.

2024-06-14 17:55 UTC, johnwilkins commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +====
Done.

2024-06-14 17:55 UTC, johnwilkins commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +$ oc get dataimage <node_name> -n openshift-machine-api -o yaml
Done.

2024-06-14 18:13 UTC, hroyrh commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +    namespace: test-dataimage
namespace: openshift-machine-api

2024-06-14 18:13 UTC, hroyrh commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +        {"apiVersion":"metal3.io/v1alpha1","kind":"DataImage","metadata":{"annotations":{},"name":"bmh-node-1","namespace":"test-dataimage"},"spec":{"url":"http://dataimage.example.com/non-bootable.i
namespace: openshift-machine-api

2024-06-14 18:26 UTC, johnwilkins commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +        {"apiVersion":"metal3.io/v1alpha1","kind":"DataImage","metadata":{"annotations":{},"name":"bmh-node-1","namespace":"test-dataimage"},"spec":{"url":"http://dataimage.example.com/non-bootable.i
Done.

2024-06-14 18:26 UTC, johnwilkins commented on modules/bmo-attaching-a-non-bootable-iso-to-a-bare-metal-node.adoc
> +    namespace: test-dataimage
Done

2024-06-14 18:42 UTC, hroyrh commented
/lgtm

2024-06-14 19:04 UTC, stevsmit commented
lgtm

2024-06-14 19:17 UTC, merged

2024-06-14 19:17 UTC, kcarmichael08 commented
/cherrypick enterprise-4.16

2024-06-14 19:57 UTC, kcarmichael08 commented
/cherrypick enterprise-4.16

2024-06-14 20:12 UTC, stevsmit commented
/cherrypick enterprise-4.16

2024-06-14 20:21 UTC, stevsmit commented
/cherrypick enterprise-4.16

2024-06-14 21:01 UTC, stevsmit commented
/cherrypick enterprise-4.16

2024-06-15 13:21 UTC, stevsmit commented
/cherrypick enterprise-4.16