TELCODOCS-1707: Add Performing upgrade GitOps
openshift/openshift-docs pull request #77561
Opened 2024-06-17 13:57 UTC by amolnar-rh

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-06-17 14:22 UTC, amolnar-rh commented
/label peer-review-needed

2024-06-17 14:23 UTC, amolnar-rh commented
Please ignore the build error, that should be resolved after relevant PRs are merged and I rebase.

2024-06-17 17:01 UTC, ShaunaDiaz commented
/test validate-portal

2024-06-17 19:24 UTC, tmalove commented
/remove-label peer-review-needed
/label peer-review-in-progress

2024-06-17 20:17 UTC, tmalove commented
/remove-label peer-review-in-progress
/label peer-review-done

Also be sure to squash your commits before requesting a merge. Thanks.

2024-06-17 20:18 UTC, tmalove approved these changes

2024-06-17 20:18 UTC, tmalove commented on edge_computing/image_based_upgrade/ztp-image-based-upgrade.adoc
> +* xref:../../edge_computing/image_based_upgrade/preparing_for_image_based_upgrade/ztp-image-based-upgrade-prep-resources.adoc[Preparing for the image-based upgrade for single-node OpenShift clusters]
Same comment as the bot - missing anchor ID.

2024-06-17 20:18 UTC, tmalove commented on edge_computing/image_based_upgrade/ztp-image-based-upgrade.adoc
> +* xref:../../backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-cr.adoc[Creating a Backup CR]
Same comment as the bot - missing anchor ID.

2024-06-17 20:18 UTC, tmalove commented on modules/ztp-image-based-upgrade-talm-prep.adoc
> +You may encounter the following issues:
```suggestion
You might encounter the following issues: 
```
See ISG: https://www.ibm.com/docs/en/ibm-style?topic=word-usage#m

2024-06-17 20:18 UTC, tmalove commented on modules/ztp-image-based-upgrade-talm-prep.adoc
> +* validation errors if the {lcao} detects any issues with with `oadpContent`
```suggestion
* validation errors if the {lcao} detects any issues with `oadpContent`
```
```suggestion
* validation errors if the {lcao} detects any issues with with `oadpContent`
```

2024-06-18 08:47 UTC, amolnar-rh commented on edge_computing/image_based_upgrade/ztp-image-based-upgrade.adoc
> +* xref:../../backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-cr.adoc[Creating a Backup CR]
These are commented out for now, I'll have a dedicated PR to add and resolve xref issues.

2024-06-18 15:55 UTC, mpmaruthu requested changes
few change needs to be updated otherwise looks good to me.

2024-06-19 09:59 UTC, mpmaruthu commented
Telco RAN QE: Looks good to me.
/Peri M

2024-06-21 18:46 UTC, jeana-redhat reviewed
mostly minor stuff, but also the TS module is not getting rendered for some reason :thinking: 

/remove-label merge-review-in-progress
/remove-label merge-review-needed

2024-06-21 18:46 UTC, jeana-redhat commented on edge_computing/image_based_upgrade/ztp-image-based-upgrade.adoc
Can replace GitOps ZTP with `{ztp}` throughout

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-prep.adoc
> +* Create policies and `ConfigMap` objects for resources used in the image-based upgrade. For more information, see _Creating ConfigMap objects for the image-based upgrade with {ztp}_
I think you have the titles in quotes in the other ones I have looked at

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-prep.adoc
> +<2> Define the seed image, OpenShift Container Platform version, and pull secret for the upgrade in the Prep stage.
```suggestion
<2> Define the seed image, {product-title} version, and pull secret for the upgrade in the Prep stage.
```

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-prep.adoc
> +. Verify that the policies required for an image-based upgrade are created:
```suggestion
. Verify that the policies required for an image-based upgrade are created by running the following command:
```

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-prep.adoc
> +. Apply the `Prep` policy:
```suggestion
. Apply the `Prep` policy by running the following command:
```

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-prep.adoc
> +* validation errors if the {lcao} detects any issues with `oadpContent`
```suggestion
* Validation warnings or errors if the {lcao} detects any issues with `extraManifests` 
* Validation errors if the {lcao} detects any issues with `oadpContent`
```

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-prep.adoc
> +. Monitor the status and wait for the `cgu-ibu-prep` `ClusterGroupUpgrade` to report `Completed`.
```suggestion
. Monitor the status and wait for the `cgu-ibu-prep` `ClusterGroupUpgrade` to report `Completed` by running the following command:
```

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-prep.adoc
> +$ oc get cgu -n default
would check with SMEs about `cgu` vs a long name as well (later)

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-upgrade.adoc
{ztp} in here as well

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-upgrade.adoc
> +. Apply the `Upgrade` policy:
```suggestion
. Apply the `Upgrade` policy by running the following command:
```

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-upgrade.adoc
> +.. Monitor the status and wait for the `cgu-ibu-upgrade` `ClusterGroupUpgrade` to report `Completed`.
Would un-nest this step `a` 
```suggestion
. Monitor the status by running the following command and wait for the `cgu-ibu-upgrade` `ClusterGroupUpgrade` to report `Completed`:
```

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-upgrade.adoc
> +. Apply the policy:
```suggestion
. Apply the policy by running the following command:
```

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-upgrade.adoc
> +.. Monitor the status and wait for the `cgu-ibu-finalize` `ClusterGroupUpgrade` to report `Completed`.
same here, would un-nest
```suggestion
. Monitor the status by running the following command and wait for the `cgu-ibu-finalize` `ClusterGroupUpgrade` to report `Completed`:
```

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-rollback.adoc
> +. Apply the `Rollback` policy:
```suggestion
. Apply the `Rollback` policy by running the following command:
```

2024-06-21 18:46 UTC, jeana-redhat commented on modules/ztp-image-based-upgrade-talm-rollback.adoc
> +. Apply the policy:
```suggestion
. Apply the policy by running the following command:
```

2024-06-21 18:46 UTC, jeana-redhat commented on edge_computing/image_based_upgrade/ztp-image-based-upgrade.adoc
> +include::modules/cnf-image-based-upgrade-troubleshooting.adoc[leveloffset=+1]
This one is not getting pulled into the assembly :thinking: 
![image](https://github.com/openshift/openshift-docs/assets/61474374/3447721f-51b7-4aa2-87b4-c8b4824cd4cb)

2024-06-21 18:49 UTC, jeana-redhat commented on edge_computing/image_based_upgrade/ztp-image-based-upgrade.adoc
> +include::modules/cnf-image-based-upgrade-troubleshooting.adoc[leveloffset=+1]
nvm this shows up now idk what the deal was

2024-06-21 19:15 UTC, merged

2024-06-21 19:15 UTC, jeana-redhat commented
/cherrypick enterprise-4.16