CNV#43195: RN - VM migration fails with virError
openshift/openshift-docs pull request #77978
Opened 2024-06-24 15:32 UTC by danielclowers

Version(s):
4.16

Issue:
https://issues.redhat.com/browse/CNV-43195

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-06-24 15:46 UTC, danielclowers commented
/retest-required

2024-06-24 17:22 UTC, kbidarkar requested changes

2024-06-24 17:22 UTC, kbidarkar commented on virt/release_notes/virt-4-16-release-notes.adoc
> +* VM migrations may fail on clusters with mixed CPU types.
Would be good to have the bug added in RN.

VM migrations may fail on clusters with mixed CPU types. ( CNV-43195 )

2024-06-24 17:47 UTC, danielclowers commented
@kbidarkar is it possible to remove the security level for CNV-43195? The build is failing because that Jira requires a login.

```
 ERROR: Do not include links to JIRA issues that require a login (https://issues.redhat.com/browse/CNV-43195)
```

2024-06-25 13:02 UTC, danielclowers commented
/retest-required

2024-06-25 13:08 UTC, danielclowers commented
/label peer-review-needed

2024-06-25 14:16 UTC, bergerhoffer commented
/label peer-review-in-progress

2024-06-25 14:27 UTC, bergerhoffer reviewed
One minor grammar thing, but just to address your comment about having to rename / change the ID of the module in order to link to it.

You shouldn't have to do this, because they shouldn't be the same (even if they look the same, the module has the "_{context}" added to the ID, so it should still be different. And even if you do need to change the ID, you don't necessarily have to change the whole file name - we usually try to avoid file name changes unless truly necessary. I'll ping you on slack!

2024-06-25 14:27 UTC, bergerhoffer commented on virt/release_notes/virt-4-16-release-notes.adoc
> +* VM migrations may fail on clusters with mixed CPU types. (link:https://issues.redhat.com/browse/CNV-43195[*CNV-43195*])
may -> might (per IBM style guide)

```suggestion
* VM migrations might fail on clusters with mixed CPU types. (link:https://issues.redhat.com/browse/CNV-43195[*CNV-43195*])
```

2024-06-25 15:57 UTC, danielclowers commented
/label merge-review-needed

2024-06-25 16:10 UTC, michaelryanpeter commented
/label merge-review-in-progress

2024-06-25 16:20 UTC, michaelryanpeter commented on modules/virt-configuring-default-cpu-model.adoc
@danielclowers This change to the module should be made in `main` and then cherrypicked to `enterprise-4.16`.

I know it seems like a nit, but it is actually important to keep `main` and 4.16 in sync. Would you please reverse this edit and move it to another PR with `main` as the target branch?

Otherwise, LGTM.

/remove-label merge-review-in-progress
/remove-label merge-review-needed

2024-06-25 16:46 UTC, danielclowers commented on modules/virt-configuring-default-cpu-model.adoc
Great catch. Reverted that change and will look into opening a separate PR.

2024-06-25 17:39 UTC, michaelryanpeter commented
Daniel asked for a merge over Slack.

2024-06-25 17:39 UTC, merged