[wip] events update
openshift/openshift-docs pull request #7809
Opened 2018-02-15 05:37 UTC by gaurav-nelson

WIP

2018-02-15 05:39 UTC, gaurav-nelson commented
@tnguyen-rh This one is for https://bugzilla.redhat.com/show_bug.cgi?id=1484537 PTAL

Can I get some help with this one?

2018-03-28 13:38 UTC, knobunc approved these changes
The networking events LGTM.

/lgtm

2018-03-28 20:21 UTC, pravisankar reviewed
Some more events might be missing here. I do not see Scheduler, Pod auto scale events.

2018-03-28 23:48 UTC, pravisankar commented
Scheduler Events:
---------------------
FailedScheduling  :  Failed to schedule pod: `<pod-namespace>/<pod-name>` 
This event is raised for various reasons: AssumePodVolumes failed, Binding rejected, etc.

Preempted  :  By `<preemptor-namespace>/<preemptor-name>` on node `<node-name>`

Scheduled  :  Successfully assigned `<pod-name>` to `<node-name>`

2018-03-29 00:01 UTC, pravisankar commented
Horizontal Pod AutoScaler Events:
--------------------------------------

SelectorRequired  :  Selector is required

InvalidSelector  :  Couldn't convert selector into a corresponding internal selector object

FailedGetObjectMetric  :  HPA was unable to compute the replica count

InvalidMetricSourceType  :  Unknown metric source type

ValidMetricFound  :  HPA was able to successfully calculate a replica count

FailedConvertHPA  :  Failed to convert the given HPA

FailedGetScale  :   HPA controller was unable to get the target's current scale

SucceededGetScale  :  HPA controller was able to get the target's current scale

FailedComputeMetricsReplicas  :  Failed to compute desired number of replicas based on listed metrics

FailedRescale  :  New size: `<size>`; reason: `<msg>`; error: `<error-msg>`

SuccessfulRescale  :  New size: `<size>`; reason: `<msg>`

FailedUpdateStatus  :  Failed to update status

2018-03-29 00:10 UTC, gaurav-nelson commented
Thank you @pravisankar 
I will add these ones as well.

2018-03-29 00:16 UTC, pravisankar commented
DaemonSet Events:
-----------------------

SelectingAll  :  This daemon set is selecting all pods. A non-empty selector is required

FailedPlacement  :  Failed to place pod on `<node-name>`

FailedDaemonPod  :  Found failed daemon pod `<pod-name>` on node `<node-name>`, will try to kill it

2018-03-29 01:05 UTC, pravisankar commented
LoadBalancer Events:
------------------------

CreatingLoadBalancerFailed  :  Error creating load balancer

DeletingLoadBalancer  :  Deleting load balancer

EnsuringLoadBalancer  :  Ensuring load balancer

EnsuredLoadBalancer  :  Ensured load balancer

UnAvailableLoadBalancer :  There are no available nodes for LoadBalancer service

LoadBalancerSourceRanges  :  `<old-source-range>` -> `<new-source-range>`

LoadbalancerIP  :  `<old-ip>` -> `<new-ip>`

ExternalIP  :  Added: `<external-ip>`

UID  : `<old-service-uid>` -> `<new-service-uid>`

ExternalTrafficPolicy :  `<old-policy>` -> `<new-ploicy>`

HealthCheckNodePort  : `<old-node-port>` -> `new-node-port>`

UpdatedLoadBalancer  :  Updated load balancer with new hosts

LoadBalancerUpdateFailed  :  Error updating load balancer with new hosts

DeletingLoadBalancer  :  Deleting load balancer

DeletingLoadBalancerFailed  :  Error deleting load balancer

DeletedLoadBalancer  :  Deleted load balancer

2018-04-04 20:26 UTC, gaurav-nelson commented
Thanks @pravisankar I have added all these event as well. I am now working on their descriptions and will soon put this up for a review.

2018-04-04 23:32 UTC, gaurav-nelson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[DOCS] Add documentation for ALL events](https://trello.com/c/yRIZC72I/1-docs-add-documentation-for-all-events)

2018-04-05 02:46 UTC, pravisankar requested changes

2018-04-05 02:46 UTC, pravisankar commented on dev_guide/events.adoc
> +|New size: <size>; reason: <msg>; error: <error-msg>
New size: `<size>`; reason: `<msg>`; error: `<error-msg>`

2018-04-05 02:46 UTC, pravisankar commented on dev_guide/events.adoc
> +|New size: <size>; reason: <msg>
New size: `<size>`; reason: `<msg>`

2018-04-05 02:46 UTC, pravisankar commented on dev_guide/events.adoc
> +|Lists the new `HealthCheckNodePort. For example, `<old-node-port> -> new-node-port>`
`HealthCheckNodePort`

2018-04-05 23:40 UTC, pravisankar approved these changes
/lgtm

2018-04-08 23:31 UTC, gaurav-nelson commented
@bmeng Please take a look

2018-04-09 05:28 UTC, gaurav-nelson commented
@openshift/team-documentation PTAL

2018-04-09 23:26 UTC, bfallonf commented on dev_guide/events.adoc
> +|Preempting other pods
Full stop after sentence?

2018-04-09 23:28 UTC, bfallonf commented on dev_guide/events.adoc
> +|Failed create pod sandbox.
"Failed to create pod sandbox" maybe?

2018-04-09 23:28 UTC, bfallonf commented on dev_guide/events.adoc
> +|Failed to make pod data directories
Full stop?

2018-04-09 23:28 UTC, bfallonf commented on dev_guide/events.adoc
> +|Selector is required
Full stop?

2018-04-09 23:28 UTC, bfallonf commented on dev_guide/events.adoc
> +|Couldn't convert selector into a corresponding internal selector object
s/couldn't/could not

2018-04-09 23:29 UTC, bfallonf commented on dev_guide/events.adoc
> +|HPA was unable to compute the replica count
Full stop? For the rest of this table as well.

2018-04-09 23:30 UTC, bfallonf commented on dev_guide/events.adoc
> +|Occurs when volume for the claim is provisioned either manually or via external software
Full stop? And on the one below the one below as well.

2018-04-09 23:31 UTC, bfallonf commented on dev_guide/events.adoc
> +|Pre stop hook unfinished.
s/pre stop/pre-stop

2018-04-09 23:31 UTC, bfallonf commented on dev_guide/events.adoc
> +|Failed to place pod on `<node-name>`
Full stop

2018-04-09 23:32 UTC, bfallonf commented
@gaurav-nelson I made a few comments. Mostly full stop is missing-related.

2018-04-10 03:01 UTC, gaurav-nelson commented
Thanks @bfallonf I have fixed those. Merging this one now.

2018-04-10 03:01 UTC, merged

2018-04-10 03:02 UTC, gaurav-nelson commented
/cherrypick enterprise-3.6

2018-04-10 03:02 UTC, gaurav-nelson commented
/cherrypick enterprise-3.7

2018-04-10 03:02 UTC, gaurav-nelson commented
/cherrypick enterprise-3.9

2018-04-10 03:02 UTC, gaurav-nelson commented
/cherrypick enterprise-3.10

2018-04-10 03:04 UTC, gaurav-nelson commented
/cherrypick enterprise-3.5

2018-04-10 03:05 UTC, gaurav-nelson commented
Cherry-picked in 3.5 branch as well, because the original bug was against version 3.5