Pipelines 5988: Update override for git resolver
openshift/openshift-docs pull request #78382
Opened 2024-07-02 17:35 UTC by buildbricks

Version(s):

* Cherrypick to `pipelines-docs-1.14` `pipelines-docs-1.15` `pipelines-docs-1.16`

Issue:

* https://issues.redhat.com/browse/RHDEVDOCS-5988

Link to docs preview: https://78382--ocpdocs-pr.netlify.app/openshift-pipelines/latest/create/remote-pipelines-tasks-resolvers.html 

QE review:
- [x] QE has approved this change.

Additional information:

2024-07-02 23:11 UTC, mramendi commented
/ok-to-test

2024-07-18 09:16 UTC, ppitonak requested changes

2024-08-02 09:56 UTC, ppitonak commented on modules/op-resolver-git-scm.adoc
> +apiVersion: tekton.dev/v1beta1
we should use v1 everywher

2024-08-02 09:59 UTC, ppitonak commented on modules/op-resolver-git-anon.adoc
> +      value: "testPipelineRun"
```suggestion
      value: "testPipelineRun"
    - name: sample-pipeline-parameter
      value: test
```

2024-08-02 09:59 UTC, ppitonak commented on modules/op-resolver-git-anon.adoc
> +        value: test
see the suggestion below

2024-08-02 10:49 UTC, ppitonak commented on modules/op-resolver-git-anon.adoc
> +        value: test
```suggestion
```

2024-08-02 11:55 UTC, ppitonak requested changes

2024-08-02 11:55 UTC, ppitonak commented on modules/op-resolver-git-anon.adoc
> +      value: test
```suggestion
      params:        
      - name: sample-task-parameter
        value: test
```

2024-08-02 11:55 UTC, ppitonak commented on modules/op-resolver-git-override-scm.adoc
> +
```suggestion
    params:
    - name: org
      value: tektoncd
    - name: repo
      value: catalog
    - name: revision
      value: main
    - name: pathInRepo
      value: task/git-clone/0.6/git-clone.yaml
    - name: token
      value: my-secret-token
    - name: tokenKey
      value: token
    - name: scmType
      value: github
    - name: serverURL
      value: https://ghe.mycompany.com
```

2024-08-05 10:11 UTC, vdemeester approved these changes

2024-08-05 21:03 UTC, adellape commented on modules/op-resolver-git-override-scm.adoc
> +| https://ghe.mycompany.com
This needs some passthrough to make it non-clickable (like the others in earlier tables):
```suggestion
| `+https://ghe.mycompany.com+`
```

2024-08-05 21:03 UTC, adellape commented on modules/op-resolver-git-override-scm.adoc
> +| tektoncd
Overall, this table should be marked-up/formatted (for file names, field/value names, etc.) to better match the earlier tables, too. For example in this first row (though, apply uniformly throughout the table):
```suggestion
.Supported parameters to override the Git resolver
|===
| Parameter | Description | Example value

| `org`
| The organization for the repository.
| `tektoncd`
```

2024-08-05 21:13 UTC, adellape commented
Also reminder to squash down to 1 commit before requesting merge. Thank you!

2024-08-06 08:07 UTC, ppitonak approved these changes

2024-08-06 11:46 UTC, xenolinux commented
/label merge-review-needed

2024-08-06 15:07 UTC, adellape approved these changes

2024-08-06 15:07 UTC, adellape commented on modules/op-resolver-git-override-scm.adoc
> +| `+https://ghe.mycompany.com+`
I meant for the whole table to get the marked-up treatment (where appropriate), but not going to block merge on this. But consider for a follow-up.

2024-08-06 15:07 UTC, merged

2024-08-06 15:08 UTC, adellape commented
/cherrypick pipelines-docs-1.16

2024-08-06 15:08 UTC, adellape commented
/cherrypick pipelines-docs-1.15

2024-08-06 15:08 UTC, adellape commented
/cherrypick pipelines-docs-1.14