OSDOCS#35593: Update example resource for auto-updates
openshift/openshift-docs pull request #78673
Opened 2024-07-09 16:19 UTC by jherrman

Version(s):
4.14, 4.15, 4.16

Issue:
https://issues.redhat.com/browse/CNV-35593

Link to docs preview:
TODO

QE review:
- [ ] QE has approved this change.

2024-08-07 13:01 UTC, dominikholler requested changes
Thanks for the PR. I requested some changes.

2024-08-07 13:01 UTC, dominikholler commented on modules/virt-autoupdate-custom-bootsource.adoc
> +              pullMethod: node
the `pullMethod' is not required here.

2024-08-07 16:26 UTC, jherrman commented
@dominikholler , thank you for the review, I removed the two extraneous lines

2024-08-12 16:08 UTC, jherrman commented
/label peer-review-needed

2024-08-13 10:10 UTC, ShaunaDiaz commented
/test validate-asciidoc

2024-08-13 11:36 UTC, RoniKishner commented
versions description says 4.15 and later.
You are merging into [openshift:enterprise-4.14](https://github.com/openshift/openshift-docs/tree/enterprise-4.14), is this correct?

2024-08-13 12:07 UTC, jherrman commented
@RoniKishner , good catch. The [related JIRA](https://issues.redhat.com/browse/CNV-35593) was originally filed against an incorrect version, so I had to change the description. I'll try to change the target branch, hopefully it won't break too much...

2024-08-13 12:23 UTC, jherrman commented
> @RoniKishner , good catch. The [related JIRA](https://issues.redhat.com/browse/CNV-35593) was originally filed against an incorrect version, so I had to change the description. I'll try to change the target branch, hopefully it won't break too much...

Okay, that didn't work too well. Would it be okay to leave this PR unmerged and only create cherry-pick PRs for 4.15 and later?

2024-08-14 07:37 UTC, RoniKishner commented
In theory it sounds good for me, not sure how the CI will react on this though, but give it a try.

2024-08-14 14:34 UTC, mburke5678 commented
@jherrman The changes in the PR look OK to me from a purely docs perspective. Did you address this issue? 

> Okay, that didn't work too well. Would it be okay to leave this PR unmerged

2024-08-14 15:11 UTC, jherrman commented
> @jherrman The changes in the PR look OK to me from a purely docs perspective. Did you address this issue?

Not really. If I change the base branch to 4.15, it adds a whole bunch of commits that create a lot of conflicts, because this was originally branched off the 4.14 branch.

I could try to do the 4.14 -> 4.15 sync and deal with the conflicts locally, or I could start again with branching off 4.15 and create a new PR. However, given the small scope of the changes involved, I think it would be more economical not to merge this PR, and only create the cherry-pick PRs for 4.15 and later, as I suggested to Roni.

2024-09-02 05:30 UTC, jherrman commented
Hi @mburke5678 , do you think it would be possible, then, to close this PR  (because [it turned out it's against an invalid branch](https://issues.redhat.com/browse/CNV-35593?focusedId=25289710&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25289710)) but to create cherry-picks of it to 4.15 and later?

Thanks,
J.

2024-09-04 10:07 UTC, closed without merging

2024-09-04 19:42 UTC, jeana-redhat commented
> Hi @mburke5678 , do you think it would be possible, then, to close this PR (because [it turned out it's against an invalid branch](https://issues.redhat.com/browse/CNV-35593?focusedId=25289710&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25289710)) but to create cherry-picks of it to 4.15 and later?
> 
> Thanks, J.

yep, good call!