Added oc adm drain options for 3.9
openshift/openshift-docs pull request #7881
Opened 2018-02-21 04:34 UTC by ahardin-rh

Added per discussion in https://github.com/openshift/openshift-docs/pull/5709#issuecomment-367043544

@pravisankar PTAL

2018-02-21 19:42 UTC, pravisankar requested changes

2018-02-21 19:42 UTC, pravisankar commented on admin_guide/manage_nodes.adoc
>  $ oc adm drain <node1> <node2>
We are saying 'evacuate all or selected pods' but we are not telling how to do that using a command.
We should talk about `--pod-selector` here and show that as optional param to the command.
```
 $ oc adm drain <node1> <node2> [--pod-selector=<pod_selector>]
```
I've assumed '[ ]' is used for optional flags if that is not the case use what ever convention is used in other places.

2018-02-21 19:42 UTC, pravisankar commented on admin_guide/manage_nodes.adoc
> +You can also use `--pod-selector=<pod>` to filter pods on the node.
This can be skipped if we have already mentioned this option before.

2018-02-22 22:59 UTC, ahardin-rh commented
@pravisankar Thanks! I made some edits. Please let me know if more changes are necessary. Thanks again!

2018-02-22 23:04 UTC, pravisankar approved these changes
LGTM

2018-02-23 19:53 UTC, merged