[SRVCOM-3134] Update API version for connecting-channel-sinks
openshift/openshift-docs pull request #78923
Opened 2024-07-16 09:53 UTC by ochromy

Version(s):
serverless-docs-1.33+

Issue:
https://issues.redhat.com/browse/SRVCOM-3134

Link to docs preview:
FIXME

QE review:
- [ ] QE has approved this change.

2024-07-19 07:35 UTC, maschmid requested changes

2024-07-19 07:35 UTC, maschmid commented on modules/serverless-creating-subscriptions-kn.adoc
> +<1> `--channel` specifies the source for cloud events that should be processed. You must provide the channel name. If you are not using the default `InMemoryChannel` channel that is backed by the `Ch
While `Channel` would be `messaging.knative.dev:v1:Channel` , the `KafkaChannel` is still just `v1beta1`, so this line should stay as it was.

2024-07-19 07:36 UTC, maschmid commented
Hi, the changes in [modules/serverless-creating-subscriptions-yaml.adoc](https://github.com/openshift/openshift-docs/pull/78923/files#diff-ace56381e9f18c030d18eb20534d354033a62fc7797f1c77471d35148dffd3d3) are OK, but the KafkaChannel version change in https://github.com/openshift/openshift-docs/pull/78923/files#diff-d97b7362ba6c02ad7f15ebfb0c940abc44ec2a82629288974758abc58a7df03f  should be reverted.

2024-07-23 07:59 UTC, ochromy commented
/label serverless
/label peer-review-needed

2024-07-23 10:16 UTC, snarayan-redhat reviewed
LGTM!

2024-07-23 10:48 UTC, ochromy commented
/label merge-review-needed

2024-07-23 11:55 UTC, merged