WIP - OADP-4517: Adding Performance Section to OADP docs
openshift/openshift-docs pull request #78956
Opened 2024-07-16 17:40 UTC by anarnold97

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-07-19 13:30 UTC, anarnold97 commented
/label oadp

2024-07-21 13:33 UTC, anarnold97 commented on modules/oadp-1-4-0-performance.adoc
> +|Velero Spec Limits
```suggestion
|Velero spec limits
```

2024-07-21 13:34 UTC, anarnold97 commented on modules/oadp-1-4-0-performance.adoc
> +|ODF ver
```suggestion
|{odf-short} version
```

2024-07-21 13:35 UTC, anarnold97 commented on modules/oadp-1-4-0-performance.adoc
> +|node-agent Spec Limits
```suggestion
|node-agent spec limits
```

2024-07-21 13:36 UTC, anarnold97 commented on modules/oadp-1-4-0-performance.adoc
> +|OCP ver
```suggestion
|OCP version
```

2024-07-22 21:10 UTC, anarnold97 commented on modules/oadp-1-4-0-performance.adoc
> +
```suggestion
[id="oadp-1-4-0-performance-test-cases_{context}"]
== {oadp-short} 1.4.0 performance test cases
```

2024-07-22 21:11 UTC, anarnold97 commented on modules/oadp-1-4-0-performance.adoc
> +
```suggestion
[id="oadp-1-4-0-performance-test-cases_{context}"]
== {oadp-short} 1.4.0 performance test cases
```

2024-08-26 20:31 UTC, anarnold97 commented on backup_and_restore/application_backup_and_restore/oadp-performance/oadp-1-3-performance.adoc
> +[id="oadp-1-3-summary_{context}"]
```suggestion
[id="oadp-1-3-testing-summary_{context}"]
```

2024-08-26 20:31 UTC, anarnold97 commented on backup_and_restore/application_backup_and_restore/oadp-performance/oadp-1-3-performance.adoc
> +
```suggestion
```

2024-08-30 13:41 UTC, weshayutin commented
/hold
The raw data provided by the performance team and now used in this doc needs to be updated to use the correct terms for backup and restore.  There are also some other inconsistencies brought over from the perf tests.  There isn't a rush on this, so lets review this carefully.

2024-09-26 15:32 UTC, anarnold97 commented
@weshayutin - updated

2024-10-07 14:47 UTC, weshayutin commented on modules/oadp-1-3-1-performance-kubevirt.adoc
> +The objective of this test is to test {oadp-first} Backup and restore namespaces with idle big VMS with restic/velero-csi plugins to external NVME storage.
remove line 8.   restic is not a supported option for VMs

2024-10-07 14:49 UTC, weshayutin commented on modules/oadp-1-3-1-performance-kubevirt.adoc
> +|csi & dm
DM ( datamover) is always first a CSI backup.  I see some notes through out that have "dm"  and "csi & dm"  This is the same thing

2024-10-13 14:06 UTC, anarnold97 commented
@weshayutin - please can I give you a nudge about this

thanks

2024-10-21 16:38 UTC, weshayutin commented
thank you @anarnold97 LGTM
/LGTM

2024-10-21 16:38 UTC, weshayutin approved these changes

2024-11-04 14:06 UTC, mpryc commented
@mpryc pls review.

2024-11-18 14:02 UTC, anarnold97 commented
@m0rdechai  - will try this and if you cannot add inline comments, please give me a shout and i will ping the OpenShift docs team as soon as dammit

2025-01-02 13:56 UTC, anarnold97 commented on _topic_maps/_topic_map.yml
> +      File: oadp-1-3-performance
```suggestion
```

2025-01-02 13:59 UTC, anarnold97 commented on modules/oadp-1-4-1-performance.adoc
> +
```suggestion
```

2025-01-03 13:24 UTC, anarnold97 commented
@amastbau & @weshayutin - I do not think this is going to work. What we are getting by way of feedback from Perf & Scale is just not usable, so I propose we close this PR and the associated ticket. In the future, we should only work within agreed parameters where Perf & Scale provide proper summaries for users.

2025-01-03 19:53 UTC, anarnold97 commented on modules/oadp-1-4-data-utilization.adoc
> +:_content-type: CONCEPT
```suggestion
:_mod-docs-content-type: CONCEPT
```

2025-01-03 19:54 UTC, anarnold97 commented on modules/oadp-1-4-0-performance.adoc
> +:_mod-docs-content-type: CONCEPT
```suggestion
:_mod-docs-content-type: REFERENCE
```

2025-01-03 19:55 UTC, anarnold97 commented on modules/oadp-1-4-data-utilization.adoc
> +:_mod-docs-content-type: CONCEPT
```suggestion
:_mod-docs-content-type: REFERENCE
```

2025-01-03 19:57 UTC, anarnold97 commented on modules/oadp-1-4-data-utilization.adoc
> +
```suggestion
```

2025-01-03 19:58 UTC, anarnold97 commented on modules/oadp-1-4-data-utilization.adoc
> +The following shows observed performance when running OADP backup and restore with different plugins in an isolated environment.  Customers' experience using OADP may vary from these results dependin
```suggestion
The following shows observed performance when running OADP backup and restore with different plugins in an isolated environment. Customers' experience using OADP may vary from these results depending on the type of resources in their cluster such as cpu(cores), storage, network and content of the data that is used for backup and restores.  These numbers are not meant as a minimum expected rate but represent transfer rate when performing backup and restores in an isolated environment with optimal conditions and dedicated hardware.
```

2025-01-04 11:33 UTC, anarnold97 commented on modules/oadp-1-4-data-utilization.adoc
> +The following shows observed performance when running OADP backup and restore with different plugins in an isolated environment. Customers' experience using OADP may vary from these results depending
```suggestion
The following is an example of observed performance when running {oadp-short} backup and restore with different plugins in an isolated environment. Customers' experiences with {oadp-short} may differ from these outcomes based on the types of resources in their cluster, including CPU (cores), storage, network, and the content of the data utilized for backup and restores. These numbers are not intended to represent a minimum expected rate, but rather the transfer rate when performing backup and restores in an isolated environment with optimal conditions and dedicated hardware.
```

2025-01-04 11:36 UTC, anarnold97 commented on modules/oadp-1-4-data-utilization.adoc
> +
```suggestion

[id="oadp-1-4-data-utilization-single-backup_{context}"]
```

2025-01-04 11:37 UTC, anarnold97 commented on modules/oadp-1-4-data-utilization.adoc
> +== Backups for single pod and pv
```suggestion
== Backups for single pod and PV
```

2025-01-04 11:38 UTC, anarnold97 commented on modules/oadp-1-4-data-utilization.adoc
> +The following is an example of observed performance when running {oadp-short} backup and restore with different plugins in an isolated environment. Customers' experiences with {oadp-short} may differ
```suggestion
The following is an example of observed performance when running {oadp-short} backup and restore with different plugins in an isolated environment. Your experiences with {oadp-short} may differ from these outcomes based on the types of resources in their cluster, including CPU (cores), storage, network, and the content of the data utilized for backup and restores. These numbers are not intended to represent a minimum expected rate, but rather the transfer rate when performing backup and restores in an isolated environment with optimal conditions and dedicated hardware.
```

2025-01-04 11:40 UTC, anarnold97 commented on modules/oadp-1-4-data-utilization.adoc
> +The calculated throughput rate represents the amount of non-zero data contained in a pv(s), used in the backup or restore process divided by the  time taken to process a backup or restore.
```suggestion
The calculated throughput rate denotes the quantity of non-zero data contained within persistent volumes (PVs) utilized in the backup or restore process, divided by the duration required to process a backup or restore.
```

2025-01-04 11:41 UTC, anarnold97 commented on modules/oadp-1-4-data-utilization.adoc
> +This rate allows customers to understand the performance of OADP.
```suggestion
This rate assists in your understanding of {oadp-short}.
```

2025-02-09 12:29 UTC, anarnold97 commented
@m0rdechai & @weshayutin - please can i give you a nudge about this
Thanks

2025-02-09 19:50 UTC, anarnold97 commented
@weshayutin - honestly i am kind of on the fence
I think we should have a performance section but I think we need a very clear message from Perf and Scale. My reason being that it is hard for docs to know what is applicable. 
We have nice *recommendations* in MTV, see [MTV performance recommendations](https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.7/html-single/installing_and_using_the_migration_toolkit_for_virtualization/index#mtv-performance-recommendation_mtv) but to do this for OADP, we would need more guidance from Perf & Scale and your OK to do something like this. WDYT?

2025-02-10 13:50 UTC, anarnold97 commented
@m0rdechai - please can you take a look at this PR and review. And please can you think on whether you want to keep this or if there is still too much work required

if there is lots of work, please can we close and discuss OADP 1.5.0 and producing a recommendations document for us to include in those docs?

2025-02-16 09:38 UTC, m0rdechai requested changes
I've commented that there are still raw internal test case results included in this document.  These include version matrix info, internal test case names, and test case pass/failure status - this requires clean up in my opinion, but if you feel there's value please feel free to speak with Daniel Gur directly.

2025-02-16 09:38 UTC, m0rdechai commented on modules/oadp-1-4-1-performance.adoc
> +|backup-vbd-datagen-single-ns-100pods-2gb-cephrbd |00:09:20 |00:09:07 |00:08:51
In this section we still have references to 'internal' test case names, the issue is that it wont make sense to users or dev as its currently written.  If we want to include this section then you likely need to change the test case names and have a few sentences explaining what we were testing here.  My only question before providing this details to Andy is does it make sense to have this level of comparison between versions?  If its desired then happy to provide the missing info to convert his test result into a more informative comparison.  Perhaps we can talk about this in office hours or direct meeting or slack.

My personal opinion is that this internal version comparison is not so useful externally, but open to making changes in order to allow it others differ and do find it useful.

2025-02-16 09:38 UTC, m0rdechai commented on modules/oadp-1-4-0-performance.adoc
> +[id="oadp-1-4-0-performance-test-cases_{context}"]
this part of the doc contains more internal test case and scenario information, version matrix covered, specific case information, this is not exposed externally. 

 It also contains test case statuses and shows which cases are marked as 'failed'.  Since we discussed this type of information already and its still part of the docs, if you find it helpful it might be worthwhile to speak with Daniel Gur to see if he agrees with releasing this info as I don't wish to create additional work for anyone in docs but in my opinion remains as before that this type of raw internal test result data should not be exposed externally in the same form that it is shared internally.

2025-03-31 18:30 UTC, closed without merging