CNV-43385: Added networking architecture diagram
openshift/openshift-docs pull request #79229
Opened 2024-07-22 19:35 UTC by sjhala-ccs

Version(s): 4.15+

Issue: CNV-43385

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-07-24 15:17 UTC, phoracek commented on virt/vm_networking/virt-networking-overview.adoc
> +
Suggested text (to explain the basic concepts, but to make sure people understand this is not the only solution we have to offer):

Illustration of a typical network setup of OpenShift Virtualization. Other options are available.

1. Pods and VMs are running on the same network infrastructure, allowing users to easily connect their containerized and virtualized workloads
2. VMs can be connected to the default pod network and to any number of secondary networks
3. The default pod network provides connectivity between all its members, service abstraction, it supports IP management, micro segmentation, and more
4. Multus is a component allowing users to connect to secondary networks
5. The default pod network is overlay-based, tunneled through the underlying machine network
6. The machine network can be defined over a selected set of NICs
7. Secondary VM networks are typically bridged directly to a physical network, with or without VLAN encapsulation
8. Secondary VM networks can be defined on dedicated set of NICs (in the picture) or they can use the machine network

2024-08-02 08:26 UTC, phoracek approved these changes
LGTM, thanks!

2024-08-02 15:37 UTC, lpettyjo reviewed
LGTM!

2024-08-03 15:11 UTC, yossisegev requested changes
From this illustration it looks like the default pod networks goes through the multus CNI, but it doesn't.
@phoracek Please keep me honest here so I won't cause unnecessary confusion.

2024-08-03 20:04 UTC, phoracek commented
Technically it does - Multus is the main CNI, delegating to the default Pod network CNI and secondary CNIs. Although many people take Multus (or Multus networks) as a synonym of secondary networks. I would keep the picture as is.

2024-08-04 05:54 UTC, yossisegev commented
> Technically it does - Multus is the main CNI, delegating to the default Pod network CNI and secondary CNIs. Although many people take Multus (or Multus networks) as a synonym of secondary networks. I would keep the picture as is.

Very well then. So the change LGTM.

2024-08-04 05:55 UTC, yossisegev approved these changes

2024-08-05 12:27 UTC, merged

2024-08-05 12:27 UTC, sjhala-ccs commented
/cherrypick enterprise-4.15

2024-08-05 12:27 UTC, sjhala-ccs commented
/cherrypick enterprise-4.17