Add type to YAML main for Builds
openshift/openshift-docs pull request #79750
Opened 2024-07-31 13:36 UTC by buildbricks

Update binaries and YAML

Version(s):

cherrypick `build-docs-1.1`

Issue:

Link to docs preview:

https://79750--ocpdocs-pr.netlify.app/openshift-builds/latest/work_with_builds/using-builds.html

QE review:
- [x] QE has approved this change.

Additional information:

2024-08-06 11:51 UTC, apoorvajagtap requested changes

2024-08-06 11:51 UTC, apoorvajagtap commented on modules/ob-creating-a-s2i-build.adoc
>      value: quay.io/centos7/nodejs-12-centos7
```suggestion
    value: quay.io/centos7/nodejs-12-centos7:master
```
This image needs the tag.

2024-08-06 11:51 UTC, apoorvajagtap commented on modules/ob-creating-a-s2i-build.adoc
> +    image: quay.io/centos7/nodejs-12-centos7:master <4>
```suggestion
```
- This needs to be kept as it. User is expected to specify the repo as per their need.

2024-08-06 13:51 UTC, apoorvajagtap approved these changes

2024-08-07 08:32 UTC, xenolinux commented
/label peer-review-needed

2024-08-07 08:32 UTC, xenolinux commented
/label peer-review-in-progress

2024-08-07 08:42 UTC, xenolinux reviewed
LGTM

Gentle reminder to squash your commits. 

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

2024-08-09 17:52 UTC, merged

2024-08-09 17:52 UTC, adellape commented
/cherrypick build-docs-1.1