changes
openshift/openshift-docs pull request #80234
Opened 2024-08-08 16:18 UTC by kcarmichael08

Version(s):
4.5+

[Issue](https://issues.redhat.com/browse/ROX-25607)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-09-03 10:42 UTC, ebensh requested changes

2024-09-03 10:42 UTC, ebensh commented on modules/secured-cluster-services-config.adoc
> +a| To provide security at the network level, {product-title-short} creates default `NetworkPolicy` resources in the namespace where secured cluster resources are installed. These network policies all
Sorry for the very late review; the Helm chart value is actually a boolean, with the default being true. You can set it to false to disable writing the network policies. (The Operator part with 'Disabled' and 'Enabled' is correct though).

2024-09-03 10:42 UTC, ebensh commented on modules/central-services-public-config.adoc
> +| Specify if {product-title-short} creates default network policies to allow communication between components. To create your own network policies, set this parameter to `Disabled`.
Same comment here - for the Helm chart it's a boolean, so either true/false.

2024-09-04 20:20 UTC, jeana-redhat approved these changes
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2024-09-05 17:34 UTC, merged

2024-09-05 17:34 UTC, kcarmichael08 commented
/cherrypick rhacs-docs-4.5

2024-09-05 17:34 UTC, kcarmichael08 commented
/cherrypick rhacs-docs-4.6