OCP 4.17 Release Notes for P/Z
openshift/openshift-docs pull request #80276
Opened 2024-08-09 05:39 UTC by alishaIBM

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-09-03 00:03 UTC, prb112 commented on release_notes/ocp-4-17-release-notes.adoc
> +* Compliance Operator DISA-STIG
```suggestion
```

2024-09-03 00:03 UTC, prb112 commented on release_notes/ocp-4-17-release-notes.adoc
> +* Scheduler Plugins
```suggestion
```

2024-09-04 05:43 UTC, alishaIBM commented on release_notes/ocp-4-17-release-notes.adoc
> +* Scheduler Plugins
Ack. Updated the PR.

2024-09-04 05:43 UTC, alishaIBM commented on release_notes/ocp-4-17-release-notes.adoc
> +* Compliance Operator DISA-STIG
Ack. Updated the PR.

2024-09-04 13:13 UTC, SNiemann15 requested changes

2024-09-04 17:02 UTC, SNiemann15 commented on release_notes/ocp-4-17-release-notes.adoc
> +* Scheduler Plugins
This is the correct wording for etcd see https://docs.redhat.com/en/documentation/openshift_container_platform/4.14/html/release_notes/ocp-4-14-release-notes#ocp-4-14-tuning-etcd-latency-tolerances
```suggestion
* Tuning etcd latency tolerances 
```

2024-09-04 17:03 UTC, SNiemann15 commented on release_notes/ocp-4-17-release-notes.adoc
> +* Add cluster-etcd-operator support for additional slower hardware conditions
Verified with Laura, this is the correct wording for etcd see https://docs.redhat.com/en/documentation/openshift_container_platform/4.14/html/release_notes/ocp-4-14-release-notes#ocp-4-14-tuning-etcd-latency-tolerances
```suggestion
* Tuning etcd latency tolerances 
```

2024-09-05 11:47 UTC, prb112 approved these changes
/lgtm

2024-09-12 12:42 UTC, holgwolf commented
LGTM

2024-09-13 05:47 UTC, alishaIBM commented
/label peer-review-needed

2024-09-13 13:59 UTC, lahinson reviewed
Just a couple of minor things to fix. Otherwise, LGTM.

2024-09-13 13:59 UTC, lahinson commented on release_notes/ocp-4-17-release-notes.adoc
> +* Non-volatile Memory Express (NVMe) support for LPAR
```suggestion
* Non-volatile memory express (NVMe) support for LPAR
```

2024-09-13 13:59 UTC, lahinson commented on release_notes/ocp-4-17-release-notes.adoc
> +This release introduces support for the following features on {ibm-power-name}:
```suggestion
This release introduces support for the following features on {ibm-power-title}:
```

2024-09-17 10:39 UTC, alishaIBM commented
@lahinson thank you for the review. I have incorporated the changes.

/label merge-review-needed

2024-09-17 12:56 UTC, bergerhoffer commented
/label merge-review-in-progress

2024-09-17 12:58 UTC, bergerhoffer reviewed
LGTM for merging

2024-09-17 12:58 UTC, merged