OSDOCS-11439: update microshift config defaults
openshift/openshift-docs pull request #80598
Opened 2024-08-16 16:12 UTC by ShaunaDiaz

Version(s):
4.17+

Issue:
[OSDOCS-11439](https://issues.redhat.com/browse/OSDOCS-11439)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-08-16 18:56 UTC, copejon requested changes

2024-08-16 18:56 UTC, copejon commented on modules/microshift-default-settings.adoc
> +        - "" # <23>
```suggestion
storage:
  driver: "" # <22>
  optionalCsiComponents:  # <23>
  - ""
```

2024-08-16 18:56 UTC, copejon commented on modules/microshift-default-settings.adoc
> +<23> Default value is empty. An empty array defaults to deploying `snapshot-controller` and `snapshot-webhook`.Expected values are `csi-snapshot-controller`, `csi-snapshot-webhook`, or `none`. An ent
```suggestion
<23> Array. Default value is null or an empty array. A null or empty array defaults to deploying `snapshot-controller` and `snapshot-webhook`. Expected values are `csi-snapshot-controller`, `csi-snapshot-webhook`, or `none`. An entry of `none` is mutually exclusive with all other values.
```

2024-08-16 18:56 UTC, copejon commented on modules/microshift-default-settings.adoc
> +        - "" # <23>
Moved the number since it's the `optionalCsiComponents` field that's actually being described below.

2024-08-19 07:11 UTC, pmtk commented on modules/microshift-default-settings.adoc
> +<14> Optional parameter for configuring low latency. Default value is null.
```suggestion
<14> Optional parameter for configuring kubelet. Default value is null.
```
Technically someone could configure anything related to kubelet using that field. We don't really want that, but saying it's for "configuring low latency" feels off.

2024-08-19 11:00 UTC, pacevedom commented on modules/microshift-default-settings.adoc
> +<17> A block of virtual IP addresses for Kubernetes services. IP address pool for services. A single entry is supported. This field is immutable after installation.
These two now allow adding one more entry for the other IP family. It is true though that the first entry of the list must remain unchanged.

2024-08-19 20:18 UTC, dhensel-rh commented on modules/microshift-default-settings.adoc
> +<20> The IP address of the node. The default value is the IP address of the default route.
Small nit. Maybe use IPv4 in place of IP here

2024-08-21 18:19 UTC, jneczypor commented
/label peer-review-in-progress

2024-08-21 18:38 UTC, jneczypor reviewed
Just one small change. Otherwise, LGTM.

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2024-08-21 18:38 UTC, jneczypor commented on modules/microshift-default-settings.adoc
> +<14> Parameter for configuring kubelet. Used for low latency configuration. Default value is null.
```suggestion
<14> Parameter for configuring kubelet. Used for low-latency configuration. Default value is null.
```

2024-08-22 10:38 UTC, merged

2024-08-22 10:38 UTC, ShaunaDiaz commented
/cherrypick enterprise-4.17