OCPBUGS-37821: Add section for new roles for short lived credentials
openshift/openshift-docs pull request #80701
Opened 2024-08-20 13:56 UTC by barbacbd

Version(s):

4.17

Issue:

https://issues.redhat.com/browse/OCPBUGS-37821

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

** GCP Short lived credentials does not fill out certain fields in the GCP structure. This causes failures when creating resources such as signed urls. In order to create these resources the user should add the role Service Account User which has the permission "iam.serviceAccounts.signBlob".

2024-08-20 13:56 UTC, barbacbd commented
/cc @bscott-rh

2024-08-20 13:56 UTC, barbacbd commented
/cc @jianli-wei

2024-08-20 14:09 UTC, bscott-rh commented
LGTM from Docs side. the bug says this also applies to 4.15 and 4.16, do you want this picked to those branches as well?

2024-08-29 15:49 UTC, patrickdillon reviewed
The docs also state:
> You must have a service account key or a virtual machine with an attached service account to create the cluster.

Which I think is no longer true, so perhaps we should update that?

Finally, are we able to include the more fine-grained `signBlob` permission rather than the role for the permissions section: https://docs.openshift.com/container-platform/4.16/installing/installing_gcp/installing-gcp-account.html#minimum-required-permissions-ipi-gcp_installing-gcp-account

2024-08-29 15:49 UTC, patrickdillon commented on modules/installation-gcp-permissions.adoc
> +* IAM Service Account User
Does this need more explanation? Technically, I think the requirement is anytime users authenticate with credentials that do not include a service account key.

We have docs on how to create a Service Account for GCP: https://docs.openshift.com/container-platform/4.16/installing/installing_gcp/installing-gcp-account.html#installation-gcp-service-account_installing-gcp-account 

(we also allow authentication without service accounts, via Default Application Credentials, which isn't documented). 

I wonder if we should add a note, perhaps in this section, pointing to this. Perhaps something like:

> If the created service account does not include a key, or you are authenticating via short-lived credentials or Default Application credentials, you must include the roles listed in `Required roles for using short-lived credentials`

2024-09-04 20:01 UTC, bscott-rh commented on modules/installation-gcp-permissions.adoc
> +====
It looks like adding a note in the middle of the list of permissions is breaking something in asciidoc. Can you move this note down a few lines to be right after the `endif::template[]` line? I think you'll need an empty new line before and after the note block.

2024-09-06 17:12 UTC, bscott-rh requested changes

2024-09-06 17:12 UTC, bscott-rh commented on modules/installation-gcp-permissions.adoc
> +If the created service account does not include a key, or you are authenticating via short-lived credentials or Default Application credentials, you must include the roles listed in Required roles fo
```suggestion
If the created service account does not include a key, or you are authenticating using short-lived credentials or Default Application credentials, you must include the roles listed in _Required roles for using short-lived credentials_.
```

2024-09-11 19:12 UTC, bscott-rh approved these changes

2024-09-13 05:25 UTC, jianli-wei requested changes

2024-09-13 05:25 UTC, jianli-wei commented on modules/installation-gcp-permissions.adoc
> +* IAM Service Account User
The "Required roles for the installation program" has listed "Service Account User" role already. Besides, please also take a look at [my comment](https://issues.redhat.com/browse/OCPBUGS-38723?focusedId=25567899&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25567899), thanks!

2024-09-16 16:58 UTC, patrickdillon commented on modules/minimum-required-permissions-ipi-gcp.adoc
> +* `iam.serviceAccounts.signBlob`
`signBlob` is not required for all installations--only when the installer is authenticated without a service account key, which is with Application Default Credentials. So perhaps we want to move this to a permissions section called `Required permissions when authenticating with Application Default Credentials`.

2024-09-16 17:02 UTC, patrickdillon commented on modules/minimum-required-permissions-ipi-gcp.adoc
> +* `iam.serviceAccounts.signBlob`
There may be other methods of authenticating, besides "Application Default Credentials" which do not provide a key, so perhaps we want to call this `Required permissions when authenticating without a service account key"

2024-09-19 08:25 UTC, jianli-wei commented
/label qe-approved

2024-09-19 13:44 UTC, bscott-rh commented
/retest

2024-09-26 13:24 UTC, merged

2024-09-26 13:25 UTC, bscott-rh commented
/cherrypick enterprise-4.16

2024-09-26 13:25 UTC, bscott-rh commented
/cherrypick enterprise-4.17