update jenkins doc for the new jenkins-agent-* images and deprecation…
openshift/openshift-docs pull request #8103
Opened 2018-03-12 16:04 UTC by gabemontero

… of jenkins-slave-maven* and jenkins-slave-nodejs* images

@openshift/sig-developer-experience @bmcelvee ptal

For https://trello.com/c/YQm7osws/1493-5-jenkins-slave-scl-dep-updatesjenkinsintegration

2018-03-12 16:04 UTC, gabemontero commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Jenkins slave SCL dep updates[jenkins_integration]](https://trello.com/c/YQm7osws/1493-5-jenkins-slave-scl-dep-updatesjenkinsintegration)

2018-03-12 16:04 UTC, gabemontero commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Jenkins slave SCL dep updates[jenkins_integration]](https://trello.com/c/YQm7osws/1493-5-jenkins-slave-scl-dep-updatesjenkinsintegration)

2018-03-12 20:04 UTC, bparees requested changes
nits

2018-03-12 20:04 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +jenkins-agent-maven-34-* and jenkins-agent-nodejs-8-* images.
s/34/35/

2018-03-12 20:04 UTC, bparees commented on using_images/other_images/jenkins.adoc
> +jenkins-agent-maven-34-* and jenkins-agent-nodejs-8-* images.
or better, just "jenkins-agent-maven-* and jenkins-agent-nodejs-* images"

2018-03-12 20:04 UTC, bparees commented on using_images/other_images/jenkins_slaves.adoc
> +jenkins-agent-maven-34-* and jenkins-agent-nodejs-8-* images.
"jenkins-agent-maven-* and jenkins-agent-nodejs-* images"

2018-03-12 21:47 UTC, gabemontero commented
update for nits pushed @bparees thanks

2018-03-12 21:48 UTC, bparees commented
lgtm

2018-03-12 22:02 UTC, gabemontero commented
commits squashed

2018-03-12 23:23 UTC, bparees commented
@openshift/team-documentation ptal

2018-03-12 23:55 UTC, vikram-redhat commented
@bmcelvee - PTAL.

2018-03-13 17:03 UTC, bmcelvee commented
Thanks, @gabemontero! LGTM. This is for 3.10, right?

@vikram-redhat, we don't yet have a 3.10 label or branch. Should I hold off on merging until those are available? Thanks!

2018-03-13 17:05 UTC, gabemontero commented
YW @bmcelvee 

And yes, this is for 3.10

2018-03-16 02:03 UTC, vikram-redhat commented
@bmcelvee - yes, sorry no 3.10 branch yet. I have created the 3.10 label though and attached it. 

@gabemontero or @bparees - should it go into the master so it's available upstream in the meantime?

2018-03-16 02:50 UTC, bparees commented
> @gabemontero or @bparees - should it go into the master so it's available upstream in the meantime?

as long as there's no risk it ends up in the v3.9 product docs, yes please.

2018-03-16 19:34 UTC, merged