OSDOCS#10249: Drafted docs for creating a disconnected cluster
openshift/openshift-docs pull request #81456
Opened 2024-09-06 21:45 UTC by EricPonvelle

Version(s):
`enterprise-4.16+`

Issue:
**[OSDOCS-10249](https://issues.redhat.com/browse/OSDOCS-10249)**

Link to docs preview:
- Creating a disconnected ROSA cluster
- Creating a disconnected ROSA cluster - separated HCP distro link

QE review:
- [ ] QE has approved this change.

Additional information:
This PR creates documentation to create a disconnected ROSA cluster.

2024-10-14 14:48 UTC, bergerhoffer commented
The `branch/enterprise-4.18` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.17. And any PR going into `main` must also target the latest version branch (enterprise-4.18).

If the update in your PR does NOT apply to version 4.18 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2024-12-02 21:42 UTC, jneczypor reviewed
Just a few small things.

2024-12-02 21:42 UTC, jneczypor commented on modules/rosa-hcp-sts-creating-a-disconnected-cluster-cli.adoc
> +When using the {product-title} (ROSA) CLI, `rosa`, to create a cluster, you can select the default options to create the cluster quickly.
```suggestion
When using the {product-title} (ROSA) command-line interface (CLI), `rosa`, to create a cluster, you can select the default options to create the cluster quickly.
```

2024-12-02 21:42 UTC, jneczypor commented on modules/rosa-hcp-sts-creating-a-disconnected-cluster-cli.adoc
> +When creating a {hcp-title} cluster, the default machine Classless Inter-Domain Routing (CIDR) is `10.0.0.0/16`. If this does not correspond to the CIDR range for your VPC subnets, add `--machine-cid
```suggestion
When creating a {hcp-title} cluster, the default machine Classless Inter-Domain Routing (CIDR) is `10.0.0.0/16`. If this does not correspond to the CIDR range for your VPC subnets, add `--machine-cidr <address_block>` to the following commands. To learn more about the default CIDR ranges for {product-title}, see the CIDR range definitions.
```

2024-12-02 21:42 UTC, jneczypor commented on modules/rosa-hcp-sts-creating-a-disconnected-cluster-cli.adoc
> +* If you did not set environmental variables, run the following command:
```suggestion
* If you did not set environment variables, run the following command:
```

2024-12-02 21:42 UTC, jneczypor commented on modules/rosa-hcp-sts-creating-a-disconnected-cluster-cli.adoc
> +* If you set the environmental variables, create a disconnected cluster with a single, initial machine pool, using a privately available API, and a privately available Ingress by running the followin
```suggestion
* If you set the environment variables, create a disconnected cluster with a single, initial machine pool, using a privately available API, and a privately available Ingress by running the following command:
```

2024-12-02 21:42 UTC, jneczypor commented on modules/rosa-hcp-sts-creating-a-disconnected-cluster-cli.adoc
> +The following `State` field changes are listed in the output as the cluster installation progresses:
```suggestion
The following `State` field changes are listed in the output as cluster installation progresses:
```

2024-12-02 21:42 UTC, jneczypor commented on modules/rosa-hcp-sts-creating-a-disconnected-cluster-cli.adoc
> +. Track the progress of the cluster creation by watching the {product-title} installation program logs. To check the logs, run the following command:
```suggestion
. Track the cluster creation progress by watching the {product-title} installation program logs. To check the logs, run the following command:
```

2024-12-02 21:42 UTC, jneczypor commented on modules/rosa-hcp-vpc-terraform.adoc
> +<3> CIDR block for your VPC.
```suggestion
<3> Enter the CIDR block for your VPC.
```
Just to match steps 1 and 2

2024-12-02 21:42 UTC, jneczypor commented on modules/rosa-hcp-vpc-terraform.adoc
> +<4> Each of the subnets that are created for the VPC.
```suggestion
<4> Enter each of the subnets that are created for the VPC.
```
Not sure if it should be in present or past tense.

2024-12-02 21:42 UTC, jneczypor commented on rosa_hcp/rosa-hcp-disconnected-install.adoc
> +You can create a fully operational cluster that does not require a public Internet egress by configuring a virtual private cloud (VPC) and using the `--properties zero_egress:true` flag when creating
```suggestion
You can create a fully operational cluster that does not require a public internet egress by configuring a virtual private cloud (VPC) and using the `--properties zero_egress:true` flag when creating your cluster.
```

2024-12-02 21:42 UTC, jneczypor commented on rosa_hcp/rosa-hcp-disconnected-install.adoc
> +* You have installed Terraform v1.4.0+ CLI.
```suggestion
* You have installed the Terraform v1.4.0+ CLI.
```

2024-12-02 21:42 UTC, jneczypor commented on rosa_hcp/rosa-hcp-disconnected-install.adoc
> +* You have installed ROSA v1.2.45+ CLI.
```suggestion
* You have installed the ROSA v1.2.45+ CLI.
```

2024-12-02 21:42 UTC, jneczypor commented on rosa_hcp/rosa-hcp-disconnected-install.adoc
> +You must have a Virtual Private Cloud (VPC) to create {hcp-title} cluster. You can use the following methods to create a VPC:
```suggestion
You must have a Virtual Private Cloud (VPC) to create {hcp-title} clusters. You can use one of the following methods to create a VPC:
```

2024-12-05 17:58 UTC, dustman9000 commented on modules/rosa-hcp-vpc-terraform.adoc
> +$ cd terraform-vpc-example/zero-egress
For some reason I'm not seeing this in the preview: https://81456--ocpdocs-pr.netlify.app/openshift-rosa-hcp/latest/rosa_hcp/rosa-hcp-egress-lockdown-install.html#rosa-hcp-creating-vpc-disconnected-install

2024-12-05 17:59 UTC, dustman9000 commented on rosa_hcp/rosa-hcp-egress-lockdown-install.adoc
> +== Creating a Virtual Private Cloud for your disconected {hcp-title} clusters
```suggestion
== Creating a Virtual Private Cloud for your Egress Lockdown {hcp-title} clusters
```

2024-12-05 18:00 UTC, dustman9000 commented on rosa_hcp/rosa-hcp-egress-lockdown-install.adoc
> +* See the link:https://github.com/openshift-cs/terraform-vpc-example[Terraform VPC] repository for a detailed list of all options available when customizing the VPC for your needs.
This needs to refer to the zero-egress subfolder in this repo if they want to create a VPC without egress.

2024-12-05 18:02 UTC, dustman9000 commented on modules/rosa-hcp-vpc-terraform.adoc
This seems to be missing the steps around the default security group and setting up the privatelink connections for AWS services:
https://access.redhat.com/articles/7090154#create-the-vpc-via-aws-consolecli-4

2024-12-05 18:03 UTC, dustman9000 commented on rosa_hcp/rosa-hcp-egress-lockdown-install.adoc
> +* You have an AWS account with sufficient permissions to create VPCs, subnets, and other required infrastructure.
Also the prereqs for default security groups and vpc privatelink connections setup for AWS services. See: https://access.redhat.com/articles/7090154#create-the-vpc-via-aws-consolecli-4

2024-12-12 22:26 UTC, dustman9000 commented on modules/rosa-hcp-sgs-and-vpce.adoc
> +        --cidr 10.0.0.0/16
Add a note saying "Where 10.0.0.0/16 is the CIDR of your VPC"

2024-12-12 22:27 UTC, dustman9000 commented on modules/rosa-hcp-sgs-and-vpce.adoc
> +$ aws ec2 authorize-security-group-egress \
@hectorakemp - do we still need this wide open like this?

2024-12-12 22:28 UTC, dustman9000 commented on modules/rosa-hcp-sts-creating-a-cluster-egress-lockdown-cli.adoc
> +* You have completed the AWS prerequisites for {hcp-title}.
Add a new bullet that you need to complete the prerequisites for Zero Egress?

2024-12-12 22:34 UTC, dustman9000 commented on modules/rosa-hcp-sgs-and-vpce.adoc
> +        --protocol -1 \
```suggestion
        --protocol https \
```

2024-12-12 22:34 UTC, dustman9000 commented on modules/rosa-hcp-sgs-and-vpce.adoc
> +        --port 0-0 \
```suggestion
        --port 443-443 \
```

2024-12-12 22:35 UTC, dustman9000 commented on modules/rosa-hcp-sgs-and-vpce.adoc
> +    --service-name com.amazonaws.${REGION}.ecr.dkr \
Where `${REGION}` is where your VPC is located.

2024-12-16 13:21 UTC, hectorakemp requested changes
Once all of Dustin's comments are resolved, it looks good to me :+1:

2024-12-17 18:50 UTC, michaelryanpeter commented
/label peer-review-in-progress

2024-12-17 22:21 UTC, michaelryanpeter reviewed
Minor style and asciidoc issues. There are some commands that look like they have some cruft around user-supplied variables that either need to be cleaned up or, if they are environment variables, they need callouts.

One question, I noticed in comment zero that egress lockdown is the AWS/ROSA term for a disconnected cluster. Since we use the term disconnected throughout our docs, do you think it is worthwhile working it into the abstracts of the modules and maybe the title of the assembly?

/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed

2024-12-17 22:21 UTC, michaelryanpeter commented on modules/rosa-hcp-sgs-and-vpce.adoc
> +        --vpc-id $VPC_ID
```suggestion
        --vpc-id <vpc_id>
```
`$VPC_ID` looks like a variable name. If this is a user replaced variable, it should be `<vpc_id>`. If this is part of the script mentioned earlier, I think you should use a callout to explain that this value is related to the script run earlier and that it must be done this way.

Does that make sense?

2024-12-17 22:21 UTC, michaelryanpeter commented on modules/rosa-hcp-sgs-and-vpce.adoc
> +    --service-name com.amazonaws.${REGION}.s3
See my previous comment. I suspect that all of the instances of `${REGION}.s3` and `$VPC_ID` should be `<region>` or `<vpc_id>`, respectively. Again, if this is not the case and the customer should enter these exact values due to the script mentioned in the first module of the assembly or some sort of environment variable, I think that should be called out.

2024-12-18 20:03 UTC, jneczypor reviewed
Added a few tiny, small, tiny things.

2025-01-17 20:13 UTC, merged

2025-01-17 20:13 UTC, EricPonvelle commented
/cherrypick enterprise-4.17

2025-01-17 20:13 UTC, EricPonvelle commented
/cherrypick enterprise-4.18