OSDOCS-11732: Add dummy device as additional network
openshift/openshift-docs pull request #81643
Opened 2024-09-11 18:02 UTC by jab-rh

- https://issues.redhat.com/browse/OSDOCS-11732

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-09-12 03:40 UTC, jab-rh commented
@dougbtv, I've added the `dummy` device to the additional networks configuration page. What do you think? Thanks!

2024-09-13 18:34 UTC, dougbtv commented on modules/nw-multus-dummy-device-object.adoc
> +|The value for the `name` parameter you provided previously for the CNO configuration.
This is arbitrary but I think the recommended value is useful (as it may appear this way in logging), nicely done.

2024-09-13 18:37 UTC, dougbtv requested changes

2024-09-17 19:55 UTC, jab-rh commented on modules/nw-multus-dummy-device-object.adoc
> +
@dougbtv, perfect, thanks!

2024-09-18 09:47 UTC, agantony commented
/label peer-review-in-progress

2024-09-18 10:25 UTC, agantony reviewed
Added a few suggestions for your consideration; overall lgtm!

2024-09-18 10:25 UTC, agantony commented on modules/nw-multus-dummy-device-object.adoc
> +The dummy CNI plugin functions like a loopback device. The plugin is a virtual interface that allows packets to be routed to a designated IP address. Unlike loopback, the IP address can be arbitrary
```suggestion
The dummy CNI plugin functions like a loopback device. The plugin is a virtual interface. You can use the plugin to route the packets to a designated IP address. Unlike a loopback device, the IP address is arbitrary and is not restricted to the `127.0.0.0/8` address range.
```

2024-09-18 10:25 UTC, agantony commented on modules/nw-multus-dummy-device-object.adoc
> +The dummy CNI plugin functions like a loopback device. The plugin is a virtual interface that allows packets to be routed to a designated IP address. Unlike loopback, the IP address can be arbitrary
https://www.ibm.com/docs/en/ibm-style?topic=word-usage#:~:text=Use%20uppercase.-,allow%20verb,-Avoid%20stating%20that

2024-09-18 10:25 UTC, agantony commented on modules/nw-multus-dummy-device-object.adoc
> +|The CNI specification version. The `0.3.1` value is required.
```suggestion
|The CNI specification version. The required value is `0.3.1`.
```

2024-09-18 10:25 UTC, agantony commented on modules/nw-multus-dummy-device-object.adoc
> +|The value for the `name` parameter you provided previously for the CNO configuration.
```suggestion
|The value for the `name` parameter that you previously specified for the CNO configuration.
```

2024-09-18 10:25 UTC, agantony commented on modules/nw-multus-dummy-device-object.adoc
> +|The name of the CNI plugin to configure: `dummy`.
```suggestion
|The name of the CNI plugin that you want to configure. The required value is `dummy`.
```

2024-09-18 10:25 UTC, agantony commented on modules/nw-multus-dummy-device-object.adoc
> +|The configuration object for the IPAM CNI plugin. The plugin manages IP address assignment for the attachment definition.
```suggestion
|The configuration object for the IPAM CNI plugin. The plugin manages the IP address assignment for the attachment definition.
```

2024-09-18 10:25 UTC, agantony commented on modules/nw-multus-dummy-device-object.adoc
> +|The configuration object for the IPAM CNI plugin. The plugin manages IP address assignment for the attachment definition.
Expand IPAM?

2024-09-18 10:25 UTC, agantony commented on modules/nw-multus-dummy-device-object.adoc
> +== dummy configuration example
```suggestion
== Dummy configuration example
```

2024-09-18 10:25 UTC, agantony commented
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2024-09-30 17:49 UTC, kalexand-rh commented
The `branch/enterprise-4.18` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.17. And any PR going into `main` must also target the latest version branch (enterprise-4.18).

If the update in your PR does NOT apply to version 4.18 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2024-11-12 14:06 UTC, weliang1 commented
/lgtm

2025-02-24 19:15 UTC, bergerhoffer commented
The `branch/enterprise-4.19` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.18. And any PR going into `main` must also target the latest version branch (enterprise-4.19).

If the update in your PR does NOT apply to version 4.19 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2025-06-03 00:57 UTC, merged

2025-06-03 00:57 UTC, jab-rh commented
/cherry-pick enterprise-4.19