OCPBUGS-37081: Added OVN RN update
openshift/openshift-docs pull request #81666
Opened 2024-09-12 09:51 UTC by dfitzmau

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-09-12 11:55 UTC, sreber84 commented
/lgtm

2024-09-12 12:49 UTC, ricky-rav requested changes
A little type in the title, other than that all good! :)

2024-09-12 12:49 UTC, ricky-rav commented on release_notes/ocp-4-14-release-notes.adoc
> +==== Change in the IP address ranged that Open Virtual Network Infrastructure Controller uses
`range`

2024-09-12 12:54 UTC, dfitzmau commented on release_notes/ocp-4-14-release-notes.adoc
> +==== Change in the IP address ranged that Open Virtual Network Infrastructure Controller uses
:heavy_check_mark:

2024-09-12 12:57 UTC, dfitzmau commented
/label peer-review-needed

2024-09-12 12:58 UTC, ricky-rav approved these changes
LGTM
Thanks, Darragh!

2024-09-13 17:17 UTC, anuragthehatter commented
For 4.14.0 this looks good but we just backported changes allowing these values to be configurable https://issues.redhat.com/browse/OCPBUGS-41360

Now I am thinking we might need to mention them like those are configurable in 4.14z and 4.15 z as well.
@dfitzmau Not sure if you can help with that or someone already on it


Also good to mention IPv6 reserved range as well as more and more customers are now trying IPv6?
Equivalent IPv6 ranges can be referred from https://github.com/openshift/ovn-kubernetes/blob/master/contrib/kind.sh#L553

2024-09-18 13:25 UTC, anuragthehatter commented
As discussed with @dfitzmau regarding z stream notes 

/lgtm

2024-09-18 13:35 UTC, merged