RHDEVDOCS#6145: Replaced specific task name and namespace name with placeholders for clarity
openshift/openshift-docs pull request #81790
Opened 2024-09-13 11:31 UTC by kalyaniverma

This PR replaces specific task names and namespace names with placeholders in the Task run commands for better clarity

No new information is added. Therefore, no QE review is necessary.

Version(s):

Issue:
- [RHDEVDOCS-6145](https://issues.redhat.com/browse/RHDEVDOCS-6145)

Link to docs preview:
- [Task run Command Documentation Preview](https://github.com/kalyaniverma/openshift-docs/blob/773850841296a4796727a9d52f6b9f9715926523/modules/op-tkn-task-run.adoc)

QE review:
- [ ] **Not required** (no changes impacting functionality)

Additional information:

2024-09-16 09:27 UTC, Srivaralakshmi commented
/ok-to-test

2024-09-19 10:52 UTC, eromanova97 requested changes
Hello @kalyaniverma I added two comments, for line 19 and 63 that need to be edited. The rest looks good.

However, there is one more issue, I notice you created your feature branch against `pipelines-docs-1.15`, it needs to be created against `pipelines-docs-main`. So you will have to create a new feature branch against the right branch and raise a new PR again. Please also incorporate the feedback I left.

Thank you! :slightly_smiling_face:

2024-09-19 10:52 UTC, eromanova97 commented on modules/op-tkn-task-run.adoc
>  .Example: Cancel the `mytaskrun` task run from a namespace
```suggestion
.Example: Cancel a task run from a namespace
```

2024-09-19 10:52 UTC, eromanova97 commented on modules/op-tkn-task-run.adoc
Change a line 63 from:
```
.Example: Display live logs for the `mytaskrun` task run in a namespace
```

to:
```
.Example: Display live logs for a task run in a namespace
```

2024-09-24 10:53 UTC, Srivaralakshmi commented
Good job! I have a suggestion about the content type attribute. Please implement the suggestion given.

After L2, leave a line. Before L4, add this attribute:
:_mod-docs-content-type: REFERENCE

For more information, see: https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#content-type-attributes and https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#module-file-metadata.

Thanks, @kalyaniverma.

2024-10-01 05:40 UTC, closed without merging