OSDOCS-12075 adding GCP N4 Machine series release note
openshift/openshift-docs pull request #82300
Opened 2024-09-23 19:18 UTC by bscott-rh

Version(s):
4.17

Issue:
https://issues.redhat.com/browse/OSDOCS-12075

Link to docs preview:

QE review:
- [ ] QE has approved this change.

2024-09-23 19:19 UTC, bscott-rh commented
@jianli-wei PTAL at this RN for GCP N4 machine series for 4.17. I am creating a separate PR to add the `hyperdisk-balanced` disk type to the main documentation.

2024-09-24 02:13 UTC, jianli-wei requested changes

2024-09-24 02:13 UTC, jianli-wei commented on release_notes/ocp-4-17-release-notes.adoc
> +With this release, you can deploy a cluster on {gcp-short} using the link:https://cloud.google.com/compute/docs/general-purpose-machines#n4_series[N4 machine series] for compute or control plane mach
The supported disk type of **N4** machine series is `hyperdisk-balanced` instead, thanks!

2024-09-24 14:32 UTC, lpettyjo reviewed
LGTM!

2024-09-24 15:47 UTC, merged