OCPBUGS-34995-FIZX: Updated the Expanding the node port range doc for…
openshift/openshift-docs pull request #82695
Opened 2024-09-30 11:44 UTC by dfitzmau

… range

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-10-01 08:38 UTC, hideshi3 commented
@dfitzmau 
Thank you for creating the PR. However, I don't understand why you are making these changes.
First, please tell me the following. Are you A or B?

A. You are trying to fix the documentation from the standpoint that Red Hat does NOT allow and support customers setting the starting port to a value smaller than 3000.

B. You are trying to fix the documentation from the standpoint that Red Hat allows and supports customers setting the starting port to a value smaller than 30000.


A. If you were in A's position, I think that most of the documents you have revised should be reverted, and a note should be added to the effect that
   "setting the starting port to a value less than 30000 is not supported".


B. If you were in B's position, you would have to change some parts to make it a logical explanation.
===============================
```
> Replace <port> with the largest port number in the new range.

  => Replace <smallest-port> with the smallest port number and <largeest-port> with the largest port number in the new range.

>      { "serviceNodePortRange": "29000-32768" }

  =>   { "serviceNodePortRange": "<smallest-port>-<largest-port>" }      

>  serviceNodePortRange: "29000-32768"

  => serviceNodePortRange: "<smallest-port>-<largest-port>"

> "service-node-port-range":["29000-32768"]

  => "service-node-port-range":["29000-33000"]

> The default port range is 29000-32768.

   => The default port range is 30000-32767

> For example, if you expand the node port range to `30000-32900`, the inclusive port range of `29000-32768` must ...

  => For example, if you expand the node port range to `29000-32900`, the inclusive port range of `29000-29999` and `32768-32900` must ...
```
===============================
Also, I think you should include some Notice about the range of possible changes to the starting port.
This is because customers may misunderstand that it is possible to change the default '30000-32767' to something like '10-34000'.

2024-10-17 11:55 UTC, dfitzmau commented on modules/nw-nodeport-service-range-edit.adoc
> +* Expand the range for the `serviceNodePortRange` parameter in the `network.config.openshift.io` object that your cluster uses to manage traffic for pods, by entering the following command in your co
Is a cluster restart needed when the port range is changed?

2024-10-17 14:52 UTC, knobunc commented
@hideshi3 customers can change the range to 10-34000.  The PR is trying to clarify the original docs, but they were not inaccurate.  They were talking about reducing the range, not reducing the start port of the range.

As long as the new port range completely includes the old, then the change is valid.  There is no limit to the lower bound (either in OpenShift or upstream Kubernetes).  BUT it would be inadvisable to lower it to 10 since there may be well-known services running on the host that need ports > 10 (e.g. ssh on port 22) or pods that run in host network mode (e.g. the router running on 443).  We should not that in the docs.

2024-10-17 15:04 UTC, knobunc requested changes
I think you also want to add a section saying that the cluster admin should ensure that the port range used does not overlap with ports used by any host processes.  And mention that this is a one-way operation.  If you change the range there is no way to change it back.

2025-02-24 19:12 UTC, bergerhoffer commented
The `branch/enterprise-4.19` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.18. And any PR going into `main` must also target the latest version branch (enterprise-4.19).

If the update in your PR does NOT apply to version 4.19 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2025-06-16 18:51 UTC, bergerhoffer commented
The `branch/enterprise-4.20` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.19. And any PR going into `main` must also target the latest version branch (enterprise-4.20).

If the update in your PR does NOT apply to version 4.20 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2025-06-18 01:03 UTC, hideshi3 commented
LGTM

2025-06-18 14:45 UTC, knobunc commented
/lgtm

2025-06-18 18:31 UTC, cbippley commented
/label peer-review-in-progress
/remove-label peer-review-needed

2025-06-18 18:45 UTC, cbippley reviewed
Couple nits for clarity. LGTM!

2025-06-18 18:45 UTC, cbippley commented on modules/nw-nodeport-service-range-edit.adoc
> +Before you expand a node port range, consider that Red{nbsp}Hat has not performed testing outside the default port range of `30000-32768`. For ranges outside the default port range, ensure that you t
```suggestion
Before you expand a node port range, consider that Red{nbsp}Hat has not performed testing outside the default port range of `30000-32768`. For ranges outside the default port range, ensure that you test to verify the expanding node port range does not impact your cluster. If you expanded the range and a port allocation issue occurs, create a new cluster and set the required range for it. 
```

2025-06-18 18:45 UTC, cbippley commented on modules/nw-nodeport-service-range-edit.adoc
> +* To confirm a successful configuration, enter the following command. The command can take several minutes for the update to apply.
```suggestion
* To confirm a successful configuration, enter the following command. The update can take several minutes to apply. 
```

2025-06-18 18:45 UTC, cbippley commented on networking/configuring-node-port-service-range.adoc
> +During cluster installation, you can set the node port range to a range meets the needs of your cluster. Only a cluster administrator can change the range by expanding the range as a postinstallation
```suggestion
During cluster installation, you can set the node port range to a range meets the needs of your cluster. Only a cluster administrator can change the range by expanding the range as a postinstallation task. If your cluster uses a large number of node ports, consider increasing the number of available ports for your cluster.
```

2025-06-18 18:45 UTC, cbippley commented on networking/configuring-node-port-service-range.adoc
> +Before you expand a node port range, consider that Red{nbsp}Hat has not performed testing outside the default port range of `30000-32768`. For ranges outside the default port range, ensure that you t
```suggestion
Before you expand a node port range, consider that Red{nbsp}Hat has not performed testing outside the default port range of `30000-32768`. For ranges outside the default port range, ensure that you test to verify the expanding node port range does not impact your cluster. If you expanded the range and a port allocation issue occurs, create a new cluster and set the required range for it. 
```

2025-06-18 18:45 UTC, cbippley commented
/label peer-review-done
/remove-label peer-review-in-progress

2025-06-19 08:59 UTC, gangwgr commented on networking/configuring-node-port-service-range.adoc
> +During cluster installation, you can set the node port range to a range meets the needs of your cluster. Only a cluster administrator can change the range by expanding the range as a postinstallation
During cluster installation, you can configure the node port range to meet your cluster's requirements. After installation, only a cluster administrator can expand the range as a postinstallation task. If your cluster uses a large number of node ports, consider increasing the available port range accordingly.

2025-06-19 09:05 UTC, gangwgr commented on networking/configuring-node-port-service-range.adoc
> +If you expand the node port range and {oc-first} stops working because the OpenShift API server
If you expand the node port range and {oc-first} stops working due to a port conflict with the OpenShift API server, you must create a new cluster.  
Ensure that the new node port range does not overlap with any ports already in use by host processes or pods configured with host networking.

2025-06-19 09:31 UTC, dfitzmau commented on networking/configuring-node-port-service-range.adoc
> +During cluster installation, you can set the node port range to a range meets the needs of your cluster. Only a cluster administrator can change the range by expanding the range as a postinstallation
:heavy_check_mark:

2025-06-19 09:31 UTC, dfitzmau commented on networking/configuring-node-port-service-range.adoc
> +If you expand the node port range and {oc-first} stops working because the OpenShift API server
:heavy_check_mark:

2025-06-19 09:34 UTC, gangwgr commented
seems ok to me
lgtm

2025-06-23 12:06 UTC, everettraven approved these changes
/lgtm

2025-06-23 12:51 UTC, merged

2025-06-23 12:51 UTC, dfitzmau commented
/cherrypick enterprise-4.20
/cherrypick enterprise-4.19

2025-06-23 12:52 UTC, dfitzmau commented
/cherrypick enterprise-4.20

2025-06-23 12:52 UTC, dfitzmau commented
/cherrypick enterprise-4.19

2025-06-23 12:52 UTC, dfitzmau commented
/cherrypick enterprise-4.18

2025-06-23 12:52 UTC, dfitzmau commented
/cherrypick enterprise-4.17

2025-06-23 12:52 UTC, dfitzmau commented
/cherrypick enterprise-4.16

2025-06-23 12:52 UTC, dfitzmau commented
/cherrypick enterprise-4.15

2025-06-23 12:52 UTC, dfitzmau commented
/cherrypick enterprise-4.14

2025-06-23 12:52 UTC, dfitzmau commented
/cherrypick enterprise-4.13

2025-06-23 12:52 UTC, dfitzmau commented
/cherrypick enterprise-4.12