bugfix: inconsistent install methods content cross-vendor
openshift/openshift-docs pull request #83385
Opened 2024-10-11 14:20 UTC by sean-freeman

Installation Methods page is inconsistent across infrastructure platform vendors. This uses the new structure found in AWS and MS Azure content, removing the duplicated prerequisite content found at the start of each `/installing/installing_<<platform>>/installing_*.adoc` file.

The change cannot be immediately applied to the following, as the file also contains other preparation content / the content file structure is too different:
- `installing/installing_nutanix/preparing-to-install-on-nutanix.adoc`
- `installing/installing_openstack/preparing-to-install-on-openstack.adoc`
- `installing/installing_sno/install-sno-preparing-to-install-sno.adoc`

Version(s):
4.17, do not cherry pick as this file is likely to have changed between each version

Issue:
- None (GH or Jira), this is community author contribution

QE review:
- [ ] QE has approved this change.

Additional information:
- n/a

2024-10-11 14:21 UTC, sean-freeman commented
@kalexand-rh @bscott-rh @sheriff-rh Mentioning you all, as GH Issue template requests @openshift/team-documentation [which does not work] is mentioned after PR is raised.

2024-10-21 15:29 UTC, sean-freeman commented
@kalexand-rh @bscott-rh @sheriff-rh Can you please review this PR? I would prefer to avoid merge conflicts which is more likely the longer this PR is open.

2024-10-24 16:03 UTC, bscott-rh requested changes

2024-10-24 16:03 UTC, bscott-rh commented on installing/installing_gcp/preparing-to-install-on-gcp.adoc
Please remove this change as a GCP reorganization is ongoing

2024-10-24 16:03 UTC, bscott-rh commented on installing/installing_ibm_cloud/preparing-to-install-on-ibm-cloud.adoc
Why are you deleting all of this content? Is it being re-added somewhere else?

2024-10-24 20:36 UTC, sean-freeman commented on installing/installing_ibm_cloud/preparing-to-install-on-ibm-cloud.adoc
Content is removed, so as to match `Installation methods` template for AWS/AZ and remove the duplicated content - as descsribed in PR body.

Removed content:
https://docs.openshift.com/container-platform/4.17/installing/installing_ibm_cloud/preparing-to-install-on-ibm-cloud.html#prerequisites_preparing-to-install-on-ibm-cloud

`Prerequisites` Content at beginning of each `installing*.adoc` file for the vendor:
- https://docs.openshift.com/container-platform/4.17/installing/installing_ibm_cloud/installing-ibm-cloud-customizations.html#prerequisites_installing-ibm-cloud-customizations
- https://docs.openshift.com/container-platform/4.17/installing/installing_ibm_cloud/installing-ibm-cloud-network-customizations.html#prerequisites_installing-ibm-cloud-network-customizations
- https://docs.openshift.com/container-platform/4.17/installing/installing_ibm_cloud/installing-ibm-cloud-vpc.html#prerequisites_installing-ibm-cloud-vpc
- https://docs.openshift.com/container-platform/4.17/installing/installing_ibm_cloud/installing-ibm-cloud-private.html#prerequisites_installing-ibm-cloud-private
- https://docs.openshift.com/container-platform/4.17/installing/installing_ibm_cloud/installing-ibm-cloud-restricted.html#prerequisites_installing-ibm-cloud-restricted

2024-10-24 20:37 UTC, sean-freeman commented on installing/installing_gcp/preparing-to-install-on-gcp.adoc
Will be done as requested

2024-10-27 23:53 UTC, sean-freeman commented on installing/installing_gcp/preparing-to-install-on-gcp.adoc
Done

2024-10-29 12:42 UTC, sean-freeman commented on installing/installing_ibm_cloud/preparing-to-install-on-ibm-cloud.adoc
@bscott-rh see above that shows pre-req content at top of each `installing-` file, can this PR merge please?

2024-10-29 13:42 UTC, bscott-rh commented
/ok-to-test

2024-10-29 15:02 UTC, sean-freeman commented
/retest

2024-11-04 20:16 UTC, sean-freeman commented
@bscott-rh This passes the tests last week and resolves content structure issues. Can this please merge?

2024-11-05 20:47 UTC, merged

2024-11-05 20:47 UTC, bscott-rh commented
/cherrypick enterprise-4.17

2024-11-05 20:47 UTC, bscott-rh commented
/cherrypick enterprise-4.18