OCPBUGS-38689: Add section for xpn deletion permissions
openshift/openshift-docs pull request #83469
Opened 2024-10-14 20:10 UTC by barbacbd

OCPBUGS-38689: Add section for xpn deletion permissions

Version(s):

4.18, 4.17

Issue:

https://issues.redhat.com/browse/OCPBUGS-38689

Link to docs preview:
https://83469--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-account.html#minimum-required-permissions-ipi-gcp-xpn_installing-gcp-account

QE review:
- [x] QE has approved this change.

Additional information:

The docs leave out the permissions for deleting firewalls in a gcp xpn install. The section is added to include the 3 permissions to do so.

2024-10-14 20:11 UTC, barbacbd commented
/cc @bscott-rh

2024-10-14 20:41 UTC, bscott-rh commented
LGTM from docs perspective

2024-10-14 20:41 UTC, bscott-rh approved these changes

2024-10-16 05:50 UTC, jianli-wei requested changes

2024-10-16 05:50 UTC, jianli-wei commented on modules/minimum-required-permissions-ipi-gcp-xpn.adoc
> +====
The required permissions are `compute.firewalls.delete` and `compute.networks.updatePolicy` instead (see below for example).

FYI the custom role in the QE's host project for that purpose: 
```
$ gcloud iam roles describe --project openshift-qe-shared-vpc compute.firewalls.delete_compute.networks.updatePolicy
description: permissions of deleting firewall rules and update network policy
etag: BwYi1WE_uEs=
includedPermissions:
- compute.firewalls.delete
- compute.networks.updatePolicy
name: projects/openshift-qe-shared-vpc/roles/compute.firewalls.delete_compute.networks.updatePolicy
stage: ALPHA
title: compute.firewalls.delete_compute.networks.updatePolicy
$

2024-10-16 05:52 UTC, jianli-wei commented
> Version(s):
> 4.18, 4.17, 4.16, 4.15

The bug is for 4.17+, so the versions shall be "4.18, 4.17" instead. Thanks!

2024-10-18 17:09 UTC, bscott-rh approved these changes

2024-10-23 05:55 UTC, jianli-wei requested changes

2024-10-28 01:49 UTC, jianli-wei commented on modules/minimum-required-permissions-ipi-gcp-xpn.adoc
> +.Required permissions for destroying firewalls in the host project
@barbacbd Any updates? Thanks!

2024-10-30 10:52 UTC, barbacbd commented on modules/minimum-required-permissions-ipi-gcp-xpn.adoc
> +.Required permissions for destroying firewalls in the host project
Fixed/Updated.

2024-10-31 01:32 UTC, jianli-wei commented
/label qe-approved

2024-10-31 14:33 UTC, merged

2024-10-31 14:33 UTC, bscott-rh commented
/cherrypick enterprise-4.17

2024-10-31 14:33 UTC, bscott-rh commented
/cherrypick enterprise-4.18