OSDOCS#38575: Added inferFromVolume to creating VMs from container disks
openshift/openshift-docs pull request #84294
Opened 2024-10-31 14:04 UTC by jherrman

Version(s):
4.17 and later

Issue:
https://issues.redhat.com/browse/CNV-38575

Link to docs preview:
TBA

QE review:
- [ ] QE has approved this change.

2024-10-31 14:44 UTC, dominikholler commented
The usage on commandline improved significantly recently.
Let's work with @0xFelix to let this file reflect the current state.

2024-11-07 09:08 UTC, 0xFelix reviewed
Looking at it, I noticed the items 1-3 in the Procedure section are now also obsolete.

2024-11-07 18:51 UTC, jherrman commented
@0xFelix , just to make sure, do you mean that creating a `Secret` manifest and making a config map for communicating to systems with self-signed certificates are no longer needed to create a VM from a container disk, or do you mean that different steps are needed for those than what the documentation currently describes?

Cheers,
J.

2024-11-08 09:42 UTC, 0xFelix commented
They are not needed with the new VM manifest. The new manifests clones the `rhel9` DataSource, which is available in every cluster without specifying any additional credentials or certificates.

2024-11-08 18:37 UTC, jherrman commented
Thank you for the clarification Felix! I've removed the steps, and I'm moving the ticket to QE review.

Thanks again for your help,
J.

2024-11-18 12:42 UTC, RoniKishner requested changes

2024-11-18 12:42 UTC, RoniKishner commented on modules/virt-creating-vm-import-cli.adoc
> +        name: rhel9
The namespace might be needed here
```suggestion
      sourceRef:
        kind: DataSource
        name: rhel9
        namespace: openshift-virtualization-os-images
```

2024-11-18 12:42 UTC, RoniKishner commented on modules/virt-creating-vm-import-cli.adoc
> +          name: datavolumedisk1
Should be same as `dataVolumeTemplates` name
```suggestion
          name: rhel-dv <2>
```

2024-11-18 17:49 UTC, RoniKishner commented
/lgtm

2024-11-19 10:52 UTC, snarayan-redhat reviewed
LGTM!

2024-11-19 12:29 UTC, jherrman commented
/label merge-review-needed

2024-11-19 14:44 UTC, RoniKishner approved these changes

2024-11-19 20:21 UTC, merged

2024-11-19 20:21 UTC, skrthomas commented
/cherrypick enterprise-4.17