OSDOCS-12552 Wrong SLA link in Service Definition
openshift/openshift-docs pull request #84479
Opened 2024-11-05 13:33 UTC by xJustin

Fixed inaccurate link in the Support section of the service def pionting to SLA. 

Version(s):
4.17+
Issue:
https://issues.redhat.com/browse/OSDOCS-12552

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-11-05 14:18 UTC, michaelryanmcneill requested changes

2024-11-05 14:18 UTC, michaelryanmcneill commented on modules/rosa-sdpolicy-am-support.adoc
> +See {product-title} link:https://access.redhat.com/support/offerings/production/sla[SLAs] for support response times.
Suggested change:
> See Red Hat's [Production Support Terms of Service](https://access.redhat.com/support/offerings/production/sla) for support response times.

2024-11-05 14:46 UTC, michaelryanmcneill approved these changes
/lgtm

2024-11-05 14:49 UTC, xJustin commented
/label peer-review-needed

2024-11-05 15:09 UTC, tmalove commented
/remove-label peer-review-needed
/label peer-review-in-progress

2024-11-06 00:10 UTC, michaelryanmcneill commented
@tmalove did you happen to complete your peer review?

2024-11-06 00:19 UTC, wanghaoran1988 commented
/lgtm

2024-11-06 18:57 UTC, michaelryanmcneill commented
Not sure what happened but moving this back to the peer review queue. 

/remove-label peer-review-in-progress
/label peer-review-needed

2024-11-06 19:03 UTC, tmalove commented
/remove-label peer-review-needed
/label peer-review-in-progress

2024-11-06 19:14 UTC, tmalove commented
/remove-label peer-review-in-progress
/label peer-review-done
/lgtm

2024-11-06 19:16 UTC, xJustin commented
/label merge-review-needed

2024-11-06 19:51 UTC, bmcelvee commented
LGTM!

2024-11-06 19:53 UTC, merged

2024-11-06 19:53 UTC, bmcelvee commented
/cherrypick enterprise-4.17

2024-11-06 19:53 UTC, bmcelvee commented
/cherrypick enterprise-4.18