RHDEVDOCS 6263 Release notes for Pipelines 1.16.1
openshift/openshift-docs pull request #84654
Opened 2024-11-07 22:12 UTC by mramendi

Version(s):

cp to pipelines-docs-1.16

Issue:

RHDEVDOCS 6263 

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-11-07 22:12 UTC, mramendi commented
https://issues.redhat.com/browse/RHDEVDOCS-6263

2024-11-08 02:16 UTC, khrm reviewed
LGTM

2024-11-08 04:50 UTC, lokanandaprabhu requested changes

2024-11-08 04:50 UTC, lokanandaprabhu commented on modules/op-release-notes-1-16.adoc
> +* Before this update, when you used the web console to start a pipeline or task that defined a parameter of the type `array`, the web console reported an error when yiou entered the value for the par
```suggestion
* Before this update, when you used the web console to start a pipeline or task that defined a parameter of the type `array`, the web console reported an error when you entered the value for the parameter and you could not start the pipeline or task. With this update, you can use the web console to start a pipeline or task that defines a parameter of the type `array` and entering a value for this parameter works normally.
```

2024-11-08 04:50 UTC, lokanandaprabhu commented on modules/op-release-notes-1-16.adoc
> +* Before this update, when viewing information from {tekton-results} in the web console, if the information was displayed in multiple pages, some of the information was not displayed. With this updat
```suggestion
* Before this update, when viewing information from {tekton-results} in the web console, if user scrolled down to the bottom, the next set of records was not fetched, causing some of the information was not displayed. With this update, as user scroll down to the bottom, records from {tekton-results} load correctly, ensuring all information displays correctly in the web console.
```

2024-11-08 08:09 UTC, ppitonak approved these changes

2024-11-08 11:37 UTC, mramendi commented
/label peer-review-needed

2024-11-08 11:58 UTC, lokanandaprabhu approved these changes

2024-11-08 11:58 UTC, lokanandaprabhu commented
/lgtm

2024-11-08 12:01 UTC, abhatt-rh commented
/label peer-review-in-progress

2024-11-08 12:31 UTC, abhatt-rh reviewed
Hi @mramendi 
Mostly LGTM! Added some wording-related comments for your consideration.

Also, adding a reminder to squash your commits to one before requesting a merge review 

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2024-11-08 12:31 UTC, abhatt-rh commented on modules/op-release-notes-1-16.adoc
> +* Before this update, when you used the web console to start a pipeline or task that defined a parameter of the type `array`, the web console reported an error when you entered the value for the para
took a shot at rewording it for clarity. What do you think?
```suggestion
* Before this update, you could not use the web console to start a pipeline or task that defined a parameter of the type `array` and entering a value for this parameter resulted in an error. With this update, you can use the web console to start a pipeline or task that defines a parameter of the type `array` and entering a value for this parameter works normally.
```

2024-11-08 12:31 UTC, abhatt-rh commented on modules/op-release-notes-1-16.adoc
> +* Before this update, when viewing information from {tekton-results} in the web console, when you scrolled down to the end of a page, the console failed to fetch the next set of records and some of t
```suggestion
* Before this update, when viewing information from {tekton-results} in the web console, if you scrolled down to the end of a page, the console failed to fetch the next set of records and some of the information was not displayed. With this update, if you scroll to the end of the page, records from {tekton-results} load correctly and all information displays correctly in the web console.
```

2024-11-08 17:00 UTC, mramendi commented
/label merge-review-needed

2024-11-08 17:40 UTC, adellape approved these changes

2024-11-08 17:42 UTC, adellape commented on modules/op-release-notes-1-16.adoc
> +* Before this update, when you tried to used the web console to start a pipeline or task that defined a parameter of the type `array`, entering a value for this parameter resulted in an error and you
```suggestion
* Before this update, when you tried to use the web console to start a pipeline or task that defined a parameter of the type `array`, entering a value for this parameter resulted in an error and you could not start the pipeline or task. With this update, you can use the web console to start a pipeline or task that defines a parameter of the type `array` and entering a value for this parameter works normally.
```

2024-11-08 18:28 UTC, merged