Update ingress-operator.adoc
openshift/openshift-docs pull request #84979
Opened 2024-11-14 19:20 UTC by rameshsahoo111

Added a solution article link to this document for the original client IP details.

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-11-19 16:59 UTC, jldohmann reviewed
thanks for opening! small edit to the existing link. when you've made the change, feel free to ping me

2024-11-19 16:59 UTC, jldohmann commented on networking/ingress-operator.adoc
> +* link:https://access.redhat.com/solutions/7096271k[Viewing the original client source IP through the X-Forwarded-For header in OpenShift Ingress access log]
the current link doesn't work, but this does:
```suggestion
* link:https://access.redhat.com/solutions/7096271[Viewing the original client source IP through the X-Forwarded-For header in OpenShift Ingress access log]
```

2024-11-19 17:01 UTC, jldohmann commented
/ok-to-test

2024-11-19 17:11 UTC, jldohmann commented on networking/ingress-operator.adoc
> +* link:https://access.redhat.com/solutions/7096271k[Viewing the original client source IP through the X-Forwarded-For header in OpenShift Ingress access log]
```suggestion
* link:https://access.redhat.com/solutions/7096271k[Viewing the original client source IP through the X-Forwarded-For header in {product-title} Ingress access log]
```

2024-11-19 22:49 UTC, jldohmann commented
@melvinjoseph86 can you PTAL at this docs PR for QE ack? thank you

2024-11-19 22:50 UTC, jldohmann commented
@rameshsahoo111 what version(s) of OCP do you mean for this change to apply to?

2024-11-20 10:15 UTC, melvinjoseph86 requested changes
/label qe-approved

2024-11-20 10:15 UTC, melvinjoseph86 commented on networking/ingress-operator.adoc
> +* link:https://access.redhat.com/solutions/7096271k[Viewing the original client source IP through the X-Forwarded-For header in OpenShift Ingress access log]
Working links is 'https://access.redhat.com/solutions/7096271'

2024-11-20 17:03 UTC, rameshsahoo111 commented
> > @rameshsahoo111 what version(s) of OCP do you mean for this change to apply to?
> 
> Please apply this to all OCP 4.x version.

I would also request  changing the heading as below; 

FROM: 
Viewing the original client source IP through the X-Forwarded-For header in OpenShift Ingress access log

TO: 
Viewing the original client IP through the X-Forwarded-For header in OpenShift Ingress access logs or within applications logs deployed on OpenShift

2024-11-20 18:29 UTC, jldohmann commented
@rameshsahoo111 that sounds fine, just remember to use the attribute `{product-title}` in place of OpenShift when making the change 😄

2024-11-21 04:38 UTC, rameshsahoo111 commented
> {product-title}

yes, sure. Thank you.

2024-12-23 06:25 UTC, rameshsahoo111 commented
New pull request available at https://github.com/openshift/openshift-docs/pull/86578

2025-02-24 19:08 UTC, bergerhoffer commented
The `branch/enterprise-4.19` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.18. And any PR going into `main` must also target the latest version branch (enterprise-4.19).

If the update in your PR does NOT apply to version 4.19 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2025-03-03 06:06 UTC, rameshsahoo111 commented
Thank you, please merge the pr

2025-03-03 17:03 UTC, bergerhoffer commented
@rameshsahoo111 There is a conflict now, so this PR needs to be rebased (and then squashed to 1 commit). 

Or if you can't do that, you can always open it as a new PR. Please ping @jldohmann for help (my comment was just a standard boilerplate for cutting a new version).

2025-06-16 18:51 UTC, bergerhoffer commented
The `branch/enterprise-4.20` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.19. And any PR going into `main` must also target the latest version branch (enterprise-4.20).

If the update in your PR does NOT apply to version 4.20 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

2025-08-16 08:01 UTC, closed without merging