RHDEVDOCS-6198: Content creation for PSA labels note
openshift/openshift-docs pull request #85061
Opened 2024-11-18 12:37 UTC by Dhruv-Soni11

Version(s):

GitOps 1.15

Issue:

https://issues.redhat.com/browse/RHDEVDOCS-6198

Link to docs preview:

The second note under the section [Setting up an Argo CD Instance](https://85061--ocpdocs-pr.netlify.app/openshift-gitops/latest/argocd_instance/setting-up-argocd-instance.html).
QE review:
- [x] QE has approved this change.

SME review: @svghadi 
QE review: @varshab1210 
Peer review @bergerhoffer 

Additional information:

2024-11-18 14:49 UTC, svghadi requested changes
Hi @Dhruv-Soni11 , the content is good. Can we just move it up in the same page?
![image](https://github.com/user-attachments/assets/f5d4dae1-ad78-4e91-8334-68f56b773947)

2024-11-19 06:11 UTC, Dhruv-Soni11 commented
Hi @svghadi, I have incorporated your feedback in the content. PTAL. Thanks.

2024-11-19 06:30 UTC, svghadi commented
/lgtm
Thanks @Dhruv-Soni11

2024-11-20 05:17 UTC, varshab1210 commented
LGTM, thanks

2024-11-21 07:09 UTC, Dhruv-Soni11 commented
/label peer-review-needed

2024-11-21 14:33 UTC, bergerhoffer commented on argocd_instance/setting-up-argocd-instance.adoc
> +* Restrictive Pod Security Admission (PSA) labels are applied to the `openshift-gitops` namespace to ensure compliance with {OCP} standards. If you are running additional workloads, for example - mon
- The profile is called "restricted", not "restrictive", so I assume you'd want to use that term? https://docs.openshift.com/container-platform/4.17/authentication/understanding-and-managing-pod-security-admission.html#psa-profiles_understanding-and-managing-pod-security-admission
- Pod security admission isn't capitalized
- When you say "the Operator", can you clarify which Operator you mean? 
- A few other suggestions

```suggestion
* Restricted pod security admission (PSA) labels are applied to the `openshift-gitops` namespace to ensure compliance with {OCP} standards. If you are running additional workloads in this namespace, such as monitoring or logging, ensure that they comply with the restricted PSA requirements. If compliance is not feasible, consider using a user-defined, cluster-scoped ArgoCD instance, where PSA labels are not applied or controlled by the Operator.
```

2024-11-21 14:33 UTC, bergerhoffer commented
/label peer-review-done
/remove-label peer-review-needed
/remove-label peer-review-in-progress

2024-11-22 16:20 UTC, merged

2024-11-22 16:20 UTC, adellape commented
/cherrypick gitops-docs-1.15