HCIDOCS-550: Update supported firmware version for idrac 15th and 16t…
openshift/openshift-docs pull request #85307
Opened 2024-11-21 18:42 UTC by kdrake20

**Fixes:** [HCIDOCS-550](https://issues.redhat.com/browse/HCIDOCS-550)

**For:** OCP 4.16, 4.17, 4.18

[**Preview**](https://--ocpdocs-pr.netlify.app)

**Approvals -** `/lgtm`:
- [ ] SME
- [ ] QE
- [ ] Peer Review

2024-11-21 18:51 UTC, kdrake20 commented
**Who:**
@elfosardo, SME
@jadhaj , QE

**Summary:** Hello! Could you please review this content? Please provide feedback directly in the PR.
Comment /lgtm if no changes are required. Thank you!

**Next Steps:**
- [ ] Receive /lgtm from SME
- [ ] Receive /lgtm from QE

2024-11-22 08:29 UTC, elfosardo requested changes

2024-11-22 08:29 UTC, elfosardo commented on modules/ipi-install-firmware-requirements-for-installing-with-virtual-media.adoc
> +| 11th Generation | iLO6 | 1.57 or later
please move this change to a different PR, it's unrelated, thanks

2024-11-25 18:39 UTC, kdrake20 commented
/retest

2024-11-26 08:38 UTC, elfosardo commented
/lgtm
thanks!

2024-11-26 08:38 UTC, elfosardo commented
/retest

2024-11-26 13:58 UTC, jadhaj commented
/lgtm

2024-11-26 14:00 UTC, kdrake20 commented
/label peer-review-needed

2024-11-26 17:26 UTC, mburke5678 commented
/lgtm

2024-11-26 19:40 UTC, kdrake20 commented
/label merge-review-needed

2024-11-26 20:17 UTC, opayne1 reviewed
lgtm!

2024-11-26 20:18 UTC, merged

2024-11-26 20:18 UTC, opayne1 commented
/cherrypick enterprise-4.16

2024-11-26 20:18 UTC, opayne1 commented
/cherrypick enterprise-4.17

2024-11-26 20:18 UTC, opayne1 commented
/cherrypick enterprise-4.18