PR for SRVLOGIC-481: Document "workflow eventing system" section in the Serverless Logic product docs
openshift/openshift-docs pull request #85644
Opened 2024-12-02 07:19 UTC by kaldesai

Affected versions: serverless-docs-1.35

Tracking JIRAs: 
https://issues.redhat.com/browse/SRVLOGIC-420
sub-task: https://issues.redhat.com/browse/SRVLOGIC-481

Doc preview: [Workfloe eventing system](url)

2024-12-03 16:46 UTC, wmedvede requested changes

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +.Example of Knative Eventing trigger
```suggestion
.Example of Knative Eventing Trigger listing 
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +kn trigger list -n example-namespace
```suggestion
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +$ oc get triggers -n example-namespace
```suggestion
$ kn trigger list -n example-namespace
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +.Example of Knative Eventing SinkBinding
```suggestion
.Example of Knative Eventing SinkBinding listing
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +$ oc get sinkbindings -n example-namespace
```suggestion
$ kn source list -n example-namespace
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +----
```suggestion
----

.Example output
[source,terminal]
----
NAME                                          TYPE            RESOURCE                                   SINK                              READY
example-workflow-sb                  SinkBinding   sinkbindings.sources.knative.dev   broker:example-broker   True
----

----


```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +.Example output
```suggestion
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +[source,terminal]
```suggestion
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +----
```suggestion
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +NAME                                                      BROKER           SINK                         READY   REASON
```suggestion
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +example-workflow-inevent1-b40c067c-595b-4913-81a4-c8efa980bc11    example-broker   service:example-workflow   True
```suggestion    
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +example-workflow-inevent2-b40c067c-595b-4913-81a4-c8efa980bc11    example-broker   service:example-workflow   True
```suggestion
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +----
```suggestion
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +<2> Events of type `in-event-type1` are consumed using the trigger.
```suggestion
<2> Events of type `in-event-type1` are consumed using the trigger `example-workflow-inevent1-b40c067c-595b-4913-81a4-c8efa980bc11`.
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +<3> Events of type `in-event-type2` are consumed using the trigger.
```suggestion
<3> Events of type `in-event-type2` are consumed using the trigger `example-workflow-inevent2-b40c067c-595b-4913-81a4-c8efa980bc11`.
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +You can create the SinkBinding `example-workflow-sb` for producing events by using the following commands:
```suggestion
You can list the automatically created SinkBinding `example-workflow-sb` by using the following command:
```

2024-12-03 16:46 UTC, wmedvede commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +The `example-workflow-inevent1-b40c067c-595b-4913-81a4-c8efa980bc11` and `example-workflow-inevent2-b40c067c-595b-4913-81a4-c8efa980bc11` triggers are created for consuming events by using the follow
```suggestion
You can list the automatically created Triggers for consuming events by using the following command:
```

2024-12-12 08:08 UTC, kaldesai commented on modules/serverless-logic-cluster-scoped-eventing-system-config.adoc
> +----
Tweaked a sentence a little bit to make it more reader-friendly and easy to understand.

2024-12-12 10:45 UTC, wmedvede requested changes
@kaldesai  3 nitpicks and we are there!
Great work!

2024-12-12 13:00 UTC, kaldesai commented
@wmedvede Done! I have incorporated your changes now.

2024-12-12 14:00 UTC, wmedvede approved these changes

2025-01-07 15:47 UTC, jakubschwan approved these changes

2025-01-08 06:50 UTC, kaldesai commented
/label peer-review-needed

2025-01-08 12:46 UTC, dfitzmau approved these changes

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-cluster-scoped-eventing-system-config.adoc
> +In a `SonataFlowClusterPlatform` setup, workflows are automatically linked to the Broker specified in the associated `SonataFlowPlatform` CR. This linkage follows the Eventing System Configuration Pr
```suggestion
In a `SonataFlowClusterPlatform` setup, workflows are automatically linked to the Broker specified in the associated `SonataFlowPlatform` CR. This linkage follows the Eventing System Configuration Precedence rules.
```

A section heading lowercases "rules".

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-cluster-scoped-eventing-system-config.adoc
> +The following example displays how to configure the `SonataFlowClusterPlatform` CR and its reference to the `SonataFlowPlatform` CR:
This sentence is either confusing or rehashing what was said before. How about just add to the previous paragraph, the following example...

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-cluster-scoped-eventing-system-config.adoc
> +.Example of cluster-scoped eventing system configuration
Given my previous comment, this heading might no longer be needed as a lead-in sentence should cover what the example is primarily showcasing.

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-cluster-scoped-eventing-system-config.adoc
> +    namespace: global-namespace
```suggestion
    namespace: global-namespace
 # ...
```

Unless it's actually the end of the definition? Same for the other definition. Consider stepping out each definition in it's own example.

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-cluster-scoped-eventing-system-config.adoc
> +The following example displays how to configure the `SonataFlowClusterPlatform` CR and its reference to the `SonataFlowPlatform` CR:
`SonataFlowClusterPlatform` and `SonataFlowPlatform` are both CR? Is any a CRD?

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-cluster-scoped-eventing-system-config.adoc
> +The `SonataFlowClusterPlatform` can refer to any `SonataFlowPlatform` that has already been deployed.
Add CR or CRD as required to each resource to maintain consistency of object types.

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-eventing-system-config-precedence-rule.adoc
> += Eventing system configuration precedence rules
"rules" is lowercase here and this was intended?

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-eventing-system-config-precedence-rule.adoc
> +1. If the workflow has a defined eventing system using either workflow-scoped outgoing or incoming eventing system configurations, this configuration takes priority and applies to the workflow.
Do the rules need to be followed in a particular order? If not, consider bullet points.

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-eventing-system-config-precedence-rule.adoc
> +1. If the workflow has a defined eventing system using either workflow-scoped outgoing or incoming eventing system configurations, this configuration takes priority and applies to the workflow.
> If the workflow has a defined eventing system by using either workflow-scoped outgoing or incoming eventing system configurations, the choice of configuration takes priority over the other configuration and applies to the workflow.

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-eventing-system-config-precedence-rule.adoc
> +2. If the `SonataFlowPlatform` CR enclosing the workflow has a platform-scoped eventing system configured, this configuration applies next.
```suggestion
2. If the `SonataFlowPlatform` CR enclosing the workflow has a platform-scoped eventing system configured, this configuration applies next.
```

"Next" dangles a bit.Maybe "this configuration is then applied to X". The numbered steps, if needed, state the order of events.

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-eventing-system-config-precedence-rule.adoc
> +3. If the current cluster is configured with a cluster-scoped eventing system, it is applied if no workflow-scoped or platform-scoped configuration exists.
```suggestion
3. If the current cluster is configured with a cluster-scoped eventing system, it is applied if no workflow-scoped or platform-scoped configuration exists.
```
"It" is vague. Reads like the cluster is applied to...

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-eventing-system-config-precedence-rule.adoc
> +* The workflow consumes incoming events via HTTP POST calls at the workflow service root path `/`.
```suggestion
* The workflow consumes incoming events by HTTP POST calls at the workflow service root path `/`.
```

![Screenshot from 2025-01-08 12-41-13](https://github.com/user-attachments/assets/3590ebf9-a7b8-4533-a4c9-20f844317708)

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-eventing-system-config-precedence-rule.adoc
> +* No eventing system is configured to produce workflow business events. Any attempt to produce such events will result in a failure.
```suggestion
* No eventing system is configured to produce workflow business events. Any attempt to produce such events might result in a failure.
```

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +.Example of platform-scoped eventing system configuration
Heading would be optional given that a lead-in sentence exists. I could be wrong.

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +  namespace: example-namespace
User-replaced values should be surrounded by angle brackets.

example-namespace > <example-namespace>

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +      enabled: true
```suggestion
      enabled: true
# ...
```

If the definition is not a complete YAML.

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +<2> Events of type `in-event-type1` are consumed using the `example-workflow-inevent1-b40c067c-595b-4913-81a4-c8efa980bc11` trigger.
```suggestion
<2> Events of type `in-event-type1` are consumed by using the `example-workflow-inevent1-b40c067c-595b-4913-81a4-c8efa980bc11` trigger.
```

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +$ oc get triggers -n example-namespace
User-replaced value and a callout should be used here.

2025-01-08 12:46 UTC, dfitzmau commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +NAME                                                              BROKER           SINK                                                     AGE   CONDITIONS   READY   REASON
In the preview the formatting of headings to output is off. Can this be corrected?

Maybe the Verbatim attribute might help solidify spaces.

![Screenshot from 2025-01-08 12-45-19](https://github.com/user-attachments/assets/99fca6a4-4544-48ef-a73b-ef8149cbf51c)

2025-01-09 04:50 UTC, kaldesai commented on modules/serverless-logic-cluster-scoped-eventing-system-config.adoc
> +The following example displays how to configure the `SonataFlowClusterPlatform` CR and its reference to the `SonataFlowPlatform` CR:
Yes both are CRs

2025-01-09 04:53 UTC, kaldesai commented on modules/serverless-logic-eventing-system-config-precedence-rule.adoc
> += Eventing system configuration precedence rules
The usage of "rules" here is correct. it was not intended.

2025-01-09 04:53 UTC, kaldesai commented on modules/serverless-logic-eventing-system-config-precedence-rule.adoc
> +1. If the workflow has a defined eventing system using either workflow-scoped outgoing or incoming eventing system configurations, this configuration takes priority and applies to the workflow.
Yes, they need to be followed in a particular order.

2025-01-09 05:27 UTC, kaldesai commented
/label merge-review-needed

2025-01-09 08:39 UTC, xenolinux reviewed
Posted a couple of comments for consideration; otherwise good job!

2025-01-09 08:39 UTC, xenolinux commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +<1> The `example-workflow` outgoing events are produced by using the SinkBinding `example-workflow-sb`.
```suggestion
<1> The `example-workflow` outgoing events are produced by using the `SinkBinding` named `example-workflow-sb`.
```

2025-01-09 08:39 UTC, xenolinux commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +<1> The Kafka class is used to create the `example-broker`.
```suggestion
<1> The Kafka class is used to create `example-broker`.
```

or the `example-broker` object.

2025-01-09 08:39 UTC, xenolinux commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +.Example of Knative Kafka Broker used by the SonataFlowPlatform
```suggestion

```

Redundant with lin no 41

2025-01-09 08:39 UTC, xenolinux commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +The `example-broker` is a Kafka class Broker, and its configuration is defined in the `kafka-broker-config` ConfigMap.
```suggestion
The `example-broker` object is a Kafka class Broker, and its configuration is defined in the `kafka-broker-config` config map.
```

2025-01-09 08:39 UTC, xenolinux commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +<1> The `example-broker` is used by the Data Index, Jobs Service, and the `example-workflow`.
```suggestion
<1> The `example-broker` object is used by the Data Index, Jobs Service, and the `example-workflow` workflow .
```

2025-01-09 08:39 UTC, xenolinux commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +.Example of platform-scoped eventing system configuration
```suggestion

```
Redundant with line no 10

2025-01-09 08:39 UTC, xenolinux commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +The following example shows the Knative Eventing objects created for an `example-workflow` configured with a platform-scoped eventing system:
```suggestion
The following example shows the Knative Eventing objects created for an `example-workflow` workflow configured with a platform-scoped eventing system:
```

2025-01-09 08:39 UTC, xenolinux commented on modules/serverless-logic-eventing-system-config-precedence-rule.adoc
> +The rules are as follows:
```suggestion
Eventing system configuration precedence rules are as follows:
```

2025-01-09 08:39 UTC, xenolinux commented on modules/serverless-logic-eventing-system-config-precedence-rule.adoc
> +4. If none of the above configurations are defined:
```suggestion
4. Review the following information, if none of the above configurations are defined:
```

2025-01-09 08:39 UTC, xenolinux commented on modules/serverless-logic-cluster-scoped-eventing-system-config.adoc
> +To ensure proper integration, you can configure the Broker in the `SonataFlowPlatform` CR referenced by the `SonataFlowClusterPlatform` CR, the following example displays how to configure the `Sonata
```suggestion
To ensure proper integration, you can configure `Broker` in the `SonataFlowPlatform` CR referenced by the `SonataFlowClusterPlatform` CR.

 The following example displays how to configure the `SonataFlowClusterPlatform` CR and its reference to the `SonataFlowPlatform` CR:
```

2025-01-09 09:18 UTC, kaldesai commented on serverless-logic/serverless-logic-workflow-eventing-system.adoc
> +This document describes how to set up the eventing system for a SonataFlow workflow.
`SonataFlow` is correct (with back ticks)

2025-01-09 09:20 UTC, kaldesai commented on modules/serverless-logic-workflow-scoped-eventing-system-config.adoc
> +<12> Event type for the incoming event `inEvent2`. The link of the workflow event, with the corresponding `spec.sources[]` entry, is by using the event type name `in-event-type2`.
That is right "created" was missing and I have now incorporated it.

2025-01-09 09:21 UTC, kaldesai commented on modules/serverless-logic-workflow-scoped-eventing-system-config.adoc
> +.Example of workflow-scoped incoming eventing system configuration
Removed

2025-01-09 09:27 UTC, kaldesai commented on modules/serverless-logic-linking-workflows-eventing-system.adoc
> +<1> The Kafka class is used to create the `example-broker`.
I will use: _The Kafka class is used to create the `example-broker` object._

2025-01-09 09:54 UTC, merged