PR for SRVLOGIC-482: Add "Supporting services eventing system configurations" section in the OSL product docs.
openshift/openshift-docs pull request #85650
Opened 2024-12-02 10:13 UTC by kaldesai

**Affected versions:** `serverless-docs-1.35`

**Tracking JIRAs:**
- https://issues.redhat.com/browse/SRVLOGIC-420
- sub-task: https://issues.redhat.com/browse/SRVLOGIC-482

**Doc preview:** [Supporting services eventing system configurations](https://github.com/openshift/openshift-docs/pull/url)

2024-12-03 17:31 UTC, wmedvede requested changes

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +This section describes the supporting services eventing system configurations for a SonataFlow workflow.
```suggestion
This section describes the supporting services eventing system configurations.
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +Additionally, workflows deployed in the same namespace with the `preview` or `GitOps` profile, and without a custom eventing system configuration, will automatically link to the specified Broker.
```suggestion
Additionally, workflows deployed in the same namespace with the `preview` or `gitops` profile, and without a custom eventing system configuration, will automatically link to the specified Broker.
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +== Jobs Service eventing system configuration
```suggestion
== Job Service eventing system configuration
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +To configure a service-scoped eventing system for the Jobs Service, you must use the `spec.services.jobService.source.ref` and `spec.services.jobService.sink.ref` fields in the `SonataFlowPlatform` C
```suggestion
To configure a service-scoped eventing system for the Job Service, you must use the `spec.services.jobService.source.ref` and `spec.services.jobService.sink.ref` fields in the `SonataFlowPlatform` CR. These fields instruct the {ServerlessLogicOperatorName} to automatically link the Job Service to consume and produce SonataFlow system events, based on the provided configuration.
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +The following example displays the Jobs Service eventing system configuration:
```suggestion
The following example displays the Job Service eventing system configuration:
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +.Example of Jobs Service eventing system configuration
```suggestion
.Example of Job Service eventing system configuration 
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<1> Specifies the Knative Eventing Broker from which the Jobs Service consumes events.
```suggestion
<1> Specifies the Knative Eventing Broker from which the Job Service consumes events.
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<3> Specifies the Knative Eventing Broker on which the Jobs Service produces events.
```suggestion
<3> Specifies the Knative Eventing Broker on which the Job Service produces events.
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +1. If the supporting service has its own eventing system configuration, using either the Data Index eventing system or Jobs Service eventing system configuration, that configuration takes precedence.
```suggestion
1. If the supporting service has its own eventing system configuration, using either the Data Index eventing system or Job Service eventing system configuration, that configuration takes precedence.
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<1> Used by the Data Index, Jobs Service, and workflows, unless overridden.
```suggestion
<1> Used by the Data Index, Job Service, and workflows, unless overridden.
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<3> Jobs Service ephemeral deployment, configures the Jobs Service.
```suggestion
<3> Jobs Service ephemeral deployment, configures the Job Service.
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +The following command displays the list of triggers set up for the Data Index and Jobs Service events, showing which services are subscribed to the events:
```suggestion
The following command displays the list of triggers set up for the Data Index and Job Service events, showing which services are subscribed to the events:
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +.Knative Eventing triggers created for the Data Index and Jobs Service events consumption
```suggestion
.Knative Eventing triggers created for the Data Index and Job Service events consumption
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +data-index-process-sla-fbf285df-c0a4-4545-b77a-c232ec2890e2       example-broker   service:sonataflow-platform-example-data-index-service     106s  7 OK / 7    True    -
```suggestion
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +jobs-service-create-job-fbf285df-c0a4-4545-b77a-c232ec2890e2    example-broker   service:sonataflow-platform-example-jobs-service         106s  7 OK / 7    True    -
```suggestion

jobs-service-create-job-fbf285df-c0a4-4545-b77a-c232ec2890e2    example-broker   service:sonataflow-platform-example-jobs-service         106s  7 OK / 7    True    -
```

2024-12-03 17:31 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +To see the SinkBinding for the Jobs Service, use the following command:
```suggestion
To see the SinkBinding for the Job Service, use the following command:
```

2024-12-12 07:59 UTC, kaldesai commented
@domhanak Can you please QE review this PR? 

@wmedvede I have incorporated all of your changes. Thank you!

2024-12-12 11:04 UTC, wmedvede requested changes
@kaldesai 1 nitpick and ready.
Great work!

2024-12-12 11:04 UTC, wmedvede commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +The {ServerlessLogicOperatorName} automatically creates Knative Eventing,SinkBindings, and triggers to link supporting services with the eventing system. These objects enable the production and consu
```suggestion
The {ServerlessLogicOperatorName} automatically creates Knative Eventing, SinkBindings, and triggers to link supporting services with the eventing system. These objects enable the production and consumption of events by the supporting services.
```

2024-12-12 13:05 UTC, kaldesai commented
@wmedvede, Done! I have incorporated your suggestion. Good catch! :D Thank you! :)

2024-12-12 14:03 UTC, wmedvede approved these changes

2025-01-07 13:23 UTC, jakubschwan approved these changes

2025-01-07 13:25 UTC, kaldesai commented
/label peer-review-needed

2025-01-07 16:16 UTC, dfitzmau approved these changes

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +The {ServerlessLogicOperatorName} leverages the Knative Eventing system to manage all event communication between these services, ensuring efficient and reliable event handling.
```suggestion
The {ServerlessLogicOperatorName} leverages the Knative Eventing system to manage all event communication between these events and services, ensuring efficient and reliable event handling.
```

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +[NOTE]
NOTE > IMPORTANT?

Seems important to me but I'm no expert!

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +        kind: Broker
```suggestion
        kind: Broker
# ...
```

Not a complete YAML?

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<2> Optional: Defines the namespace of the Knative Eventing Broker. If not specified, it defaults to the SonataFlowPlatform namespace. It is recommended to create the Broker in the same namespace as
```suggestion
<2> Optional: Defines the namespace of the Knative Eventing Broker. If you do not specify a value, the parameter defaults to the `SonataFlowPlatform` namespace. Consider creating the Broker in the same namespace as the `SonataFlowPlatform`.
```

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<2> Optional: Defines the namespace of the Knative Eventing Broker. If not specified, it defaults to the SonataFlowPlatform namespace. It is recommended to create the Broker in the same namespace as
See [Claims and recommendations](https://www.ibm.com/docs/en/ibm-style?topic=information-claims-recommendations) in the IBM SG.

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +[id="serverless-logic-supporting-services-service-scoped-eventing-system-config_{context}"]
Consider moving this content to a separate module to facilitate linkage and file findability.

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +In {ServerlessLogicProductName} installation, the recommended approach is to use a platform-scoped eventing system configuration. The service-scoped configuration is intended for advanced use cases o
```suggestion
For a {ServerlessLogicProductName} installation, consider using a platform-scoped eventing system configuration. The service-scoped configuration is intended for advanced use cases only.
```

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +[id="serverless-logic-data-index-eventing-system-config_{context}"]
Separate module?

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +[NOTE]
NOTE > IMPORTANT?

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +          kind: Broker
```suggestion
          kind: Broker
#...
```

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<2> Optional: Defines the namespace of the Knative Eventing Broker. By default, it uses the SonataFlowPlatform namespace. It is recommended to create the Knative Eventing Broker in the same namespace
Same as previous comment for callouts.

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<4> Optional: Defines the namespace of the Knative Eventing Broker. By default, this is the SonataFlowPlatform namespace. It is recommended to create the Knative Eventing Broker in the same namespace
```suggestion
<4> Optional: Defines the namespace of the Knative Eventing Broker. By default, this is the SonataFlowPlatform namespace. It is recommended to create the Knative Eventing Broker in the same namespace as the SonataFlowPlatform.
```

SonataFlowPlatform > `SonataFlowPlatform`?

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +1. If the supporting service has its own eventing system configuration, using either the Data Index eventing system or Job Service eventing system configuration, that configuration takes precedence.
```suggestion
1. If the supporting service has its own eventing system configuration, either the Data Index eventing system or the Job Service eventing system configuration, then supporting service's configuration takes precedence over X.
```

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +2. If the `SonataFlowPlatform` CR enclosing the supporting service is configured with a Platform-scoped eventing system, that configuration takes precedence.
SonataFlowPlatform is highlighted here so it should be highlighted elsewhere?

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +2. If the `SonataFlowPlatform` CR enclosing the supporting service is configured with a Platform-scoped eventing system, that configuration takes precedence.
Platform-scoped > platform-scoped

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +3. If the current cluster is configured with a Cluster-scoped eventing system, that configuration takes precedence.
```suggestion
3. If the current cluster is configured with a cluster-scoped eventing system, that configuration takes precedence.
```

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +4. If none of the previous configurations exist, the supporting service will use direct HTTP calls to deliver events.
```suggestion
4. If none of the previous configurations exist, the supporting service uses direct HTTP calls to deliver events.
```

2025-01-07 16:16 UTC, dfitzmau commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +The {ServerlessLogicOperatorName} automatically creates Knative Eventing, SinkBindings, and triggers to link supporting services with the eventing system. These objects enable the production and cons
```suggestion
The {ServerlessLogicOperatorName} automatically creates Knative Eventing, `SinkBindings`, and triggers to link supporting services with the eventing system. These objects enable the production and consumption of events by the supporting services.
```

2025-01-08 07:00 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +[id="serverless-logic-supporting-services-platform-scoped-eventing-system-config_{context}"]
Kept it under the same module as the content was not that much and it is a part of the "eventing system".

2025-01-08 07:02 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +[NOTE]
Changed it to "IMPORTANT"

2025-01-08 07:04 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +        kind: Broker
It is a complete YAML. I mean it is just a snippet.

2025-01-08 07:04 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<2> Optional: Defines the namespace of the Knative Eventing Broker. If not specified, it defaults to the SonataFlowPlatform namespace. It is recommended to create the Broker in the same namespace as
Thank you!

2025-01-08 07:05 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +[id="serverless-logic-supporting-services-service-scoped-eventing-system-config_{context}"]
Kept it under the same module as the content was not that much and it is a part of the "eventing system".

2025-01-08 07:06 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +[id="serverless-logic-data-index-eventing-system-config_{context}"]
Kept it under the same module as the content was not that much and it is a part of the "eventing system".

2025-01-08 07:06 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +[NOTE]
Changed it to "IMPORTANT"

2025-01-08 07:07 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +          kind: Broker
It is just a snippet of the YAML

2025-01-08 07:08 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<2> Optional: Defines the namespace of the Knative Eventing Broker. By default, it uses the SonataFlowPlatform namespace. It is recommended to create the Knative Eventing Broker in the same namespace
Done!

2025-01-08 07:13 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +2. If the `SonataFlowPlatform` CR enclosing the supporting service is configured with a Platform-scoped eventing system, that configuration takes precedence.
Done!

2025-01-08 07:40 UTC, kaldesai commented
/label merge-review-needed

2025-01-08 10:58 UTC, xenolinux reviewed
Left a couple of comments; otherwise good job!

2025-01-08 10:58 UTC, xenolinux commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<2> Optional: Defines the namespace of the Knative Eventing Broker. If you do not specify a value, the parameter defaults to the `SonataFlowPlatform` namespace. Consider creating the Broker in the sa
```suggestion
<2> Optional: Defines the namespace of the Knative Eventing Broker. If you do not specify a value, the parameter defaults to the `SonataFlowPlatform` namespace. Consider creating the broker in the same namespace as `SonataFlowPlatform`.
```

2025-01-08 10:58 UTC, xenolinux commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +<2> Optional: Defines the namespace of the Knative Eventing Broker. If you do not specify a value, the parameter defaults to the `SonataFlowPlatform` namespace. Consider creating the Broker in the sa
```suggestion
<2> Optional: Defines the namespace of the Knative Eventing Broker. If you do not specify a value, the parameter defaults to the `SonataFlowPlatform` namespace. Consider creating the Broker in the same namespace as `SonataFlowPlatform`.
```

2025-01-09 05:34 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +== Eventing system configuration precedence rules for Supporting Services
That is correct! It should be in the lower case

2025-01-09 05:38 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +.Example of SonataFlowPlatform eventing system configuration
I will remove the example heading

2025-01-09 05:39 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +.Example of Job Service eventing system configuration
I will remove the example heading

2025-01-09 05:42 UTC, kaldesai commented on modules/serverless-logic-supporting-services-eventing-system-config.adoc
> +----
Done!

2025-01-09 06:36 UTC, kaldesai commented
/label merge-review-needed

2025-01-09 06:38 UTC, xenolinux reviewed
Looks great!

Merging

2025-01-09 06:39 UTC, merged

2025-01-09 06:39 UTC, xenolinux commented
/cherrypick serverless-docs-1.35