OCPBUGS-44421: Added info on how to remove an NNCP config from networ…
openshift/openshift-docs pull request #85705
Opened 2024-12-03 09:50 UTC by dfitzmau

…k interface

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2025-01-21 10:11 UTC, mkowalski commented on modules/node-network-configuration-policy-file.adoc
> +Operator (CNO) uses to configure networking for nodes that exist in an {product-title} cluster.
Change "Cluster Network Operator" to "Kubernetes NMstate Operator"

2025-01-21 10:11 UTC, mkowalski commented on modules/node-network-configuration-policy-file.adoc
> +After you apply a node network policy to a node, the CNO creates an interface on the node. A node network policy includes your requested network configuration and the status of execution for the poli
Change "CNO" to "K-NMstate"

2025-01-21 10:11 UTC, mkowalski commented on modules/node-network-configuration-policy-file.adoc
> +. Run `oc apply -f <nncp_file_name>`. After the CNO applies the node network policy to each node in your cluster, the interface that was previously created on each node is now marked _absent_.
Change "CNO" to "K-NMstate"

2025-01-21 10:12 UTC, mkowalski commented on modules/node-network-configuration-policy-file.adoc
> +. Add `state: absent` under the `dns-resolver.config` section of the NNCP.
Change "dns-resolver.config" to "interface.state" -- because in this section we always say "[...] added an interface", "[...] removing an interface" so let's keep the example about the interface

2025-01-21 10:15 UTC, mkowalski commented on modules/virt-example-nmstate-IP-management.adoc
> +If you want to remove the options from your network interface, delete the options from the file, add `state: absent` under the `dns-resolver.config` section of the NNCP, and then run `oc apply -f <nn
DNS does not have "state: absent" as opposed to interfaces. For this example you can just link to the upstream nmstate documentation that has an example -- https://github.com/nmstate/nmstate/blob/base/examples/dns_remove.yml

2025-01-21 10:16 UTC, mkowalski commented on modules/virt-removing-interface-from-nodes.adoc
> +Deleting the node network policy that added an interface does not change the configuration of the policy on the node. Although a `NodeNetworkConfigurationPolicy` is an object in the cluster, the obje
>Similarly, removing an interface does not delete the policy.

You are opening a can of worms with this sentence :)

If we want to pursue this path, we should add something like -- "[...] removing an interface does not delete the policy. In this case however, K-NMstate will recreate the deleted interface once its Pod or Node is restarted."

2025-01-21 12:43 UTC, dfitzmau commented on modules/node-network-configuration-policy-file.adoc
> +Operator (CNO) uses to configure networking for nodes that exist in an {product-title} cluster.
:heavy_check_mark:

2025-01-21 12:43 UTC, dfitzmau commented on modules/node-network-configuration-policy-file.adoc
> +After you apply a node network policy to a node, the CNO creates an interface on the node. A node network policy includes your requested network configuration and the status of execution for the poli
:heavy_check_mark:

2025-01-21 12:43 UTC, dfitzmau commented on modules/node-network-configuration-policy-file.adoc
> +. Run `oc apply -f <nncp_file_name>`. After the CNO applies the node network policy to each node in your cluster, the interface that was previously created on each node is now marked _absent_.
:heavy_check_mark:

2025-01-21 12:48 UTC, dfitzmau commented on modules/node-network-configuration-policy-file.adoc
> +. Add `state: absent` under the `dns-resolver.config` section of the NNCP.
Updates. I see the YAML config in the doc states "interfaces.state" so I updated as per this example. 

![Screenshot from 2025-01-21 12-47-38](https://github.com/user-attachments/assets/95913c84-9cfc-4204-8703-b84f9217d53f)

2025-01-21 12:57 UTC, dfitzmau commented on modules/virt-example-nmstate-IP-management.adoc
> +If you want to remove the options from your network interface, delete the options from the file, add `state: absent` under the `dns-resolver.config` section of the NNCP, and then run `oc apply -f <nn
I added a configuration as linking to GH might not be warranted.

2025-01-21 14:21 UTC, mkowalski commented
/lgtm

2025-01-21 16:58 UTC, jneczypor commented
/label peer-review-in-progress

2025-01-21 17:44 UTC, jneczypor commented
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

2025-01-22 09:50 UTC, ffmancera requested changes
I made a comment, other than that, LGTM!

2025-01-22 09:50 UTC, ffmancera commented on modules/node-network-configuration-policy-file.adoc
> +. Edit the NNCP and remove all interface details from the file.
I think this can be confusing. While as a Nmstate developer I know that the interface details usually refers to non-identifier values like mtu, ip configuration and so, a user that is not very familiar could think it refers to all under the `interfaces` section.

It could be better to explicitly say that `name`, `state` and `type` shouldn't be removed.

2025-01-22 10:41 UTC, dfitzmau commented on modules/node-network-configuration-policy-file.adoc
> +. Edit the NNCP and remove all interface details from the file.
Thanks for the details. I updated the doc to state what should not be removed.

2025-01-22 12:11 UTC, merged

2025-01-22 12:11 UTC, dfitzmau commented
/cherrypick enterprise-4.18

2025-01-22 12:11 UTC, dfitzmau commented
/cherrypick enterprise-4.16

2025-01-22 12:11 UTC, dfitzmau commented
/cherrypick enterprise-4.15

2025-01-22 12:11 UTC, dfitzmau commented
/cherrypick enterprise-4.13

2025-01-22 12:12 UTC, dfitzmau commented
/cherrypick enterprise-4.12