OSDOCS-10810: OVN Kubernetes support for BGP as a routing protocol
openshift/openshift-docs pull request #85842
Opened 2024-12-05 02:11 UTC by jab-rh

- https://issues.redhat.com/browse/OSDOCS-10810

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-12-17 10:39 UTC, cgoncalves requested changes
Any user-created  `FRRConfiguration` CRs must be moved under the `openshift-network-operator` when upgrading clusters to 4.18+ from 4.16 or 4.17. I suggest to add a warning note in [1] as well as in the 4.18 GA release notes.

[1] https://docs.openshift.com/container-platform/4.17/networking/metallb/metallb-frr-k8s.html

2024-12-17 10:39 UTC, cgoncalves commented on modules/nw-bgp-examples.adoc
> +  namespace: metallb-system
I believe the namespace where `FRRConfiguration` CRs now have to be created under is `openshift-network-operator`. @fedepaol or @jcaamano should be able to confirm.

2024-12-17 10:39 UTC, cgoncalves commented on modules/nw-bgp-examples.adoc
> +  namespace: metallb-system
Ditto

2024-12-17 10:39 UTC, cgoncalves commented on modules/nw-bgp-examples.adoc
> +  namespace: metallb-system
Ditto

2024-12-17 10:39 UTC, cgoncalves commented on modules/nw-bgp-examples.adoc
> +  namespace: metallb-system
Ditto

2024-12-20 19:38 UTC, jab-rh commented
@jcaamano @jechen0648 

As per Slack last week, this is what I have so far. It would help to know how far off base this is so I can revise it when I'm back in January and fill in gaps.

Thanks!

2025-01-06 21:43 UTC, jab-rh commented on modules/nw-bgp-about.adoc
> +- `spec.additionalRoutingCapabilities`: Enables deployment of the FRR-K8S daemon for the cluster, which can be used independently of route advertisements, such as for the MetalLB Operator. When enabl
@jechen0648, needs to be enabled for BGP routing to work?

2025-01-06 21:46 UTC, jab-rh commented on modules/nw-bgp-about.adoc
> +
@jechen0648, couldn't `additionalRoutingCapabilities` theoretically support other values than FRR-K8S?

2025-01-06 22:00 UTC, jab-rh commented on modules/nw-bgp-examples.adoc
> +----
@jechen0648, I pulled this from the enhancement PR.

2025-01-06 22:32 UTC, jechen0648 commented on modules/nw-bgp-about.adoc
> +- `spec.additionalRoutingCapabilities`: Enables deployment of the FRR-K8S daemon for the cluster, which can be used independently of route advertisements, such as for the MetalLB Operator. When enabl
yes, the command is:

oc patch Network.operator.openshift.io cluster --type=merge -p='{"spec":{"additionalRoutingCapabilities": {"providers": ["FRR"]}, "defaultNetwork":{"ovnKubernetesConfig":{"routeAdvertisements":"Enabled"}}}}'

2025-01-06 22:36 UTC, jechen0648 commented on modules/nw-bgp-about.adoc
> +
I am not sure I can answer this question accurately, currently we do not support other routing capability except FRR.    adding "FRR" in front of routing capabilities will not be wrong.

2025-01-06 22:38 UTC, jechen0648 commented on modules/nw-bgp-examples.adoc
> +----
in BGP slack channel, bgp devel tab, Jaime posted a valid RouteAdvertisement yaml 

cat ra.yaml
apiVersion: k8s.ovn.org/v1
kind: RouteAdvertisements
metadata:
  name: default
spec:
  networkSelector:
    matchLabels:
      k8s.ovn.org/default-network: ""
  advertisements:
  - "PodNetwork"
  - "EgressIP"

2025-01-06 22:39 UTC, jechen0648 commented on modules/nw-bgp-examples.adoc
> +----
also, nodeSelector is currently not supported. https://redhat-internal.slack.com/archives/C07AT0XP4J0/p1736171556169349

2025-01-07 22:38 UTC, jab-rh commented on modules/nw-bgp-about.adoc
> +- `spec.additionalRoutingCapabilities`: Enables deployment of the FRR-K8S daemon for the cluster, which can be used independently of route advertisements, such as for the MetalLB Operator. When enabl
@jechen0648, I describe this in `modules/nw-bgp-routing-config.adoc`.

2025-01-07 22:42 UTC, jab-rh commented on modules/nw-bgp-examples.adoc
> +----
@jechen0648, this particular example revolves around `k8s.ovn.org/metadata.name: blue`, but if this isn't possible, the entire example in the enhancement proposal is itself invalid?

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-examples.adoc
> +      kubernetes.io/hostname: ovn-worker
This changed a bit as well. According to the FRRConfiguration base I provided above, it would look like
```
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: ovnk-generated-abcdef
  namespace: openshift-frr-k8s
spec:
  bgp:
    routers:
    - asn: 64512
      vrf: blue
      imports:
      - vrf: default
    - asn: 64512
      neighbors:
        - address: 172.18.0.5
          asn: 64512
          toReceive:
            allowed:
              prefixes:
              - 10.0.1.0/16
                le: 24
                ge:24
          toAdvertise:
            allowed:
              prefixes:
              - 10.0.1.0/24
      prefixes:
      - 10.0.1.0/24
      imports:
      - vrf: blue
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: ovn-worker
```
Worth noting, one such FRRConfiguration would be generated per selected node in the RouteAdvertisement with the appropriate prefix that applies to that node.

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-examples.adoc
> +spec:
You are missing the `advertisements` field:
```
advertisements:
- PodNetwork
```

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-examples.adoc
> +The OVN-Kubernetes controller checks if this `FRRConfiguration` CR applies to its node as indicated by the `kubernetes.io/hostname: ovn-worker` label. For these examples a user-defined network named
`The OVN-Kubernetes controller checks if this `FRRConfiguration` CR applies to its node as indicated by the `kubernetes.io/hostname: ovn-worker` label.`

should really be

`The OVN-Kubernetes controller checks that the RouteAdvertisements selected nodes is a subset of the nodes selected by the RouteAdvertisements selected FRRConfigurations`

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-examples.adoc
> +The generated `FRRConfiguration` object configures the subnet `10.0.1.0/24`, which belongs to VRF blue, is imported into the default VRF and advertised to the `172.18.0.5` neighbor. Because the `targ
correct but `... configures the subnet `10.0.1.0/24`, which belongs to VRF blue, is imported into the default VRF ... ` doesn't read well to me.

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-examples.adoc
> +In this scenario, a VLAN interface attached to a VRF device is associated with the blue network and the VLAN includes the external PE router. This setup provides a _VRF lite_ design where FRR-K8S is
I would probably rephrase
```
In this scenario, a VLAN interface is attached to the VRF device associated with the blue network. This setup provides ...
```
Additionally we might need to provide some examples on how to configura that VLAN with NMState. I will get back to you on this.

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-examples.adoc
> +- An assigned subnet of `10.0.1.0/24`
Same comment as in the previous example applies.

Additionally, this scenario would allow overlapping IPs so you might want to exercise it in the example.

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-examples.adoc
> +----
So this is the FRRConfiguration the generated ones will be based on.

I would probably simplify it a bit:
```
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: vpn-blue-red
  namespace: openshift-frr-k8s
  labels:
    routeAdvertisements: vpn-blue-red
spec:
  bgp:
    routers:
    - asn: 64512
      vrf: blue
      neighbors:
      - address: 182.18.0.5
        asn: 64512
        toReceive:
          allowed:
            mode: filtered
    - asn: 64512
      vrf: red
      neighbors:
      - address: 192.18.0.5
        asn: 64512
        toReceive:
          allowed:
            mode: filtered
```

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-examples.adoc
> +
It would be
```
apiVersion: k8s.ovn.org/v1
kind: RouteAdvertisements
metadata:
  name: default
spec:
  targetVRF: auto
  advertisements:
    - PodNetwork
  networkSelector:
    matchExpressions:
    - { key: k8s.ovn.org/metadata.name, operator: In, values: [blue,red] }
  frrConfigurationSelector:
    matchLabels:
      routeAdvertisements: vpn-blue-red
```

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-examples.adoc
> +----
This would be
```
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: ovnk-generated-abcde
  namespace: openshift-frr-k8s
spec:
  bgp:
    routers:
    - asn: 64512
      neighbors:
      - address: 182.18.0.5
        asn: 64512
        toReceive:
          allowed:
            prefixes:
            - 10.0.1.0/16
              le: 24
              ge:24
        toAdvertise:
          allowed:
            prefixes:
            - 10.0.1.0/24
      vrf: blue
      prefixes:
        - 10.0.1.0/24
    - asn: 64512
      neighbors:
      - address: 192.18.0.5
        asn: 64512
        toReceive:
          allowed:
            prefixes:
            - 10.0.2.0/16
              le: 24
              ge:24
        toAdvertise:
          allowed:
            prefixes:
            - 10.0.2.0/24
      vrf: red
      prefixes:
         - 10.0.2.0/24
  nodeSelector:
     matchLabels:
        kubernetes.io/hostname: ovn-worker
```
Worth noting again, one such FRRConfiguration would be generated per selected node in the RouteAdvertisement with the appropriate prefix that applies to that node.

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-examples.adoc
> +In this scenario, any filtering or selection of routes to receive must be done in the `FRRConfiguration` CR that defines peering relationships.
This applies to both scenarios.

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-examples.adoc
> +----
This is the equivalent example of the one you have for the second scenario that defines BGP peering. So I guess this one is specific to the first scenario.

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-bgp-routing-config.adoc
> +. To enable a dynamic routing provider, enter the following command:
This would be done first, so I would probably move it ahead of routeAdvertisements flag above

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-operator-cr.adoc
> +|This setting enables a dynamic routing provider. The FRR routing capability provider is required for additional route advertisement. The only supported value is `FRR`.
... is required for OVN-Kuberenetes RouteAdvertisements feature.

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-operator-cr.adoc
> +|`spec.additionalRoutingCapabilities`
`spec.additionalRoutingCapabilities.providers`

2025-01-08 13:57 UTC, jcaamano commented on modules/nw-operator-cr.adoc
> +  - FRR
```
spec:
  additionalRoutingCapabilities:
    providers:
    - FRR
```

2025-01-08 14:33 UTC, jcaamano commented
@jab-rh we also talked about moving [Networking](https://85842--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/about-networking) [Load balancing with MetalLB](https://85842--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/metallb/metallb-configure-address-pools)  to a more centric place since it applies equally for MetalLB, OVN-K RouteAdvertisements and other independent use cases.

So maybe the structure could look like
```
Networking
  BGP Routing
    About BGP Routing (like the current one, but tweaked to be more generic and less mention of route advertisements)
    Configuring FRR-K8s (the current "Configuring the integration of MetalLB and FRR-K8s", with slight tweaks mentioning it is also used for RouteAdvertisements)
    RouteAdvertisements
      About RouteAdvertisments (with content extracted from "About BGP Routing" specific to RouteAdvertisments)
      Configuring RouteAdvertisements (the current content of "Configuring BGP Routing")
```

2025-01-08 14:53 UTC, fedepaol commented
> @jcaamano, we actually can't nest that deeply, tooling limitation, so the depth of _BGP routing_ is as far as that goes.
> 
> Route advertisements is separate because being able to use BGP is independent of it? Can/would you do anything with BGP without either MetalLB or RouteAdvertisements?
>

Yes. FRR-K8s exposes a lower level API the user can use for his own needs. Most straightforward is, configure the cluster to learn BGP routes from outside.
 
> Thanks!

2025-01-08 14:54 UTC, fedepaol commented
> @jab-rh we also talked about moving [Networking](https://85842--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/about-networking) [Load balancing with MetalLB](https://85842--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/metallb/metallb-configure-address-pools) to a more centric place since it applies equally for MetalLB, OVN-K RouteAdvertisements and other independent use cases.
> 
> So maybe the structure could look like
> 
> ```
> Networking
>   BGP Routing
>     About BGP Routing (like the current one, but tweaked to be more generic and less mention of route advertisements)
>     Configuring FRR-K8s (the current "Configuring the integration of MetalLB and FRR-K8s", with slight tweaks mentioning it is also used for RouteAdvertisements)
>     RouteAdvertisements
>       About RouteAdvertisments (with content extracted from "About BGP Routing" specific to RouteAdvertisments)
>       Configuring RouteAdvertisements (the current content of "Configuring BGP Routing")
> ```
> 
> This is just a suggestion. Let's discuss. cc @fedepaol

Makes sense to me, with a cross reference from / to MetalLB (as it involves BGP too)

2025-01-08 18:58 UTC, jab-rh commented on modules/nw-bgp-about.adoc
> +With advanced routing capabilities enabled, the OVN-Kubernetes network plugin supports the following features:
@jcaamano, just based on the API field name and trying not to be overly specific, if perhaps "advanced routing" could one day be satisfied with some technology that is not BGP. But maybe BGP is the only technology that can ever provide this functionality?

> AdditionalRoutingCapabilities describes components and relevant configuration providing
> advanced routing capabilities.

And thus I refer to it as "advanced routing".

What should we call this capability that this enhancement provides? Isn't this "advanced routing" for OpenShift clusters? And you can use BGP without any of this "advanced routing" that the features provides, yes? So it seems like there's a distinction between just BGP being available, and "other stuff" that this enhancement makes possible with the primary and secondary networks?

Thanks!

2025-01-08 19:02 UTC, jab-rh commented on modules/nw-bgp-routeadvertisements-object.adoc
> +|Optional: Specifies which network routes to advertise. When omitted, advertises the default cluster network routes. Only a single network may be selected by a `RouteAdvertisements` CR. If multiple C
I have no idea, if it isn't in the enhancement, then it is something that I saw on Slack.

2025-01-08 19:04 UTC, jab-rh commented on modules/nw-bgp-examples.adoc
> +- A VRF named `mp0-red`
@jcaamano, all of this is a best guess based the enhancement as I tried to understand it; if neither of the examples are at all valid, I can include any possible examples that are valid that are supplied to me, or I can omit examples entirely. Thanks!

2025-01-08 19:09 UTC, jab-rh commented on modules/nw-bgp-examples.adoc
> +- An assigned subnet of `10.0.1.0/24`
@jcaamano, exercise?

2025-01-09 09:39 UTC, jcaamano commented on modules/nw-bgp-about.adoc
> +- Improving throughput and reducing packet overhead
Yeah, maybe better to remove this and add it back in 4.19 when we have that available.

2025-01-09 09:54 UTC, jcaamano commented
> @jcaamano, we actually can't nest that deeply, tooling limitation, so the depth of _BGP routing_ is as far as that goes.
> 
> Route advertisements is separate because being able to use BGP is independent of it? Can/would you do anything with BGP without either MetalLB or RouteAdvertisements?
> 
> Thanks!

Maybe then
```
BGP Routing
    About BGP Routing (like the current one, but tweaked to be more generic and less mention of route advertisements)
    Configuring FRR-K8s (the current "Configuring the integration of MetalLB and FRR-K8s", with slight tweaks mentioning it is also used for RouteAdvertisements)
Network Route Advertisements
    About RouteAdvertisments (with content extracted from "About BGP Routing" specific to RouteAdvertisments)
    Configuring RouteAdvertisements (the current content of "Configuring BGP Routing")
```

2025-01-09 22:24 UTC, jab-rh commented on modules/nw-bgp-about.adoc
> +- Improving throughput and reducing packet overhead
@jcaamano, this is actually commented out here `////` but can be re-added when correct.

2025-02-07 15:38 UTC, jcaamano reviewed
Looks generally good, minor comments.

2 more things:

- Whats the plan for the TBD implementation sections?
- Can we have separate PRs for `BGP Routing` and `RouteAdvertisements`? Potentially, the former might be introduced in an earlier release than the latter.

2025-02-07 15:38 UTC, jcaamano commented on modules/nw-routeadvertisements-example.adoc
> +      k8s.ovn.org/metadata.name: blue
I wouldn't this label as example. It makes it look like such label is well known but it isn't. Use a random label like `export: true` and just mention that the blue network has this label above?

2025-02-07 15:38 UTC, jcaamano commented on modules/nw-routeadvertisements-example.adoc
> +  namespace: openshift-frr-k8s
You need to add the label you are using in the RouteAdvertisements examples below:
```
...
metadata:
  name: receive-all
  namespace: openshift-frr-k8s
  labels:
    routeAdvertisements: receive-all
...
```

2025-02-07 15:38 UTC, jcaamano commented on modules/nw-routeadvertisements-example.adoc
> +- A VRF named `mp0-red`
A VRF named `red`

2025-02-07 15:38 UTC, jcaamano commented on modules/nw-routeadvertisements-example.adoc
> +- A VRF named `mp0-blue`
A VRF named `blue`

2025-02-07 15:38 UTC, jcaamano commented on modules/nw-routeadvertisements-example.adoc
> +    - { key: k8s.ovn.org/metadata.name, operator: In, values: [blue,red] }
same comment for label as before

2025-02-07 15:38 UTC, jcaamano commented on modules/nw-routeadvertisements-example.adoc
> +In this scenario, any filtering or selection of routes to receive must be done in the `FRRConfiguration` CR that defines peering relationships. An `FRRConfiguration` object is generated for each node
This paragraph is a bit out of place because it is not specific to this scenario. It is rather a generic consideration. It fits better under `Examples advertising pod IP addresses with BGP` combining it somehow with the last paragraph there:

```
An `FRRConfiguration` object is generated for each node selected by a `RouteAdvertisements` CR with the appropriate advertised prefixes that apply to each node. The OVN-Kubernetes controller checks that the RouteAdvertisements CR selected nodes are a subset of the nodes selected by the RouteAdvertisements CR selected FRRConfigurations.

Any filtering or selection of prefixes to receive are not considered in `FRRConfiguration` objects generated from the `RouteAdvertisements`. Prefixes to receive need to be configured on other FRRConfiguration objects, like the one above. OVN-Kubernetes will import routes from the VRF into the appropriate network.
````

2025-02-08 00:41 UTC, jab-rh commented on modules/nw-routeadvertisements-example.adoc
> +In this scenario, the blue user-defined network is exposed to the external network so that the attached pods have IP addresses that are reachable from the external network. The user-defined networks
@jcaamano, should I call out elsewhere that this feature is intended for use with CUDN only? Thanks!

2025-02-08 00:43 UTC, jab-rh commented on modules/nw-routeadvertisements-example.adoc
> +In this scenario, the blue user-defined network is exposed to the external network so that the attached pods have IP addresses that are reachable from the external network. The user-defined networks
@jcaamano, is it

s/user-defined network/cluster user-defined network/g

for all occurrences, or just this specific instance?

2025-02-13 15:56 UTC, jcaamano commented on modules/nw-bgp-about.adoc
> +The MetalLB Operator is installed as an add-on to the cluster. Deployment of the MetalLB Operator automatically enables FRR-K8s as an additional routing capability provider and uses the FRR-K8s daemo
This potentially needs it's own instruction

1. Create namespace:
```
oc create namespace openshift-frr-k8s
```
2. Copy FRRConfigurations from old namespace to new namespace
```
OLD_NAMESPACE="metallb-system"
NEW_NAMESPACE="openshift-frr-k8s"

# don't copy FRRConfigurations starting with 'metallb-' as those are generated
FILTER_OUT="metallb-"

oc get -n "${OLD_NAMESPACE}" FRRConfigurations -o json |\
  jq -r '.items[] | select(.metadata.name | test("'"${FILTER_OUT}"'") | not) |\ 
  jq -r '.metadata.namespace = "'"${NEW_NAMESPACE}"'"' |\
  oc create -f -
```

2025-02-13 15:56 UTC, jcaamano commented on modules/nw-bgp-about.adoc
> +The MetalLB Operator is installed as an add-on to the cluster. Deployment of the MetalLB Operator automatically enables FRR-K8s as an additional routing capability provider and uses the FRR-K8s daemo
Also, I guess this might also need to be noted on a release note, but not sure if this is handled through docs

2025-02-17 07:40 UTC, laubai commented on networking/bgp-routing/about-bgp-routing.adoc
> +This feature provides native BGP routing capabilities for the cluster. Additionally, this feature must be enabled to use the RouteAdvertisements feature of the OVN-Kubernetes network plugin.
Coming in from a related diagram request - spell out acronym on first use? This isn't necessarily a ubiquitous term.

2025-02-18 18:12 UTC, jab-rh commented
This is getting split into two distinct PRs, for each half.

2025-03-27 00:58 UTC, jab-rh commented
Closing in favor of two split PRs.

2025-03-27 00:58 UTC, closed without merging