CNV-45152: Added note about linux bonding mode support
openshift/openshift-docs pull request #85882
Opened 2024-12-05 17:15 UTC by sjhala-ccs

Version(s): 4.13+

Issue: CNV-45152

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-12-06 15:30 UTC, phoracek requested changes

2024-12-06 15:30 UTC, phoracek commented on virt/vm_networking/virt-connecting-vm-to-linux-bridge.adoc
> +{VirtProductName} does not support Linux bridge bonding modes 5 and 6. For more information, see link:https://access.redhat.com/solutions/67546[Which bonding modes work when used with a bridge that v
If RHV did not support it, we should not either.

2024-12-10 22:19 UTC, phoracek approved these changes

2024-12-11 20:57 UTC, lahinson reviewed
LGTM

2024-12-12 14:19 UTC, yossisegev approved these changes
/lgtm

2024-12-12 15:01 UTC, merged

2024-12-12 15:02 UTC, sjhala-ccs commented
/cherrypick enterprise-4.13

2024-12-12 15:02 UTC, sjhala-ccs commented
/cherrypick enterprise-4.15

2024-12-12 15:02 UTC, sjhala-ccs commented
/cherrypick enterprise-4.16

2024-12-12 15:02 UTC, sjhala-ccs commented
/cherrypick enterprise-4.17

2024-12-12 15:02 UTC, sjhala-ccs commented
/cherrypick enterprise-4.18

2024-12-12 15:06 UTC, sjhala-ccs commented
/cherrypick enterprise-4.18