CNV-50607: Connecting VMs to primary UDNs
openshift/openshift-docs pull request #86295
Opened 2024-12-13 21:53 UTC by sjhala-ccs

Version(s): 4.17+

Issue: CNV-50607

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2024-12-16 13:42 UTC, yossisegev requested changes

2024-12-16 14:26 UTC, maiqueb requested changes
I think we need to understand if we want to "recommend" passt (I don't think so...) or `l2bridge` as the recommended binding. 

I think we should recommend l2bridge, since it doesn't have the TCP connection limitation.

2024-12-16 14:26 UTC, maiqueb commented on modules/virt-attaching-vm-to-primary-udn.adoc
> +                name: passt # <2>
let's please use l2bridge.

2024-12-16 14:26 UTC, maiqueb commented on modules/virt-attaching-vm-to-primary-udn.adoc
> +. Optional: If you edited a running virtual machine, you must restart it for the changes to take effect.
correct, let's drop this clause.

2024-12-16 14:26 UTC, maiqueb commented on modules/virt-creating-a-primary-udn.adoc
> +<3> The topological configuration of the network. The required value is `Layer2`. A `Layer2` topology creates a logical switch that is shared by all nodes.
let's not even mention Layer3. Live migration will **not** work with that.

2024-12-16 14:26 UTC, maiqueb commented on modules/virt-enabling-primary-udn.adoc
So we will document this in tech preview, and then once ready, "graduate" it ?

2024-12-16 14:26 UTC, maiqueb commented on modules/virt-enabling-primary-udn.adoc
> +To bind a virtual machine (VM) to a user-defined network on the VM's primary interface, you must first set the `primaryUserDefinedNetworkBinding` and `deployKubevirtIpamController` feature gates to `
In 4.18, you no longer need to refer the `deployKubevirtIpamController` FG.

I think you also do not need to do it for the `primaryUserDefinedNetworkBinding` as well. @orelmisan to keep me honest here.

2024-12-16 14:26 UTC, maiqueb commented on modules/virt-enabling-primary-udn.adoc
> + {"op":"replace","path":"/spec/featureGates/deployKubevirtIpamController","value":true} ]'
ditto

2024-12-16 14:26 UTC, maiqueb commented on virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc
> +* Open TCP sessions close during live migration
you're right, this is a limitations of passt - for `l2bridge` it doesn't exist.

2024-12-16 15:05 UTC, sjhala-ccs commented on modules/virt-enabling-primary-udn.adoc
@maiqueb There is a [separate doc story](https://issues.redhat.com/browse/CNV-46630) for downstream GA docs. Anything that is mentioned here in the Tech Preview docs which is not applicable for GA will be removed/updated.

2024-12-16 19:28 UTC, sjhala-ccs commented
> Normally we would get TP docs merged first, and then later upgrade them to GA. However, we have a timing issue here - Despite the original plan, the UDN feature will be released in 4.18.0 as GA first before it lands on 4.17.z as TP.
> 
> We could:
> 
> 1. Treat this as doc PR for the TP. Verify it with passt on 4.18. Post a follow-up PR to graduate it to GA with l2bridge. Then once 4.17.z introduces UDN TP, backport the first PR there. The only challenge connected to this method I can think of is that if we remove passt binding from 4.18 before QE gets to verify this documentation PR, we have no way of verifying it.
> 2. Rework this PR to be focused on the GA from the beginning. Once 4.17.z is a thing, push a new PR for TP + passt.
> 
> It mostly depends on @sjhala-ccs and how she prefers to proceed, except for the issue with testing of the TP docs - there we would need @sjhala-ccs and @yossisegev to agree how to verify this initial PR.

@phoracek Thanks for the update about the timing of the TP and GA releases. I think option 2 (reworking this PR for 4.18 GA and creating a separate 4.17 PR for TP) sounds reasonable to me. 

@yossisegev WDYT?

2024-12-17 15:50 UTC, yossisegev commented
>> Normally we would get TP docs merged first, and then later upgrade them to GA. However, we have a timing issue here - Despite the original plan, the UDN feature will be released in 4.18.0 as GA first before it lands on 4.17.z as TP.
>> 
>> We could:
>> 
>> Treat this as doc PR for the TP. Verify it with passt on 4.18. Post a follow-up PR to graduate it to GA with l2bridge. Then once 4.17.z introduces UDN TP, backport the first PR there. The only challenge connected to this method I can think of is that if we remove passt binding from 4.18 before QE gets to verify this documentation PR, we have no way of verifying it.
>> Rework this PR to be focused on the GA from the beginning. Once 4.17.z is a thing, push a new PR for TP + passt.
>> It mostly depends on @sjhala-ccs and how she prefers to proceed, except for the issue with testing of the TP docs - there we would need @sjhala-ccs and @yossisegev to agree how to verify this initial PR.
> @phoracek Thanks for the update about the timing of the TP and GA releases. I think option 2 (reworking this PR for 4.18 GA and creating a separate 4.17 PR for TP) sounds reasonable to me.
>
> @yossisegev WDYT?

Definitely 2. The first option is too messy to handle, and subject to errors and confusions. The fact that this feature is going to be back-ported to a z!=0 version is already a source for confusions, which we must minimize as possible

2025-01-21 14:26 UTC, sjhala-ccs commented
@phoracek Can you please review?

2025-01-21 14:59 UTC, maiqueb commented on virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc
> +* Incorrect IP addresses are listed on the VM status.
hm ... how so ? I'm not sure this is true. 

Looking at a running VMI in my cluster:
```
$ kubectl get vmi -nred-namespace red -ojsonpath="{@.status.interfaces}" | jq
[
  {
    "infoSource": "domain, guest-agent",
    "interfaceName": "eth0",
    "ipAddress": "203.203.0.4",
    "ipAddresses": [
      "203.203.0.4"
    ],
    "mac": "0a:58:cb:cb:00:04",
    "name": "happy",
    "podInterfaceName": "ovn-udn1",
    "queueCount": 1
  }
]
```

This looks correct.

2025-01-21 15:00 UTC, maiqueb commented on modules/virt-creating-a-primary-udn.adoc
> +      - "2001:db8::/60"
@ormergi didn't we change this recently ? Or was it just for the c-UDN ?

2025-01-21 15:15 UTC, maiqueb commented on modules/virt-creating-a-primary-udn.adoc
> +<2> The namespace in which the VM is located. This value cannot be `default` or match any global namespaces that are created by the Cluster Network Operator (CNO).
we need to indicate that this namespace **must** feature the `k8s.ovn.org/primary-user-defined-network`, right @phoracek ?

2025-01-21 17:09 UTC, maiqueb requested changes
Thanks for the updated version.

Unfortunately, the API changed a little, and we need to adapt ...

2025-01-21 17:09 UTC, maiqueb commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +    excludeSubnets: ["10.0.0.100/26"]
this is wrong. 

It recently changed. Please check [this](https://github.com/maiqueb/fosdem2025-p-udn/blob/afe9e49a264f7f6ca98c86854742c45c24bf57cd/manifests/cluster-wide-network/01-udn.yaml#L42) example of a correct c-udn.

@ormergi do we expose the `excludeSubnets` attribute ?... I don't see it in the [API reference](https://ovn-kubernetes.io/api-reference/userdefinednetwork-api-spec/#clusteruserdefinednetwork) ... which we know is **not** up-to-date :crying_cat_face:

2025-01-21 17:09 UTC, maiqueb commented on modules/virt-attaching-vm-to-primary-udn.adoc
> +You can connect a virtual machine (VM) to the primary user-defined network (UDN) by including the network details in the VM configuration.
```suggestion
You can connect a virtual machine (VM) to the primary user-defined network (UDN) by requesting the pod network attachment, and properly configuring the interface binding.
```

2025-01-21 17:09 UTC, maiqueb commented on modules/virt-attaching-vm-to-primary-udn.adoc
> +<2> The name of the binding plugin that is used to connect the interface to the VM.
Please indicate that it **must** be l2bridge.

```suggestion
<2> The name of the binding plugin that is used to connect the interface to the VM. The required value is `l2bridge`
```

2025-01-21 17:09 UTC, maiqueb commented on virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc
> +Tenant owners can configure a primary `UserDefinedNetwork` CRD to create a network that isolates their namespace from other namespaces. Cluster administrators can use the `ClusterUserDefinedNetwork`
```suggestion
Tenant owners can configure a primary `UserDefinedNetwork` CRD to create a network that isolates their namespace from other namespaces without requiring network policies. Cluster administrators can use the `ClusterUserDefinedNetwork` CRD to create a shared OVN network across multiple namespaces.
```

2025-01-21 17:10 UTC, ormergi commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +    excludeSubnets: ["10.0.0.100/26"]
We dont for l2 & l3 topologies, for the incoming localnet topology it will have excludeSubnets

2025-01-21 17:14 UTC, ormergi commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +    excludeSubnets: ["10.0.0.100/26"]
@maiqueb we should specify persistent IPs for VMs right?

2025-01-21 17:22 UTC, ormergi commented
@sjhala-ccs it seems some UDN and CUDN examples in the docs this PR adds asumme on very early iteration of the API.
Please see the following docs https://github.com/openshift/openshift-docs/blob/main/modules/nw-udn-cr.adoc  
for the updated API and attributes  descriptions. 
UDN CRD docs https://github.com/openshift/openshift-docs/blob/main/modules/nw-udn-cr.adoc 
CUDN CRD docs PR (not merged yet) https://github.com/openshift/openshift-docs/pull/85165 
https://github.com/openshift/openshift-docs/blob/6f35f45822bcc6760b77d33adcfc18ecc4ada2b3/modules/nw-cudn-cr.adoc

2025-01-21 17:25 UTC, maiqueb commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +    excludeSubnets: ["10.0.0.100/26"]
Oh for sure we want `Persistent` ipam lifecycle. 

Good catch !

2025-01-21 17:29 UTC, ormergi commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +$ oc apply -f <filename>.yaml
Please consider spesifying `--validate` flag in `oc` commands around UDN & CUDN CRDs to ensure strict validation is done.
It will encourage users to use this flag avoiding invalid yaml create silently.

2025-01-21 17:33 UTC, ormergi commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +<2> Specifies which namespaces can connect to this network. You can use the `kubernetes.io/metadata.name` label to ensure that only namespaces with the matching label are able to access the network.
Please see the example for describing the `namespaceSelector` https://github.com/openshift/openshift-docs/blob/6f35f45822bcc6760b77d33adcfc18ecc4ada2b3/modules/nw-cudn-cr.adoc?plain=1#L34-L49

2025-01-21 17:34 UTC, maiqueb commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +$ oc apply -f <filename>.yaml
Neat suggestion.

2025-01-21 17:35 UTC, sjhala-ccs commented
> @sjhala-ccs it seems some UDN and CUDN examples in the docs this PR adds asumme on very early iteration of the API. Please see the following docs https://github.com/openshift/openshift-docs/blob/main/modules/nw-udn-cr.adoc for the updated API and attributes descriptions. UDN CRD docs https://github.com/openshift/openshift-docs/blob/main/modules/nw-udn-cr.adoc CUDN CRD docs PR (not merged yet) #85165 https://github.com/openshift/openshift-docs/blob/6f35f45822bcc6760b77d33adcfc18ecc4ada2b3/modules/nw-cudn-cr.adoc

@ormergi @maiqueb Thanks for the comments and updated resource links. I have been referring mainly to the UDN deep dive slides and this [readme doc](https://github.com/openshift/enhancements/blob/master/enhancements/network/user-defined-network-segmentation.md#example---namespace-scoped-network).

2025-01-21 17:37 UTC, ormergi commented on modules/virt-creating-a-primary-udn.adoc
> +<2> The namespace in which the VM is located. This value cannot be `default` or match any global namespaces that are created by the Cluster Network Operator (CNO).
```suggestion
<2> The namespace in which the VM is located. This value should not be `default` or match any global namespaces defied by Cluster Network Operator (CNO).
```

2025-01-21 17:38 UTC, ormergi commented on modules/virt-creating-a-primary-udn.adoc
> +$ oc apply -f <filename>.yaml
Please see https://github.com/openshift/openshift-docs/pull/86295/files#r1924126560

2025-01-21 17:45 UTC, ormergi commented on virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc
> +* You cannot use the `oc port-forward` command to forward ports to a VM.
@yossisegev did you tackled these by chance?
 If so, can you tell where does it fail?

2025-01-21 19:13 UTC, maiqueb commented on modules/virt-creating-a-primary-udn.adoc
> +<2> The namespace in which the VM is located. This value cannot be `default` or match any global namespaces that are created by the Cluster Network Operator (CNO).
*defined

2025-01-22 14:46 UTC, sjhala-ccs commented on virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc
> +* Incorrect IP addresses are listed on the VM status.
Removed the bullet. It was left over from the tech preview content.

2025-01-22 14:48 UTC, sjhala-ccs commented on modules/virt-creating-a-primary-udn.adoc
> +      - "2001:db8::/60"
Updated the YAML

2025-01-22 15:48 UTC, phoracek commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +    mtu: 9000
This would not work on most of setups. Please remove the explicit MTU configuration to stick to the default. With that, the config will be easier to copy paste.

2025-01-22 16:08 UTC, sjhala-ccs commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +<1> The name of the `ClusterUserDefinedNetwork` custom resource.
I'll keep this as is to be consistent with OCP docs.

2025-01-22 16:28 UTC, sjhala-ccs commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +    excludeSubnets: ["10.0.0.100/26"]
I have updated the YAML based on [this doc](https://github.com/maiqueb/fosdem2025-p-udn/blob/afe9e49a264f7f6ca98c86854742c45c24bf57cd/manifests/cluster-wide-network/01-udn.yaml#L42)

2025-01-28 13:04 UTC, phoracek commented on virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc
> +* You cannot use headless services to access a VM.
Sorry for raising this only now, but we should raise one more limitation - TCP and HTTP probes are not supported with primary UDN. https://docs.openshift.com/container-platform/4.16/virt/monitoring/virt-monitoring-vm-health.html#virt-about-readiness-liveness-probes_virt-monitoring-vm-health

2025-01-28 13:57 UTC, yossisegev requested changes

2025-01-28 13:57 UTC, yossisegev commented on virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc
> +You must add the `k8s.ovn.org/primary-user-defined-network` label when you create a namespace that is to be used with user-defined networks.
@maiqueb This is new to me.
Until now, we only needed to create a UDN in a certain namespace, in order to make this namespace a UDN one.
Do you know anything else?

2025-01-28 13:57 UTC, yossisegev commented on modules/virt-creating-a-primary-udn.adoc
> +. You have created a namespace and applied the `k8s.ovn.org/primary-user-defined-network` label.
@maiqueb This is new to me.
Until now, we only needed to create a UDN in a certain namespace, in order to make this namespace a UDN one.
Do you know anything else?

2025-01-28 13:57 UTC, yossisegev commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +. You have created a namespace and applied the `k8s.ovn.org/primary-user-defined-network` label.
Again - I'm not even sure it is true, but if it is, then this comment should be modified in a way that it clarifies, that all the namespaces that are targeted for UDN must be labeled.

2025-01-28 13:57 UTC, yossisegev commented on modules/virt-attaching-vm-to-primary-udn.adoc
> +<3> The name of the network. This must match the value of the `spec.template.spec.domain.devices.interfaces.name` field.
And it should also match the `metadata.name` of the `UserDefinedNetwork` resource.

2025-01-28 13:57 UTC, yossisegev commented on modules/virt-attaching-vm-to-primary-udn.adoc
> +  name: example-vm
It may be obvious, but I think it is better to also add an explicit `namespace` entry, and explain (in the call-outs below) that VM must be created in a namespace where UDN was defined.

2025-01-28 16:06 UTC, phoracek commented on modules/virt-creating-a-primary-udn.adoc
> +  ipam
this is missing colon

2025-01-29 16:51 UTC, maiqueb commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +. You have created a namespace and applied the `k8s.ovn.org/primary-user-defined-network` label.
Yeah, I kind of agree ... 

Our wording should make it clear that the event of labeling the namespace upon creation appropriately, and creating a primary UDN CR in said namespace are what overrides the default cluster network, and attaches teh primary UDN instead. 

... it is implied sure, but, maybe, it's better to be crystal clear here.

2025-01-29 16:53 UTC, maiqueb commented on modules/virt-creating-a-primary-udn.adoc
> +. You have created a namespace and applied the `k8s.ovn.org/primary-user-defined-network` label.
Yes, this is new.

You need to do this upon namespace creation, since the namespace is not mutable. 

Hence, the user, when they create the namespace, must already label the namespace appropriately. 

Afterwards, they'll create the UDN. This was the way we found of preventing the UDN / workload race where the workload would be processed before the UDN, and the workload would be granted a default cluster network attachment instead.

2025-01-29 16:54 UTC, maiqueb commented on virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc
> +You must add the `k8s.ovn.org/primary-user-defined-network` label when you create a namespace that is to be used with user-defined networks.
Replied below.

2025-01-29 16:54 UTC, maiqueb commented
> @phoracek @maiqueb do you think it make sense to have aditional example of using UDN with IPAM disabled?

No. I don't think we care. Let people read the API if they want that.

2025-01-29 17:16 UTC, maiqueb reviewed
Some other questions . 

We're nearly there !

2025-01-29 17:16 UTC, maiqueb commented on modules/virt-creating-a-primary-udn.adoc
> +.Prerequisites
@phoracek do we need any sort of clarification / differentiation for a non-admin user ?

2025-01-29 17:16 UTC, maiqueb commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +    - "blue-namespace"
I think this example is not good ... Below we indicate:
> With the `matchLabels` selector, namespace values are evaluated with an _AND_ relationship.

Which means this will match any namespaces with *both* `red-namespace` **and** `blue-namespace` labels in them. 

I don't know, while semantically correct, I think a namespace can't be both red and blue ... That's purple ... 

But this is opinionated! Take it with a grain of salt.

2025-01-29 17:16 UTC, maiqueb commented on modules/virt-attaching-vm-to-primary-udn.adoc
> +<4> The name of the network. This must match the value of the `spec.template.spec.domain.devices.interfaces.name` field of the `VirtualMachine` manifest and the `metadata.name` field of the `UserDefi
wait a minute ... why does it have to match the "`metadata.name` field of the `UserDefinedNetwork` manifest" ? 

I don't think so ...

@phoracek FYI
@ormergi in case there's something fishy w/ the CRD that I'm not aware of ...

2025-01-30 07:15 UTC, ormergi commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +    - "blue-namespace"
I can confirm this is true when `matchLabels` are used.
If one would like to select `red-namespace` and `blue-namespace` namespaces they could use `matchExpressions`:
```
matchExpressions:
- key: kubernetes.io/metadata.name
  operator: In
  values: [ "red-namespace", "blue-namespace" ]
```

2025-01-30 07:28 UTC, ormergi commented on modules/virt-attaching-vm-to-primary-udn.adoc
> +<4> The name of the network. This must match the value of the `spec.template.spec.domain.devices.interfaces.name` field of the `VirtualMachine` manifest and the `metadata.name` field of the `UserDefi
Nope its like you would work with any other Multus network.
The "..and the `metadata.name` field of the `UserDefinedNetwork` manifest."  part is not correct for this field, 
its correct for `spec.template.spec.networks.[].multus.networkName` though.

Please see docs we have today for bridge secondary network, I think the new docs should be consistent with what we have today https://docs.openshift.com/container-platform/4.17/virt/vm_networking/virt-connecting-vm-to-linux-bridge.html#virt-attaching-vm-secondary-network-cli_virt-connecting-vm-to-linux-bridge

Plus the addition that the `spec.template.spec.networks.[].multus.**networkName**` field should specify the `UserDefinedNetwork` CR metadata.name.

2025-01-30 07:32 UTC, ormergi commented on modules/virt-attaching-vm-to-primary-udn.adoc
> +<3> The name of the binding plugin that is used to connect the interface to the VM. The required value is `l2bridge`.
nit: Please consider following existing docs https://docs.openshift.com/container-platform/4.17/virt/vm_networking/virt-connecting-vm-to-linux-bridge.html#virt-attaching-vm-secondary-network-cli_virt-connecting-vm-to-linux-bridge

2025-01-30 07:41 UTC, ormergi commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +    - "blue-namespace"
In SND docs PR there are two examples for CUDN, one demonstrate using `matchLabels` and another one using `matchExpressions`, please see https://github.com/openshift/openshift-docs/pull/85165/files#diff-99caca4d20a24b77fac646362338d4957b4c028f63f8723326924a13b6bbebeaR86-R89

2025-01-30 08:22 UTC, Anatw commented on modules/virt-creating-a-primary-udn.adoc
> +. You have created a namespace and applied the `k8s.ovn.org/primary-user-defined-network` label.
Is this also true for C-UDN?

2025-01-30 08:43 UTC, maiqueb commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +    - "blue-namespace"
Thanks @ormergi .

@sjhala-ccs I think the correct example to show the user (if we're indeed going for "color" based examples) would be the `matchExpressions` one.

2025-01-30 10:56 UTC, phoracek commented on modules/virt-creating-a-primary-udn.adoc
> +.Prerequisites
I would leave it as is, not to overcomplicate the guide. As far as I'm concerned, the whole process of defining a network is for the cluster admin persona.

2025-02-03 13:53 UTC, sjhala-ccs commented on virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc
> +You must consider the following limitations before implementing a primary UDN:
@maiqueb I link to the [About user-defined networks](https://docs.openshift.com/container-platform/4.18/networking/multiple_networks/primary_networks/about-user-defined-networks.html) page in the Additional resources section in this PR. That page has a section which describes the benefits of user-defined networks.

2025-02-03 14:32 UTC, maiqueb approved these changes

2025-02-03 14:43 UTC, sjhala-ccs commented
@yossisegev Can I get QE approval on this PR if the changes look good? Thank you.

2025-02-03 15:01 UTC, yossisegev requested changes
One comment from my previous reviews that should be handled.
Other than that - LGTM.

2025-02-03 22:48 UTC, mburke5678 commented on modules/virt-creating-a-primary-cluster-udn.adoc
> +<6> Specifies if the UDN is primary or secondary. {VirtProductName} only supports the `Primary` role. This means that the UDN acts as the primary network for the VM and all default traffic passes thr
Maybe make all of the call-outs consistent.
```suggestion
<1> Specifies the name of the `ClusterUserDefinedNetwork` custom resource.
<2> Specifies the set of namespaces that the cluster UDN applies to. The namespace selector must not point to `default`, an `openshift-*` namespace, or any global namespaces that are defined by the Cluster Network Operator (CNO).
<3> Specifies the type of selector. In this example, the `matchExpressions` selector selects objects that have the label `kubernetes.io/metadata.name` with the value `red-namespace` or `blue-namespace`.
<4> Specifies the type of operator. Possible values are `In`, `NotIn`, and `Exists`.
<5> Specifies the topological configuration of the network. The required value is `Layer2`. A `Layer2` topology creates a logical switch that is shared by all nodes.
<6> Specifies if the UDN is primary or secondary. {VirtProductName} only supports the `Primary` role. This means that the UDN acts as the primary network for the VM and all default traffic passes through this network.
```

2025-02-03 22:49 UTC, mburke5678 commented on modules/virt-creating-a-primary-udn.adoc
> +<5> Specifies that virtual workloads have consistent IP addresses across reboots and migration. The `spec.layer2.subnets` field is required when `ipam.lifecycle: Persistent` is specified.
Same here
```suggestion
<1> Specifies the name of the `UserDefinedNetwork` custom resource. 
<2> Specifies the namespace in which the VM is located. The namespace must have the `k8s.ovn.org/primary-user-defined-network` label. The namespace must not be `default`, an `openshift-*` namespace, or match any global namespaces that are defined by the Cluster Network Operator (CNO).
<3> Specifies the topological configuration of the network. The required value is `Layer2`. A `Layer2` topology creates a logical switch that is shared by all nodes.
<4> Specifies if the UDN is primary or secondary. {VirtProductName} only supports the `Primary` role. This means that the UDN acts as the primary network for the VM and all default traffic passes through this network.
<5> Specifies that virtual workloads have consistent IP addresses across reboots and migration. The `spec.layer2.subnets` field is required when `ipam.lifecycle: Persistent` is specified.
```

2025-02-03 22:51 UTC, mburke5678 commented on modules/virt-creating-a-primary-udn.adoc
> +<2> The namespace in which the VM is located. The namespace must have the `k8s.ovn.org/primary-user-defined-network` label. The namespace must not be `default`, an `openshift-*` namespace, or match a
Maybe keep consistent with the previous.
```suggestion
<2> The namespace in which the VM is located. The namespace must have the `k8s.ovn.org/primary-user-defined-network` label.  The namespace selector must not point to `default`, an `openshift-*` namespace, or any global namespace that is defined by the Cluster Network Operator (CNO).
```

2025-02-03 22:56 UTC, mburke5678 commented
@sjhala-ccs A few comments. Otherwise LGTM

2025-02-03 23:48 UTC, sjhala-ccs commented on modules/virt-creating-a-primary-udn.adoc
> +<2> The namespace in which the VM is located. The namespace must have the `k8s.ovn.org/primary-user-defined-network` label. The namespace must not be `default`, an `openshift-*` namespace, or match a
@mburke5678 This call out describes the actual namespace value while the call out in the other procedure is for a namespace selector that points to namespace values in an array. The two fields are different.

2025-02-04 15:55 UTC, merged

2025-02-04 15:56 UTC, sjhala-ccs commented
/cherrypick enterprise-4.18