added ingress support section
openshift/openshift-docs pull request #8638
Opened 2018-04-09 03:25 UTC by bfallonf

For: #8596 

cc: @JacobTanenbaum

2018-04-10 00:16 UTC, bfallonf commented
Neato. Thanks @JacobTanenbaum 

@openshift/team-documentation PTAL

2018-04-10 00:32 UTC, gaurav-nelson commented on architecture/networking/routes.adoc
> +----
maybe add `[source, yaml]` tags before code blocs (2 instances)

2018-04-10 00:32 UTC, gaurav-nelson commented on architecture/networking/routes.adoc
> +would generate the following route object:
s/would generate/generates

2018-04-10 00:34 UTC, gaurav-nelson commented on architecture/networking/routes.adoc
> +In order for a route to be created, an ingress object needs to have a host,
s/In order for/For

2018-04-10 00:35 UTC, gaurav-nelson commented on architecture/networking/routes.adoc
> +In order for a route to be created, an ingress object needs to have a host,
maybe? s/needs to have/must have

2018-04-10 00:47 UTC, gaurav-nelson requested changes
few nits, rest looks good. 👍

2018-04-11 00:37 UTC, gaurav-nelson approved these changes

2018-04-11 01:13 UTC, bfallonf commented
Thanks @gaurav-nelson . I made changes as per your suggestions.

2018-04-11 04:39 UTC, merged

2018-04-11 04:39 UTC, bfallonf commented
/cherrypick enterprise-3.10

2018-04-11 07:01 UTC, vikram-redhat commented
@bfallonf - was this QEed?

2018-04-11 23:55 UTC, bfallonf commented
@vikram-redhat yes, in the PR this was based on.

2018-06-01 05:44 UTC, vikram-redhat commented
Removing dedicated and online labels as it doesn't apply to them.