OCP 4.18 Release Notes for P/Z
openshift/openshift-docs pull request #86406
Opened 2024-12-18 06:13 UTC by alishaIBM

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

2025-01-15 12:06 UTC, SNiemann15 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Compliance/SP Operator Support for Multi-Arch Compute Environments
@prb112 Will this be ready for the 4.18 GA or release async after GA? 

cc @werled

2025-01-15 13:53 UTC, prb112 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Compliance/SP Operator Support for Multi-Arch Compute Environments
release async

2025-01-21 01:41 UTC, prb112 approved these changes
/lgtm 
Power aspects look good

2025-01-23 11:51 UTC, SNiemann15 requested changes

2025-01-23 11:51 UTC, SNiemann15 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Agent-based Installer day 2
```suggestion
* Adding compute nodes to on-premise clusters
```

2025-01-23 11:51 UTC, SNiemann15 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Agent-based Installer Post-Installation add workers
```suggestion
* Adding compute nodes to on-premise clusters
```
@alishaIBM @prb112 I would use the wording x86 has used in the [4.17 RNs](https://docs.openshift.com/container-platform/4.17/release_notes/ocp-4-17-release-notes.html#ocp-4-17-adding-nodes-to-on-prem_release-notes)

The underlying technology utilizes the ABI, however users don't need to know how it's implemented. Any cluster on the supported platforms can use this method regardless of whether or not the cluster was installed using the ABI.

2025-01-23 11:51 UTC, SNiemann15 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Agent-based Installer Post-Installation add workers
Also in the supported features table please add a new row before Agent-based Installer

```
|Adding compute nodes to on-premise clusters
|Supported
|Supported
```

2025-01-23 14:25 UTC, prb112 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Agent-based Installer Post-Installation add workers
Contextually, shouldn't it mention agent/assisted installers?

2025-01-23 17:23 UTC, SNiemann15 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Agent-based Installer Post-Installation add workers
> Contextually, shouldn't it mention agent/assisted installers? I only noticed going back and reading it.

I would prefer staying with what @skopacz1 told me , that the user doesn't need to know how it's implemented.

2025-01-23 17:42 UTC, skopacz1 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Agent-based Installer Post-Installation add workers
FYI that this preference for just mentioning the functionality while leaving out the underlying tech comes from @andfasano, who originally implemented the node-adding feature

2025-01-24 08:15 UTC, werled commented on release_notes/ocp-4-18-release-notes.adoc
> +* Agent-based Installer Post-Installation add workers
Since this is the way it's communicated for other platforms, it makes sense to me to communicate it without explicit note of the underlying tech. Also helps with not confusing it with the way the cluster was initially installed, which is not relevant for this feature.

2025-01-27 13:06 UTC, alishaIBM commented on release_notes/ocp-4-18-release-notes.adoc
> +* Agent-based Installer Post-Installation add workers
Thank you all. Updated as per the above discussion.

2025-01-28 13:14 UTC, SNiemann15 commented
@alishaIBM  Please remove the TP from `Hosted control planes (Technology Preview)` in the features table. line 178.

2025-01-30 07:20 UTC, alishaIBM commented
/assign @prb112 @werled

2025-01-30 12:51 UTC, prb112 commented on release_notes/ocp-4-18-release-notes.adoc
> +//* Additional Hardware Configurations for ABI/AI/HCP on P
```suggestion
//* Additional Hardware Configurations for ABI/AI/HCP on P
```

What does the slash mean?

2025-01-30 12:52 UTC, prb112 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Adding compute nodes to on-premise clusters
```suggestion
* Adding compute nodes to on-premise clusters
```

This existed in prior versions. I think the context is everything as to why clients would care. The Agent/Assisted context is very important here.

2025-01-30 12:52 UTC, prb112 commented on release_notes/ocp-4-18-release-notes.adoc
> +|Adding compute nodes to on-premise clusters
It's always been supported. This is with the context of Agent/Assisted.

2025-01-30 12:53 UTC, prb112 requested changes
I think the context for adding compute is very important. Otherwise It should be excluded from what's new.

2025-01-30 15:40 UTC, SNiemann15 commented on release_notes/ocp-4-18-release-notes.adoc
> +//* Additional Hardware Configurations for ABI/AI/HCP on P
The slash means it's commented out. At least for Z we decided not to mention this as it's not really a feature.

2025-01-30 15:45 UTC, SNiemann15 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Agent-based Installer Post-Installation add workers
> FYI that this preference for just mentioning the functionality while leaving out the underlying tech comes from @andfasano, who originally implemented the node-adding feature

@prb112 see above

2025-01-30 16:53 UTC, prb112 commented on release_notes/ocp-4-18-release-notes.adoc
> +//* Additional Hardware Configurations for ABI/AI/HCP on P
ack

2025-01-30 16:53 UTC, prb112 commented on release_notes/ocp-4-18-release-notes.adoc
> +//* Additional Hardware Configurations for ABI/AI/HCP on P
I'm leaning towards commenting it out as you mention. I think it's too confusing to mention.

2025-02-07 12:24 UTC, SNiemann15 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Adding compute nodes to on-premise clusters
```suggestion
* Adding compute nodes to on-premise clusters using `oc`
```

2025-02-07 12:25 UTC, SNiemann15 commented on release_notes/ocp-4-18-release-notes.adoc
> +* Adding compute nodes to on-premise clusters
```suggestion
* Adding compute nodes to on-premise clusters using `oc`
```

2025-02-07 13:06 UTC, prb112 approved these changes
/lgtm

2025-02-10 06:54 UTC, alishaIBM commented on release_notes/ocp-4-18-release-notes.adoc
> +//* Additional Hardware Configurations for ABI/AI/HCP on P
Removed the commented line.

2025-02-10 06:54 UTC, alishaIBM commented on release_notes/ocp-4-18-release-notes.adoc
> +* Adding compute nodes to on-premise clusters
Updated as suggested above.

2025-02-10 06:54 UTC, alishaIBM commented on release_notes/ocp-4-18-release-notes.adoc
> +* Adding compute nodes to on-premise clusters
Updated as suggested above.

2025-02-10 08:29 UTC, SNiemann15 approved these changes

2025-02-11 15:21 UTC, alishaIBM commented
/label peer-review-needed

2025-02-11 16:33 UTC, ShaunaDiaz reviewed
little comments otherwise LGTM

2025-02-11 16:33 UTC, ShaunaDiaz commented on release_notes/ocp-4-18-release-notes.adoc
> +xref:../installing/installing_ibm_z/preparing-to-install-on-ibm-z.adoc#preparing-to-install-on-ibm-z[Preparing to install on {ibm-z-title} and {ibm-linuxone-title}].
```suggestion
xref:../installing/installing_ibm_z/preparing-to-install-on-ibm-z.adoc#preparing-to-install-on-ibm-z[Installation methods].
```
the actual title of the section

2025-02-11 16:33 UTC, ShaunaDiaz commented on release_notes/ocp-4-18-release-notes.adoc
> +* Adding compute nodes to on-premise clusters using `oc`
```suggestion
* Adding compute nodes to on-premise clusters using {oc-first}
```
This looks like the first mention of the OpenShift CLI in the release notes as far as I can see by searching.

2025-02-12 11:05 UTC, prb112 approved these changes
/lgtm

2025-02-12 13:55 UTC, SNiemann15 commented on release_notes/ocp-4-18-release-notes.adoc
> +xref:../installing/installing_ibm_z/preparing-to-install-on-ibm-z.adoc#preparing-to-install-on-ibm-z[Preparing to install on {ibm-z-title} and {ibm-linuxone-title}].
Agree we changed the title with the restructuring.

2025-02-12 14:08 UTC, SNiemann15 commented
@alishaIBM I just had a meeting with @holgwolf. We also need to update the Hypershift Operator entry from TP to supported for both Power and Z (lines 329/330) and for IBM Z we need to change the OpenShift virtualization entry to Technology Preview (line 210)
fyi: @prb112

2025-02-13 13:34 UTC, SNiemann15 commented
> > @alishaIBM I just had a meeting with @holgwolf. We also need to update the Hypershift Operator entry from TP to supported for both Power and Z (lines 329/330) and for IBM Z we need to change the OpenShift virtualization entry to Technology Preview (line 210) fyi: @prb112
> 
> Updated the PR as per the above suggestion. Thanks. cc: @SNiemann15 @prb112
/lgtm

2025-02-13 13:51 UTC, prb112 reviewed
/lgtm

2025-02-14 08:05 UTC, alishaIBM commented
/label merge-review-needed

2025-02-14 08:41 UTC, xenolinux reviewed
I have one comment but probably not worth holding the merge for
Hence LGTM merging

2025-02-14 08:41 UTC, xenolinux commented on release_notes/ocp-4-18-release-notes.adoc
> +This release introduces support for the following features on {ibm-z-name} and {ibm-linuxone-name}:
```suggestion
This release introduces support for the following feature on {ibm-z-name} and {ibm-linuxone-name}:
```

- Use singular `feature`:  cause there is only one feature.

2025-02-14 08:42 UTC, merged