Brief note about timeouts in the haproxy router
openshift/openshift-docs pull request #8900
Opened 2018-04-25 12:16 UTC by JacobTanenbaum

Some of the timeouts that we allow cluster administrators to set
interact with others that we expose or in some cases don't expose.
Causing haproxy to actually timeout as the sum of those timeouts

Ex.

setting
ROUTER_SLOWLORIS_HTTP_KEEPALIVE to 10s

because we set "tcp-request inspect-delay" to 5s

ROUTER_SLOWLORIS_HTTP_KEEPALIVE triggers and then the inspect-delay
waits to timeout so the connection closes after 15s

2018-04-26 18:57 UTC, JacobTanenbaum commented
@bfallonf PTAL

not sure if I should provide a specific example or not

2018-04-26 19:46 UTC, akostadinov commented
It's good to have this specific example because it is easy to hit. Also (even more useful) to link to the relevant HAProxy documentation where more detailed information can be found.

2018-04-27 14:30 UTC, knobunc requested changes

2018-04-27 14:30 UTC, knobunc commented on architecture/topics/router_environment_variables.adoc
> +Some of the timeouts that we expose interact casuing the total timeout to be longer then specified.
Should we say:

e.g. ROUTER_SLOWLORIS_HTTP_KEEPALIVE  adjusts "timeout http-keep-alive" , but haproxy will waits on the "tcp-request inspect-delay" which we set to 5s.

2018-04-30 14:01 UTC, knobunc approved these changes
/lgtm

2018-04-30 14:17 UTC, akostadinov commented
while on it, is `tcp-request inspect-delay` adjustable or is it presently hardcoded?

2018-04-30 19:11 UTC, JacobTanenbaum commented
@akostadinov tcp-request inspect-delay is hardcoded

2018-04-30 21:45 UTC, akostadinov commented
Thank you. I think we need to make these parameters configurable. 5 seconds is a pretty big value. No need to wait for people with big installations to request that. But this is for another forum.

2018-05-03 04:59 UTC, bfallonf commented
@JacobTanenbaum Thanks, this is good info to have in the docs.

I'm concerned people might not see it where it is, but I can't see a better location. Below is a section called Timeouts, that has almost literally no information. Would it be better to group the relevant timeout variable there? I don't mind making these changes in a followup PR if necessary.

2018-05-07 12:36 UTC, JacobTanenbaum commented
@bfallonf are you recommending making a section about timeouts? I don't see one

2018-05-08 22:48 UTC, akostadinov commented
@JacobTanenbaum , you can refer to the `Note` from the `ROUTER_SLOWLORIS_HTTP_KEEPALIVE` parameter description (such that users notice it). For me this would resolve the immediate issue. I don't mind if options are grouped better if needed though.

2018-05-11 03:37 UTC, bfallonf commented
I spoke to @JacobTanenbaum over email that it'd be good to see what grouping together the timeout variables would look like. I'll merge this PR, then make a followup giving that a go. Thanks, all.

Also, I'll label this for 3.9 because that's the version the BZ above is set to. If I'm wrong, please correct me.

2018-05-11 03:37 UTC, merged

2018-05-11 03:38 UTC, bfallonf commented
/cherrypick enterprise-3.9

2018-05-11 03:38 UTC, bfallonf commented
/cherrypick enterprise-3.10